### ISSUE TITLE
Modulo statistiche

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#10]
- Fatturato
- Entrate/Uscite
- Articoli più venduti
- Numero di interventi mensili
- Clienti top

**Comment by Dasc3er** [comment]
Qualche framework in particolare come idea di base?
Se si vuole, una possibilità è: https://github.com/chartjs/Chart.js

**Comment by loviuz** [comment]
non male come libreria per i grafici... se ne trovo altre le segnalo qui

**Comment by Dasc3er** [comment]
@loviuz Considerando l'effettiva introduzione del modulo con le funzioni sopra indicate, questa issue può essere considerata completa per il momento?

**Comment by loviuz** [comment]
volevo apportare qualche piccola miglioria grafica, perchè i grafici mi sembravano molto grandi, anche con monitor 16:9 con alta risoluzione. mi risultavano un po' dispersivi. faccio qualche prova...

**Comment by gabrielepiccinnu** [comment]
@loviuz pensavo ad una soluzione di questo tipo

![image](https://user-images.githubusercontent.com/25913492/31538560-3edbe3e4-b006-11e7-90fb-f0a17a1493e7.png)

**Comment by loviuz** [comment]
accorciati in altezza, e cambiato il primo grafico con fatturato/acquisti. il secondo, invece che per stato intervento, è ora per tipo intervento. lo stato degli interventi precedenti tenderà a diventare sempre "fatturato" o "completato", per cui poco utile. ora vengono usati dei colori random per i tipi intervento perchè non hanno un colore come gli stati.
