### ISSUE TITLE
widget "promemoria contratti da pianificare" [OSM 2.4.27]

### ISSUE THREAD

**Issue by mars984** [devcode-it/openstamanager#1000]
## Comportamento richiesto

Cliccare sul widget e vedere relativo menù 

## Comportamento attuale

Clicco sul widget ma non succede nulla

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause? 

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Andare sul modulo dashboard
2. Cliccare sul widget promemoria contratti da pianificare
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
21-11-25 10:14:15] Logs.ERROR: Class 'Carbon' not found {"code":0,"message":"Class 'Carbon' not found","file":"/var/www/html/crm/plugins/pianificazione_interventi/widgets/promemoria_da_pianificare.php","line":28,"trace":"#0 {main}"}
{"url":"/crm/plugins/pianificazione_interventi/widgets/promemoria_da_pianificare.php","ip":"192.***.***.***","http_method":"GET","server":"192.***.***.***","referrer":"http://192.***.***.***/crm/controller.php?id_module=1","uid":"734b51b"}

```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Dashboard
* Versione del progetto: 2.4.27
* Versione PHP: 7.2.30
* Tipo di server: Debian 8.11

**Comment by mars984** [comment]
problema risolto aggiungendo nel file /var/www/html/crm/plugins/pianificazione_interventi/widgets/promemoria_da_panificare.php "use Carbon\Carbon;"

**Comment by Dasc3er** [comment]
@mars984 Potrebbe essere in questo caso che il file non sia stato aggiornato correttamente dalla procedura di aggiornamento, probabilmente per un problema di permessi all'estrazione dall'archivio ZIP.
Puoi verificare se ci sono problemi con i file dal modulo Aggiornamenti, tramite le funzionalità di Controllo aggiunte nelle ultime 10-15 versioni (>2.4.10 credo).
