### ISSUE TITLE
Chiusura widget non funzionante

### ISSUE THREAD

**Issue by humarcoDZ** [devcode-it/openstamanager#1001]
## Comportamento richiesto

Disabilitare il widget quando si clicca sulla X, in qualunque schermata

## Comportamento attuale

Refresh della pagina, non succede nulla.

## Possibile soluzione

rinominare l'op per disabilitare il widget in "disabilita-widget" o rimettere (ho notato che nelle versioni precedenti alla 2.4.24 c'era) il case "disable_widget". (edit: il case in questione si trova in modules/stato_servizi/actions.php)

## Passi per riprodurre il comportamento

1. cliccare sulla X del widget

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Dashboard
* Versione del progetto: 2.4.26
* Versione PHP: 7.3.31
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @humarcoDZ,
Il problema è stato risolto nella release 2.4.28 del 13-12-21.
Grazie per la segnalazione!
