### ISSUE TITLE
(SOLVED) Installazione interrotta : cartella "Vendor" 

### ISSUE THREAD

**Issue by orionssoftware** [devcode-it/openstamanager#1003]
Bellissimo progetto,
ho tutta l'intenzione di studiarlo meglio, installandolo sul mio spazioweb php/mysql.
Sicuramente però sbaglio qualcosa poiché non riesco ad installarlo, me tapino.

Dopo aver scompattato lo zip e posizionato correttamente la cartella nello spazio pubblico dell'hosting, punto via web alla cartella e ricevo sistematicamente questa risposta con tutte le versioni di OpenSta che ho testato.

**Warning: Cannot modify header information - headers already sent by (output started at /home/mhd-01/www.orionssoftware.org/htdocs/sta/core.php:1) in /home/mhd-01/www.orionssoftware.org/htdocs/sta/core.php on line 21**

**Warning: require_once(/home/mhd-01/www.orionssoftware.org/htdocs/sta/vendor/autoload.php): failed to open stream: No such file or directory in /home/mhd-01/www.orionssoftware.org/htdocs/sta/core.php on line 42**

Effettivamente, cercando nella directory base dell'applicazione non trovo la cartella "Vendor", ma non so se questo sia importante.
Debbo cambiare il servizio di hosting? 
Uso [questo](https://www.tophost.it/hosting/) da anni senza particolari problemi ovviamente con architettura php/mysql.

Ho fatto la controprova su un hosting php/mysql gratuito ed ho ottenuto lo stesso risultato:
**Fatal error: require_once(): Failed opening required '/membri/invitalia/openstamanager-2.4.27/vendor/autoload.php' (include_path='.:') in /membri/invitalia/openstamanager-2.4.27/core.php on line 42**

Ho provato diverse release prendendole da [qui](https://github.com/devcode-it/openstamanager/releases). 
Pescando a caso nelle varie versioni e nelle 3 estensioni (zip, tar) non trovo la cartella "vendor". Sbaglio qualcosa?

A disposizione.
Grazie.

* Modulo:
* Versione del progetto: 2.4.27
* Versione PHP: 7.3.18
* Tipo di server: Spazio Web MySQL/PHP

**Comment by loviuz** [comment]
Ciao! La cartella vendor ed altre sono mancanti se scarichi lo zip del repository, poiché vengono generate usando i comandi scritti nel README, infatti sono librerie esterne che vengono scaricate tramite yarn e composer. Se scarichi invece lo zip da releases trovi i file zip completi e installabili. Prova cosí!

**Comment by orionssoftware** [comment]
Ohhhh...caro Loviuz, finalmente è partito! Il pacchetto completo da appoggiare in hosting è quello più sostanzioso con l'icona di un pacchetto (circa 18MB). Li ho provati tutti, ma evidentemente questo lo avevo lasciato indietro :-1:  GRAZIE. L'installazione è andata a buon fine!
