### ISSUE TITLE
Gestione automatica autofattura IVA

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1006]
## Comportamento richiesto

Gestione automatica di autofatture di integrazione per acquisti UE/extra-UE con IVA da rettificare.

## Comportamento attuale

Lo scenario non è supportato (impossibile selezionare come caso speciale cedente e cessionario)

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: fatture
* Versione del progetto: 2.4.28
* Versione PHP: 7.2
* Tipo di server: Apache Aruba

**Comment by Pek5892** [comment]
Disponibile dalla versione 2.4.34
https://docs.openstamanager.com/v/2.4.34/guide/esempi/autofattura
