### ISSUE TITLE
Elenco stampato male in esportaizone PDF da lista fatture

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1007]
## Comportamento richiesto

Selezionando le fatture e esportando il pdf viene esportato un elenco completo come da parametri e selezioni.

## Comportamento attuale

Il pdf esportato è parziale per via della probabile selezione errata della pagina verticale anziché orizzontale come da screenshot.
![image](https://user-images.githubusercontent.com/392762/148995823-27be79c8-cbe6-46e8-af51-1fa7c60538ae.png)

## Possibile soluzione

Impostare la pagina orizzontale. Provo a inviare un pull request relativo a breve, non appena termino i test.

## Passi per riprodurre il comportamento

1. apertura modulo fatture di vendita
2. selezione di alcune fatture
3. clic su Esporta -> PDF

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: fatture
* Versione del progetto: 2.4.28
* Versione PHP: 7.2
* Tipo di server: Apache (Aruba)

**Comment by marcus905** [comment]
Guardando alcune doc delle librerie datatables e la comunicazione con pdfmake, dovrebbe essere sufficiente aggiungere qui:

https://github.com/devcode-it/openstamanager/blob/653c02608c3390f352091429e0f90ab7c832e587/assets/src/js/functions/datatables.js#L261

`
...
      orientation: 'landscape',
...
`

ma non riesco a testarlo perché sul PC oggi non mi funziona il build system.

Se qualcuno può farlo gliene sarei grato, a seguire eventualmente preparo un pull request.

**Comment by marcus905** [comment]
PS: altro piccolo bug relativo su queste stampe sarebbe l'allineamento delle cifre a sinistra mentre dovrebbe essere a destra, solo che non credo che ci sia una soluzione agevole per quello.

**Comment by loviuz** [comment]
@marcus905 grazie per il contributo. La scelta della stampa orizzontale o verticale andrebbe resa configurabile al di fuori da datatables, a meno che non abbia senso lasciarla fissa in orizzontale. Dopotutto la stampa di tabelle con diverse colonne non ci sta facilmente in verticale.
Riguardo gli importi invece credo sia un po' piú complesso. Non é usata moltissimo questa esportazione, probabilmente per questo non siamo mai intervenuti su questa parte, ma se riesci a contribuire tu meglio :-)
