### ISSUE TITLE
ADD_ARTICOLO - Manca nei contratti e nei preventivi

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#101]
Deve essere possibile inserire un articolo nei contratti e nei preventivi
![image](https://user-images.githubusercontent.com/34273200/34638725-0dee58a2-f2d2-11e7-99f2-8631244e0690.png)

**Comment by fpsoftware** [comment]
@fgambarelli puoi fare un esempio reale per questa necessità? 
Nei preventivi inoltre c'è giá questa possibilitá e le logiche tra contratti e preventivi sono molto simili...

**Comment by fgambarelli** [comment]
Ideale sarebbe che in tutti e tre gli oggetti (preventivi/fatture/contratti) ci fossero gli stessi pulsanti, per congruenza e chiarezza:
nel preventivi  con AGGIUNGI RIGA - si aggiungere solo dagli articoli, mentre nei contratti con AGGIUNGI RIGA si aggiunge una riga generica.
In un Contratto è indispensabile poter aggiungere anche dei prodotti/pacchetti che vengono registrati come articoli , in modo da avere la distinzione di che cosa viene dato come contratto (MANUTENZIONE, MANUTENZIONE STRAORDINARIA, MANUTENZIONE TERZO RESPONSABILE) ma soprattutto registrandoli come articolo è possibile avere le statistiche di vendita e prezzo per diversi clienti.

**Comment by fpsoftware** [comment]
Riguardo i preventivi il select Articolo nella finestra AGGIUNGI RIGA non è obbligatorio ed è quindi possibile inserire anche una riga generica scrivendo direttamente descrizione, prezzo, etc... 

Concordo però sulla necessità di inserire Articoli che in realtà sono servizi, è stato chiesto parecchie volte come personalizzazione, solitamente aggiungiamo un flag "Servizio" sulla scheda articolo, potrebbe sicuramente diventare una funzionalità base.

E corcordo anche sul fatto che gestendo i servizi come articoli è poi possibile avere statistiche su di essi.

**Comment by Dasc3er** [comment]
Per rendere **Preventivi** e **Contratti** conformi con i restanti moduli si potrebbe separare allo stesso modo l'inserimento di righe e articoli...
Procediamo in questo modo per la 2.4?

**Comment by loviuz** [comment]
Concordo

**Comment by lucasalva87** [comment]
Sì
