### ISSUE TITLE
Versione 2.4.30 richiede PHP >=7.4

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1011]
## Comportamento richiesto

Compatibilità con PHP 7.2 o avviso upgrade richiede la 7.4

## Comportamento attuale

L'aggiornamento richiede la 7.4 senza avviso. Post upgrade compare:

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".`

## Possibile soluzione

Avvisare in caso di upgrade nelle release notes.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Aggiornare da v2.4.29 su server con PHP <7.4

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto: V2.4.30
* Versione PHP: <7.4
* Tipo di server: es. Aruba Apache default

**Comment by loviuz** [comment]
Ciao @marcus905, ho appena aggiornato il README aggiungendo 2 tabelle con le versioni di PHP e MySQL supportate, inserendo anche la data di fine mantenimento di ogni versione. Grazie del suggerimento!
