### ISSUE TITLE
Stampe consuntivo - Riepilogo interventi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1013]
## Comportamento richiesto

Nelle stampe di consuntivo ( Preventivo, Ordine, Contratto ) e nella stampa riepilogo interventi.
in Sessioni riporta il nome del tecnico e in piccolo tra parentesi il tipo di attività svolta.

riteniamo molto utile l'inverso, sia per noi ma anche per il cliente che ha modo di comprendere meglio le attività svolte più che il tecnico che le ha eseguite.

## Comportamento attuale

![Sessioni](https://user-images.githubusercontent.com/75281007/152790114-c0465469-e599-44fa-92d1-c6fb9da1a67f.jpg)

## Possibile soluzione

alla riga 80 del file piece.php inversione del campo.

![originale](https://user-images.githubusercontent.com/75281007/152792679-2f802e81-2cdd-432f-91c7-182f1dd134de.jpg)

![modificato](https://user-images.githubusercontent.com/75281007/152792692-d703343c-7b6f-47b3-87ed-6798bfc4944c.jpg)

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
Quella che richiedi sembra più una modifica relativa ad un'esigenza specifica, non potendo gestire tutte le casistiche la stampa di default è impostata così.

**Comment by sajotrei** [comment]
Ciao @Pek5892,
grazie per il riscontro.
sinceramente è più un suggerimento 😉 in linea di principio è più logico, in quanto al cliente interessa più il tipo di attività  che chi la svolta.

comunque valutate voi.

...noi abbiamo già applicato la modifica sul nostro OSM ☺️
