### ISSUE TITLE
Articolo importando XML fattura di acquisto

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1020]
## Comportamento richiesto

Quando si importa un XML fattura di acquisto, e selezioniamo la **creazione degli articoli** sarebbe molto utile poter **"deselezionare" le righe che non si vuole creare come articolo.**

## Comportamento attuale

praticamente adesso il sistema crea un articolo quando esiste in fattura una riga con cod. articolo, ma esistono anche righe con cod. articoli fornitore che non servono.

ES: capita che il fornitore inserisca una riga di sconto con codice articolo e questa andrà a fine a magazzino anche se non è un articolo.

## Possibile soluzione

creare una sorta di flag per riga per escludere la creazione di quel campo.

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by MatteoPistorello** [comment]
Ciao @sajotrei,
abbiamo previsto la possibilità di selezionare/deselezionare le righe da creare come articoli in fase di importazione della fattura elettronica, ecco il commit: https://github.com/devcode-it/openstamanager/commit/fae3f5da2fe43f6a7a57eaa2490c62478bc42861
