### ISSUE TITLE
Problema creazione anagrafiche dopo la ridenominazione dei conti

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#1021]
Se il conto **110 Crediti clienti e crediti diversi** viene rinominato o rimosso, quando si creano nuove anagrafiche cliente si ottiene un errore. Lo stesso per il conto **240 Debiti fornitori e debiti diversi** per le anagrafiche fornitore.

Si potrebbe gestire un'impostazione per definire qual è il conto di livello 2 sotto cui creare il conto cliente e il conto fornitore, togliendo così il vincolo dal nome del conto.

**Comment by MatteoPistorello** [comment]
Gestito con questo commit: https://github.com/devcode-it/openstamanager/commit/af7eb19567578899da95c5cd7e382d58a7aa792e
