### ISSUE TITLE
BUG Vista fatture di vendita

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1024]
Ho notato che emettendo una nota di credito, nell'elenco fatture di vendita i totali sono errati.
Il problema sta nel fatto che nella fattura da cui ho generato la NC c'erano degli sconti. Il totale nella NC è corretto, ma nelle viste gli sconti vengono sommati, ovvero:

Totale NC = - totale fattura +(-sconti), quindi il problema risiede nelle query all'interno della vista dei campi "totale ivato" e "netto a pagare":

(righe.totale + `co_documenti`.`rivalsainps` + `co_documenti`.`iva_rivalsainps`) * IF(co_tipidocumento.reversed, -1, 1)

(righe.totale + `co_documenti`.`rivalsainps` + `co_documenti`.`iva_rivalsainps` - `co_documenti`.`ritenutaacconto` - `co_documenti`.`sconto_finale`) * (1 - `co_documenti`.`sconto_finale_percentuale` / 100) * IF(co_tipidocumento.reversed, -1, 1)

Non ho ancora verificato se si verifica anche nelle fatture di vendita, ma se il calcolo è errato, il problema dovrebbe verificarsi anche qui.

* Modulo: Vista fatture
* Versione del progetto: 2.4.30

**Comment by MatteoPistorello** [comment]
Ciao @idraulicadueci, ho verificato e la visualizzazione dei totali nell'elenco delle fatture è corretto, era presente un problema di visualizzazione nei totali delle righe nella schermata di modifica delle fatture di vendita per quanto riguarda lo sconto finale ed è stato risolto con i seguenti commit: https://github.com/devcode-it/openstamanager/commit/a963790440bfad279d7dcf91bedb178cca9ca985    https://github.com/devcode-it/openstamanager/commit/7d9d25507162be7d17e94844d597776306a94b48

**Comment by idraulicadueci** [comment]
Ciao, a me continua a verificarsi il problema. come detto sopra ho una nota di credito generata da una fattura che ha degli sconti, e nel trasformarla in NC gli sconti vengono sottratti. Per somma algebrica lo sconto viene sommato, anziché sottratto. Credo che il problema stia proprio nel tipo di operazione che viene fatta.

**Comment by MatteoPistorello** [comment]
Ciao, riusciresti ad inviare la query risultante del modulo così da verificare nel dettaglio? Grazie

**Comment by idraulicadueci** [comment]
SELECT IF(`dup`.`numero_esterno` IS NULL, '', 'red') AS '_bg_', co_documenti.id AS 'id', an_anagrafiche.idanagrafica AS 'idanagrafica', co_tipidocumento.descrizione AS 'Tipo', IF(co_documenti.numero_esterno='', co_documenti.numero, co_documenti.numero_esterno) AS 'Numero', co_documenti.data AS 'Data', an_anagrafiche.ragione_sociale AS 'Ragione sociale', (SELECT CONCAT(co_banche.nome, ' - ' , co_banche.iban) AS descrizione FROM co_banche WHERE co_banche.id = id_banca_azienda) AS 'Banca', righe.totale_imponibile * IF(co_tipidocumento.reversed, -1, 1) AS 'Totale', co_statidocumento.descrizione AS 'icon_title_Stato', dir AS 'dir', (righe.totale + `co_documenti`.`rivalsainps` + `co_documenti`.`iva_rivalsainps`) * IF(co_tipidocumento.reversed, -1, 1) AS 'Totale ivato', (righe.totale + `co_documenti`.`rivalsainps` + `co_documenti`.`iva_rivalsainps` - `co_documenti`.`ritenutaacconto` - `co_documenti`.`sconto_finale`) * (1 - `co_documenti`.`sconto_finale_percentuale` / 100) * IF(co_tipidocumento.reversed, -1, 1) AS 'Netto a pagare', `fe_stati_documento`.`icon` AS 'icon_FE', `fe_stati_documento`.`descrizione` AS 'icon_title_FE', co_statidocumento.icona AS 'icon_Stato', IF(`email`.`id_email` IS NOT NULL, 'fa fa-envelope text-success', '') AS 'icon_Inviata', IF(`email`.`id_email` IS NOT NULL, 'Inviata via email', '') AS 'icon_title_Inviata' FROM `co_documenti`
     LEFT JOIN `an_anagrafiche` ON `co_documenti`.`idanagrafica` = `an_anagrafiche`.`idanagrafica`
     LEFT JOIN `co_tipidocumento` ON `co_documenti`.`idtipodocumento` = `co_tipidocumento`.`id`
     LEFT JOIN `co_statidocumento` ON `co_documenti`.`idstatodocumento` = `co_statidocumento`.`id`
     LEFT JOIN `fe_stati_documento` ON `co_documenti`.`codice_stato_fe` = `fe_stati_documento`.`codice`
     LEFT JOIN (
         SELECT `iddocumento`,
                SUM(`subtotale` - `sconto`) AS `totale_imponibile`,
                SUM(`subtotale` - `sconto` + `iva`) AS `totale`
         FROM `co_righe_documenti`
         GROUP BY `iddocumento`
     ) AS righe ON `co_documenti`.`id` = `righe`.`iddocumento`
     LEFT JOIN (
         SELECT `numero_esterno`, `id_segment`
         FROM `co_documenti`
         WHERE `co_documenti`.`idtipodocumento` IN(SELECT `id` FROM `co_tipidocumento` WHERE `dir` = 'entrata') AND (`co_documenti`.`data` BETWEEN '2021-01-01' AND '2022-12-31 23:59:59') AND `numero_esterno` != ''
         GROUP BY `id_segment`, `numero_esterno`
         HAVING COUNT(`numero_esterno`) > 1
     ) dup ON `co_documenti`.`numero_esterno` = `dup`.`numero_esterno` AND `dup`.`id_segment` = `co_documenti`.`id_segment`
     LEFT JOIN (
         SELECT `zz_operations`.`id_email`, `zz_operations`.`id_record`
         FROM `zz_operations`
                INNER JOIN `em_emails` ON `zz_operations`.`id_email` = `em_emails`.`id`
                INNER JOIN `em_templates` ON `em_emails`.`id_template` = `em_templates`.`id`
                INNER JOIN `zz_modules` ON `zz_operations`.`id_module` = `zz_modules`.`id`
         WHERE `zz_modules`.`name` = 'Fatture di vendita' AND `zz_operations`.`op` = 'send-email'
         GROUP BY `zz_operations`.`id_record`
     ) AS `email` ON `email`.`id_record` = `co_documenti`.`id`
WHERE 1=1 AND `dir` = 'entrata'    AND (`co_documenti`.`data` BETWEEN '2021-01-01' AND '2022-12-31 23:59:59')
HAVING 2=2
ORDER BY `co_documenti`.`data` DESC, CAST(`co_documenti`.`numero_esterno` AS UNSIGNED) DESC

**Comment by loviuz** [comment]
ciao @idraulicadueci, ti risulta risolto questo problema? credo sia molto datato e già risolto probabilmente

**Comment by idraulicadueci** [comment]
ciao @loviuz a me continua a dare il problema. Nel modulo tutto ok, perché gli importi sono tutti positivi e quindi lo sconto viene sottratto correttamente al netto (+NETTO-SCONTO). 
Il problema si presenta nelle viste (solo quando emetto una nota di credito su una fattura che contiene uno sconto). Guardando infatti la query, noto che l'operazione che viene fatta algebricamente è -NETTO-SCONTO, e quindi i due valori si sommano.
Per replicare il bug è necessario creare una fattura con degli sconti e poi da questa creare la nota di credito.

**Comment by Pek5892** [comment]
![immagine](https://user-images.githubusercontent.com/102604205/182785741-22160c6e-e803-43ea-9f65-1a74e177bf2d.png)
Fattura:
![immagine](https://user-images.githubusercontent.com/102604205/182785783-952f0d45-9a78-43b9-bb7f-bfef293e33e3.png)
Nota di credito:
![immagine](https://user-images.githubusercontent.com/102604205/182785816-cb6d4760-c76d-48c3-a856-04af3d2b5839.png)
Confermo che il problema è stato risolto nelle versioni precedenti

**Comment by idraulicadueci** [comment]
Salve a tutti, il problema sulle nuove fatture non si presenta, resta comunque su quelle precedenti ai commit https://github.com/devcode-it/openstamanager/commit/a963790440bfad279d7dcf91bedb178cca9ca985 e https://github.com/devcode-it/openstamanager/commit/7d9d25507162be7d17e94844d597776306a94b48
Il problema l'ho riscontrato a livello di database, cioè nella tab. co_tipidocumento ho 2 record per la nota di credito (id. 7 e 9). Però modificando l'id da 9 a 7 poi non vedo più la nota di credito in questione nell'elenco, quale altro parametro devo modificare per riallineare il database? o meglio, quale query devo lanciare per fare la correzione? grazie

**Comment by Pek5892** [comment]
Potresti controllare la direzione dei due record 7 e 9 (nota di credito)? dovrebbero essere una in uscita e l'altra in entrata.

**Comment by idraulicadueci** [comment]
ciao @Pek5892, avevo già provato, ma stranamente non vedo la nota di credito nell'elenco, sicuramente c'è qualche altro parametro che devo modificare per riallineare il database.

**Comment by Pek5892** [comment]
Non riusciamo a formulare una query generica per riallineare il database essendoci stati nelle varie versioni bug diversi.
Per ricevere assistenza dedicata potresti valutare in caso l'acquisto di un pacchetto di assistenza :)
