### ISSUE TITLE
Cambio voce Tecnico/i in voce più generica

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1025]
## Comportamento richiesto

Riteniamo che sarebbe utile **modificare la voce Tecnico/i** nei vari punti del gestionale, con altro termine 
**es. Risorsa**, Collaboratore, Personale, o simili 

al fine di renderlo più generico e così applicabile anche in altri contesti al di fuori della sola assistenza tecnica.
le dinamiche del software rimarrebbero le medesime.

## Comportamento attuale

![Crea attività](https://user-images.githubusercontent.com/75281007/155167829-e9b4bf9c-949b-4506-a43f-daec77824c32.jpg)

![1](https://user-images.githubusercontent.com/75281007/155167761-a0396677-0156-4ff0-b4bc-f4b0e8b2def3.jpg)
![2](https://user-images.githubusercontent.com/75281007/155167763-98d995d2-2f96-48c6-a0f8-4c89080951bb.jpg)
![3](https://user-images.githubusercontent.com/75281007/155167766-6d6c995b-4063-45dc-9700-fdb4ddb7e3c9.jpg)
![4](https://user-images.githubusercontent.com/75281007/155167768-eaec064c-0519-4c80-bafd-946da7b7bfa5.jpg)
![5](https://user-images.githubusercontent.com/75281007/155167771-a86841f4-c0f4-4d5e-9f51-fc386346649e.jpg)
![6](https://user-images.githubusercontent.com/75281007/155167775-7d653a71-397d-432e-ae41-01cd2cbf5d6d.jpg)
![in dashboard](https://user-images.githubusercontent.com/75281007/155167779-8b1067ae-e68e-4ab1-b026-4c7811ea5e46.jpg)

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
è possibile applicare questa modifica ? almeno nella parte visibile dall'utente finale.

**Comment by sajotrei** [comment]
Ciao, capisco che di fatto il programma è specifico per le assistenze.

ma se si riuscisse ad applicare questa modifica, o comunque qualcosa del genere, renderebbe il gestionale applicabile anche in altri contesti.

**Comment by Pek5892** [comment]
Ciao @sajotrei, questa è una personalizzazione che potremmo eventualmente valutare nel caso specifico

**Comment by sajotrei** [comment]
Ciao, @lucasalva87 @loviuz 

abbiamo suggerito questa modifica non per un caso specifico, ma per rendere **più "aperto" OSM anche ad altri settori**, come l'edilizia, ecc...

vi chiediamo la cortesia di tenerne conto almeno come valutazione, perché ha un senso logico.
grazie
