### ISSUE TITLE
Errore Controllo ortografico in base il browser

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1028]
## Comportamento richiesto

abbiamo riscontrato che il Controllo ortografico su FireFox non funziona, considera l'inglese come lingua preferita.
su Safari funziona correttamente.

## Comportamento attuale

lo stesso documento aperto su due browser differenti.

**su FireFox**

![Firefox](https://user-images.githubusercontent.com/75281007/156766119-724695e9-7951-495c-a219-128ebf3a1ecb.jpg)

**Su Safari**

![Safari](https://user-images.githubusercontent.com/75281007/156766123-517f8c21-cf09-4306-a882-1250e1821ccd.jpg)

## Passi per riprodurre il comportamento

inserire il testo in qualsiasi campo dove è attivo il controllo.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
stesso problema con browser EDGE

**Comment by sajotrei** [comment]
Grazie Matteo per la risoluzione 👍

![1](https://user-images.githubusercontent.com/75281007/162739162-b4159fba-7199-43de-91dd-516b190e0ed1.png)
![2](https://user-images.githubusercontent.com/75281007/162739170-69d376e0-906d-4803-ad65-086a621e87f5.png)

**Comment by sajotrei** [comment]
il problema persiste anche con le seguenti modifiche

nel file config.inc.php:
**$lang = 'it_IT';**

in assets/src/js/functions/textarea.js
**scayt_sLang: "it_IT",**

**Comment by Pek5892** [comment]
Risolto con commit: 54cb3254355c1b3d069ae2accd69e20332ab88ca
