### ISSUE TITLE
Preventivi - IVA articoli non riportata nella compilazione di una riga 

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#103]
Nella versione 2.3 master aggiornata ad oggi inserendo un aricolo (precedentemente salvato nel magazzino con apposito codice iva) vengono aggiunte la descrizione e il prezzo unitario ma non viene inserito il codice iva precedentemente salvato.
Quest'ultimo deve essere inserito manualmente scegliendolo tra le varie opzioni del form.

**Comment by Dasc3er** [comment]
Ciao @antonioscarpino,
per la precisione hai aggiunto l'articolo in questione in che modulo? Fatture, DDT, Ordini, ...

**Comment by antonioscarpino** [comment]
la correzione apportata non risolve il problema

come si vede dalla prima immagine viene impoastato un valore iva che non so da dove sia preso

![errore1](https://user-images.githubusercontent.com/34765237/34683323-01d8495c-f4a2-11e7-8906-e5f571e37e42.png)

se si seleziona un articolo il valore di iva salvato alla creazione dell'articolo non viene riportato ma si deve scegliere tra le opzioni

![errore2](https://user-images.githubusercontent.com/34765237/34683400-3a4440d4-f4a2-11e7-89dd-05acc1259b7c.png)

**Comment by antonioscarpino** [comment]
nel modulo preventivi

"Il contenuto della presente email è da considerarsi strettamente riservato
e non divulgabile a terze parti"

Antonio Scarpino


2018-01-08 17:00 GMT+01:00 Thomas Zilio <notifications@github.com>:

**Comment by Dasc3er** [comment]
@antonioscarpino L'IVA che viene pre-selezionata è quella di impostata come predefinita nelle impostazioni oppure nell'anagrafica Cliente.
In ogni caso, ho appena testato nuovamente il commit e, una volta selezionata l'IVA nell'articolo, questa viene impostata correttamente.

Sei sicuro di aver impostato l'IVA predefinita per l'articolo?

**Comment by antonioscarpino** [comment]
certo che è impostata

![immagine](https://user-images.githubusercontent.com/34765237/34687394-dfd3f5ec-f4ae-11e7-850d-ba75a9f2bdd7.png)

in effetti l'iva preselezionata è quella del cliente però selezionando l'articolo l'iva precedentamente impostata sull'articolo non viene inserita.

a questo punto mi sorge un dubbio, ma è stato eseguito qualche cambiamento sul db? perchè altrimenti non si spiega che a te funzioni e a me no

**Comment by Dasc3er** [comment]
Che mi risulti non sono stati effettuati cambiamenti a livello di database di recente... Forse sono io che non capisco bene il problema e non riesco a replicarlo :D

@loviuz @fpsoftware @lucasalva87

**Comment by antonioscarpino** [comment]
Beh c'è poco da replicare.... se crei un articolo nel magazzino compilando anche il valore dell'iva, poi crei un preventivo inserisci una nuova riga e dal menù opzioni inserisci l'articolo che hai creato dovrebbe compilarti tutto il form con le informazioni di quell'articolo compreso quello dell'iva.
Se non sono stati eseguiti dei cambiamenti la query che viene eseguita per recuperare le informazioni al tuo db e quella che viene eseguaita sul mio devono dare gli stessi risultati e cioè il recupero di tutte le informazioni e la compilazione di tutti i campi del form.
Se a te lo fa e me no c'è qualcosa che tu hai ed io no.

**Comment by antonioscarpino** [comment]
Ok risolto l'arcano.
Pur avendo aggiornato il repository non so perchè i cambiamenti che avevi apportato al file edit_riga.php non sono stati inseriti.
Quindi i come è logico che il file che avevi tu non era quello che avevo io.
Adesso con lo stesso file è tutto ok puoi chiudere il tutto.
Grazie

**Comment by Dasc3er** [comment]
Errore mio, mi ero dimenticato che nei preventivi vi è una solo flusso ("entrata") e non avevo corretto il codice di conseguenza. Grazie mille!
Dovrebbe essere risolto con il commit f8132abfc1fdeee0dcd820b5ad372d200da57663
