### ISSUE TITLE
informazioni ed esempi nella documentazione sui filtri

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#1030]
Buonasera, nella documentazione non si fanno grandi esempi di filtri. Vorrei sapere come fare rifermento ai dati dell'utente loggato all'interno della query per la condizione del filtro.

In particolare mi interessava limitare l'accesso da parte degli agenti ai soli preventivi delle anagrafiche delle quali si è agente.

Dove è possibile trovare tutti i valori disponibili?  (Se ve ne sono)

Altrimenti possiamo lasciare aperta questa issue per rappresentare la necessità di aggiungere più info nella sezione relativa nella documentazione.

**Comment by Pek5892** [comment]
Buonasera, allego documentazione relativa alla selezione dei filtri.
[https://docs.openstamanager.com/v/2.4.34/guide/esempi/permessi-di-visualizzazione-degli-utenti](https://docs.openstamanager.com/v/2.4.34/guide/esempi/permessi-di-visualizzazione-degli-utenti)

Il filtro va impostato da Viste/Preventivi
![immagine](https://user-images.githubusercontent.com/102604205/182416739-a6391583-474e-441e-8d1b-735effeb3c65.png)
