### ISSUE TITLE
Blocco data conclusione

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1032]
## Comportamento richiesto

Quando si mette in stato accettato/lavorazione un preventivo si blocca la data di conclusione.

## Comportamento attuale

ci sta che blocca la data di accettazione, ma quella di conclusione sarebbe comodo averla accessibile perché può variare per vari motivi.
adesso l'unico modo e cambiare lo stato ogni volta.

## Possibile soluzione

sblocco campo data conclusione.

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
Ciao Valentina, dici che è fattibile questa richiesta?

**Comment by Pek5892** [comment]
Ciao @sajotrei, sembrerebbe una richiesta personalizzata più che un errore di logica.
Nel momento in cui un preventivo viene accettato, ne vengono accettate anche le condizioni prefissate tra cui la data di conclusione. Il comportamento previsto è quindi che il campo relativo a tale data si blocchi.
Nel caso in cui ci si trovi per fattori vari a dover apportare modifiche al preventivo si potrà ovviare a tale blocco rimettendolo in bozza, ma la sua funzione è utile per non rischiare di andare a modificare per errore delle condizioni che teoricamente dal momento in cui un preventivo risulta accettato non dovrebbero più subire modifiche.
