### ISSUE TITLE
Campo obbligatorio in aggiunta banca

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1035]
## Comportamento richiesto
Quando si crea una nuova banca impone l'inserimento del campo BIC/SWIFT.
Tale valore non viene quasi mai fornito dal cliente quindi si deve cercarlo sul web sperando che sia corretto.

![BIC](https://user-images.githubusercontent.com/75281007/165488135-a5e3fa91-5240-454d-b9ba-57faed238eec.png)

## Comportamento attuale

Ritengo sia utile rimuovere l'obbligo per tale campo, **anche perché è necessario SOLO in caso di bonifico internazionale.**

**Comment by sajotrei** [comment]
Ciao @Pek5892, 
Si ci è chiara la sua funzione.

osservando altri gestionali non è obbligatorio questo campo, alcuni lo richiedono solo se si inserisci un IBAN che non inizia con IT, così facendo lo richiede quando vedono un iban estero. 
sarebbe una soluzione interessante.

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/ec53c0ac31eb130c1f39348c53d324ebfd07928a
