### ISSUE TITLE
Bug relativo al widget "Attività da programmare"

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1036]
## Comportamento richiesto

Versione 2.4.30 e demo 2.4.32
Poter modificare il campo "descrizione" nel record "TODO" della tabella "Tipi di attività" senza togliere funzionalità al widget relativo sulla dashboard

## Comportamento attuale

Se modifico il campo "descrizione" il relativo widget smette di funzionare perchè nella tabella "zz_widgets" la query del record con id=24 fa riferimento al campo "descrizione" e non al campo "codice" (chiave primaria) della tabella "in.statiintervento".

## Possibile soluzione

Sostituire la query attuale con la query 
SELECT COUNT(id) AS dato FROM in_interventi WHERE in_interventi.idstatointervento = (SELECT in_statiintervento.idstatointervento FROM in_statiintervento **WHERE in_statiintervento.codice='TODO')** ORDER BY in_interventi.data_richiesta ASC

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. modulo "Stati attività"
2. record "TODO"
3. modifico campo "descrizione" in "PROGRAMMARE" o qualsiasi altra cosa.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by MatteoPistorello** [comment]
Ciao @NicolaNext,
grazie per la segnalazione, abbiamo risolto il problema con il seguente commit aggiornando la query del widget:
https://github.com/devcode-it/openstamanager/commit/027bdf7bc76b52845c0f7477562a1a8a60849b43
