### ISSUE TITLE
Bug che non permette la creazione di una fattura

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1037]
## Comportamento richiesto

Poter creare una fattura alla fine di un percorso Preventivo --> Ordine Cliente --> Attività

## Comportamento attuale

Già segnalato nel forum ma forse con troppe parole. Sintetizzo qui (almeno nella descrizione):
Se creo un **preventivo**, lo converto in **ordine cliente** e converto l'ordine cliente in **attività** non ho più possibilità di fatturare il materiale oggetto di questo processo lavorativo.
L'ordine risulta "fatturato" (e il materiale evaso) ma non viene creata nessuna fattura e l'attività non è fatturabile perché esiste un preventivo.

## Possibile soluzione

Rendere fatturabile una attività anche se esiste un preventivo (ma la creazione dell'attività non dovrebbe scaricare il magazzino) oppure rendere fatturabile l'ordine non evadendo il materiale alla creazione dell'attività (che per inciso potrebbe essere anche annullata dal cliente).
In realtà riconosco che la questione è molto più complessa perché OSM può essere usato in moltissimi modi differenti ma è evidente che in almeno un modo il sistema non funziona.

## Passi per riprodurre il comportamento

1. Creo un preventivo per un cliente (e il cliente lo accetta)
2. Converto il preventivo in ordine cliente (e, se serve, creo un ordine fornitore dall'ordine cliente magari perché non ho il materiale in negozio)
3. Creo una attività dall'ordine cliente (per esempio perché il materiale ordinato andrà utilizzato in laboratorio sul prodotto del cliente).
  3.1 La creazione dell'attività provoca lo scarico del materiale dal magazzino anche se non è stato ancora emesso un documento fiscale e questo mi suona strano.
  3.2  La creazione dell'attività trasforma l'ordine cliente in "Fatturato" senza l'emissione di un documento fiscale e anche questo mi sembra strano.
4. Completato il lavoro devo poter in qualche modo generare un documento fiscale ma sono in un "cul de sac" perché l'ordine cliente è bloccato e l'attività non è fatturabile in quanto legata ad un preventivo.

NB Tutto questo utilizzando gli strumenti messi a disposizione da OSM col comodo pulsante "Crea..."

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @NicolaNext, con la versione attuale puoi ovviare alla situazione ricorrendo alle azioni di gruppo, in attesa che entrambi i problemi vengano risolti. E' infatti qui possibile fatturare le attività selezionate anche se collegate a un preventivo.

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/7b53d2a1b76a26a6e2b578712f66d63876db8a29
