### ISSUE TITLE
Fatturazione Di Massa Contratti

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [devcode-it/openstamanager#1038]
Buongiorno,
avremmo la necessità di poter fatturare in massa le varie rate contrattuali dei contratti già precedentemente creati.

in questo momento noto che l'unica modalità possibile è quella di entrare in ogni singolo contratto,cliccare sulla pianificazione fatturazione e cliccare su crea fattura oppure dalla dashboard su rate contrattuali,cliccare su crea fattura per ogni rata in scadenza e poi si apre la modale per generare la fattura.( se ci sono centinaia di contratti da fatturare inizia ad essere oneroso in termini di tempo(immagino quelli a scadenza semestrale))

Esiste qualche metodologia per poter fatturare in massa tutte le rate contrattuali in scadenza per tutti i clienti?

in Alternativa è possibile recuperare dove vengono salvate le varie rate dei contratti con le relative righe da fatturare?
grazie a tutti

**Comment by Pek5892** [comment]
Buongiorno @andreameneguzzoinfol, al momento la funzione non è supportata ma lo metteremo in sviluppo nelle prossime versioni, grazie per il suggerimento!

**Comment by loviuz** [comment]
@andreameneguzzoinfol abbiamo inserito nella versione 2.4.38 questa funzionalità grazie a https://github.com/MichaelOliverio
