### ISSUE TITLE
Bug azioni di gruppo preventivi per utenti senza permessi (Versione 2.4.30)

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1039]
## Comportamento richiesto

Sicuramente una svista, un utente senza permessi non deve poter fatturare un preventivo neanche usando le azioni di gruppo.

## Comportamento attuale

Se un utente senza permessi crea un preventivo (ha permessi solo per questo) e dall'interno dello stesso cerca di creare un altro documento (Ordine, DDT, Fatture) ottiene il messaggio di accesso negato (un po' minimal), se però seleziona lo stesso preventivo dall'elenco preventivi e tramite azioni di gruppo fattura il preventivo stesso non ottiene nessun messaggio e la fattura viene regolarmente creata.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Accesso con utente che non ha permessi per nessun documento eccetto i preventivi
2. Creazione preventivo e accettazione dello stesso
3. Uscita all'elenco preventivi
4. Selezione del preventivo creato e fatturazione tramite azioni di gruppo

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Abbiamo risolto per la prossima versione, se vuoi anticiparti la modifica questo è il commit: https://github.com/devcode-it/openstamanager/commit/995c6e714ef3f67654a9c9af9decca37c8a8a246

**Comment by NicolaNext** [comment]
Grazie Valentina, e grazie ancora una volta a Matteo.
Per ora aggiorno manualmente la mia 2.4.30, con "prossima versione" parli della 2.4.33 già rilasciata o di quella che seguira?

Ciao, Nicola

**Comment by Pek5892** [comment]
Intendo la versione 2.4.34, buona giornata :)
