### ISSUE TITLE
Riordinamento righe in fattura non viene salvato

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1041]
## Comportamento attuale

Se vado a modificare l'ordine delle righe in una fattura, al salvataggio ritorna l'ordinamento originale.
Da verificare se il problema si verifichi anche con altri moduli

## Passi per riprodurre il comportamento

Creare una fattura e inserire le righe
Spostare una riga.
Salvare

* Modulo: FATTURE
* Versione del progetto: OSM 2.4.32
* Versione PHP 7.4

**Comment by sajotrei** [comment]
Ciao confermo questo problema

**Comment by idraulicadueci** [comment]
Ho testato gli altri moduli:

- DDT entrata OK
- DDT uscita OK
- Preventivi OK
- Contratti OK
- Ordini fornitore OK
- Ordini cliente OK

Quindi confermo che il problema si verifica solo sul modulo fatture.

**Comment by MatteoPistorello** [comment]
Ciao @idraulicadueci,
grazie per la segnalazione, il riordinamento delle righe in fattura viene risolto con il seguente commit: 
https://github.com/devcode-it/openstamanager/commit/9295eae151990625aec383ecc0e386f5555200a5

**Comment by idraulicadueci** [comment]
grazie @MatteoPistorello
