### ISSUE TITLE
(RISOLTO) Documento collegato errato nella creazione Ord. Forn. da Preventivo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1042]
## Comportamento attuale

Creando un ordine fornitore da un preventivo, il link creato nell'elenco "documenti collegati" ricerca il documento tra gli ordini clienti, dando ovviamente "record non trovato". Questo perché effettivamente l'ordine fornitore viene creato correttamente, ma il link creato nei documenti collegati, effettua la ricerca sugli ordini clienti.

## Passi per riprodurre il comportamento

1. Creare un preventivo
2. Dal preventivo creare un ordine fornitore
3. Esplodere l'elenco documenti collegati (appare "ordine cliente num. XXXX")
4. Cliccare sul link "ordine ciente num. XXXX"

## Contesto

* Modulo: Preventivi
* Versione del progetto: 2.4.32

**Comment by NicolaNext** [comment]
Ciao idraulicadueci,
avevo aperto identica richiesta a fine marzo e a inizio aprile era stata Matteo Pistorello mi comunicava il rilascio della soluzione che trovi qui https://github.com/devcode-it/openstamanager/commit/bdaa16a73c6b82001c528826de6fd1e359b83831
Ciao, Nicola

**Comment by idraulicadueci** [comment]
Ciao @NicolaNext , grazie per l'informazione; fra l'altro ho notato che la modifica è già inclusa nell'aggiornamento alla versione 2.4.33.
