### ISSUE TITLE
(BUG )associazione righe a ordine fornitore chiuso

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1043]
## Comportamento richiesto

in associazione righe in FE **considera gli ordini a fornitore in stato fatturato** ( concluso )

## Comportamento attuale

Abbiamo notato che quando si importa una FE passiva, se si cerca i riferimenti, trova e associa le righe di ordini fornitori in stato fatturato.

capita che si creino ordini a fornitore, ma poi quando arriva la fattura e non è presente tutta la merce ordinata ( per varie ragioni ).

per non stare li ad aprire e modificare l'ordine fornitore, gli cambiamo lo stato da parzialmente evaso a fatturato, perché quella merce non arriverà più...

dopo mesi, quando arriva una nuova fattura ( sempre lo stesso fornitore ) associa comunque le righe dell'ordine che avevamo chiuso.
immagino che il sistema considera comunque quelle righe non evase.

**Comment by sajotrei** [comment]
Ciao siete riusciti a replicare il problema?

**Comment by sajotrei** [comment]
Ciao riporto delle info sperando di aiutarvi nella risoluzione del problema

![1](https://user-images.githubusercontent.com/75281007/180963360-8f3fbf3b-f9b9-4c4e-a8d5-1e09bd0f781e.png)
![2](https://user-images.githubusercontent.com/75281007/180963369-543a5ebc-64d9-4009-bcd4-652a30df2406.png)
![3](https://user-images.githubusercontent.com/75281007/180963371-b7a4ff53-85a4-4e0f-8c62-a5544c8e2f37.png)
![4](https://user-images.githubusercontent.com/75281007/180963375-f3bad4f8-4cd6-4297-af74-e3207384425d.png)

**Comment by sajotrei** [comment]
Ciao, il problema si presenta anche con l'ultima versione 2.4.35

abbiamo anche notato che non "recupera" l'articolo, anche se è presente a magazzino e nell'ordine fornitore associato.
quindi lo si deve mettere a mano.

![1](https://user-images.githubusercontent.com/75281007/188147004-61d839b9-3c69-43af-b578-838fcc225d56.png)
![2](https://user-images.githubusercontent.com/75281007/188147015-1e9c2192-5830-4046-a87d-4294c06972a6.png)
![3](https://user-images.githubusercontent.com/75281007/188147040-2c9bad9c-181d-4aac-9151-305e48d0ec70.png)
![4](https://user-images.githubusercontent.com/75281007/188147053-e34da4d8-dc58-424e-a23a-93cb98d0236c.png)
![5](https://user-images.githubusercontent.com/75281007/188147054-b59ee4dc-88e6-491a-af67-c1110e726c7a.png)

**Comment by sajotrei** [comment]
Ciao 
in merito a questo bug si sa qualcosa?

è davvero molto fastidioso, di fatto associa righe ordini fornitori già chiusi e ogni volta si deve andare a correggerli a mano.

su fatture con molti articoli diventa impegnativo.😬

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/31713bbb51f1b112892cea9ca993710c6c37dd0b
