### ISSUE TITLE
BUG plugin provvigioni

### ISSUE THREAD

**Issue by xcbroberto** [devcode-it/openstamanager#1047]
## Comportamento richiesto

Plugin provvigioni, delete record.

## Comportamento attuale

    case 'deletereferente':
        $dbo->query('DELETE FROM `co_provvigioni` WHERE `id`='.prepare($id_record));

        flash()->info(tr('Provvigione eliminata!'));

        break

## Possibile soluzione

    case 'deleteprovvigione':
        $dbo->query('DELETE FROM `co_provvigioni` WHERE `id`='.prepare($id_record));

        flash()->info(tr('Provvigione eliminata!'));

        break

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/e824624f6925a08a2aafa447f054e61b0d2a5c7b
