### ISSUE TITLE
DDT in Entrata - Warning assenza DDT

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#1048]
Appena creo un DDT mi compare subito un Warning:
" E' assente un Ddt di acquisto numero "32" in data precedente o corrispondente a 27/05/2022: si potrebbero verificare dei problemi con la numerazione corrente delle fatture."

e non riesco a capire cosa possa essere. Ho guardato la base dati ma non ho trovato particolari anomalie

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: DDT in entrata
* Versione del progetto: 2.4.33
* Versione PHP: 7.4.27
* Tipo di server: Linux

**Comment by leonardocalabretta** [comment]
Il problema c'è con qualsiasi DDT anche dell'anno prima

**Comment by leonardocalabretta** [comment]
Se posso eventualmente dare una mano, molto volentieri

**Comment by loviuz** [comment]
ciao @leonardocalabretta hai provato con qualche versione piú aggiornata?

**Comment by loviuz** [comment]
Quell'avviso controlla che ci sia una sequenzialità fra il numero documento e la data, forse manca il ddt 32 o non é consequenziale come la data. Prova a controllare questo.

**Comment by leonardocalabretta** [comment]
Eh ci ho guardato ma in realtà mi sembra tutto ok :-(

**Comment by Pek5892** [comment]
Risolto con commit 4653647e407d927743addb7f1508dc04b0177cd9

**Comment by leonardocalabretta** [comment]
Confermo sembra tutto ok
