### ISSUE TITLE
NOTE D'ACCREDITO - vengono erroneamente registrate come fatture.

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#105]
La nota d'accredito non viene considerata come storno di una fattura, ma si comporta come se fosse una fattura e l'importi di queste vengono aggiunti e non sottratti nello scadenzario e nei mastri di contabilità.
![image](https://user-images.githubusercontent.com/34273200/34693857-6d512776-f4c5-11e7-8633-56380a59d279.png)

![image](https://user-images.githubusercontent.com/34273200/34693928-a1709a46-f4c5-11e7-881c-81fef602a26d.png)

Risultando così sbagliato sia le scadenze che il conto specifico del cliente in contabilità

**Comment by loviuz** [comment]
avevamo sempre gestito la nota di accredito inserendo gli importi in negativo delle righe, per cui tutti i vari movimenti del piano dei conti tornano. probabilmente manca una guida...

**Comment by fgambarelli** [comment]
Ho due osservazioni importanti nel trattare gli importi in negativo:
1 - Deve inserirli l'utente e non mi sembra corretto, visto che è una Nota d'accredito
2 - Purtroppo gli importi in negativo non è una soluzione accettata in contabilità, dove è sono le colonne dare ed avere ed il libro giornale che fa fede. 

Le fatture in contabilità devono essere registrate come da esempio, 
![image](https://user-images.githubusercontent.com/34273200/34709433-8c9e0516-f517-11e7-8548-0eacf7ccb76a.png)
Mentre quando è una nota d'accredito deve essere come sotto:
![image](https://user-images.githubusercontent.com/34273200/34709614-302b6f8e-f518-11e7-9a63-2392c6c71198.png)

**Comment by fpsoftware** [comment]
ciao @fgambarelli, concordiamo con quello che hai scritto, visti i tempi siamo costretti a posticipare lo sviluppo di questa funzionalità più avanti, collegando l'emissione di note di accredito/debito anche al relativo sezionale.
Grazie per l'aiuto intanto!

**Comment by lucasalva87** [comment]
> 1 - Deve inserirli l'utente e non mi sembra corretto, visto che è una Nota d'accredito

Facciamo in modo che in fase di salvataggio della fattura se di tipo "Nota di accredito" tutti gli importi vengano forzatamente salvati con segno negativo.

> 2 - Purtroppo gli importi in negativo non è una soluzione accettata in contabilità, dove sono le colonne dare ed avere ed il libro giornale che fa fede.

Con importo negativo i movimenti nel piano dei conti risultano corretti. Eventualmente nella stampa fattura possiamo nascondere il segno meno.

**Comment by Dasc3er** [comment]
@fgambarelli @devcode-it/openstamanager La gestione di base delle Note di credito (e di debito) è stata implementata nella branch master per la prossima versione 2.4.1.
