### ISSUE TITLE
Proposta miglioramento provvigioni

### ISSUE THREAD

**Issue by xcbroberto** [devcode-it/openstamanager#1050]
## Comportamento richiesto

Visualizzare per ogni riga dei documenti la provvigione applicata

## Passi per riprodurre il comportamento

1. file: "common.php" definire la funzione per restituire le informazioni della provvigione _**function provvigioneInfo(Accounting $riga, $mostra_provigione = true)**_ 
3. Inserire nei file: "row-list.php "  in prossimità della visualizzazione dell'importo riga il richiamo alla funzione provvigioneInfo()

Eventuale codice rilevante:
common.php
  ```/**
 * Visualizza le informazioni relative allo provvigione presente su una riga.
 *
 * @param bool $mostra_provigione
 *
 * @return string|null
 */
function provvigioneInfo(Accounting $riga, $mostra_provigione = true)
{
    if (empty($riga->provvigione_unitaria) || (!$mostra_provigione && $riga->provvigione_unitaria < 0)) {
        return null;
    }

    $text = $riga->provvigione_unitaria > 0 ? tr('provvigione _TOT_ _TYPE_') : tr('provvigione _TOT__TYPE_');
    $totale = !empty($riga->provvigione_percentuale) ? $riga->provvigione_percentuale : $riga->provvigione_unitaria;

    return replace($text, [
        '_TOT_' => Translator::numberToLocale(abs($totale)),
        '_TYPE_' => !empty($riga->provvigione_percentuale) ? '%' : currency(),
    ]);
}
``` 
row-list.php
```        // Importo
        echo '
            <td class="text-right">
                '.moneyFormat($riga->importo);
		
		//provvigione riga 
			if (abs($riga->provvigione_unitaria) > 0) {
				$text = provvigioneInfo($riga);

				echo '
						<br><small class="label label-warning">'.$text.'</small>';
			}
		
        echo '</td>';
``` 

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

- [ ]

**Comment by loviuz** [comment]
Ciao @xcbroberto,
grazie per il suggerimento! Hai mai fatto delle pull request con github? E' un metodo per provare la modifica su una copia del repository e poi inviare direttamente al repository il contributo così che noi lo accettiamo direttamente.

**Comment by Pek5892** [comment]
Modifiche allineate alla corrrente versione nel commit https://github.com/devcode-it/openstamanager/commit/e13a608460bf5d4d82b2574738239f46e867b67d
