### ISSUE TITLE
PREVENTIVI - errore nella generazione della stampa

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#106]
come da titolo generando la stampa di un preventivo c'è il segurnte errore

![immagine](https://user-images.githubusercontent.com/34765237/34726085-48d72ccc-f553-11e7-9cbd-6f9ee5189684.png)

**Comment by Dasc3er** [comment]
Ciao @antonioscarpino, prova a controllare la issue #96 che tratta la soluzione dello stesso problema.
