### ISSUE TITLE
Problema in visualizzazione logo nelle stampe

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1060]
## Comportamento richiesto

Il logo sia centrato come fino a qualche versione fa (purtroppo non sono riuscito a fare il bisect esatto, ma credo 2.4.30 o 2.4.31, possibile anche 2.4.32) come da screen da vecchia fattura (logo differente perche cambiato nel mentre ma effetto con uguale logo e dimensione)
![image](https://user-images.githubusercontent.com/392762/178113083-4647dbdd-55f7-47ff-a1b1-b644f5647487.png)

## Comportamento attuale

Il logo viene tagliato in alto come da screen
![image](https://user-images.githubusercontent.com/392762/178112942-f26c5190-4986-46fe-b09a-aef129d25fd4.png)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Stampa di un elemento (anche riepilogo o stampa contabile, non solo fattura)
2. Errore nel PDF generato
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: stampe
* Versione del progetto: 2.4.33
* Versione PHP: 8.0.18
* Tipo di server: Apache (aruba)

**Comment by Pek5892** [comment]
Buongiorno @marcus905,
in che formato è il logo nuovo?
