### ISSUE TITLE
Cambio logo da anagrafica non funzionante

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1061]
## Comportamento richiesto

Al cambio del logo in anagrafica Azienda, sia con la modifica del nome del logo vecchio in altro che "Logo stampe" o l'eliminazione del logo vecchio, e conseguente upload e rinomina del logo nuovo in "Logo stampe" il logo nuovo venga usato.

## Comportamento attuale

Il logo vecchio rimane nelle stame anche se rinominato in anagrafica. Se eliminato in anagrafica compare il generico indicatore Logo Azienda. Qualsiasi nuovo caricamento "Logo stampe" non ha effetto, la riga in zz_settings rimane con il riferimento al file vecchio.

**Possibile che il bug impatti anche la funzionalità filigrana stampe ma non è stato testato.**

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Modifica nome logo vecchio/eliminazione logo vecchio da anagrafica Azienda
2. Caricamento e ridenominazione del nuovo logo
3. Test stampa

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: anagrafiche
* Versione del progetto: 2.4.33
* Versione PHP: 8.0.18
* Tipo di server: Apache (aruba)

**Comment by Pek5892** [comment]
Bug non presente nella versione 2.4.37
