### ISSUE TITLE
Errore durante l'apertura della fattura elettronica

### ISSUE THREAD

**Issue by joy2k** [devcode-it/openstamanager#1064]
L'importazione della fattura elettronica ha smesso di funzionare dopo l'aggiornamento all'ultima release. Aprendo uno dei file supportati, presi direttamente dallo SDI o già caricati precedentemente, compare la scritta: **Errore durante l'apertura della fattura elettronica .**

ho condotto alcune prove sul codice sorgente e sembra che la variabile $fatturapa sia vuota

ho controllato e ricontrollato i permessi a files e cartelle (che non sono mai cambiati).

ho provato a disabilitare-abilitare i plugin della fatturazione elettronica ma non ha risolto.

è possibile che l'aggiornamento fatto da 2.4.28 a 2.4.33 provochi questo problema? 

Tutto il resto funziona bene

* Modulo:
* Versione del progetto: 2.4.33 (5a18f6963)
* Versione PHP: 7.4.30
* * Versione MysQL: mysql_version | Valore consigliato: 5.7.x - 8.0.x **(Valore attuale: 10.6.8)**
* Tipo di server: apache

**Comment by Pek5892** [comment]
Buona sera,
non abbiamo riscontri di problemi simili da parte di altri utenti. Sembrerebbe un problema legato all'installazione.

**Comment by lucasalva87** [comment]
Potete provare ad installare l'ultima versione di OSM 2.4.34 rilasciata venerdì 15/07?
Questo zip non dovrebbe avere permessi impostati sui file.

**Comment by joy2k** [comment]
**Risolto** con la nuova versione 2.4.34, l'ho installata in una nuova directory ed andando a confrontarla con la vecchia ho notato una differenza di permessi sul modulo di importazione della fattura elettronica. grazie e buon lavoro a tutti.
