### ISSUE TITLE
Aggiunta campi in modulo Articoli

### ISSUE THREAD

**Issue by Pek5892** [devcode-it/openstamanager#1065]
Aggiunta dei campi "Produttore" e "Link"(alla pagina del prodotto), con possibilità di filtrare in base al produttore.
[https://forum.openstamanager.com/d/2312-aggiungere-campi-articoli-magazzino](
https://forum.openstamanager.com/d/2312-aggiungere-campi-articoli-magazzino)

**Comment by sajotrei** [comment]
al momento noi per colmare questa mancanza abbiamo usato i campi personalizzati, con i relativi limiti.
ma sarebbe certamente comodo una gestione più adeguata e corretta.

<img width="1086" alt="Screenshot 2022-08-02 alle 15 36 54" src="https://user-images.githubusercontent.com/75281007/182388598-727d837b-4159-4fac-8d1e-6462c361c72a.png">

<img width="825" alt="Screenshot 2022-08-02 alle 15 36 36" src="https://user-images.githubusercontent.com/75281007/182388635-2b1fe1ac-9d73-4b2b-ab16-9f817eaed30d.png">

**Comment by Pek5892** [comment]
Aggiunto il campo Marchio in articoli dalla versione 2.5.6
