### ISSUE TITLE
BUG: Errore al primo accesso

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1067]
Ho aggiornato alla nuova versione 2.4.34.
Al primo accesso mi viene restituito un errore, che comunque non risulta bloccante per il programma. Infatti ricaricando la pagina, l'errore scompare e tutto funziona correttamente.
Allego file LOG.

[error.log](https://github.com/devcode-it/openstamanager/files/9125264/error.log)

**Comment by idraulicadueci** [comment]
Ho provato a sostituire il file `index.php` con quello della versione precedente e il problema non si presenta.

**Comment by Pek5892** [comment]
Ciao @idraulicadueci,
potresti allegarci il file config.inc.php? (magari oscurando i dati di connessione al database)

**Comment by idraulicadueci** [comment]
[config.inc.txt](https://github.com/devcode-it/openstamanager/files/9137579/config.inc.txt)

**Comment by lucasalva87** [comment]
@idraulicadueci verificando dal file error.log postato inizialmente vedo che l'errore dipende dalla riga 37 del file index.php.
Più nel dettaglio sembra dipendere da un'errata valorizzazione dell'impostazione "Inizio periodo calendario". Potresti cortesemente verificarne il valore accedendo a "Strumenti->Impostazioni->Generali->Inizio periodo calendario"?

Fammi sapere se risolvi, grazie mille.

**Comment by idraulicadueci** [comment]
ciao @lucasalva87 ho fatto come hai detto, i campi erano correttamente valorizzati. La cosa strana è che adesso il problema non si è ripresentato. Forse facendo questa operazione il sistema ha riformattato i valori?
Grazie @lucasalva87 e @Pek5892 per il vostro aiuto.
