### ISSUE TITLE
Percorso OSM

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1068]
## Comportamento richiesto

https://forum.openstamanager.com/d/2322-percorso-osm

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
il file manifest viene generato durante la prima installazione, essendo le demo installate manualmente abbiamo provveduto a correggerlo manualmente.

**Comment by sajotrei** [comment]
Ciao @Pek5892 , grazie per la risposta.
ovviamente la demo era solo per fare l'esempio.

il punto è che questo problema si presenta su tutte le installazioni, sembra che in fase di installazione NON compila correttamente il file manifest.

**Comment by sajotrei** [comment]
Ciao, 
comunque questo aspetto si presenta anche sulle installazioni sulla piattaforma in cloud

https://xxnomeclientexx.osmcloud.it/**openstamanager**

e quindi non funziona 😬
