### ISSUE TITLE
Fattura elettronica: errore AdE "Descrizione (Beni e servizi) è in un formato non corretto"

### ISSUE THREAD

**Issue by gbcelano** [devcode-it/openstamanager#1069]
Dopo aggiornamento alla ver. 2.4.34, nell'importazione del file XML generato da OSM in "Fatturazione elettronica e Conservazione" dell'Agenzia delle Entrate viene generato l'errore "Descrizione (Beni e servizi) è in un formato non corretto".

L'analisi dei file XML prodotti con ver. 2.4.34 e con versioni precedenti rivela che il problema, in effetti, è nella Descrizione; l'Agenzia delle Entrate non digerisce il CR-LF (a capo) che nelle versioni precedenti di OSM veniva rimosso, mentre nella versione attuale viene mantenuto (in conformità a come in effetti è stato inserito da OSM), quindi: 
- Accettato: _"<Descrizione>Prestazione. Rif. Contratto 1</Descrizione>"_
- Non accettato: _"<Descrizione>Prestazione.
     Rif. Contratto 1</Descrizione>"_

**Comment by lucasalva87** [comment]
Da quale versione provenivi?
Non sembra siano state fatte modifiche a quel nodo dalla 2.4.29

**Comment by gbcelano** [comment]
Ciao Luca. 
Ho aggiornato dalla 2.4.32. XML importato in AdE prima dell'aggiornamento, tutto ok, ma dopo aver fatto l'aggiornamento ho riscontrato il problema, poi analizzato con la comparazione degli XML (inizialmente pensavo fosse colpa di asterischi/apici)

**Comment by lucasalva87** [comment]
Riusciresti a testare questa fix per vedere se risolve il problema?

**Comment by gbcelano** [comment]
Caricato il file, prodotta una fattura di prova e importata in AdE: NESSUN ERRORE 😀✔
Grazie!
