### ISSUE TITLE
Fatture Vendita - nella stampa non viene riportata l'intestazione del cliente e le informazioni della fattura

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#107]
Generando la stampa di una fattura, in essa non vengono riportate ne l'intestazione del cliente ne le informazioni della fattura (n. fattura, data, ecc..)

![errore](https://user-images.githubusercontent.com/34765237/34752595-88610bbe-f5b3-11e7-814f-199bb75ce4ed.png)

**Comment by Dasc3er** [comment]
@antonioscarpino Sembra che ci sia un malfunzionamento di qualche tipo all'interno del file **header.php**...
Potresti provare ad abilitare il debug dal file di configurazione?

**Comment by lepool** [comment]
Ho provato a stampare una mia fattura di prova.

Versione git 2.3.1 branch master ultimo commit f8132abfc1fdeee0dcd820b5ad372d200da57663
Ecco il risultato : 

![grafik](https://user-images.githubusercontent.com/32035706/34764726-aa05e618-f5ef-11e7-9570-5167d9946f57.png)

**Comment by antonioscarpino** [comment]
Risolto era un errore che avevo fatto nel file header.php di base
