### ISSUE TITLE
(RISOLTO) Statistiche articoli non visualizzate

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1071]
## Comportamento attuale

- Nel modulo ARTICOLI non sono visualizzati i dati "Ultimi 20 prezzi di acquisto" e "Ultimi 20 prezzi di vendita"

![IMG001](https://user-images.githubusercontent.com/40104356/180370479-c544377b-dd72-4112-ad5a-02d2885bb19d.png)

- Nel form di inserimento articolo in un documento non vengono visualizzati "Ultimi prezzi di acquisto" e "Ultimi prezzi di vendita"; sotto "Ultimi prezzi dal fornitore" oltre a non esserci alcun dato viene visualizzato "Nessuna vendita trovata di questo articolo al cliente"

![IMG002](https://user-images.githubusercontent.com/40104356/180370836-ad356476-3270-4316-a35d-de895d4b200a.png)

OSM 2.4.34

**Comment by lucasalva87** [comment]
Ciao @idraulicadueci , domanda banale. Le fatture di vendita / acquisito le visualizzi per il 2022?

**Comment by sajotrei** [comment]
Ciao, io vedo le statistiche degli ultimi prezzi.
sempre con la ver. 2.4.34

**Comment by idraulicadueci** [comment]
ciao @lucasalva87, ho emesso ieri una fattura con l'articolo, quindi dovrei vederlo nelle statistiche, invece succede quello che ho descritto. 
Questo è l' [error.log](https://github.com/devcode-it/openstamanager/files/9169523/error.log)

**Comment by idraulicadueci** [comment]
Ho fatto un'installazione da zero di OSM 2.4.34 sul server di test, per escludere la possibilità di qualche errore in fase di aggiornamento. Il problema si presenta comunque e nel file error.log viene riportato lo stesso errore indicato in quello precedente.

**Comment by loviuz** [comment]
@idraulicadueci dall'errore sembra un problema di compatibilità della versione di PHP, probabilmente hai la versione 8.0 o 8.1 in uso. Puoi provare con la 7.4?

**Comment by loviuz** [comment]
@idraulicadueci prova a integrare questa modifica, credo dipenda proprio da PHP 8.0: https://github.com/devcode-it/openstamanager/commit/f79ac1c300a192cb4904c7ef6f4ca70043db1b9d

**Comment by idraulicadueci** [comment]
> @idraulicadueci dall'errore sembra un problema di compatibilità della versione di PHP, probabilmente hai la versione 8.0 o 8.1 in uso. Puoi provare con la 7.4?

Ciao @loviuz, è esattamente come dici; infatti passando alla versione PHP 7.4 il problema non si presenta

> @idraulicadueci prova a integrare questa modifica, credo dipenda proprio da PHP 8.0: [f79ac1c](https://github.com/devcode-it/openstamanager/commit/f79ac1c300a192cb4904c7ef6f4ca70043db1b9d)

con il commit https://github.com/devcode-it/openstamanager/commit/f79ac1c300a192cb4904c7ef6f4ca70043db1b9d il problema si è risolto. Grazie per il tuo aiuto.
