### ISSUE TITLE
Errore in cerca destinatari newsletter

### ISSUE THREAD

**Issue by Pek5892** [devcode-it/openstamanager#1072]
Effettuando una ricerca tra i destinatari di una newsletter si presenta questo errore:
https://forum.openstamanager.com/d/2329-errore-in-cerca-su-newsletter

**Comment by loviuz** [comment]
Dovrebbe essere risolto con questo commit, era un problema di compatibilità con PHP 8.0:
https://github.com/devcode-it/openstamanager/commit/58c70f98d4d9020b3118a0b9e151edbda2261340
