### ISSUE TITLE
Statistiche Interventi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1073]
## Comportamento richiesto

Abbiamo notato che le statistiche sono basate sulla Data Richiesta e non sulla data della sessione ( Ora inizio )
questo di fatto sfalsa molto le statistiche, perché la data richiesta può essere di mesi prima della reale attività svolta.

ES. si imposta una attività a gennaio per manutenzione, ma poi per vari motivi la si deve eseguire a febbraio.
nelle statistiche questa attività risulterà a gennaio.

## Possibile soluzione

Considerare la data inizio Sessione/i, piuttosto che la data richiesta attività

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Corretto con commit f5b15738a562972b8d70175c9102ef90bc2758c5
