### ISSUE TITLE
Attività legate al contratto si chiudono anche se sono ancora de eseguire.

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1074]
## Comportamento richiesto

Ciao, abbiamo dei contratti con delle attività pianificate nei mesi, abbiamo notato che se emettiamo la fattura dal contratto, chiude TUTTE le attività legate, **incluse quelle future in stato da programmare e/o programmato** 

in teoria ci sia aspetta che chiuda solo le attività in stato completato, lasciando intatte le altre.

## Comportamento attuale

Qual è il comportamento attuale, e come ti aspetti che venga migliorato?

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by MatteoPistorello** [comment]
Ciao @sajotrei ,
grazie per la segnalazione, ecco il commit che risolve il problema:
https://github.com/devcode-it/openstamanager/commit/9eaa601732bb6db3257258fbb195ab29e61402fd
