### ISSUE TITLE
Funzioni in errore in Newsletter

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1075]
## Comportamento richiesto

se si usano delle funzioni per il carattere, dopo aver salvato, ritornano allo stato precedente.
anche se si inserisce una immagine, dopo aver salvato, viene eliminata.

## Comportamento attuale

![Screenshot 2022-07-29 alle 15 12 52](https://user-images.githubusercontent.com/75281007/181768960-8ba71b81-378f-4606-9217-8c7bcfcd037f.png)
![Screenshot 2022-07-29 alle 15 12 58](https://user-images.githubusercontent.com/75281007/181768967-b02c5ddf-4517-41f7-8307-49ad93cf9716.png)

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by loviuz** [comment]
Ciao @sajotrei,

per motivi di sicurezza sono permessi solo una serie di tag html negli editor di testi. Ho comunque verificato come mai i tag da h1 a h6 venivano rimossi e non erano in questa lista. Se riprovi con questo commit dovrebbe essere risolto:
https://github.com/devcode-it/openstamanager/commit/36fbde507bd6f85116c81019045b504e4104f464
