### ISSUE TITLE
errore di visualizzazione data-orario in duplica attività

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1078]
## Comportamento richiesto

non si vede la parte dei minuti

## Comportamento attuale

<img width="462" alt="Screenshot 2022-09-01 alle 16 32 07" src="https://user-images.githubusercontent.com/75281007/187956056-f9276da6-7e89-45d9-8e53-f8ff1edaf299.png">

## Passi per riprodurre il comportamento

selezionare attività e duplicarla con azioni di gruppo 
selezionare data/ora

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno,
non riusciamo a riprodurre lo stesso comportamento, potresti darci maggiori informazioni?
![immagine](https://user-images.githubusercontent.com/102604205/188455509-26d515aa-bcc2-44ea-97e9-bf369a85c97b.png)

**Comment by Pek5892** [comment]
Risolto con commit 012018b257b6a98469f02ac8df5514a2825c8733
