### ISSUE TITLE
Firefox: problema con le stampe

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#108]
Volevo rivolgare una domanda.
Ma come mai i piè pagina delle varie stampe (fatture, preventivi, ecc.), anche se correttamente impostati e corettamente visualizzati in fase di creazione delle stampe, poi non vengono effettivamente stampati?
E' un problema che riscontro solo io?

**Comment by Dasc3er** [comment]
@antonioscarpino Intendi dire che il PDF della stampa viene generato correttamente, e solo stampando il PDF in formato cartaceo non compare il footer?

**Comment by antonioscarpino** [comment]
Esatto

**Comment by loviuz** [comment]
è molto strano come problema...!

**Comment by antonioscarpino** [comment]
Ho appena scoperto che è un problema di Firefox.
Anche se nella creazione del pdf e in anterpima di stampa fa vedere il footer, poi nell'atto pratico della stampa il footer non viene stampato.
Con Edge il problema non c'è.
Non so con Chrome.

**Comment by loviuz** [comment]
stampi dall'anteprima di stampa di firefox, da dentro il browser?

**Comment by antonioscarpino** [comment]
Si esatto.
Con Firefox se stampi il pdf creato direttamente da bowser non viene stampato il footer.
Invece scaricando il pdf creato e poi stanpandolo tutto ok.
Con Edge invece sia stampando direttamente da browser che scaricando il pdf e poi stampandolo è tutto ok.

**Comment by loviuz** [comment]
molto strano... da approfondire!

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager Non potrebbe trattarsi di un problema della gestione dei PDF da parte dei browser?

**Comment by Dasc3er** [comment]
@antonioscarpino Ci sono novità sulla questione?

**Comment by antonioscarpino** [comment]
confermo che il problema é dovuto a una non perfetta gestione del formato pdf da parte di firefox. É possibile che in futuro con un aggiornamento di firefox il problema si risolva. Per il momento consiglio di scaricare l'anteprima del pdf che viene creato e stampare il file scaricato con un qualsiasi reader pdf. In questo modo il problema non si presenta.
