### ISSUE TITLE
importazione fatture elettroniche in segmenti diversi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1081]
## Comportamento richiesto

in **Fatture di acquisto**, ci è capitato di essere nel **segmento** **Fatture non elettroniche** e poi **cliccare** su **Fatturazione Elettronica**, abbiamo importato la fatture FE per poi scoprire che è stata importata nelle fatture NON elettroniche anzichè sotto il segmento Standard acquisti.

<img width="1627" alt="Screenshot 2022-09-13 alle 10 35 29" src="https://user-images.githubusercontent.com/75281007/189854037-49688d75-cc03-4051-a2cc-8b141aff2f35.png">

## Possibile soluzione

permettere di cambiare il segmento all'interno della fattura dopo averla importata.
oppure quando si importa una FE imposta in automatico il segmento Standard acquisti.

## Passi per riprodurre il comportamento

importare una fatture FE sotto segmento fatture NON elettroniche.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
questa opzione è già presente
![immagine](https://user-images.githubusercontent.com/102604205/201145118-968e4efc-7a6a-4f52-a220-66c20f67b1f1.png)

**Comment by sajotrei** [comment]
Ciao, si si lo so, ma dopo averla importata non è più possibile cambiare il sezionale, infatti la richiesta che ho indicato è dopo l'importazione.

sarebbe utile che tutte le fatture da SDI prenda in automatico il sezionale giusto

al momento l'unica soluzione ( apparte la modifica sul DB ) è quella di salvare il file XML eliminare la fattura e rimportare il file XML nella sessione corretta.

**Comment by sajotrei** [comment]
Ciao, quindi mi sembra di capire che non si può far nulla, giusto ?

**Comment by sajotrei** [comment]
Ciao, 
preciso che sono problemi simili ma questo è sulla fatture passive.
il #1126 su fatture attive.

**Comment by sajotrei** [comment]
è stato chiuso perché non è fattibile ?

**Comment by Pek5892** [comment]
L'issue è stata chiusa per non avere troppe issue aperte dove è sufficiente effettuare la medesima modifica in quanto le fatture di acquisto e di vendita vengono trattate negli stessi file in modules/fatture. Verrà eventualmente presa in considerazione in riferimento all'issue #1126.
