### ISSUE TITLE
Creare attività da preventivo

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1082]
## Comportamento richiesto

sarebbe comodo poter creare una o più attività dal preventivo senza necessariamente importare le righe del preventivo.

ES, facciamo un preventivo con riga libera indicato 100€ di lavoro, poi eseguiamo un intervento associato al preventivo, con le relative sessioni di lavoro.

## Comportamento attuale

è possibile creare una attività da preventivo **solo** importando le righe.

![Screenshot 2022-09-13 alle 15 16 04](https://user-images.githubusercontent.com/75281007/189912160-8f7015fe-b2df-49ba-9dc9-164580b12f0f.png)
![Screenshot 2022-09-13 alle 15 17 06](https://user-images.githubusercontent.com/75281007/189912169-aa84b188-707f-43f8-99c0-c351a21882d2.png)

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei, avete provato a gestirlo come se fosse un contratto a ore? https://docs.openstamanager.com/v/2.4.37/guide/esempi/contratti-a-ore 
o meglio a creare un preventivo in stato "In lavorazione" e selezionandolo al momento della creazione di un'attività?

**Comment by sajotrei** [comment]
Ciao, il contratto lo usiamo ma non per attività sporadiche.

...si certo al momento facciamo così, crediamo una nuova attività e associamo il preventivo quando è presente la lavorazione.

**Comment by loviuz** [comment]
Ciao @sajotrei, intendi quindi poter creare l'attività senza che ci sia volutamente almeno una riga selezionata da riportare da preventivo ad attività?

**Comment by sajotrei** [comment]
Ciao @loviuz, 
scusami non avevo visto la tua domanda.

si esatto.

come ho indicato sopra, è utile come processo di lavoro.
non devo necessariamente evadere qualcosa come se fosse un ddt

**Comment by Pek5892** [comment]
Introdotto in release, disponibile dalla versione 2.7
