### ISSUE TITLE
Data conclusione preventivo

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1085]
## Comportamento richiesto

Ci si aspetta che la data conclusione sia impostata in automatico tenendo conto della data accettazione + il valore indicato in tempi di consegna. 

Es.
data accettazione : 13/09/2022
tempi di consegna : 5 giorni
data conclusione : 18/09/2022

## Comportamento attuale

la data conclusione NON viene influenzata dal valore del campo "Validità", né dal valore del campo "tempi di consegna".

analizzando il file /preventivi/edit.php
sembra esserci dei riferimenti ma non funziona

![Screenshot 2022-09-14 alle 16 08 03](https://user-images.githubusercontent.com/75281007/190178842-97dac9bd-ffc4-49bb-a855-d3411cba396a.png)
![Screenshot 2022-09-14 alle 16 08 21](https://user-images.githubusercontent.com/75281007/190178846-998c65c2-ea90-417f-9583-6d57b37b75dd.png)

**Ps.** tra altro non esce il campo Help a fianco delle data conclusione, anche se nel codice ci sono i riferimenti.

![Screenshot 2022-09-14 alle 16 15 56](https://user-images.githubusercontent.com/75281007/190179581-8f6d854f-cbb7-42a4-882e-0c491a0e1f21.png)
![Screenshot 2022-09-14 alle 16 16 16](https://user-images.githubusercontent.com/75281007/190179588-3c8c3ecf-ed1b-4214-889b-d4fde7b5ae97.png)

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
come specificato dall'help della validità offerta, la data conclusione viene calcolata automaticamente in caso non sia stato impostato un valore di Validità offerta manuale (dal menu a tendina andando a selezionare quindi le opzioni che escludono la scelta manuale della data di conclusione). In questo modo la data di conclusione viene correttamente calcolata.
![immagine](https://user-images.githubusercontent.com/102604205/201127887-776b51ec-a054-4e1b-8b54-815c7aa61110.png)

**Comment by sajotrei** [comment]
Ciao Valentina, 
grazie del riscontro, ma sinceramente sembra esserci qualcosa che no va.
ho provato su una installazione pulita agg. alla 2.4.37 e non funziona come hai descritto.

inoltre ho notato che nella tua immagine è presente l'help in data conclusione, aspetto che avevo evidenziato.
hai una versione più recente ?

![Screenshot 2022-11-11 alle 11 31 24](https://user-images.githubusercontent.com/75281007/201321984-26785cc4-e259-47fe-8d5f-ede39e9fac99.png)

**Comment by Pek5892** [comment]
![immagine](https://user-images.githubusercontent.com/102604205/201362533-74ebbb08-0e60-4ef4-bc6d-c248069bc2b1.png)

Lo screenshot di ieri, come questo, sono di una versione 2.4.37 pulita, eseguendo i seguenti passaggi:
1- Valorizzati Validità offerta e Data accettazione
2- messo in stato Accettato il preventivo
viene così automaticamente calcolato il campo Data conclusione, e appare l'help (che si visualizza solo nel caso in cui il campo Data conclusione sia disabilitato).
Dovresti provare a verificare l'installazione

**Comment by sajotrei** [comment]
ora più chiaro e logico 



![Image](https://github.com/user-attachments/assets/3f7bc6fb-c242-426b-b52d-dd35ee6ce6ea)
