### ISSUE TITLE
non funziona la Variabile {ragione_sociale} nel template email DDT

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1086]
## Comportamento richiesto

La variabile {ragione_sociale} del template email DDT non funziona

## Passi per riprodurre il comportamento
![templat mail](https://user-images.githubusercontent.com/75281007/190388846-f30c8926-8e55-4422-87e9-e4c0f2d19e37.png)

![variabili](https://user-images.githubusercontent.com/75281007/190388862-d178f0c7-f268-42cc-9838-37d68a7a3cda.png)

![invio ddt via mail](https://user-images.githubusercontent.com/75281007/190388882-d531d83c-bb63-43f7-bc47-f6a8cfa3cf8a.png)

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Abbiamo risolto nella versione che stiamo rilasciando, grazie della segnalazione :)
