### ISSUE TITLE
in Dashboard la possibilità di avere 6 widgets per fila

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1088]
## Comportamento richiesto

in Dashboard la possibilità di **avere 6 widgets per fila**

<img width="1922" alt="modificato" src="https://user-images.githubusercontent.com/75281007/191006553-ea810d00-17b2-4210-98f4-57862b39642a.png">

## Comportamento attuale

Attualmente si vedo 4 widgets per fila, riempiendo così gran parte dello schermo sia sui desktop ma in particolare su Devices mobile rendendo scomoda la gestione.

<img width="1922" alt="originale" src="https://user-images.githubusercontent.com/75281007/191006278-538822f7-0ca5-48e7-b1fa-cac0908e1481.png">

## Possibile soluzione

basterebbe modificare in relase questo valore nel seguente file.
/src/HTMLBuilder/Manager/**WidgetManager.php**

![WidgetManager](https://user-images.githubusercontent.com/75281007/191006236-907666ee-10e9-4f88-ac51-9cdd27f68a61.png)

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei, questa sembrerebbe più una personalizzazione che un vero e proprio problema...

**Comment by sajotrei** [comment]
Ciao Valentina, 
in realtà è un suggerimento lato pratico per l'uso quotidiano del gestionale anche su tablet e smartphone.
dato che stiamo proponendo OSM anche a i nostri clienti, riteniamo valida questa modifica anche per gli altri.

invece per noi non c'è problema, anche perché già usiamo questa modifica da circa un'anno.
anche se ad ogni aggiornamento di OSM si sovrascrive la modifica al file...

**Comment by sajotrei** [comment]
se propongo non la si vuole mettere come relase

un'idea potrebbe essere quella di aggiungerla in impostazioni, così che la sceglie l'utente secondo la preferenza.
che ne dite ?

**Comment by kenchu84** [comment]
Ciao, se puo interessare io ho risolto aggiungendo un opzione in Dashboard (Widget per riga) e richiamando tale variabile in 
/src/HTMLBuilder/Manager/WidgetManager.php alla riga 248 con la variabile '.$options['maxwidget'].'

A presto

**Comment by sajotrei** [comment]
Ciao, @kenchu84 

non mi è chiara questa modifica, ho provato ma di fatto penso peggiori la visualizzazione dei widgets
probabilmente ho sbagliato qualcosa

<img width="431" alt="Screenshot 2023-01-25 alle 12 58 34" src="https://user-images.githubusercontent.com/75281007/214557804-1733706a-c42b-4561-8490-5e46836ff3f5.png">

...comunque, noi abbiamo già introdotto la modifica che abbiamo indicato nel post.
il punto è che **a ogni aggiornamento si sovrascrive il file e bisogna rifare la modifica.**

se si potesse mettere in relase e come opzione, ognuno la abilita secondo preferenza.😉

**Comment by kenchu84** [comment]
noi abbiamo fatto cosi: 

// 20220622_Generazione del codice HTML per supportare numero variabile di Widget in base all'opzione in settaggi.
        if (!empty($widgets)) {
            $row_max = '.$options['maxwidget'].';

Devi indicare $row_max  perche viene richiamato anche nella riga 278 per la creazione stessa. 

Penso che lavorando con un impostazione editabile dai settaggi, sia piu probabile che accettino il pull.

**Comment by kenchu84** [comment]
Scusa, ho sbagliato, ho preso il file da una vecchia versione. Ecco le righe giuste!

 if (!empty($widgets)) {
            $row_max =setting('Numero massimo Widget in Dashboard');

**Comment by sajotrei** [comment]
ok come non detto 😅

attendo eventuale modifica lato relase 🤞
speriamo che le tue info possano essere di spunto 😉

**Comment by kenchu84** [comment]
Eseguito. Spero di aver fatto giusto. 

PS. evitiamo di darci del Lei ?  :)

**Comment by Pek5892** [comment]
Implementato con fix: https://github.com/devcode-it/openstamanager/commit/791ea68abdb8643a3b631e8aafdd7530fc4d9ca0
