### ISSUE TITLE
In consuntivo preventivi sono invertite le colonne Km-Ore

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1089]
## Comportamento richiesto

In consuntivo preventivi sono invertite le colonne Km-Ore

## Comportamento attuale

![Screenshot 2022-09-26 alle 13 22 59](https://user-images.githubusercontent.com/75281007/192264873-e16ae1cf-0b24-4303-a148-23e86b6f70ca.png)

## Passi per riprodurre il comportamento

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit: 29388fdabd6a49cad8ea5c76a29d94d95e086abe
