### ISSUE TITLE
Domanda: sincronizzazione interventi attraverso API 

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#109]
Come viene settato 'idtecnico'? Mi spiego : 

Uso icalsync2 su Android e tramite link mi ritrovo i dati nel calendario del device.
Ma questo perche ho modificato il file /modules/interventi/api/retrieve.php alla riga 8
        if ($idtecnico != '0') {
in 
        if ($idtecnico != '') {

"idtecnico" non viene mai settato nell' API . Si tratta di un errore oppure la sincronizzazione in tal maniera non è ancora prevista?

**Comment by fpsoftware** [comment]
Ciao @lepool inizieremo a breve test anche  su questa parte del programma, le API sono diventate importanti, oltre per icalsync e simili, anche per una app che possa interagire con il sistema,  quindi avremo parecchie procedure da vedere! Grazie per il tuo aiuto!

**Comment by Dasc3er** [comment]
@lepool In effetti si trattava di un errore di importazione del codice dalla versione originaria della sincronizzazione calendario.
In teoria, aggiornando con il commit 207108e02b501ecbdf87a4a8a9359dcef6044e8a (e forse anche alla versione 2.4), il problema dovrebbe risolversi.
