### ISSUE TITLE
bug stampa di ore in decimale

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1091]
## Comportamento richiesto
stampa ore in sessantesimi

## Comportamento attuale
Nelle attività segue le impostazioni di sistema in riepilogo le stampa in formato decimi

## Possibile soluzione
Seguire la selezione di impostazioni->attività->formato di ore in stampa

## Passi per riprodurre il comportamento
1. effettuare una stampa di riepilogo attività

Eventuale codice rilevante:
template/riepilogo_interventi

* Modulo: riepilogo interventi
* Versione del progetto: 2.4.34 (4a0772f7f)
* Versione PHP: 7.4.30

**Comment by Pek5892** [comment]
Buongiorno, non riusciamo a riprodurre l'errore. Con una sessione di lavoro dalle 10 alle 19:30:
- se impostato in sessantesimi viene mostrato 9:30,
- se impostato in decimale viene mostrato 9,50.

**Comment by Pek5892** [comment]
Risolto con commit 672b443545ac3f55326ca774c08ba02a7b7b343a
