### ISSUE TITLE
Movimenti Vendita al banco in scadenziario

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1093]
## Comportamento richiesto

Ci si aspetta che il movimento contabile della vendita al banco sia presente nello scadenzario.
di solito i pagamenti sono rimessa diretta e carta, così risultano pagati al momento delle vendita.

ma si usano anche altre forme di pagamento per agevolare il cliente, come il prestito, bonifici, e altro, pertanto legare la vendita al banco ( scontrino ) a uno scadenzario diventa essenziale.

## Comportamento attuale

attualmente il modulo non si "interfaccia" con lo scadenzario del programma

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Modifica messa in lista per l'implementazione nel modulo
