### ISSUE TITLE
Possibilità disattivare anagrafica

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1095]
## Comportamento richiesto

sarebbe molto utile poter **disattivare**/attivare una anagrafica, un po come si fa già con gli articoli

![Screenshot 2022-10-11 alle 12 22 52](https://user-images.githubusercontent.com/75281007/195065841-e2018e1d-5087-401b-9bf0-bf4e81ad99c2.png)

## Possibile soluzione

creare un flag Attivato/Disattivato qualcosa di simile a quello presente in articoli.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
se la funzione è quella di non utilizzare l'anagrafica nei nuovi documenti, è consigliata la sua eliminazione da gestionale.
Eliminandola, essa non perderà il collegamento con i documenti esistenti e da essi si potrà visualizzare la ragione sociale seguita da "(eliminata)" e si potrà accedere ai relativi dati da Visualizza scheda.
![immagine](https://user-images.githubusercontent.com/102604205/195072232-868086f9-9d14-4546-96b1-f96ed1efbb0f.png)

**Comment by lucasalva87** [comment]
Ciao, ricordo anche, nel caso possa essere d'aiuto, la possibilità di utilizzare l'apposito flag di blocco presente della scheda relazione.
L'anagrafica bloccata continuerà ad esistere ma non potrà più essere selezionata per attività, contratti ecc..

![immagine](https://user-images.githubusercontent.com/30728163/195086606-6463cf47-8f81-45e4-ac4d-2344313f14da.png)

**Comment by sajotrei** [comment]
Grazie a tutti per il riscontro.
proviamo la soluzione che ha suggerito Lucasalva87, che non avevamo fatto caso ci fosse.

**Comment by sajotrei** [comment]
> Ciao, sulla nostra versione l'ho fatta questa modifica perche mi e' comodo poter tracciare le anagrafiche non piu attive, ma che comunque ho necessità di elencare in altri moduli, magari di cui ho insoluti. Se ti interessa posso darti codice e modifiche alla tabella an_anagrafiche.
> 
> Luca

Ciao Luca, interessate, se vuoi comunque postare la modifica, così può tonare utile più avanti.
grazie
