### ISSUE TITLE
Articolo non disponibile in attività

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1096]
## Comportamento richiesto
Possibilità di inserire articoli in una attività

## Comportamento attuale
Al momento mi ritrovo bloccati: "Preventivo" "Contratto" "ddt" e "Articolo"

* Modulo: Interventi
* Versione del progetto:  2.4.34 (4a0772f7f)
* Versione PHP: 7.4.32
* Tipo di server:  MariaDB 10.3.36

**Comment by lucasalva87** [comment]
Ciao, avevi provato a dare un'occhiata alla nostra documentazione? 

https://docs.openstamanager.com/v/2.4.36/guide/esempi/magazzino#utilizzare-articoli-con-quantita-negativa-nei-documenti

Non è che il blocco dipende da una giacenza negativa?

**Comment by bulleITA** [comment]
era per giacenza negativa. grazie.
