### ISSUE TITLE
in riepilogo interventi, distinzione visiva tra interventi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1099]
## Comportamento richiesto

inserire una divisione visiva, tra un'intervento e l'altro, aiuterebbe a una visione più chiara e distintiva tra le righe.

## Comportamento attuale

![1](https://user-images.githubusercontent.com/75281007/196154476-69b673cd-41e1-4710-804a-6bb2d5586264.png)

## Possibile soluzione

potrebbe essere sufficiente inserire una riga nera più spessa.

![2](https://user-images.githubusercontent.com/75281007/196154449-fb2b063c-b2bd-4a07-b7bb-017ab440d4cd.png)

**Comment by Pek5892** [comment]
Ciao @sajotrei,
stiamo lavorando a delle migliorie sulle stampe, lo prenderemo in considerazione per le prossime release :)

**Comment by sajotrei** [comment]
Ciao, ma purtroppo **rimane il problema distinzione tra interventi**, spesso ci viene fatto notata che è confusionaria.
l'introduzione suggerita di barra aiuta 


![Screenshot 2024-08-30 alle 17 38 09](https://github.com/user-attachments/assets/c64bd8da-46ca-42d8-aa95-560390412830)

**Comment by sajotrei** [comment]
non è proprio possibile introdurre una distinzione? 
come suggerito nel post, potrebbe bastare una barra evidenziata tra le attività 

![Screenshot 2024-10-22 alle 17 50 31](https://github.com/user-attachments/assets/582332bc-2caa-4f31-97a5-b01d366a7e76)
