### ISSUE TITLE
ATTIVITA' - proposta modifica stampa intervento

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#110]
Nella stampa di intervento nella sezione "ORE TECNICI" -> Costo Orario per poter dare al cliente un documento il meglio leggibile e comprensibile possibile non sarebbe meglio inserire i tre campi
Costo orario:
Costo trasferta:
Diritto di Chiamata:
al posto di mettere il costo medio+d.c. di difficile comprensione?
Anche perchè il costo della trasferta non è riportato in nessuna sezione.

**Comment by loviuz** [comment]
certamente, più che altro perché abbiamo ricevuto un'altra segnalazione stamattina, e cioè che la trasferta non esce, neanche sull'ultimissima versione

**Comment by mdkdog** [comment]
Ciao tutti!
Visto che qualquno ci mette le mani su codice, non sarebbe male ripristinare anche la tipologia di intervento ("Generico", "Ordine di servizio" ... ) sulla stampa.

**Comment by loviuz** [comment]
ho aggiunto il tipo intervento che mancava, e inserito un po' di dati che mancavano, tra cui il totale km, il diritto di chiamata a parte e ho evidenziato meglio lo sconto totale, in questo esempio c'è un 10% di sconto sulle ore, però avendo più sessioni di lavoro che possono avere sconti diversi, non è facilmente fattibile mettere quel 10% visibile in stampa... :-\

comunque la stampa ora esce così, con del materiale e sconti vari:
![immagine](https://user-images.githubusercontent.com/1647128/35172791-5c084948-fd69-11e7-8420-e150a872583d.png)

**Comment by antonioscarpino** [comment]
Solitamente al costo della manodopera non possono essere applicati sconti.
Perchè sotto il costo determinato dalle varie regioni o dal codice appalti non si può andare, ed è comunque un errore applicare uno sconto sulla manodopera su un documento ufficiale che poi si lascia al cliente.
Quindi io eliminerei lo sconto sulla manodopera anche perchè sul documento non è chiaro la scontistica applicata.
Nel caso che hai portato tu essendo un costo di 40 € orario e applicando il 10% di sconto è facile per il cliente fare il conto.
Ma se il costo della manodopera non 28,70€ e lo sconto fosse per esempio 8% far capire al cliente che è stato applicato uno sconto dell'8% sulla manodopera senza un rifarimento sul rapporto diventa un po complicato.

**Comment by loviuz** [comment]
in questo modo c'è tutta la flessibilità che si vuole. se poi non si vuole utilizzare lo sconto sulla manodopera si lascia lo sconto vuoto. molte persone lo usano.

sui km invece, forse non è chiaro come l'ho impostato, perché il "Costo km" dell'esempio è già il totale, altrimenti non ci stava il diritto di chiamata.

se avete qualche idea di come mostrare i costi fate pure qualche screenshot, bel frattempo provo a pensare anch'io come visualizzarli meglio. tanto poi i clienti ci fanno sempre personalizzare questa stampa perché ognuno lavora in modo diverso 😀

**Comment by antonioscarpino** [comment]
Si per lo sconto sulla manodopera se si vuole mettere si mette o no però era per evidenziare la poca chiarezza dovuta al fatto che lo sconto non viene riportato nella stampa.
Per quanto riguarda i costo/km un'idea potrebbe essere questa
![stampa](https://user-images.githubusercontent.com/34765237/35185701-b837145c-fe08-11e7-9900-919ad17e1f0d.jpg)

**Comment by loviuz** [comment]
mi piace. l'unica cosa è che metterei il diritto di chiamata subito nella seconda riga, in modo che il costo/km e il totale costo km siano sotto il costo unitario manodopera e costo totale manodopera

**Comment by antonioscarpino** [comment]
Ok ottimo

**Comment by loviuz** [comment]
Dato che i costi orario e al km possono essere diversi sessione per sessione, ho valutato che forse il modo più semplice per visualizzare un riepilogo sia quello che allego di seguito.

**SENZA COSTI**
![immagine](https://user-images.githubusercontent.com/1647128/35282398-a9e45e56-0055-11e8-874d-20aeddfd4d1f.png)

**CON COSTI**
![immagine](https://user-images.githubusercontent.com/1647128/35283127-a060d9d4-0057-11e8-9d10-3d505fd55200.png)
