### ISSUE TITLE
Seriali da ordine fornitore a import FE

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1101]
## Comportamento richiesto

i **seriali** nell'articolo indicato nell'ordine fornitore non vengono riportati nella **fattura FE in fase di import**, quando si associa l'ordine.

invece in queste situazioni funziona correttamente:
( non più in uso per via della FE)
- se da ordine fornitore si crea direttamente la fattura.
- se si crea a mano un nuova fattura fornitore e si importa un ordine fornitore.

## Comportamento attuale

<img width="1477" alt="ORDINE FORNITORE" src="https://user-images.githubusercontent.com/75281007/196800618-32c0dc07-bc7a-48f2-9406-0b29fa3057ee.png">
<img width="1380" alt="IMPORTAZONE FE ASSICIAZIONE RIGA ORDINE" src="https://user-images.githubusercontent.com/75281007/196800657-f53277d1-1c57-41ca-82d0-7bc4f3e2af8b.png">

<img width="945" alt="RIGA ART FATTURA SENZA SERIALI" src="https://user-images.githubusercontent.com/75281007/196800679-83c02608-f50a-44b5-a997-50b0f66c5f08.png">

## Passi per riprodurre il comportamento

- si crea un ordine a fornitore con articoli con seriale
- si importa la fatture FE
- si associano gli articoli all'ordine fornitore
- si salva/registra la FE
- i seriali nella fattura non sono presenti, anche se associati all'ordine fornitore dove erano indicati.

**Comment by sajotrei** [comment]
se si inserisco i seriali nell'ordine fornitore e poi lo si importa in fase di registrazione FE passiva
considerando che non riporta il valore dei seriali dall'ordine alla fattura
non possibile associarli neanche manualmente perché risultano già in un'altro documento ( appunto ordine fornitore )

<img width="1716" alt="Screenshot 2023-03-14 alle 11 41 01" src="https://user-images.githubusercontent.com/75281007/224977298-99c7b56c-824b-41af-aef9-69cd14584c6e.png">

**Comment by sajotrei** [comment]
stesso problema si presenta anche con i DDT di entrata

**Comment by Pek5892** [comment]
Risolto nella versione 2.4.52 in release
