### ISSUE TITLE
Errore modifica colore tecnico

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1102]
## Comportamento richiesto

se si prova a modificare il colore, si crea un codice colore non valido e da errore.

## Comportamento attuale

![1](https://user-images.githubusercontent.com/75281007/196950542-a6377ed4-ad19-42b8-b2e3-87978206e6ec.png)
![2](https://user-images.githubusercontent.com/75281007/196950548-c5766141-c57e-4c12-ab93-fcb2856aaf9d.png)
![3](https://user-images.githubusercontent.com/75281007/196950550-6b22a950-55d8-45c6-8bbc-e1f96ff0a261.png)

## Passi per riprodurre il comportamento

dopo avere selezionato il colore, provare a schiarirlo con la barra laterale.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit 9b22b07dcf01fc0ea785b4ab7c5f8190d4afa47c
