### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#1108]
## Comportamento richiesto

Con la rimozione dei filtri, mi aspetto la visualizzazione di tutti i record.

## Comportamento attuale

Genera l'errore riportato nello screen allegato e non rimuove i filtri.

## Passi per riprodurre il comportamento

Non ne sono certo perché capita solo occasionalmente.

Eventuali log relativi (cartella **logs/**):
Ho controllato i log, non sono riportati errori riferiti a questo.

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: In questo caso nello "Scadenzario", ma mi è capitato anche in altri moduli.
* Versione del progetto: 2.4.36
* Versione PHP: 7.4.32
* Tipo di server: Hosting

![immagine](https://user-images.githubusercontent.com/48417686/201184847-f845cc33-2f84-4f2f-8ebd-6a73ed22c558.png)

**Comment by Pek5892** [comment]
Salve @cristianviale, potrebbe provare a verificare la sua installazione? 
[Guida](https://docs.openstamanager.com/v/2.4.37/guide/esempi/verificare-linstallazione-di-osm)

**Comment by cristianviale** [comment]
Grazie per il riscontro @Pek5892.
Vado per ordine: per quanto riguarda i requisiti ho un problema col modulo "mod_rewrite" che sto tentando di risolvere. Per quanto riguarda la mysql_version: "Valore consigliato: 5.7.x - 8.0.x (Valore attuale: 10.3.36)".

Per quanto riguarda il controllo file (ho apportato delle modifiche alle stampe):
![image](https://user-images.githubusercontent.com/48417686/201313685-202e8022-9a8f-42a8-bafa-afecca41358b.png)

Per quanto riguarda il database l'unico problema è questo:
![image](https://user-images.githubusercontent.com/48417686/201313936-e5464290-2ef8-4d9d-8130-c23386e815b8.png)

I controlli del gestionale non riporta alcun errore.

Nel tab non risultano personalizzazioni, ma in questa installazione è stato installato un modulo personalizzato acquistato direttamente da DevCode. Cosa comunque poco rilevante perché ho lo stesso problema su un'altra installazione che non ha questo modulo.

**Comment by Pek5892** [comment]
MySQL "Valore consigliato: 5.7.x - 8.0.x (Valore attuale: 10.3.36)", MariaDB non è pienamente supportato dal gestionale. Dovrebbe provare a utilizzare MySQL e installare il modulo mod_rewrite.

**Comment by cristianviale** [comment]
MariaDB è completamente open-source mentre MySQL no, inoltre è anche molto più performante... Non avrebbe molto senso.
A parte questo, a me sembra più un problema con AJAX...

**Comment by Pek5892** [comment]
Ci servirebbe vedere l'errore della chiamata AJAX, può trovarlo così:
https://stackoverflow.com/a/63786792

**Comment by cristianviale** [comment]
Risolto: si tratta di una protezione dell'hosting.
Grazie
