### ISSUE TITLE
Riferimento riga Ordine Cliente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1109]
## Comportamento richiesto

In Ordine Cliente, cliccando su Riferimenti nella riga articolo, ci si aspetta che nell'elenco **siano visibili solo gli Ordini a fornitore**.

## Comportamento attuale

![1](https://user-images.githubusercontent.com/75281007/202198459-d8b6940c-8640-4b5e-ac40-44d8d165aa50.png)

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/d539d383bcc464f40012568d41e6d1196c23b035
