### ISSUE TITLE
FATTURE VENDITA - errore nella creazione delle stampe

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#111]
generando la stampa di una fattura di vendita (non ho provato ma penso che a questo punto l'errore sia un po in tutte le generazioni di stampa) con una descrizione lunga, il testo non va a capo rendendo quindi non leggibile le righe della fattura

![errore](https://user-images.githubusercontent.com/34765237/34881981-5996524a-f7b5-11e7-9183-dc94340366c3.png)

**Comment by Dasc3er** [comment]
Ciao @antonioscarpino,
il problema in questione è caratteristico della libreria mPDF utilizzata a partire dalla nuova versione per la generazione dei PDF (come accennato [qui ](https://devcode-it.github.io/openstamanager/stampe.html#mpdf)n ella documentazione ufficiale).

Si verifica in particolare quando i contenuti di una riga di una tabella sono talmente tanti da non poter stare all'interno di una singola pagina: mPDF reagisce quindi riducendo la dimensione del carattere utilizzato.
Puoi temporaneamente rimuovere il problema riducendo i contenuti della riga.

Mi sembra comunque strano che il comportamento si sia verificato con un testo così ridotto in dimensioni...

**Comment by antonioscarpino** [comment]
Per risolvere temporaneamente il problema basta dare una formattazione al testo, inserendo i vari a capo e cercando di non scrivere linee troppo lunghe massimo 5/6 parole a riga.
In questo modo il testo rimane nei limiti della tabella.
La cosa strana è che l'errore no si presenta sempre anche se magari si inseriscono righe anche più lunghe di quella in esempio.

**Comment by antonioscarpino** [comment]
Ok l'errore sembra essere causato dall'inserimento di un carattere speciale nel mio caso " ° " (infatti nella descrizione era riportato " piano 1° ") togliendo il carattere speciale la formattazione è tornata normale senza l'errore di resize pur mantenendo la lunghezza della riga invariata

**Comment by antonioscarpino** [comment]
Confermato il problema viene dato da alcuni caratteri speciali e dalle lettere accentate (ò, à, ù, è, é, ì, °) non inserendo questi caratteri l'errore di resize non si presenta

**Comment by Dasc3er** [comment]
@antonioscarpino Il problema con le lettere accentate dovrebbe essere stato risolto con il commit 0c0c5c613aeeab55288d1e9aa3baeb4b1585eed4, se puoi confermare...
Sono riuscito ad impostare correttamente la visualizzazione di questi caratteri attraverso la codifica del PDF in utf-8, che però ha richiesto l'inclusione di alcuni file di font di MPDF. Di conseguenza lo zip della release risulterà leggermente più grande (sui 14 MB rispetto ai precedenti 12 MB)...

**Comment by Dasc3er** [comment]
In ogni caso, rimane il problema generico di MPDF con le tabelle per cui se i contenuti di una riga sono eccessivi, la dimensione del carattere viene ridotta.
**In ogni caso si dovrebbe trattare di una condizione estremamente particolare, e non dovrebbe presentarsi nei casi normali di utilizzo del gestionale.**

**Comment by antonioscarpino** [comment]
Ti confermo che aggiornado al commit il problema viene risolto
