### ISSUE TITLE
Articolo, quantità impegnata

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1111]
## Comportamento richiesto

Abbiamo provato a fare un preventivo con articolo a magazzino, poi confermato e trasformato come ordine cliente.
ci sia spetta che l'ordine cliente in stato accettato, influisca nel magazzino nella colonna Q.tà impegnata dell'articolo in questione.

## Comportamento attuale

attualmente anche se esiste un articolo in un ordine cliente con stato accettato, non influisce nella quantità.
se invece facciamo un ordine fornitore, influisce correttamente nella colonna Q.tà ordinata 👍

![1](https://user-images.githubusercontent.com/75281007/202687519-956c9fef-f782-4b6d-9b35-4e5bb1740bf6.png)

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
in un'installazione pulita della v.2.4.37 non riusciamo a riprodurre l'errore.
Le quantità impegnata e ordinata ci risultano correttamente movimentate.
![immagine](https://user-images.githubusercontent.com/102604205/203006396-ec7283f1-9be8-49a8-af42-643ee6151d15.png)
![immagine](https://user-images.githubusercontent.com/102604205/203006419-b809ac9b-f213-4e94-8b12-c7a883d23aa5.png)

**Comment by sajotrei** [comment]
Ciao Valentina, anche io ho fatto la prova su una installazione pulita 2.4.37.

funziona correttamente se è abilitata questa impostazione, perché nell'articolo era abilitato il seriale anche se non è presente.

altrimenti non tiene conto della movimentazione
![seriale](https://user-images.githubusercontent.com/75281007/203019592-9ad6907a-a1f1-483a-95c2-73198a501b5f.png)

**Comment by Pek5892** [comment]
Ciao @sajotrei,
il comportamento risulta quindi corretto per logica, in base alla selezione dell'impostazione.
