### ISSUE TITLE
Query vista DDT Uscita - colonna inviato

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1112]
## Comportamento richiesto

potrebbe essere utile avere la colonna **inviato** via mail in DDT in uscita

## Possibile soluzione

SELECT |select|
FROM dt_ddt
LEFT JOIN an_anagrafiche ON dt_ddt.idanagrafica = an_anagrafiche.idanagrafica
LEFT JOIN dt_tipiddt ON dt_ddt.idtipoddt = dt_tipiddt.id
LEFT JOIN dt_causalet ON dt_ddt.idcausalet = dt_causalet.id
LEFT JOIN dt_spedizione ON dt_ddt.idspedizione = dt_spedizione.id
LEFT JOIN an_anagrafiche vettori ON dt_ddt.idvettore = vettori.idanagrafica
LEFT JOIN an_sedi AS sedi ON dt_ddt.idsede_partenza = sedi.id
LEFT JOIN an_sedi AS sedi_destinazione ON dt_ddt.idsede_destinazione = sedi_destinazione.id
LEFT JOIN (
SELECT idddt,
SUM(subtotale - sconto) AS totale_imponibile,
SUM(subtotale - sconto + iva) AS totale
FROM dt_righe_ddt
GROUP BY idddt
) AS righe ON dt_ddt.id = righe.idddt
**LEFT JOIN (
SELECT GROUP_CONCAT(DISTINCT co_documenti.numero_esterno SEPARATOR ", ") AS info, co_righe_documenti.idddt FROM co_documenti INNER JOIN co_righe_documenti ON co_documenti.id = co_righe_documenti.iddocumento GROUP BY idddt
) AS fattura ON fattura.idddt = dt_ddt.id
LEFT JOIN (
SELECT zz_operations.id_email, zz_operations.id_record
FROM zz_operations
INNER JOIN em_emails ON zz_operations.id_email = em_emails.id
INNER JOIN em_templates ON em_emails.id_template = em_templates.id
INNER JOIN zz_modules ON zz_operations.id_module = zz_modules.id
WHERE zz_modules.name = 'Ddt di vendita' AND zz_operations.op = 'send-email'
GROUP BY zz_operations.id_record
) AS email ON email.id_record = dt_ddt.id**
WHERE 1=1 AND dir = 'entrata' |date_period(data)|
HAVING 2=2
ORDER BY data DESC, CAST(numero_esterno AS UNSIGNED) DESC,dt_ddt.created_at DESC

![vista](https://user-images.githubusercontent.com/75281007/203022469-7fd55355-5c71-43e1-a796-f06bb96a7cc8.png)

![invio mail ddt](https://user-images.githubusercontent.com/75281007/203022740-117e37a6-0ece-4054-a219-de52b40ea901.png)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Aggiunta colonna inviato in DDT in uscita, di default nascosta.
https://github.com/devcode-it/openstamanager/commit/84867671b278ce17d41fd225d08bddf42f3a7218
