### ISSUE TITLE
Listino clienti

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1114]
## Comportamento richiesto

In articolo, listino clienti, Sarebbe utile poter indicare il **_gruppo clienti_** per Tipologia ( Privati o Azienda )

![listino articolo](https://user-images.githubusercontent.com/75281007/203364947-0dc35814-a8f6-4144-a17a-c87429bc4f0f.png)

[https://gestionale.blog/gestione-di-magazzino/](url)

![Screenshot 2022-11-22 alle 17 12 14](https://user-images.githubusercontent.com/75281007/203364839-30ebabc7-fe94-4f98-9ed2-75b7cb4c011d.png)

## Comportamento attuale

attualmente è possibile indicare un solo cliente/anagrafica alla volta

## Possibile soluzione

permettere di selezionare anche il **gruppo clienti che appartiene alla tipologia Azienda e Privato.**

**Comment by Pek5892** [comment]
Chiudo perchè duplicato https://github.com/devcode-it/openstamanager/issues/1423
