### ISSUE TITLE
Import anagrafice con php8.0 errore type error

### ISSUE THREAD

**Issue by Andi-bz** [devcode-it/openstamanager#1115]
## Comportamento richiesto

Importazione da file csv.

## Comportamento attuale

Con php8.0 mi da errore:
`[2022-11-23 09:02:54] Logs.ERROR: Uncaught Exception TypeError: "Unsupported operand types: string - int" at /var/www/html/osm/modules/import/actions.php line 72 {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string - int at /var/www/html/osm/modules/import/actions.php:72)"}`

## Possibile soluzione

 PHP7.4 crea solo un WARNING e il import funziona. Con php8.0 ho un FATAL error e il import non funziona

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Installare il gestionale con php8.0
2. Scaricare il esempio anagrafica nel modulo import
3. Importare il esempio 

Eventuale codice rilevante:

Eventuali log relativi (cartella **logs/**):
`[2022-11-23 09:02:54] Logs.ERROR: Uncaught Exception TypeError: "Unsupported operand types: string - int" at /var/www/html/osm/modules/import/actions.php line 72 {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string - int at /var/www/html/osm/modules/import/actions.php:72)"}`

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Import
* Versione del progetto: 2.4.37
* Versione PHP: 7.4 e 8.0
* Tipo di server: Ubuntu 22.04

**Comment by Pek5892** [comment]
Risolto con commit 00407e11365130129d8897c94a09f7f144973e73
