### ISSUE TITLE
Colonna Print

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1116]
## Comportamento richiesto

sarebbe utile avere la colonna Print anche sul altri documenti oltre a interventi.
- Preventivi
- Ordini Cliente
- DDT
- Fatture

## Comportamento attuale

attualmente è disponibile solo in attività/interventi

<img width="178" alt="print" src="https://user-images.githubusercontent.com/75281007/203574223-b53ef87e-1181-4bbf-a791-e6632ddfbd28.png">

<img width="436" alt="1" src="https://user-images.githubusercontent.com/75281007/203574331-f4ff67c6-7c22-475a-a095-111c2c8cbd3f.png">

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Aggiunto disattivato di default https://github.com/devcode-it/openstamanager/issues/1116
