### ISSUE TITLE
Query vista interventi - colonna contratto

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1117]
## Comportamento richiesto

potrebbe essere utile la **colonna contratto** in elenco attività/interventi

## Possibile soluzione

SELECT |select| FROM `in_interventi`
INNER JOIN `an_anagrafiche` ON `in_interventi`.`idanagrafica` = `an_anagrafiche`.`idanagrafica`
LEFT JOIN `in_interventi_tecnici` ON `in_interventi_tecnici`.`idintervento` = `in_interventi`.`id`
LEFT JOIN `in_interventi_tecnici_assegnati` ON `in_interventi_tecnici_assegnati`.`id_intervento` = `in_interventi`.`id`
LEFT JOIN (SELECT idintervento, SUM(prezzo_unitario*qta-sconto) AS ricavo_righe, SUM(costo_unitario*qta) AS costo_righe FROM `in_righe_interventi` GROUP BY idintervento) AS righe ON righe.`idintervento` = `in_interventi`.`id`
LEFT JOIN `in_statiintervento` ON `in_interventi`.`idstatointervento`=`in_statiintervento`.`idstatointervento`
LEFT JOIN (
 SELECT an_sedi.id, CONCAT(an_sedi.nomesede, '<br />',IF(an_sedi.telefono!='',CONCAT(an_sedi.telefono,'<br />'),''),IF(an_sedi.cellulare!='',CONCAT(an_sedi.cellulare,'<br />'),''),an_sedi.citta,IF(an_sedi.indirizzo!='',CONCAT(' - ',an_sedi.indirizzo),'')) AS info FROM an_sedi
) AS sede_destinazione ON sede_destinazione.id = in_interventi.idsede_destinazione
LEFT JOIN (
 **SELECT co_contratti.id, CONCAT('Contratto ', numero, ' del ', DATE_FORMAT(data_bozza, '%d/%m/%Y'), ' - ', co_contratti.nome, ' [', (SELECT `descrizione` FROM `co_staticontratti` WHERE `co_staticontratti`.`id` = co_contratti.`idstato`) , ']') AS info FROM co_contratti
) AS contratto ON contratto.id = in_interventi.id_contratto
LEFT JOIN (**
 SELECT GROUP_CONCAT(DISTINCT co_documenti.numero_esterno SEPARATOR ", ") AS info, co_righe_documenti.original_document_id AS idintervento FROM co_documenti INNER JOIN co_righe_documenti ON co_documenti.id = co_righe_documenti.iddocumento WHERE original_document_type='Modules\\Interventi\\Intervento' GROUP BY co_documenti.id, idintervento
) AS fattura ON fattura.idintervento = in_interventi.id
LEFT JOIN (SELECT `zz_operations`.`id_email`, `zz_operations`.`id_record`
        FROM `zz_operations`
            INNER JOIN `em_emails` ON `zz_operations`.`id_email` = `em_emails`.`id`
            INNER JOIN `em_templates` ON `em_emails`.`id_template` = `em_templates`.`id`
            INNER JOIN `zz_modules` ON `zz_operations`.`id_module` = `zz_modules`.`id` WHERE `zz_modules`.`name` = 'Interventi' AND `zz_operations`.`op` = 'send-email'GROUP BY `zz_operations`.`id_record`) AS inviato ON inviato.id_record=in_interventi.id
LEFT JOIN an_referenti ON an_referenti.id=in_interventi.idreferente
LEFT JOIN (
    SELECT GROUP_CONCAT(CONCAT(matricola, IF(nome != '', CONCAT(' - ', nome), '')) SEPARATOR '<br />') AS descrizione, my_impianti_interventi.idintervento
    FROM my_impianti
        INNER JOIN my_impianti_interventi ON my_impianti.id = my_impianti_interventi.idimpianto
    GROUP BY my_impianti_interventi.idintervento
) AS impianti ON impianti.idintervento = in_interventi.id
LEFT JOIN (
    SELECT co_preventivi.id,  CONCAT(co_preventivi.numero, ' del ', DATE_FORMAT(data_bozza, '%d/%m/%Y')) AS info FROM co_preventivi
) AS preventivo ON preventivo.id = in_interventi.id_preventivo
LEFT JOIN (
    SELECT or_ordini.id,  CONCAT(or_ordini.numero, ' del ', DATE_FORMAT(data, '%d/%m/%Y')) AS info FROM or_ordini
) AS ordine ON ordine.id = in_interventi.id_ordine
WHERE 1=1 |date_period(`orario_inizio`,`data_richiesta`)|
GROUP BY `in_interventi`.`id`
HAVING 2=2
ORDER BY IFNULL(`orario_fine`, `data_richiesta`) DESC

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei, la colonna Contratto in Attività ci risulta già presente dalla v.2.4.33, attivabile dal modulo viste.
