### ISSUE TITLE
SCONTI MULTIPLI - righe fatture/ordini/ecc

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#112]
Soprattutto in acquisti è usuale che i fornitori di materiale applichino della scontista concatenata.
Mi spiego meglio, in un ordine di materiale, all'artico spesso è applicato uno sconto di 35% + un ulteriore 10% sul 35%, che non è il 45%, ma sono sconti concatenati, mentre nella maschera della riga è possibile applicare solo una percentuale di sconto.
![image](https://user-images.githubusercontent.com/34273200/34905227-957eceb4-f854-11e7-8ba8-97e316a27c14.png)

**Comment by fpsoftware** [comment]
Ciao @fgambarelli grazie per la richiesta, funzione fondamentale per gli acquisti

**Comment by loviuz** [comment]
Abbiamo fatto alcune prove, e senza creare campi dinamici per ogni sconto concatenato, basterebbe lasciar inserire all'utente una stringa del tipo "10+35" quando viene selezionato il tipo di sconto "%". Nel db verrebbe salvata la stringa "10+35" e, in fase di salvataggio sconto in €, dato che calcoliamo sempre e comunque, verrebbe fatto uno split sul "+" e calcolato lo sconto in un loop, scontando ad ogni ciclo dall'importo scontato.

Esempio:

`$sconto_concat = "10+35";`
`$sconto = 0;`
`$prezzo = 100.00;`
`$prezzo_scontato = $prezzo;`

`$sconti_prc = explode( "+", $sconto );`

`for( $i=0; $i<sizeof($sconti_prc); $i++ ){`
`    $sconto = $prezzo_scontato / 100 * $sconti_prc[$i];`
`    $prezzo_scontato -= $sconto;`
`}`

**Comment by lexen77** [comment]
Salve,
la stessa logica dovrebbe essere applicata ai listini.
Infatti nella vita reale la scontistica concatenata si riscontra spesso nei listini dei rivenditori o rappresentanti.

**Comment by Dasc3er** [comment]
Con il commit 81137ad89f1a2d5f5f42ef8284addd794caad590 è stata aggiunta una funzione specifica per il calcolo degli sconti.
Di seguito alcuni esempi di utilizzo:

```php
// Sconto in euro
$discount = calcola_sconto([
    'sconto' => 5,
    'prezzo' => 100,
    'tipo' => 'EUR',
]);

// Sconto percentuale
$discount = calcola_sconto([
    'sconto' => 5,
    'prezzo' => 100,
    'tipo' => 'PRC',
]);

// Sconto percentuale concatenato
$discount = calcola_sconto([
    'sconto' => "10+35",
    'prezzo' => 100,
    'tipo' => 'PRC',
]);
```

Sarebbe utile per generalizzare questi calcoli e permetterne la futura espansione, sostituendo tutti i codici di questo tipo nel modo seguente:
https://github.com/devcode-it/openstamanager/blob/81137ad89f1a2d5f5f42ef8284addd794caad590/modules/contratti/actions.php#L151

```php
// Sconto automatico
$sconto = calcola_sconto([
    'sconto' => $sconto_unitario,
    'prezzo' => $prezzo,
    'tipo' => $tipo_sconto,
    'qta' => $qta,
]);
```

**Comment by Dasc3er** [comment]
@loviuz Rimane da definire la modalità di salvataggio dell'informazione nel database, perchè al momento il campo _sconto_unitario_ è un **decimal(12,4)**.

**Comment by loviuz** [comment]
Funzionalità inserita nel frattempo nei listini.

**Comment by Dasc3er** [comment]
Grazie ai cambiamenti di #758, è ora possibile registrare anche gli sconti percentuali composti nel database. Resta da definire se salvare lo sconto risultante oppure se salvare anche la stringa indicata.
