### ISSUE TITLE
Colonna Agente in preventivi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1124]
## Comportamento richiesto

sarebbe utile avere la **colonna Agente in preventivi**

## Passi per riprodurre il comportamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Aggiunta colonna Agente in preventivi, di default nascosta
