### ISSUE TITLE
Errore su salvataggio contratto

### ISSUE THREAD

**Issue by tecnologieinformatiche** [devcode-it/openstamanager#1125]
## Comportamento richiesto

Salvataggio contratto

## Comportamento attuale

Forbidden
You do not have permission to access this document.
Web Server at tecnologie-informatiche.com

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Inserisco un nuovo contratto
2. premo salva
3. e va in errore

Eventuale codice rilevante:
```php 7.4.32
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: contratti
* Versione del progetto: ultima
* Versione PHP: 7.4.32
* Tipo di server: Aruba Business linux

**Comment by Pek5892** [comment]
Buongiorno, potrebbe verificare che i permessi siano impostati correttamente?

**Comment by tecnologieinformatiche** [comment]
Buongiorno, ho controllato meglio, il problema era il firewall sull'hosting. L'ho disabilitato, ma non è una soluzione sicura. Come posso mettere una esclusione ? grazie

**Comment by Pek5892** [comment]
Per questo dovrebbe provare a contattare il suo hosting
