### ISSUE TITLE
Fatture di Vendita, in segmenti diversi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1126]
## Comportamento richiesto

se in Fatture di Vendita abbiamo selezionato il segmento Autofatture
poi si fattura un preventivo o DDT 
ci troviamo la nuova fattura sotto il segmento precedente selezionato, quindi Autofatture

il problema è che **dopo non è più possibile cambiare il sezionale.**

![1](https://user-images.githubusercontent.com/75281007/205688190-1cebe3e0-0b62-4171-88ec-ee50b1de7138.png)

## Possibile soluzione

1 - permettere la fatturazione di un preventivo, ddt, ecc... solo con sezionale standard di vendita
2 - permettere di **cambiare il segmento** all'interno della fattura **dopo averla generata**.

## Passi per riprodurre il comportamento

1. in fatture di vendita selezionare un segmento autofatture o fatture non elettroniche
2. fatturare un ddt o preventivo
3.

**Comment by Pek5892** [comment]
Già trattato in: https://github.com/devcode-it/openstamanager/issues/1081#issuecomment-1337650708.
Non è prevista al momento l'introduzione di una funzionalità per il cambio di sezionale.

**Comment by sajotrei** [comment]
Ciao, 
il problema è simile, ma questo è sulle fatture attive, il precedente post sulle fatture passive.
