### ISSUE TITLE
BUG: Note interne riga articolo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1127]
Se in una nota interna di una riga articolo di un documento inserisco una dicitura che contiene virgolette, quando riapro la riga la nota non è più editabile e compare:
`{[ "type": "textarea", "label": "Note interne", "name": "note", "value": "NOTA INTERNA"", "help": "Queste note saranno utilizzate solo a scopo interno", "extra": "rows=\"2\"" ]}`

Lo stesso problema lo avevo riscontrato nella versione 2.4.25 nel dettaglio del listino fornitori  (vedi issue #985)

OSM ver. 2.4.37

**Comment by idraulicadueci** [comment]
Ho trovato il problema:
L'istruzione contenuta nel file /include/common/descrizione.php
`<div class="row">

        <div class="row">

        <div class="col-md-12">

            {[ "type": "textarea", "label": "'.tr('Note interne').'", "name": "note", "value": "'.$result['note'].'", "help": "'.tr('Queste note saranno utilizzate solo a scopo interno').'", "extra": "rows=\"2\"" ]}

        </div>

    </div>';

Deve essere modificata nel seguente modo:
`<div class="row">

        <div class="col-md-12">

            {[ "type": "textarea", "label": "'.tr('Note interne').'", "name": "note", "value": '.json_encode($result['note']).', "help": "'.tr('Queste note saranno utilizzate solo a scopo interno').'", "extra": "rows=\"2\"" ]}

        </div>

    </div>';`

**Comment by loviuz** [comment]
ciao @idraulicadueci, riesci a fare una pull request?
