### ISSUE TITLE
BUG: Errore ricerca coordinate 

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1129]
## Comportamento richiesto

in anagrafica, azione di gruppo, ricerca coordinate 
![Screenshot 2022-12-07 alle 13 05 40](https://user-images.githubusercontent.com/75281007/206177325-cf3cd836-d955-4ce0-85be-9089316510de.png)
![Screenshot 2022-12-07 alle 13 05 44](https://user-images.githubusercontent.com/75281007/206177333-6994e151-50cd-4b85-9256-3a133f09530f.png)
![Screenshot 2022-12-07 alle 13 05 54](https://user-images.githubusercontent.com/75281007/206177340-a07a5385-92ae-4316-b64c-ca41ec24f9bf.png)

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. selezionare una anagrafica
2. azione di gruppo
3. selezionare ricerca coordinate 

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Funzione non più disponibile
