### ISSUE TITLE
BUG: Nessuna immagine nelle stampe preventivi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1133]
## Comportamento attuale

Nella stampa dei preventivi non sono più visualizzate le immagini relative agli articoli indicati

* Modulo: Preventivi
* Versione del progetto: 2.4.38

**Comment by idraulicadueci** [comment]
Il bug si presenta anche su un'installazione pulita della versione 2.4.38

**Comment by Pek5892** [comment]
Buongiorno @idraulicadueci,
non riusciamo a riprodurre l'errore, da installazione pulita l'immagine inserita nella scheda articolo viene visualizzata:
![image](https://user-images.githubusercontent.com/102604205/207874328-b4e53930-76e2-4126-add2-5cdf92ef4a97.png)

**Comment by idraulicadueci** [comment]
Strano, perché anch'io ho provato su un'installazione pulita.
Sicuri che non ci siano dei vincoli che influenzano il risultato?
![Screenshot](https://user-images.githubusercontent.com/40104356/207945202-0d3a9086-bd67-4547-b62e-bd23658cd058.png)

**Comment by Pek5892** [comment]
Non riusciamo a riprodurre il problema neanche sulla demo, potrebbe controllare di aver assegnato correttamente i permessi?

**Comment by idraulicadueci** [comment]
ciao, ho controllato, ma non ci sono problemi di permessi. Dato che ho fatto l'installazione pulita sia dei file che del database, mi viene il dubbio che il problema sia legato al server Aruba che rifiuta qualche comando. Ci sono altre impostazioni da fare oltre a quelle dei requisiti minimi nel modulo aggiornamenti?

**Comment by lucasalva87** [comment]
Ciao, credo che il problema con questo hosting sia stato introdotto da questo "Fix"
https://github.com/devcode-it/openstamanager/commit/d45a5c30d1abd386acdc4c4125bd2f879b3968eb

@MatteoPistorello

**Comment by idraulicadueci** [comment]
ciao @lucasalva87, avevo già provato a modificare il file, ma non succede niente.

**Comment by Pek5892** [comment]
Ciao @idraulicadueci,
potresti controllare dal log se viene visualizzato qualche errore?

**Comment by idraulicadueci** [comment]
Già guardato, nessun errore.

**Comment by lucasalva87** [comment]
Dicevi che "non sono più visualizzate le immagini relative agli articoli indicati" su quale versione di OSM ti risultava funzionare?

**Comment by idraulicadueci** [comment]
Sto caricando una versione precedente su una cartella di test del server per fare un'installazione pulita.
Parto dalla 2.4.36 e poi faccio gli aggiornamenti successivi per vedere con quale aggiornamento di verifica il problema.
Ti faccio sapere. Grazie mille.

**Comment by idraulicadueci** [comment]
Ho provato con la 2.4.35 e già il problema si presenta. Hanno sicuramente cambiato qualcosa nel server Aruba, non capisco dove sia l'inghippo. Provo a aprire un ticket e vi aggiorno.

**Comment by idraulicadueci** [comment]
L'assistenza di Aruba non mi dà una soluzione, praticamente dicono che non dipende dal server. E dalle prove fatte sono certo che non dipende da OSM.

Per ora ho creato una custom body.php dove ho disattivato la funzione di visualizzazione delle immagini. 

Vedo di indagare sulla causa.

Grazie per il tempo speso.
