### ISSUE TITLE
BUG: errore salva articolo

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1134]
## Comportamento richiesto

**errore** quando si salva un articolo

<img width="1631" alt="Screenshot 2022-12-10 alle 23 29 54" src="https://user-images.githubusercontent.com/75281007/206877749-482a1f14-de8a-4e97-a4e6-65d2619bab46.png">

* Modulo:
* Versione del progetto: 2.4.38
* Versione PHP:
* Tipo di server:

**Comment by lucasalva87** [comment]
Purtroppo non riusciamo a riprodurre il problema. Potresti verificare questi tre punti?
https://docs.openstamanager.com/v/2.4.38/guide/esempi/verificare-linstallazione-di-osm

Grazie.

**Comment by sajotrei** [comment]
Ciao Luca,
abbiamo verificato, effettivamente non si presenta sull'installazione base
ma solo sulle installazioni con moduli aggiuntivi 
apriamo specifico ticket nell'area clienti.

**Comment by lucasalva87** [comment]
Ottimo, grazie mille.
