### ISSUE TITLE
Vista elenco vendita al banco

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1136]
## Comportamento richiesto

è più logico e pratico che l'elenco in vendita al banco sia in ordine per data decrescente
quindi l'utimo corrispettivo in alto.

SELECT |select|
FROM `vb_venditabanco`
     INNER JOIN `vb_stati_vendita` ON `vb_venditabanco`.`idstato` = `vb_stati_vendita`.`id`
     LEFT JOIN (
         SELECT `idvendita`,
                GROUP_CONCAT(`descrizione` SEPARATOR ', ') AS `descrizione_righe`,
                SUM(`subtotale` - `sconto`) AS `totale_imponibile`,
                SUM(`subtotale` - `sconto` + `iva`) AS `totale`
         FROM `vb_righe_venditabanco`
         GROUP BY `idvendita`
     ) AS righe ON `vb_venditabanco`.`id` = `righe`.`idvendita`
     LEFT JOIN `an_anagrafiche` ON `vb_venditabanco`.`idanagrafica` = `an_anagrafiche`.`idanagrafica`
WHERE vb_venditabanco.deleted_at IS NULL AND 1=1 HAVING 2=2

## Comportamento attuale

Qual è il comportamento attuale, e come ti aspetti che venga migliorato?

## Possibile soluzione

**Query di default in vista vendita al banco** aggiungere il seguente campo.

WHERE vb_venditabanco.deleted_at IS NULL AND 1=1 **|date_period(`vb_venditabanco`.`data`)| HAVING 2=2 ORDER BY `vb_venditabanco`.`data` DESC**

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
è inteso che il **suggerimento** vale **anche** per la vista **Easy vendita**

**Comment by Pek5892** [comment]
Introdotta miglioria query con ordinamento in base alla data in release.

**-- Vendita al banco:**
UPDATE `zz_modules` SET `options` = "SELECT 
|select|
FROM 
    `vb_venditabanco`
    INNER JOIN `vb_stati_vendita` ON `vb_venditabanco`.`idstato` = `vb_stati_vendita`.`id`
    LEFT JOIN (SELECT `idvendita`, GROUP_CONCAT(`descrizione` SEPARATOR ', ') AS `descrizione_righe`, SUM(`subtotale` - `sconto`) AS `totale_imponibile`, SUM(`subtotale` - `sconto` + `iva`) AS `totale` FROM `vb_righe_venditabanco` GROUP BY `idvendita`) AS righe ON `vb_venditabanco`.`id` = `righe`.`idvendita`
    LEFT JOIN `an_anagrafiche` ON `vb_venditabanco`.`idanagrafica` = `an_anagrafiche`.`idanagrafica`
WHERE 
    vb_venditabanco.deleted_at IS NULL 
AND 
    1=1 
HAVING 
    2=2 ORDER BY vb_venditabanco.data DESC" WHERE `name` = 'Vendita al banco';
    
**-- Easy vendita:**
UPDATE `zz_modules` SET `options` = "SELECT 
|select|
FROM 
    `vb_venditabanco`
    INNER JOIN `vb_stati_vendita` ON `vb_venditabanco`.`idstato` = `vb_stati_vendita`.`id`
    LEFT JOIN (SELECT `idvendita`, GROUP_CONCAT(`descrizione` SEPARATOR ', ') AS `descrizione_righe`, SUM(`subtotale` - `sconto`) AS `totale_imponibile`, SUM(`subtotale` - `sconto` + `iva`) AS `totale` FROM `vb_righe_venditabanco` GROUP BY `idvendita`) AS righe ON `vb_venditabanco`.`id` = `righe`.`idvendita`
WHERE 
    deleted_at IS NULL 
AND 
    1=1 
HAVING 
    2=2 
ORDER BY 
    vb_venditabanco.data DESC" WHERE `name` = 'Easy vendita';
