### ISSUE TITLE
Stampa XML nelle azioni di gruppo delle fatture di acquisto

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#1138]
## Domanda

In una vecchia versione c'era la possibilità di stampare più XML delle fatture (utilizzando il file "view_pdf.php", ma nella versione 2.4.37 questa opzione non c'è più.
Trattandosi di un'opzione che poteva essere comoda a molti, mi chiedevo perché è stata rimossa e se sarà mai nuovamente implementata.
Grazie

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: "Fatture di Acquisto"
* Versione del progetto: 2.4.37
* Versione PHP: 7.4
* Tipo di server: hosting

**Comment by cristianviale** [comment]
> Buongiorno @cristianviale, intende la funzione Esporta XML da azioni di gruppo?
> 
> ![image](https://user-images.githubusercontent.com/102604205/207875526-e7bbe8a0-c95a-4d11-97d8-28ec7ca8b8bd.png)
> 
> 

No, intendo la funzione di stampa che generava un PDF in formato asso-invoice

**Comment by Pek5892** [comment]
Ricorda il numero della versione in cui questa funzione era presente?

**Comment by cristianviale** [comment]
> Ricorda il numero della versione in cui questa funzione era presente?

Non sono sicuro ma potrebbe essere la 2.4.17

**Comment by cristianviale** [comment]
Ho verificato, la versione era la 2.4.13

**Comment by Pek5892** [comment]
Non ci risulta essere una funzione presente nella versione 2.4.13 da release, ne la presenza del file "view_pdf.php", aveva qualche personalizzazione?

**Comment by cristianviale** [comment]
Se non vi risulta magari l'avevo creato io anni fa e non ricordavo.
Grazie
