### ISSUE TITLE
PRIMA NOTA - Fatture Vendita

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#114]
Una volta emessa la fattura questa appare nello scadenzario e del piano dei conti , ma non appare in prima nota.
![image](https://user-images.githubusercontent.com/34273200/34917037-639b29a4-f941-11e7-9a7f-b7fcc8811970.png)

Guardando nella tabella co_movimenti ho visto che il campo primanota è =0 
![image](https://user-images.githubusercontent.com/34273200/34917061-b2edcb06-f941-11e7-897b-2aab5016c039.png)

**Comment by Dasc3er** [comment]
@fgambarelli Se non sbaglio, per inserire la fattura in Prima Nota è necessario utilizzare il pulsante relativo che compare una volta impostato lo stato in "Emessa"...

![screenshot-2018-1-14 fatture di vendita - openstamanager](https://user-images.githubusercontent.com/15911489/34918302-c0d7f282-f950-11e7-93c2-8b75a576d24b.png)

**Comment by fgambarelli** [comment]
Anche io credevo, ma sul DB c'è e se si preme il pulsante appare la registrazione in prima nota del pagamento
![image](https://user-images.githubusercontent.com/34273200/34918476-311fa74a-f953-11e7-9347-89cfe4047ef3.png)

**Comment by Dasc3er** [comment]
@loviuz @fpsoftware @lucasalva87

**Comment by loviuz** [comment]
quando la fattura va in stato "emessa" vengono effettuati i movimenti di emissione fattura su co_movimenti, ma non devono vedersi sulla prima nota. la prima nota viene fatta per incassare una fattura, va sempre su co_movimenti (con flag primanota a 1) e si vede su "Prima nota". non ho capito qual è il punto anomalo...

**Comment by fgambarelli** [comment]
Credo sia un obbligo della contabilità...
![image](https://user-images.githubusercontent.com/34273200/34931452-2dbbdffc-f9cf-11e7-946b-6514d711f86d.png)
La prima nota è la base dell'emissione del Libro Giornale che deve contenere tutte le registrazioni di prima nota in ordine cronologico.
A mio parere, poi verificate voi, i movimenti delle fatture rilasciate devono vedersi in prima nota.

**Comment by loviuz** [comment]
la stampa del libro giornale non l'abbiamo mai fatta, ma ho chiesti vari pareri e i movimenti di emissione fattura mi dicono che non devono andare in prima nota. devono esserci, eventualmente se faremo la stampa libro giornale li faremo uscire

**Comment by loviuz** [comment]
Ho spostato qui l'argomento: #151
