### ISSUE TITLE
Errore check Anagrafiche con codici REA

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1140]
## Comportamento richiesto

Errore check Anagrafiche con codici REA
sistema li segnala come errore anche se è corretto o mancante

dovrebbe segnalare solo i valori inseriti e se sono realmente errati.

## Comportamento attuale

![207899644-5e9c19f6-cb7d-4123-bec2-542fff6c4e1a](https://user-images.githubusercontent.com/102604205/207904656-6e8f6e1c-46c9-4561-88ee-0016d1298675.png)

* Modulo:
* Versione del progetto: 2.4.38
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Il problema si verifica per codici REA con numero di cifre diverso da 6, mentre il controllo su codici REA mancanti risulta corretto. Nel caso specifico le anagrafiche indicate riportano a database codice REA registrato come "-", e vengono pertanto segnalate come errate.

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/237eed1cc1374e0182b88b48f5a1ad6bbfa83a70
