### ISSUE TITLE
non è possibile selezionare la rata contrattuale dell'anno precedente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1141]
## Comportamento attuale

<img width="1858" alt="Screenshot 2023-01-09 alle 21 23 12" src="https://user-images.githubusercontent.com/75281007/211401717-f0ac130a-9ab0-44f6-b9a0-b54e1d6c052c.png">

* Modulo:
* Versione del progetto: 2.4.38
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno @sajotrei,
risolto con commit: [https://github.com/devcode-it/openstamanager/commit/d91da3422786b172e0dfe4599b62cad9c1fc9b3e](https://github.com/devcode-it/openstamanager/commit/d91da3422786b172e0dfe4599b62cad9c1fc9b3e)

**Comment by sajotrei** [comment]
ottimo ora è ok 👍
grazie
