### ISSUE TITLE
Errore durante l'esecuzione di Node Sass

### ISSUE THREAD

**Issue by ToX82** [devcode-it/openstamanager#1144]
## Comportamento richiesto

Ho bisogno di eseguire il minify di alcuni nuovi files JS, ma lanciando gulp (o gulp watch) mi viene mostrato un errore

```
➜ gulp watch  
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
```

## Possibile soluzione

Dovrebbe essere sufficiente aggiornare le dipendenze di npm, vedo che gulp-sass è impostato come "^4.1.1". Ho provato ad aggiornare io ma senza successo :)

## Contesto

Lavoro in ambiente linux (ubuntu 22.04 LTS), con npm 9.2.0 e node 16.18.1. Sono nel canale master

**Comment by ToX82** [comment]
Ho risolto, più o meno, togliendo la versione specifica da `package.json`

da
`"gulp-sass": "^4.1.1",`
a
`"gulp-sass": "*",`

Non è un gran che ma funziona

**Comment by Pek5892** [comment]
Dovrebbe risolversi con l'aggiornamento della libreria introdotto con commit: https://github.com/devcode-it/openstamanager/commit/30cd0d275a0a3af147d166583213aea7564b176c
