### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1145]
## Comportamento richiesto

sarebbe certamente comodo creare un auto save, che salva in automatico i campi testo nei vari documenti

https://forum.openstamanager.com/d/2361-auto-save

**Comment by Pek5892** [comment]
Buongiorno @sajotrei,
potrebbe fare degli esempi pratici?

**Comment by sajotrei** [comment]
se non si clicca su salva, capita di perdere il contenuto delle note, descrizione, ecc..
quindi avere una sorta di salvataggio automatico riduce/elimina questo rischio.

**Comment by Pek5892** [comment]
Il salvataggio automatico è un'arma a doppio taglio, perchè se si elimina o sovrascrive per errore il valore di un campo, esso sarà perso per sempre al primo click fuori dal campo stesso. Per questo preferiamo evitare l'autosave e confermare la modifica dei campi solo al salvataggio del documento.
Il salvataggio automatico è già presente al momento dell'aggiunta/modifica di sessioni e righe.
