### ISSUE TITLE
Nome preventivo in elenco revisioni del plugin 

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1146]
## Comportamento richiesto

la possibilità di avere il nome del preventivo in elenco revisioni del plugin

![revisione](https://user-images.githubusercontent.com/75281007/212058876-be896a7e-b010-4b50-8af6-51911ceec9e6.png)

https://forum.openstamanager.com/d/2479-modifica-nome-revisione-preventivo

**Comment by Pek5892** [comment]
Chiudo per issue duplicata in: https://github.com/devcode-it/openstamanager/issues/1219
