### ISSUE TITLE
Miglioramento interfaccia grafica

### ISSUE THREAD

**Issue by 27andrea** [devcode-it/openstamanager#1148]
Buonasera,
Volevo chiedere se era previsto un rilascio per un interfaccia grafica più recente e in linea con gli ultimi anni.
Grazie

**Comment by sajotrei** [comment]
https://github.com/devcode-it/openstamanager/issues/710

qui alla voce **Frontend**, c'è una proposta/valutazione anche sulla parte grafica, ma sembra essere un intervento di sviluppo importate non so se verrà applicata.

**Comment by 27andrea** [comment]
Sarebbe interessante.visto che più persone lo vorrebbero.

**Comment by 27andrea** [comment]
si sa nulla?

**Comment by loviuz** [comment]
ciao @27andrea, la domanda è un po' vaga. cosa intendi più precisamente?

**Comment by lucasalva87** [comment]
Su una branch era stato iniziato il porting ad AdminLTE 3 più di 2 anni fa.

https://github.com/devcode-it/openstamanager/blob/43eec7a6379c9a2c82760c1ff5b6de75dc581620/assets/src/css/style.css

**Comment by sajotrei** [comment]
> Su una branch era stato iniziato il porting ad AdminLTE 3 più di 2 anni fa.
> 
> https://github.com/devcode-it/openstamanager/blob/43eec7a6379c9a2c82760c1ff5b6de75dc581620/assets/src/css/style.css

interessante! 🤔👍
https://adminlte.io
https://adminlte4.gatner.be/index.html

per la AdminLTE 3 sembra fermo lo sviluppo a febbraio 22...
https://github.com/ColorlibHQ/AdminLTE


immagino che non basta modificare il file /assets/src/css/**style.css** per avere una grafica differente.

**Comment by 27andrea** [comment]
> > Su una branch era stato iniziato il porting ad AdminLTE 3 più di 2 anni fa.
> 
> > 
> 
> > https://github.com/devcode-it/openstamanager/blob/43eec7a6379c9a2c82760c1ff5b6de75dc581620/assets/src/css/style.css
> 
> 
> 
> interessante! 🤔👍
> 
> https://adminlte.io/premium/
> 
> https://adminlte.io/themes/v3/
> 
> https://adminlte4.gatner.be/index.html
> 
> 
> 
> per la AdminLTE 3 sembra fermo lo sviluppo a febbraio 22...
> 
> https://github.com/ColorlibHQ/AdminLTE
> 
> 
> 
> 
> 
> 
> 
> 

Seguo

**Comment by 27andrea** [comment]
Si sa più nulla?

**Comment by Pek5892** [comment]
attualmente in uso Admin LTE
