### ISSUE TITLE
CONTRATTI - RINNOVO

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#115]
Rinnovando un contratto non vengono riporti gli impianti precedentemente selezionati

**Comment by Dasc3er** [comment]
@fgambarelli Grazie mille per la segnalazione!
Il commit a2f425dd37a5ac2ccab05614219123f89a2a7001 dovrebbe aver risolto il problema, puoi confermare?

**Comment by fgambarelli** [comment]
Confermo BUG risolto.
