### ISSUE TITLE
Modalità di pagamento differente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1151]
## Comportamento richiesto

ci sono delle situazioni dove **_è necessario_** impostare in fattura modalità di pagamento differenti.
ES. bonifico e RiBa, oppure contanti e bonifico, ecc..

in parte era stato citato in un precedete post. anche se evidenziava l'acconto.
**Gestione acconto e relativa modalità di pagamento #1016**

## Comportamento attuale

al momento è possibile frazionare il pagamento, Es. Bonifico 30/60gg, ma **non si può diversificare il tipo di pagamento** 

## Possibile soluzione
se al momento non è possibile modificare la struttura della fattura, una possibile soluzione più "snella" come sviluppo potrebbe essere quello di modificare almeno le scadenze.

<img width="1356" alt="1" src="https://user-images.githubusercontent.com/75281007/213684123-886ccd31-3d05-4cd8-aa96-c451565eb2fd.png">

<img width="1707" alt="2" src="https://user-images.githubusercontent.com/75281007/213684636-557e10eb-52e2-4299-a973-f7bfd99ea343.png">

**Comment by Pek5892** [comment]
Trattato in: https://github.com/devcode-it/openstamanager/issues/830

**Comment by sajotrei** [comment]
Ciao, ci sono novità su questo aspetto ?

**Comment by Pek5892** [comment]
Ciao @sajotrei, al momento non ci sono novità, e in caso saranno segnalate sull'issue originale.
Chiudo questa in quanto duplicata.
