### ISSUE TITLE
Cambio stato a seguito di programmazione in dashboard

### ISSUE THREAD

**Issue by kenchu84** [devcode-it/openstamanager#1154]
## Comportamento richiesto

un intervento "da programmare" quando viene trascinato in dashboard e quindi progrmmato ( con l'inserimento di una sessione di lavoro ), dovrebbe passare automaticamente in "programmato"

## Comportamento attuale

Al momento non succede, ed il cambio stato e' inibito durante la modifica dell'intervento trascinato in dashboard.

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: "dashboard"
* Versione del progetto: qualsiasi
* Versione PHP: come sopra
* Tipo di server: come sopra

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/99f0f3520b545e135b95d7f2fc0e5764bb2bd61b
