### ISSUE TITLE
(BUG) Duplicata visualizzazione pagamenti

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1156]
## Comportamento richiesto

viene duplicata la visualizzazione del pagamento in base alle scadenze

![1](https://user-images.githubusercontent.com/75281007/214291202-06c467f2-1953-4e4d-92c0-77b61b872904.png)

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/c8afdf27f9688188971db80683886261770abf08
