### ISSUE TITLE
Errore Calcolo Iva in liquidazione 

### ISSUE THREAD

**Issue by L3d83** [devcode-it/openstamanager#1158]
Anomalia riscontrata
Nel modulo contabilità, liquidazione iva.
Errore sul calcolo dell' Iva in base alle specifiche definite in tabella Iva.

Il comportamento richiesto dovrebbe essere , che l'iva venga calcolata tenendo conto della  % di indetraibilità.

Problema analogo con Iva codice 315 , "Escluso art. 15"
Esempio di una fattura ricevuta e importata.
Nella fattura di acquisto,  è presente una riga con iva Escluso art 15. In questo caso l'iva è 0 e il calcolo in questo modulo è corretto.

Quando però vado nella liquidazione del mese o trimestre, il calcolo avviene in modo differente e viene conteggiata  l'iva di 2.374 circa % e non capisco perché.
Si dovrebbero allineare i calcoli, oppure utilizzare le scritture del DB per fare la sommatoria corretta, in modo tale che , se si dovesse implementare un 'integrazione che va a modificare i dati manualmente, il ricalcolo sia sulla lettura e non sulla nuova generazione dei dati.

**Comment by L3d83** [comment]
Buongiorno Valentina, le farò sapere domani perché chi si occupa della contabilità ci sarà domani.

Cordiali saluti 

Giuseppe. S.

 

 

Da: Valentina ***@***.***> 
Inviato: lunedì 27 marzo 2023 11:59
A: devcode-it/openstamanager ***@***.***>
Cc: Giuseppe Siragusano ***@***.***>; Author ***@***.***>
Oggetto: Re: [devcode-it/openstamanager] Errore Calcolo Iva in liquidazione (Issue #1158)

 

Buongiorno,
potreste verificare i valori applicando questa fix:  <https://github.com/devcode-it/openstamanager/commit/7b8c67b443637ff1ff73d3e4ce6f9fdf37f40da9> 7b8c67b?

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/51dd56d2ea88ee2fd5e79ffaaa760d0272ce00d0
