### ISSUE TITLE
Gestione semplificata delle credenziali personali

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#116]
Un utente non ha la possibilità di cambiarsi la password. Ho provato dando permessi di scrittura al gruppo del quale fa parte l'utente. In questa maniera però riesce a modificare anche le password degli altri gruppi.

Versione Git 2.3.1

**Comment by Dasc3er** [comment]
@lepool In effetti la possibilità di modificare la propria password non è mai stata resa possibile senza l'accesso al modulo **Utenti e permessi**, come documentato nella [nuova documentazione di aggiornamento](https://devcode-it.github.io/openstamanager/aggiornamento.html#recupero-della-password).
Potrebbe essere però utile introdurre una funzionalità simile in futuro per la gestione del proprio account.

**Comment by Dasc3er** [comment]
Con il commit c85bb159fa0f8931a227d39dfaedea4932697ac3 è stata introdotta la possibilità di accedere ad una pagina dedicata all'utente dove è possibile:

- Cambiare la propria password
- Visualizzare il proprio token di accesso all'API
- Visualizzare il link e le informazioni per importare il calendario eventi all'esterno del gestionale

Per il momento la grafica è estremamente basilare, e quindi da migliorare.
Inoltre, per il momento non è ancora stata prevista la possibilità di ricuperare la propria password in altri modi (per esempio, via email).

**Comment by lucasalva87** [comment]
Bellissima questa schermata. Credo che però ci sia qualche problema nel case sync dell'api in quanto idtecnico è vuoto. E non viene restituito nessun intervento nel file VCALENDAR.

**Comment by Dasc3er** [comment]
@lucasalva87 Potresti controllare con il commit d1ac0cf42b1ea30ca0ce366d6236a49282514596?

**Comment by lucasalva87** [comment]
@Dasc3er , sembra ok... ottimo!
