### ISSUE TITLE
Widget attività

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1161]
## Comportamento richiesto

Aggiungere dei **_Widget in elenco attività_**.

magari prendendo il nome e colore dalle impostazioni in attività-stati di attività

<img width="1786" alt="Widget attività" src="https://user-images.githubusercontent.com/75281007/214624623-e7d57dc5-8f4a-4090-942b-77d9a883cb3e.png">

## Possibile soluzione
qui sono stati impostati manualmente i colori e nomi

![db attivita](https://user-images.githubusercontent.com/75281007/214624710-2a6c6a5d-a8f2-4462-bdb7-e7a095543ee7.png)

**Comment by Pek5892** [comment]
Modifica non applicabile, essendo gli stati delle attività modificabili da gestionale.

**Comment by sajotrei** [comment]
ciao Valentina, noi l'abbiamo introdotto da tempo, ed è molto utile!

ci spiace che vanga scarta così a priori.

pensavo che si possono introdurre i widget standard come da stati attività...
poi se uno dovesse fare un cambio nome e colore, al salvataggio se esegue uno script che va a modificare il volere dei widget

**Comment by sajotrei** [comment]
con la 2.7

![Image](https://github.com/user-attachments/assets/b24e835e-506c-476a-9671-21d5e3ae97c5)
