### ISSUE TITLE
(BUG) Categorie articoli - Salva e chiusi 

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1164]
## Comportamento richiesto

in Categorie articoli, cliccando su Salva e chiudi non si chiude la pagina 

## Passi per riprodurre il comportamento

1. STRUMENTI
2. TABELLE
3. CATEGORIE ARTICOLI
4. APRIRE UNA CATEGORIA
5. CLIACCARE SU SALVA E CHIUDI

* Modulo:
* Versione del progetto: 2.4.39
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/1077ad31d775af2febbd87fe1714271d14ad46e0
