### ISSUE TITLE
Controllo presenza anagrafica fornitore in registrazione FE

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1165]
## Comportamento richiesto

quando si importa una fattura passiva FE, il sistema ti avvisa se l'anagrafica è nuova. 
e se si procede con la registrazione crea la nuova anagrafica secondo quanto indicato nella FE 👍

ma di fatto può essere che l'anagrafiche è già presente, ma essendo senza p.iva non viene trovata.
perché attualmente il sistema fa **SOLO una verifica se è presente o meno la P.IVA**.

potrebbe essere utile fare una ricerca **ANCHE della anagrafica** oltre alla p.iva

questo evita che si creino doppioni della stessa anagrafica.

**Comment by sajotrei** [comment]
se si vuole alzare il "livello" 
si potrebbe aumentare la verifica, cioè, anche se trova la p.iva verifica anche il resto dei dati ( anagrafica, indirizzo, ecc...)

magari introducendo una schermata che ti avvisa delle differenze rilevate tra l'anagrafica a sistema e quella riportata sulla FE

e propone/suggerisce un aggiornamento

**Comment by Pek5892** [comment]
Buongiorno @sajotrei, potrebbe farci un esempio di fattura di acquisto ricevuta da un'anagrafica senza partita iva?

**Comment by sajotrei** [comment]
come mai è stata chiusa?


> potrebbe farci un esempio di fattura di acquisto ricevuta da un'anagrafica senza partita iva?

esistono molti motivi uno in particolare che cambia la p.iva o non è stata inserita correttamente, questo capita spesso per le fatture estere con le autofatture

ES.
- si crea l'anagrafica estera con p.iva, si crea la fattura non elettronica
- il commercialista che gestisce le autofatture, crea una anagrafica simile ma con p.iva inventata/differente
- arriva via SDI la fattura e OSM non trova corrispondenza della anagrafica, quindi ne crea una nuova uguale a quella già esistente ma con p.iva diversa.
