### ISSUE TITLE
Creare e associare il Seriale/i articolo in registrazione FE

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1166]
## Comportamento richiesto

si chiede la possibilità di introdurre un **nuovo campo SERIALI** su ogni riga in fase di registrazione fattura di acquisto.

un campo simile a quello già presente in articoli seriali, dove è possibile inserire più seriali 

![Screenshot 2023-01-30 alle 14 55 49](https://user-images.githubusercontent.com/75281007/215500850-4f096e29-f517-401d-86ae-696b8f386434.png)

ES. nella FE ho la riga articolo, abilito crea automatica articolo, se il seriale è già presente nel rigo FE xml, associa il seriale automaticamente ( questo vale sia per un pezzo che più pezzi )

in caso non è presente il seriale in FE, leggo con la pistola barcode o lo inserisco a mano. 

<img width="1798" alt="Screenshot 2023-01-30 alle 15 15 35" src="https://user-images.githubusercontent.com/75281007/215501462-9dff7b21-b545-4e2d-b20e-387163d37b1e.png">

## Comportamento attuale

attualmente per gli articoli nuovi è molto scomodo il sistema, questa è l'attuale procedura

- import fe passiva
- in fase di registrazione fe abilitare creazione automatica articoli 
- registrare la fattura
- andare su ogni articolo presente in fe e abilitare il seriale 
- tornare in fe passiva appena registrata riaprila eliminare gli articoli e reinserirli, così facendo il sistema ti permetterà di associargli il seriale o i seriali, e l'articolo avrà il riferimento del documento di acquisto.

**Comment by Pek5892** [comment]
Forum: https://forum.openstamanager.com/d/2540-creazione-automatica-articoli-e-serial-number

**Comment by Pek5892** [comment]
Aggiunta la possibilità di creare articoli con seriali attivati di default da impostazioni, i seriali vanno però caricati dalla schermata successiva, direttamente in fattura: https://github.com/devcode-it/openstamanager/commit/297f1c889073a5d2bf4bed888d3c92e08c86edf0
