### ISSUE TITLE
ERRORE invio email

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1167]
Se provo a inviare email, mi viene restituita una serie di errori e non viene completato l'invio.
Specifico che la configurazione dell'account email è quella che ho sempre utilizzato e ha sempre funzionato.
Ho fatto una prova di invio da browser di posta elettronica e l'account funziona sia in invio che in ricezione.

Allego file log.

[error.log](https://github.com/devcode-it/openstamanager/files/10554295/error.log)

OSM 2.4.39

**Comment by Pek5892** [comment]
Buongiorno @idraulicadueci,
potresti verificare che l'indirizzo da cui si sta tentando di inviare la mail corrisponda con quello dell'account SMTP configurato?

**Comment by idraulicadueci** [comment]
Ciao. Ho inviato messaggi sempre da quell'account con quella configurazione. L'errore me lo ha dato solo oggi.

**Comment by idraulicadueci** [comment]
Il problema si è misteriosamente risolto. Probabile che fosse un errore temporaneo del server.
Grazie.

**Comment by idraulicadueci** [comment]
Credo di aver capito da cosa è causato il problema. In poche parole, prima di inviare la mail ho dovuto cancellare l'indirizzo del destinatario e richiamarlo dall'elenco a discesa che compare. A quel punto l'invio avviene senza ulteriori errori. Penso che non venga caricato in automatico l'indirizzo al momento che si carica il modal di invio, cosa che viene risolta richiamando nuovamente il destinatario.

**Comment by Pek5892** [comment]
Problema non presente in release
