### ISSUE TITLE
installazione pagina bianca!!

### ISSUE THREAD

**Issue by mosaico48625** [devcode-it/openstamanager#117]
salve , ho scaricato la cartella da git , copiata su xampp\htdocs , eseguito composer e yarn come nella guida ... tutto ok ....
ma quando vado sull' indirizzo mi viene la pagina bianca !!

**Comment by Dasc3er** [comment]
Ciao @mosaico48625,
Hai completato tutta la procedura di installazione prevista sotto il titolo "Github"?
La puoi trovare qui: https://github.com/devcode-it/openstamanager/blob/master/README.md#github

**Comment by Dasc3er** [comment]
Ciao @mosaico48625 ,
Potresti controllare se sono presenti dei file all'interno della cartella **logs/**?
Eventualmente, per ottenere maggiori informazioni, prova ad abilitare il debug dal file **core.php**...

**Comment by antonioscarpino** [comment]
Nelle versione git non è compresa la directory vendor che viene creata tramite yarn . Magari il problema è li anche se dovrebbe dare qualche errore.

**Comment by mosaico48625** [comment]
no ... niente file nella cartella ... solo htaccess
versione PHP 5.6.28
ho eseguito i seguenti comandi dalla directory del progetto:
composer install
yarn global add gulp
yarn install
gulp

tutti andati abuon fine ... sbaglio qualcosa?

**Comment by mosaico48625** [comment]
abilitando il debug esce l'errore sulla riga :

$result = $this->pdo->query($query)->fetchAll($mode);

**Comment by mosaico48625** [comment]
database.php riga 253

**Comment by Dasc3er** [comment]
@mosaico48625  Potresti essere più specifico riguardo l'errore postando i contenuti del file **logs/error.log** oppure facendo uno screenshot?

**Comment by mosaico48625** [comment]
![errore](https://user-images.githubusercontent.com/35410914/34979715-69ebedf4-faa2-11e7-8eeb-a8cddacf1237.jpg)

**Comment by fpsoftware** [comment]
ciao @mosaico48625 
apri il file php.ini ed abilita le seguenti estensioni (rimuovi il "punto e virgola" all'inizio della riga):
extension=php_pdo.dll
extension=php_pdo_mysql.dll
e riavvia xampp

**Comment by mosaico48625** [comment]
avevo gia guardato!!
è gia tutto abilitato !!
extension=php_pdo.dll non è presente.....PHP5.6

**Comment by mosaico48625** [comment]
![php](https://user-images.githubusercontent.com/35410914/34982340-6dc62fae-faaa-11e7-9ee5-25b30cb6b581.jpg)

**Comment by Dasc3er** [comment]
Ciao @mosaico48625,
potresti provare ad aggiornare da repository il progetto?
Con il commit 3d997992642ecfa56591f40b118cb7bb0b2fb1dc i problemi in fase di installazione dovrebbero essere stati risolti...

**Comment by AndreasNogler** [comment]
Avevo riscontrato il stesso errore

`[2018-01-17 11:03:45] Logs.ERROR: Uncaught Exception Error: "Call to a member function query() on null" at /Applications/MAMP/htdocs/openstamanager/src/Database.php line 253
{"url":"/openstamanager/","ip":"::1","http_method":"GET","server":"localhost","referrer":"http://localhost:8888/","uid":"bc855d7"} `

Adesso funziona.

**Comment by fpsoftware** [comment]
controlla che il commit indicato da @Dasc3er sia effettivamente presente nei tuoi files, ho appena creato una nuova installazione e avevo lo stesso problema, praticamente alcuni files non si erano scaricati aggiornati all'ultima versione, ho risolto rimuovendo i files modificati dal commit in questione e poi eseguendo "git pull origin master"

**Comment by AndreasNogler** [comment]
Io ho cancellato la cartella completa poi scaricato con git clone. Eseguito yarn run develop-OSM
e la solita pagina "prima installazione" compare senza nessun problema. Secondo me con il commit 3d99799 @Dasc3er ha risolto.

**Comment by mosaico48625** [comment]
ok !! tutto risolto !! grazie
