### ISSUE TITLE
Sconto in contratto con Pianificazione fatturazione

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1172]
## Comportamento richiesto

si crea un contratto con delle righe servizi e/o merci 
si applica dello sconto % o €

se poi si crea la Pianificazione fatturazione trami il plugin, di conseguenza il sistema modifica le righe del preventivo, **ma perde lo sconto** applicato nelle righe in fase di creazione contratto.

**Comment by Pek5892** [comment]
In release, risolto con commit: https://github.com/devcode-it/openstamanager/commit/bbd03cc0fd924a3eaf1e5f140ce9fc76bdc68414
