### ISSUE TITLE
Evidenziare il totale nei documenti di vendita

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1173]
## Comportamento richiesto

la possibilità di modificare graficamente **il totale** nei vari documenti di vendita, preventivi, ordini, fatture.
basterebbe ingrandirlo almeno di un punto e metterlo **in grassetto per evidenziarlo**.

![PRIMA](https://user-images.githubusercontent.com/75281007/216595119-2cd4e08d-1919-412a-87db-e5855d20f97b.png)

![DOPO](https://user-images.githubusercontent.com/75281007/216595233-a1bcfbb6-eae1-44c2-9e71-a60705dbe940.png)

## Possibile soluzione
  
abbiamo provato a modificare il /fatture/custom/footer.php

disabilitando il 'upper' tranne il Totale

riga 179 = <th class='text-center small' style='width:".$width."**; font-size:11pt;'**>
riga 206 = <td class='cell-padded text-center **small-bold'; style='width:".$width."; font-size:11pt;**'>

<img width="1524" alt="code" src="https://user-images.githubusercontent.com/75281007/216595783-b9fb40ac-7568-42ed-860e-70236adc52eb.png">

**Comment by NicolaNext** [comment]
Questo però funziona solo in parte perchè in caso di sconto, split payment ecc. ecc. va corretto anche il "netto a pagare"
