### ISSUE TITLE
Utente longato, in creazione documenti

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1174]
## Comportamento richiesto

abbiamo notato che quando si crea un qualsiasi documento di vendita / acquisto.

il sistema propone l'**anagrafica del utente loggato** o l'anagrafica Azienda🤔🤷🏻‍♂️
ci **si aspetta che questo campo sia vuoto** a prescindere dall'utente. 

![Screenshot 2023-02-03 alle 14 32 06](https://user-images.githubusercontent.com/75281007/216616069-6f2d391d-21ba-425f-a4d7-60671e71638f.png)

**Comment by Pek5892** [comment]
Buongiorno @sajotrei,
non riusciamo a riprodurre il problema, potrebbe provare in demo o su un'installazione pulita?

**Comment by sajotrei** [comment]
si certo
si già fatto anche su una installazione pulita.
il problema si presenta **SOLO** se l'azienda e l'utente loggato **sono anche clienti e fornitori**.

_________________
infatti se andiamo in anagrafica azienda e rimuoviamo Cliente e Fornitore in tipo anagrafica, il problema NON si presenta.
lo stesso vale per gli utenti tecnici.

![Screenshot 2023-02-06 alle 16 53 25](https://user-images.githubusercontent.com/75281007/217020390-bd6e956b-373e-4357-add7-d3a7d12aaaed.png)
![Screenshot 2023-02-06 alle 16 53 40](https://user-images.githubusercontent.com/75281007/217020397-cfce3ae7-39b8-4666-abea-046830622764.png)
![Screenshot 2023-02-06 alle 16 54 07](https://user-images.githubusercontent.com/75281007/217020400-5dd995e5-5081-42b8-95d9-b89747e1c70e.png)




![Screenshot 2023-02-06 alle 16 57 06](https://user-images.githubusercontent.com/75281007/217020627-ed5c2807-be08-40ec-8703-02d07768f8e2.png)

**Comment by sajotrei** [comment]
ovviamente per tamponare la cosa basta rimuovere i tecnici ( utenti ) e l'azienda come cliente/fornitore.

ma può capitare che un tecnico sia anche cliente e/o fornitore.

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/6f7b0a22e4066cbc4941274b4293ed2907fe1ced
