### ISSUE TITLE
Sezionale predefinito per tipo di documento

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1175]
## Comportamento richiesto

riteniamo possa essere molto utile, **impostare un Sezionale predefinito per tipo documento**.
così si riducono errori

anche perchè se si sbaglia ad associare il sezionale in creazione, poi nella fattura non è più possibile cambiarlo e si è costretti a eliminarla e rifarla da zero.

![Screenshot 2023-02-06 alle 12 39 12](https://user-images.githubusercontent.com/75281007/216962562-d8846a52-2a64-45de-af12-37b4692ebb87.png)

![Screenshot 2023-02-06 alle 12 38 16](https://user-images.githubusercontent.com/75281007/216962717-bbe20e74-2598-46b0-ab24-893d7539dbfd.png)

![Screenshot 2023-02-06 alle 12 37 58](https://user-images.githubusercontent.com/75281007/216962777-789db8a3-b025-48a7-8b97-4bb501d579cd.png)

## Comportamento attuale

al momento è possibile impostare un segmento predefinito per modulo, ma risulta limitato come metodo.

![Screenshot 2023-02-06 alle 12 44 12](https://user-images.githubusercontent.com/75281007/216963418-e96a3e6a-db2c-4fec-8d94-f11ac8b6a90d.png)

**Comment by sajotrei** [comment]
ovviamente sia per le fatture attive che passive. 😉

tra altro, penso che risolvendo questo punto, si risolvono di conseguenza anche questi due. 👍

importazione fatture elettroniche in segmenti diversi #1081
Fatture di Vendita, in segmenti diversi #1126

**Comment by Pek5892** [comment]
Introdotta la funzione di cambio sezionale tramite azioni di gruppo da commit https://github.com/devcode-it/openstamanager/commit/2512cfa2382034279cba915083f036393fced513

**Comment by sajotrei** [comment]
Ciao Valentina
ok grazie
anche se mi sembra più una escamotage più che risolvere a monte il creasi del problema

la possibilità di assegnare il sezionale al tipo di documento come ho indicato sopra non è tecnicamente applicabile?
