### ISSUE TITLE
(BUG)Rate in Modalità di pagamento

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1177]
## Comportamento richiesto

in pagamenti, per errore si è cliccato sul tasto Aggiungi, così facendo si sono create due rate aggiuntive.
ma dato che questa modalità è stata già usata in altri documenti, il tasto Elimina rata non è presente.

di conseguenza crea il problema nelle fatture, e non è possibile modificare/eliminare le rate aggiuntive.

![Screenshot 2023-02-07 alle 11 27 24](https://user-images.githubusercontent.com/75281007/217225464-50c782a6-2091-4222-a6ac-f37aa567ed5f.png)
![Screenshot 2023-02-07 alle 11 27 49](https://user-images.githubusercontent.com/75281007/217225488-1eeb4616-aa0f-4dcb-8c37-dd62016b2ba2.png)

![Screenshot 2023-02-07 alle 11 27 01](https://user-images.githubusercontent.com/75281007/217225498-88733dd2-d9ef-420d-88ca-20399d6c0ea1.png)

__________________

## Possibile soluzione

**Disattivare / Eliminare il pulsante Aggiungi**, così non si presenta il problema.

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/6c60aea8e7ee5024e106547c8fb09f9e053715ae
