### ISSUE TITLE
Cambio Tema front-end in impostazioni

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1178]
## Comportamento richiesto

penso possa essere utile introdurre **in impostazioni** la possibilità della **modifica del tema front-end**
magari addirittura per utente sarebbe ancora meglio.

## Comportamento attuale

attualmente per modificare il Tema grafico front-end è necessario modificare il file php di config.inc, e non è una cosa fattibile per gli users

https://forum.openstamanager.com/d/2378-tema-grafico

![Screenshot 2023-02-07 alle 16 56 57](https://user-images.githubusercontent.com/75281007/217296660-f824e59d-cd99-4e56-b4d2-bed968602e6b.png)

![theme-black](https://user-images.githubusercontent.com/75281007/217297876-1f48a408-1878-48de-a9e5-f943b788a277.png)
![theme-blu-light](https://user-images.githubusercontent.com/75281007/217297886-1975c7ec-092b-42ce-b40d-64a325974978.png)

**Comment by sajotrei** [comment]
nel frattempo che questa modifica venga implementata

può tornare già utile introdurre i Theme nel file /config.example.php

![Screenshot 2023-12-24 alle 16 18 45](https://github.com/devcode-it/openstamanager/assets/75281007/b8093ffa-b2a0-48a1-be03-5d2ed77ad49c)

**Comment by Pek5892** [comment]
Aggiunta la selezione del tema per gruppo di utenti nella versione 2.4.54

**Comment by sajotrei** [comment]
penso che i colori delle righe andranno un po "sbiaditi" per renderli meno coprenti, altrimenti non si legge il testo 

![Screenshot 2024-02-23 alle 18 09 35](https://github.com/devcode-it/openstamanager/assets/75281007/6dc39f43-04c0-4da5-94d3-3f533b59f261)

**Comment by lucasalva87** [comment]
Questa cosa è già stata gestita con la 2.4.55 di prossimo rilascio.
![immagine](https://github.com/devcode-it/openstamanager/assets/30728163/68fb3712-00ab-4d9e-8d13-bf9f2a5e6415)
