### ISSUE TITLE
Marca articoli

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1180]
## Comportamento richiesto

in articoli manca un campo rilevante, **Marca** 
magari che sia visibile come colonna in elenco articoli, con la possibilità di mappare questo valore in fase di import csv

https://forum.openstamanager.com/d/2275-aggiunta-campo-personalizzato-marca-prodotto

sarebbe utile introdurre questo campo nella schermata principale dell'articolo magari a fianco categoria.

![Unknown](https://user-images.githubusercontent.com/75281007/217361077-e0a48871-3235-4ca1-b9da-d4ee82809cd1.png)

___________________
noi **abbiamo provato con campi aggiunti, ma di fatto non è sufficiente** è solo un campo nota non a db

___________________
![Unknown2](https://user-images.githubusercontent.com/75281007/217361424-46fb6ef6-a8d7-4dd5-80fd-c9aa31618ce9.png)

**Comment by Pek5892** [comment]
Vedere anche: https://github.com/devcode-it/openstamanager/issues/1065

**Comment by sajotrei** [comment]
sarebbe molto utile poter inserire la marca articolo è un elemento importate che manca

anche facendo con i campi personalizzabili rimane comunque un valore non a DB e non visibile in elenco articoli.

<img width="1704" alt="Screenshot 2023-12-22 alle 00 02 18" src="https://github.com/devcode-it/openstamanager/assets/75281007/4bf8b903-14bf-4ef3-a8fc-606cb778b2c8">

**Comment by sajotrei** [comment]
Abbiamo notato che nella demo è prevista la tabella dei Marchi...


![Screenshot 2023-12-31 alle 16 20 47](https://github.com/devcode-it/openstamanager/assets/75281007/4b0479c0-1329-4a58-9964-2b3bb7ef18ea)

**Comment by Pek5892** [comment]
Buongiorno @sajotrei 

> anche facendo con i campi personalizzabili rimane comunque un valore non a DB e non visibile in elenco articoli.
i record vengono salvati nella cartella zz_field_record.

> Abbiamo notato che nella demo è prevista la tabella dei Marchi...
questo è uno screenshot dalla demo premium, questo modulo appartiene infatti ad un modulo aggiuntivo, non è presente nella versione standard del gestionale come può vedere in demo: https://demo.osmcloud.it/2452/

**Comment by NicolaNext** [comment]
La caratteristica della demo premium (introduzione del campo "marca") è davvero molto interessante tanto più che nella scheda "articolo" è già presente uno spazio vuoto che sembra proprio stare lì ad aspettare il campo suddetto.
A questo punto attendiamo con ansia di vedere il modulo aggiuntivo e il relativo costo.

![marca](https://github.com/devcode-it/openstamanager/assets/102433047/685a878c-81db-4c30-ad80-dc47743407d5)

**Comment by loviuz** [comment]
Il campo della marca articolo è stato introdotto per la prossima versione, e diventa un menu a tendina dove specificare il marchio e il link al sito del marchio.

Andremo a inserire anche un campo libero **Modello**, così da farla completa :-D
