### ISSUE TITLE
(BUG) Prezzo Ivato su stampa Etichette

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1181]
## Comportamento richiesto

abbiamo necessità di **stampare le etichette con il prezzo Ivato**.

dato che al momento non è disponibile una impostazione che ti permetta di scegliere se avere o meno il prezzo Ivato sulle etichette, quindi abbiamo modificato il seguente file come da istruzioni.

osm/templates/barcode/**custom/body.php**

![Screenshot 2023-02-08 alle 11 16 38](https://user-images.githubusercontent.com/75281007/217506051-3ccb3d73-41f5-4cff-8b7e-f300e315b163.png)
___

## Comportamento attuale

**la modifica** del file body.php, **influisce solo sulla stampa di etichette singole**, invece sulla stampa nel **_Formato A4 rimane con il prezzo imponibile._**

![articoli](https://user-images.githubusercontent.com/75281007/217508518-5ad4a345-16af-4dc6-97e4-0de85744e547.png)
___
![etichette A4](https://user-images.githubusercontent.com/75281007/217508577-3763c579-6917-4ef4-96e5-ffda561d438c.png)

___
![etichette singole](https://user-images.githubusercontent.com/75281007/217508603-f1466727-430c-448c-a479-54466f965812.png)

* Modulo:
* Versione del progetto: 2.4.39
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
In Strumenti>Impostazioni
Potrebbe essere utile che quando si Attiva usa prezzi comprensivi di IVA 
il **sistema abiliti la stampa etichette con prezzi ivati**

oppure, sempre in Strumenti>Impostazioni>Magazzino, aggiungere una selezione attiva/disattiva 

![Screenshot 2023-02-08 alle 11 34 58](https://user-images.githubusercontent.com/75281007/217510098-05c662e6-5d65-4ff0-b74f-9658f95af28a.png)

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/c8950fca7e6434aa214ba0556a72bb0b79b7c00a
