### ISSUE TITLE
info in Stampa scadenzario

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1183]
## Comportamento richiesto

quando si stampa lo scadenzario, n**on escono info in base alla selezione**, così come è ora rende difficile capire. 

si potrebbe aggiungere una scritta informativa, un po come si fa già per la stampa inventario magazzino.

![Screenshot 2023-02-09 alle 12 00 14](https://user-images.githubusercontent.com/75281007/217797161-19256e79-f04c-4d1e-85ce-2d4456743a6f.png)
_____
![Screenshot 2023-02-09 alle 12 00 38](https://user-images.githubusercontent.com/75281007/217797170-3f07bdd6-2eef-45a5-aabb-78062ac21313.png)
_____
![Screenshot 2023-02-09 alle 12 06 13](https://user-images.githubusercontent.com/75281007/217797173-a76e0ad7-c129-49f1-90e9-8b114a2a172a.png)

**Comment by Pek5892** [comment]
Vedere anche le scadenze generiche non collegate a documenti
