### ISSUE TITLE
(BUG) Selezione sezionale in Stampa registro IVA

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1187]
## Comportamento richiesto

in Contabilità>Stampe contabili>**Stampa registro IVA vendite e acquisti** 
non è possibile selezionare TUTTI I SEZIONALI

![Screenshot 2023-02-15 alle 15 31 17](https://user-images.githubusercontent.com/75281007/219058137-ec2fd06b-7b7c-4834-941f-d248dadc1883.png)
![Screenshot 2023-02-15 alle 15 31 21](https://user-images.githubusercontent.com/75281007/219058144-53c65668-0e62-4926-bb66-c8151e34503e.png)

* Modulo:
* Versione del progetto: 2.4.39
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
'Tutti i selezionali" viene correttamente selezionato e la stampa risulta corretta, ma non viene visualizzata la scelta nel selettore
