### ISSUE TITLE
PIANIFICAZIONE FATTURE - Richiede Cliente e fattura scollegata

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#119]
Dal contratto se si pianifica la fattura , si può creare la fattura direttamente dal contratto, ma confermando i dati non c'è traccia della fattura, non viene creata.
![image](https://user-images.githubusercontent.com/34273200/34989127-a48fb49e-fac1-11e7-93d9-e490acd386df.png)
Mentre dalla dashboard, cliccando su Fatture da emettere, appare la fattura da emettere
![image](https://user-images.githubusercontent.com/34273200/34989268-3b03bff6-fac2-11e7-8b0b-077fd97d8b79.png)
cliccando sul pulsante €, appare la form di creazione di una fattura normale, mentre il cliente non dovrebbe più chiedermelo.
![image](https://user-images.githubusercontent.com/34273200/34989321-63d5a98a-fac2-11e7-801a-0f588caebf9c.png)
Continuando inserimento e scegliendo il cliente, viene creata una fattura generica di quel cliente non collegata al contratto e senza la descrizione come da prima figura.

**Comment by loviuz** [comment]
avevamo temporaneamente disabilitato quel plugin per migliorarlo, altrimenti non rilasciavamo più la 2.3. metto tra le cose da sistemare/migliorare
