### ISSUE TITLE
Errata destinazione link "visualizza" prezzo articoli

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1190]
![IMG001](https://user-images.githubusercontent.com/40104356/219566239-cdebb56d-113e-4e14-b38f-dee09c922882.png)

## Comportamento richiesto

Nelle versioni precedenti i link portavano direttamente al listino, e questo rendeva immediata la modifica del prezzo

## Comportamento attuale

Adesso il link porta all'elenco degli articoli. Quindi si deve filtrare l'articolo e entrarvi dentro per effettuare l'aggiornamento dei prezzi

## Possibile soluzione

Ripristinare il comportamento delle versioni precedenti

* Versione del progetto: 2.4.39

**Comment by Pek5892** [comment]
Risolto in release 2.4.40
