### ISSUE TITLE
errore campi aggiuntivi personalizzati

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1192]
## Comportamento richiesto

errore campi aggiuntivi personalizzati

![Screenshot 2023-02-17 alle 18 38 10](https://user-images.githubusercontent.com/75281007/219794666-cd953815-b275-4f4c-8c95-79575a254b78.png)

* Modulo:
* Versione del progetto: 2.4.40
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei! potresti controllare il contenuto dei campi personalizzati? non riusciamo a replicare l'errore
![immagine](https://user-images.githubusercontent.com/102604205/220165064-401275c1-7021-42ca-94f3-d1aeb585cf9e.png)
![immagine](https://user-images.githubusercontent.com/102604205/220165118-bc9fb2f2-f8e1-45b3-8470-09b91c302926.png)

**Comment by sajotrei** [comment]
eccomi, ho verificato, il problema è dato sempre dagli apici che viene convertito **( & quot ; )**
ho provato a fare la correzione manuale e sembra ok

![Screenshot 2023-02-20 alle 18 01 55](https://user-images.githubusercontent.com/75281007/220166423-4c14d8b6-0907-45f0-a05f-b171ec6ae8ae.png)

![Screenshot 2023-02-20 alle 18 07 55](https://user-images.githubusercontent.com/75281007/220166745-b94b67e8-29e3-49e9-8002-47d961960fad.png)
