### ISSUE TITLE
Errore di agg. alla ver.2.4.40

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1194]
## Comportamento richiesto

Ciao, sto provando ad aggiornare alla 2.4.40
mi si blocca e nel file /logs/setup.log esce questo

[2023-02-17 21:56:23] 
Logs.EMERGENCY: Aggiornamento fallito: INSERT INTO zz_settings (id, nome, valore, tipo, editable, sezione, order, help) VALUES (NULL, "Stato predefinito dell\'attività da Dashboard", (SELECT idstatointervento FROM in_statiintervento WHERE descrizione = "Programmato"), 'query=SELECT idstatointervento AS id, descrizione AS text FROM in_statiintervento', '1', 'Attività', NULL, NULL) []
{"url":"/osm/index.php?action=do_update&firstuse=false","ip":"xxxxxx","http_method":"GET","server":"xxxxxxx","referrer":"/xxxxx/osm/index.php","uid":"29b8222"}

https://forum.openstamanager.com/d/2562-errore-di-agg-alla-ver2440
https://github.com/devcode-it/openstamanager/commit/99f0f3520b545e135b95d7f2fc0e5764bb2bd61b

* Modulo:
* Versione del progetto: 2.4.40
* Versione PHP:
* Tipo di server:

**Comment by loviuz** [comment]
Ciao @sajotrei,
probabilmente non hai più lo stato **Programmato** negli stati attività e la procedura di aggiornamento dà errore nell'inserire un'impostazione poiché cerca di inserire come valore predefinito l'id dello stato con descrizione uguale a **Programmato**, che probabilmente hai modificato. Credo dovremo modificare la query di aggiornamento usando il codice stato, perché la descrizione potrebbe essere cambiata. Per risolvere temporaneamente potresti rinominare lo stato con codice **WIP** in **Programmato** e rilanciare l'aggiornamento, e ripristinare mantenendo la tua descrizione. 

@Pek5892, forse conviene modificare la query di aggiornamento usando il campo **codice**, non ci avevo pensato. Per chi aggiornerà alla 2.4.40 avrà purtroppo il problema se ha cambiato la descrizione **Programmato** in altro, ma quando rilasceremo la 2.4.41 ci sarà l'inserimento dell'impostazione usando il campo **codice** invece di **descrizione**.

**Comment by sajotrei** [comment]
Ciao @loviuz , 
confermo che dopo aver modificato sul DB questi du valori.
TODO: Da programmare
WIP: Programmato

con il comando ?force ho forzato l'agg. ed è andato a buon fine! 👍
