### ISSUE TITLE
Filtro inserimento articoli non ricerca in base a codice fornitore

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1195]
Durante l'aggiunta di un articolo in un documento di acquisto, utilizzando il codice del fornitore, l'articolo non viene filtrato

* Versione del progetto: 2.4.40

**Comment by Pek5892** [comment]
Ciao @idraulicadueci,
ci risulta che attualmente sia possibile filtrare per codice fornitore:
![immagine](https://user-images.githubusercontent.com/102604205/231472578-551d8871-417c-4dff-814d-97236c9e7138.png)
