### ISSUE TITLE
(BUG) Visualizza informazioni aggiuntive sul calendario

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1196]
## Comportamento richiesto

abbiamo aggiornato dalla 2.4.39 alla 2.4.40
in impostazioni è abilitato: **Visualizza informazioni aggiuntive sul calendario**

si vedono in calendario ma se ci clicchiamo sopra non trova il riferimento.

<img width="597" alt="Screenshot 2023-02-21 alle 22 40 20" src="https://user-images.githubusercontent.com/75281007/220464722-a466c5dd-0880-49bf-89e1-cb5092056a82.png">

![Screenshot 2023-02-21 alle 22 38 33](https://user-images.githubusercontent.com/75281007/220464754-d574392e-1e4d-4caf-afb0-9cb975026d03.png)

* Modulo: Dashboard
* Versione del progetto: 2.4.40
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/2b77c2ee4ad9557eb1d088576470a2cba43f8d90

**Comment by sajotrei** [comment]
anche aggiornando alla 2441 il problema è rimasto.

cliccando sull'informazione aggiuntiva non trova il riferimento al doc.


<img width="974" alt="Screenshot 2023-02-28 alle 11 32 42" src="https://user-images.githubusercontent.com/75281007/221829334-c1a3299d-a397-41e9-8fea-cc0bb1dc32e6.png">

<img width="721" alt="Screenshot 2023-02-28 alle 11 32 53" src="https://user-images.githubusercontent.com/75281007/221829340-7d5669ec-d3a3-4b8a-93aa-d1da53773835.png">

**Comment by sajotrei** [comment]
inoltre se si crea un nuovo preventivo 
in dashboard non crea le info aggiuntive

<img width="1528" alt="preventivo" src="https://user-images.githubusercontent.com/75281007/221832479-f29b6dce-31a0-4fdb-b0c5-c1577540dbfe.png">

<img width="1528" alt="dashborad" src="https://user-images.githubusercontent.com/75281007/221832471-6e560377-ca2d-4fc2-aa48-9b3e3d1b40c8.png">

**Comment by Pek5892** [comment]
Lo stato del preventivo deve essere "In lavorazione"

**Comment by sajotrei** [comment]
a ok, si ho verificato e funziona

resta comunque il Problema che non apre il doc...

<img width="1444" alt="Screenshot 2023-02-28 alle 18 21 39" src="https://user-images.githubusercontent.com/75281007/221929974-33a8df86-4dcd-470b-8797-f7841e6fc28b.png">
