### ISSUE TITLE
BUG note interne in modulo attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1199]
## Comportamento attuale

Il campo non consente di andare a capo. Se si preme invio, viene restituito il seguente errore:

![IMG001](https://user-images.githubusercontent.com/40104356/221304776-5def30a4-de2c-4147-a404-ae51d57100a1.png)

## Passi per riprodurre il comportamento

Creare un intervento
Digitare una stringa di testo nel campo "Note interne" e premere invio per andare a capo

## Contesto

* Modulo: Attività
* Versione del progetto: 2.4.40

**Comment by sajotrei** [comment]
si confermo
ho notato che quando si preme invio il cursore passa nel campo di inserimento codice a barre

<img width="1218" alt="Screenshot 2023-02-24 alle 23 42 14" src="https://user-images.githubusercontent.com/75281007/221311072-39fb767e-ae58-4390-bf41-c8a1f1a8abe5.png">

<img width="1509" alt="Screenshot 2023-02-24 alle 23 42 35" src="https://user-images.githubusercontent.com/75281007/221311102-b6699984-79f6-4bef-9a5e-ae660b964b6b.png">
