### ISSUE TITLE
Gestione avanzata permessi

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#12]
Aggiunta modulo per la gestione dei filtri permessi, in modo da poter scegliere quali filtri abilitare per gruppo.
Esempio:
il gruppo "Tecnici" potrà vedere solo i suoi interventi, oppure tutti. Sarà l'amministratore che abiliterà o meno questo filtro.
Possibilità di aggiungere filtri manualmente con query (modalità avanzata per esperti).

**Comment by Dasc3er** [comment]
Al momento questa funzionalità è parzialmente permessa dal nuovo modulo Viste, con la sezione Filtri in fondo alla pagina del modulo...

@loviuz Come vorresti espanderla?

**Comment by loviuz** [comment]
rivedendola ieri è ottima già così! basterebbe solo dare un nome a questi filtri, tipo "Mostra ai tecnici solo i propri interventi", e mettere tutti questi filtri anche nella schermata dei gruppi, con la sola possibilità di attivare o meno l'opzione. In questo modo possiamo predisporre dei filtri utili e tenerli disattivati di default, in modo che l'utente possa solo attivarli/disattivarli. Gli esperti potranno comunque crearne di nuovi.
