### ISSUE TITLE
FATTURE - inserimento di un intervento in fattura

### ISSUE THREAD

**Issue by mosaico48625** [devcode-it/openstamanager#120]
salve,
in fattura , quando si aggiunge un preventivo c'è la checkbox (importa righe in fattura).....
sarebbe corretto metterlo anche quando si aggiunge un intervento, in quanto se ho 100 articoli nell'intervento viene una fattura lunga un km !!

**Comment by lucasalva87** [comment]
Inoltre sarebbe da aggiungere un flag per scegliere se importare o meno la descrizione dell'intervento.

**Comment by loviuz** [comment]
Sarebbe da migliorare un po' perché attualmente, se spunto la checkbox dopo la scelta intervento, non mi riporta la descrizione

**Comment by Dasc3er** [comment]
Con le modifiche più recenti nella gestione delle righe dei documenti, questo comportamento è necessario e inevitabile. E' però possibile procedere al raggruppamento delle righe nei documenti sulla base dei documenti di origine per la visualizzazione grafica normale (ed eventualmente, con dovute considerazioni, per le stampe).

@loviuz @lucasalva87 Che ne pensate? Potrebbe essere utile una Impostazione apposita "Raggruppa righe per documento di origine"?

**Comment by Dasc3er** [comment]
Chiuso in favore di #860, che tratta il problema più nel dettaglio.
