### ISSUE TITLE
Errore Calcolo Iva in liquidazione

### ISSUE THREAD

**Issue by cigo76** [devcode-it/openstamanager#1200]
Errore riscontrato
Nel modulo contabilità, liquidazione iva.
Errore sul calcolo dell' Iva in base alle specifiche definite in tabella Iva.

Il comportamento richiesto dovrebbe essere , che l'iva venga calcolata tenendo conto della % di indetraibilità.

N.B. se si controlla il registro iva esce con importo corretto.

OSM 2.4.40

**Comment by Pek5892** [comment]
Buongiorno @cigo76, già trattato in https://github.com/devcode-it/openstamanager/issues/1158.

**Comment by cigo76** [comment]
Ma è stato risolto il problema?
Dove posso trovare la modifica da fare per sistemare?

Grazie!!

Il ven 17 mar 2023, 11:42 Valentina ***@***.***> ha scritto:

**Comment by sajotrei** [comment]
@cigo76
per il momento non è ancora stato risolto
@Pek5892 ha chiuso solo le issues che richiamavano lo stesso problema.

al momento quella aperta è questa.
**Errore Calcolo Iva in liquidazione #1158**

**Comment by Pek5892** [comment]
Buongiorno @cigo76,  potrebbe applicare questa fix e verificare i calcoli: https://github.com/devcode-it/openstamanager/commit/7b8c67b443637ff1ff73d3e4ce6f9fdf37f40da9?
