### ISSUE TITLE
Errore corpo invio email da fatture

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1203]
## Comportamento richiesto

Nelle versioni precedenti funzionava tutto correttamente

## Comportamento attuale

Il testo delle email non è corretto e ci sono caratteri unescaped:
![image](https://user-images.githubusercontent.com/392762/221672134-69d70945-77b5-440d-9343-fb56de85a72a.png)

In piu l'editor sembra funzionare in modo errato post invio anche con le spaziature:
![image](https://user-images.githubusercontent.com/392762/221672578-49a80f24-f019-4bd3-a7b7-353f033e0783.png)

## Possibile soluzione

Un aggiornamento dell'editor potrebbe aver causato questo.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Creare una fattura
2. Cliccare su Invia email in alto
3.

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: fatture/documenti
* Versione del progetto: 2.4.41
* Versione PHP: 8.0.27
* Tipo di server: Aruba

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/c8470911407389e5b4ab5619a7495c2107b87680
(Modifica nel file mail.php)
