### ISSUE TITLE
Filtro su campi data nelle viste

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [devcode-it/openstamanager#1204]
Buongiorno,
ho cercato nel forum e su github ma non ho trovato nulla a riguardo. o meglio ho trovato questo 
https://forum.openstamanager.com/d/1377-filtri-sulle-viste/2
avrei la necessità di filtrare dei contratti/rapportini o altro usando i campi delle viste .
utilizzando il periodo temporale in alto permette di filtrare solo per un campo data ma la mia necessità a volta è di filtrare per altre date del modulo. ho visto che il campo data filtra come se fosse una stringa. è possibile filtrare anche per data > o data < oppure data compresa ?
grazie

**Comment by andreameneguzzoinfol** [comment]
nessuno?

**Comment by Pek5892** [comment]
Buongiorno @andreameneguzzoinfol, attualmente è possibile filtrare per periodi unicamente dal filtro in alto. E' possibile eventualmente modificare il campo su cui questo filtro viene applicato modificando la query del modulo in Viste.

**Comment by Pek5892** [comment]
Il filtro per data > e < sarà disponibile dalla versione 2.4.48
