### ISSUE TITLE
(BUG) Campo obbligatorio in attività

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1206]
## Comportamento richiesto

nel creare un nuova attività non tiene in considerazione il campo obbligatorio **Richiesta**

![Screenshot 2023-03-01 alle 10 48 27](https://user-images.githubusercontent.com/75281007/222104314-39d8c065-5a30-4c88-85d3-c7d1fc6cb88d.png)

* Modulo:
* Versione del progetto: 2.4.41
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei, potresti essere più specifico? riscontri lo stesso problema anche in demo?

**Comment by sajotrei** [comment]
di fatto ti permette di creare l'attività senza compilare il campo richieste che è obbligatorio.

invece gli altri campi obbligatori ( con asterisco ) se non li compili il sistema ti segnala valore richiesto 

si si confermo anche in demo, ho fatto subito la verifica prima di aprire la issue
https://demo.osmcloud.it/2441

comunque il problema cera anche prima nelle versioni precedenti almeno dalla ver.2437
