### ISSUE TITLE
Attività in Dashboard

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1207]
## Comportamento richiesto

quando si crea una attività nella dashboard dopo aver cliccato su aggiungi ci si aspetta di vederla sul calendario
invece risulta vuoto, solo aggiornando la pagina del browser si vede l'attività appena creata. 🤔

questo capita su **tutte le installazione dove abbiamo aggiornato** con la 2440 e 2441

se si fa una installazione pulita non si presenta il problema.
abbiamo fatto delle prove sulla demo online 2441 e il problema non si presenta.

in parte è legato a questo
Impossibile creare eventi su calendario #1193

* Modulo:
* Versione del progetto: 2.4.41
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei! Durante l'aggiornamento vi hanno dato errore delle query e avete dovuto forzarlo? la release non presenta questo problema, che altrimenti si presenterebbe anche in fase di aggiornamento su nuova installazione. Sembrerebbe un problema legato alle vostre installazioni, probabilmente per qualche query che in fase di aggiornamento non è riuscito ad eseguire o qualche file personalizzato e non allineato all'ultima versione. Eseguendo un controllo sul gestionale vengono evidenziate differenze che implicano la dashboard? https://docs.openstamanager.com/v/2.4.41/guide/esempi/verificare-linstallazione-di-osm

**Comment by sajotrei** [comment]
- nessun errore in fase di agg.
- niente problemi/errori o avvisi nei controlli 
- il problema si presenta anche su installazioni pulite che usiamo come test e non hanno personalizzazioni.
- ho provato anche a cancellare la cache e ho provato ad accedere con vari browser
-

**Comment by Pek5892** [comment]
sostituendo i file della vostra installazione con quelli presenti nello zip il problema rimane?

**Comment by sajotrei** [comment]
abbiamo provato a fare così solo nella installazione di test e il problema si risolve.

**Comment by Pek5892** [comment]
Quindi il problema sembrerebbe essere dovuto a qualche file non aggiornato correttamente dalle versioni precedenti, e non riproducibile.

**Comment by kenchu84** [comment]
Succede anche a noi, installazione pulita 2.4.40, anche nel modulo disponibilità.

**Comment by kenchu84** [comment]
Vi aggiorno, se creo attività in vista "Giorno" o "Settimana" e richiamo la vista agenda o settimana, il calendario non si aggiorna, se invece richiamo la vista "mese", per un millesimo di secondo compare il loading e l'evento da quel momento compare. 
Nella vista mese, di contro, non mi permette di creare nuovi eventi. Non riesco a creare eventi "allDay" invece, in nessuna visualizzazione.

**Comment by Pek5892** [comment]
Buongiorno @kenchu84, Il modulo disponibilità tecnici è quello aggiornato compatibile con fullcalendar 6?
Il problema si presenta anche nel caso in cui sia già stato selezionato almeno un tecnico nel filtro?

**Comment by kenchu84** [comment]
> > ## Comportamento richiesto
> > quando si crea una attività nella dashboard dopo aver cliccato su aggiungi ci si aspetta di vederla sul calendario invece risulta vuoto, solo aggiornando la pagina del browser si vede l'attività appena creata. 🤔
> > questo capita su **tutte le installazione dove abbiamo aggiornato** con la 2440 e 2441
> > se si fa una installazione pulita non si presenta il problema. abbiamo fatto delle prove sulla demo online 2441 e il problema non si presenta.
> > in parte è legato a questo Impossibile creare eventi su calendario #1193
> > 
> > * Modulo:
> > * Versione del progetto: 2.4.41
> > * Versione PHP:
> > * Tipo di server:
> 
> @Pek5892 grazie Valentina per avere trovato cosa causava il problema! 👍
> 
> il calendario dava problemi a causa di un file personalizzato in interventi sotto custom in cui non era stata apportata la modifica che riporta la corretta chiamata ajax per vedere le attività inserite a calendario.

Ciao scusa, che modifica avevi ? Noi non abbiamo modifiche, eppure il calendario non si aggiorno se non premo F5...

**Comment by sajotrei** [comment]
/modules/interventi/add.php

la modifica a sx è quella corretta

<img width="1676" alt="Screenshot 2023-03-04 alle 01 07 21" src="https://user-images.githubusercontent.com/75281007/222857810-1e66d3c0-7140-4f0b-89f5-9fde6a0269f7.png">

**Comment by kenchu84** [comment]
Applicata la modifica,ma senza successo, devo premere sempre F5...
