### ISSUE TITLE
New segmento in fatture di acquisto

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1209]
## Comportamento richiesto

riteniamo sia **utile aggiungere questo filtro in relase**
perché ha senso avere a disposizione anche l'elenco completo di **tutte le fatture che hanno valore fiscale.**

https://forum.openstamanager.com/d/2567-new-segmento-in-fatture-di-acquisto

![Screenshot 2023-03-01 alle 12 29 19](https://user-images.githubusercontent.com/75281007/222127036-08017ff3-159d-4af4-b91f-874ecc90dbbe.png)

**Comment by sajotrei** [comment]
Ciao Valentina 
era una cosa definita sul forum con te diversi mesi fa

sarebbe utile metterla in relase con la query corretta, e se fosse possibile anche con i valori nei widget 

https://forum.openstamanager.com/d/2567-risolto-new-segmento-in-fatture-di-acquisto

**Comment by Pek5892** [comment]
Per il caso specifico la query era stata strutturata in questo modo, usando quindi gli id, perchè l'installazione riporta nomi dei sezionali personalizzati. Che è anche il motivo principale per cui non possiamo introdurre in release un segmento che fa riferimento ad altri segmenti che possono essere modificati manualmente dall'utente.
