### ISSUE TITLE
DDT - Vendita

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#121]
Il pulsante "Crea Fattura da DDT.." è visibile solo quando il DDT è in Bozza, dovrebbe essere attivo quando è stato Evaso.
Se si crea la fattura il DDT non cambia stato, dovrebbe risultare Fatturato

**Comment by loviuz** [comment]
E' stato cambiato lo stato "Pagato" in "Fatturato" (che ha più senso per un ddt), ed è stato aggiunto lo stato "Parzialmente fatturato" nel caso non sia stato fatturato tutto il ddt.
Sistemato anche il pulsante di creazione ddt che non si vede finché è in bozza o fatturato.
Aggiunto anche l'aggiornamento automatico dello stato ddt quando si evade in fattura o si modifica la fattura contenente ddt.
16d78485be8f0c6953d2915279422273b66271d1
