### ISSUE TITLE
Aumento quantità in aggiunta articoli nei documenti

### ISSUE THREAD

**Issue by Pek5892** [devcode-it/openstamanager#1216]
All'aggiunta di un articolo nei documenti, sarebbe corretto che si andasse ad aumentare la quantità in caso di articolo già presente, anzichè aggiungere una nuova riga con lo stesso articolo. Utile soprattutto in fase di aggiunta articoli tramite barcode.

**Comment by bulleITA** [comment]
Sarebbe corretto scegliere, nel mio caso a volte viene richiesto dei preventivi fatti a "zone" dove lo stesso articolo compare su piu "zone".
Sarebbe invece corretto se quando viene creato un ordine fornitore venissero unificati tutti gli articoli sommati.

**Comment by Pek5892** [comment]
Problemi nell'accorpamento di articoli con sconti diversi.
