### ISSUE TITLE
Statistiche Vendite e acquisti

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1217]
## Comportamento richiesto

i periodi temporali aggiuntivi si vendo in nero rendendoli poco comprensibili.

![Screenshot 2023-03-02 alle 20 34 18](https://user-images.githubusercontent.com/75281007/222533881-9b66853f-72d7-4f34-982c-0c6fc79b6bba.png)

* Modulo:
* Versione del progetto: 2.4.43
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/e9db2e20100944fad6d0c93c414cd1a5e496a9f2
