### ISSUE TITLE
Widget contratti in scadenza in Dashboard, visualizzazione errate

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#122]
Contratti in scadenza appaiono in Dashboard quando contratto è in attesa di pagamento , ma quando voglio vedere il contratto in scadenza mi appare nessuna scadenza.
Ripeto , nel mio caso il contratto era "in attesa pagamento".

**Comment by loviuz** [comment]
Si potrebbero impostare dei flag sugli stati contratto per indicare quali stati vengono considerati come "chiusi" e quali aperti, perché è hard-coded ora il controllo sugli stati contratto da considerare nelle scadenze

**Comment by Dasc3er** [comment]
SI potrebbe impostare la gestione in modo simile a quella definita nella versione 2.3 per i Contratti (tabella **co_staticontratti**).

**Comment by Dasc3er** [comment]
Miglioria completata tempo fa.
