### ISSUE TITLE
Stato preventivo durante creazione

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1220]
Quale utilità ha scegliere lo stato del preventivo nella finestra di creazione? Se è in creazione non è una bozza al 100%?

**Comment by sajotrei** [comment]
si vero.
anche se a volte può capitare che un preventivo sia già accettato a voce, quindi quando lo si crea lo si mette già in stato accettato.

comunque per velocizzare in fase di creazione sarebbe **utile che fosse giù in stato bozza**, poi al massimo lo si cambia a piacimento.

**Comment by bulleITA** [comment]
> si vero. anche se a volte può capitare che un preventivo sia già accettato a voce, quindi quando lo si crea lo si mette già in stato accettato.
> 
> comunque per velocizzare in fase di creazione sarebbe **utile che fosse giù in stato bozza**, poi al massimo lo si cambia a piacimento.

Ma se lo metti già accettato te lo blocca e non puoi aggiungere nessuna voce...
