### ISSUE TITLE
Visualizzazione articoli per categoria/sottocategoria

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1221]
Sarebbe comodo se sia in magazzino che in fase di aggiunta degli articoli nei documenti fosse possibile filtrare con un menuva tendina le varie categorie/sottocategorie.
Magari con un widget in magazzino.

**Comment by Pek5892** [comment]
In magazzino è  possibile filtrare i record per categoria e sottocategoria tramite appositi filtri: 
![immagine](https://user-images.githubusercontent.com/102604205/222734556-727a1d4e-75da-45b0-a5c7-89e857e8724d.png)

**Comment by bulleITA** [comment]
> Salve @bulleITA , In magazzino è possibile filtrare i record per categoria e sottocategoria tramite appositi filtri, cosa intende? ![immagine](https://user-images.githubusercontent.com/102604205/222734556-727a1d4e-75da-45b0-a5c7-89e857e8724d.png)

si certo già lo uso cosi, in alcuni casi trovo scomodo non avere un menu a tendina dove si scelgono i valori.
