### ISSUE TITLE
Problema visualizzazione schermi piccoli e/o portrait

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1223]
Alcuni campi quando vengono visualizzati in schermi con pochi pixel vengono visualizzati in verticale in una lunghezza assurda.
![image](https://user-images.githubusercontent.com/103928231/223217805-c0c04744-ad4b-43ac-837d-66077db5e21a.png)

Suggerirei di mettere un limite massimo alle righe ed aggiungerci un "...altro"
Inoltre farei ridimensionare prima altre colonne prima di quella della descrizione, es. Q.tà, Sconto..
Questo problema ovviamente non è solo nel modulo preventivi ma su tanti moduli

**Comment by Pek5892** [comment]
Sono state apportate delle migliorie alla visualizzazione delle tabelle da altri dispositivi, il problema dovrebbe ora essere risolto.
