### ISSUE TITLE
Autofattura collegata

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1224]
## Comportamento richiesto

quando si importa e registra una Autofattura passiva, nella sezione Autofattura collegata ci si aspetta di vedere l'elenco solo di quella ancora aperte, invece si vedono tutte anche di anni precedenti.

una soluzione potrebbe essere di **elencare solo quelle ancora aperte**.
se possibile, ancora meglio, che rilevi l'autofattura corrispondete magari tramite alcuni valori ( anagrafica, importo, ecc.. )

<img width="482" alt="Screenshot 2023-03-06 alle 21 04 55" src="https://user-images.githubusercontent.com/75281007/223218968-7963a4ed-4e7f-4881-b2ed-01024644a46b.png">

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/31713bbb51f1b112892cea9ca993710c6c37dd0b
