### ISSUE TITLE
Manifest.json mancante

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1226]
Installando una 2.4.41 da zero mi da errore nel trovare il file manifest.json
Credo che questo problema ci sia dalla 2.3.39

**Comment by Pek5892** [comment]
Sono stati impostati correttamente i permessi? il file manifest.json viene creato al primo accesso nel gestionale.

**Comment by bulleITA** [comment]
I permessi erano impostati in lettura e scrittura, comunque ho risolto mettendolo manualmente
