### ISSUE TITLE
Comportamento promemoria da pianificare

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1227]
Nel widget promemoria da pianificare nella dashboard vengono visualizzate le attività che sono state create con lo stato "da programmare".
Se un'attività già creata con altri stati viene messa nello stato "da programmare" non viene visualizzata

**Comment by Pek5892** [comment]
Buongiorno @bulleITA,
nel widget "Promemoria attività da pianificare" vengono visualizzate tutte le attività che non hanno nessuna sessione di lavoro inserita, mentre nel widget "Attività nello stato da programmare"  è possibile visualizzare tutte le attività che si trovato in questo stato.
