### ISSUE TITLE
Inserimento intervento in fattura, costo ore intervento poco chiaro

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#123]
Quando inserisco in una fattura un intervento che comprende ore da diversi tipi di attività, in fattura vengono sommati e mostra come costo da quel che ho capito **la media del costo delle ore**.
A livello contabile questo è poco chiaro.

**Comment by antonioscarpino** [comment]
vedi https://github.com/devcode-it/openstamanager/issues/110 lo avevo già proposto

**Comment by lepool** [comment]
OK , allora chiudo.

**Comment by lepool** [comment]
Avevo letto male , qui si parla di inserimento intervento in fattura , non la stampa intervento.
Riapro la richiesta

**Comment by antonioscarpino** [comment]
Ah ok.
Visto che, anche nella stampa intervento viene fatta una media sul costo delle ore che è poco chiara la cosa mi ha tratto in errore.
Chiedo scusa.

**Comment by loviuz** [comment]
duplicato di #110

**Comment by lepool** [comment]
@loviuz , ho visto che hai segnato questo issue come duplicato. In fattura la stampa della parte dell'intervento risulta poco chiaro.
Ad esempio se ho un intervento con due posizioni di tipologie intervento : 
- intervento generico 1 ora con tecnico 1
- intervento ordine servizio 1 ora con tecnico 2

Ora nella stampa della fattura risulta come segue:
- 2 ore a 15€ (come tariffe ho lasciato quelli di default 30€ generico e 0€ ordine di servizio) cioè ti segna la media del costo delle ore. 
Se uno ha un offerta dove sono indicate determinate tariffe, dalla fattura non si evince bene il conto delle ore svolte, mentre nella stampa dell'intervento si vedono le posizioni differenti ma manca la tariffa delle singole posizioni.  Il totale risulta giusto sia in interventi che in fatture, ma l'elenco è poco chiaro.

Domani provo a mandare una proposta della stampa
