### ISSUE TITLE
(BUG) prezzo di vendita in ordine fornitore

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1231]
## Comportamento richiesto

**in ordine fornitore** quando si inserisce un articolo **riporta il prezzo di vendita anziché il prezzo di acquisto**.

![Screenshot 2023-03-09 alle 16 33 30](https://user-images.githubusercontent.com/75281007/224074427-70274972-fec2-4971-88ea-2f2f12fbc16c.png)
<img width="1901" alt="Screenshot 2023-03-09 alle 16 34 08" src="https://user-images.githubusercontent.com/75281007/224074434-4dd16166-9896-4d34-88eb-daa80eacc1c8.png">

* Modulo:
* Versione del progetto: 2.4.40
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Si risolve con questa fix: https://github.com/devcode-it/openstamanager/commit/d802dda05afa262e00fd0eaa47188f1821c56e65
che va a togliere la direzione fissa dagli ordini

**Comment by sajotrei** [comment]
Ciao, abbiamo applicato la modifica ma non cambia nulla.
preciso che **il problema che abbiamo segnalato si presenta su Ordine a Fornitore** 
invece la modifica è su ordini cliente e preventivi

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/86fd08124f2196ce8c7a2c9ddc91912acda2d9f9

**Comment by sajotrei** [comment]
ok confermo che con questa modifica ora il problema è risolto 👍
