### ISSUE TITLE
Importazione fatture elettroniche di acquisto non ricerca IVA da natura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1233]
## Comportamento richiesto

Quando importo una fattura di acquisto, il campo IVA dovrebbe essere popolato automaticamente anche in base alla natura indicata nel file XML.

## Comportamento attuale

Importando una fattura elettronica da file XML, se questa contiene un'aliquota IVA indicata come N(x), il campo resta vuoto e devo compilarlo manualmente, indicando per esempio "Escluso art. 15", invece di "N1" (con N1 non trova la voce)

## Possibile soluzione

Implementare nella query di ricerca dell'aliquota IVA, il campo `codice_natura_fe`

## Contesto

* Versione del progetto: 2.4.41

**Comment by Pek5892** [comment]
Attualmente l'aliquota IVA proposta nel menu a tendina in fase di importazione viene ricercata tra le aliquote con la natura IVA indicata nell'xml della fattura di acquisto.
