### ISSUE TITLE
Aggiornamento stato preventivo

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#1235]
Quando si crea un ordine cliente dal preventivo, poi si crea il ddt dal relativo ordine e successivamente la fattura dal ddt, il preventivo non cambia di stato. Dovrebbe cambiare in stato Fatturato.

**Comment by Pek5892** [comment]
Si verifica un problema analogo seguendo il flusso ddt->attività->fattura, il ddt non cambia stato in fatturato, probabilmente vengono persi dei riferimenti.

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/330434d4726779598888d2151033cf5670831455
