### ISSUE TITLE
Colonna q.tà disponibile in preventivo

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1236]
## Comportamento richiesto

Sarebbe molto utile por avere **una colonna q.tà disponibile nel preventivo**
magari che si và ad aggiornare quando lo si riapre.

**esempio**,
- si crea un preventivo e nel selezionare la merce si vede quanti pezzi sono disponibili
- si spedisce il prev. al ciente
- dopo qualche giorno il cliente conferma il preventivo
- riaprendo il documento il sistema aggiorna la q.tà nella colonna e così si avrà in live la disponibilità merce

![colonna ](https://user-images.githubusercontent.com/75281007/224318368-56a4f2ad-1e17-4b48-b721-11c094bf83c2.png)

**Comment by sajotrei** [comment]
in alternativa aggiungere il Button simile a quello già presente in ordine cliente.

![Screenshot 2023-03-12 alle 14 33 34](https://user-images.githubusercontent.com/75281007/224548121-5bf0e045-c0ad-433a-8716-be229c93bf9f.png)

**Comment by bulleITA** [comment]
io invece suggerirei di creare una sezione dove vengono scelte le colonne da visualizzare, come già si può fare per esempio nel'elenco delle attività. ho creato un post nel forum a riguardo "Personalizzazione viste righe"

**Comment by sajotrei** [comment]
@bulleITA 
nei vari **elenchi** ( attività, preventivi, ecc... ) **è già possibile scegliere le colonne** da visualizzare, e in parte anche modificare il nome della colonna

ma non è possibile scegliere le colonne dentro i documenti
si sarebbe comodo se fosse possibile avere un'impostazione ( simile a viste ) per poter aggiungere, abilitare/disabilitare le colonne dentro i documenti.

ma questa modifica è più impegnativa della richiesta iniziale 😅

**Comment by lucasalva87** [comment]
Ciao segnalo che nella 2.4.42 abbiamo iniziato a potenziare le opzioni per le stampe.
Questa logica potrebbe essere utile per abilitare/disabilitare colonne e quindi visualizzare/nascondere valori sul documento generato.

![immagine](https://user-images.githubusercontent.com/30728163/224977777-3b371716-3666-42a9-b3d4-55fb8c9c8264.png)

**Comment by sajotrei** [comment]
Ciao @lucasalva87 
si ho visto, interessate 👍, lo testeremo meglio nei prox gg.

ma questa issue non è per la stampa, ma proprio nel documento stesso, così da poter avere la possibilità di sapere se la merce proposta è ancora disponibile a magazzino.
al momento per verificare si apre una seconda pagina e si fa la ricerca degli articoli in questione.

**Comment by sajotrei** [comment]
in teoria dovrebbe bastare recuperare queste righe di codice da modules/ordini/**edit.php**
righe 288 a 294

e creare/**modificare** questo file /modules/preventivi/**quantita_impegnate.php**

**Comment by Pek5892** [comment]
Chiudo issue in quanto duplicata https://github.com/devcode-it/openstamanager/issues/1168

**Comment by sajotrei** [comment]
Ciao Valentina, non sono la stessa richiesta, sono correlate

la proposta di avere una colonna della merce disponibile
