### ISSUE TITLE
errore nel creare Checklist

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1238]
## Comportamento richiesto

provata la demo 2.4.42

![Screenshot 2023-03-10 alle 23 57 46](https://user-images.githubusercontent.com/75281007/224443856-e2d0efd9-1b3d-4487-a2f0-0e3cbdd7b73a.png)

* Modulo:
* Versione del progetto: 2.4.42
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno @sajotrei, potreste darci maggiori informazioni riguardo l'errore? che passaggi eseguite?

**Comment by sajotrei** [comment]
l'errore si presenta quando crei il contenuto della Check-list
o provi a modificarne una già esistente.

se proviamo in interventi sembra funzionare.

![Screenshot 2023-03-13 alle 10 32 28](https://user-images.githubusercontent.com/75281007/224661946-8b89d76a-a4cc-485e-b945-6bfe6fd201ed.png)

**Comment by sajotrei** [comment]
abbiamo provato con questo commit https://github.com/devcode-it/openstamanager/commit/278e77d715e76d9608256d79d9c5e5ab1b756d35 
è si risolve 👍

**Comment by sajotrei** [comment]
In stampa si presenta così 


![IMG_5390](https://user-images.githubusercontent.com/75281007/225134327-25a280bd-0224-40a8-bf6b-aca4cbeae68d.jpeg)
