### ISSUE TITLE
articoli in registrazione fattura passiva

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1239]
## Comportamento richiesto

quando un articolo creato a magazzino ha la descrizione su più righe
in fase di associazione articoli in registrazione fattura passiva si presenta questo errore grafico.

![Screenshot 2023-03-12 alle 14 36 38](https://user-images.githubusercontent.com/75281007/224687703-394d13a6-4a6e-4099-af41-e200f8b26bb8.png)

* Modulo:
* Versione del progetto: 2.4.42
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno @sajotrei,
non riusciamo a riprodurre l'errore:
![immagine](https://user-images.githubusercontent.com/102604205/225937189-bedda3ea-d40d-46e3-a372-81fb54b8a3b7.png)
![immagine](https://user-images.githubusercontent.com/102604205/225937333-b62ff825-f05d-43e4-82a2-974ad3327130.png)

**Comment by sajotrei** [comment]
non saprei il motivo, a noi si presenta anche con articoli con la descrizione su du righe 🤔🤷🏻‍♂️

**Comment by Pek5892** [comment]
Il problema si verifica ancora?

**Comment by sajotrei** [comment]
stranamente si 🤷🏻‍♂️🤔
ma dato che non abbiamo molti articoli su più righe il problema non causa disagi.

**Comment by Pek5892** [comment]
Errore non riproducibile in un'installazione pulita
