### ISSUE TITLE
Gestione campi personalizzati

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#124]
Poter gestire dei campi personalizzati per ogni modulo, tramite uno strumento via web. Basterebbe indicare:
 - etichetta campo
 - tipologia: intero, decimali, data, stringa, menu a tendina con query (modalità utenti esperti)

Farli uscire poi in un panel a parte in fondo su edit.php, sotto "Campi personalizzati"

**Comment by Dasc3er** [comment]
Tabella per la gestione dei campi personalizzati

- id
- id_module
- content (formato JSON semplificato oppure HTML)
- options (possibile query aggiuntiva per ottenere dati da un altro elemento)
- order

Tabella per i valori dei campi personalizzati

- id
- id_campo
- id_record
- value (campo TEXT)

Aggiungere hook (`{( controller_before )}` o simili) per l'aggiunta automatica di questi campi in fondo e all'inizio dei file **add.php**, **controller.php**, **editor.php**.
Aggiungere una gestione generalizzata per il salvataggio nel database in **actions.php**.

**Comment by Dasc3er** [comment]
1. Come possiamo prevedere la possibilità di rendere visibili o meno i campi all'interno dei diversi file?
Campo "Esempio", vogliamo mostrarlo in **add** e **editor**.
Campo "Esempio2", vogliamo mostrarlo solo in **editor**.
In ogni caso i campi vengono mostrati nell'**editor**, ma sarebbe utile prevedere un'impostazione per mostrarli o meno in **add** (tipo un campo boolean apposito)?

2. Quale sarebbe l'utilità di avere un campo personalizzato nel **controller**?
Per la concezione dei campi personalizzati, sono relativi ai singoli record: quando dovrebbero essere utili per il **controller**?

3. Potrebbe essere utile estendere i campi personalizzati anche ai plugin?

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager Mi sembra che la gestione dei campi personalizzati sia stata completata...
Mancava qualche funzionalità da aggiungere oppure erano presenti delle migliorie da effettuare (tipo la creazione di un modulo per la relativa gestione)?

**Comment by loviuz** [comment]
Per ora li terrei così per la 2.4, per la loro gestione tramite modulo possiamo farlo nella 2.4.1 eventualmente, giusto per non tardare troppo nel rilascio della 2.4, volevamo anticiparlo dato che la gestione delle email è super ora!

**Comment by Dasc3er** [comment]
Chiedevo appunto per chiudere alcune issue ormai in chiusura e separarle da quelle ancora da concludere 😄
