### ISSUE TITLE
elenco Stato preventivo

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1240]
## Comportamento richiesto

Nel **preventivo**, per logica di processo e per ridurre errori, sarebbe comodo avere **l'elenco degli stati in ordine per descrizione**, e non per idstato come ora.

e permettere di modificare e **numerare a piacimento la descrizione** secondo le proprie necessità.

![Stati preventivi](https://user-images.githubusercontent.com/75281007/224721896-44e0f1e8-be5d-4ba5-a776-8763f5883a0c.png)

________
inoltre la possibilità di **avere le voci del colore impostato**, come già avviene per le attività

<img width="393" alt="Screenshot 2023-03-13 alle 15 07 10" src="https://user-images.githubusercontent.com/75281007/224726331-dd9d659d-fac5-4a4e-ac5d-e52f60b8b476.png">

![Screenshot 2023-03-13 alle 15 07 29](https://user-images.githubusercontent.com/75281007/224726361-1df0d9b2-b747-4f60-9bf7-f35b14fcc4a1.png)

**Comment by sajotrei** [comment]
provando a modificare /modules/preventivi/**edit.php** alla riga 118

{[ "type": "select", "label": "<?php echo tr('Stato'); ?>", "name": "idstato", "required": 1, "values": "query=SELECT id, descrizione, colore AS _bgcolor_ FROM co_statipreventivi WHERE deleted_at IS NULL ORDER BY descrizione", "value": "$idstato$", "class": "unblockable" ]}

esce così 👍 
ma resta da capire se la modifica della descrizione influenza le logiche di collegamento tra i documenti.

<img width="495" alt="Screenshot 2023-03-13 alle 15 26 41" src="https://user-images.githubusercontent.com/75281007/224731458-e9f5bf63-5c75-4a26-bd00-e118421055c9.png">

**Comment by NicolaNext** [comment]
Riprendo questa richiesta perché stavo per proporne una molto simile e vorrei evitare doppioni.
Anche per noi sarebbe molto utile poter definire l'ordine degli stati (intervento, preventivo ecc.) ad oggi abbiamo modificato i nomi degli stati anteponendo un numero che ci permetta di ordinarli secondo necessità (in particolare parlo degli interventi).
La soluzione potrebbe essere di inserire nel database, nelle tabelle relative agli stati, una colonna "ordinamento" o simile in modo da decidere come ordinare gli elenchi senza modificare le descrizioni (correndo il rischio di creare malfunzionamenti).

**Comment by Pek5892** [comment]
Introdotto con commit https://github.com/devcode-it/openstamanager/commit/af2f79f8179463652678b1695708edea924e373b
