### ISSUE TITLE
Gestione Checklist

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1245]
## Comportamento richiesto

gli Utenti del gruppo: **Amministratori**, dovrebbero **sempre poter modificare e eliminare** l'assegnazione della Checklist
ES. se una Checklist viene assegnata a un tecnico, per gli amministratori non è più modificarla.

___________________

nella finestra Checklist sarebbe utile mettere un **button salva**, attualmente è necessario cliccare su plugin tornare sul documento e cliccare salva.

![Screenshot 2023-03-14 alle 19 32 40](https://user-images.githubusercontent.com/75281007/225105576-07f60bb3-3ea1-43ba-99bd-3a1ae70b4bc4.png)

___________________

quando apriamo un documento, non si sa se è presente una o più Checklist, per saperlo si è obbligati a entrare nella sessione Checklist.
sarebbe utile e pratico avere un **avviso** simile a quello delle note interne.

![Screenshot 2023-03-14 alle 19 34 25](https://user-images.githubusercontent.com/75281007/225105780-13dafa48-9143-46ff-ac0a-f0b6a974c379.png)

___________________
* Modulo:
* Versione del progetto: 2.4.42
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei, con questo commit è ora possibile modificare le checklist assegnate accedendo con account amministratore. E' inoltre possibile visualizzare un badge con il numero di check ancora da spuntare. https://github.com/devcode-it/openstamanager/commit/dd865a2347f79f4a197da8041428a64dcc20a096
