### ISSUE TITLE
Calcolo Liquidazione IVA errati

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1247]
## Comportamento richiesto

https://forum.openstamanager.com/d/2606-problemi-calcolo-liquidazione-iva-dopo-agg-22442

**Comment by Pek5892** [comment]
Buongiorno @sajotrei ,
già trattato in https://github.com/devcode-it/openstamanager/issues/1200, non riusciamo a verificare il problema senza degli esempi di importi non corretti

**Comment by Pek5892** [comment]
Buongiorno @sajotrei,
per la risoluzione avremmo bisogno di poter confrontare dati reali, consigliamo l'apertura di un ticket in area clienti.
