### ISSUE TITLE
Pianificare backup

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1248]
## Comportamento richiesto

sarebbe molto comodo poter **schedulare/pianificare il backup** direttamente in **impostazioni** 

una cosa simile 

![Screenshot 2023-03-17 alle 11 05 26](https://user-images.githubusercontent.com/75281007/225884235-2d5387ed-e962-40a2-832a-a09ded95e643.png)
![Screenshot 2023-03-17 alle 11 47 19](https://user-images.githubusercontent.com/75281007/225884265-65d92be9-0d6f-4ac1-97f5-a77a88891cbd.png)

___________

adesso per modificare la schedulazione di bck è necessario intervenire direttamente sul DB
zz_tasks - Backup automatico

Vedi anche
**Backup parametrico #300**

**Comment by Pek5892** [comment]
Introdotto con l'aggiunta del modulo Gestione task
