### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#125]
Salve,
ho provato ad installare il vostro software, ma il mio hosting non consente l'utilizzo degli short tags di PHP (<? per l'apertura e ?> per la chiusura), ma supporta solo quelli standard (ovvero <?php per l'apertura e ?> per la chiusura). Potreste cambiarli e rilasciare una nuova versione del programma (anche in beta) con questi tag?
Grazie

**Comment by Dasc3er** [comment]
Ciao @maicol07, 
con la versione 2.3 (attualmente in sviluppo, ma di cui puoi utilizzare una beta in attesa del prossimo rilascio) gli _short tags_ PHP sono stati completamente sostituiti proprio per permettere una maggiore compatibilità con i diversi host...

**Comment by maicol07** [comment]
Ok, io infatti stavo cercando di installare l'ultima beta... sentirò con il mio hosting per trovare una soluzione.
Grazie mille intanto!

**Comment by Dasc3er** [comment]
@maicol07 Per maggiori informazioni ecco la documentazione ufficiale PHP: http://php.net/manual/it/language.basic-syntax.phptags.php
Per la precisione, l'unica differenza degli _short tags_ PHP è relativa al tag di **apertura** dello script, mentre quelli di chiusura sono equivalenti. Inoltre, per la maggior parte del progetto abbiamo iniziato ad utilizzare un sistema di formattazione automatica del codice, che gestisce in automatico la conformazione di questi tag (https://github.com/FriendsOfPHP/PHP-CS-Fixer).

Potresti indicare con maggiori informazioni il problema che hai riscontrato?

**Comment by maicol07** [comment]
In particolare, il problema è questo:
![screenshot-2018-1-24 500 internal server error](https://user-images.githubusercontent.com/9463142/35343753-af60e684-012b-11e8-9225-adc31be3aaab.png)
e nel file error_log c'è questo:
`PHP Warning: Module 'apcu' already loaded in Unknown on line 0`

**Comment by Dasc3er** [comment]
@maicol07 Il problema indicato dalla pagine **Internal Server Error** è solitamente causato da un errore di configurazione del file **.htaccess**, che in effetti era presente nelle versioni beta ed è stato risolto a dicembre (#82).
Prova ad aggiornare i contenuti del file **.htaccess** che trovi nella cartella principale con i seguenti: https://github.com/devcode-it/openstamanager/blob/master/.htaccess

**Comment by maicol07** [comment]
Non funziona...

**Comment by maicol07** [comment]
Risolto modificando l'htaccess!
