### ISSUE TITLE
Problemi calcolo Liquidazione IVA

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1261]
Come segnalato da altre persone nel forum dalla versione  2.4.41 si è presentato un problema nella stampa delle liquidazioni iva e registri iva
Dopo un attento esame mi sono accorto che il problema si verifica nelle fatture vendite e acquisti, quando si inseriscono più righe.
nel dettaglio liquidazione infatti appare solamente la prima. e quindi il calcolo iva è sbagliato. e tutte le stampa inerenti come stampa registro iva vendite e acquisti oppure stampa fatturato
Importando una fattura estera tramite xml, non genera questo problema, nemmeno nella controparte autofattura (ma in questo caso il rigo è solo 1 quindi non è attendibile)

**Comment by Pek5892** [comment]
Buongiorno,
non abbiamo riscontrato problemi collegati alla presenza di più righe nei documenti, potreste verificare i valori applicando questa fix: https://github.com/devcode-it/openstamanager/commit/7b8c67b443637ff1ff73d3e4ce6f9fdf37f40da9 ?

![image](https://user-images.githubusercontent.com/102604205/227908225-c00b84fe-e9e3-4c7a-956f-282f67f238d4.png)
![image](https://user-images.githubusercontent.com/102604205/227908667-fe9a7202-ee49-4ecf-986f-94cefd3d3a6d.png)

**Comment by leo-spa** [comment]
Vi inserisco alcune registrazioni che ho effettuato in questo modo riuscite a capire cosa non sta funzionando correttamente e se la patch che avete postato risolve il problema.
nella numero 5 inoltre se notate ho inserito un rigo inps in quanto se provate ad inserirlo con la sezione cassa previdenziale, il totale è errato per un centesimo

[Registro-IVA-vendite-errato.pdf](https://github.com/devcode-it/openstamanager/files/11078574/Registro-IVA-vendite-errato.pdf)
[fattura numero 1.pdf](https://github.com/devcode-it/openstamanager/files/11078578/fattura.numero.1.pdf)
[fattura numero 5.pdf](https://github.com/devcode-it/openstamanager/files/11078579/fattura.numero.5.pdf)

**Comment by leo-spa** [comment]
Vi inserisco alcune registrazioni che ho effettuato in questo modo riuscite a capire cosa non sta funzionando correttamente e se la patch che avete postato risolve il problema.
nella numero 5 inoltre se notate ho inserito un rigo inps in quanto se provate ad inserirlo con la sezione cassa previdenziale, il totale è errato per un centesimo

[Registro-IVA-vendite-errato.pdf](https://github.com/devcode-it/openstamanager/files/11078574/Registro-IVA-vendite-errato.pdf)
[fattura numero 1.pdf](https://github.com/devcode-it/openstamanager/files/11078578/fattura.numero.1.pdf)
[fattura numero 5.pdf](https://github.com/devcode-it/openstamanager/files/11078579/fattura.numero.5.pdf)

**Comment by Pek5892** [comment]
Buongiorno, la stampa da voi indicata è il Registro IVA, non la liquidazione IVA. Quindi la fix riportata non andrà a correggere questo problema.

**Comment by leo-spa** [comment]
il problema si presenta conseguentemente anche sulla liquidazione iva,
facendo un calcolo manuale in quanto nell'elenco che vi ho mandato non sono
comprese le autofatture avrei un totale di 323,33 come totale iva a debito,
la stampa iva mi da invece 331,54
Questo problema se controllate nel forum capita anche ad altri
https://forum.openstamanager.com/d/2606-problemi-calcolo-liquidazione-iva-dopo-agg-22442

Il giorno lun 27 mar 2023 alle ore 14:43 Valentina ***@***.***>
ha scritto:
