### ISSUE TITLE
Focus su casella di testo

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1264]
Quando si clicca sulla casella articolo dentro un preventivo

![image](https://user-images.githubusercontent.com/103928231/227144287-dde0c1f6-23c4-49b9-ab8a-a8f4ce19a7d6.png)

Bisogna ricliccare sulla casella di testo per poter iniziare a scrivere

![image](https://user-images.githubusercontent.com/103928231/227144556-f0a9dc8e-31a8-4df4-8409-e0f57db0cd03.png)

un'altra cosa che avevo già segnalato è che se non si ricorda il codice articolo non è possibile ritrovare l'articolo.
Suggerirei di implementare la ricerca anche alla descrizione cosi da riuscire a trovarlo o di filtrare ed elencare le categorie e sottocategorie.

Modulo: Preventivi
Versione: 2.4.42
Tipo server: Maria db

**Comment by lucasalva87** [comment]
@bulleITA ricordo che quando si apre un issue, come ricordato anche dal template proposto, vanno sempre specificati:

![immagine](https://user-images.githubusercontent.com/30728163/227155782-befff234-5b1c-4654-8f9a-9ea05d57be4c.png)

inoltre chiediamo di tenere separati gli issue di segnalanazioni bug da quelli che riportano suggerimenti.

grazie per la collaborazione.

**Comment by sajotrei** [comment]
@bulleITA 
Ho verificato, e non sembra esserci il problema nella 2.4.42
questo aspetto si era presentato diversi mesi fa ma poi era stato risolto.

ho verificato anche **la ricerca per testo** oltre che per codice e funzionano entrambi.

<img width="1040" alt="Screenshot 2023-03-23 alle 12 18 19" src="https://user-images.githubusercontent.com/75281007/227188190-0d09198f-aa2f-48a9-b666-3d158a460751.png">
