### ISSUE TITLE
FATTURE VENDITA - errore dopo aggiornamento ad ultimo commit

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#127]
Dopo aggiornamento all'ultimo commit, nella visualizzazione di una vecchia fattura o nell'inserimento di una riga generica in una nuova fattura viene visualizzato il seguente errore

![immagine](https://user-images.githubusercontent.com/34765237/35432466-760e51a4-0280-11e8-9824-aa2538a9a59e.png)

**Comment by Dasc3er** [comment]
Ciao @antonioscarpino,
potresti provare ad aggiungere la seguente riga all'inizio del file **actions.php** del modulo Fatture?
```php
include_once $docroot.'/modules/ordini/modutil.php';
```

**Comment by antonioscarpino** [comment]
Ok con questo fix sembra funzionare tutto.
Testo meglio e do conferma.

**Comment by Dasc3er** [comment]
Ho creato un commit che dovrebbe sistemare il problema (7b8876d54af02e3c69daeeabc56b3e0a27bf6eff).

**Comment by antonioscarpino** [comment]
Confermo sia la visualizzazione delle vecchie fatture che la creazione di nuove fatture adesso sembrano funzionare correttamente

**Comment by antonioscarpino** [comment]
Per quanto riguarga la riga generica tutto ok.
Inserendo una descrizione viene visualizzato il seguente errore
![immagine](https://user-images.githubusercontent.com/34765237/35435909-bab5878a-028c-11e8-890f-a0ba62384751.png)
