### ISSUE TITLE
Eventi festività - ricorrente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1274]
## Comportamento richiesto

se si imposta una festività in Strumenti>Tabelle>Eventi e si attiva la voce Ricorrente, ci si aspetta che ripeta quell'evento ogni anno

attualmente **ti obbliga a aggiornare la data per visualizzare l'evento in dashboard**.

![1](https://user-images.githubusercontent.com/75281007/228213844-402ba9a9-a173-4388-ab06-b8c5e2649d39.png)

![2](https://user-images.githubusercontent.com/75281007/228214435-ea892762-4481-48ca-beb9-e5668379c2ab.png)
![3](https://user-images.githubusercontent.com/75281007/228214437-9a7d8aa9-c335-4f59-a7aa-753eef8ef3ff.png)

* Modulo:
* Versione del progetto: 2.4.42
* Versione PHP:
* Tipo di server:

**Comment by lucasalva87** [comment]
Questa la fix temporanea: https://github.com/devcode-it/openstamanager/commit/74382685d33d22e0d30028caa9715c6218d5cbc4#diff-98f521e34835e5591c0283fac2c9d4c0c50680ebe239f0b22ccbb82dfbfcf668

considerà che però stiamo rivedendo la funzionalità per la 2.4.43.
