### ISSUE TITLE
Attività ( richiesta e descrizione affiancati )

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1277]
## Comportamento richiesto

quando **si crea una nuova attività**, può essere utile avere a disposizione anche **il campo descrizione**, torna utile soprattutto quando si crea una attività già eseguita che non era pianificata.

inoltre sia in fase di creazione che nell'attività riteniamo sia utile avere i due campi **Richiesta e Descrizione _affiancati_**
così si ottimizza la schermata 

![Screenshot 2023-03-30 alle 17 14 18](https://user-images.githubusercontent.com/75281007/228884161-34b2daff-0ed6-43c5-b58c-42c21e126bc7.png)
![Screenshot 2023-03-30 alle 17 14 56](https://user-images.githubusercontent.com/75281007/228884168-d1044809-9d15-43c3-b51e-9c33654183d8.png)

**Comment by Pek5892** [comment]
In release nella versione 2.4.43

**Comment by sajotrei** [comment]
nell'attività riteniamo sia utile avere i due campi **Richiesta e Descrizione _affiancati_**
così si ottimizza la schermata

/osm/modules/interventi/**edit.php**

![Screenshot 2023-03-31 alle 14 45 11](https://user-images.githubusercontent.com/75281007/229123491-3e591913-e4bd-4ae2-bf63-b110ddc4d74a.png)

**Comment by Pek5892** [comment]
Introdotto con commit: https://github.com/devcode-it/openstamanager/commit/3ec45f24b35737d3d7eb5419e134fbdcf8492d4d
