### ISSUE TITLE
Sistema per l'aggiornamento del database con la versione in sviluppo

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#128]
Aggionando all'ultimo commit inserendo un descrizione (no un riga generica) viene visualizzato il seguente errore
![immagine](https://user-images.githubusercontent.com/34765237/35436044-3926b9b8-028d-11e8-9d7e-e2356a0d32b6.png)

**Comment by Dasc3er** [comment]
Il problema è relativo al fatto che sono state effettuate delle modifiche a livello di database, e non esiste al momento una procedura per aggiornare automaticamente il database di conseguenza se si sta utilizzando la versione in sviluppo.
L'unico sistema per risolvere questo malfunzionamento è controllare le modifiche al database e replicarle manualmente.

**Comment by antonioscarpino** [comment]
Ok.
Però a mio avviso inserire nella master (che si dovrebbe considerare una relese funzionante per il testing del gestionale) degli aggiornamenti non ancora conclusi nello sviluppo non è la soluzione ideale.
Sarebbe meglio rilasciare una miglioria quando anche tutte le eventuali dipendenze sono state aggiornate.
Personale pensiero non è una polemica :)

**Comment by Dasc3er** [comment]
@antonioscarpino La versione master è la versione in sviluppo. Il suo utilizzo in ambienti non destinati a test è sconsigliato.

Attualmente il procedimento di sviluppo è piuttosto lungo e complesso, e sarebbe decisamente improponibile attendere di avere una versione corretta e completa prima di effettuare un commit, poiché la repository ha proprio l'obiettivo di rendere più agevole e distribuito lo sviluppo del software.

Chiunque utilizzi la versione in sviluppo dovrebbe controllare i contenuti e gli obiettivi dei singoli commit, quantomeno nella descrizione, poiché di fatto la repository non è utilizzata esclusivamente per risolvere bug e malfunzionamenti (come in precedenza era SourceForge).

**Comment by antonioscarpino** [comment]
@Dasc3er condivido ogni tuo pensiero.
Infatti, non mi sognerei mai di utilizzare la versione master in altri ambiti se non quello del testing.
La mia, era solo una considerazione personale sul fatto che rilasciare un aggiornamento, ancora non completamente sviluppato e quindi probabile causa di errori, forse non sia il massimo.
Comunque ripeto, quello che ho scritto, non era una polemeica o un mettere in discussione il vostro lavoro, che è stato ed è sempre celere e preciso.

**Comment by loviuz** [comment]
Il problema non è che manchino dei pezzi nel repository, è che le query da eseguire sono in update/2.3.sql, e per sapere se dev'essere aggiornato il db bisognerebbe fare un diff di quel file locale con quello dell'ultimo commit.
Di solito i file sono sempre aggiornati e completi :-)

**Comment by antonioscarpino** [comment]
@loviuz scusami ma non ho capito.
Io solitamente quando aggiorno all'ultimo commit faccio prima di tutto un backup della vecchia versione, poi un "git pull" della master, un "yarn run develop-OSM" per aggiornare tutte le dipendenze.
A questo punto, cancello il vecchio db ed eseguo un'installazione pulita di tutto il gestionale per evitare l'incorrere in errori solo aggiornando.
Nell'eseguire l'installazione pulita il db viene aggiornato dalla versione 2.0 alla 2.3 (ultimo commit spero).
Quindi non riesco a capire quale possa essere la differenza del mio db locale e quello dell'ultimo commit se l'installazione è fatta da zero e i file sono sempre aggiornati e completi.
Scusa la domanda ma è per capire ed imparare qualcosa che sicuramente ignoro.

**Comment by loviuz** [comment]
ah ok, quindi fai sempre un'installazione da zero. in questo caso il database che installi dovrebbe essere completo...! fammi verificare, ma ho installato anch'io l'ultima versione da git, ramo master, non avevo riscontrato il problema, pensavo usassi solo i file aggiornati.

comunque quello che fai è corretto, così sei sicuro di avere anche il database sempre all'ultima versione

**Comment by lepool** [comment]
Premetto: Ho installato attraverso git l'attuale versione OSM. Ho gia un utente mysql presente , database presente , file config **non** presente e mi compare la maschera di prima configurazione. 
Ora se configurando tutto, il test mi dice **privilegi insufficenti**  .
Se però metto nel file config.inc i dati di accesso al database a mano, la procedura di installazione va a buon fine.
La query del test di configurazione ha dato la seguente risposta:

+-----------------------------------------------------------------------------------+
| Grants for assistenza@localhost                                                   |
+-----------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'assistenza'@'localhost' IDENTIFIED BY PASSWORD <secret>    |
| GRANT ALL PRIVILEGES ON `osmtemp`.* TO 'assistenza'@'localhost' WITH GRANT OPTION |
| GRANT ALL PRIVILEGES ON `osmtest`.* TO 'assistenza'@'localhost' WITH GRANT OPTION |
| GRANT ALL PRIVILEGES ON `assistenza`.* TO 'assistenza'@'localhost'                |
+-----------------------------------------------------------------------------------+
4 rows in set (0,00 sec)

**Comment by antonioscarpino** [comment]
Stessa cosa succede a me

**Comment by Dasc3er** [comment]
Il problema sulla procedura di test del database dovrebbe essere stato risolto con il commit ef36f98f8e350251f6d5480cb54a69a9549c2328.
In pratica, si verificava quando il primo risultato non era rilevante per il controllo sui permessi (per esempio _GRANT USAGE..._).

Comunque, l'errore iniziale segnalato in questa issue è strano, soprattutto in un'installazione da zero...
