### ISSUE TITLE
liquidazione iva trimestrale manca calcolo 1%

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1281]
Data la velocità di risoluzione dei problemi alle stampe, vorrei chiedere se fosse possibile nelle liquidazioni iva trimestrali, correggere il mancato calcolo della maggiorazione dell'1% attualmente non calcolato dal programma. obbligatorio per chi paga l'iva trimestrale

IVA A DEBITO 126,92 €
MAGGIORAZIONE 1,00% 1,27 €
IVA A DEBITO CON MAGGIORAZIONE 128,19 €
IMPORTO DA VERSARE 128,19 €

grazie

**Comment by sajotrei** [comment]
esiste già qualcosa in merito

**Maggiorazione 1% stampe liquidazione iva #955**
https://forum.openstamanager.com/d/2330-interessi-liquidazione-iva

**Comment by leo-spa** [comment]
lo avevo già segnalato anch'io, tempo fa nel forum, ma considerando che saranno 3 righe di codice in più da inserire, e vista la diponibilità di @Valentina speravo che questa volta venisse effetuato l'aggiornamento, La risposta data il 1° agosto non mi sembra corretta, giustamente le stampe vanno sempre controllate, ci siamo accorti infatti di un problema che è stato prontamente risolto, permettere un calcolo automatico per chi stampa l'iva trimestrale non vuole dire che la stampa è usata per fini fiscali, ma agevolare quelle persone che versano l'iva trimestrale e hanno la necessità di avere il calcolo dell'1% sul totale. Come ripeto son 3 righe di codice a di tanto. 
Iva a debito *1/100 = Maggiorazione 
Iva a debito + Maggiorazione = IVA A DEBITO CON MAGGIORAZIONE
IVA A DEBITO SENZA Maggiorazione o (se presente)  IVA DEBITO CON MAGGIORAZIONE = IMPORTO DA VERSARE

**Comment by lucasalva87** [comment]
Fix https://github.com/devcode-it/openstamanager/commit/8047ccda8f39b09eaea3f2abf156fcc66ec47d84

**Comment by sajotrei** [comment]
Abbiamo provato la fix e sembra valida in stampa
dobbiamo solo fare le verifiche della correttezza dei valori.

**Comment by leo-spa** [comment]
ho fatto un test di stampa registro iva 1° trimestre ed il valore sembra corretto, occorre vedere i casi particolari, se l'arrotondamento è effettuato correttamente

**Comment by leo-spa** [comment]
con la modifica appare selezionando l'iva trimestrale il calcolo del'interesse dell1%
questa formula va benissimo per le stampe iva trimestrali primo secondo terzo e quatro trimestre

se però si stampano le liquidazioni mensili, anche se la scelta è iva trimestrale, il calcolo dell'iva dell1% non va effettuato in quanto non è mai previsto l'interesse dell1% per stampe iva mensili e quindi per una stampa registro iva mensile anche se si è in regime trimestrale non andrebbe calcolato l'1%
infatti nell'elenco appaiono sia i trimestri che le stampe mensili.

io proporrei come soluzione di rendere visibile solo la stampe mensili per iva ordinaria, solo le stampe trimestrali per iva trimestrale. Oppure, lggermente più impegnativo, sistemare il modulo di stampa e sia che il regime fiscale sia ordinario che trimestrale fare in modo che le stampe vengano gestite correttamente in base alla scelta della stampa, mensile o trimestrale

al contrario nell'opzione manuale (regime trimestrale) se seleziono periodo 01/01 - 31/12  è corretto il calcolo dell1% in quanto potrebbe essere una stampa di controllo simile al calcolo iva annuale.

**Comment by Pek5892** [comment]
Buongiorno @leo-spa, abbiamo aggiunto un controllo sulla selezione del periodo in base al tipo di liquidazione da impostazioni: https://github.com/devcode-it/openstamanager/commit/00f69a483e755766ad2fec4e2d425988c382add6

**Comment by leo-spa** [comment]
Modifica perfetta e funzionante, manca un'ultima miglioria, più che altro una sottigliezza.
nelle liquidazioni iva mensili andrebbe riportato l'importo 
IVA A DEBITO 126,92 €
nel rigo
IMPORTO DA VERSARE 126,92 €

non mi è ancora capitato un importo inferiore a 25,82 o a credito

se l'iva a debito, è inferiore a 25,82  va riportata  come aggiunta del debito nel mese o trimestre successivo 
se l'importo è a credito andrebbe riportato in un rigo
IVA A CREDITO  
e nel mese o trimestre successivo
andrebbe inserito l'importo nel rigo
VARIAZIONE DI IMPOSTA RELATIVE A PERIODI PRECEDENTI

grazie per tutte le modifiche e migliorie che state attuando per rendere il programma sempre più efficiente

**Comment by Pek5892** [comment]
Buongiorno @leo-spa, 
grazie per i consigli :smile:  potrebbe verificare se con la seguente modifica il problema viene risolto: https://github.com/devcode-it/openstamanager/commit/2da52a630bd381825f2146b21eeddc4a163a0011?

**Comment by leo-spa** [comment]
Ho aggiunto sue immagini, la modifica applicata non è corretta, e non va assolutamente applicata o utilizzata, l'unico problema è relativo al calcolo dell1% nel mese in cui l'iva è inferiore a 25,82 e quindi non va pagata ma portata a debito o credito nel mese successivo come già il modulo fa correttamente.
Forse mi ero spiegato male nel messaggio precedente
nelle due immagini si vede come nel trimestre n risulta un'iva a debito sotto i 25,82 esattamente 6,13 e viene applicato un interesse dell1% (che non andrebbe applicato)
nel trimestre n+1 viene aggiunto al debito iva correttamente l'importo di 6,13 nella voce debito periodo precedente.
Quindi ripeto la patch di cui sopra non va assolutamente applicata in quanto errata, ma va solo corretto l'errore del calcolo iva per importi inferiore a 25,82

![Screenshot_20230411_181451](https://user-images.githubusercontent.com/60449835/231228555-9e07a0a6-19f6-402f-89a9-f3509326dabc.png)
![Screenshot_20230411_182737](https://user-images.githubusercontent.com/60449835/231228561-fef5c144-6996-4e46-8824-298978f6333b.png)

**Comment by Pek5892** [comment]
Buongiorno, il totale iva inferiore a 25.82 dovrebbe ora essere correttamente gestito: https://github.com/devcode-it/openstamanager/commit/dad780faaddbfae737221579e8079d93a47b64ae

**Comment by leo-spa** [comment]
ho fatto delle prove effettuando la variazione riportata ci siamo quasi ma ancora qualcosa non è corretto
ho allegato 3 trimestri.
Il primo 897,91-169,97=727,94  maggiorazione 7,28  ; iva a debito con maggiorazione 735,22  - totale da pagare 735,22
L'unica voce che non dovrebbe apparire è totale iva detraibile che ha lo stesso valore del totale iva su acquisti detraibili

Il secondo 39,21-33,08=6,13  maggiorazione 0,06
in questo caso essendo iva sotto i 25,82 non dobrebbe aparire la maggiorazione, ma la stampa è corretta non appare il totale da pagare

Il terzo 61,42-32,52=28,90+6,13=35,03   maggiorazione 0,35 ; iva a debito con maggiorazione 35,65 - totale da pagare 35,05
in questo caso il riporto del mese precedente non viene sommato all'iva e quindi il totale da pagare è errato


![liq1](https://user-images.githubusercontent.com/60449835/231562222-a26aee1e-4729-4fe7-9755-56cd77f2ae72.png)
![liq2](https://user-images.githubusercontent.com/60449835/231562234-d0351869-856e-43ce-8692-2ef14a72f865.png)
![liq3](https://user-images.githubusercontent.com/60449835/231562242-20925c9f-f5f4-4736-b660-35c435abdb62.png)

    <td>VARIAZIONE DI IMPOSTA RELATIVE A PERIODI PRECEDENTI</td>';
        if ($totale_iva_periodo_precedente < '25.82' && $totale_iva_periodo_precedente > '0') {
            echo'
            <td class=text-right>'.moneyFormat(abs($totale_iva_periodo_precedente), 2).'</td>';
        } else {
            echo'
            <td class=text-right></td>';
        } 
    echo'
    </tr>
    <tr>
        <td>DI CUI INTERESSI PER RAVVEDIMENTO</td>
        <td class=text-right></td>
    </tr>
    <tr>
        <td>DI CUI INTERESSI PER MAGGIORAZIONE TRIMESTRALI</td>
        <td class=text-right></td>
    </tr>
    <tr>
        <td>CREDITO IVA COMPENSABILE</td>
        <td class=text-right></td>
    </tr>
    <tr>';
        if ($totale_iva >= 0) {
            echo ' <td>IVA A DEBITO</td>';
        } else {
            echo ' <td>IVA A CREDITO</td>';
        }
        echo ' <td class=text-right>'.moneyFormat(abs($totale_iva), 2).'</td>
    </tr>
    <tr>
        <td>CREDITO SPECIALE DI IMPOSTA</td>
        <td class=text-right></td>
    </tr>
    <tr>
        <td>MAGGIORAZIONE 1,00%</td>
  <td class=text-right>'.($periodo['valore'] == 'Trimestrale' ? moneyFormat($maggiorazione, 2) : '').'</td>
    </tr>
    <tr>
  <td>IVA A DEBITO CON MAGGIORAZIONE</td>';
        if ($totale_iva > '25.82' && $periodo['valore'] == 'Trimestrale') {
            echo'
            <td class=text-right>'.moneyFormat($totale_iva_maggiorata, 2).'</td>';
        } else {
            echo'
            <td class=text-right></td>';
        } 
    echo'
    </tr>
    <tr>
  <td>IMPORTO DA VERSARE</td>';
        if ($totale_iva > 25.82) {
            echo'
            <td class=text-right>'.($periodo['valore'] == 'Mensile' ? moneyFormat($totale_iva, 2) : moneyFormat($totale_iva_maggiorata, 2)).'</td>';
        } else {
            echo'
            <td class=text-right></td>';
        } 
    echo'

**Comment by Pek5892** [comment]
L'importo da versare quindi non riporta la maggiorazione in caso siano presenti variazioni relative a periodi precedenti?
https://github.com/devcode-it/openstamanager/commit/0f1cf8bc2ad15067621cc5db74ba5e15a50b00ed

**Comment by leo-spa** [comment]
si infatti è così se vede nelle immagini ho riportato trimestre (n) trimestre (n+1) e trimestre (n+2)
il primo trimestre è corretto
il secondo riporta la maggiorazione che non dovrebbe essere presente
nel terzo non viene sommata la variazione del mese precedente (n+1) al totale iva del trimestre (n+2)

e c'e' quella voce doppia errata totale iva detraibile  che non si capisce l'utilità

**Comment by leo-spa** [comment]
ci siamo quasi due mini correzioni, rimane il calcolo iva dell1% quando l'importo è sotto la soglia di pagamento
e il totale da versare deve essere uguale all'importo iva a debito con maggiorazione
i calcoli sono giusti


![liq1](https://user-images.githubusercontent.com/60449835/231771898-947cc087-5d4d-47e1-9787-ad6d3c7bed11.png)
![liq2](https://user-images.githubusercontent.com/60449835/231771910-82b49393-0835-4e3d-9ff0-935a270bb574.png)

**Comment by Pek5892** [comment]
![immagine](https://user-images.githubusercontent.com/102604205/231802245-734fe6d7-76bc-4a17-9c25-c2827dd6e97d.png)
Corretto l'importo da versare: https://github.com/devcode-it/openstamanager/issues/1281

**Comment by leo-spa** [comment]
Ho provato tutte e tre le stampe e ora quadra tutto. grazie mille per le modifiche

**Comment by Pek5892** [comment]
:smile: Grazie a lei per il supporto!
