### ISSUE TITLE
problemi smtp account email

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1284]
errore nelle configurazioni smtp sia tramite google che tramite microsoft.
a Seguire il messaggio di errore:

    Modulo: account email
    Versione del progetto: Versione: 2.4.43 (Rc95b8fd39)
    Versione PHP: PHP (7.4.30 )
    Tipo di server: server smtp

Si è verificato un'errore [uid: 1c59d37]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception GuzzleHttp\Exception\RequestException: "Error creating resource: [message] stream_context_create() has been disabled for security reasons [file] /var/www/clients/client92/web5527/web/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 318" at /var/www/clients/client92/web5527/web/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php line 52
Si è verificato un'errore [uid: 1c59d37]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Error creating resource: [message] stream_context_create() has been disabled for security reasons [file] /var/www/clients/client92/web5527/web/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 318

**Comment by lucasalva87** [comment]
Ciao quando apri issues per malfunzionamenti o presunti tali ti ricordo Inserire le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

Grazie.

**Comment by leo-spa** [comment]
Ho aggiornato nel primo  di aperturai dati richiesti, comunque non ha mai funzionato il servizio smtp nemmeno configurando la pec, prendendo i dati direttamente da un client offline configurato e perfettamente funzionante.
Per questo ho aperto il post perchè non capisco se c'e' qualcosa che non va in un file di OpenSTAManager oppure se c'e' qualcosa che non va nella configurazione del mio domino

**Comment by Pek5892** [comment]
Buongiorno @leo-spa, le confermo che il modulo per la gestione delle email è funzionante e attualmente utilizzato. Potrebbe provare a controllare nuovamente la configurazione seguendo la guida e configurando l'OAuth2?
https://docs.openstamanager.com/v/2.4.47/openstamanager/modules/email/account#gmail

**Comment by Pek5892** [comment]
Ciao @leo-spa, potresti provare a modificare un impostazione del server web aggiungendo al file php.ini 
allow_url_fopen = on
?

**Comment by leo-spa** [comment]
Scusa se sono un po' assente ma sono incasinatissimo con il lavoro questa
sera provo a fare la modifica che hai suggerito e ti faccio sapere

Il gio 22 giu 2023, 11:19 Valentina ***@***.***> ha scritto:

**Comment by leo-spa** [comment]
Ciao @Pek5892, mi confermi che il file php.ini che evo cambiare è quello nella directory principale perchè mi risulta vuoto
devo quindi solo aggiungere la riga
allow_url_fopen = on

**Comment by Pek5892** [comment]
Ciao @leo-spa, non sappiamo indicarti con esattezza dove questo file sia collocato sul tuo server, non essendo un'impostazione del gestionale ma del server dovresti chiedere al tuo sistemista per una maggiore conferma
