### ISSUE TITLE
Vari problemi di funzionalità dei DDT

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1288]
Utilizzando i moduli DDT ho riscontrato vari problemi di funzionamento:

**1 - Aggiornamento delle quantità:**
- Inserisco un DDT in ingresso n. 1234 con articolo XXX quantità 3.
- Inserisco un DDT in uscita n. 5678 (reso materiale) e richiamo il DDT n. 1234. Seleziono l'articolo XXX relativo e assegno quantità 2 (quantità restituita).
- Richiamando il DDT n. 1234 mi aspetto che la quantità evasa nel n. 5678 sia 1, invece questo non accade

**2 - Aggiornamento dei riferimenti:**
Se nel precedente DDT in uscita n. 5678 avevo indicato un riferimento al DDT n. 1234 (entrata), eliminando  il n. 1234, il riferimento resta e non posso più modificarlo ne' eliminarlo

![Screenshot](https://user-images.githubusercontent.com/40104356/230548704-e087c839-f740-4392-9a6e-ac85f982592c.png)

**3 - Articoli con quantità 0:**
Se a uno degli articoli del DDT assegno quantità 0, il processo di aggiornamento si blocca

![Screenshot(1)](https://user-images.githubusercontent.com/40104356/230549327-f66364b3-9815-4036-b8f1-b0ffcc5aee38.png)

salvando o aggiornando la pagina, tutti gli articoli spariscono

![Screenshot(2)](https://user-images.githubusercontent.com/40104356/230549519-ec73c76a-f96f-4a59-a222-82bf1c4efb32.png)

* Modulo: DDT ingresso - DDT uscita
* Versione del progetto: 2.4.43

**Comment by Pek5892** [comment]
1 - Aggiornamento delle quantità:
Una gestione dei documenti in questo modo non sarebbe corretta, il documento di trasporto deve riportare sempre la quantità di merce trasportata in quella consegna, a prescindere da eventuali resi o aggiunte successive.

2 - Aggiornamento dei riferimenti:
Il problema è stato risolto nella versione 2.4.52
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/3364fd63-be6f-4ff2-ba25-05250631e802)

3 - Articoli con quantità 0:
Il problema è stato risolto nella versione 2.4.52
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/ab174da9-7e15-40e4-bcd6-bfca649f4b3c)
