### ISSUE TITLE
Data fatturazione

### ISSUE THREAD

**Issue by AndreasNogler** [devcode-it/openstamanager#129]
Ho notato che nella versione 2.3 beta 2 la scadenza è sempre impostata su data fatturazione (strumenti->tabelle->pagamenti). Sulle scadenze con d.f.f.m. dovrebbe essere impostato data fatturazione fine mese.

Grazie

**Comment by lepool** [comment]
Ho provato ora, nella versione master mi prende l'impostazione predefinita (impostazioni->fatturazione->Tipo di pagamento predefinito)
Tu cosa hai impostato in quell'impostazione?

**Comment by AndreasNogler** [comment]
Penso che mi sono spiegato male. Se vai a modificare i pagamenti è sempre pre impostato data fattura invece data fattura fine mese sulle scadenze con d.f.f.m

**Comment by Dasc3er** [comment]
@AndreasNogler Potrebbe trattarsi di un bug nel modulo Pagamenti.

**Comment by lepool** [comment]
Nel scadenzario sotto data emissione indica "fattura .... numero x" invece della data emmissione.
![grafik](https://user-images.githubusercontent.com/32035706/35459414-5cbe1882-02e0-11e8-8bfd-c0160d39e711.png)

**Comment by AndreasNogler** [comment]
<img width="1532" alt="bildschirmfoto 2018-01-26 um 21 32 23" src="https://user-images.githubusercontent.com/2395217/35459495-b4dce142-02e0-11e8-8920-21a56eb0466d.png">

**Comment by lepool** [comment]
Da me in pagamenti indica una scadenza sbagliata. Stranamente nello scadenzario  indica correttamente la scadenza.
