### ISSUE TITLE
avviso presenza allegati in elenco doc

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1295]
## Comportamento richiesto

**in elenco dei vari documenti** ( preventivi, contratti, attività, fatt. ecc.. ) riteniamo possa essere **utile una sorta di avviso della presenza di allegati** "extra" che non siano quelli standard ( xml, ricevuta, ecc.. )

esempio, in **elenco** preventivi, si vede un **avviso del numero allegati** ( simile a quello che segnala la presenza di note in plugin )
ma segnala/evidenzia solo gli allegati extra

![225105780-13dafa48-9143-46ff-ac0a-f0b6a974c379](https://user-images.githubusercontent.com/75281007/233607941-df20fe15-cae8-47af-a5e4-594bcaa54348.png)

**Comment by Pek5892** [comment]
Colonna allegati presente in Attività

**Comment by sajotrei** [comment]
mi sono accorto ora che ho formulato male la richiesta.
non in elenco...

mi riferivo **la gestione degli allegati nel plugin nei rispettivi documenti**
quindi nei documenti dove è assente, aggiungerlo e poi abilitare un avviso simile a quello delle note interne
