### ISSUE TITLE
Posizione Avviso

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1299]
## Comportamento richiesto

quando si salva qualsiasi cosa nel programma abbiamo notato che spesso l'**avviso è posizionato in un punto che copre** la possibilità di procedere in particolare nel Plugin.

magari potrebbe aver senso **_spostare l'avviso in alto al centro_**.

![Screenshot 2023-04-28 alle 14 30 48](https://user-images.githubusercontent.com/75281007/236501987-66c4402c-70c7-43f9-9f85-fcfab50fd194.png)

![Screenshot 2023-05-05 alle 17 33 36](https://user-images.githubusercontent.com/75281007/236508329-2c82df7e-87ce-4f50-803c-cb2120cd5882.png)

![Screenshot 2023-05-05 alle 17 33 43](https://user-images.githubusercontent.com/75281007/236508337-cded517c-9fe2-44c5-9aa6-42df866171de.png)

**Comment by Pek5892** [comment]
Gli avvisi sono stati spostati in basso a destra dalla versione 2.4.52
