### ISSUE TITLE
App Chrome non compare

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1300]
Salve, da un installazione pulita non mi compare il popup dell'app chrome
![image](https://user-images.githubusercontent.com/103928231/236895140-e95bee2c-ad70-42f7-99eb-81615655d477.png)

Mentre su un altra installazione mi è sempre comparsa

entrambe le installazioni hanno:

* Versione del progetto: 2.4.43
* Versione PHP: 8.0.28
* Tipo di server: MariaDB

**Comment by lucasalva87** [comment]
Salve, riusciresti a verificare che i requisiti del punto #1 siano rispettati? [https://docs.openstamanager.com/v/2.4.44/guide/esempi/verificare-linstallazione-di-osm#1-verificare-che-i-requisiti-di-osm-siano-rispettati](Verifica requisiti)

**Comment by bulleITA** [comment]
Si, l'unica cosa è mariaDB 10.5.19, ma ripeto, entrambe le installazioni sono su medesimo server con medesimi requisiti.
Credo che il problema derivi da altro.
