### ISSUE TITLE
Inserimento articolo in documenti non tiene conto della quantità minima ordinabile

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1301]
## Comportamento attuale

Nella fase di inserimento di un articolo in un documento, non viene tenuta in considerazione la quantità minima ordinabile, dato che viene indicato nel plugin "Listini fornitore"

## Contesto

* Modulo: Articoli ->Plugin "Listino fornitori"
* Versione del progetto: 2.4.44

**Comment by Pek5892** [comment]
Ciao @idraulicadueci, abbiamo corretto con fix: https://github.com/devcode-it/openstamanager/commit/29f7a4298edc29672cb91d0b5e73ff3a1d2804b1.
L'unico documento dove questa modifica può essere introdotta sono gli ordini cliente, in quanto le fatture di acquisto e i ddt vengono ricevuti dal fornitore e vanno importati "così come sono".

**Comment by idraulicadueci** [comment]
@Pek5892 grazie
