### ISSUE TITLE
errore totale iva in registro iva vendite

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1302]
mi sono accorto dopo la presentazione iva periodica effettuata automaticamente da agenzia entrate, che la stampa il valore iva era errato di pochi centesimi.
Ho spulciato tutte le fatture e gli importi sono corretti, quello che è errato è il totale nel registro iva vendite
Come si evince dagli allegati viene calcolata un'imposta di 323,31 mentre dovrebbe essere di 323,33
questo problematica risolverebbe l'ultimo problema sulle stampe dei registri e le renderebbe conformi a quelle di agenzia entrate.
e quindi il medesimo valore errato viene riportato nella liquidazione iva.
allego la stampa così è più chiara la problematica per effettuare la modifica, grazie @Pek5892 
![Scan0001(1)](https://github.com/devcode-it/openstamanager/assets/60449835/9df8bfd2-4c4c-44e9-b40b-6c1fb0bac12d)
![Scan0001](https://github.com/devcode-it/openstamanager/assets/60449835/9d9db223-c218-47b5-b1b3-5b0076a74a7e)

**Comment by Pek5892** [comment]
Buongiorno @leo-spa, dovrebbe risolversi con questo commit: https://github.com/devcode-it/openstamanager/commit/0af69cb1840b8366da43618bd7d3ea608626095f :smile:

**Comment by leo-spa** [comment]
Sempre velocissima e precisa, mi spiace di non aver risposto prima, non si è sistemato il valore nella liquidazione iva, ho allegato l'immagine per mostrare il punto in cui si presenta l'errore
