### ISSUE TITLE
errore importi Comunicazione dati fatture (ex-spesometro)

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1303]
ho provato la stampa comunicazioni dati fatture e mi sono accorto che l'imponibile considera un valore errato
Ho inserito l'immagine di una fattura vendite e come si può vedere il campo corretto da riportare nella comunicazione dati fatture è totale imponibile, sul quale viene calcolata l'iva
attualmente il modulo considera la voce imponibile e calcola l'iva quindi gli importi risultano errati infatti dobrebbe riportare
imponibile 936,00
iva 205,92
totale 1.141,92
Grazie @Pek5892 

Lo stesso problema si riscontra nella stampa Dati economici - Stampa fatturato

![Screenshot_20230512_213726](https://github.com/devcode-it/openstamanager/assets/60449835/ebd9d4fc-d86b-47e9-a463-41354f4e9af3)
![Screenshot_20230512_213228](https://github.com/devcode-it/openstamanager/assets/60449835/8e67310a-e053-4fe3-9f67-60ca3c7c307f)
![Screenshot_20230512_215438](https://github.com/devcode-it/openstamanager/assets/60449835/83a1bada-6ca1-4213-a03d-2485ded629a3)

**Comment by loviuz** [comment]
ciao @leo-spa, in realtà questa stampa la volevamo rimuovere perché, se non ricordo male, la comunicazione dati spesometro ormai è elettronica. chiedo a te se avrebbe senso ancora mantenerla, perché sarebbe una stampa in più da tenere allineata con eventuali correzioni. grazie :-)

**Comment by leo-spa** [comment]
Lo spesometro è stato abolito nel 2019 con l''entrata in vigore della fattura elettronica, quindi in effetti non ha senso tenere in piedi una stampa che non si utilizza, e chi doveva inviarla ha la copia sul portale di agenzia entrate sezione ivaservizi

**Comment by Pek5892** [comment]
Stampa spesometro rimossa con fix: https://github.com/devcode-it/openstamanager/commit/01f1e20ac85d295051a138a9cc8cd0ad66ead640
