### ISSUE TITLE
Duplicazione righe vista scadenzario

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1304]
## Comportamento attuale

Inviando più email di sollecito, la voce di scadenzario compare tante volte quante sono le email inviate. Questo ovviamente falsa l'elenco delle voci in scadenzario e di conseguenza il credito, che viene moltiplicato.

## Contesto

* Modulo: Scadenzario
* Versione del progetto: 2.4.44

**Comment by Pek5892** [comment]
Buongiorno @idraulicadueci, il problema dovrebbe risolversi con: https://github.com/devcode-it/openstamanager/commit/67a2c5c83eb3c2ef1611a0a39b74f1f188d23cb6

**Comment by idraulicadueci** [comment]
Buongiorno @Pek5892, adesso è a posto. Grazie.
