### ISSUE TITLE
Utilizzo PIani di sconto

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [devcode-it/openstamanager#1305]
Buongiorno,
volevo una delucidazione sull'utilizzo del modulo piani di sconto.
come funziona?
ho provato ad inserire un piano 10+5 che poi vedo nell'anagrafica articolo.
come posso utilizzare questo piano di sconto all'interno di un documento di magazzino o ordine fornitore e impostare questo sconto all'interno del listino fornitore presente nell'anagrafica articolo?
grazie

**Comment by Pek5892** [comment]
Buongiorno @andreameneguzzoinfol, con la modifica della gestione delle righe introdotta dalla v.2.4.40 attualmente i piani di sconto/maggiorazione non sono gestiti.

**Comment by Pek5892** [comment]
La gestione dei piani di sconto è stata ripristinata con la versione 2.4.48 del gestionale.
