### ISSUE TITLE
riepilogo inserimento fatture e commenti per Valentina

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1306]
![Screenshot_20230516_174151](https://github.com/devcode-it/openstamanager/assets/60449835/ebe52e72-9b06-46b6-ad62-ba4593d4bd03)

Nella prima immagine l'inserimento di un rigo fattura
 è presente la cassa nazionale, la ritenuta d'acconto del 20%, il calcolo della ritenuta sull'imponibile, l'iva al 22% e il nostro imponibile di 822,12

![Screenshot_20230517_151303](https://github.com/devcode-it/openstamanager/assets/60449835/b642b89f-7e00-4244-9d8c-3dbb2b773f87)

Nella seconda immagine abbiamo i totali fattura, generati correttamente
in questo caso 822,12+62,04 che genera il nostro totale righe di 884,16
il programma calcola correttamente la cassa previdenziale di 35,37
il programma crea il totale imponible di 919,53
il programma calcola l'iva di 202,30
il programma crea il totale documento di 1121,83
il programma crea la ritenuta d'acconto sul totale righe 176,83
Il programma crea il totale documento di 945,00

Quindi la fattura è corretta e le modifiche apportate in precedenza danno come risultato che il programma ha effettuato gli arrotondamenti corretti al decimale superiore o inferiore in base alla terza cifra, se superiore o inferiore a 5.

![Screenshot_20230517_152705](https://github.com/devcode-it/openstamanager/assets/60449835/90be02ae-fc54-4be0-afc9-3211dfb2acba)

In questa immagine il registro iva vendite
anche in questo caso con le modifiche fino a ieri perfettamente corretto
la somma imponibile delle fatture da esattamente 1469,61
la somma imposta delle fatture da esattamente 323,33
L'imponibile e l'imposta non devono essere un calcolo totale colonna imponibile per il 22%, ma la somma dei singoli importi che compongono la colonna imponibile e la somma dei singoli importi che compongono la colonna imposta.

![Screenshot_20230517_154044](https://github.com/devcode-it/openstamanager/assets/60449835/b727d3c6-2b23-46c4-8a91-bdae7d805ea9)

![Screenshot_20230517_154121](https://github.com/devcode-it/openstamanager/assets/60449835/ababc784-0040-4242-9ee1-14d42b0ed680)

Nelle ultime due immagini la liquidazione iva, sempre in questo con le modifiche fino alla giornata di ieri, si può vedere come sia l'imponibile che l'imposta dell'iva siano errati rispetto al prospetto precedente, corretto.
Anche in questo caso con le modifiche precedenti sul calcolo iva trimestrale tutti i restanti valori sono corretti, in base ai dati forniti.

Spero di essere stato chiaro ed esaustivo @Pek5892

**Comment by Pek5892** [comment]
Buongiorno @leo-spa, potrebbe provare con l'applicazione del seguente commit: https://github.com/devcode-it/openstamanager/commit/a8f1bbc4428bcd8ca4fe3a24e2b3b8ab4b628c52 ?

**Comment by leo-spa** [comment]
@Pek5892 ho effettuato le modifiche ed ora le due stampe sono perfette.
--------
come ho commentato in questo post https://github.com/devcode-it/openstamanager/commit/fe8157196bea786edecca18bb9cc0738c08d0865
permane l'errore nella stampa fatturato, ho aggiunto una fattura nella versione demo  sul vostro sito e anche li la stampa non è corretta

**Comment by Pek5892** [comment]
Buongiorno @leo-spa,
la stampa fatturato dovrebbe correggersi con: https://github.com/devcode-it/openstamanager/commit/ab36baaabeba2803e1a13fa54d047267d30de774

![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/39a29c0f-f006-4d55-89ec-5a2c19870b28)

**Comment by leo-spa** [comment]
Ciao Valentina, ho visto che nella demo è perfettamente corretto, mentre
nella mia versione ci deve essere qualcosa che non va, visto che la
modifica apportata non fornisce nessuna variazione sugli importi, io
attendo il prossimo upgrade per caricare tutti i file modificati e vedo se
si sistema anche nella mia installazione

Il giorno lun 22 mag 2023 alle ore 11:53 Valentina ***@***.***>
ha scritto:

**Comment by leo-spa** [comment]
Ciao Valentina @Pek5892 , premetto che tutte le stampe sono perfette eccetto la stampa fatturato vendite, ma credo che sia solo un problema mio e non capisco come correggerlo.

Per esempio marzo 2023 dovrebbe essere: imponibile 287,84   iva 63,33  totale 343,87

io non capisco qual'e' il file corrotto che non permette la stampa corretta.

Le 3 fatture che compongono questa stampa sono così formate
imponibile 93,56  cassa p 3,74   totale imponibile 97,30   iva 21,41   totale 118,71    rit acc 18,71   totale  100,00
imponibile 88,88  cassa p 3,56   totale imponibile 92,44    iva 20,34   totale 112,78   rit acc 17,78   totale  95,00
                                                              imponibile 99,10    iva 21,58   totale 119,68    



Quando ho provato con la openstamanager demo, la stampa non era errata come nel mio caso.
Ho effettuato l'upload di tutti i file, selezionando sovrascrivi tutti.
Qualche consiglio per risolvere questa anomalia?

Versione: 2.4.46 (Rbbc7b16df)
PHP (7.4.30 )



 

![Screenshot_20230607_194225](https://github.com/devcode-it/openstamanager/assets/60449835/4126dbbb-52bd-4710-9345-d40cce18973c)

**Comment by Pek5892** [comment]
Buongiorno @leo-spa, potrebbe controllare l'importo della terza fattura? 
i valori ci risultano essere imponibile 99,10 iva **21,80** totale **120,90**
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/8e82353e-8515-46e1-bfcb-0c84e4ad958f)

**Comment by leo-spa** [comment]
Ciao Valentina ho dimenticato di scrivere che la terza fattura è un td17, quindi è corretto che non abbia ne l'inps ne la ritenuta d'acconto. I valori che ti ho riportato sono corretti come puoi verificare dall'immagine in allegato

![file](https://github.com/devcode-it/openstamanager/assets/60449835/58ebc50a-9136-4e75-9120-382600767110)

**Comment by leo-spa** [comment]
Io non ho apportato modifiche, ho aggiunto sono un logo

Il gio 8 giu 2023, 12:30 Valentina ***@***.***> ha scritto:

**Comment by leo-spa** [comment]
Scusa @Pek5892 ho visto che hai chiuso il post, quindi il problema che ho con la stampa fatturato mensile non è risolvibile?

**Comment by Pek5892** [comment]
Buongiorno @leo-spa, l'issue è stata chiusa un mese fa con la risoluzione del problema in release in seguito al commit https://github.com/devcode-it/openstamanager/commit/a8f1bbc4428bcd8ca4fe3a24e2b3b8ab4b628c52, in quanto il problema che le permane sembrerebbe non replicabile. Avremmo bisogno di maggiori informazioni per capire se le stampe necessitano di ulteriori correzioni, e possibilmente il problema dovrebbe essere replicabile da installazione pulita. In questo caso la invito ad aprire una nuova issue per mantenere le due problematiche distinte :smiley:
