### ISSUE TITLE
Errore se si elimina un doc contenete un articolo eliminato

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1307]
## Comportamento richiesto

se si crea un documento ( prev. ordine, vendita al banco, ecc.. ) con un articolo, poi successivamente quel articolo viene eliminato dal magazzino, **non sarà più possibile eliminare quel documento** e neanche rimuovere l'articolo inserito, anche se questo non esiste più a magazzino.

sarebbe comodo che **il sistema avvisi quando si elimina l'articolo** che è contenuto in un determinato documento/i
magari **con una nota che riporta i vari doc**.

altrimenti si è obbligati a intervenire sul DB per risolvere.

**Comment by Pek5892** [comment]
Buongiorno @sajotrei, i documenti collegati a un articolo e relativo avviso sono già visualizzabili all'interno della scheda articolo
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/299873c1-16c7-40ec-9801-3469514b2a78)

**Comment by sajotrei** [comment]
Ciao @Pek5892 
Si abbiamo visto, ed è già utile 👍

ma pensavamo a qualcosa di più, provo a spiegare meglio.

come già indicato sopra, quando si presenta quel errore a sistema è davvero molto scomodo e di fatto **bloccante** non c'è modo di risolvere se non agendo sul DB.

una soluzione potrebbe essere quella di "blindare" l'azione di elimina articolo 
per esempio **non concedere l'eliminazione di quell'articolo _SOLO_ se è contenuto in documenti ancora aperti non evasi.**

al contrario, dare la possibilità di eliminare l'articolo se è contenuto in documenti conclusi evasi.

questo potrebbe risolvere/ridurre il problema

inoltre nella sessione Documenti collegati ( immagine te postata ) a fianco **indicare lo stato del documento**

**Comment by Pek5892** [comment]
Non sarebbe più corretto impostare l'articolo come non attivo, sapendo di non doverlo più riutilizzare, anzichè cancellarlo dal gestionale una volta che è già stato inserito in qualche documento, come da avviso?

**Comment by sajotrei** [comment]
Ciao quindi non si può risolvere?
