### ISSUE TITLE
Cambio password utente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1308]
## Comportamento richiesto

non è possibile modificare la password utente
sia che si prova a fare il recupero password o la modifica sotto utenti e permessi 

nella demo 2445 non è possibile verificare
ma abbiamo provato anche su una installazione pulita.

![Screenshot 2023-05-19 alle 11 41 26](https://github.com/devcode-it/openstamanager/assets/75281007/bff4ae93-aec6-499d-9b4c-2742a32181bc)
![Screenshot 2023-05-19 alle 11 41 47](https://github.com/devcode-it/openstamanager/assets/75281007/bd688cc4-fb14-4a45-b56d-cfa675a7daae)

<img width="1441" alt="Screenshot 2023-05-19 alle 11 38 52" src="https://github.com/devcode-it/openstamanager/assets/75281007/cc5dfecd-88e6-4b90-90b5-806158e4d94a">

* Modulo:
* Versione del progetto:
* Versione PHP: 2.4.45
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno @sajotrei, da installazione pulita non riusciamo a riprodurre il problema, potrebbe darci maggiori informazioni? (gruppo di utente dal quale si sta provando ad effettuare la modifica - eventuali problemi segnalati effettuando un test sull'installazione)
Vedo che non vengono visualizzati neanche gli avvisi del controllo dei caratteri inseriti, quindi probabilmente c'è qualcosa che non va a livello di installazione.
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/269d70d7-5491-441e-a8eb-753e64261ea9)
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/2072b754-fc34-499b-8db4-c29f758f869a)

**Comment by sajotrei** [comment]
il problema si presenta su qualsiasi utente al di la del gruppo di appartenenza.
non si attiva il tasto **modifica**

![Screenshot 2023-05-19 alle 14 37 55](https://github.com/devcode-it/openstamanager/assets/75281007/77687afb-fb55-4449-ae70-a9840916284e)

**Comment by sajotrei** [comment]
quali sono i files coinvolti? così possiamo fare un check più approfondito

**Comment by Pek5892** [comment]
I file del modulo sono in modules/utenti. Potrebbe provare a inserire come password almeno 6 caratteri?

**Comment by sajotrei** [comment]
nel fare le prove, è emerso che il problema sembra essere legato al generatore psw introdotto nelle ultime ver.

se si inserisce la psw manualmente il tasto modifica si attiva.

![Screenshot 2023-05-19 alle 14 55 42](https://github.com/devcode-it/openstamanager/assets/75281007/ec51a1fd-db55-4034-810b-21e798e5f14a)

![Screenshot 2023-05-19 alle 14 56 23](https://github.com/devcode-it/openstamanager/assets/75281007/a24980fd-99c4-4677-a741-db102561782c)

**Comment by Pek5892** [comment]
Il tasto Modifica nel caso di generazione di password automatica viene abilitato solo dopo che la password appena generata sia stata selezionata/copiata, per evitare che la password venga salvata senza essere copiata e comunicata all'utente che deve utilizzarla per effettuare l'accesso.

**Comment by sajotrei** [comment]
ok quindi è una sicurezza 👍
è che così non è molto chiaro 😅

comunque avvisiamo il cliente che ci ha segnalato, con la tua spiegazione 👌

**Comment by sajotrei** [comment]
comunque anche selezionando/copiando non si attiva il tasto modifica 🤔
ma solo se modifichiamo o aggiungiamo un carattere o anche semplicemente la spazio 

![Screenshot 2023-05-19 alle 15 22 51](https://github.com/devcode-it/openstamanager/assets/75281007/d48a2183-f1e0-494c-aeb5-0feb5d602dc2)

![Screenshot 2023-05-19 alle 15 23 01](https://github.com/devcode-it/openstamanager/assets/75281007/2c7b4e24-9acf-472d-8622-6e7f610ef17c)

**Comment by Pek5892** [comment]
Intendevo copiare tramite CTRL+C, si attiva alla pressione di un tasto. Proveremo a renderlo più intuitivo. :smile:
