### ISSUE TITLE
file xml generato con campo non conforme

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1309]
Ciao @Pek5892 
il file xml che viene creato all'atto dell'emissione della fattura nella descrizione aggiunge un campo non conforme che andrebbe tolto

Tipo dato: IMPON-RACC
Rif. testo: Imponibile % ritenuta d'acconto
Rif. numero: 100,00

Questi valori inseriti in ogni rigo  andrebbero rimossi perchè inutili e non compilati correttamente

Inoltre perchè il file xml sia valido è presente questo errore:
Data riferimento termini di pagamento - Dati pagamento 1 - Dettaglio pagamento 1 (Dati della fattura) è richiesto

Quindi voi generate un file con "Data scadenza pagamento:"  che è facoltativa

mentre il valore "Data riferimento termini di pagamento: " obbligatorio è in bianco

![Screenshot_20230519_192311](https://github.com/devcode-it/openstamanager/assets/60449835/9581806f-670a-49a6-b9ce-a03a108684e6)

**Comment by Pek5892** [comment]
Buongiorno, l'xml generato non ottiene ricevuta di scarto dallo SDI, 
il nodo indicato inoltre non è obbligatorio, bensì è consigliato utilizzare data scadenza pagamento.
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/400c8031-7f45-49fe-9210-2b50b7f15a17)
https://fex-app.com/FatturaElettronica/FatturaElettronicaBody/DatiPagamento/DettaglioPagamento/DataRiferimentoTerminiPagamento
