### ISSUE TITLE
Inserimento seriali in fase di importazione Fattura Elettronica 

### ISSUE THREAD

**Issue by gponzo** [devcode-it/openstamanager#1311]
Quando importo una fattura elettronica in cui qualche prodotto ha il seriale, devo rimettere la fattura in bozza (ad importazione terminata), mettere il seriale e poi rimetterla in "emessa". Ci sono abituato e può andar bene così, però lo segnalo perché magari si potrebbe invece aggiungere il tastino seriali in fase di importazione :)

**Comment by sajotrei** [comment]
ciao è un punto che avevo già segnalato
ed è stato leggermente migliorato nelle ultime versioni

quando stai registrano la fattura, nella riga articolo clicca sul più per creare il nuovo articolo e **abilita il seriale** oltre che compilare i vari dati richiesti..
poi procedi come di consueto, a questo punto anche se la fattura appena importata avrà lo stato emesso sarà comunque possibile associare il seriale all'articolo senza cambiare lo stato in bozza..

purtroppo questo non funziona se si selezione crea articoli.

vedi anche 
Creare e associare il Seriale/i articolo in registrazione FE #1166

**Comment by gponzo** [comment]
Mea culpa!

In effetti sono fermo alla ver 2.4.30 e non posso aggiornare, fin quando non mi deciderò ad aggiornare tutto il server.
Bene comunque, mi fa piacere sapere che avrò questa miglioria non appena mi deciderò a fare questo passo (rifare il server).

Scusate per la segnalazione inutile.

**Comment by gponzo** [comment]
La ringrazio, ho cercato rapidamente di fare un merge manuale, ma i file sono troppo differenti.

Spero di trovare quanto prima il tempo per aggiornare il server e quindi il SW.

Grazie ancora.
