### ISSUE TITLE
Generazione ZIP (esempio con XML FE) contiene dati estranei al termine

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1314]
## Comportamento richiesto

Il file zip sia completo ma senza dati extra.

## Comportamento attuale

Al termine dell'EOD del file zip, c'è un blocco di pagina come mostrato qui (in giallo)

![image](https://github.com/devcode-it/openstamanager/assets/392762/8f5952c4-711c-4303-a95d-e54f97fe1807)

## Possibile soluzione

Sto indagando

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. selezionare delle fatture e tramite l'esportazione bulk scaricare lo zip coi documenti.

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: fatture
* Versione del progetto: 2.4.45
* Versione PHP: 8.0.27
* Tipo di server: Apache (aruba)

**Comment by marcus905** [comment]
Sospetti la funzione qui:

https://github.com/devcode-it/openstamanager/blob/5a0f29ff82d25c05c0953eed512f55e6b054afa9/lib/util.php#L315

una continuazione in output dopo la chiamata al download

https://github.com/devcode-it/openstamanager/blob/5a0f29ff82d25c05c0953eed512f55e6b054afa9/modules/fatture/bulk.php#L66

o la funzione di creazione dello ZIP

https://github.com/devcode-it/openstamanager/blob/5a0f29ff82d25c05c0953eed512f55e6b054afa9/src/Util/Zip.php#L78

**Comment by loviuz** [comment]
Ciao @marcus905 scusa il ritardo ma ho provato anch'io ora, con una 2.4.54 e non riesco a riprodurre il problema. Hai provato con una versione più recente per caso?

**Comment by marcus905** [comment]
Ciao, riprovo e ti aggiorno con l'ultima 2.4.54

**Comment by Pek5892** [comment]
Ciao @marcus905, hai avuto modo di provarlo o possiamo chiudere l'issue?

**Comment by marcus905** [comment]
Perdonami, riverifico al volo. Ti dico domani, grazie!

**Comment by marcus905** [comment]
![image](https://github.com/user-attachments/assets/5cb0393a-c364-4385-aaa5-30b9709732e8)
Il problema persiste con la 2.4.54

**Comment by Pek5892** [comment]
Potrebbe provare in demo pubblica? non riusciamo in nessun modo a riprodurre l'errore

**Comment by marcus905** [comment]
La demo pubblica non genera gli XML dando errore nella barra rossa, non posso scaricare massivamente da li.

**Comment by Pek5892** [comment]
Putroppo, essendo la demo pubblica, era stato impostato un adattatore di archiviazione inesistente da qualche utente, che non permetteva quindi la generazione di xml non trovando la cartella di destinazione. Ho provveduto a ripristinare l'archiviazione di default e ora le fatture vengono correttamente generate.

**Comment by marcus905** [comment]
Ora non c'è piu la password di default  e utente demo preimpostato, e non fa accedere

**Comment by Pek5892** [comment]
Modificato, li ho disattivati finchè effettuavo dei test ;)

**Comment by marcus905** [comment]
Anche la demo ha il problema:

![image](https://github.com/user-attachments/assets/1d2695c5-80e3-40b1-8415-37c0455286aa)
[fatture_1729162987.zip](https://github.com/user-attachments/files/17411261/fatture_1729162987.zip)
Per riprodurre:
![image](https://github.com/user-attachments/assets/85dc9a1c-80af-4c9e-b331-70fc714784ff)
