### ISSUE TITLE
errore importo in visualizzazione elenco fatture vendita

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1316]
Mi sono accorto che nel /controller.php?id_module=14
Nell'area vendite - fatture di vendita nella sezione netto a pagare, l'importo è errato per un centesimo.
Il netto a pagare in fattura invece è corretto.
Nelle due immagini che ho allegato, si vede la fattura che riporta l'importo corretto 95,00 euro
Mentre nell'elenco appare 94,99.
Grazie per la futura correzione

Versione installata 2.4.46 (Rbbc7b16df)
PHP (7.4.30 )

![Screenshot_20230607_203754](https://github.com/devcode-it/openstamanager/assets/60449835/15998653-3e35-41df-8843-ebc9074eb567)
![Screenshot_20230607_203810](https://github.com/devcode-it/openstamanager/assets/60449835/b2ba0bfc-e2eb-489c-986c-53e30ce1066f)

**Comment by sajotrei** [comment]
Ciao, si confermo questo problema che esiste da tempo.
noi per cercare di ovviare in parte abbiamo attivato la gestione di 3 decimali per importi, migliora ma non risolve del tutto il problema

**Comment by leo-spa** [comment]
L'importante che le fatture siano giuste, credo che ci sia da qualche parte
nel codice una dato errato, lo stesso problema lo avevo rilevato sia nella
compilazione della fattura e poi nella stampa, ma Valentina ha sempre
risolto

Il gio 8 giu 2023, 11:11 sajotrei ***@***.***> ha scritto:
