### ISSUE TITLE
Stampa Mastrino

### ISSUE THREAD

**Issue by L3d83** [devcode-it/openstamanager#1319]
## Comportamento richiesto

La stampa del mastrino, in pdf dovrebbe  far visualizzare l'elenco con l'apertura dell'anno precedente solo se è stata fatta la chiusura.

Attualmente questo non è cosi, viene riportata l'apertura anche se volutamente, l'anno precedente  non è stato chiuso.

La visualizzazione dell'elenco mastrini in html è corretta, allineare anche il pdf con le stesse query.

Il problema avviene in Contabilità - piano dei conti.

**Comment by Pek5892** [comment]
L'apertura viene mostrata per ogni mastrino in cui non è stato fatto un movimento manuale di apertura.
