### ISSUE TITLE
ORDINI FORNITORI - Problema con l'inserimento righe

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1321]
## Comportamento attuale

Quando in un ordine inserisco una riga, non viene aggiornato l'elenco e la row-list resta bloccata sulla gif di aggiornamento 

## Contesto

* Modulo: Ordini fornitore
* Versione del progetto: 2.4.46

**Comment by idraulicadueci** [comment]
L'errore restituito nel file log è division by zero e rimanda alla linea 200 del file /modules/ordini/row-list.php
` $progress_perc = $riga->qta_evasa * 100 / $riga->qta;`
infatti commentando la riga il problema non si presenta

**Comment by Pek5892** [comment]
Ciao @idraulicadueci, che versione di php stai usando?

**Comment by idraulicadueci** [comment]
8.0.27

**Comment by Pek5892** [comment]
non riusciamo a replicare l'errore, in fase di aggiunta riga viene proposta correttamente la quantità?
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/22e2d23c-9ff5-4926-9186-396a350a1fd5)

**Comment by idraulicadueci** [comment]
Strano, perché non ho files custom sul modulo. Fra l'altro lo stesso errore lo ottengo anche quando tento di creare un ordine fornitore da un preventivo.
[error.log](https://github.com/devcode-it/openstamanager/files/11779192/error.log)

**Comment by idraulicadueci** [comment]
Il problema deriva dal fatto che la quantità minima ordinabile è di default a zero. Infatti mettendola a un valore >0 il problema non si presenta. Non ci sono personalizzazioni nel database, ne' nei file. In effetti nelle installazioni pulite il problema non si presenta. Ho provato a fare un update del campo `qta_minima` della tabella `mg_fornitore_articolo` mettendo tutti i valori 0 a 1 e il problema non si ripresenta, ma se inserisco un nuovo articolo nel listino fornitore e mi dimentico di mettere il valore >0 si verifica di nuovo.
