### ISSUE TITLE
vista fatture , righe multiple della stessa fattura

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#1323]
Nella vista delle fatture di vendita trovo 3 righe della stessa fattura. 
Il progetto di Openstamanager è stato creato da nuovo. 

La cosa sembra avere a che fare con le mail inviate . La fattura è stata inviata 3 volte .

Nel progetto via è solamente una fattura. 

* Modulo: viste
* Versione del progetto:  2.4.44 (cbb0c15ae) 
* Versione PHP: 7.3.33-10
* Tipo di server: Apache/2.4.38 (Debian)

**Comment by lepool** [comment]
Confermo quanto scritto prima , ho inviato una altra mail ed ora ne vedo 4 di righe.

**Comment by Pek5892** [comment]
Buongiorno @lepool, aggiornando all'ultima versione il problema dovrebbe risolversi.
E' stato risolto con commit: https://github.com/devcode-it/openstamanager/commit/979d603396655d0e18c4bc96d735b9856fcf1e36
