### ISSUE TITLE
Modifica Righe inline

### ISSUE THREAD

**Issue by servisys** [devcode-it/openstamanager#1324]
Sarebbe interessante,
la possibilità di modificare le righe (preventivi e contratti), in-line senza dove aprire in modifica l'articolo.

Una cosa simile a quello che si può fare per la quantità e lo sconto.

![image](https://github.com/devcode-it/openstamanager/assets/11680849/ff73a7bb-d18d-4ddf-acc6-6c5028c545cd)

**Comment by sajotrei** [comment]
già vero 👍👏
quindi la possibilità di _**modificare online**_ la **descrizione**, q.tà, **prezzo**, sconto.

invece cliccando sul modifica avremmo maggior dettagli e info come ora...

in realtà penso che sarebbe utile un po su tutto, certamente in attività, preventivi, contratti, fatture.
meno rilevante in ordini, ddt

**Comment by servisys** [comment]
Si esattamente, su più cose si possono fare modifiche online, più è comodo, poi se servono dettagli in più, va bene dover aprire l'articolo.

Noi usiamo molto il campo descrizione anche per indicare la data di inizio e fine, e al rinnovo del contratto, dobbiamo aprire ogni articolo per modificarla, quindi poter fare la modifica senza aprire l'articolo, sarebbe veramente comodo

**Comment by Pek5892** [comment]
Disponibile dalla versione 2.4.50 (introdotto con commit https://github.com/devcode-it/openstamanager/commit/92354a02813672d6fc5214008c1ffe10cec0c7ea)

**Comment by sajotrei** [comment]
ottimo!
molto comodo 👏

suggerisco se possibile uniformare le colonne in questo modo, così occupano meno spazio ed è leggermente più lineare 


                <th width="35" class="text-center" >'.tr('#').'</th>
                <th>'.tr('Descrizione').'</th>
                <th width="105">'.tr('Prev. evasione').'</th>
                <th class="text-center tip" width="160">'.tr('Q.tà').'</th>
                <th class="text-center" width="140">'.tr('Costo unitario').'</th>
                <th class="text-center" width="140">'.tr('Prezzo unitario').'</th>
                <th class="text-center" width="140">'.tr('Sconto unitario').'</th>
                <th class="text-center" width="100">'.tr('Importo').'</th>
                <th width="80"></th>

___________

**PRIMA**
<img width="2001" alt="Screenshot 2023-09-29 alle 17 30 32" src="https://github.com/devcode-it/openstamanager/assets/75281007/94e5dafe-f2bb-48a4-b95c-f2f900673c7c">

___________

**DOPO**
<img width="1833" alt="Screenshot 2023-09-29 alle 17 28 18" src="https://github.com/devcode-it/openstamanager/assets/75281007/18480c38-93b5-4970-8e10-2ef7120d208c">

**Comment by Pek5892** [comment]
Ciao @sajotrei, le dimensioni delle colonne sono volute, perchè nel campo prezzo unitario c'è l'icon-before per visualizzare l'eventuale provvigione

**Comment by sajotrei** [comment]
Ciao Valentina, si ho visto

si potrebbe risolvere cosi.
**indicando la percentuale della provvigione in azzurro** come era prima, così è più evidente e fornisce la subito l'nformazione utile.

inoltre se fosse possibile **evidenziare un qualche modo quando nella riga è valorizzato lo sconto**.
prima uscita in rosso, ora non si vede a colpo d'occhio le righe con sconto.

_______
**PRIMA**
![Screenshot 2023-10-03 alle 11 07 12](https://github.com/devcode-it/openstamanager/assets/75281007/d0c99f20-2ecc-4f47-b45e-2bd27324a375)

_______
**ADESSO** Ver.2450
![Screenshot 2023-10-03 alle 11 06 54](https://github.com/devcode-it/openstamanager/assets/75281007/ee6faf5a-37be-4a3d-9b37-edd398ccc846)

_______
**DOPO**
![Screenshot 2023-10-03 alle 11 06 54](https://github.com/devcode-it/openstamanager/assets/75281007/88b1b63b-dd19-4270-93ae-8a080bfd1d30)
