### ISSUE TITLE
Redirect su HTTPS/SSL

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#133]
Salve,
è possibile inserire un'opzione che consenta di reindirizzare l'utente alla versione HTTPS del sito? O devo gestire io il file .htaccess?
Esempio:
http://example.com --> https://example.com
Grazie

**Comment by Dasc3er** [comment]
Ciao @maicol07,
Se controlli sul file **config.inc.php** della nuova versione 2.3 è disponibile l'opzione **$redirectHTTPS** appositamente per questa funzione.

**Comment by maicol07** [comment]
Ah ok grazie non avevo controllato. Tramite le impostazioni si può attivare? O devo modificare il file config.inc.php?

**Comment by loviuz** [comment]
devi modificarlo (per ora) da file config.inc.php

**Comment by maicol07** [comment]
Ok grazie mille. Funziona!
