### ISSUE TITLE
Nuova vendita - Modulo vendita al Banco

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1331]
## Comportamento richiesto

quando si crea una nuova vendita nel modulo vendita al banco, ma poi non si prosegue con salva, quando si torna in elenco è presente comunque una vendita vuota. 🤔

ci sia aspetta lo stesso principio e modalità degli altri documenti ( preventivi, ordini, fatture, ecc.. )
cioè che **rimanga il documento di vendita al banco solo se si salva**.

**Comment by Pek5892** [comment]
Ciao @sajotrei,
funziona così anche per gli altri documenti, viene salvato il documento in bozza una volta cliccato su Aggiungi, anche senza salvare.
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/c8798bfb-71c8-4409-8dfd-9b9aa4180b31)
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/808bdf18-9cec-41ac-bcb7-c5ab11bc7e14)

**Comment by sajotrei** [comment]
il problema nella vendita a banco che è molto scomodo perché rimangono aperte diverse "vendite" vuote 🤷🏻‍♂️

**Comment by Pek5892** [comment]
Suggerimento spostato tra le issue dell'apposito modulo.
