### ISSUE TITLE
Errore compilazione progetto

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [devcode-it/openstamanager#1333]
Buongiorno,
quando sto cercando di compilare il progetto si blocca sul file node-gyp.js
sapete aiutarmi?
questo il comando
yarn develop-OSM

grazie
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python311\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python311\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\xampp\\htdocs\\xxx\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\xampp\htdocs\xxxx\node_modules\node-sass
gyp ERR! node -v v18.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

**Comment by Pek5892** [comment]
Buongiorno @andreameneguzzoinfol  potrebbe controllare di aver installato python?

**Comment by andreameneguzzoinfol** [comment]
@Pek5892 
confermo che è installato
![image](https://github.com/devcode-it/openstamanager/assets/24794417/2db47ec4-7aec-4029-8186-1285480889d8)

**Comment by Pek5892** [comment]
ciao @andreameneguzzoinfol, potresti controllare che i file package.json e gulpfile.js siano allineati con quelli in release?
nello specifico che package.json riporti le righe:
       "gulp-sass": "^5.1.0",
        "sass": "^1.62.1",
e gulpfile.js:
        const sass = require('gulp-sass')(require('sass'));
