### ISSUE TITLE
Bug in stampa scheda di accettazione

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1335]
Nel modulo "accettazione" (un po' acerbo per alcuni versi, ma segnalerò in seguito cosa penso sia migliorabile) ho notato un bug nella stampa finale.
Allego una stampa dell'intervento 22 creato col modulo accettazione compilando tutte le sezioni disponibili. Si osserva che:
1. Il campo "modello apparato" non viene stampato
2. Il campo "serial number" non viene stampato
3. I campi "dati", "password" e "teleassistenza" vengono impaginati in modo confuso, sembra mancare qualche "tag" ma non potendo vedere il codice sto solo facendo supposizioni. A naso direi che la struttura è una tabella in cui il "sì" relativo al campo "dati presenti nel sistema" viene allineato a destra e tutto il resto rimane anch'esso a destra.
4. Il campo "descrizione del problema a cura del cliente" non viene stampato.
5. Non c'è nessun riferimento al tecnico assegnato ma forse è voluto.

Per le prove ho utilizzato la versione demo 2.4.47 (https://demopremium.osmbusiness.it)
![Accettazione stampa modulo](https://github.com/devcode-it/openstamanager/assets/102433047/1802188f-9baa-4a60-9fc9-77167bcc962b)
![Accettazione creata](https://github.com/devcode-it/openstamanager/assets/102433047/1ca850ad-bb55-4cdb-9f7a-6c83a903d18c)
![Accettazione compilazione](https://github.com/devcode-it/openstamanager/assets/102433047/a0185825-8a3b-48cf-89fe-fd9a10e3370e)

**Comment by NicolaNext** [comment]
Aggiungo, scusate, le foto vanno viste dall'ultima alla prima

**Comment by Pek5892** [comment]
Ciao @NicolaNext, grazie per la segnalazione! abbiamo apportato delle correzioni al modulo e ora non dovrebbe più presentare errori :smile:

**Comment by NicolaNext** [comment]
Grazie Valentina,
meglio dei pompieri! Problema preso in gestione e QUASI risolto in un'ora! 
Dico quasi perchè rimane qualche cosetta, nei due campi "Descrizione del problema a cura del cliente" e "Materiale consegnato" in fase di compilazione è previsto che io possa andare a capo.. 
ma se vado a capo.. 
hai già capito, se vado a capo mi stampa solo il primo paragrafo, tutto quello che scrivo dopo essere andato a capo non viene stampato.
Aggiungo che, se entro **nell'attività** creata e apporto una modifica alla "descrizione del problema" (non impossibile col cliente che si ricorda altro), quando **ristampo** l'accettazione la parola GIORNI del campo "giorni di deposito" va a capo e perde il grassetto.
Se serve ti carico delle foto.

Buon divertimento

**Comment by sajotrei** [comment]
> Ciao @NicolaNext, grazie per la segnalazione! abbiamo apportato delle correzioni al modulo e ora non dovrebbe più presentare errori 😄


Ciao Valentina, dove troviamo le modifiche apportate?

**Comment by Pek5892** [comment]
Ciao @NicolaNext,
ho caricato le modifiche in demo pubblica :smile: 

Ciao @sajotrei, puoi provare il modulo in demo pubblica e richiedere la versione aggiornata via ticket.

**Comment by NicolaNext** [comment]
Buongiorno Valentina,
adesso sembra tutto a posto. Il modulo "accettazione" è decisamente interessante anche se vedo enormi margini di miglioramento (ad esempio si potrebbe immaginare una integrazione tra i dati del materiale consegnato e gli impianti del cliente), ma queste diventeranno altre issues più avanti. Con il 2024 passeremo ad Open Sta Manager quindi mi sto "portando avanti".

Giusto perchè sono incontentabile... dato che ora il report stampato è diventato discretamente lungo potrebbe essere un'indea inserire una interruzione di pagina prima delle condizioni, tanto è praticamente scontato che vadano a finire nella seconda pagina.
