### ISSUE TITLE
numerazione fattura errata al cambio del tipo documento

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1336]
## Comportamento richiesto

se si crea una fatture di vendita in bozza, es. TD01 Vendita immediata 
poi si cambia il tipo di documento es. TD02 acconto su fattura, la si completa e si emette la fattura, **il sistema assegna la numerazione dalla fattura di vendita immediata** invece di usare la numerazione specifica del tipo documento..

quindi non tiene conto del tipo di documento 

* Modulo:
* Versione del progetto: 2445
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
il numero progressivo attribuito in fase di emissione di un documento viene calcolato sulla base della maschera impostata nel sezionale, non in base al tipo di documento. Per avere una numerazione progressiva in base a un determinato tipo di documento è necessario creare un sezionale apposito con maschera propria dove creare questi documenti.

**Comment by sajotrei** [comment]
ciao Valentina,
si si confermo che abbiamo il sezionale distinto per tipo di documento...

quello che volevo sottolineare che se creo un documento es. fattura
poi cambio idea e all'interno del documento lo cambio es. parcella  ( vedi sotto )
il sistema mi assegnerà comunque la numerazione della fattura e non terrà conto quella della parcella che ha un suo sezionale distinto.


![Screenshot 2023-07-20 alle 10 12 15](https://github.com/devcode-it/openstamanager/assets/75281007/bcf6c195-d973-401f-a150-0ddbddf68bca)

**Comment by lucasalva87** [comment]
Confermo che non c’è (e non è prevista) la possibilità di ricalcolare i numeri in funzione al tipo del documento, ne a qualsiasi altro campo. Infatti il sezionale non è modificabile una volta emesso il documento: quest’ultimo viene scelto solo in fase di emissione della fattura (esempio) e poi il campo non è più disponibile.
Per ricalcolare la numerazione corretta va eliminato e ricreato il documento associandolo sin dall’inizio al sezionale corretto.

**Comment by Pek5892** [comment]
Nella versione 2.4.47 abbiamo introdotto la funzionalità di cambio sezionale da azioni di gruppo.
Sarà sufficiente riportare in stato Bozza il documento, selezionarlo e da azione di gruppo spostarlo nel sezionale corretto, il numero verrà così azzerato e all'emissione del documento verrà attribuito il progressivo in base alla maschera del sezionale corrente.

**Comment by sajotrei** [comment]
> Confermo che non c’è (e non è prevista) la possibilità di ricalcolare i numeri in funzione al tipo del documento, ne a qualsiasi altro campo. **Infatti il sezionale non è modificabile una volta emesso il documento**: quest’ultimo viene scelto solo in fase di emissione della fattura (esempio) e poi il campo non è più disponibile. Per ricalcolare la numerazione corretta va eliminato e ricreato il documento associandolo sin dall’inizio al sezionale corretto.


Luca, comunque vorrei precisare che il documento **è ancora in bozza senza numerazione**, quindi per logica dovrebbe darmi la possibilità di fare il **cambio del tipo documento**.

**Comment by sajotrei** [comment]
si può fare qualcosa per risolvere questo errore ?

**Comment by sajotrei** [comment]
@lucasalva87 
hai ragione 😅

con questa Issue si risolverebbe 
**Sezionale predefinito per tipo di documento #1175**

**Comment by sajotrei** [comment]
con la 2.4.49 è stata introdotta la issue **Sezionale predefinito per tipo di documento https://github.com/devcode-it/openstamanager/issues/1175**

quindi magari ora è possibile valutare quanto suggerito. 😉👍

**Comment by Pek5892** [comment]
Ciao @sajotrei, potresti riassumere qual è la richiesta?

**Comment by sajotrei** [comment]
> ok grazie della risposta.
> 
> magari potrebbe aver senso dare la possibilità del cambio tipo documento SOLO a quelli dello stesso sezionale. così il problema si risolve comunque
> 
> quindi se la parcella ha un suo sezionale distinto, non verrà indicato insieme nelle fattura della schermata sopra allegata
> 
> che ne pensate?

questa soluzione...
che di fatto tiene conto del sezionale per tipo documento.
