### ISSUE TITLE
cambio schermata su modifica scadenze

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1337]
## Comportamento richiesto

una cosa molto scomoda è che quando siamo nella fattura ( immagine 1 ) e clicchiamo su modifica scadenze, il sistema ci apre la pagina ( immagine 2 ) poi se si clicca salva e chiudi ci si trova in elenco scadenze ( immagine 3 ) 
poi dobbiamo andare nuovamente sulla fattura e aggiornare la pagina F5.

sarebbe molto più pratico e comodo che dopo aver fatto la modifica alle scadenze, ci riporta alla fattura in questione e che faccia un refresh automatico.

__________________

![1](https://github.com/devcode-it/openstamanager/assets/75281007/d7974b74-225d-4cb1-967a-0e52aab3461a)
![2](https://github.com/devcode-it/openstamanager/assets/75281007/4ab565b1-e7d7-4b01-bf09-c499cf979bd4)
![3](https://github.com/devcode-it/openstamanager/assets/75281007/ddd6ed9e-e63b-41ca-917f-0c6f2cc715b6)

**Comment by Pek5892** [comment]
Ciao @sajotrei,
è possibile registrare i pagamenti direttamente dalla fattura utilizzando l'apposito tasto **Registra contabile** se non si ha necessità di modificare scadenze e visualizzare successivamente lo scadenzario.

**Comment by sajotrei** [comment]
no non mi riferisco alla registrazione contabile 

ma alla modifica delle scadenze, e che ti apre altre schermate senza ritornare alla schermata della fattura...

**Comment by Pek5892** [comment]
Per tornare alla fattura di origine è sufficiente cliccare su Apri documento.
![immagine](https://github.com/user-attachments/assets/f8eb1ce1-3dae-4087-af0f-f561da8e2a7b)
