### ISSUE TITLE
Inserimento secondo destinatario mail fa comparire numerosi campi errati (Javascript)

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1338]
## Comportamento richiesto

Nel momento che inserisco un CC nell'invio mail fattura, mi aspetto che funzioni l'invio e che non compaiono errori come da video

## Comportamento attuale

Ci sono diversi campi vuoti inutili ed errati, l'invio funziona solo parzialmente.

## Possibile soluzione

Problema lato Javascript, non ho potuto indagare

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Creazione fattura
2. Invio mail
3. Inserimento secondo destinatario

Video:

https://github.com/devcode-it/openstamanager/assets/392762/fdddc3e2-c42b-4816-a5e5-1c45f5e9ed2c

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: email
* Versione del progetto: 2.4.47
* Versione PHP: 8.0
* Tipo di server: Apache (Aruba)

**Comment by Pek5892** [comment]
Buongiorno @marcus905, risolto con fix: https://github.com/devcode-it/openstamanager/commit/89152478610342fdb4ecf134fd77da03f4d2cf72, potrà trovare la correzione nella prossima release.
