### ISSUE TITLE
Viste - Stringhe non supportate

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#134]
Nel modulo viste ho riscontrato il seguente malfunzionamento volendo aggiungere per "scadenzario" un nuovo campo "Data emissione fattura":

1. riesco ad aggiungere il nuovo campo
2. riesco a salvare la modifica senza errore
3. la query risultante contiene una stringa parziale 

Qui i dati :
La casella _**\_bg\_**_ contiene la query _**IF(scadenza<NOW(), '#ff7777', '')**_
Il problema avvieme in edit.php del modulo viste quando viene effettuato il submit "fields". Mi trancia il contenuto della query in _**IF(scadenza**_    .
Ho controllato e prima del submit i dati sono corretti nel form. Dopo il submit a actions.php riceve solo i dati tranciati. Se lascio uno spazio tra _**<**_ e _**Now**_ il problema non si presenta.

**Comment by Dasc3er** [comment]
@lepool Il problema in questione viene generato dal fatto che il browser interpreta il contenuto come un tag HTML.
In ogni caso la query dovrebbe essere salvata correttamente, come dovresti poter notare dalla simulazione di query all'inizio della pagina.

**Comment by lepool** [comment]
Ah, percio il browser traduce il contenuto e lo modifica in formato supportato per browser?

**Comment by Dasc3er** [comment]
Teoricamente si.
Per sicurezza, poi provare a inserire la query che crea il problema, salvare e navigare all'interno del modulo in questione: non dovrebbero verificarsi problemi.

@loviuz Ora che ci penso, sarebbe possibile provare a inserire un _htmlencode_ per codificare in automatico questi caratteri, anche se poi bisognerebbe controllare che non ci siano malfunzionamenti con il salvataggio nel database.

**Comment by lepool** [comment]
Se provi ad aggiungere un campo al modulo scadenzario lo vedi subito.

**Comment by lepool** [comment]
Ho appena provato javascript encodeURIComponent e decodeURIComponent e falliscono con la stringa
**"IF(scadenza<NOW(), \'#ff7777\', \'\')', 8, 1, 0, 0, 1"** 
succede la stessa cosa come nel bug descritto .

**Comment by Dasc3er** [comment]
Con il commit abd26ffec0c724a448c2253253a760149dfb63ff il problema dovrebbe essere stato risolto.
In pratica, è stata disabilitata la protezione contro l'XSS esclusivamente per il campo query in questione.

**Comment by lepool** [comment]
Confermo, ora la stringa viene accettata.

**Comment by loviuz** [comment]
in effetti non avevo mai provato ad inserire un campo in quel modo, però con htmlentities avrebbe dovuto risolversi, con possibile problema però in salvataggio poi.

**Comment by lepool** [comment]
In teoria dovrebbe esserci il problema in ogni modulo dove in post trasmetti < senza spazio in seguito.

**Comment by Dasc3er** [comment]
Per la precisione, il problema era nel filtraggio automatico dell'input per la protezione contro XSS.
Considerando che il modulo Viste è avanzato e disabilitato di default, ho disabilitato la protezione XSS per il singolo campo dove si potevano verificare questi problemi.

Non si trattava quindi di un malfunzionamento generato dal browser come credevo inizialmente.

**Comment by loviuz** [comment]
Essendo uno strumento avanzato e disabilitato di default, può rimanere anche disattivato il filtro xss, perché potrei voler aggiungere parti di html con qualche CONCAT su delle colonne. Che ne dite?

**Comment by Dasc3er** [comment]
Per adesso infatti è disabilitato per le query del modulo Viste, mentre negli altri moduli è attivo.

**Comment by lepool** [comment]
@Dasc3er , potresti spiegarmi in che modo viene filtrato l'input ?

**Comment by Dasc3er** [comment]
@lepool In pratica, gli attacchi XSS prevedono l'utilizzo di codice HTML con JavaScript malevolo per l'utente finale.
La libreria [HTMLPurifier](http://htmlpurifier.org/) rimuove in automatico tutti i tag HTML e i relativi attributi non inseriti nella whitelist che puoi trovare qui: https://github.com/devcode-it/openstamanager/blob/b8b9e95929c6b227fc0d66d492fd830f88355798/src/Filter.php#L141

**Comment by lepool** [comment]
Per questo se neccessario bisognerebbe prima codificare in formato ad es. json e poi trasmettere al server dove poi viene tradotto, giusto?

**Comment by Dasc3er** [comment]
No, provo a spiegarmi meglio.

Il codice `<br><a href="" onclick="">ciao</a>` è codice HTML con i tag _br_ e _a_.
Questi tag sono permessi dal filtro, mentre l'attributo _onclick_ viene rimosso perché non permesso.

In ogni caso la codifica JSON non è utile per migliorare la gestione dei dati, peggiorerebbe soltanto la situazione.

**Comment by lepool** [comment]
Capito, grazie. Sei stato chiarissimo.

**Comment by Dasc3er** [comment]
In modo simile, il codice HTML `il risultato è <di quello precedente` può essere interpretato come contenente il tag <di, e pertanto filtrato di conseguenza in `il risultato è ` .
Al contrario, il codice HTML `il risultato è < di quello precedente` (con lo spazio) viene considerato correttamente.

Questo comportamento è presente quindi in tutti moduli e dove è richiesto l'input dell'utente.
E' stata inserita un'esclusione specifica per il modulo Viste nei punti in cui si potevano verificare problemi con l'interpretazione delle query.

@devcode-it/openstamanager Eventualmente potremmo considerare di inserire come facoltativa l'abilitazione di questa protezione, come di inserire la possibilità di rimuovere i controlli contro attacchi brute-force.

**Comment by loviuz** [comment]
Non ho ben capito come proporresti di risolvere...

**Comment by Dasc3er** [comment]
Proponevo l'aggiunta di una variabile nel file di configurazione, così costruita di default:
```php
$security = [
    'brute-force' => true,
    'xss' => true,
];
```

Nel caso venissero modificati i valori in `false`, volevo fare in modo che le relative operazioni venissero disabilitate.

**Comment by loviuz** [comment]
temporaneamente si potrebbe introdurre allora, se non è una modifica impegnayiva, lasciandole di default a true

**Comment by Dasc3er** [comment]
Effettivamente però l'utilità di questa variabile non è molto elevata...

**Comment by loviuz** [comment]
ma ora... lasciando lo spazio dopo < o >, il testo viene mantenuto? non ho ancora provato. perchè, se viene mantenuto il testo originale, si può lasciare così secondo me. è uno strumento avanzato e se serve uno spazio per non bloccare la stringa secondo me basta questo

**Comment by Dasc3er** [comment]
Si, funziona proprio così...

**Comment by loviuz** [comment]
A questo punto lascerei questo funzionamento. Dovremmo scrivere da qualche parte che i simboli < o > devono essere usati con uno spazio. Non so se conviene scriverlo nella documentazione o come alert nella schermata

**Comment by lepool** [comment]
Volendo si potrebbe impostare un controllo sugli input con un eventuale alert. Sarebbe secondo me la cosa migliore.

**Comment by loviuz** [comment]
Ho aggiunto un testo nell'help dei 3 campi dove si possono inserire query, giusto per ricordare di inserire sempre gli spazi con caratteri < o >.
E' uno strumento avanzato per sviluppatori, non so se sia troppo inserire un alert in fase di salvataggio, almeno per ora...

**Comment by Dasc3er** [comment]
@loviuz Possiamo quindi considerare la issue risolta?
