### ISSUE TITLE
Stampa Liquidazione IVA

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#1340]
Buongiorno,

quanto sto per segnalare si verificava anche con le versioni precedenti. Attualmente ho la versione 2.4.48, PHP 7.4.27, MySQL  5.7.32.

Quando lancio la Liquidazione iva dalle stampe contabili, e inserisco il periodo predefinito (Ad esempio il Terzo trimestre 2023), il risultato dell'IVA a Debito mi sembra che in realtà sia la somma di tutto l'anno e non solo del trimestre. Forse è corretto così però, se inserisco il periodo manualmente, l'iva mostra il valore corretto.

A disposizione per qualsiasi chiarimento

**Comment by Pek5892** [comment]
Buongiorno @leonardocalabretta,
non riusciamo a replicare il problema in un'installazione pulita, potrebbe verificare che i file presenti in templates/liquidazione iva corrispondano a quelli della release? e eventualmente provare a replicare il problema in demo pubblica

**Comment by leonardocalabretta** [comment]
Non so se è replicabile facilmente in un ambiente diverso dal mio. Posso farvi vedere sul mio?

I file sono di questa mattina alle 9:18 quando ho fatto l’upgrade alla 2.4.48

Leonardo

--

Leonardo Calabretta - IT Solutions Architet

 
  
    
  
 +39 0521 18 56 267 | +39 393 79 82 036 
 
 ***@***.*** 
 
 www.leonardocalabretta.com 
 
 
  

  
 
  
   
   
   
 
 
 
Il giorno 2 ago 2023, alle ore 10:49, Valentina ***@***.***> ha scritto:



Buongiorno @leonardocalabretta<https://github.com/leonardocalabretta>,
non riusciamo a replicare il problema in un'installazione pulita, potrebbe verificare che i file presenti in templates/liquidazione iva corrispondano a quelli della release? e eventualmente provare a replicare il problema in demo pubblica

**Comment by Pek5892** [comment]
@leonardocalabretta sono presenti personalizzazioni/file diversi da quelli presenti nello zip? ha provato ad effettuare un test dell'installazione? https://docs.openstamanager.com/v/2.4.48/guide/esempi/verificare-linstallazione-di-osm

**Comment by leonardocalabretta** [comment]
Sui file è tutto ok. Sul DB ho questo:

[Capto_Capture 2023-08-02_12-43-39_PM.png]
 e poi sui controlli del gestionale, ho dei problemi riguardanti le anagrafiche senza REA. Ma non credo centri nulla

--

Leonardo Calabretta - IT Solutions Architet

 
  
    
  
 +39 0521 18 56 267 | +39 393 79 82 036 
 
 ***@***.*** 
 
 www.leonardocalabretta.com 
 
 
  

  
 
  
   
   
   
 
 
 
Il giorno 2 ago 2023, alle ore 12:42, Valentina ***@***.***> ha scritto:



@leonardocalabretta<https://github.com/leonardocalabretta> sono presenti personalizzazioni/file diversi da quelli presenti nello zip? ha provato ad effettuare un test dell'installazione? https://docs.openstamanager.com/v/2.4.48/guide/esempi/verificare-linstallazione-di-osm

**Comment by Pek5892** [comment]
Non riusciamo a visualizzare l'immagine, potrebbe provare cancellando la cartella templates e riestraendo quella dello zip della release?

**Comment by leonardocalabretta** [comment]
Ok credo di aver capito dove fosse il problema.
Io utilizzo Safari su MacOS; provando con Chrome il problema non si verifica. Unico caso da quando utilizzo il software. Con Safari ha sempre funzionato tutto alla perfezione, tranne questa cosa.
In pratica anche se seleziono "Terzo trimestre" o qualsiasi altro dal menù tendina, in pratica le date  sulla destra non vengono aggiornate.
![Capto_Capture 2023-08-22_06-11-07_PM](https://github.com/devcode-it/openstamanager/assets/757880/091eaa01-71f4-4e20-9d89-6d884f22c5d5)
