### ISSUE TITLE
errore upload file programma bloccato

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1343]
![Screenshot_20230803_213137](https://github.com/devcode-it/openstamanager/assets/60449835/9b5ea2bb-1a94-4efe-acaf-adc0372f188a)
ho effettuato l'upload alla versione 2.4.48
sono 3 anni che aggiorno il programma e non ho mai avuto problemi, ho 171 file che non vengono sovrascritti, è stato cancellato il file della versione 2.4.47 ed inserito uno a 0
adesso non riesco più ad accedere,al login non mi fa accededere, come posso fare per risolvere il problema?

**Comment by Pek5892** [comment]
Ciao @leo-spa, per riprendere a utilizzare il gestionale conviene effettuare un ripristino dell'ultimo backup eseguito (consigliamo di effettuarne sempre uno prima di tentare l'aggiornamento del gestionale).
Dovresti poi verificare le motivazioni del perchè questi file non vengono caricati, potresti controllare di avere i permessi di scrittura su questi file per l'utente con cui sei loggato?

**Comment by leo-spa** [comment]
Si è verificato un errore [uid: 463cc81]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception Error: "Class 'Modules\Fatture\Fattura' not found" at /var/www/clients/client92/web5527/web/plugins/receiptFE/edit.php line 38

questa mattina mi fa entrare con il login ma appaiono questi errori, dice che fa il backup ma non appare in lista, ho un backup del 18 luglio non ho tante registrazioni da riprendere ho fatto delle immagini dello schermo per un'eventuale ripristino

riprovare a caricare il pacchetto aggiornamento potrebbe servire?

**Comment by Pek5892** [comment]
Solitamente quando prova a fare il backup ma non lo porta a termine è un problema di spazio residuo. Dovresti provare a cancellare i file via ftp (tranne le cartelle files, backup e il config) e caricare i file presenti nello zip della release.
Chiudo l'issue perchè non è un problema riproducibile legato al gestionale ma alla specifica installazione, e ricordo che in queste casistiche è preferibile utilizzare il nostro forum: [forum.openstamanager.com](https://forum.openstamanager.com/) :smiley:
