### ISSUE TITLE
Avviso fattura con lo stesso numero

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1344]
## Comportamento richiesto

se si duplica una fattura già emessa, il sistema segnala che esiste una fattura con lo stesso numero.
me non è vero perché la nuova fattura è in bozza e non ha ancora il numero...

**quando poi la nuova fattura duplicata da stato bozza passa a stato emessa, l'avviso sparisce.**

<img width="1038" alt="Screenshot 2023-08-30 alle 11 13 21" src="https://github.com/devcode-it/openstamanager/assets/75281007/10b64dda-23ed-437a-88b9-c435e285ca49">

* Modulo:
* Versione del progetto: 2.4.48
* Versione PHP: 7.4.33
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei, non riusciamo a replicare il problema, potresti farci un esempio sulla demo pubblica?

**Comment by sajotrei** [comment]
sulla demo ho provato ed esce l'avviso anche li

![Screenshot 2023-08-30 alle 12 17 32](https://github.com/devcode-it/openstamanager/assets/75281007/ca039134-38f3-4155-8704-24a130178fa1)

**Comment by Pek5892** [comment]
Abbiamo provato da azioni di gruppo e dall'interno del documento ma non riusciamo a visualizzare l'avviso, che azioni eseguite per duplicare il documento?
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/5943f580-0035-45d8-a246-fc5c7fdcc2df)

**Comment by sajotrei** [comment]
apriamo la fattura e clicchiamo su duplica fattura

![Screenshot 2023-08-30 alle 12 55 47](https://github.com/devcode-it/openstamanager/assets/75281007/32657044-991f-4425-a44c-11ee40f9c039)

**Comment by Pek5892** [comment]
seguendo questi passaggi?
https://www.awesomescreenshot.com/video/20350893?key=d2bdb8877d6a9c1954605cb6e9d3e6d3

**Comment by sajotrei** [comment]
comunque l'avviso si presenta anche solo creando una nuova fattura senza fare duplica 

ho appena provato sulla demo 

![Screenshot 2023-09-04 alle 11 41 29](https://github.com/devcode-it/openstamanager/assets/75281007/ee888ce6-97f8-4e33-bc12-99b412009fc7)

**Comment by Pek5892** [comment]
Abbiamo effettuato dei test ma non riusciamo a replicare l'errore nemmeno in fase di aggiunta nuovo documento

**Comment by Pek5892** [comment]
Chiudo perchè non riproducibile
