### ISSUE TITLE
Problema validazione su form submit

### ISSUE THREAD

**Issue by matt-tro** [devcode-it/openstamanager#1346]
Buongiorno,
Su add.php di "modules/anagrafiche" ho messo una validazione sulla partita iva per il controllo dei duplicati sfruttando l'apposito file validation.php, però, anche se la validazione della partita iva fallisce, mi viene comunque permesso di inserire l'anagrafica. Come posso fare per fare in modo che questo errore sia bloccante?

Io ho provato ad effettuare un check sul form tramite Javascript che controllasse se ci fossero div con classe "has-error", ma non funziona. C'è un modo "ufficiale" per risolvere questa cosa?

Cordialmente,
Mattia

**Comment by Pek5892** [comment]
Buongiorno @matt-tro,
nella versione corrente del gestionale (2.4.48) è già presente un controllo sulla partita IVA, che versione del gestionale sta utilizzando?
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/33e34c11-38e2-4a77-b491-ddd5e1b4c652)

**Comment by matt-tro** [comment]
Buongiorno @Pek5892,
L'avviso sulla partita IVA mi funziona perfettamente, ma il problema che sto cercando di esporre è diverso: quando clicco su "Aggiungi", dal momento che c'è un errore di validazione, mi viene comunque inserita l'anagrafica.

Io avevo messo un check sul submit del form che controlla la validazione e il blocco in caso di esito negativo, però sia che la validazione è corretta, sia che non lo è, al click sul bottone "Aggiungi" non funziona più l'inserimento.

**Comment by Pek5892** [comment]
@matt-tro potrebbe fare una pull request, così nel caso in cui sia una funzionalità di utilità comune avremmo modo di verificarla e correggerla?

**Comment by matt-tro** [comment]
@Pek5892 ho appena creato la pull request

**Comment by Pek5892** [comment]
Abbiamo testato la modifica e per il momento abbiamo deciso di lasciare l'inserimento della partita IVA libero e non bloccante, a causa di alcune casistiche che non verrebbero più gestite.
