### ISSUE TITLE
Statistiche

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1347]
## Comportamento richiesto

nelle statistiche **in vendite e acquisti** sarebbe utile avere **i mesi** nel grafico

invece nelle altre statistiche dove **i mesi** sono indicati **risultano in inglese**.

nel grafico **Numero interventi per tipologia** e **Ore interventi per tipologia**
riteniamo sia comodo poter avere un elenco per selezionare e **filtrare il tecnico**.

![1](https://github.com/devcode-it/openstamanager/assets/75281007/8389feec-c1b7-4891-a103-742d655ae637)
![2](https://github.com/devcode-it/openstamanager/assets/75281007/c831ec5d-9eec-4cb7-b9c1-200134040b3f)
![3](https://github.com/devcode-it/openstamanager/assets/75281007/9897c0fb-d378-494e-a789-0e35b47c3d56)
![4](https://github.com/devcode-it/openstamanager/assets/75281007/8f107040-934d-4dd0-82c2-1d407fb45fa0)

**Comment by Pek5892** [comment]
Ciao @sajotrei, nel grafico acquisti e vendite non è possibile visualizzare i mesi in quanto è possibile confrontare periodi diversi

**Comment by sajotrei** [comment]
sinceramente non mi è chiaro del perché non è possibile
ho provato a selezionare periodi diversi ciccando su Aggiungi periodo, e comunque il mese corrisponde nell'asse verticale del grafico, quindi presumo si possa inserire il nome del mese.

la cosa scomoda di adesso è che si fa a intuito e non è immediata la lettura..

**Comment by Pek5892** [comment]
Il problema sorge andando a confrontare periodi diversi, i mesi mostrati nell'asse delle x non corrisponderebbero:
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/e30e7f2c-fe2c-4bc2-b778-9d5544c1b880)

**Comment by sajotrei** [comment]
Ciao Valentina quindi non è possibile applicare questa modifica ?
> nel grafico Numero interventi per tipologia e Ore interventi per tipologia
> riteniamo sia comodo poter avere un elenco per selezionare e filtrare il tecnico.


inoltre abbiamo notato che nella 2.5 è stato torto il filtro Tipi attività che è presente fino alla 2.4.54
![Screenshot 2024-08-30 alle 17 14 57](https://github.com/user-attachments/assets/03ccbc3c-fcbd-48e0-8207-cc3359f6afbb)

**Comment by Pek5892** [comment]
Buongiorno @sajotrei ho corretto il menu a tendina che non era più visualizzato in Statistiche, e appuntato i suggerimenti indicati.

**Comment by sajotrei** [comment]
> Buongiorno @sajotrei ho corretto il menu a tendina che non era più visualizzato in Statistiche, e appuntato i suggerimenti indicati.

Ciao Valentina, non sembra che sia stato ripristinato il menu a tendina nelle statistiche 
stiamo testando la 2.5.5 

![Screenshot 2024-10-08 alle 11 28 57](https://github.com/user-attachments/assets/4723f6c2-dfd5-4f13-ac67-f6f1bb51530b)
