### ISSUE TITLE
(bug) campo nascosto in Listini cliente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1348]
## Comportamento richiesto

campo nascosto in Listini cliente, è necessario chiudere il menu Plugin 

![1](https://github.com/devcode-it/openstamanager/assets/75281007/f337321d-94a0-442f-8ac6-05ebbccd33c3)
![2](https://github.com/devcode-it/openstamanager/assets/75281007/aa141cfc-55f7-4e0f-a2ff-8a4ba3f1a370)

* Modulo:
* Versione del progetto: 2.4.48
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
Ciao Valentina
il problema non si è risolto con la modifica, è leggermente migliorato.

I button laterali per la modifica delle righe rimangono nascosti. 🤷🏻‍♂️

**Comment by Pek5892** [comment]
Non riusciamo a riprodurre il problema, l'adattamento della tabella è ora dinamico in base alla larghezza della pagina:
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/7a20d61c-219e-45f4-b0d0-527c09fadb74)
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/a0d6f086-415d-4679-b870-a6fb0372ef50)

**Comment by sajotrei** [comment]
ho fatto le prove su una installazione pulita e con tutti i browser con pagina al 100%, e confermo che i tasti rimangono nascosti

ho fatto la prova anche con la demo online, e anche li si presenta il problema.
https://demo.osmcloud.it/2448/editor.php?id_module=88&id_record=4

**Comment by Pek5892** [comment]
La modifica è stata introdotta nella versione 2.4.49, la demo non è  ancora stata aggiornata.
Potreste provare nella demo premium che invece è stata aggiornata all'ultima versione?
https://demopremium.osmbusiness.it/editor.php?id_module=88&id_record=1
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/f0765617-1ed0-49c1-ae60-eef51f03ee3f)

**Comment by sajotrei** [comment]
già vero ho visto ora che la demo pubblica è la 2448

ok ho verificato sulla demo 2449 che mi hai girato ed effettivamente li il problema non si presenta 🤷🏻‍♂️🤔
eppure il file è come indicato nella modifica https://github.com/devcode-it/openstamanager/commit/1492892cfef9bc01a356930ce0092c297b6b40e9

**Comment by Pek5892** [comment]
potreste provare a resettare la cache ed eventualmente aprire un ticket nel caso il problema non si risolva?

**Comment by sajotrei** [comment]
allora ho rifatto il giro
pulito tutto ecc..

il problema si pretesta anche con la demo 2449 su tutti i browser, meno su safari.
ho provato anche con risoluzioni differenti...

l'unico modo per vedere i tasti è portare lo zoom al 90%

comunque sia mi sembra che sia legato alla tabella che non si adatta, ma rimane fissa

**Comment by Pek5892** [comment]
Ciao @sajotrei, potresti provare ad applicare questa fix? https://github.com/devcode-it/openstamanager/commit/686c9af24e11b590576665b7d63d88d4998d6db8

**Comment by sajotrei** [comment]
si ottimo!! ora la tabella si adatta automaticamente 
grazie.
