### ISSUE TITLE
ATTIVITA' - inserimento firma intervento

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#135]
In Anteprima e Firma, non viene visualizzato il form dove inserire Nome e Cognome di chi ha apposto la firma (gestionale aggiornato a ultimo commit)
![immagine](https://user-images.githubusercontent.com/34765237/35529104-50f1157a-0530-11e8-9666-2cd934dae869.png)

**Comment by Dasc3er** [comment]
Ho appena testato con la versione più recente e da me funziona:
![immagine](https://user-images.githubusercontent.com/15911489/35530016-192ff4f0-0533-11e8-874e-11fb9f438610.png)

**Comment by antonioscarpino** [comment]
Mmmmm boh, anche io aggiornato all'ultimo commit però mi da quell'errore.
Non riesco a capire perchè avendo la stessa versione a te funziona a me no.

**Comment by Dasc3er** [comment]
L'errore che viene mostrato nel tuo caso, sotto forma del codice HTML semplificato, sembra indicare che per qualche motivo il tag non è stato riconosciuto...
Effettivamente però si tratta di un problema strano.

Potresti indicare la versione di PHP in utilizzo?

**Comment by antonioscarpino** [comment]
Attualmente 5.6.
Provato con la 7.2 l'errore non c'è.
Strano i requisiti minimi se non sbaglio erano 5.6.
Boh misteri del php.

**Comment by antonioscarpino** [comment]
5.6.31

**Comment by Dasc3er** [comment]
@antonioscarpino Allora stiamo utilizzando la stessa identica versione PHP!
In generale, problemi di questa tipologia sono generati da un errore durante l'esecuzione della funzione **json_decode** nativa di PHP.

Se sei interessato ad approfondire il problema, potresti provare a confrontare l'input della funzione **decode** del file src/HTMLBuilder/HTMLBuilder.php con il relativo output.
La funzione in questione prende il formato HTML semplificato e lo interpreta nel formato JSON, restituendo un array con tutte le informazioni previste.

**Comment by antonioscarpino** [comment]
Ho effettuato il downgrade di php ritornando alla 5.6.31 (per capire quale fosse il problema della funzione decode da te suggerito) ma il problema è sparito.
Il mio pensiero è, che, gli hosting condivisi forniti dalle varie aziende (ovh, aruba, ecc.), appoggiandosi a degli script automatici per l'upgrade o il downgrade delle varie versioni di php, spesso provochino questo tipo di errori magari perchè lo script non è stato eseguito nel modo giusto.
Prova sta, che, come dicevo, eseguendo il downgrade della versione di php sullo stesso hosting (in questo caso OVH) e alla stessa versione che prima evidenziave il problema, adesso maggicamente non da più problemi.
