### ISSUE TITLE
Elenco segmenti vuoto

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1353]
Non riesco più a visulaizzare i record nel modulo segmenti
Dato che con gli ultimi aggiornamenti sono venuti fuori vari bug, la mia domanda è se esiste un modo per riparare il database, senza sovrascrivere i dati esistenti. 

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Segmenti
* Versione del progetto: 2.4.46 anche dopo aggiornamento a 2.4.48
* Versione PHP: 8.0.29
* Tipo di server: Aruba

**Comment by Pek5892** [comment]
Buongiorno @idraulicadueci,
dovrebbe provare a controllare la presenza di query personalizzate nel modulo viste, e verificare le query che hanno dato errore. Chiudo l'issue perchè è un problema legato all'installazione e non alla release, in caso abbia bisogno di assistenza per l'allineamento del database e voglia richiedere un nostro intervento ci può contattare da qui: https://openstamanager.com/contattaci/ Buona serata :)

**Comment by idraulicadueci** [comment]
Non ci sono personalizzazioni e se provo a inserire un nuovo segmento mi viene "Stai cercando di accedere ad un record eliminato o non presente." Nei log non ho nessuna informazione.
