### ISSUE TITLE
Ingranaggio ruota all'infinito dopo ricompilazione

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [devcode-it/openstamanager#1354]
Buongiorno,
dopo la ricompilazione utilizzando il comando:yarn run develop-OSM
il progetto viene compilato correttamente ma in caso di click su una sessione di un intervento,quando viene richiamata la funzione modificasessione(),viene richiamata la funzione salvaform e dopo rimane con l'ingranaggio che ruota.
se commento la parte await salvaForm("#edit-form", {}, button); non si blocca
ripristinando la cartella assets precedente funziona correttamente

**Comment by Pek5892** [comment]
Buongiorno @andreameneguzzoinfol,
che versione di php è stata utilizzata?

**Comment by andreameneguzzoinfol** [comment]
PHP Version 7.4.33

**Comment by andreameneguzzoinfol** [comment]
> Buongiorno @andreameneguzzoinfol, che versione di php è stata utilizzata? sembrerebbe più un problema legato alla sua installazione


PHP Version 7.4.33

**Comment by andreameneguzzoinfol** [comment]
Buongiorno,
si ci sono sicuramente delle modifiche al codice php ma non al codice javascript.

**Comment by Pek5892** [comment]
Senza aver accesso al codice non sapremmo come poter intervenire, chiudo l'issue in quanto non riproducibile e non verificabile. Per problemi su installazioni personalizzate consigliamo di consultare il nostro forum: https://forum.openstamanager.com/ o eventualmente di contattarci tramite apposito contact form per richiedere un intervento: https://openstamanager.com/contattaci/
