### ISSUE TITLE
Ordine elenco Azioni di gruppo in fatture

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1355]
## Comportamento richiesto

riteniamo sia utile ordinare le voci in azioni di gruppo in fatture attive.

o in **ordine alfabetico,** o quanto meno **quelle più utili e richieste in alto**, come ad esempio Coda di invio FE che si usa spesso.

![Screenshot 2023-09-15 alle 17 08 54](https://github.com/devcode-it/openstamanager/assets/75281007/50b2ad10-5765-4a5e-b7df-58ff05627ce4)

**Comment by Pek5892** [comment]
Introdotto con https://github.com/devcode-it/openstamanager/commit/539e4b16061620b9bdf883a00e5aa7d1302fb048 e https://github.com/devcode-it/openstamanager/commit/18d3eb4fbdcfa94676d5cd8dd476601f0bab2ee8
