### ISSUE TITLE
Attività - Proposta modifica stampa

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#136]
Se possibile vorrei proporre una piccola modifica al body.php relativo alla stampa degli interventi

```
// Dati cliente
echo '
    <tr>
        <td colspan=2>
            '.tr('Cliente').': <b>'.$c_ragionesociale.'</b>
        </td>';

// Codice fiscale o P.Iva

if ($c_piva != 0) {
	echo '
			<td colspan=2>
				'.tr('P.Iva').': <b>'.strtoupper($c_piva).'</b>
			</td>
		</tr>';
} else {
	echo '
			<td colspan=2>
				'.tr('C.F.').': <b>'.strtoupper($c_codicefiscale).'</b>
			</td>
		</tr>';
}
```
in modo che, se il cliente è un privato, quindi non possessore di partita iva, venga stampato il Codice Fiscale nel rapporto d'intervento.

**Comment by Dasc3er** [comment]
@antonioscarpino Potresti provare ad effettuare una Pull Request per non farci perdere di vista la proposta?

**Comment by loviuz** [comment]
Commit fatto, ho solo migliorato un if
