### ISSUE TITLE
Segmento SOLO DISPONIBILI articoli

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1360]
## Comportamento richiesto

selezionando SOLO DISPONIBILI filtra anche le q.tà negative.

![Screenshot 2023-09-19 alle 17 21 35](https://github.com/devcode-it/openstamanager/assets/75281007/d56b64b5-4fb3-4254-996b-407d0f1a26b3)

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno @sajotrei,
da release non ci risulta sia presente un segmento denominato "SOLO DISPONIBILI", è stato modificato da voi?

**Comment by sajotrei** [comment]
si è stato solo rinominato, ma il filtro è uguale

![Screenshot 2023-09-20 alle 09 52 01](https://github.com/devcode-it/openstamanager/assets/75281007/31dc7550-de9b-42b0-8e80-5a2bec89d26a)
![Screenshot 2023-09-20 alle 09 52 17](https://github.com/devcode-it/openstamanager/assets/75281007/3bf9ae3d-2c4a-4a1f-a01f-f94ebc1de436)

**Comment by Pek5892** [comment]
La query del modulo Articoli in viste corrisponde alla versione aggiornata della query? (Modificata l'ultima volta nella versione 2.4.38):
SELECT
     mg_articoli.id AS 'id', mg_articoli.descrizione AS 'Descrizione', mg_articoli.codice AS 'Codice', mg_articoli.barcode AS 'Barcode', mg_categorie.nome AS 'Categoria', sottocategorie.nome AS 'Sottocategoria', an_anagrafiche.ragione_sociale AS 'Fornitore', prezzo_acquisto AS 'Prezzo di acquisto', prezzo_vendita AS 'Prezzo di vendita', IF( co_iva.percentuale IS NOT NULL, (mg_articoli.prezzo_vendita + mg_articoli.prezzo_vendita * co_iva.percentuale / 100), mg_articoli.prezzo_vendita + mg_articoli.prezzo_vendita*iva.perc/100) AS 'Prezzo vendita ivato', qta AS 'Q.tà', IFNULL(a.qta_impegnata, 0) AS 'Q.tà impegnata', ordini_fornitore.qta_ordinata AS 'Q.tà ordinata', qta-IFNULL(a.qta_impegnata, 0) AS 'Q.tà disponibile', IF(mg_articoli.servizio, 'Sì', 'No') AS 'Servizio', IF(threshold_qta!=0, IF(mg_articoli.qta>threshold_qta, '#CCFFCC', '#FFCCEB'), '') AS '_bg_'
FROM
     `mg_articoli`
     LEFT JOIN an_anagrafiche ON mg_articoli.id_fornitore = an_anagrafiche.idanagrafica
     LEFT JOIN co_iva ON mg_articoli.idiva_vendita = co_iva.id
     LEFT JOIN (SELECT SUM(or_righe_ordini.qta - or_righe_ordini.qta_evasa) AS qta_impegnata, or_righe_ordini.idarticolo FROM or_righe_ordini INNER JOIN or_ordini ON or_righe_ordini.idordine = or_ordini.id INNER JOIN or_tipiordine ON or_ordini.idtipoordine = or_tipiordine.id INNER JOIN or_statiordine ON or_ordini.idstatoordine = or_statiordine.id WHERE or_tipiordine.dir = 'entrata' AND or_righe_ordini.confermato = 1 AND or_statiordine.impegnato = 1 GROUP BY idarticolo) a ON a.idarticolo = mg_articoli.id
     LEFT JOIN (SELECT SUM(or_righe_ordini.qta - or_righe_ordini.qta_evasa) AS qta_ordinata, or_righe_ordini.idarticolo FROM or_righe_ordini INNER JOIN or_ordini ON or_righe_ordini.idordine = or_ordini.id INNER JOIN or_tipiordine ON or_ordini.idtipoordine = or_tipiordine.id INNER JOIN or_statiordine ON or_ordini.idstatoordine = or_statiordine.id WHERE or_tipiordine.dir = 'uscita' AND or_righe_ordini.confermato = 1 AND or_statiordine.impegnato = 1
     GROUP BY idarticolo) ordini_fornitore ON ordini_fornitore.idarticolo = mg_articoli.id
     LEFT JOIN mg_categorie ON mg_articoli.id_categoria = mg_categorie.id
     LEFT JOIN mg_categorie AS sottocategorie ON mg_articoli.id_sottocategoria = sottocategorie.id
     LEFT JOIN (SELECT co_iva.percentuale AS perc, co_iva.id, zz_settings.nome FROM co_iva INNER JOIN zz_settings ON co_iva.id=zz_settings.valore)AS iva ON iva.nome= 'Iva predefinita'
WHERE
     1=1 AND(`mg_articoli`.`deleted_at`) IS NULL
HAVING
     2=2
ORDER BY
     `mg_articoli`.`descrizione`

**Comment by sajotrei** [comment]
si si è identica e non è mai stata modificata

![Screenshot 2023-09-21 alle 13 07 40](https://github.com/devcode-it/openstamanager/assets/75281007/243ee3f5-60bf-4478-90ae-384aae72aa59)

**Comment by Pek5892** [comment]
I valori inseriti nei campi del select sono gli stessi?
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/9958cf0d-d54d-423d-a4ba-eb165f54dba6)

**Comment by sajotrei** [comment]
Abbiamo questa

![Screenshot 2023-09-21 alle 17 01 15](https://github.com/devcode-it/openstamanager/assets/75281007/1ccff0a5-2ecb-48fb-9e38-0ab2f10cf19a)

**Comment by Pek5892** [comment]
Sono presenti dei campi diversi nel select.
In ogni caso questo filtro mostra semplicemente gli articoli disponibili nel senso di articoli che hanno una quantità impegnata minore di quella presente a magazzino, non evidenzia gli articoli che hanno disponibilità positive.
Per visualizzare gli articoli con quantità > 0 in magazzino è sufficiente modificare la query del segmento in
qta-IFNULL(a.qta_impegnata,0) > 0
o in
qta > 0
Chiudo l'issue perchè il funzionamento di questo filtro in release non presenta errori.
