### ISSUE TITLE
ATTIVITA' inserimento ORE DI VIAGGIO

### ISSUE THREAD

**Issue by 0kJ0** [devcode-it/openstamanager#1362]
## Comportamento richiesto

All'inserimento delle ore di viaggio impiegate dal tecnico, queste devono essere sommate ad altre eventualmente presenti

## Comportamento attuale

Non è possibile inserire le ore di viaggio necessarie per raggiungere il cantiere

## Possibile soluzione:

nella maschera di inserimento attività del tecnico, aggiungere il campo "ore di viaggio"

![Senza titolo](https://github.com/devcode-it/openstamanager/assets/145558082/4a64fea4-788e-45cf-925a-d7c4b6e658cb)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:

```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: attività
* Versione del progetto: tutte
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
se crei un tipo attività viaggio o trasferta ? 
puoi indicare il costo chilometrico o orario

![Screenshot 2023-09-25 alle 18 47 01](https://github.com/devcode-it/openstamanager/assets/75281007/d5e1f4f0-5628-43ca-9516-9c80d49dd399)

**Comment by Pek5892** [comment]
Chiudo perchè duplicata https://github.com/devcode-it/openstamanager/issues/1498
