### ISSUE TITLE
Aumento visibilità button: copia, elimina e confronta prezzi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1364]
i button **copia, elimina e confronta prezzi**, sono poco visibili 
suggeriamo di **ingrandirli** e magari anche **dargli un colore** per meglio identificarli.

qualcosa di simile a i button già presenti nelle righe, che sono coloranti.

![Screenshot 2023-09-25 alle 17 53 34](https://github.com/devcode-it/openstamanager/assets/75281007/7c62e9e0-d252-44e0-8a6e-5364264fdab6)

**Comment by Pek5892** [comment]
Ciao @sajotrei, i tasti sono volutamente diversi da quelli standard per evidenziare il loro funzionamento unicamente in fase di modifica righe, evidenziato anche dalla loro abilitazione solo nel momento in cui viene selezionata una riga.
Non è prevista attualmente la loro modifica.

**Comment by sajotrei** [comment]
risultano poco evidenti in generale.
se fosse possibile anche solo ingrandirli un po
