### ISSUE TITLE
Colore elenco Stato documento

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1366]
nei preventivi, contratti, attività, fatture, ddt

riteniamo sia utile introdurre il **colore dello stato** 

nel file  /edit.php

[ "type": "select", "label": "<?php echo tr('Stato'); ?>", "name": "idstato", "required": 1, "values": "query=SELECT id, descrizione, **_colore AS _bgcolor__** FROM co_statipreventivi", "value": "$idstato$", "class": "unblockable" ]}

_____
<img width="365" alt="Screenshot 2023-09-26 alle 15 56 56" src="https://github.com/devcode-it/openstamanager/assets/75281007/bce97bbc-11cf-4bac-8d89-afe4a475cbc0">

<img width="330" alt="Screenshot 2023-09-26 alle 16 00 48" src="https://github.com/devcode-it/openstamanager/assets/75281007/943da759-fd16-4c20-9d66-d0ee1ee78993">

**Comment by sajotrei** [comment]
**elenco Stato preventivo #1240**

**Comment by Pek5892** [comment]
Introdotto con commit https://github.com/devcode-it/openstamanager/commit/af2f79f8179463652678b1695708edea924e373b
