### ISSUE TITLE
Duplica Fattura su versione 2.4.49

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#1369]
## Comportamento richiesto

Duplicazione fattura
## Comportamento attuale

Compare un errore:

 Si è verificato un errore [uid: 10efe0d]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception Illuminate\Database\QueryException: "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'numero_esterno' cannot be null (SQL: insert into `co_documenti` (`numero`, `numero_esterno`, `data`, `data_competenza`, `data_registrazione`, `idanagrafica`, `idreferente`, `idagente`, `ref_documento`, `idcausalet`, `idspedizione`, `idporto`, `idaspettobeni`, `idvettore`, `n_colli`, `peso`, `volume`, `peso_manuale`, `volume_manuale`, `idsede_partenza`, `idsede_destinazione`, `idtipodocumento`, `idstatodocumento`, `idpagamento`, `id_banca_azienda`, `id_banca_controparte`, `idconto`, `idrivalsainps`, `idritenutaacconto`, `rivalsainps`, `iva_rivalsainps`, `ritenutaacconto`, `bollo`, `id_ritenuta_contributi`, `ritenuta_contributi`, `split_payment`, `is_fattura_conto_terzi`, `note`, `note_aggiuntive`, `buono_ordine`, `id_segment`, `progressivo_invio`, `tipo_resa`, `codice_stato_fe`, `data_stato_fe`, `descrizione_ricevuta_fe`, `addebita_bollo`, `id_riga_bollo`, `dati_aggiuntivi_fe`, `hook_send`, `id_dichiarazione_intento`, `id_ricevuta_principale`, `id_autofattura`, `is_ritenuta_pagata`, `sconto_finale`, `sconto_finale_percentuale`, `updated_at`, `created_at`) values (, ?, 2023-10-02 14:23:33, 2023-10-02 14:23:33, 2023-10-02 14:23:33, 398, ?, 0, ?, 0, 0, 0, 0, 0, 0, ?, ?, 0, 0, 0, 0, 2, 2, 113, 1, ?, 0, 0, 0, 0.000000, 0.000000, 0.000000, ?, ?, 0.000000, 0, 0, Canone 1 del contratto numero 11, , , 1, ?, ?, ?, ?, ?, 0, ?, ?, 0, ?, ?, ?, 0, 0.00000000, 0.00000000, 2023-10-02 14:23:33, 2023-10-02 14:23:33))" at /var/www/html/vendor/illuminate/database/Connection.php line 712
 Si è verificato un errore [uid: 10efe0d]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'numero_esterno' cannot be null (SQL: insert into `co_documenti` (`numero`, `numero_esterno`, `data`, `data_competenza`, `data_registrazione`, `idanagrafica`, `idreferente`, `idagente`, `ref_documento`, `idcausalet`, `idspedizione`, `idporto`, `idaspettobeni`, `idvettore`, `n_colli`, `peso`, `volume`, `peso_manuale`, `volume_manuale`, `idsede_partenza`, `idsede_destinazione`, `idtipodocumento`, `idstatodocumento`, `idpagamento`, `id_banca_azienda`, `id_banca_controparte`, `idconto`, `idrivalsainps`, `idritenutaacconto`, `rivalsainps`, `iva_rivalsainps`, `ritenutaacconto`, `bollo`, `id_ritenuta_contributi`, `ritenuta_contributi`, `split_payment`, `is_fattura_conto_terzi`, `note`, `note_aggiuntive`, `buono_ordine`, `id_segment`, `progressivo_invio`, `tipo_resa`, `codice_stato_fe`, `data_stato_fe`, `descrizione_ricevuta_fe`, `addebita_bollo`, `id_riga_bollo`, `dati_aggiuntivi_fe`, `hook_send`, `id_dichiarazione_intento`, `id_ricevuta_principale`, `id_autofattura`, `is_ritenuta_pagata`, `sconto_finale`, `sconto_finale_percentuale`, `updated_at`, `created_at`) values (, ?, 2023-10-02 14:23:33, 2023-10-02 14:23:33, 2023-10-02 14:23:33, 398, ?, 0, ?, 0, 0, 0, 0, 0, 0, ?, ?, 0, 0, 0, 0, 2, 2, 113, 1, ?, 0, 0, 0, 0.000000, 0.000000, 0.000000, ?, ?, 0.000000, 0, 0, Canone 1 del contratto numero 11, , , 1, ?, ?, ?, ?, ?, 0, ?, ?, 0, ?, ?, ?, 0, 0.00000000, 0.00000000, 2023-10-02 14:23:33, 2023-10-02 14:23:33))

## Possibile soluzione

ALTER TABLE co_documenti CHANGE numero_esterno numero_esterno VARCHAR(100) NOT NULL;

## Passi per riprodurre il comportamento

Basta duplicare un fattura

## Contesto

* Versione PHP: 7.4.27

**Comment by Pek5892** [comment]
Ciao @leonardocalabretta il problema è già stato risolto nel commit https://github.com/devcode-it/openstamanager/commit/af2f79f8179463652678b1695708edea924e373b

è sufficiente modificare il file modules/fatture/src/Fattura.php alla riga 704 in:
$new->numero_esterno = '';
