### ISSUE TITLE
Gestione storico azioni su attività

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#137]
Spesso, chi utilizza le attività in maniera intensiva, chiede di visualizzare uno storico con queste info:
 - chi ha assegnato l'attività, a chi e data/ora di questi eventi
 - data/ora dei cambi di stato

Secondo me, andrebbe creata un'ulteriore tabella con tutte queste note.
Se venisse utilizzato a pieno il flag "completato" di in_statiinterventi, sarebbe possibile un domani fare delle statistiche sui tempi di chiusura di un'attività, facendo una differenza fra le date dell'apertura e chiusura attività. Per rilevare la data di chiusura, si andrebbe a leggere la data del cambio stato, il cui stato ha flag "completato" a "true".

Attualmente non mi viene in mente altro, almeno per una prima versione.
Qualche altra proposta o osservazione?
Troppo per una 2.4, dato che ci sono già le email con gli account email?

**Comment by loviuz** [comment]
Diventerebbe una cosa simile a quello che si vede su github, all'incirca... :-)

**Comment by loviuz** [comment]
E' da generalizzare con zz_log, l'ho spostata nella prossima milestone, la 2.5

**Comment by Dasc3er** [comment]
Aggiunto il supporto al log delle operazioni attraverso la tabella **zz_operations**.
Per mantenere un numero sensato di azioni, quelle più vecchie di 30 giorni vengono rimosse attraverso le operazioni di login.

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager Aggiunta schermata di informazioni per gli utenti Amministratori.
Sulla sinistra vengono mostrate le operazioni generiche (_add, update, delete_) mentre sulla destra quelle specifiche del modulo.

![immagine](https://user-images.githubusercontent.com/15911489/42722960-463b48f6-8755-11e8-817f-12d4260a813c.png)

**Comment by Dasc3er** [comment]
La funzione è stata completata per la versione 2.4.2.

**Comment by loviuz** [comment]
:+1:
