### ISSUE TITLE
Stampe preventivi con raggruppamento delle righe dei preventivi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1370]
se si imposta in un preventivo con il raggruppamento delle righe (introdotto nella ver.2449)

**le varie stampe sono da verificare perchè risultano sballatte.**

inoltre suggeriamo di poter impostare il Subtotale ivato in grassetto.

vedi esempio preventivo  OFF_23/10 sulla demo ( https://demo.osmcloud.it/2449/editor.php?id_module=13&id_record=19#tab_ )

________
![Screenshot 2023-10-02 alle 16 41 52](https://github.com/devcode-it/openstamanager/assets/75281007/a63ad318-10e9-41e4-adbe-d0fe84f41c35)
________
![Screenshot 2023-10-02 alle 16 42 32](https://github.com/devcode-it/openstamanager/assets/75281007/fb89d45d-db8a-45ce-93db-0f372faeddb9)
________
![Screenshot 2023-10-02 alle 16 51 22](https://github.com/devcode-it/openstamanager/assets/75281007/aa0a1d97-ab0c-4470-b003-7aec2542a453)

* Modulo:
* Versione del progetto: 2.4.49
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Già risolto con commit: https://github.com/devcode-it/openstamanager/commit/f726d2629ccf0a008b2c613f7148b0441f1c6af1

**Comment by Pek5892** [comment]
Ciao @sajotrei,
i dati ci risultano corretti, che problemi hai riscontrato?

**Comment by sajotrei** [comment]
non il valore economico ma le stampe

Stampa preventivo (senza prezzi)
Stampa preventivo (solo totale)

**Comment by Pek5892** [comment]
Corretto con commit: https://github.com/devcode-it/openstamanager/commit/8fc61a8199caf234939a64d1a745d43627865724

**Comment by sajotrei** [comment]
ciao
con questa modifica rimane comunque sballata la stampa **Stampa preventivo (solo totale)**
