### ISSUE TITLE
Note interne

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1372]
nelle righe dei vari documenti, se si inserisce un link o del testo lungo nelle **note interne** 
sballa la visione 

cosa che non succede nel campo descrizione.

prova fatta sulla demo online 
https://demo.osmcloud.it/2449

<img width="1390" alt="Screenshot 2023-10-03 alle 15 25 41" src="https://github.com/devcode-it/openstamanager/assets/75281007/551f7fd6-4ac5-4ccd-892e-a5300b588e02">
<img width="1333" alt="Screenshot 2023-10-03 alle 15 25 58" src="https://github.com/devcode-it/openstamanager/assets/75281007/617dee0d-d7c4-4d79-af29-6b07ee939797">

* Modulo:
* Versione del progetto: 2.4.49
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto nelle versioni successive
