### ISSUE TITLE
sconto su riga

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1374]
si aggiunge una riga con sconto.

poi se la si deve correggere in-live non **prende la correzione**, si deve necessariamente fare la modifica con il tasto giallo laterale

![1 prima](https://github.com/devcode-it/openstamanager/assets/75281007/4c6cb5db-8d9e-4f21-a727-3ea60c9d4503)
![2 correzzione](https://github.com/devcode-it/openstamanager/assets/75281007/e1ed8ea5-3a15-4149-b091-fd410d0c2c7e)
![3 dopo](https://github.com/devcode-it/openstamanager/assets/75281007/1ca75772-f55b-4204-aa69-6c8e232c51b1)

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
con questa modifica sembra risolto 👍
https://github.com/devcode-it/openstamanager/commit/ab6c0f11c5b5b2bb8af921b9b3af23b95369880a

**Comment by Pek5892** [comment]
Ciao @sajotrei, è sufficiente cliccare fuori dalla cella per rendere effettive le modifiche

**Comment by sajotrei** [comment]
avevamo provato questa funzione **prima** che uscisse la 2.4.50 ( ovviamente modificando i rispettivi files )

dopo l'agg. alle 2.4.50, abbiamo verificato e ora sembra funzionare
