### ISSUE TITLE
Duplica attività

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1377]
## Comportamento richiesto

quando si duplica una attività non è possibile scegliere una nuova anagrafica, ti impone sempre la stessa anagrafica.

inoltre sarebbe più logico 
- rimuovere tutti i giorni della settimana e lasciare la scelta 
- disattivare Duplica allegati

______
![1](https://github.com/devcode-it/openstamanager/assets/75281007/32ed5ecd-b63a-4187-868c-8d529bde9ef6)
![2](https://github.com/devcode-it/openstamanager/assets/75281007/11128030-14de-410d-ae93-8416a05e7aca)
![3](https://github.com/devcode-it/openstamanager/assets/75281007/10c0d657-70bb-4ab2-8878-ab6000160210)

**Comment by sajotrei** [comment]
inoltre non sembra necessario il campo Data fine

**Comment by Pek5892** [comment]
L'attività viene duplicata così com'è, cambiando l'anagrafica da questa schermata non sarebbe possibile duplicare gli impianti e allegati. Il cambio anagrafica potrà essere fatto in un secondo momento.

**Comment by sajotrei** [comment]
ok va bene per l'anagrafica
ma per il resto come, i giorni e data fine, non servono a nulla, anche perchè non sembrano influire sul duplica.

**Comment by Pek5892** [comment]
I campi giorni e data fine servono per la generazione automatica delle sessioni dell'attività.
