### ISSUE TITLE
Stampa DDT da colonna Print

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1382]
## Comportamento richiesto

la colonna Print in DDT in Uscita prende sempre la stampa con prezzi e non considera il modello di stampa predefinito.

* Modulo: Magazzino DDT in Uscita
* Versione del progetto: 2.4.50
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei la stampa della colonna Print viene impostata dalle viste

**Comment by sajotrei** [comment]
Ciao Valentina, Si si certo è stata già impostata dalle viste

ma come ho indicato sopra, cliccando sulla icona stampante nella colonne in elenco DDT propone sempre la stampa con PREZI anche se la stampa predefinita è quella senza prezzi.

puoi verificare anche nella DEMO 2.4.50

______

![Screenshot 2023-10-11 alle 14 33 59](https://github.com/devcode-it/openstamanager/assets/75281007/4e1105fc-64d7-47ce-92e3-16d4dac02239)

**Comment by Pek5892** [comment]
Perchè nelle viste è stata impostata quella stampa, per cambiarla è necessario cambiarla dalle viste

**Comment by sajotrei** [comment]
ma non è modificabile il campo Query 🤷🏻‍♂️

**Comment by sajotrei** [comment]
e anche se interveniamo direttamente sul DB, cosa dovremmo indicare ?

![Screenshot 2023-10-11 alle 15 13 22](https://github.com/devcode-it/openstamanager/assets/75281007/bf63b9a8-5a9d-409f-ac55-5f51a1f581cb)


![Screenshot 2023-10-11 alle 15 14 10](https://github.com/devcode-it/openstamanager/assets/75281007/21826bf4-61be-4c07-b49d-130f8ded4776)

**Comment by Pek5892** [comment]
Il nome della stampa senza costi, ovvero:
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/c108ff73-6453-4779-bb5a-6cc21a29f7d0)
nella tabella corretta che è zz_views, nel campo _print_
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/062a6248-269a-4454-8cbd-8e22bd745a1e)

**Comment by sajotrei** [comment]
ok risolto con **'Ddt di vendita (senza costi)'**

peccato che si deve andare sul DB per fare questa modifica, sarebbe corretto prendesse la stampa predefinita
