### ISSUE TITLE
Categorie documenti

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1384]
## Comportamento richiesto

sotto Gestione documentale, **le categorie documenti rimangono visibili al di la dei gruppi inseriti in Gruppo abilitati.**

inoltre sarebbe utile avere 
- la colonna Gruppo abilitati, altrimenti si deve necessariamente aprire singolarmente ogni singola voce.
- nel plugin aggiungere le note interne

![Screenshot 2023-10-16 alle 16 53 33](https://github.com/devcode-it/openstamanager/assets/75281007/c8167e42-510e-4ace-8c83-5bb2c8822808)
![Screenshot 2023-10-16 alle 16 53 42](https://github.com/devcode-it/openstamanager/assets/75281007/57278b24-7c49-44bc-9786-5f6aba3bbbd5)

* Modulo:
* Versione del progetto:2.4.50
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
@sajotrei in release non è infatti presente l'accesso ai gruppi in gestione documentale

**Comment by sajotrei** [comment]
si si volevo dire utenti e permessi 😅
comunque sia abbiamo fatto un test su una installazione pulita e il problema si presenta con alcune cartelle.

**Comment by sajotrei** [comment]
**_chi può aiutarmi a inserire la Query corretta ?_** 🙏🏻😅


_________
<img width="1290" alt="Screenshot 2023-12-25 alle 13 00 39" src="https://github.com/devcode-it/openstamanager/assets/75281007/768a95c8-15ff-4aa3-8560-3b00db862545">

**Comment by sajotrei** [comment]
è possibile risolvere questo problema?

**Comment by sajotrei** [comment]
grazie! 🙏🏻
