### ISSUE TITLE
Variabile email in template Anagrafica

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1387]
## Comportamento richiesto

se si crea un template email associato al modulo anagrafica
non rileva la mail del cliente associato.

_____
<img width="727" alt="Screenshot 2023-10-23 alle 19 02 51" src="https://github.com/devcode-it/openstamanager/assets/75281007/1876e895-0a77-4b59-8d46-d7700c9f1b84">
<img width="830" alt="Screenshot 2023-10-23 alle 19 03 31" src="https://github.com/devcode-it/openstamanager/assets/75281007/27b97073-2e7e-42ab-b89f-63729c3f7dfb">

![2](https://github.com/devcode-it/openstamanager/assets/75281007/0238f3e1-b4ee-4da6-ae0a-f8b691210f95)

* Modulo: Anagrafica
* Versione del progetto: 2.4.50
* Versione PHP:
* Tipo di server:

**Comment by sajotrei** [comment]
Così funziona, ma và verificata la correttezza.

![Screenshot 2023-10-23 alle 19 17 43](https://github.com/devcode-it/openstamanager/assets/75281007/cc7dd756-9c72-4923-a812-860c03f1cff8)

**Comment by lucasalva87** [comment]
Ciao @sajotrei se vuoi contribuire al software con del codice ti suggerisco di effettuare delle pull request. 
In questo modo poi figurerai anche tra i contributori.
