### ISSUE TITLE
BUG errore mappa in creazione attività 

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1388]
## Comportamento richiesto

nel creare una attività se si associa un impianto restituisce un errore mappa 
vedi nella demo 
https://demo.osmcloud.it/2450/

____
![Screenshot 2023-10-25 alle 18 44 11](https://github.com/devcode-it/openstamanager/assets/75281007/a1bc8abd-4637-4c6f-ad71-44fc6bc83503)
![Screenshot 2023-10-25 alle 18 44 18](https://github.com/devcode-it/openstamanager/assets/75281007/0893b405-2786-4620-a809-a066219ed0b2)
![Screenshot 2023-10-25 alle 18 44 43](https://github.com/devcode-it/openstamanager/assets/75281007/d3ea8054-1dc2-44f5-b681-8a925a36f9eb)

* Modulo:
* Versione del progetto: 2.4.50
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei,
non riusciamo a replicare l'errore in demo.

**Comment by sajotrei** [comment]
ho riprovato ora sulla demo 2.4.51 si presenta ancora 

è sufficiente creare una attività, cercare la anagrafica Cliente Demo ( che ha la posizione indirizzo salvato ) 
poi espandere la voce Posizione e il sistema fornisce l'errore sopra indicato, dovrete indicare la posizione associata al cliente.

**Comment by Pek5892** [comment]
Errore non presente a partire dalla versione 2.5.7 del gestionale

**Comment by sajotrei** [comment]
Ciao Valentina, lo scherzo lo fa ancora anche sulla 2.5.7 e la 2.6
ovviamente l'indirizzo è valorizzato e valido.

![Screenshot 2024-12-05 alle 12 11 53](https://github.com/user-attachments/assets/f4e4948d-96a1-48b7-8ce5-f1a3886f6e4d)

**Comment by Pek5892** [comment]
Buongiorno @sajotrei, non siamo riusciti a replicare l'errore, potrebbe provare nella demo pubblica?

**Comment by sajotrei** [comment]
@Pek5892 ho provato su una installazione pulita 
quali sono le credenziali della demo ?  https://demo.osmbusiness.it/index.php

**Comment by Pek5892** [comment]
@sajotrei quelle inserite di default, dovrei aver trovato come riprodurre il problema

**Comment by sajotrei** [comment]
sulla demo, ho aperto il cliente Apple che ha valorizzato l'indirizzo e creo una attività 

![Screenshot 2024-12-06 alle 15 20 14](https://github.com/user-attachments/assets/7ddffad5-f47b-4e07-a77f-2a074abe6bfd)

**Comment by Pek5892** [comment]
Abbiamo apportato una miglioria alla funzionalità
