### ISSUE TITLE
BUG: Stampa fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#1394]
## Comportamento attuale

Le righe della fattura si sovrappongono sulla tabella di riepilogo IVA, Il problema si presenta quando si crea una fattura da un preventivo, esattamente quando le righe superano il limite di fine pagina. Per essere sicuro ho provato a replicare il problema sulla demo online (vedere fattura n. 0043/2023). 

* Modulo: FATTURE
* Versione del progetto: 2.4.51

**Comment by marcus905** [comment]
Confermo che la stessa cosa accade quando ci sono note piu' lunghe di 10 righe, in alcuni casi anche meno se ci sono righe con descrizione lunga.

Vedi fattura su demo datata 14 novembre

**Comment by Pek5892** [comment]
Template dei documenti migliorati nella versione 2.5.4
