### ISSUE TITLE
(BUG) filtro trimestri in liquidazione iva

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1395]
in Stampa liquidazione IVA non non considera la selezione dei filtri trimestrali ma solo se si inserisce manualmente il periodo.

- stampe contabili
- Registri IVA
- Stampa liquidazione IVA

vedi demo https://demo.osmcloud.it/2451

<img width="1423" alt="Screenshot 2023-11-16 alle 21 15 57" src="https://github.com/devcode-it/openstamanager/assets/75281007/e44a8b16-931d-4274-8551-2cc2cf1bbcc3">

**Comment by sajotrei** [comment]
abbiamo notato che lo stesso discorso si presenta anche,

- Stampa registro IVA vendite
- Stampa scadenzario

**Comment by Pek5892** [comment]
Ciao @sajotrei,
non riusciamo a riprodurre il problema indicato, neanche in demo pubblica.

**Comment by sajotrei** [comment]
semplicemente se il periodo è manuale e si imposta una data inizio e fine la stampa riporta il periodo indicato
se invece si seleziona il periodo in elenco 3° Trimestre 2023 la stampa riporta comunque tutto l'anno.




<img width="1423" alt="1" src="https://github.com/devcode-it/openstamanager/assets/75281007/684d5788-2641-4194-bc52-18961c0b5bbe">
<img width="1423" alt="2" src="https://github.com/devcode-it/openstamanager/assets/75281007/c4c2a674-e593-437b-9acf-2465f68017bb">
<img width="1423" alt="3" src="https://github.com/devcode-it/openstamanager/assets/75281007/11fee6fa-e38f-479a-877d-f89a0c62b577">
<img width="1423" alt="4" src="https://github.com/devcode-it/openstamanager/assets/75281007/734e8710-1d6d-4c37-a2fd-4ab2dac441cc">

**Comment by Pek5892** [comment]
https://www.awesomescreenshot.com/video/22551056?key=4f05c6dcf7d2b2b8fea383a42ebb980a
potrebbe essere il tuo browser che blocca i js che cambiano il valore dei campi data? dai tuoi screenshot non sembra vengano eseguiti
