### ISSUE TITLE
Articolo con quantita 0 blocca il preventivo

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1396]
## Comportamento richiesto

un articolo con quantita 0 venga indicato su un preventivo/fattura con prezzo unitario riportato ma quantita e prezzo finale 0

## Comportamento attuale

al momento un articolo con quantita 0 blocca l'intera schermata preventivo/fattura in maniera irrecuperabile

## Possibile soluzione

nessuna, devo indagare

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. creazione di un preventivo
2. aggiunta di un articolo con quantita 0
3. tabella articoli viene sostituita da uno spinner

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: fatture/preventivi
* Versione del progetto: 2.4.51
* Versione PHP: 8.0
* Tipo di server: Aruba

**Comment by Pek5892** [comment]
Buongiorno @marcus905, siamo riusciti a riprodurre il problema solo con i preventivi, e non con le fatture di vendita
