### ISSUE TITLE
Valori di Vendita al Banco in Statistiche

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1397]
## Comportamento richiesto

Ciao Abbiamo notato che in Statiche il sistema non tiene conto dei valori mensili Vendite al Banco, ma solo delle fatture attive/passive

**Comment by Pek5892** [comment]
Ciao @sajotrei,
questa funzionalità è stata introdotta da https://github.com/devcode-it/openstamanager/commit/66af1b5521e898ec9194f3b8915db92d096fca35
