### ISSUE TITLE
Problema dichiarazione intento

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#1398]
## Comportamento richiesto

In fase di creazione nuova fattura, dovrebbe riportare la dichiarazione d'intento con plafond disponibile se c'è e comunque non dovrebbe riportare una dichiarazione che è già stata utilizzata al 100%.

## Comportamento attuale

Attualmente, per via della riga 195 del file /modules/fatture/src/Fattura.php riporta le dichiarazione già utilizzate.

## Possibile soluzione

Credo che una possibile soluzione sia quella di sostituire il codice
```php
->where('massimale', '>', 'totale')
```
col codice
```php
->whereColumn('massimale', '>', 'totale')
```

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.Inserire una dichiarazione d'intento in anagrafica
2.Utilizzarla al 100%
3.Inserire una seconda dichiarazione d'intento
4.Creare una nuova fattura per quell'anagrafica

**Comment by Pek5892** [comment]
La gestione della dichiarazione d'intento è stata migliorata nelle ultime versioni (2.5.4)
