### ISSUE TITLE
Anagrafica nei movimenti articolo

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1399]
## Comportamento richiesto

nei movimenti nel plugin articoli sarebbe molto utile aggiungere la colonna anagrafica che riporta il cliente / fornitore in base al documento associato.

<img width="1944" alt="Screenshot 2023-12-05 alle 20 06 15" src="https://github.com/devcode-it/openstamanager/assets/75281007/38bbe471-e4e6-4508-a210-90fc8d7342ba">

**Comment by Pek5892** [comment]
Da qualche versione è presente il campo **Controparte**.
