### ISSUE TITLE
Osservazioni su Fatture

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#14]
Ciao, ho trovato 2 cosette che non mi convincono sul modulo Fatture, allora le segnalo.
La prima è la seguente: creo una fattura di acquisto con 3 scadenze per esempio. Se pago una scadenza metterò parzialmente pagato sulla fattura. A quel punto scompaiono le scadenze, anche se non sono state tutte pagate.
La seconda è: carico un file come allegato alla fattura, poi se provo a scaricarlo non mantiene il nome originale con cui l'ho caricato, ma prende un nome casuale (del file temporaneo immagino). Nel senso che viene salvato nella cartella files con il nome temporaneo casuale (nella 2.2 salvava il nome originale).
Non so se sono 2 intended functionality o piccoli problemi, intanto le inserisco, poi al limite chiudete la issue..

**Comment by Dasc3er** [comment]
@ldanese83 La rinominazione dei file in modo casuale è stata prevista a partire dalla versione 2.3 per evitare problemi relativi alla sicurezza dell'upload. Questo comunque non dovrebbe influenzare l'esperienza di navigazione, poiché il progetto fornisce i link automaticamente impostati e corretti.

Quanto alla tua prima domanda, il progetto si basa sullo stato "Emessa" per le fatture al fine di determinare le eventuali scadenze di pagamento.
Consiglierei di chiedere nel [forum ufficiale](www.openstamanager.com/forum/) per maggiori chiarimenti o per proporre l'ampliamento delle funzionalità di OpenSTAManager, poichè già predisposto per queste operazioni (credo che la repository sia intesa come più tecnica).

Per sicurezza sentirei anche @loviuz sugli obiettivi prefissati con l'utilizzo di Github.

Ancora grazie per le segnalazioni!

**Comment by fpsoftware** [comment]
Riguardo la seconda: possiamo lasciare il file fisico con nome casuale, e sul database salviamo il nome originale, poi basta aggiungere un secondo comando per il download "scarica con nome originale", in questo modo accontentiamo tutti!

**Comment by fpsoftware** [comment]
Riguardo la prima, sembra un bug, da verificare

**Comment by loviuz** [comment]
@fpsoftware, sicuro di voler scaricare il file con nome casuale? se sono allegati di impianti, ad esempio, tipo una scheda tecnica, magari da inviare al cliente, è brutto poi mandare il file con nome casuale, meglio il nome originale...
@Dasc3er, perché dici che è un problema di sicurezza? se il file viene scaricato passando tramite un file php, si può mettere un .htaccess su /files/ in modo che non si possa accedere direttamente al file anche se si conosce la path. che ne dici?

**Comment by Dasc3er** [comment]
@loviuz Avevamo discusso con @fpsoftware che, effettivamente, se si caricavano file con nomi simili (come è probabile) e magari semplicemente diversi per un numero, tutti gli utenti potevano vederli anche se non erano relativi a elementi su cui avevano i permessi di accesso (semplicemente modificando il nome sull'URL).

Certamente si può fare in modo di avere un pulsante download che permette di scaricarli con il nome originale...
Al momento, sul file **.htacces** c'è già un controllo per evitare l'esecuzione di file PHP e di elencare tutti i contenuti, ma mettendo un blocco nella cartella poi i file non risultano utilizzabili (il caricamento avviene tramite PHP, ma la visualizzazione da parte dell'utente è gestita attraverso l'apertura diretta).

@fpsoftware Sul file actions.php c'è un controllo diretto sullo stato "Emessa", perchè sarebbe sbagliato?
```
// Elimino la scadenza e tutti i movimenti, poi se la fattura è emessa le ricalcolo
if ($rs[0]['descrizione'] == 'Bozza') {
    elimina_scadenza($id_record);
    elimina_movimento($id_record, 0);
    elimina_movimento($id_record, 1);
} elseif ($rs[0]['descrizione'] == 'Emessa') {
    elimina_scadenza($id_record);
    elimina_movimento($id_record, 0);
}

// Se la fattura è in stato "Emessa" posso inserirla in scadenziario e aprire il mastrino cliente
if ($rs[0]['descrizione'] == 'Emessa') {
    aggiungi_scadenza($id_record, $pagamento);
    aggiungi_movimento($id_record, $dir);
}
```
