### ISSUE TITLE
Miglioria: configurabilità righe vuote grafiche in fattura e colore

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1400]
## Comportamento richiesto

Mi aspetto sia configurabile l'abilitazione o meno delle righe vuote grafiche nelle tabelle dei documenti

## Comportamento attuale

Attualmente vengono generate le righe vuote in ogni caso con evidenti bug grafici come questo:
![image](https://github.com/devcode-it/openstamanager/assets/392762/67e48b80-2c35-4bf1-b7e8-1ff86218964d)
Rendendomi conto della difficolta nella gestione degli elementi e degli spazi nella stampa PDF, almeno questo potrebbe risolvere alcune problematiche.
Aggiungo che sarebbe comodo la stessa configurabilità relativamente al colore (che se si e' passati da alcune versioni diventa verde, mentre nella demo è grigio.

La demo non mostra righe vuote grafiche, stranamente.

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Creazione di una fattura con alcune righe con descrizione multilinea (nei test 5 righe con descrizione da 4 righe)
2. Stampare la fattura

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: fatture
* Versione del progetto: 2.4.51
* Versione PHP: 8.0
* Tipo di server: Apache (Aruba)

**Comment by sajotrei** [comment]
Per il colore prova a verificare il seguente file  /templates/base/**style.css**

riga 49 :     **background-color: #eee;**

**Comment by marcus905** [comment]
> si questa anomalia si è presentata con la 2.4.50 o 51, che già qualcuno ha segnalato.
> 
> noi per tamponare al momento quando si presenta il problema, modifichiamo il body del template in questione...
> 
> ![Screenshot 2023-12-06 alle 18 06 38](https://private-user-images.githubusercontent.com/75281007/288488793-a4ddc878-25fa-40f5-b885-38ead967f421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODM4NjksIm5iZiI6MTcwMjM4MzU2OSwicGF0aCI6Ii83NTI4MTAwNy8yODg0ODg3OTMtYTRkZGM4NzgtMjVmYS00MGY1LWI4ODUtMzhlYWQ5NjdmNDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEyMTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MDc5Y2I1MDk0NDNlMDI3Y2MxYjNiYzI0M2VmOWI0MTJkMDZjOWFkNGU3NDFkOTNlNGEwZmY0YzIzZTU5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHy7QVKYcp_IhHhBc_Pxx_XzKTHhVYTHqG0b7-awzZs)

E avete dei puntatori per rendere quel 6 un parametro nelle impostazioni? Per il colore essendo CSS la vedo più difficile :/

**Comment by Pek5892** [comment]
Migliorata la generazione delle righe vuote nella versione 2.5.4, il colore non è attualmente gestito.

**Comment by Pek5892** [comment]
https://github.com/devcode-it/openstamanager/issues/1149
