### ISSUE TITLE
(BUG) Errore Ordine Cliente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1401]
## Comportamento richiesto

Errore nel creare e aprire un ordine cliente.

![Screenshot 2023-12-08 alle 15 37 13](https://github.com/devcode-it/openstamanager/assets/75281007/a656f665-fa43-438b-a638-ff994c52b771)

## Passi per riprodurre il comportamento

Aprire un ordine cliente

* Modulo: ORDINE CLIENTE
* Versione del progetto: **2.4.52**
* Versione PHP:
* Tipo di server:

**Comment by NicolaNext** [comment]
Io per ora ottengo un errore **chiudendo** un ordine, sia già creato che appena creato. E l'errore è sempre lo stesso
"syntax error, unexpected token "<"" at /var/www/gestione/prova/modules/ordini/plugins/ordini.consuntivo.php line 403

**Comment by Pek5892** [comment]
Risolto con commit: https://github.com/devcode-it/openstamanager/commit/e04785d53044a2851ba5232c27fa407eaa0fa061
