### ISSUE TITLE
Invio automatico avviso scadenza fattura

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1405]
## Comportamento richiesto

in impostazione/scadenzario, ora è possibile impostare un invio automatico per il sollecito.

sarebbe molto utile aggiungere anche una cosa simile per mandare automaticamente un **avviso di scadenza di pagamento**, con l'obiettivo evitare l'insoluto della scadenze Riba e/o bonifico

<img width="1641" alt="Screenshot 2023-12-21 alle 23 12 17" src="https://github.com/devcode-it/openstamanager/assets/75281007/055002e7-4164-424f-a414-59f7f26f1764">

**Comment by Pek5892** [comment]
Funzionalità attualmente presente in release
