### ISSUE TITLE
Firma interventi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1406]
## Comportamento richiesto

abbiamo attivato il sistema di firma Tavoletta Wacom, e la firma nel modulo accettazione funziona bene.

il problema si presenta nel far firmare i rapportini da smartphone/tablet, esce un errore.
tra l'altro **la tavoletta Wacom non è utilizzabile su Devices mobile quindi non avrebbe senso.**

<img width="454" alt="Screenshot 2023-12-23 alle 13 14 10" src="https://github.com/devcode-it/openstamanager/assets/75281007/0e133710-1efd-464a-be8c-89e87b03fa4a">

![IMG_8638](https://github.com/devcode-it/openstamanager/assets/75281007/103f9c20-9946-4e30-8b4d-0d0ffa382d1f)
![IMG_8637](https://github.com/devcode-it/openstamanager/assets/75281007/ff6181da-54f8-4449-9b81-f1c4c1e8eed8)

## Possibile soluzione

**permettere di impostare il _sistema di firma per modulo_**

ES. 
per modulo **interventi**, sistema **Base**
per modulo **accettazione**, Sistema **Wacom** 

## Passi per riprodurre il comportamento

* Modulo: Accettazione / Interventi 
* Versione del progetto: 2.4.52
* Versione PHP:
* Tipo di server:

**Comment by kenchu84** [comment]
Ciao, forse il problema e' la compatibilità browser con l'utilizzo di WebHID. Prova a scaricare Chrome sul dispositivo mobile e fai un test...

**Comment by sajotrei** [comment]
Ciao sì sì già fatto 
Stesso scherzo

sembra che sia sia la dimensione 
Se si allarga molto il quadrante della firma non si presenta 

riducendo lo zoom e mettendo lo smartphone il orizzontale 

![IMG_8682](https://github.com/devcode-it/openstamanager/assets/75281007/2b47dbb1-d229-4145-9bb1-a0e375ed7d90)

**Comment by Pek5892** [comment]
Risolto nelle versioni successive
