### ISSUE TITLE
Backup non compressi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1407]
sulla stessa macchina abbiamo due installazione OSM
1-  OSM di produzione personalizzata 
2-  OSM standard per dei tests

il backup sulla installazione standard funziona senza problemi.
in quella di produzione il backup non si comprime

se proviamo manualmente a creare il backup da questo errore.

non ci sono personalizzazioni nel modulo backup

<img width="1828" alt="Screenshot 2023-12-23 alle 16 00 46" src="https://github.com/devcode-it/openstamanager/assets/75281007/f23daf4f-bfb9-4f97-a39a-604de234a362">

<img width="1828" alt="Screenshot 2023-12-23 alle 16 00 57" src="https://github.com/devcode-it/openstamanager/assets/75281007/121a6fec-a0e3-43e8-b690-a74ac2554859">

* Modulo: BACKUP
* Versione del progetto: 2.4.52
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Ciao @sajotrei, lo spazio sul server è sufficiente? potresti provare a cambiare cartella di default per i backup impostandone una all'interno dell'installazione con i permessi corretti?

**Comment by sajotrei** [comment]
si già verificato ( Totale occupato: 3259.309 MB, su **100000 MB diponibili.** )
confermo che anche con cambio percorso bck rimane il problema

**Comment by Pek5892** [comment]
Potresti verificare che l'estensione ZIP sul server sia abilitata? Puoi verificarlo da impostazioni

**Comment by sajotrei** [comment]
![Screenshot 2023-12-27 alle 12 55 41](https://github.com/devcode-it/openstamanager/assets/75281007/fc91f392-3730-4159-a2d5-1bd962d9f32f)
