### ISSUE TITLE
Nascondere i riferimenti dei documenti nelle stampe (possibile bug)

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1411]
Nel menù impostazioni>generali c'è un controllo che dovrebbe permettermi di nascondere i riferimenti tra documenti nelle stampe (si chiama proprio "Riferimento dei documenti nelle stampe").
Ho la sensazione però che non funzioni, ho provato sia con la versioni 2.4.47 che con la 2.4.52 in quanto nella stampa di una fattura mi trovo tutti i riferimenti a partire dal preventivo.
Peggio ancora, i riferimenti me li ritrovo tutti anche nella fattura elettronica e mal impaginati (manca un <br>alla fine della descrizione articolo quindi il riferimento ai documenti è attaccato alla fine della descrizione articolo stessa)
Non posso fare prove sulla demo perchè non c'è la possibilità di modificare le impostazioni.

Passi per riprodurre il problema

1.crea un preventivo
2.convertilo in ordine
3.converti l'ordine in fattura
4.stampa la fattura

Aggiornamento 31/12/2023 - Ho sostituito le foto con altre più chiare

Stampa fattura (dettaglio)
![3](https://github.com/devcode-it/openstamanager/assets/102433047/cb252369-b10f-404f-853e-950e2cfbf00d)

Stampa fattura elettronica (dettaglio)
![4](https://github.com/devcode-it/openstamanager/assets/102433047/f33398cc-e266-45d1-887a-5d134b16375f)

**Comment by Pek5892** [comment]
Buongiorno @NicolaNext,
questo sarà corretto nella versione 2.4.53 in release.

**Comment by NicolaNext** [comment]
Buongiorno Valentina, sto provando la versione aggiornata e, effettivamente, ora posso raggruppare i riferimenti ai documenti. Ma se io proprio non li volessi vedere? Non mi risulta ci sia nulla del genere.

**Comment by Pek5892** [comment]
Buongiorno @NicolaNext , l'impostazione è **Aggiungi riferimenti tra documenti**.
Se disabilitata, all'evasione delle righe di un documento in fattura o in un altro documento, non viene riportato il riferimento al documento originale. Questo non ha però effetto retroattivo sulle righe già evase.

**Comment by NicolaNext** [comment]
Ma se io volessi conservare i riferimenti ma non vederli nel tempate di stampa?
Inoltre il problema nel file XML rimane, il riferimento viene scritto immediatamente dopo l'articolo senza neanche lo spazio (vedi foto più su)
