### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1412]
## Comportamento richiesto

la colonna di destra ( elimina/invia ) viene nascosto dal menu plugin
sia nel riquadro destinatari della **lista** contatti che nelle **newsletter** 

![Screenshot 2023-12-31 alle 14 11 01](https://github.com/devcode-it/openstamanager/assets/75281007/86702c03-042f-4fd2-8839-fc169fd9e796)
![Screenshot 2023-12-31 alle 14 11 06](https://github.com/devcode-it/openstamanager/assets/75281007/42eebf5d-ade4-4f9f-960f-a37e40570a10)

* Modulo: Gestione email
* Versione del progetto: 2.4.52
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Problema non più presente nella versione 2.5.4
