### ISSUE TITLE
Colonna scadenza in fatture vendita e acquisti

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1416]
## Comportamento richiesto

sarebbe utile avere la **colonna scadenza in elenco fatture Attive e Passive**

abbiamo provato a inserirla in viste, ma non funziona, eppure la query sembra corretta.

<img width="1502" alt="Screenshot 2024-01-03 alle 12 48 20" src="https://github.com/devcode-it/openstamanager/assets/75281007/2ce32322-9e0f-4cca-831c-ea088b01569d">

![Screenshot 2024-01-03 alle 12 48 36](https://github.com/devcode-it/openstamanager/assets/75281007/a8191e22-f861-4052-af38-677fa931b71b)

**Comment by Pek5892** [comment]
Ciao @sajotrei, 
la query è errata, per testarla ti è sufficiente provare a lanciarla a database. Per ora la colonna scadenze è stata evitata, potendo avere le fatture più scadenze diverse e non necessariamente un'unica scadenza.

**Comment by sajotrei** [comment]
magari sarebbe utile indicare almeno la **prima** scadenza 
comunque ok
grazie
