### ISSUE TITLE
Importazione articoli, fornitore predefinito si moltiplica

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1419]
Ho appena terminato una installazione ex novo della versione 2.4.53 per verificare un problema che mi si è presentato in fase importazione articoli.
Il problema si presenta tale e quale anche con la installazione pulita.
Se importo un certo numero di articoli (oltre 300) incluso il listino fornitore (un solo fornitore) gli articoli vengono importati correttamente ma, per ogni articolo viene creato un nuovo id fornitore col risultato che in anagrafica ho centinaia di fornitori identici.
Ho fatto questa prova perché il problema mi si è presentato in fase di importazione per la versione 2.4.52. Dall'8 gennaio l'idea era di abbandonare il vecchio gestionale ma a questo punto non so...

Zero personalizzazioni, zero modifiche, il problema si presenta sempre.
Ho provato sulla demo con un set ridotto di articoli e il problema non si è presentato (al che uno si sente anche scemo).
Nessuno ha mai avuto questo tipo di problema?

PHP (8.0.28 )
Versione MySQL: 10.5.18-MariaDB-0+deb11u1 via estensione PHP MySQLi

**Comment by NicolaNext** [comment]
Aggiungo dopo numerose prove (ho pensato fosse un problema della versione MySQL)
1 - Installazione pulita come sopra (virtual server Aruba e database localhost) e importazione di un backup dei dati: il problema **si presenta**
2 - Stessa installazione (virtual server Aruba) con file config modificato per puntare ad un database MySQL 5.7.32 vuoto (MySQL Aruba), quindi reinstallazione completa del database e importazione dello stesso backup: il problema **si presenta** ancora
3 - Installazione ex novo (hosting Aruba) e database MySQL 5.7.32 vuoto (MySQL Aruba), importazione del solito backup prima di caricare il magazzino, il problema **non si presenta**
4 - Nuova installazione ex novo per scrupolo estremo (virtual server Aruba e database localhost) e solita importazione: il problema **non si presenta** (condizioni identiche al punto 1)

5 - Backup dell'installazione del punto 3 caricato su installazione precedente il punto 1 (quella originale 2.4.52 con conseguente aggiornamento "indietro" del database) e successivo riaggiornamento a 2.4.53, il problema **non si presenta**

Sinceramente sono perplesso, il backup che importavo era sempre lo stesso ma il problema a volte non si presentava a volte sì, in ogni caso con il punto 5 ho risolto e da lunedì partiamo con Open Sta Manager, con le dita incrociate.

**Comment by loviuz** [comment]
Ciao @NicolaNext, con PHP 8.0 avevamo avuto un problema di "duplicazione" record in prima nota, poi risolto. Hai modo di provare con PHP 7.4? Potrebbe essere un problema simile legato alla versione di PHP. Abbiamo iniziato da poco la migrazione a PHP 8.1 perché la 8.0 non è più aggiornata dal team di PHP da fine novembre.

**Comment by NicolaNext** [comment]
Farò un po' di prove, è una questione abbastanza spinosa per me, ci ho lavorato 2 giorni con numerose installazioni di test.
Mi piacerebbe più che altro trovare un fattore realmente discriminante perché ad oggi sembra che sia abbastanza casuale.

**Comment by Pek5892** [comment]
Buongiorno @NicolaNext, potrebbe verificare di aver formattato il file come indicato nella documentazione?
https://docs.openstamanager.com/v/2.4.53/openstamanager/modules/strumenti/import/import-articoli
ovvero che il campo Partita IVA sia mappato, o in alternativa i campi id_fornitore o anagrafica_listino?
Nelle ultime versioni abbiamo introdotto una modifica che esegue il controllo sulla Partita IVA per associare l'anagrafica corrispondente, può testarlo utilizzando il file di esempio.

**Comment by NicolaNext** [comment]
Buonasera Valentina,
farò un po' di prove nel week end, adesso abbiamo riaperto l'attività con tanto di nuovo gestionale e, come prevedibile, sto facendo i salti mortali per far funzionare tutto, collaboratori compresi. L'importazione alla fine l'ho fatta con qualche espediente quindi il problema è diventato puramente accademico.

Il CSV che ho utilizzato era quello precedente senza partita iva (non ne sono certo ma non ricordo che nei vari changelog fosse specificato che il CSV era stato esteso).
Comunque rimane la casualità dell'errore, ieri pomeriggio ho importato 3 articoli per 8 volte e in 3 casi (non consecutivi) l'anagrafica si è moltiplicata mentre in 5 casi no. Le condizioni erano sempre identiche, gestionale ripristinato da backup e importazione dello stesso CSV.

**Comment by Pek5892** [comment]
Consigliamo di utilizzare la partita IVA, o in ogni caso la versione 2.4.53 dove il problema non si presenta.

**Comment by NicolaNext** [comment]
Le 8 importazioni di ieri pomeriggio le ho provate proprio sulla versione 2.4.53

**Comment by Pek5892** [comment]
Potrebbe fornirci un file csv d'esempio nel quale il problema si verifica in modo da poterlo testare?

**Comment by NicolaNext** [comment]
Buonasera Valentina,
questo fine settimana provo a guardare, l'importazione l'ho fatta a casa a cavallo di Natale, dovrei però avere conservato tutto.

**Comment by NicolaNext** [comment]
Buongiorno Valentina,
sono riuscito a guardare solo oggi, mi scuso per il ritardo.
Purtroppo i file csv per l'importazione li ho generati da un file madre di excel e via via che li importavo devo averli cancellati.
Non escludo, tempo permettendo, di ricreare le stesse condizioni di fine anno e riprovare. Nel caso ti avviserò.
Questa questione mi sta molto a cuore visto il tempo che ci ho dedicato e, soprattutto, vista la totale casualità con cui si presentava l'errore.
Per quanto mi riguarda questa issue si può chiudere dato che non ho altri elementi da fornirvi.
