### ISSUE TITLE
Cambio ora e data in sessione intervento

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1422]
## Comportamento richiesto

se si cambia la data e/o l'ora in **Orario inizio** ci si aspetta che in **Ora fine** cambi la data o l'ora di conseguenza, magari tendo conto del valore impostato nel tipo di attività, es. 1h il sistema porterà la data fine di un'ora avanti.

invece rimane indietro creando una anomalia anche nel conteggio ore totali.

![1](https://github.com/devcode-it/openstamanager/assets/75281007/f4412945-85cd-4a44-82b9-5c0e1a66ec5c)

_____
inoltre **l'avviso** che il campo ore non è valorizzato **viene nascosto** 

![2](https://github.com/devcode-it/openstamanager/assets/75281007/2fa0dad6-fcb2-404f-b082-f91f3f422594)

* Modulo: interventi
* Versione del progetto: 2.4.53
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/6e31818c5304a3b55c2ccf011f560dc12dc51115
