### ISSUE TITLE
Errore invio mail da preventivi

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#1425]
## Comportamento richiesto

Invio mail da modulo Preventivi.
## Comportamento attuale

Vengono restituiti due errori:

 **Si è verificato un errore [uid: a2e9e63]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception BadMethodCallException: "Required parameter not passed: "refresh_token"" at /var/www/html/vendor/league/oauth2-client/src/Tool/RequiredParameterTrait.php line 35

 Si è verificato un errore [uid: a2e9e63]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Required parameter not passed: "refresh_token"**

![Capto_Capture 2024-01-10_05-01-47_PM](https://github.com/devcode-it/openstamanager/assets/757880/95add74f-90e0-4a07-960b-2fdad6695c98)

Ho configurato sul Gestionale l'account di Office 365 tramite l'Applicazione su azure ad che ha funzionato perfettamente prima dell'upgrade alla 2.4.53.

Per riprodurre il problema basta inviare un preventivo (ho provato solo con quello).

PHP 7.4.27

Grazie mille

**Comment by Pek5892** [comment]
Buongiorno @leonardocalabretta ,
effettuando una verifica dell'account smtp, la configurazione va a buon fine?

**Comment by leonardocalabretta** [comment]
No purtroppo fallisce
Sent from my iPhone

--

Leonardo Calabretta - IT Solutions Architet

 
  
    
  
 +39 0521 18 56 267 | +39 393 79 82 036 
 
 ***@***.*** 
 
 www.leonardocalabretta.com 
 
 
  

  
 
  
   
   
   
 
 
 
Il giorno 12 gen 2024, alle ore 16:10, Valentina ***@***.***> ha scritto:

﻿

Buongiorno @leonardocalabretta<https://github.com/leonardocalabretta> ,
effettuando una verifica dell'account smtp, la configurazione va a buon fine?

**Comment by Pek5892** [comment]
sembrerebbe un problema legato alla configurazione e non al gestionale, dovreste provare a correggerla seguendo la guida: https://docs.openstamanager.com/v/2.4.53/configurazioni/configurazione-oauth2#microsoft

**Comment by leonardocalabretta** [comment]
La configurazione originale però è stata fatta seguendo questa guida. E ha funzionato tutto fino alla 2.4.52.

--

Leonardo Calabretta - IT Solutions Architet

 
  
    
  
 +39 0521 18 56 267 | +39 393 79 82 036 
 
 ***@***.*** 
 
 www.leonardocalabretta.com 
 
 
  

  
 
  
   
   
   
 
 
 
Il giorno 12 gen 2024, alle ore 16:14, Valentina ***@***.***> ha scritto:



sembrerebbe un problema legato alla configurazione e non al gestionale, dovreste provare a correggerla seguendo la guida: https://docs.openstamanager.com/v/2.4.53/configurazioni/configurazione-oauth2#microsoft

**Comment by leonardocalabretta** [comment]
Purtroppo ho capito il problema. E' scaduta la Key il giorno prima di aggiornare.

Mi scuso ma la combinazione di eventi mi ha mandato fuori strada.
