### ISSUE TITLE
errore arrotondamento in lista fatture vendite

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1428]
Versione: 2.4.53 (Rf40d3ee4f)
PHP (7.4.33 )
Come era già successo precedentemente ed era stato corretto, come si evince dalle foto che ho mandato, il totale fattura è corretto, così come tutti gli altri dati riportati.
Mentre nel riepilogo fatture "modulo=14" sbaglia di un centesimo

![Schermata del 2024-01-22 11-48-39](https://github.com/devcode-it/openstamanager/assets/60449835/ec1fd8ee-7082-47da-99bc-663ac9ed7678)
![Schermata del 2024-01-22 11-48-23](https://github.com/devcode-it/openstamanager/assets/60449835/a1962051-7b12-45f7-8b2b-fcd54eeb4228)

**Comment by Pek5892** [comment]
Buongiorno @leo-spa,
risolto con commit: https://github.com/devcode-it/openstamanager/commit/2541aaec3a32dae32b8ada334ed3576b136c777f
