### ISSUE TITLE
Statistiche

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1430]
## Comportamento richiesto

sarebbe molto utile rivedere le statistiche, aggiungendo informazioni utili 
allego alcuni esempi come spunto ...

____________
![dashboard-controlla-andamento-azienda](https://github.com/devcode-it/openstamanager/assets/75281007/623e9bbf-ac71-4495-be3d-57847ba355ab)

<img width="1768" alt="statistiche OSM 1" src="https://github.com/devcode-it/openstamanager/assets/75281007/152a9e3b-5fa5-42c1-88ad-e38b42329284">

![Screenshot 2024-01-24 alle 13 58 28](https://github.com/devcode-it/openstamanager/assets/75281007/0a137a51-8c99-499e-8975-2f5c6e3d23b4)

* Modulo: **Statistiche**
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Per ampliare le statistiche visualizzate in OSM è disponibile il modulo aggiuntivo Business Intelligence
https://openstamanager.com/soluzioni/business_intelligence/
