### ISSUE TITLE
con fattura td17 non crea xml

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1431]
Versione: 2.4.53 (Rf40d3ee4f)
PHP (7.4.33 )

ho creato una fattura con il codice td17 e non crea l'xml, si prega di correggere l'errore grazie.
si stanno verificando errori che erano già stati corretti in passato :-(

**Comment by Pek5892** [comment]
Buongiorno @leo-spa ,
non riusciamo a riprodurre l'errore, potrebbe provare a riprodurre l'errore in demo pubblica così da poter testare la funzionalità?

**Comment by lepool** [comment]
Avevo notato che nelle nostre versioni vi è un problema con la l'apostrofo . Se c'è un'apostrofo  in una descrizione a noi non invia la fattura elettronica perche in quel caso l'xml risulta errato.  Magari nella nuova versione il problema si ripresenta altrove.

**Comment by leo-spa** [comment]
io ho provato anche con la demo, ed è molto strano perchè da esattamente lo stesso errore, se controllate nella sezione autofatture ho creato la fattura 12 (emessa)  l'xml "fattura elettronica" non è presente - a seguire quando creo l'autofattura in vendite che ho lasciato come bozza, non riporta nessun valore della fattura precedente e comunque non è presente l'allegato "fattura elettronica xml" che serve per l'nvio al sistema di interscambio. Questo problema non lo ha mai dato ed ho sempre inviato correttamente gli xml generati dal vostro programma

**Comment by Pek5892** [comment]
Buongiorno @leo-spa,
il gestionale non genera gli xml delle fatture di acquisto caricate manualmente, per questo non potete vedere l'xml nella fattura di acquisto numero 12.
Per quanto riguarda invece l'autofattura generata in vendite, il gestionale segnala che questi campi non sono stati valorizzati:
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/fb61727d-969b-46e0-bc25-a208250becc9)
andando a valorizzarli correttamente, l'xml viene correttamente generato, come per ogni fattura di vendita.

**Comment by leo-spa** [comment]
Il problema a me lo dà compilando tutti i campi e fino alla versione
precedente funzionava benissimo, no. Ho mai avuto problemi con le fatture
estere

Il ven 26 gen 2024, 14:59 Valentina ***@***.***> ha scritto:

**Comment by Pek5892** [comment]
come può verificare nel documento creato in demo pubblica, compilando i campi indicati ed emettendo la fattura, l'xml viene correttamente generato. Dovreste darci maggiori dettagli per riuscire a riprodurre il problema.

**Comment by leo-spa** [comment]
ho rifatto una nuova fattura e comunque l'errore rimane non carica i dati nella fattura vendita risulta completamente a 0 e va compilata manualmente, quando prima questa operazione era automatica
e ribadisco le fatture eu le ho sempre compilate manualmente e dil file fattura acquisti fino al 31 dicembre risultava sempre creato senza problemi.
la prima immagine è il vostro programma demo che non crea correttamente la fattura vendita
la seconda immagine è il vostro programma con una fattura eu acquisti che ho compilato l'anno scorso e il file xml era riportato correttamente in acquisto, in vendita veniva correttamente riportato e creato il file xml con l'unico rigo come deve essere


![Screenshot_20240126_163733](https://github.com/devcode-it/openstamanager/assets/60449835/d5faeae7-f677-4ca1-b287-132575ee8fe2)

![Screenshot_20240126_164340](https://github.com/devcode-it/openstamanager/assets/60449835/0cebbec2-c911-4971-b2c0-6d347d033c00)

**Comment by Pek5892** [comment]
Buongiorno,
la fattura di acquisto estera è stata registrata in modo scorretto: riporta essa infatti l'IVA. 
Per gestire le fatture con reverse charge misto abbiamo introdotto da qualche versione un controllo che va ad aggiungere l'IVA in fase di generazione autofattura solo per le righe che non la riportano già. 
Caricando quindi la fattura iniziale correttamente, non dovreste riscontrare problemi nella creazione delle autofatture, è tutto riportato sulla documentazione: https://docs.openstamanager.com/v/2.4.53/guide/esempi/autofattura#id-1-registrazione-fattura-estera

**Comment by leo-spa** [comment]
Mi scusi ma la normativa europea sulle fatture estere non prevede reverse
charge come dice lei la fattura deve essere compilata in maniera corretta
aggiungendo l'IVA italiana registrata con l'IVA italiana e riportata nel
registro IVA vendite esattamente a storno

Il Lun 29 Gen 2024, 10:22 Valentina ***@***.***> ha scritto:

**Comment by Pek5892** [comment]
Buongiorno,
intendo che per gestire anche le fatture sottoposte a reverse charge misto, il sistema di generazione delle autofatture è stato modificato in modo che non vada a calcolare l'IVA su righe in cui è già presente, dovete pertanto provvedere a compilare correttamente le righe della fattura di acquisto estera senza IVA, così come le ricevete, per avere il corretto calcolo automatico dell'IVA.

**Comment by leo-spa** [comment]
Le fatture estere td17 che si ricevono, vanno registra sia in acquisto che
in vendita aggiungendo l'IVA al 22%.  perché sia valida l'invio così come
disposto da agenzia entrate, la fattura acquisto, la devo integrare con
l'IVA ed invIarla. Ma va inviata la fattura acquisto e non vendita
compilando tutti i righi come da fattura ricevuta.

Il Lun 29 Gen 2024, 11:03 Valentina ***@***.***> ha scritto:

**Comment by leo-spa** [comment]
Questo è il programma ufficiale di agenzia entrate che si usa per inviare le fatture estere, come si evince quello che sta dicendo non è assolutamente corretto, vi chiedo di ripristinare la versione precedente che non ha mai dato nessun problema, altrimenti il vostro programma risulta praticamente inutile ai fini dell'invio di suddette fatture

![Schermata del 2024-01-29 11-09-56](https://github.com/devcode-it/openstamanager/assets/60449835/00da7e43-8e38-4f08-8c1e-4dc52d328930)

![Schermata del 2024-01-29 11-10-10](https://github.com/devcode-it/openstamanager/assets/60449835/1be69470-06e6-4e17-9c10-ab91d08fee39)

![Schermata del 2024-01-29 11-10-27](https://github.com/devcode-it/openstamanager/assets/60449835/5df08482-8f71-4d1c-bb7c-8acc6501d2f4)

**Comment by Pek5892** [comment]
La fattura viene attualmente integrata di IVA sia tra gli acquisti che tra le vendite, con l'emissione appunto dell'autofattura. Potrebbe seguire i passaggi descritti sulla guida per creare l'autofattura? ovvero:
1) registrazione della fattura estera **così come la si riceve, ovvero senza l'IVA riportata tra le righe**.
2) generazione dell'autofattura (tra le vendite) da questo documento e invio allo SDI
3) importazione dell'autofattura precedentemente inviata allo SDI (tra gli acquisti) .
**La fattura che viene inizialmente registrata tra gli acquisti non è la fattura integrativa ma la fattura di acquisto originale ricevuta dai fornitori esteri.**

**Comment by leo-spa** [comment]
Però devo poter allegare la fattura estera cartacea come aegato

Il Lun 29 Gen 2024, 11:48 Valentina ***@***.***> ha scritto:
