### ISSUE TITLE
Aggiornamento da 2.4.53 a 2.4.54 su Aruba fallisce

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1434]
## Comportamento richiesto

L'aggiornamento ha successo

## Comportamento attuale

L'aggiornamento fallisce

## Possibile soluzione

Bisogna applicare un'update della 2.4.35. Non sono sicuro perche non sia stato applicato precednetemente e perche il controllo integrita su DB non dia errori.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Aggiornare openstamanager su hosting aruba
2. Cliccare sul tasto aggiorna
3. in debug viene mostrato:
![image](https://github.com/devcode-it/openstamanager/assets/392762/7a25ee7e-d762-4697-a32a-020c983c3e97)

Tabella `zz_groups`:
```
CREATE TABLE `zz_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(50) NOT NULL,
  `editable` tinyint(1) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4
```

Eventuali log relativi (cartella **logs/**):
```
[2024-02-05 14:55:26] Logs.EMERGENCY: Aggiornamento fallito: ALTER TABLE `zz_groups` ADD `theme` VARCHAR(25) NULL AFTER `id_module_start` []
{"url":"/openstamanager/index.php?action=do_update&firstuse=false",...}
```

piu dettaglio da MySQL:
```
#1054 - Unknown column 'id_module_start' in 'zz_groups'
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: update
* Versione del progetto: 2.4.54
* Versione PHP: 8.0.30
* Tipo di server: Apache Aruba
PS: aggiungo che sembra sia stato disattivato da Aruba il mod_mime in apache. Per cosa è necessario? Possiamo farne a meno?

**Comment by lucasalva87** [comment]
Ciao @marcus905 nel file sql di update della 2.4.35 c'era questa query: 

```
-- Prima pagina per gruppo utenti 
ALTER TABLE `zz_groups` ADD `id_module_start` INT NULL AFTER `editable`; 
```

Guardando la tua tabella `zz_groups` sembra che invece non sia mai stata eseguita.

**Comment by marcus905** [comment]
Si, ho editato poco fa. Il controllo integrita non mostrava questa incongruenza.

**Comment by lucasalva87** [comment]
Quindi il problema è risolto?

Ho fatto una prova eliminando la colonna che a te mancava e il controllo del database visualizza:

![immagine](https://github.com/devcode-it/openstamanager/assets/30728163/3b8f128b-fb9a-4ee9-8d03-c18d514f2f6d)

**Comment by marcus905** [comment]
Si, problema risolto. MA quell'incongruenza a me non compare purtroppo, invece mi compare questa:
![image](https://github.com/devcode-it/openstamanager/assets/392762/d6a13024-889c-45fb-8fa9-2fc7ea5768fd)

nonostante:
CREATE TABLE `em_print_template` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_template` int(11) NOT NULL,
  `id_print` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `id_email` (`id_template`),
  KEY `id_print` (`id_print`),
  CONSTRAINT `em_print_template_ibfk_1` FOREIGN KEY (`id_template`) REFERENCES `em_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `em_print_template_ibfk_2` FOREIGN KEY (`id_print`) REFERENCES `zz_prints` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4

**Comment by cigo76** [comment]
quindi? Come risolvere? Mitrovo bloccato e non mi aggiorna il programma!!

**Comment by marcus905** [comment]
> quindi? Come risolvere? Mitrovo bloccato e non mi aggiorna il programma!!

Se hai avuto lo stesso problema mio, devi lanciare questa query

> ```
> -- Prima pagina per gruppo utenti 
> ALTER TABLE `zz_groups` ADD `id_module_start` INT NULL AFTER `editable`; 
> ```

su MySQL.

...ma questo indica che non sono il solo. Che succede? Si deve integrare l'update con un PHP che applica quell'update condizionatamente?

**Comment by cigo76** [comment]
ho provato ad installare anche la versione precedente: stesso problema!!

**Comment by lucasalva87** [comment]
> Si, problema risolto. MA quell'incongruenza a me non compare purtroppo, invece mi compare questa: ![image](https://private-user-images.githubusercontent.com/392762/302318593-d6a13024-889c-45fb-8fa9-2fc7ea5768fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTI1NTAsIm5iZiI6MTcwNzIxMjI1MCwicGF0aCI6Ii8zOTI3NjIvMzAyMzE4NTkzLWQ2YTEzMDI0LTg4OWMtNDVmYi04ZmE5LTJmYzdlYTU3NjhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwOTM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGI2YjM4YjU2MmRmZWYzOTk1YTIwNTI2ZGQ1MTRhY2E2NTQxYzg5NTY1NDQzNDJiMjIzMTJlNzE1YTQ5YWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2AGr3BSVGJnH1dPzbPxUoWNJqccLrGuEmcFIJFw-oOI)
> 
> nonostante:
> 
> ```
> CREATE TABLE `em_print_template` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `id_template` int(11) NOT NULL,
>   `id_print` int(11) NOT NULL,
>   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
>   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
>   PRIMARY KEY (`id`),
>   KEY `id_email` (`id_template`),
>   KEY `id_print` (`id_print`),
>   CONSTRAINT `em_print_template_ibfk_1` FOREIGN KEY (`id_template`) REFERENCES `em_templates` (`id`) ON DELETE CASCADE,
>   CONSTRAINT `em_print_template_ibfk_2` FOREIGN KEY (`id_print`) REFERENCES `zz_prints` (`id`) ON DELETE CASCADE
> ) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4
> ```

Questa è un'incongruenza secondaria. Non genererà alcun problema in fase di aggiornamento. 
Sostanzialmente la chiave esterna che da te si chiama `em_print_template_ibfk_1 `nei controlli viene ricercata con il nome `em_print_template_ibfk_3` 
I controlli al momento segnalano tutto ma queste effettivamente sono segnalazioni che potremmo evitare.

**Comment by leonardocalabretta** [comment]
Stesso problema, risolto lanciando a mano 
ALTER TABLE `zz_groups` ADD `id_module_start` INT NULL AFTER `editable`;

**Comment by marcus905** [comment]
Uno è una stranezza, due è una coincidenza... Ma 3 è da valutare l'impatto.

**Comment by marcus905** [comment]
Svelato l'arcano. La v2.4.35 è stata taggata e compilata prima del commit del 29 agosto 2022 che introduceva la ALTER TABLE.

Se quindi si è fatto il passaggio 2.4.34 a .35 e poi a .36 allora il problema si manifesta. Se dalla 2.4.34 si passava direttamente alla 2.4.36 la versione del 2_4_35.sql era già fixato e non c'è il problema.

Solo che ora come si fa? Aggiungiamo un PHP che verifica ed esegue la query qualora non sia stata eseguita prima di eseguire l'SQL ovviamente ricreando lo zip?

**Comment by lucasalva87** [comment]
La v. 2.4.35 è stata rilasciata il 12/08/2022 alle 19:09:19 mentre il commit in questione risale al 29/08/2022
https://github.com/devcode-it/openstamanager/commit/4d03890ce93fc7c8aa4e69f9c4bea0f4848718cf#diff-38bcfb3809b6c9d2848dff3c339a8d5cf5aa6b16cf6486539b8074d769358115

credo proprio che tu abbia ragione. A questo punto sarà necessario fare uscire una fix assieme alla prossima versione 2.4.55

**Comment by marcus905** [comment]
Mettete un warning nella pagina della release dicendo di fare il controllo integrità database prima e se viene riscontrata l'anomalia di attendere la prossima versione a questo punto

**Comment by lucasalva87** [comment]
Stiamo provvedendo a verificare se ci sono stati altri casi analoghi e metteremo un avviso sulle pagine delle release interessate. Inoltre effettueremo una correzione omnicomprensiva con il prossimo rilascio della 2.4.55. Grazie per la segnalazione.

**Comment by lucasalva87** [comment]
Scusami @leo-spa ma:

1) Non si è obbligati PER FORZA ad aggiornare il gestionale
2) Prima di un aggiornamento va sempre fatto un backup e in caso si ripristina la versione precedente
3) E' un problema tranquillamente risolvibile (se leggi l'issue)
4) Reputo inutile questa tua segnalazione visto che è stato già spiegato come risolvere, se invece si tratta di un problema diverso andava aperto un issue separato.

Grazie per la collaborazione.
