### ISSUE TITLE
Iva in fatture non elettroniche

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1435]
## Comportamento richiesto

abbiamo notato che se registriamo una **fattura NON elettronica con iva** nelle righe, poi quando si genera l'autofattura perde il valore economico

vedi in demo fattura n.123PROVA

_____
![Screenshot 2024-02-07 alle 12 31 32](https://github.com/devcode-it/openstamanager/assets/75281007/e936708c-90ec-4907-83bb-8f3bbcbc9ea9)
![Screenshot 2024-02-07 alle 12 31 57](https://github.com/devcode-it/openstamanager/assets/75281007/518bbb9c-8f87-4140-8218-328be8800683)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. creare una fattura non elettronica con una o più **righe con iva**
2. creare l'autofattura 
3.

* Modulo:
* Versione del progetto: 2.4.54
* Versione PHP:
* Tipo di server:

**Comment by NicolaNext** [comment]
Confermo il problema, l'ho usata per la prima volta nella versione 2.4.53 e mi succede la stessa cosa.

**Comment by Pek5892** [comment]
Buongiorno,
questa modifica è stata introdotta nella versione 2.4.49 per risolvere: https://github.com/devcode-it/openstamanager/issues/1153
https://forum.openstamanager.com/d/2530-risolto-autofattura-integrazione-reverse-charge-interno-misto/4

ed è documentata qui:
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/2cfc3604-f2b2-489f-a238-af0708e6e525)
e qui:
https://docs.openstamanager.com/v/2.4.54/guide/esempi/autofattura#id-1-registrazione-fattura-estera
