### ISSUE TITLE
CKEditor 4.22.1 version is not secure. Consider upgrading to the latest one, 4.24.0-lts.

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [devcode-it/openstamanager#1437]
Buongiorno,
ho notato da oggi questo avviso.
This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts.

sembra che la versione del package.json sia 4.22.0
![image](https://github.com/devcode-it/openstamanager/assets/24794417/449247fe-4ea0-40e4-8e17-d73c5c9963fe)

**Comment by NicolaNext** [comment]
Risposta già disponibile sul forum
https://forum.openstamanager.com/d/2826-osm-v-2454-alert-versione-ckeditor
