### ISSUE TITLE
PHP 8.0 EOL 2023-11-26, supporto nuove versioni

### ISSUE THREAD

**Issue by esistgut** [devcode-it/openstamanager#1438]
Salve,
questa mattina il mio hosting ha fatto saltare il supporto a PHP 8.0 perché non più supportato da mesi e naturalmente OpenSTAManager è saltato insieme ad esso.
Ci sono programmi per il passaggio ad una nuova versione di PHP?

**Comment by Pek5892** [comment]
OSM è compatible con php8.3 a partire dalla versione 2.5.4
