### ISSUE TITLE
Duplica attività con sessioni multiple sballa o calendario o orario

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1439]
Sedetevi prima di leggere.

Se ho una attività con due o più sessioni di lavoro in giorni diversi e provo a duplicarla le date e gli orari delle sessioni vengono modificate con una logica "strana"

Vedi intervento 39 della demo da cui parto tutte le volte

**Da azioni di gruppo:**
A - L'intervento datato 01/02/2024 con due sessioni di lavoro (01 e 08 febbraio) viene duplicato mantenendo la stessa data di richiesta (01/02/2024) e attivando tutte e tre le opzioni, il risultato è un intervento (42) con due sessioni in data 01 e data 15 (la seconda sessione si incrementa di 7) e l'orario della seconda sessione aumentato di 1 ora.
La data di richiesta rimane 01/02)
B - Se duplicandolo (il 39) invece cambio data di richiesta (08/02) le date vengono entrambe incrementate (di 7 giorni) ma la data di richiesta rimane 01/02 e l'orario della seconda sessione aumenta di un'ora (vedi int.44)
La data di richiesta RIMANE 01/02)

**Dal bottone "interno" all'attività**
A - Se duplico lo stesso intervento (39) con data di richiesta uguale (attivando le prime tre opzioni) le date e gli orari rimangono uguali.
La data di richiesta rimane 01/02)
B - Se duplico infine sempre l'intervento 39 settando la richiesta all'08/02 (sempre attivando le prime tre opzioni) le date si modificano aumentando di 7 unità e gli orari rimangono corretti (intervento 45).
La data di richiesta DIVENTA 08/02)

* Modulo: Attvità
* Versione del progetto: demo 2.4.54
* Versione PHP: 
* Tipo di server:

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/6d33274dbbaaee6628db3381d681302d307a31dd
