### ISSUE TITLE
Correzione aggiornamento stati ddt e ordini automatici

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#144]
Aggiornare lettura stati ddt in fase di inserimento in fattura, non prende lo stato "Parzialmente fatturato" (legato al commit 664eb8fd538079a0daefb552210f70e03675ba16)

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere presente anche in **add_ordine.php** e la relativa query sulle **edit.php** delle fatture.
Inoltre sospetto sia presente anche nei DDT, riguardo agli Ordini.

**Comment by Dasc3er** [comment]
Inoltre per quale motivo viene inserita una gestione delle righe degli Ordini quando non è possibile importare gli ordini in Fattura?
https://github.com/devcode-it/openstamanager/blob/7717fb46dc436f79d4f7b072a17f146c69c8a6b0/modules/fatture/actions.php#L1346

**Comment by loviuz** [comment]
Nei ddt non si possono importare ordini con "+ Ordine", non c'è questo tasto, anche se sarebbe da aggiungere...
Da un ordine è possibile creare una fattura, per cui l'aggiornamento stato ordine è possibile in base alle quantità da evadere.
