### ISSUE TITLE
Confusione nei riferimenti ordine in stampa fattura

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1440]
Ho la sensazione che ci sia un po' di confusione nei riferimenti all'ordine cliente nel template di stampa della fattura
Ho creato un esempio nella demo (Ordine 06 e fattura 0011/2024)
Nell'ordine cliente il **numero d'ordine interno e la data ordine interno** li ho cerchiati in rosso mentre il **numero d'ordine cliente e la data ordine cliente** li ho cerchiati in verde.

![Ordine](https://github.com/devcode-it/openstamanager/assets/102433047/87c7410d-ec4e-4437-86c6-082feb93c58f)

Da quell'ordine ho generato la fattura 0011 (ho stampato la bozza quindi il numero non c'è) e nella stampa ho cerchiato di rosso il **riferimento al numero d'ordine interno e alla data ordine interno** mentre in verde il **riferimento al numero d'ordine cliente e alla data ordine cliente**

![Fattura](https://github.com/devcode-it/openstamanager/assets/102433047/6a2eafcd-ab01-4035-a602-03bcbd438840)

Secondo me le date sono scambiate tra di loro e il **numero d'ordine interno** è ignorato e sostituito dal **numero di ordine cliente** rendendo i riferimenti decisamente poco utili.

**Comment by NicolaNext** [comment]
Ma chiusa per inattività vuol non vuol dire che è risolto.. la tengo attiva allora.

**Comment by Pek5892** [comment]
Buongiorno @NicolaNext , ha provato ad applicare la fix https://github.com/devcode-it/openstamanager/commit/03dd0069796c220c16274a4bc9f1f8df21a21daf ?

**Comment by NicolaNext** [comment]
Non ancora, ho dato per scontato che la demo fosse stata sistemata e vedo ancora l'errore. Se non è così proverò la fix

**Comment by NicolaNext** [comment]
Ho provato la fix ma non è ancora risolto, ora sia l'**ordine** che l'**ordine cliente** (vedi foto sopra) prendono il numero e la data dell'ordine cliente. Spariscono i riferimenti dell'ordine interno.

Mi aspetterei che la dicitura fosse per esempio:
**Ordine n. 12/2024 del 25/03/2024** (questi sono i riferimenti interni dell'ordine, i miei di OpenStaManager)
**Ordine cliente num. 123456 del 22/03/2024** (questi sono i riferimenti dell'ordine del cliente).
