### ISSUE TITLE
Bloccato dopo aggiornamento da 2.4.42 a 2.4.54

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1444]
Salve, dopo aver avviato l'aggiornamento si è bloccato nella schermata che allego.
![image](https://github.com/devcode-it/openstamanager/assets/103928231/eb0e4884-d1b8-4203-bec8-a2f2b7bcf3d6)

Ho provato a sovrascrivere tutte le cartelle del gestionale, riprovando con piu versioni, la 45, 46 e 47, ma niente anche mettendo ?force mi rimane bloccato come da screen sottostante
![image](https://github.com/devcode-it/openstamanager/assets/103928231/5bb815e6-eeab-4036-ab8f-8d4be02b320c)

Quali altre procedure potrei effettuare?

**Comment by lucasalva87** [comment]
Chiudo per richiesta duplicata, già gestita sul forum: https://forum.openstamanager.com/d/2852-bloccato-dopo-aggiornamento-da-2442-a-2454
