### ISSUE TITLE
Esportare in formato XML le fatture acquisto NON elettroniche

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1445]
## Comportamento richiesto

abbiamo notato che non è possibile esportare in XML le **fattura passive _non elettroniche_.**
si presenta un'avviso e non procede con la creazione dello zip.

probabilmente questa funzione è stata pensata solo per le fatture ordinarie.

ma può tornare utile questa modalità perchè così i file XML si invano al commercialista per importarle in contabilità e non rifare tutto il lavoro di registrazione manuale.

![Screenshot 2024-03-07 alle 18 15 21](https://github.com/devcode-it/openstamanager/assets/75281007/71a67eef-fa5c-47a7-b9a6-76e773d22390)
![Screenshot 2024-03-07 alle 18 17 10](https://github.com/devcode-it/openstamanager/assets/75281007/f2d0ac8a-1004-4bc9-8aae-82640345b22a)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. selezionare le fatture acquisto NON elettroniche
2. selezionare esporta XML in Azioni di gruppo
3.

* Modulo: **Fatture di acquisto**
* Versione del progetto: **2.4.53**
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
L'azione di gruppo per esportare gli XML funziona solo con documenti dove è presente il file XML della fattura. Essendo la fattura compilata a mano, non presenta alcun file XML.
