### ISSUE TITLE
Mancata apertura anteprima pdf nei documenti

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1448]
Buongiorno,
riprendo una vecchia discussione nel forum che è recentemente tornata di attualità e cioè [https://forum.openstamanager.com/d/2785](url)

In alcuni casi la funzione di anteprima dei pdf smette di funzionare dopo un aggiornamento (a me è capitato nel passaggio da 2.4.53 a 2.4.54).
Come sempre faccio quando aggiorno, ho conservato copia della vecchia versione e, mentre sulla .53 continua a funzionare perfettamente, sulla .54 non funziona più.
Nel caso della firma interventi è particolarmente antipatico.

Nel forum vengono citati alcuni tentativi da fare ma non si parla mai di soluzione del problema.

![1709893183-70570-anteprima-e-firma](https://github.com/devcode-it/openstamanager/assets/102433047/22a19482-e980-4feb-afee-6204f3e59acc)

PHP (8.0.28 )
Versione MySQL: 10.5.18-MariaDB-0+deb11u1 via estensione PHP MySQLi

**Comment by Pek5892** [comment]
Problema risolto nella beta 2.5.1 in release
