### ISSUE TITLE
Aggiunta di una variabile $baseurl per il progetto

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#145]
Per alcuni moduli ci sarebbe bisogno dell'uso di una variabile, da noi chiamata $baseurl, con l'URL dell'installazione di OSM, per inserire, ad esempio, immagini in una mail di notifica. In questo modo, verrebbe linkata l'immagine ad un file presente nella propria installazione di OSM, ma finora abbiamo aggiunto $baseurl nel config.inc.php specificandolo manualmente.

Ci sono funzioni di PHP che ricavano l'indirizzo IP del server e la path attuali, però a volte con sottodomini o indirizzi IP diretti non si riesce ad estrarre in maniera precisa questa URL. Se si riuscisse a inizializzare questa variabile e averla sempre disponibile non sarebbe male.

**Comment by Dasc3er** [comment]
Non si potrebbe costruirla sulla base di `$rootdir` e il valore di `$_SERVER['SERVER_NAME']`?
