### ISSUE TITLE
Duplicazione (bulk_action) fattura d'acquisto con autofattura collegata collega la fattura d'acquisto duplicata all'autofattura già emessa

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#1450]
## Comportamento richiesto

Duplicazione di una fattura d'acquisto non colleghi l'autofattura gia emessa

## Comportamento attuale

Duplicazione fattura d'acquisto con autofattura collegata collega la fattura d'acquisto duplicata all'autofattura già emessa

## Possibile soluzione

Sto inviando la pull request.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Duplicazione fatture acquisto via bulk
2. apertura fattura acquisto, banner mostrato in alto

* Modulo: fatture
* Versione del progetto: 2.4.54
* Versione PHP: 8.0
* Tipo di server: Aruba Apache

**Comment by Pek5892** [comment]
Risolto nella versione 2.5 (beta) del gestionale in release.
