### ISSUE TITLE
Data intervento errata

### ISSUE THREAD

**Issue by MakPaolo** [devcode-it/openstamanager#1453]
buon giorno
Con la versione 2.4.54 abbiamo notato che la data degli interventi è errata
abbiamo provato la soluzione che ci è stata proposta
https://github.com/devcode-it/openstamanager/commit/702ddd712d265ff071728f0f573e66004f2f6b99

ma senza successo
Grazie

**Comment by Pek5892** [comment]
Buongiorno @MakPaolo,
potrebbe darci maggiori informazioni?
