### ISSUE TITLE
problema a completare l installazione e il corretto avviamento di openstamanager

### ISSUE THREAD

**Issue by VergilDMC00** [devcode-it/openstamanager#1454]
## Comportamento richiesto

vorrei che il progetto facesse l'installazione

## Comportamento attuale

non riesco a far avviare il progetto

## Passi per riprodurre il comportamento

1. clone del repo master
2. yarn develop-OSM
3. php -S localhost:3000

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

ho clonato il branch master del repo in locale, ho creato un container docker mysql per il database e ho usato i comandi:
`yarn develop-OSM` e `php -S localhost:3000` per installare le dipendenze e far partire il progetto

* Modulo: ?
* Versione del progetto: 2.5 penso
* Versione PHP: 8.3.4
* Tipo di server: computer local (MAC)

**Comment by Pek5892** [comment]
Buongiorno,
le lascio la guida completa all'installazione di OSM: [https://docs.openstamanager.com/v/2.5/openstamanager/configurazione/installazione#installazione](https://docs.openstamanager.com/v/2.5/openstamanager/configurazione/installazione#installazione).
Chiudo l'issue in quanto non sono presenti problemi da segnalare a livello software, in caso doveste riscontrare ulteriori difficoltà sentitevi liberi di contattarci nel nostro forum: [https://forum.openstamanager.com/](https://forum.openstamanager.com/)
