### ISSUE TITLE
problemi build progetto

### ISSUE THREAD

**Issue by VergilDMC00** [devcode-it/openstamanager#1455]
## Comportamento richiesto

che il progetto buildi e parta senza errori

## Comportamento attuale

quando lancio il comando `yarn develop-OSM` i pacchetti vengono installati, ma quando inizia a fare il gulp mi viene stampato un errore sulla libreria pdf.js, di seguito la copia dell'errore:
`[15:50:41] Starting 'srcFonts'...
[15:50:41] 'pdfjs' errored after 9.45 ms
[15:50:41] Error: ENOENT: no such file or directory, scandir './node_modules/pdf.js/public/'
    at Object.readdirSync (node:fs:1508:26)
    at pdfjs (/Users/giacomo/Desktop/gitRepo/openstamanager2.4.54/gulpfile.js:400:28)
    at bound (node:domain:432:15)
    at runBound (node:domain:443:12)
    at asyncRunner (/Users/giacomo/Desktop/gitRepo/openstamanager2.4.54/node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[15:50:41] 'default' errored after 13 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. lanciare il comando `yarn develop-OSM` dopo aver installato il composer

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Versione del progetto: 2.4.54
* Versione PHP: 7.4.33
* Versione Nodejs: node 21.7.1
* Tipo di server: ambiente locale con DB hostato in container docker e codice del progetto runnato dalla cartella tramite comando: `php -S localhost:3000`

**Comment by Pek5892** [comment]
Buongiorno @VergilDMC00,
le modifiche effettuate alle librerie esterne non sono dipendenti da noi, pertanto se vengono effettuate modifiche in un momento successivo alla release che ne impediscono la compilazione l'unico modo per poterla effettuare manualmente è scaricandosi l'ultima versione del gulpfile aggiornato.
Nella release 2.5 beta abbiamo aggiornato il file gulpfile.js con il seguente commit: https://github.com/devcode-it/openstamanager/commit/203606855e97f9e4deb575083a9fa9cf611adbdc. Andando ad anticipare questa modifica dovreste poter ricompilare senza problemi.

**Comment by VergilDMC00** [comment]
Buonasera ho apportato le modifiche del commit citato nella precedente risposta nel mio codice, adesso a lanciare `yarn develop-OSM` sembrerebbe andare (ho provato sia con node 18 che node 21), ma quando lancio il comando: `php -S localhost:3000` mi viene ritornato questo errore quando vado a localhost:3000

` PHP 7.4.33 Development Server (http://localhost:3000) started
[Thu Apr  4 19:28:36 2024] [::1]:50720 Accepted
[Thu Apr  4 19:28:36 2024] [::1]:50720 [500]: GET /
[Thu Apr  4 19:28:36 2024] [::1]:50720 Closing`

e a livello web mi viene presentata questa schermata
<img width="467" alt="Screenshot 2024-04-04 at 19 32 13" src="https://github.com/devcode-it/openstamanager/assets/95279077/9bf7f129-c247-4422-bc99-d91d72b4b05d">

**Comment by Pek5892** [comment]
Buongiorno,
sembrerebbe non essere stato correttamente configurato il database, le lascio la guida completa all'installazione di OSM: https://docs.openstamanager.com/v/2.5/openstamanager/configurazione/installazione#installazione.
Chiudo l'issue in quanto non sono presenti problemi da segnalare a livello software.

**Comment by VergilDMC00** [comment]
la guida l ho seguita, è proprio perche ho seguito la guida che non mi spiego il mancato funzionamento

**Comment by Pek5892** [comment]
Buongiorno,
non era ben specificato che si stava tentando di installare la versione 2.4.54, applicando questa fix il problema dovrebbe risolversi: https://github.com/devcode-it/openstamanager/commit/6722e59de4f003f7e956b1fe978ab1fdc1d4f73f
