### ISSUE TITLE
problemi nel salvataggio dei file

### ISSUE THREAD

**Issue by JakFrost00** [devcode-it/openstamanager#1460]
## Comportamento richiesto

che il progetto salvi correttamente i file che carico

## Comportamento attuale

i file non vengono salvati e viene generato l errore sottostante

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. creare un intervento sul calendario o qualsiasi altro "oggetto" dove è possibile caricare file
2. caricare un file

`[2024-04-08 15:20:47] Logs.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)" at /app/vendor/league/flysystem-local/LocalFilesystemAdapter.php line 75 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE) at /app/vendor/league/flysystem-local/LocalFilesystemAdapter.php:75)"}
{"url":"/actions.php?op=aggiungi-allegato&id_module=3&id_plugin=&id_record=1","ip":"192.168.65.1","http_method":"POST","server":"0.0.0.0","referrer":"http://localhost:3000/editor.php?id_module=3&id_record=1","uid":"21fec7e"} 
[2024-04-08 15:20:47] Logs.ERROR: syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE) {"code":0,"message":"syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)","file":"/app/vendor/league/flysystem-local/LocalFilesystemAdapter.php","line":75,"trace":"#0 /app/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()\n#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#2 /app/modules/adattatori_archiviazione/src/Adapters/LocalAdapter.php(24): spl_autoload_call()\n#3 /app/vendor/composer/ClassLoader.php(576): include('/app/modules/ad...')\n#4 /app/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()\n#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#6 /app/src/Models/Upload.php(105): spl_autoload_call()\n#7 /app/src/Uploads.php(81): Models\\Upload::build()\n#8 /app/actions.php(128): Uploads::upload()\n#9 {main}"}
{"url":"/actions.php?op=aggiungi-allegato&id_module=3&id_plugin=&id_record=1","ip":"192.168.65.1","http_method":"POST","server":"0.0.0.0","referrer":"http://localhost:3000/editor.php?id_module=3&id_record=1","uid":"21fec7e"} `

## Contesto
* Versione del progetto: 2.5
* Versione PHP: 7.4.33
* Versione Nodejs: node 21.7.1
* Tipo di server: container docker sia per DB che per server

potessero servire questo è il mio docker-compose:
`version: '3'
services:
 osm:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
    - "3000:3000"
  volumes:
    - .:/app
 sqldb:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: openstamanager
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  ports:
    - "3307:3306"
  volumes:
    - ./db_data:/var/lib/mysql`

mentre questo è il mio dockerfile:
`FROM php:7.4.33-apache-buster
#FROM php:7.4.33-apache
#FROM httpd:latest

WORKDIR /app
COPY . .
#nodejs 21 installation + yarn
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_21.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install nodejs -y
RUN npm install -g yarn

RUN apt-get update -y && apt-get install -y \
    libonig-dev \
    libzip-dev \
    libxslt-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libldap2-dev

# Installa le estensioni PHP aggiuntive
RUN docker-php-ext-install \
    pdo_mysql \
    zip \
    mbstring \
    xmlrpc \
    curl \
    soap \
    gd \
    xml \
    intl \
    ldap \
    json \
    xsl \
    mysqli

#sudo apt install -y php php-cli php-mysql php-common php-zip php-mbstring php-xmlrpc php-curl php-soap php-gd php-xml php-intl php-ldap

# Installa l'estensione GD
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

#composer installation
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"

RUN sed -i 's/display_errors = .*/display_errors = Off/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/max_execution_time = .*/max_execution_time = 180/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/max_input_time = .*/max_input_time = 180/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/max_input_vars = .*/max_input_vars = 5000/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/memory_limit = .*/memory_limit = 512M/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/post_max_size = .*/post_max_size = 32M/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/session.gc_maxlifetime = .*/session.gc_maxlifetime = 1440/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/upload_max_filesize = .*/upload_max_filesize = 32M/' /usr/local/etc/php/php.ini-development && \
    sed -i 's/zlib.output_compression = .*/zlib.output_compression = On/' /usr/local/etc/php/php.ini-development

RUN sed -i 's/display_errors = .*/display_errors = Off/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/max_execution_time = .*/max_execution_time = 180/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/max_input_time = .*/max_input_time = 180/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/max_input_vars = .*/max_input_vars = 5000/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/memory_limit = .*/memory_limit = 512M/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/post_max_size = .*/post_max_size = 32M/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/session.gc_maxlifetime = .*/session.gc_maxlifetime = 1440/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/upload_max_filesize = .*/upload_max_filesize = 32M/' /usr/local/etc/php/php.ini-production && \
    sed -i 's/zlib.output_compression = .*/zlib.output_compression = On/' /usr/local/etc/php/php.ini-production

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN php composer.phar install
RUN yarn develop-OSM

CMD [ "php", "-S", "0.0.0.0:3000" ]`

**Comment by Pek5892** [comment]
Buongiorno, il problema è già stato corretto e la correzione sarà disponibile dalla versione 2.5.1

**Comment by JakFrost00** [comment]
ok altro probelma che ho è che ogni tanto il sistema mi obbliga sia in locale che in ambiente docker a stopparlo e riavvirlo perche si impianta in caricamenti infiniti e se apro e chiudo il browser mi si impianta in un caricamento infinito che non mi permette di arrivare alla dashboard

**Comment by JakFrost00** [comment]
@Pek5892 il problema dei file ce l ho anche con la 2.4.54

**Comment by Pek5892** [comment]
Verificando la sua installazione viene segnalato qualcosa?
https://docs.openstamanager.com/v/2.5/guide/esempi/verificare-linstallazione-di-osm

**Comment by JakFrost00** [comment]
![Screenshot 2024-04-08 at 17 39 08](https://github.com/devcode-it/openstamanager/assets/166109220/8309b161-6c52-448b-aee0-4e81b3191732)
![Screenshot 2024-04-08 at 17 39 37](https://github.com/devcode-it/openstamanager/assets/166109220/aa0188f2-66ef-4a8d-a9cc-289ce6b3dacd)
![Screenshot 2024-04-08 at 17 40 00](https://github.com/devcode-it/openstamanager/assets/166109220/a9d6d069-bb4e-4d9b-9ae0-2b03189988dc)

**Comment by JakFrost00** [comment]
![Screenshot 2024-04-08 at 17 40 00](https://github.com/devcode-it/openstamanager/assets/166109220/e4acaa31-1379-4a02-a1c5-a51e5335c446)
![Screenshot 2024-04-08 at 17 39 24](https://github.com/devcode-it/openstamanager/assets/166109220/205684f1-d7b1-4794-9da1-3582692c7dff)
![Screenshot 2024-04-08 at 17 39 08](https://github.com/devcode-it/openstamanager/assets/166109220/b84cdb44-2d0e-46e9-85f9-bfb9b86b736b)

**Comment by Pek5892** [comment]
Andrebbero corretti tutti i requisiti non soddisfatti indicati

**Comment by JakFrost00** [comment]
ok e come faccio a risolverli, ce qualche comando o ce qualcosa da inserire nel codice di openstamanager?

**Comment by lepool** [comment]
Tu usi un container Docker. Verifica in quel container cosa hai installato come Mysql . Presumo dovrai adattare il file Docker alle tue esigenze oppure usare un Dockerfile diverso.

**Comment by JakFrost00** [comment]
il container docker lo creo col dockerfile che ho condiviso nel primo messaggio dell issue

**Comment by lepool** [comment]
Allora presumo che nel tuo dockerfile venga installato un Mysql non pienamente supportato dal gestionale.

**Comment by JakFrost00** [comment]
il server mysql viene tirato su da un docker compose che usa l immagine taggata come latest su docker
