### ISSUE TITLE
Sessione info SMS inviati

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1462]
## Comportamento richiesto

nei vari doc è presente il riepilogo delle mail inviate di quel determinato documento
per chi ha aggiunto il modulo SMS (https://openstamanager.com/moduli/gestione-sms/) torna molto utile avere l'info degli SMS inviati, qualcosa di simile a quello già presente dell'email.

questo permette di aver riscontro se è stato inviata comunicazione via SMS

![Screenshot 2024-04-09 alle 17 38 04](https://github.com/devcode-it/openstamanager/assets/75281007/95140152-8f38-4812-894e-43210459cabd)

**Comment by Pek5892** [comment]
Issue aperta in repository apposito, in modo da poter valutare la sua implementazione.

**Comment by sajotrei** [comment]
Ciao è possibile sapere se è stata implementata ?

**Comment by sajotrei** [comment]
a ok, attendiamo 
grazie
