### ISSUE TITLE
Statistiche: il periodo selezionato nella pagina aggiorna solo il grafico "Vendite e acquisti"

### ISSUE THREAD

**Issue by gponzo** [devcode-it/openstamanager#1464]
## Comportamento richiesto

Se in "Periodi temporali" specifico ad esempio "Anno scorso" vorrei che anche l'elenco dei 20 clienti top, dei 20 articoli più venduti e tutti i grafici a seguire fossero riferiti a quel periodo.

## Comportamento attuale

Attualmente si aggiorna solo il grafico "Vendite e acquisti".

## Passi per riprodurre il comportamento

1. Cliccare su "Statistiche" dal menu laterale (sx);
2. In "Periodi temporali" sceglierne uno diverso da quello attuale.

Eventuale codice rilevante:
Ho dato un'occhiata a `modules/statistiche/edit.php` e il codice include sempre `$start` e `$end`, per cui non capisco per quale motivo poi non mi funzioni.

## Contesto

* Modulo: 52
* Versione del progetto: 2.4.54 (7cd3b7180)
* Versione PHP: 8.0.30
* Tipo di server: LAMP

Allego ScreenShot:
![2024-04-18_11-59-02_OSM-bug](https://github.com/devcode-it/openstamanager/assets/63299644/82be9c83-c754-4edb-8b50-6b660f62bd72)

**Comment by Pek5892** [comment]
Buongiorno,
i filtri per periodi temporali vengono applicati solo al grafico vendite e acquisti per permettere di sovrapporre dati relativi ad annate diverse.
Per gli altri grafici è sufficiente modificare il selettore della data del gestionale per visualizzare i dati relativi al periodo interessato.
