### ISSUE TITLE
Whatsapp e numeri esteri

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1465]
## Comportamento richiesto
Dalla versione 2.5 OSM sta diventando "internazionale", va da se che il commit https://github.com/devcode-it/openstamanager/commit/3fffd5f1d9bb29e91c59b42e42474e69bc1a19df non è più funzionale nel caso di numeri esteri (+XX con XX != 39).
Sarebbe auspicabile che il link a whatsapp sia in grado di gestire anche numeri esteri

## Comportamento attuale
Il commit sopra citato aggiunge in automatico il +39 ai numeri che ne sono privi ma se un cliente ha numero non italiano la scappatoia introdotta smette di funzionare.

**Comment by Pek5892** [comment]
Buongiorno,
il codice indicato non è mai stato portato in release, è stato corretto da commit: a5e39bf800519de52890aea7cfeaadc6d3f31455
