### ISSUE TITLE
Autofattura collegata non presente

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1467]
Mi è capitato in alcuni casi che, in fase di importazione dell'autofattura scaricata dallo SDI, il menù "autofattura collegata" risulti vuoto. 

![autofattura_collegata](https://github.com/devcode-it/openstamanager/assets/102433047/f6961fc5-5ae3-4db1-96b8-015708ad50e8)

Credo di aver individuato il problema, sembra che l'errore si manifesti quando creo le fatture non elettroniche usando il comando duplica (e poi le slego dalla autofattura già emessa cancellando il campo "id_autofattura" in  co_documenti).

Il problema delle fatture non elettroniche che rimangono legate in caso di duplicazione è stato segnalato in https://github.com/devcode-it/openstamanager/issues/1450, è stato considerato come risolto a partire dalla instabile versione 2.5.

C'è qualche altro campo da "ripulire" nel databae senza dover necessariamente rifare le fatture a mano?
Ovviamente non penso di aggiornare alla 2.5 per ora

* Versione del progetto: 2.4.54

**Comment by Pek5892** [comment]
Buongiorno @NicolaNext può descriverci i passaggi che esegue per l'emissione delle autofatture? non ci è ben chiaro se venga correttamente creata l'autofattura tra le vendite o censita unicamente la fattura di acquisto non elettronica.

**Comment by Pek5892** [comment]
In master non riusciamo a riprodurre il problema, potrebbe verificare che la fattura num. 11 duplicata sia in stato Emessa? abbiamo seguito i passaggi ma la fattura viene correttamente associata.

**Comment by NicolaNext** [comment]
Tra ieri sera e questa mattina ho svelato l'arcano, condivido perchè potrebbe capitare ad altri.

Premetto che il "non bug" non dipendeva affatto dalla duplicazione delle fatture anche se la coincidenza è stata diabolica.

A partire da febbraio l'anagrafica incriminata sul portale di Aruba ha subito una modifica alla partita iva (non ricordo affatto di averla modificata io ma si sà, chi non dubita di niente, niente ha capito).
La partita iva era stata inserita su Aruba nel formato 000XXXXXXXX come salvata nel mio vecchio gestionale ed importata in OSM ma da febbraio i tre zeri sono spariti dall'anagrafica Aruba quindi la partita iva nell'xml di ritorno era diversa da quella presente a gestionale (e infatti mi sono trovato una nuova anagrafica identica in tutto tranne che per la partita iva appunto).

Grazie Valentina per la pazienza.
