### ISSUE TITLE
Probabile BUG: Le ore di lavoro nella vista attività si moltiplicano se inserisco allegati nell'attività

### ISSUE THREAD

**Issue by NicolaNext** [devcode-it/openstamanager#1468]
Vedi intervento 83 della demo, ho inserito un intervento con durata **2 ore** e caricato **5 allegati** (sono immagini ma anche con i pdf non cambia nulla).

![83-2024-Intervento](https://github.com/devcode-it/openstamanager/assets/102433047/f36cbc93-a6da-48eb-9dd8-2a336434bb45)

___

Il totale attività è sempre corretto TRANNE che nella vista delle attività dove il totale ore è pari a 10 vale a dire 2 ore effettive moltiplicato 5 che è il numero degli allegati

![83-2024-Vista](https://github.com/devcode-it/openstamanager/assets/102433047/05fcd8d3-ac76-4ec5-b0b7-8bd8e4c37dea)

**Comment by Pek5892** [comment]
Buongiorno @NicolaNext , sembrerebbe un problema relativo alla vista del modulo
