### ISSUE TITLE
Impostare la lingua di sistema in base all'utente

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1470]
## Comportamento richiesto

così come è stato introdotta la possibilità di impostare il tema per utente
può essere utile poter impostare la **lingua per utente**

**Comment by Pek5892** [comment]
Buongiorno @sajotrei, il tema è impostabile per gruppo di utenti e non per utenti specifici, questa della lingua è una modifica già in programma ma dobbiamo ancora affrontare il come strutturarla in quanto non è una modifica semplice come il cambio di tema.
