### ISSUE TITLE
Campo "Ordina tramite" non funzionante con funzioni

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#148]
## Comportamento richiesto

Nella gestione viste, si dovrebbe poter inserire su "Ordina tramite" anche una funzione, perché non si riesce ad ordinare, ad esempio, le fatture per numero, perché attualmente vengono ordinate per il campo numero come fosse una stringa, e non un numero intero.
Le fatture, con numerazione dalla 1 alla 20, ad esempio, se le ordino per il campo "Numero", escono così:
1,10,11,12,13,14,15,16,17,18,19,2,20,3,4,5,6,7,8,9

## Comportamento attuale

Nella gestione viste, su "Fatture di vendita", inserendo su "Ordina tramite" la stringa
`CAST(numero_esterno AS UNSIGNED)`
la vista dà errore.

## Possibile soluzione

Ora, al campo su order_by vengono aggiunti i caratteri ` per evitare errori nella query, ma lascerei all'utente inserirli, senza inserirli automaticamente, altrimenti non si riescono ad inserire negli ordinamenti delle funzioni.

**Comment by loviuz** [comment]
Il campo "order_by" delle viste riguardanti fatture, ddt, ordini, preventivi, contratti, attività andrebbe già preimpostato così di default, per cui se viene modificata la classe per gestire "Ordina tramite", sarebbe da aggiornare anche il file sql della prossima release per includere questo tipo di ordinamento di default.

**Comment by Dasc3er** [comment]
Potrebbe essere utile rimuovere gli apici anche dal campo _search_inside_ per la ricerca personalizzata?

**Comment by loviuz** [comment]
si, assolutamente, ma dovrebbe già essere così, giusto?

**Comment by Dasc3er** [comment]
In pratica, era già stato previsto che se il campo _search_inside_ contiene `|search|` è personalizzabile, con `|search|` che diventa la parola da ricercare...

**Comment by loviuz** [comment]
ottimo. confermo che l'ordinamento funziona correttamente!
