### ISSUE TITLE
Layout Preventivo OSM 2.5

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1480]
## Comportamento richiesto

stiamo "provando" la 252

per Logica potrebbe aver più senso avere **la descrizione del preventivo a sinistra** e le **note a fianco alle condizioni** 

inoltre, oltre a indicare eventuali insoluti ( molto utile ), sarebbe certamente interessate indicare **il valore € di esposizione** del cliente, ricavato da fatture emesse non ancora pagate 

<img width="2040" alt="Screenshot 2024-06-03 alle 15 24 16" src="https://github.com/devcode-it/openstamanager/assets/75281007/3f99bebb-c0d8-4cd5-819c-f6ab4b9f9b81">

* Modulo: PREVENTIVO
* Versione del progetto: 2.5.2 BETA
* Versione PHP:
* Tipo di server:

**Comment by NicolaNext** [comment]
Ho cominciato anche io a fare qualche prova, sicuramente molto acerbo, FANTASTICO l'aver portato lo stato in alto per tutti i moduli interessati, impagabile!
La butto qui senza aprire altra issue, potrebbe essere l'occasione per mettere a scaletta qualche altra segnalazione tipo (è la prima che mi è venuta in mente) la https://github.com/devcode-it/openstamanager/issues/1058 nella quale si parlava di modificare l'unità di misura delle durata garanzia degli articoli (ora solo in GIORNI).

**Comment by NicolaNext** [comment]
Senza dover aprire una nuova issue, riprendo un precedente suggerimento (https://github.com/devcode-it/openstamanager/issues/1415).
Sarebbe fantastico poter aggiungere l'elenco prodotti acquistati dal cliente nella sezione "dati cliente" della nuova interfaccia.
In questo modo, oltre alle informazioni su fatturato, pagamenti, esposizione, si avrebbe a disposizione l'elenco degli articoli già acquistati per eventuali ordini successivi.

**Comment by sajotrei** [comment]
> il valore € di esposizione del cliente, ricavato da fatture emesse non ancora pagate questa informazione andrà riportata nell'header delle fatture di vendita

Ciao Valentina, ma ho notato che dalla 2.6.x è stato mantenuto l'header SOLO nell'articolo e attività
era certamente comodo anche nella fattura con le varie info

PS. comunque a nostro avviso per logica ha senso avere queste info anche in fase di creazione del preventivo
