### ISSUE TITLE
(BUG) Cambio tipo sconto nelle righe

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1483]
## Comportamento richiesto

si presenta una anomalia con il tipo di sconto nelle righe

**es,** creo una riga indicando lo sconto in €, poi nel momento in cui porto la quantità a zero il sistema cambia lo sconto da € a percentuale. 
...la stessa cosa succede al contrario, se inizialmente si indica la % lo cambierà in € 

![Screenshot 2024-06-17 alle 12 54 25](https://github.com/devcode-it/openstamanager/assets/75281007/ec9a1133-e318-4316-bb0b-bbaa3167f0b6)
![Screenshot 2024-06-17 alle 12 54 36](https://github.com/devcode-it/openstamanager/assets/75281007/6b302eb4-93f8-4c2d-9aa6-2544b8365e76)

**VEDI SULLA DEMO PREV. OFF_24/10**

* Modulo:
* Versione del progetto: 2.4.54
* Versione PHP:
* Tipo di server: **DEMO**

**Comment by Pek5892** [comment]
Buongiorno,
il problema è già stato risolto in master
