### ISSUE TITLE
Richiesta aggiornamento CKEditor

### ISSUE THREAD

**Issue by reteinformatica** [devcode-it/openstamanager#1487]
Buongiorno, da qualche giorno all'interno dei campi "Richiesta" e "Descrizione" delle attività mi compare questo messaggio:

"This CKEditor 4.22.1 version is not secure. Consider upgrading to the latest one, 4.24.0-lts."

Grazie per l'attenzione

* Modulo: Attività
* Versione del progetto: 2.4.54
* Versione PHP: 8.1
* Tipo di server: Litespeed

**Comment by sajotrei** [comment]
prova a inserire questo CSS 
in strumenti - impostazioni - Generali

non risolve, ma rimuove l'avviso in attesa di agg.

![Screenshot 2024-07-12 alle 20 05 27](https://github.com/user-attachments/assets/a93be489-42fc-421a-b14e-4b7332e2f7fa)

**Comment by reteinformatica** [comment]
Grazie sajotrei,
era tanto per fare una segnalazione, posso aspettare anche un eventuale aggiornamento, non è un gran fastidio.

**Comment by lepool** [comment]
Si potrebbe anche inserire la seguente riga nel config.js del ckeditor

config.versionCheck = false;

**Comment by Pek5892** [comment]
Risolto nei rilasci successivi.
