### ISSUE TITLE
Fatturazione per conto di

### ISSUE THREAD

**Issue by lellonet** [devcode-it/openstamanager#1490]
## Comportamento richiesto
In caso di un attività "per conto di", in fatturazione il gestionale prendeva il pagamento archiviato nel cliente "per conto di"

## Comportamento attuale
Attualmente il gestionale prende il pagamento del cliente dell'attività e non quello "per conto di"

**Comment by Pek5892** [comment]
Buongiorno,
essendo ora definito il metodo di pagamento anche nell'attività, in fase di fatturazione viene utilizzato il metodo di pagamento qui specificato.
