### ISSUE TITLE
Aggiornamento

### ISSUE THREAD

**Issue by lellonet** [devcode-it/openstamanager#1491]
## Comportamento richiesto
Dopo aver aggiornato alla versione 2.5.3, non è più attivo il tasto "File" nella pagina aggiornamenti.
nella pagina impostazioni però è attivo, ed anche quello non è più cliccabile

**Comment by Pek5892** [comment]
Buongiorno,
non abbiamo ben capito la richiesta, potrebbe darci maggiori riferimenti?
