### ISSUE TITLE
Fatturazione

### ISSUE THREAD

**Issue by lellonet** [devcode-it/openstamanager#1492]
## Comportamento richiesto
Dalla versione 5.4.54 alla 2.5.3, anche se in impostazioni è disattivato l'addebito marca da bollo al cliente, in fatturazione continua ad addebitare i 2 euro al cliente. Bisogna deselezionare l'addebito durante la generazione della fattura.

**Comment by Pek5892** [comment]
Buongiorno,
questa funzionalità ha subito delle modifiche nelle versioni recenti: se abilitato nel documento **Marca da bollo automatica** essa verrà applicata ogni qualvolta che i requisiti per la sua applicazione si verificano, per poter modificare la sua applicazione manualmente è necessario disattivare questo flag e verrà mostrato il controllo manuale della marca da bollo.
