### ISSUE TITLE
Errore "Contabilità - Stampe contabili - Stampa bilancio

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#1496]
Quando seleziono la stampa bilancio in contabilità mi compare il seguente errore:

![grafik](https://github.com/user-attachments/assets/f7aa843e-9f70-4338-9c47-f1f4805fb50f)

OSM 2.5.4 
Apache/2.4.62 (Debian)
PHP Version 8.2.22

**Comment by Pek5892** [comment]
Buongiorno,
il problema è già stato risolto in master, le sarà sufficiente scaricare i file aggiornati o aspettare la prossima release.

**Comment by lepool** [comment]
Il problema al momento con la versione 2.5.5 è ancora presente.

**Comment by lepool** [comment]
il problema persiste nella versione 2.5.6

![grafik](https://github.com/user-attachments/assets/7c066449-058c-428f-8c80-20fec2483f3b)

**Comment by Pek5892** [comment]
Buongiorno,
il problema si verifica in assenza di documenti di acquisto registrati, e si risolve con fix: https://github.com/devcode-it/openstamanager/commit/467ebaea56a8a426f8bbc2a5ec073618007601ba

**Comment by lepool** [comment]
Il fix funziona , ma stranamente ho una fattura di acquisto registrata. 
Il problema è che php8.2 non permette parametri non inizializzati su molte funzioni.
