### ISSUE TITLE
colonna tempo in Log accessi

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1497]
## Comportamento richiesto

in log accessi, riteniamo sia utile aggiungere la seguente modifica, **aggiungere la colonna tempo di accesso**
e lasciare la colonna data come era prima con la ver.2.4.x

una cosa simile...
![Screenshot 2024-09-06 alle 13 07 51](https://github.com/user-attachments/assets/6079a20b-812d-483f-8b51-d1253c20c9a9)

![Screenshot 2024-09-06 alle 12 58 04](https://github.com/user-attachments/assets/28eb95ec-a268-48f0-9747-38cd88b2702e)

* Modulo:
* Versione del progetto: 2.5.x
* Versione PHP:
* Tipo di server:

**Comment by loviuz** [comment]
Ciao @sajotrei, per semplificare la lettura avevamo visualizzato la data in questo modo, ma passando sopra con il mouse puoi vedere data e ora nel formato completo:

![image](https://github.com/user-attachments/assets/7f324b75-05c1-475d-a834-a96f5efca652)

**Comment by sajotrei** [comment]
Ciao @loviuz grazie del riscontro, si ma così diventa molto più scomoda la consultazione a differenza di una colonna con l'informazione.
se fosse possibile la modifica in relase sarebbe meglio, altrimenti proveremo sulla nostra installazione.

**Comment by sajotrei** [comment]
non si riesce propio ad applicare questa modifica?
