### ISSUE TITLE
errore calcolo iva con versione 2.5.4

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1499]
Modulo: 2.5.4
    Versione del progetto:
    Versione PHP: 8.2
    Tipo di server:

inserisco due file, il primo la stampa con il vostro programma, il secondo l'ufficiale creato con agenzia entrate dove si evince l'errore, viene sommato per il calcolo dell'iva: variazione di imposta relativa a periodi precedenti quando questo valore.
I primi due file si riferiscono al primo trimestre 2024, mentre a seguire il secondo trimestre 2024

![Screenshot_20240912_204133](https://github.com/user-attachments/assets/8286cb59-9a26-4cf5-9517-cd8828ef2d4d)
![Screenshot_20240912_204213](https://github.com/user-attachments/assets/dfa08329-e8d3-42bc-a1d9-2482431fda8e)
![Screenshot_20240912_205711](https://github.com/user-attachments/assets/770f4af5-4e29-45f1-ad00-7ca619d59513)
![Screenshot_20240912_204311](https://github.com/user-attachments/assets/39c300a4-5ad8-456b-bd81-5bd7782f049b)

**Comment by Pek5892** [comment]
Buongiorno @leo-spa ,
potrebbe darci maggiori dettagli?

**Comment by loviuz** [comment]
Ciao @leo-spa , senza avere i dati dell'iva su cui verificare (quindi le fatture) è difficile capire se è un errore o un problema di dati purtroppo. Ovviamente non puoi caricare qui le fatture che compongono questi importi perché sono dati riservati, però senza di quelli non sappiamo che cosa verificare se non apprendere che su 2 programmi escono dati diversi. Facendo un test in locale, il calcolo del debito periodo precedente esce corretto. Non so se hai un'installazione di test su cui caricare qualche dato per fare un confronto e capire se c'è qualche problema...

**Comment by Pek5892** [comment]
Chiudo issue perchè duplicata https://github.com/devcode-it/openstamanager/issues/1499
