### ISSUE TITLE
Test su Tablet Asus Android con Chrome

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#15]
Controllare click su menú principale di sinistra. 
Il campo di ricerca perde il focus e non permette di inserire testo

**Comment by Dasc3er** [comment]
Il problema era generato dall'utilizzo dell'impostazione di fixed layout per il tema AdminLTE...
Viene risolto in modo ufficiale a partire dalla versione 2.4 (in sviluppo), quindi per il momento l'opzione è stata disattivata.
