### ISSUE TITLE
Versione 2.4 - Acquisti finestra tutta bianca

### ISSUE THREAD

**Issue by s0und0ut** [devcode-it/openstamanager#150]
## Comportamento attuale
Versione 2.3.1 (1745f0c)
Attualmente c'è un comportamento anomalo nella sezione:
acquisti > fatture di acquisto > aggiungi  (qui compare una finestra tutta bianca con scritto solo "Aggiungi...")
acquisti > ordine fornitore > aggiungi   (qui compare una finestra tutta bianca con scritto solo "Aggiungi...")

## Passi per riprodurre il comportamento

[error.log](https://github.com/devcode-it/openstamanager/files/1714686/error.log)
1. acquisti 
2. fatture di acquisto
3. aggiungi
4. qui compare una finestra tutta bianca con scritto solo "Aggiungi..."
con errore:
**SQLSTATE[42S02]: Base table or view not found: 1146 Table 'osm_test.zz_fields' doesn't exist**

1. acquisti 
2. ordine fornitore
3. aggiungi
4. qui compare una finestra tutta bianca con scritto solo "Aggiungi..."

Eventuali log relativi (cartella **logs/**):
non sono presenti log nella cartella logs
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

 Modulo: 
 Versione del progetto: 2.3.1 (1745f0c)
 Versione PHP: 5.6.31
 Tipo di server: Wamp

**Comment by Dasc3er** [comment]
@s0und0ut La branch 2.3.1 è in realtà relativa alla futura versione 2.4 per un successivo cambio di obiettivi.
La versione 2.3.1 è in sviluppo nella branch master.

**Comment by Dasc3er** [comment]
Effettivamente avevamo mantenuto i nomi in via temporanea, però per evitare problemi li ho corretti.
Ricapitolando:

- La versione 2.3.1 è in sviluppo nella branch master
- La versione 2.4 è in sviluppo nella branch 2.4

Se sei interessato a testare la versione 2.4, devi prestare attenzione alle modifiche effettuate con ogni commit ai file di aggiornamento del database (**update/2_4.sql**) perchè al momento non esiste un sistema ufficiale per replicare in automatico le modifiche.

**Comment by s0und0ut** [comment]
Ok. 
Pensavo che la 2.3.1 fosse un update della 2.3 con alcuni fix.
Continuo con i test in locale.
