### ISSUE TITLE
Caratteri speciali nella descrizione di Articoli di Magazzino

### ISSUE THREAD

**Issue by maulapi** [devcode-it/openstamanager#1500]
Segnalo che nel caso si abbia un articolo a magazzino che possiede nella descrizione uno o piu' caratteri speciali virgolette (") ottengo un'anomalia in fase di editing
Ecco un esempio
![Immagine 2024-09-14 150039](https://github.com/user-attachments/assets/2df85626-a1bd-4aba-bafe-3b3f122879e1)
Ed ecco cosa succede quando entro in editing
![Immagine 2024-09-14 150356](https://github.com/user-attachments/assets/763f395a-72cd-48ae-b204-1ec9bed743f1)

Testato nel demo on line e NON appare l'anomalia. Nella mia installazione si'.

Quindi potrebbe trattarsi di una particolare condizione del mio ambiente di lavoro?
Server Debian 12 con php 8.2
Server db mariadb
Database con codifica utf8mb4_general_ci
Versione OSM: 2.5.4 

Questa la modifica che ho apportato a modules/articoli/edit.php riga 68:
originale: `{[ "type": "textarea", "label": "<?php echo tr('Descrizione'); ?>", "name": "descrizione", "required": 1, "value": "<?php echo $articolo->getTranslation('title'); ?>", "charcounter": 1 ]}`
modificato: `{[ "type": "textarea", "label": "<?php echo tr('Descrizione'); ?>", "name": "descrizione", "required": 1, "value": "<?php echo  htmlspecialchars($articolo->getTranslation('title'), ENT_QUOTES); ?>", "charcounter": 1 ]}`
Nel mio caso ho risolto

**Comment by loviuz** [comment]
Ciao @maulapi abbiamo risolto così, con una funzione che serve per evitare problemi di apici in casi di textarea:

https://github.com/devcode-it/openstamanager/commit/6c68612e293419fbecdd655d63a6e3a47f483712
