### ISSUE TITLE
Errore se manca fotografia allegata

### ISSUE THREAD

**Issue by maulapi** [devcode-it/openstamanager#1501]
Mi appare questo errore su magazzino quando entro in edit su di un articolo SE su db , nel campo "immagine" c'è un dato MA effettivamente nella cartella files/articoli/ quel file NON esiste:

![Immagine 2024-09-14 155704](https://github.com/user-attachments/assets/851f1137-f750-485d-b04a-233b7cf6468f)

Di solito questo non dovrebbe succedere ma capita che il file possa essere cancellato. Sulla demo on-line ovviamente non posso testare una cosa del genere: non ho accesso alle cartelle

Sulla base dell' errore descritto nella foto ho risolto editando la riga 143 del file src/Uploads.php

originale: `$infos['extension'] = strtolower($infos['extension']);`

modificata: `$infos['extension'] = strtolower($infos['extension'] ?? '');`

Non è farina del mio sacco ho trovato la soluzione su di un forum

* Modulo: magazzino
* Versione del progetto: 2.5.4
* Versione PHP: 8.2.20
* Tipo di server: linux debian 12.7

**Comment by loviuz** [comment]
Da me non riesco a riprodurlo :thinking: però ha senso la verifica che l'estensione non sia null. Grazie :+1:
