### ISSUE TITLE
Pagamento predefinito impostato in anagrafica non funzionante

### ISSUE THREAD

**Issue by THORRDE** [devcode-it/openstamanager#1502]
## Comportamento richiesto

Nelle versioni precedenti dopo aver impostato in anagrafica un pagamento predefinito per un cliente, in fase di fatturazione nella sezione Pagamento veniva impostato automaticamente quello presente in anagrafica

## Comportamento attuale

Ora a pescindere da cio' che viene impostato in anagrafica per uno specifico cliente, nelle sezione fattura di vendita verra sempre impostato il pagamento predefinito "genereale" quello che si sepecifica in Strumenti>Impostazioni>Fatturazione>Tipo di pagamento predefinito
La stessa cosa vale anche per i fornitori e per i pagamenti nel modulo Acquisti

## Passi per riprodurre il comportamento

1. Aprire Anagrafiche, ed entrare nell'anagrafica di un cliente
2.  Nella sezione Informazioni per tipo di anagrafica entrare su cliente
3. Impostare un Pagamento predefinito
4.  Salvare
5. Entrare in vendite, fatture di venidta
6. Nella sezione Pagamento troveremo il pagamento predefinito "generale"

## Contesto

* Modulo: Fatture di vendita
* Versione del progetto: 2.5.4
* Versione PHP: 8.2.23

Strumenti>Impostazioni>Fatturazione>Tipo di pagamento predefinito
![Schermata_20240919_181453](https://github.com/user-attachments/assets/bc258cdf-ae19-4c25-be52-c6b930b479ed)

Anagrafica cliente
![Schermata_20240919_181649](https://github.com/user-attachments/assets/63488c41-f41e-4f40-8c60-25adf36d7c64)

Fattura di vendita
![Schermata_20240919_181854](https://github.com/user-attachments/assets/c5c29c66-d9f0-45dc-8357-027189306534)

**Comment by loviuz** [comment]
@Pek5892 forse è un bug?

**Comment by THORRDE** [comment]
> @Pek5892 forse è un bug?
Credo di si, nella versione 2.4.54 funzionava correttamente

**Comment by Pek5892** [comment]
Buongiorno @THORRDE, il pagamento predefinito viene selezionato alla creazione di un nuovo documento, non va quindi a modificare i documenti già creati in quanto non sarebbe un comportamento corretto la modifica di fatture già emesse o inviate allo SDI.
Per visualizzare il pagamento specificato nell'anagrafica cliente si dovrà quindi creare una nuova fattura.

**Comment by THORRDE** [comment]
> Buongiorno @THORRDE, il pagamento predefinito viene selezionato alla creazione di un nuovo documento, non va quindi a modificare i documenti già creati in quanto non sarebbe un comportamento corretto la modifica di fatture già emesse o inviate allo SDI.
> 
> Per visualizzare il pagamento specificato nell'anagrafica cliente si dovrà quindi creare una nuova fattura.

Buongiorno, è corretto il comportamento che hai descritto, ma il problema si verifica alla creazione di una nuova fattura di vendita o di acquisto

**Comment by Pek5892** [comment]
Non riusciamo a riprodurlo ne in master ne nella demo pubblica, potrebbe verificare?

**Comment by THORRDE** [comment]
![Schermata del 2024-09-27 10-15-57](https://github.com/user-attachments/assets/f6889cee-f10a-489f-8594-ddd480064787)
![Schermata del 2024-09-27 10-15-32](https://github.com/user-attachments/assets/e1c5e84c-8ca2-4491-97d1-18d7d278c404)
![Schermata del 2024-09-27 10-14-24](https://github.com/user-attachments/assets/0e6e5609-83fc-4238-bd2b-8f346c6168d2)
C'è altro che posso verificare?

**Comment by Pek5892** [comment]
ha verificato la presenza di file modificati?

**Comment by THORRDE** [comment]
> ha verificato la presenza di file modificati?

Appena fatto, ho due file con integrita' errata:
-  modules/oauth/edit.php 
-  modules/oauth/init.php 
ma non credo influiscano sul problema visto che si tratta di OAuth
