### ISSUE TITLE
Errore in fase generazione fattura

### ISSUE THREAD

**Issue by maulapi** [devcode-it/openstamanager#1512]
Quando si passa lo stato di una Fattura di Vendita da "Bozza" a "Emessa" e premo Salva appare un warning DEPRECATED che , a partire da PHP8, genera un errore

![Immagine 2024-10-06 120601](https://github.com/user-attachments/assets/3f654947-7890-471f-b755-ab2c8edf40f4)

Ho provato a togliere E_DEPRECATED da php.ini del mio server apache ma non e' cambiato niente quindi si deve risolvere a livello software. Il problema parte da una funzione str_replace che ha il primo parametro passato = NULL alla riga 360 di plugins/exportFE/src/FatturaElettronica.php.
Il parametro in questione e' $anagrafica->nazione->iso2.
Non avendo ancora chiaro il funzionamento di questo tipo di variabili ho aggiunto subito prima di detta riga il seguente codice:
`if (!empty($anagrafica->nazione->iso2)) {
            $iso2 = $anagrafica->nazione->iso2;
		} else {
			$iso2 = "IT";
		}`

e dopo la riga l'ho ovviamente modificata con la variabile $iso2:
prima:
`$prefix = 'IT'.(!empty($anagrafica['codice_fiscale'] and ($anagrafica['codice_fiscale'] != $anagrafica['piva'])) ? $anagrafica['codice_fiscale'] : str_replace($anagrafica->nazione->iso2, '', $anagrafica['piva']));`
dopo:
`$prefix = 'IT'.(!empty($anagrafica['codice_fiscale'] and ($anagrafica['codice_fiscale'] != $anagrafica['piva'])) ? $anagrafica['codice_fiscale'] : str_replace($iso2, '', $anagrafica['piva']));`

In questo modo l'errore e' scomparso.

Non è certo una soluzione elegante, bisognerebbe capire perché viene passato quel parametro nullo ed evitarlo. Comunque spero sia un contributo utile.

**Comment by Pek5892** [comment]
Buongiorno @maulapi,
abbiamo testato la funzionalità in master e in demo pubblica e il problema non si presenta, sembrerebbe pertanto essere un problema legato alla sua installazione. La invito ad eseguire i controlli sull'installazione https://docs.openstamanager.com/2.5.5/guide/esempi/verificare-linstallazione-di-osm e a verificare che nell'anagrafica impostata come anagrafica azienda da impostazioni sia stata correttamente definita la nazione.

**Comment by maulapi** [comment]
Ok RISOLTO. Come mi avete suggerito ho controllato e non era impostata la Nazione sull'anagrafica Azienda. Adesso non presenta piu' l'errore.
Eventualmente se l'anagrafica e' Azienda mettete un controllo di obbligo inserire Nazione.
Saluti.
