### ISSUE TITLE
Variabile {tipo_documento} in preventivo

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1527]
## Comportamento richiesto

riteniamo sia utile **_aggiungere la variabile {tipo_documento} nel template mail_** associato al preventivo.
torna utile per chi usa nomi del documento differente. ( Preventivo, Offerta, ecc... )

/modules/preventivi/variables.php
tipo_documento' => $r['tipo_documento'],

![Screenshot 2024-10-15 alle 18 26 05](https://github.com/user-attachments/assets/1112142a-7d65-4e74-8ab9-6c97273d664d)

**Comment by Pek5892** [comment]
Buongiorno @sajotrei,
nella query presente nel file variables.php non è specificato il tipo_documento

**Comment by sajotrei** [comment]
ciao Valentina, si appunto torna utile introdurlo, così permette di indicare il tipo di documento inviato 
preventivo, offerta, ecc..

**Comment by Pek5892** [comment]
Mi spiego meglio: nella query definita in variables.php non c'è nessun campo che faccia riferimento al tipo di documento, così come intendete utilizzarlo voi.
Il template di invio mail si chiama Preventivo, perchè il relativo template in em_templates ha questo nome, nel caso in cui vogliate inviare un documento diverso dal modulo preventivi, si dovrà creare un nuovo template in em_templates.

**Comment by sajotrei** [comment]
Ciao Valentina, ok ho capito.
noi abbiamo creato un nuovo template di stampa e poi abbiamo creato i relativi template email.


![Screenshot 2024-12-03 alle 11 14 05](https://github.com/user-attachments/assets/64af5362-86d6-4ae4-9cba-feac36f004b5)
___
![Screenshot 2024-12-03 alle 11 14 34](https://github.com/user-attachments/assets/12861510-b0b5-4505-b6d4-7ad05e4a53e3)
___
![Screenshot 2024-12-03 alle 11 14 49](https://github.com/user-attachments/assets/1538f9be-f27f-4fce-8fba-d710b6a8bcd8)
___
![Screenshot 2024-12-03 alle 11 16 24](https://github.com/user-attachments/assets/77ed631b-716f-482b-ac23-22a6b9e09659)
___
![Screenshot 2024-12-03 alle 11 18 21](https://github.com/user-attachments/assets/42b88bc8-1876-4f49-8386-f1704264cdc0)
___
![Screenshot 2024-12-03 alle 11 18 56](https://github.com/user-attachments/assets/cba500b4-f584-48d7-a859-5a525551913c)
