### ISSUE TITLE
Miglioramento della gestione dei sezionali

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#153]
Per permettere una maggiore flessibilità del sistema dei sezionali, propongo l'introduzione dei campi `|sezionale_entrata|` e `|sezionale_uscita|` all'interno delle query di moduli, plugin e widget con sostituzione automatica con la query di ricerca corretta.
In questo modo si potrebbe semplificare il codice in **ajax_dataload.php** e renderlo più generico:
https://github.com/devcode-it/openstamanager/blob/3d22c8337c719f225c05cfd04267d50be97e8f5b/ajax_dataload.php#L62

Secondo questa proposta, le query delle Fatture dovrebbero quindi essere aggiornate nel seguente modo:

- ```SELECT |select| FROM `co_documenti` INNER JOIN `co_tipidocumento` ON `co_documenti`.`idtipodocumento` = `co_tipidocumento`.`id` WHERE 1=1 AND |sezionale_entrata| AND `dir` = 'entrata' AND `data` >= '|period_start|' AND `data` <= '|period_end|' HAVING 2=2 ORDER BY `data` DESC, CAST(numero_esterno AS UNSIGNED) DESC``` per le **Fatture di vendita**
- ```SELECT |select| FROM `co_documenti` INNER JOIN `co_tipidocumento` ON `co_documenti`.`idtipodocumento` = `co_tipidocumento`.`id` WHERE 1=1 AND |sezionale_uscita| AND `dir` = 'uscita' AND `data` >= '|period_start|' AND `data` <= '|period_end|' HAVING 2=2 ORDER BY `data` DESC, CAST(IF(numero_esterno='', numero, numero_esterno) AS UNSIGNED) DESC```per le **Fatture di acquisto**

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager Cosa ne pensate?

**Comment by lucasalva87** [comment]
Sì mi sembra plausibile come miglioria ;-)

**Comment by Dasc3er** [comment]
Completato con il commit 4c948e8102f3e64eeac6354935000bff207576c9.
@lucasalva87 Comunque per ora non è ancora stata inserita la possibilità di selezionare sezionali specifici, o sbaglio?

**Comment by lucasalva87** [comment]
Bene :) .. da impostazioni puoi selezionare il sezionale per le fatture di vendita e le fatture di acquisto.
