### ISSUE TITLE
Descrizione articolo si bugga se inserito il doppio apice "

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1531]
Quando nella descrizione articolo viene inserito il ", es: TV 42" va in errore il codice della pagina e qualsiasi modifica successiva viene pure cancellato il testo non appena viene fatto salva

* Modulo: Magazzino (credo che si possa presentare anche in altri moduli, non ho provato da tutte le parti)
* Versione del progetto: 2.5.4
* Versione PHP: 8.3.10
* Tipo di server: apache

**Comment by Pek5892** [comment]
Corretto con fix: https://github.com/devcode-it/openstamanager/commit/6c68612e293419fbecdd655d63a6e3a47f483712
