### ISSUE TITLE
Aggiornamento requisiti

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1535]
## Comportamento richiesto

considerando la modifica nel file README.md in merito ai requisiti della ver. 2.5.6
sarà da aggiornare anche il check della versione di MySQL

<img width="1337" alt="Screenshot 2024-10-30 alle 16 26 26" src="https://github.com/user-attachments/assets/e889259a-8908-42a7-87a1-20e0bc7dbf5c">

**Comment by Pek5892** [comment]
https://github.com/devcode-it/openstamanager/commit/0a1135766771ff386a5d9e7bb5e51893ba131cad
