### ISSUE TITLE
Campo pagamento nei preventivi

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1537]
Dalle prove effettuate sembrerebbe che se viene fatta una stampa va in crash il pdf generator alla riga 487 _`'.$pagamento->getTranslation('title').'`_ se per errore non viene selezionato il metodo di pagamento nel preventivo.

Modulo: Preventivi
Versione del progetto: 2.5.4
Versione PHP: 8.3.10
Tipo di server: Apache2

**Comment by Pek5892** [comment]
Buongiorno, consigliamo di aggiornare il gestionale all'ultima release, questo problema è già stato corretto.
