### ISSUE TITLE
Invio email di notifica dallo scadenzario

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#154]
Introdurre nello scadenziario la possibilità di inviare solleciti di pagamento ai clienti per le fatture di vendita scadute. Inviare invece email di promemoria all'azienda per la fatture di acquisto scadaute e da saldare.

**Comment by Dasc3er** [comment]
Si può implementare come estensione del sistema di notifiche introdotto nella versione 2.4.2.
Eventualmente, se le email devono essere inviate in automatico e non manualmente si può prevedere un _cron_ nativo oppure l'implementazione di funzioni simili al _cron_ (per esempio, chiamando in AJAX un file che si occupa di eseguire queste operazioni in background).

**Comment by loviuz** [comment]
potrebbero servire altre operazioni in cron, per cui non farei una funzione ad-hoc per lo scadenzario, ma predisporrei una struttura che possa essere più generica per eventuali altri cron

**Comment by maicol07** [comment]
Novità su questa funzionalità?

**Comment by Dasc3er** [comment]
È prevista per la versione 2.5, quindi non sarà sviluppata fino a settembre o oltre.

**Comment by Dasc3er** [comment]
E' stato aggiunto il template email **Sollecito di pagamento** nelle email di base che permette proprio la funzionalità richiesta.
Inoltre per ora la gestione delle email è stata migliorata (versione in sviluppo 2.4.11) prevedendo l'introduzione di un hook apposito che viene richiamato automaticamente per l'invio delle email. Questo ha permesso l'introduzione del modulo sperimentale Newsletter.
