### ISSUE TITLE
errore aggiornamento anagrafica clienti

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#1541]
Stavo modificando un parametro di un cliente che è variato in anagrafica e non riesco a salvare, mi esce questo errore. Come posso risolvere?

Si è verificato un errore [uid: 767192f]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception Error: "Call to undefined function Modules\Anagrafiche\curl_exec()" at /var/www/clients/client92/web5527/web/modules/anagrafiche/src/Anagrafica.php line 471

 Si è verificato un errore [uid: 767192f]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Call to undefined function Modules\Anagrafiche\curl_exec()

* Modulo: controller.php?id_module=2
* Versione del progetto: 2.5.6 (R8a42b2d3a)
* Versione PHP: 8.2.19

**Comment by loviuz** [comment]
Ciao @leo-spa , credo ti manchi l'estensione curl di PHP dall'errore. È attiva la geolocalizzazione di default (si può togliere dalle impostazioni), da qualche versione, e usa curl per effettuare la chiamata alle API di OpenStreetMap per trovare le coordinate. Prova così...

**Comment by leo-spa** [comment]
Il tuo consiglio ha dato esito positivo comunque i servizi curl sono attivi
 	Estensione 	curl 	Permette la comunicazione con servizi esterni (ok)

questi invece hanno problemi
	Impostazione 	max_input_vars 	Valore consigliato: 5000 (Valore attuale: 1000)
	Funzione 	exec 	Permette di importare file con estensione .p7m

**Comment by loviuz** [comment]
Quindi hai curl attivo? Scusa, ma non ho capito se hai risolto 😅

**Comment by leo-spa** [comment]
Curl è attivo ma il problema si è risolto, forse è un bug, come tanti altri
😞

Il ven 15 nov 2024, 22:17 FabioL ***@***.***> ha scritto:

**Comment by loviuz** [comment]
Ho guardato ma l'errore è proprio legato alla funzione curl_exec() non trovata, ma è standard di PHP, quindi sembra proprio legato a PHP, però in locale non lo dà. Bisognerebbe verificare su quell'hosting...

**Comment by leo-spa** [comment]
faccio fare un controllo al gestore del server

**Comment by Pek5892** [comment]
Chiudo issue in quanto non valida.
