### ISSUE TITLE
Errore query mysql nel modulo Anagrafiche

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#1543]
Quando entro nel modulo anagrafiche mi compare errore nello statement mysql

PDOException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'co_pagamenti.descrizione' in 'field list'

![image](https://github.com/user-attachments/assets/61831fd1-9c6f-4835-afe4-cc7ce622bad3)

Il problema nasce a causa della colonna "descrizione" , che nella versione 2.5.7 è stata cambiata in "name" nella tabella "co_pagamenti"

Openstamanager  versione 2.5.7

**Comment by loviuz** [comment]
Ciao @lepool ,
non ci risulta essere questo errore. Sei sicuro di aver aggiornato correttamente alla 2.5.7? Puoi verificare se i file sono integri da **Strumenti » Aggiornamenti » Controlla file**:

![immagine](https://github.com/user-attachments/assets/303d0557-cf03-4c00-9968-992ebf805420)

E' un errore già risolto un po' di versioni fa, per questo mi viene il dubbio che forse i file non sono aggiornati.

**Comment by lepool** [comment]
Ho una versione 2.4.49 che aggiorno ad una 2.5.7.
La versione 2.4.49 ha la tabella co_pagamenti con la sequente struttura :
![image](https://github.com/user-attachments/assets/ac149011-9fce-47e4-a71c-98c832dd296b)

dopo l'aggiornamento ha la tabella co_pagamenti con la seguente struttura:
![image](https://github.com/user-attachments/assets/40d4125e-5983-47bf-b3f5-dde94758840c)

**Comment by lepool** [comment]
Errore mio, chiudo issue
