### ISSUE TITLE
Miglioramento della ritenuta d'acconto

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#155]
Ci sono dei casi, in particolare per i liberi professionisti, in cui la ritenuta d'acconto va calcolata sull'imponibile oppure su imponibile+rivalsa inps.
E' da approfondire se ci sono altre casistiche particolari per poi inserire eventualmente un nuovo flag.

**Comment by fgambarelli** [comment]
La ritenuta d'acconto potrebbe essere necessaria solo in alcune fatture di terminati clienti, mentre se si attiva nelle impostazioni diventa obbligatoria.

**Comment by loviuz** [comment]
Andrebbe quindi gestita così:
- fatture di vendita: se almeno uno dei 2 campi è impostato, si possono selezionare nelle righe della fattura e sono preselezionati, non obbligatori
- fatture di acquisto: sempre selezionabili, ma di default sempre deselezionati e mai obbligatori

**Comment by fgambarelli** [comment]
Nel caso di bassissima percentuale di clienti a cui emettere la fattura con ritenuta, questa tipo di gestione diventa pesante, perchè ad ogni fattura occorre ricordarsi di togliere l'impostazione della ritenuta. 
Mentre sarebbe utile impostare sull'anagrafica del cliente il fatto che abbia la ritenuta di default e se presente appaia la scelta della percentuale.
