### ISSUE TITLE
(BUG) DUPLICA ORDINE FORNITORE

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1552]
se si duplica un ordine fornitore non permette di indicare lo stato 

si potrebbe togliere lo stato in questa fase, o almeno indicare direttamente lo stato BOZZA

<img width="1340" alt="Screenshot 2024-12-06 alle 18 10 00" src="https://github.com/user-attachments/assets/4e057b18-bad6-4e9a-8bff-3fa0766ecdbe">

* Modulo:
* Versione del progetto: 2.6
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Corretto con commit: https://github.com/devcode-it/openstamanager/commit/628230fdf71fef99f7468d8315695dc322c3239b
