### ISSUE TITLE
Problema stampa fatture con dicitura

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#1558]
Vorrei segnalare la sovrapposizione in stampa della dicitura fissa con i totali, come da screen (v. 2.5.7):
![immagine](https://github.com/user-attachments/assets/04f52669-fa85-407f-822a-e27d5640b371)

**Comment by cristianviale** [comment]
Questo problema al momento l'ho risolto aggiungendo l'opzione `"rows-per-page":22` alla stampa.

**Comment by Pek5892** [comment]
Buongiorno @cristianviale, non ci risulta che il valore dell'impostazione Dicitura fissa in fattura venga visualizzata in tale posizione di default, il conteggio delle righe di tale impostazioni in ogni caso è attualmente conteggiata:
![immagine](https://github.com/user-attachments/assets/5b47e811-3c42-4363-a475-990db088ba3d)

**Comment by cristianviale** [comment]
Non è la "Dicitura fissa in fattura" che si trova nell'anagrafica cliente.
È la dicitura impostata dal codice IVA...

**Comment by Pek5892** [comment]
Potrebbe provare a riprodurre l'errore nella demo pubblica? 
https://demo.osmbusiness.it/

**Comment by cristianviale** [comment]
Fatto, la trovate [qui](https://demo.osmbusiness.it/editor.php?id_module=14&id_record=55)
