### ISSUE TITLE
Se non è un articolo aggiungi un "-"?

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#1560]
Credo di aver trovato un errore nella stampa, in questo punto:
https://github.com/devcode-it/openstamanager/blob/b02b9b5fec8fb6ace1b74cdb3dd6f43a2497f065/templates/contratti/body.php#L395

Se metto una riga (quindi non un articolo), mi aspetto che la descrizione sia quella digitata... senza l'aggiunta del trattino.

**Comment by Pek5892** [comment]
Buongiorno,
questo è già stato corretto nelle ultime versioni del gestionale. :smiley:

**Comment by cristianviale** [comment]
Quale versione? Questa cosa l'ho riscontrata nella v. 2.5.7 (perché la 2.6 è in beta)

**Comment by Pek5892** [comment]
Nella 2.6 e 2.6.1 in release
