### ISSUE TITLE
Documenti clienti creato da un agente assegnato

### ISSUE THREAD

**Issue by gfweb-it** [devcode-it/openstamanager#1562]
## Comportamento richiesto

Creando l'ordine cliente fatto da un agente al cliente a lui assegnato, mi segnalano, che anche gli altri agenti vedono gli ordini degli altri agenti anche se il cliente non è assegnato a loro e anche le fatture è uguale, praticamente per quanto riguarda i documenti vedono tutto

Mentre per le anagrafiche funziona senza problemi perché vedono solo quelle assegnate

## Comportamento attuale

I documenti vengono visualizzati da tutti gli agenti

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno,
i filtri sono stati ripristinati negli ultimi rilasci del gestionale, aggiornando il gestionale il problema dovrebbe risolversi.
