### ISSUE TITLE
FATTURE di Vendita - Plugin - Importazione FE

### ISSUE THREAD

**Issue by sajotrei** [devcode-it/openstamanager#1564]
quando si importa xlml di una fattura attiva, **associa l'anagrafica fornitore come cliente** 

SUL FILE XLM

**Cedente/prestatore (fornitore)**
PLUTO SRL ( Azienda ) - su OSM diventa il cliente

**Cessionario/committente (cliente)**
MARIO ROSSI - non la considera e non viene creata su OSM

inoltre il sistema NON tiene conto della anagrafica CLIENTE già esistente, quindi crea anagrafiche identiche per per ogni fattura importata.

abbiamo caricato un zip con 3 xml, ha creato 3 anagrafiche uguali PLUTO SRL come cliente.

* Modulo: FATTURE DI VENDITA
* Versione del progetto: 2.6.X
* Versione PHP:
* Tipo di server:

**Comment by Pek5892** [comment]
Buongiorno @sajotrei, non ci risulta quanto segnalato:
![immagine](https://github.com/user-attachments/assets/8a92fd3c-2074-485e-8e83-7351263c4878)
![immagine](https://github.com/user-attachments/assets/1ae22318-0527-4167-8e03-8a8f3f3a3c3d)
![immagine](https://github.com/user-attachments/assets/c0f82559-1acb-4f00-8aa4-7cbc6bfc93dd)
il file caricato era un file zip? è stata selezionata l'importazione automatica o manuale? potrebbe descriverci meglio i passaggi seguiti?

**Comment by sajotrei** [comment]
1 scaricato 3 fatture xml generate su OSM 2.4
2 creato lo zip dei 3 xml
3 importato zip

**Comment by sajotrei** [comment]
faremo altre prove
