### ISSUE TITLE
FATTURE - Marca da bollo assolta in modo virtuale

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#157]
Riporto segnalazione dal forum:
https://forum.openstamanager.com/viewtopic.php?p=92641
https://forum.openstamanager.com/viewtopic.php?p=95968

si tratta di aggiungere un ulteriore campo sulle fatture per registrare id della marca da bollo "virtuale", più la relativa modifica sulla stampa fattura

**Comment by Dasc3er** [comment]
Corretti i link relativi.
@loviuz E' ancora attuale come modifica?
