### ISSUE TITLE
Stampa di Fattura accompagnatoria

### ISSUE THREAD

**Issue by mdkdog** [devcode-it/openstamanager#158]
sulla colona "Costo unitario" esce solamente il simbolo "€".
"Aspetto beni", "Causale trasporto" e "Porto" sono vuoti.

**Comment by Dasc3er** [comment]
@mdkdog Che versione di OpenSTAManager stai utilizzando?

**Comment by mdkdog** [comment]
2.3.1
Ma il problema si presenta anche sulla demo. 

Il 21 febbraio 2018 17:48:37 CET, Thomas Zilio <notifications@github.com> ha scritto:
>@mdkdog Che versione di OpenSTAManager stai utilizzando?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/devcode-it/openstamanager/issues/158#issuecomment-367391421

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by Dasc3er** [comment]
@mdkdog Potresti testare la versione 2.4 attualmente in sviluppo per vedere se il problema si ripresenta?
La puoi trovare nella branch 2.4, con diverse migliorie...

**Comment by Dasc3er** [comment]
@mdkdog Nella versione 2.4 rilasciata recentemente il problema non si presenta...

**Comment by mdkdog** [comment]
Confermo

Il 13 aprile 2018 18:36:17 CEST, Thomas Zilio <notifications@github.com> ha scritto:
>@mdkdog Nella versione 2.4 rilasciata recentemente il problema non si
>presenta...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/devcode-it/openstamanager/issues/158#issuecomment-381191834

-- Inviato dal mio cellulare Android con K-9 Mail.
