### ISSUE TITLE
Eccezione Symfony\Component\Translation\Exception\NotFoundResourceException

### ISSUE THREAD

**Issue by s0und0ut** [devcode-it/openstamanager#159]
## Comportamento richiesto

Update della versione 2.3 alla 2.3.1 barra di progressione in face di update ferma al 20% attesa di circa 10 minuti, refresh della pagina, si ripresenta schermata di login e l'accesso risulta ok.
La versione risulta aggiornata alla 2.3.1

Su "Strumenti" > "Aggiornamenti" > "Moduli Installati" nella colonna versione risulta 2.3. Corretto?

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. carica il file completo di update 2.3.1 sul 2.3
2. login user password
3. richiesta update versione database 2.3.1
4. blocco barra di progressione al 20% (sia local che web)
5. refresh pagina 
6. login user password
7. aggiornato
8. Su "Strumenti" > "Aggiornamenti" > "Moduli Installati" nella colonna versione risulta 2.3. Corretto?

Eventuali log relativi (cartella **logs/**):
```
[2018-02-22 13:32:05] Logs.ERROR: Uncaught Exception Symfony\Component\Translation\Exception\NotFoundResourceException: "File "/localhost/osm_test/it/it.mo" not found." at /localhost/osm_test/vendor/symfony/translation/Loader/FileLoader.php line 33
{"url":"/osm_test/index.php?action=do_update&firstuse=false","ip":"localhost","http_method":"GET","server":"localhost","referrer":"/localhost/osm_test/index.php","unique_id":"DDFDfdsddstrbvsdabfdnbdfwe","uid":"93poc3e"} 

```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto: 2.3.1
* Versione PHP: 5.6 e 7.1
* Tipo di server: wamp e web

**Comment by Dasc3er** [comment]
@s0und0ut Grazie mille per la segnalazione!
In effetti il problema era causato dalla cancellazione dei file per la traduzione italiana (inutilizzati) nella procedura di aggiornamento.

In ogni caso, l'aggiornamento è andato a buon fine e dovresti essere in grado di utilizzare la versione 2.3.1 del gestionale. Puoi controllare la versione del progetto in basso a destra di ogni pagina oppure dalla pagina di **Informazioni**, i dati che trovi nel modulo **Aggiornamenti** sono relativi ai singoli moduli 😄 .

**Comment by s0und0ut** [comment]
@Dasc3er Figurati! Doveroso dopo tutto il lavoro che fate.
Infatti ho visto che sulla prima pagina in basso a destra è riportato 2.3.1.

Precisazione: Per i moduli quindi è giusto che riportino la dicitura 2.3 e non 2.3.1?

Approfitto, poi dimmi tu se devo aprire un'altro segnalazione: 
Un comportamento strano su: "Strumenti" > "Tabelle" i sotto menu cambiano di posizione quando ci clicco sopra (me lo fa solo sul hosting dove ho la 2.3.1 con php 5.6) su wamp sempre 2.3.1 sia php 5.6 che 7.1 non ho problemi. =S

**Comment by Dasc3er** [comment]
Per i moduli, la dicitura relativa dovrebbe essere corretta.
Il problema sulla posizione dei link sotto "Strumenti" > "Tabelle" invece è strano, poichè viene gestito con codice JavaScript (quindi dovrebbe verificarsi ovunque e non solo un un tipo di host) e dovrebbe permettere l'ordinamento dei soli link principali.

@devcode-it/openstamanager

**Comment by s0und0ut** [comment]
Mi consigli di controllare qualcosa prima di aprire thread inutili?

**Comment by loviuz** [comment]
@s0und0ut hai avuto modo di riprovare? Eventualmente, potresti provare ad aggiornare alla 2.4 per vedere se il problema è risolto...

**Comment by Dasc3er** [comment]
@s0und0ut Il problema dei link nel menù si presenta ancora?

**Comment by s0und0ut** [comment]
@Dasc3er Il problema persiste nella rev 2.3.1

**Comment by Dasc3er** [comment]
Chiuso poichè il problema iniziale è stato risolto, e il secondario sembra non replicabile (finora).
Eventualmente se il malfunzionamento continua a presentarsi prevedi la creazione di una issue separata.
