### ISSUE TITLE
Bug Gruppi e Permessi

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#16]
Ho creato un nuovo gruppo su strumenti -> Utenti e Permessi, chiamandolo per esempio Ufficio Acquisti, al quale voglio dare i permessi di lettura e scrittura solo sulla dashboard e sugli acquisti per esempio. Creo un utente acquisti e do i permessi su Dashboard, Acquisti, Ordini Fornitore, Fatture di acquisto. Vedo che non posso aggiungere il gruppo sui campi delle viste per esempio delle Fatture perchè sono disabilitati, quindi non mi aspetto di doverlo fare. Mi sloggo da admin ed entro col nuovo utente acquisti. Entro nelle fatture e mi da un errore, prima come alert javascript: DataTables warning: table id=main_10 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1; quindi errore in rosso: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id'. E non compaiono le fatture nella tabella, che risulta vuota. Lo stesso accade anche su altre pagine, attività per esempio.
Credo sia un bug sul codice, ho provato anche sulla versione online della 2.3 beta dal sito di OpenSTA e c'è lo stesso probelma..

**Comment by Dasc3er** [comment]
In questo caso, l'errore è relativo al fatto che il nuovo sistema delle Viste si basa su specifici permessi per ogni gruppo, che però non erano impostati in automatico per i nuovi gruppi.
