### ISSUE TITLE
PROPOSTA MIGLIORIA - Utilizzo stored procedures

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#160]
Essendo openstamanager un gestionale basato sul massiccio utilizzo di chiamate mysql, vorrei avanzare la proposta di convertire gradualmente tutte le varie query (o almeno quelle più gravose e che vengono utilizzate con maggiore frequenza) in stored procedures.
Questa pratica porterebbe a numerosi vantaggi, tra i quali, una maggiore rapidità nelle interrogazioni del database; un minor consumo di banda internet, visto che utilizzando una stored procedure basterebbe richiamarla e non inviare al server una complessa query; un'aggevolazione in fatto di sviluppo di team avendo tutte le stored porcedures sul server; una maggiore sicurezza o almeno una migliore protezione dall' sql injection, oltre ad altri vantaggi.

**Comment by Dasc3er** [comment]
@antonioscarpino Grazie mille per la proposta e il relativo approfondimento! Siamo sempre alla ricerca di metodi per migliorare il back-end del gestionale, anche per semplificare le procedure di personalizzazione 😄 .

In passato avevamo già considerato la possibilità di utilizzare le _Stored Procedures_ di **MySQL**, ma non le abbiamo mai sfruttate perché la loro logica non è compatibile con il funzionamento del gestionale. In pratica, solitamente le _Stored Procedures_ vengono sfruttate per semplificare la gestione di un database stabile e raramente modificato, cosa che non corrisponde al nostro caso poiché abbiamo spesso bisogno di **personalizzare sia strutture che query** (e, con le _Stored Procedures_, eventuali aggiornamenti porterebbero alla perdita completa delle modifiche).
Inoltre bisogna considerare due altri problemi nella relativa implementazione:

- la duplicazione della logica del gestionale (che sarebbe quindi presente sia nei file che nel database, rendendo il tutto più difficile da mantenere nel tempo);
- l'incompatibilità delle _Stored Procedures_ con il sistema di aggiornamento attuale (oltre che con eventuali hosting particolari).

Per quanto riguarda il consumo di banda è necessario considerare che parliamo di traffico tra server PHP e server MySQL (che quindi non influenza la navigazione utente), mentre i vantaggi sulla rapidità delle query sono estremamente ridotti (considerando che al momento effettuiamo raramente query sulle stesse tabelle in sequenza). 

Infine, è certamente vero che l'utilizzo delle Stored Procedures porterebbe ad una maggiore sicurezza in fatto di SQL Injection e nell'accesso ai dati del database. Riguardo la gestione attuale di questi elementi:

- l'SQL Injection viene evitata attraverso l'utilizzo della funzione specifica _prepare()_, e in futuro potrebbe essere risolta in modo nativo con l'utilizzo dei _Prepared Statements_ (implementazione più semplice e utile nel nostro caso);
- le query che vengo eseguite sul database sono presenti sui file fisici del gestionale e l'unico modo per modificarle è avere accesso al server.

-----------

Se sei interessato ad approfondire la questione della gestione del database, stiamo provando alcuni metodi alternativi per migliorare il codice interno attraverso:

- l'utilizzo di un **ORM** (#102 e branch eloquent);
- l'implementazione di un libreria per la **migrazione del database in fase di sviluppo** (#128, per cui stiamo considerando [Phinx](https://github.com/cakephp/phinx));
- l'utilizzo dei **Prepared Statements per PDO** (http://php.net/manual/it/pdo.prepared-statements.php).

Se hai suggerimenti oppure vuoi condividere la tua esperienza, siamo sempre disponibili 👍.
Grazie ancora per questo contributo!

**Comment by Dasc3er** [comment]
Per conoscenza, al momento sto sperimentando nell'aggiornare OpenSTAManager per farlo funzionare attraverso il framework open-source Laravel.
Ecco il fork funzionante e in sviluppo: https://github.com/Dasc3er/openstamanager

**Comment by antonioscarpino** [comment]
@Dasc3er ottimo darò sicuramente un'occhiata grazie della condivisione.

**Comment by Dasc3er** [comment]
@antonioscarpino Nella branch 2.4.2 è stato aggiunto il supporto ai Prepared Statements PDO, nel caso volessi approfondire il quesito.
@devcode-it/openstamanager In futuro, le query  del progetto dovranno essere strutturate secondo questo standard, poichè il metodo **prepare()** introdotto nella versione 2.3 era appunto per garantire una maggiore sicurezza nella transizione dall'estensione MySQL.

**Comment by antonioscarpino** [comment]
@Dasc3er  ottimo grazie per la news ci daró sicuramente un'occhiata.
