### ISSUE TITLE
Conversione tra unità di misura per gli articoli

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#161]
Per motivi contabili, alcuni utenti richiedono di poter gestire nella scheda articolo alcuni campi in più:
- conto predefinito per le vendite
- conto predefinito per gli acquisti
- unità di misura per le vendite
- unità di misura per gli acquisti

Graficamente, sarebbe da dividere meglio queste informazioni in 2 riquadri, chiamandoli "Vendita" e "Acquisto".
L'unità di misura ora è unica, ma in alcuni casi si può comprare la merce in un'unità di misura e venderla sotto forma di altra (esempio di filo elettrico: compro 3 bobine, ma lo vendo a metri).

**Comment by gabrieledaltoe** [comment]
Ciao Fabio! L'esempio che hai fatto non è corretto se non metti anche un convertitore di unità. Se prendi 3 bobine di filo dovrà esserci una conversione con la "metrica" che usi per venderlo... Sai che 1 bobina di filo è lunga 300 metri, pertanto in acquisto l'unità di misura è "bobine" (numero intero). e ha coefficente 300; mentre in vendita hai l'unità di misira "metri" e ha coefficente 1. In questo modo il magazzino torna sempre... (tranne che per gli scarti). :)

**Comment by loviuz** [comment]
Buona idea! Ricordo un caso dove non c'era però per forza la conversione da un'unità di misura ad un'altra con un moltiplicatore... però eventualmente si possono gestire entrambi i casi.

**Comment by Dasc3er** [comment]
La funzione è già stata completata per i conti predefiniti, rimarrebbe da strutturare in modo stabile la conversione automatica tra unità di misura, soprattutto per fare tornare i conti all'interno dei movimenti.

**Comment by Dasc3er** [comment]
Per motivazioni tecniche, la conversione tra unità di misura per gli articoli non verrà implementata: al fine di un utilizzo semplificato da parte dell'utente, sono ora disponibili i campi Unità di misura per Ordini fornitore e Fattore moltiplicativo relativo, Questi campi sono utilizzati ai soli fini delle stampe Ordini fornitore, e non hanno validità contabile.
Per gestire al meglio unità di misura distinte come da issue è disponibile a pagamento il modulo Distinta Base, che permette di costruire articoli sulla base di altri a magazzino.
