### ISSUE TITLE
STAMPE CONTABILI - errore nella creazione stampa registro iva vendite/acquisti

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#162]
Come da titolo provando a creare una stampa del registro iva o vendite o acquisti si ha il eguente errore

![immagine](https://user-images.githubusercontent.com/34765237/36639919-7bf269d6-1a16-11e8-9e61-996d1f559a5d.png)

probabilmente l'errore è nato dalla modifica apportata nel commit 7c342ee

* Versione del progetto: 2.3.2 ultimo commit
* Versione PHP: 7.1.12
* Tipo di server: xammp

**Comment by loviuz** [comment]
sembra non trovi l'immagine in templates/fatture/logo_azienda.jpg, puoi verificare?

**Comment by Dasc3er** [comment]
@loviuz Era un bug nella stampa dei registri iva.

**Comment by antonioscarpino** [comment]
basta modificare il file templates/registro_iva/registroiva_body.html
```
<img src="$docroot$/templates/base/logo_azienda.jpg" alt="Logo" style="width:60mm;" border="0">
```
e lasciare il vecchio commit in modo che prenda l'immagine del logo nelle cartella base
