### ISSUE TITLE
Dashboard - codice intervento

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#163]
nella Dashboard visualizza gli interventi ma riporta come numero intervento ID del record, mentre nella scheda intervento e nella stampa viene riportato il campo codice, mettiamo per favore il codice anche nel calendario e nei tooltip che compaiono passando il mouse sopra gli interventi.
Grazie.

Problema riscontrato nell'ultima demo online

**Comment by fpsoftware** [comment]
anche nel nome del file nella stampa del rapportino attività viene riportato ID del record, sarebbe più corretto riportare codice dell'attività, facendo attenzione che l'utente nelle impostazioni, nell'opzione "Formato codice intervento" può inserire caratteri come lo slash o backslash che possono causare problemi con i nomi dei files.

**Comment by Dasc3er** [comment]
@fpsoftware Il problema dei caratteri particolari viene gestito dalla funzione _sanitizeFilename()_ durante il salvataggio della stampa.
