### ISSUE TITLE
Errore invio email 2.4

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#164]
Dopo aver configurato il server STMP continua a dare il seguente errore:
![bug openstamanager](https://user-images.githubusercontent.com/30728163/36682603-cca3a416-1b1b-11e8-9afa-dfeb704d5d2d.png)

**Comment by Dasc3er** [comment]
@lucasalva87 La documentazione ufficiale dice che è un problema di configurazione...
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#could-not-instantiate-mail-function

**Comment by lucasalva87** [comment]
Solo specificando il server SMTP del mio ISP sul file php.ini sono riuscito a inviare l'email.
![immagine](https://user-images.githubusercontent.com/30728163/36720662-f9c9d428-1ba8-11e8-8862-3be46cb87239.png)

**Comment by Dasc3er** [comment]
Proveresti a controllare se la classe Mail arriva correttamente alla seguente riga?
https://github.com/devcode-it/openstamanager/blob/50a9711a175d8312be915a801bb0834964af90ce/src/Mail.php#L179

**Comment by lucasalva87** [comment]
Facendo un test come da te suggerito mi sono accordo che "host" non veniva mai valorizzato perchè la variabile era stata chiamata "server".
Fix del bug 5357976
