### ISSUE TITLE
Stampa Riepilogo Interventi

### ISSUE THREAD

**Issue by lexen77** [devcode-it/openstamanager#165]
Salve,
non c'è modo di stampare un pdf che elenca l'insieme di Attività ?

**Comment by Dasc3er** [comment]
Ciao @lexen77,
in fondo alla schermata principale del modulo **Attività** dovresti trovare un widget "Stampa riepilogo" che permette proprio di stampare l'elenco di tutti gli interventi.
Era questo che stavi cercando?

Inoltre, vorremmo mantenere una distinzione tra gli argomenti trattati nel forum e su GitHub: potresti continuare ad utilizzare il forum per fare domande sul gestionale e sul suo funzionamento, mentre GitHub per segnalare bug o proporre modifiche?

**Comment by lexen77** [comment]
ok Grazie
