### ISSUE TITLE
Miglioramento interventi da pianificare

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#166]
Sarebbe da migliorare il riquadro a destra degli interventi da pianificare, con queste caratteristiche:

- filtrarli per mese (ad esempio con un menu a tendina)
- mostrare quelli scaduti con un colore diverso, ad esempio rosso
- mostrare informazioni essenziali nel riquadro azzurro, come ad esempio il nome del cliente

**Comment by fgambarelli** [comment]
Purtroppo in una gestione ancora molto cartacea, occorre la possibilità di stamparli (sia in modo riepilogativo per mese, che in dettaglio per intervento in modo da poter dare al tecnico le informazioni dell'impianto e della locazione). Per avere questa possibilità li trasformiamo in interventi.

**Comment by loviuz** [comment]
I promemoria sono promemoria da pianificare a calendario, quindi secondo me andrebbero prima pianificati a calendario e poi stampati. Per stamparli, c'è la "Stampa riepilogo interventi"...
