### ISSUE TITLE
Opensta 2.3.1 anagrafica ordinamento colonne ERROR

### ISSUE THREAD

**Issue by cicalo** [devcode-it/openstamanager#167]
salve.
in anagrafica è possibile ordinare le colonne, solo che cliccando su "ragione sociale" e su "Rel." appare:
DataTables warning: table id=main_35 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

provato anche su vs. vversione on-line.

a presto

**Comment by cicalo** [comment]
ATTENZIONE: ho provato anceh su demo on line: l'errore si presente su tutte le viste dove vi è la colonna "reagione sociale" quiandi anche in FAtture, attività etc. etc.

**Comment by Dasc3er** [comment]
@cicalo Grazie per la segnalazione!
L'errore è causato da un problema con gli apici nella colonna query ORDER BY ed è presente nella versione 2.3.1...

@loviuz Nella 2.4 era già stato risolto in modo indiretto, comunque basterebbe aggiungere gli apici nel metodo *getQuery* di **Plugins** e **Modules** per i dati *order_by*.

**Comment by Dasc3er** [comment]
Ecco la linea di codice corretta nella branch 2.4:
https://github.com/devcode-it/openstamanager/blob/97bc1239973658045382fb97c78bf657d414bcc2/src/App.php#L241

**Comment by lucasalva87** [comment]
Grazie cicalo per la segnalazione, infatti la query prevista dovrebbe essere: 

SELECT an_anagrafiche.idanagrafica AS 'id', ragione_sociale AS 'Ragione sociale', GROUP_CONCAT(an_tipianagrafiche.descrizione SEPARATOR ', ') AS 'Tipologia', citta AS 'Città', telefono AS 'Telefono', an_relazioni.colore AS 'color_Rel.', an_relazioni.descrizione AS 'color_title_Rel.' FROM `an_anagrafiche` LEFT JOIN `an_relazioni` ON `an_anagrafiche`.`idrelazione` = `an_relazioni`.`id` LEFT JOIN `an_tipianagrafiche_anagrafiche` ON `an_tipianagrafiche_anagrafiche`.`idanagrafica`=`an_anagrafiche`.`idanagrafica` LEFT JOIN `an_tipianagrafiche` ON `an_tipianagrafiche`.`idtipoanagrafica`=`an_tipianagrafiche_anagrafiche`.`idtipoanagrafica` WHERE 1=1 AND `deleted` = 0 GROUP BY `an_anagrafiche`.`idanagrafica` HAVING 2=2 ORDER BY TRIM(`ragione_sociale`) 

invece è:

SELECT an_anagrafiche.idanagrafica AS 'id', ragione_sociale AS 'Ragione sociale', GROUP_CONCAT(an_tipianagrafiche.descrizione SEPARATOR ', ') AS 'Tipologia', citta AS 'Città', telefono AS 'Telefono', an_relazioni.colore AS 'color_Rel.', an_relazioni.descrizione AS 'color_title_Rel.' FROM `an_anagrafiche` LEFT JOIN `an_relazioni` ON `an_anagrafiche`.`idrelazione` = `an_relazioni`.`id` LEFT JOIN `an_tipianagrafiche_anagrafiche` ON `an_tipianagrafiche_anagrafiche`.`idanagrafica`=`an_anagrafiche`.`idanagrafica` LEFT JOIN `an_tipianagrafiche` ON `an_tipianagrafiche`.`idtipoanagrafica`=`an_tipianagrafiche_anagrafiche`.`idtipoanagrafica` WHERE 1=1 AND `deleted` = 0 GROUP BY `an_anagrafiche`.`idanagrafica` HAVING 2=2  **ORDER BY Ragione sociale** desc

**Comment by lucasalva87** [comment]
Se invece ti interessa per la 2.3.1.
Va sostuita la riga 229 di src/Modules.php con questo:

$order_by[] = !empty($data['order_by']) ? $data['order_by'] : '`'.$data['name'].'`';

**Comment by cicalo** [comment]
Grazie Luca, 

ho corretto prendendo quanto mi avete detto. Ora funziona.

Ho aggiunto altro apice a quanto mi hai comunicato, 

'`'.$data['name'].'`';

 

Perfetto. Risolto.

Grazie

 

 

Da: Luca [mailto:notifications@github.com] 
Inviato: venerdì 2 marzo 2018 16.18
A: devcode-it/openstamanager <openstamanager@noreply.github.com>
Cc: cicalo <cicalo@imtsol.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [devcode-it/openstamanager] Opensta 2.3.1 anagrafica ordinamento colonne ERROR (#167)

 

Se invece ti interessa per la 2.3.1.
Va sostuita la riga 229 di src/Modules.php con questo:

$order_by[] = !empty($data['order_by']) ? $data['order_by'] : ''.$data['name'].'';

**Comment by cicalo** [comment]
Grazie, Thomas,

ho apportato la modifica sulla 2.3.1. Tutto OK.

 

Ottimo Sw. Bravissimi. Non so programmare in php, ma sono un vecchio programmatore e le mani riesco ancora a mettercele.

 

Ma la 2.4 non è ancora rilasciata, giusto?

 

Moduli aggiuntivi, quali piccolo crm, per non perdermi i leads e casomai trasformarli in clienti ci state pensando?

Altra domanda, avendo al necessità di sapere su quel cliente cosa ho installato e quando, come posso fare? Ho provato con myimpianti ma è privo di informazioni utili.

Tipo: impianto XXX del cliente xx

Lista di prodotti forniti, data di quando sono stati forniti, eventuali interventi ed un riferimento ad un doc (fattura/ordine/intervento)

 

Chi siamo:www.imtsol.com

Ciao et grazie nuovamente.

 

Da: Thomas Zilio [mailto:notifications@github.com] 
Inviato: venerdì 2 marzo 2018 16.12
A: devcode-it/openstamanager <openstamanager@noreply.github.com>
Cc: cicalo <cicalo@imtsol.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [devcode-it/openstamanager] Opensta 2.3.1 anagrafica ordinamento colonne ERROR (#167)

 

Ecco la linea di codice corretta nella branch 2.4:
https://github.com/devcode-it/openstamanager/blob/97bc1239973658045382fb97c78bf657d414bcc2/src/App.php#L241

**Comment by loviuz** [comment]
Ciao @cicalo 

>  Ma la 2.4 non è ancora rilasciata, giusto?

Esatto. La rilasceremo in queste prime settimane di marzo.

> Moduli aggiuntivi, quali piccolo crm, per non perdermi i leads e casomai trasformarli in clienti ci state pensando?

Ci sono tante richieste e pian piano ci arriviamo, altrimenti sviluppiamo personalizzazioni su richiesta.

>  Altra domanda, avendo al necessità di sapere su quel cliente cosa ho installato e quando, come posso fare? Ho provato con myimpianti ma è privo di informazioni utili.

Quando associ un impianto ad un cliente, dalla scheda cliente puoi vedere tutti i suoi impianti. Oppure, dalla vista impianti, puoi filtrarli per cliente, se è questo che chiedevi...
