### ISSUE TITLE
Stampa riepilogo interventi

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#168]
Andrebbe tolto dalle stampe dell'intervento singolo, perché va stampato fuori dalla scheda intervento in quanto è una stampa riepilogativa di più interventi. Va stampata solo dal widget, però se tolgo la stampa da zz_prints non funziona. Ho provato a impostare NULL come id_module ma non è permesso.
@Dasc3er, lasciamo che si possa mettere NULL come id_module su zz_prints, così possiamo generare stampe che non siano collegate a moduli?

**Comment by Dasc3er** [comment]
@loviuz Questa situazione è presente solo per gli Interventi al momento, oppure ci sono altre stampe che non dovrebbero comparire?
Perché in alternativa potremmo prevedere un flag che specifica la natura relativa al record o all'intero modulo...

**Comment by loviuz** [comment]
Per ora non ci sono altre stampe slegate da un id_record, però potrebbero essercene altre in futuro, per cui andrei ad inserire questa possibilità

**Comment by Dasc3er** [comment]
Procedo dunque con l'aggiunta del flag *is_record* in **zz_prints**?
In questo modo le stampe rimarrebbero legate ad un modulo, ma si potrebbe specificare la relazione o meno con il record effettivo.
