### ISSUE TITLE
MIGLIORIA - Riferimenti configurabili

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#169]
In molti punti di richiamo/collegamento di oggetti sarebbe opportuno configurare la riga che riprende i riferimenti come paramento nelle impostazioni.
In fattura quando di aggiunge un intervento:
INTERVENTO --> FATTURA                 Intervento numero 1000 del 02/03/2018 -- Rapportino intervento n. 156/B del 02/03/2018 (dove il numero citato non è l'id)
CONTRATTO --> FATTURA                 Contratto numero 0172-05 - MANUTENZIONE --Es. Contratto n.0172-05 MANUTENZIONE valido dal 01/01/2018 al 31/12/2018
PREVENTIVO --> FATTURA               
Ecc..

**Comment by Dasc3er** [comment]
Al momento la gestione dei riferimenti è stata generalizzata attraverso la funzione **doc_references()** in **modules/fatture/modutil.php**.

**Comment by Dasc3er** [comment]
Correzione a seguito del raggruppamento delle movimentazioni: per i Documenti è disponibile una nuova interfaccia ReferenceInterface che permette di gestire i riferimenti tramite le nuove classi.
Per il momento il nome del documento deriva dal tipo selezionato, dove presente, oppure è definito staticamente. Eventualmente è possibile procedere a una personalizzazione tramite le funzioni di traduzione, ma il quesito è da approfondire.
