### ISSUE TITLE
Bug eliminazione fatture

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#17]
Cancello fattura numero 4, cancella anche le righe in fattura numero 5 (fatture di vendita) e anche fatture precedenti, 1 e 3. E anche da alcune fatture di acquisto.
In pratica se creo una fattura con delle righe di articoli o senza, poi ne creo una seconda sempre con alcune righe ed articoli e poi con il pulsante Elimina cancello la seconda, vengono cancellate anche le righe della prima o di alcune altre fatture, indipendentemente se sono di vendita o acquisto.

**Comment by fpsoftware** [comment]
Ciao @ldanese83 stò facendo alcunti test, ma non riesco a replicare il bug, anche il codice mi sembra corretto...

**Comment by ldanese83** [comment]
Per esempio sono ora entrato nella demo online a cui si accede dal sito di openstamanager.com. Ho fatto la fattura di acquisto numero 6, come conto ho messo il conto cancelleria in testata. Poi ho aggiunto 2 righe con lo stesso articolo: Penna a sfera, una da 1 pezzo e l'altra da 10 come quantità. Ho messo stato emessa ed ho salvato. Crea la scadenza, tutto ok. Poi inserisco fattura numero 7 sempre di acquisto. Metto stesso conto cancelleria e stesso metodo di pagamento Assegno. Inserisco 2 righe: la prima con Penna a sfera 1 pezzo, la seconda riga libera con dicitura test. Metto emessa e salvo. Crea la scadenza e tutto ok. Poi vado in fondo e metto elimina. Mi chiede se sono sicuro, si e la cancello. Poi torno in fattura 6 e mi trovo che la fattura ha una riga solo invece di 2, ha cancellato una delle due. Infatti se la controlli trovi che la scadenza è da 6,71 mentre il totale fattura è 0,61, proprio perchè mi ha cancellato una riga..

**Comment by ldanese83** [comment]
Guardando il codice, probabilmente è questa riga qua:
// Elimino la riga dal documento
    $dbo->query('DELETE FROM `co_righe_documenti` WHERE idgruppo='.prepare($idgruppo));
su modutil.php del modulo fatture. 
Non so cosa sia l'id gruppo, ma se è comune a più righe va a cancellare righe che non dovrebbe

**Comment by Dasc3er** [comment]
Il bug è risolvibile modificando il codice nel seguente modo:
```
$dbo->query('DELETE FROM `co_righe_documenti` WHERE idgruppo='.prepare($idgruppo).' AND iddocumento='.prepare($iddocumento));
```

Similmente, il problem è presente nella funzione _rimuovi_articolo_daddt_.

**Comment by loviuz** [comment]
@ldanese83, solo per completezza: idgruppo serve per raggruppare più righe in una fattura. se ad esempio c'è un articolo con quantità 10, e ho per ogni riga un codice seriale, in stampa si possono raggruppare quei 10 seriali in una sola riga, ad esempio così:

**Articolo X**
_Serial: 001, 002, 003, 004, ecc..._

**Comment by loviuz** [comment]
@Dasc3er posso chiudere la segnalazione? Ho visto il commit, dovrebbe essere corretto così, eventualmente riapriamo la segnalazione
