### ISSUE TITLE
INTERVENTI - Stato precedente

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#170]
Quando un intervento viene fatturato passa allo stato fatturato, ma se viene tolto nelle righe della fattura e rimesso diventa sempre "completato" .
Sarebbe opportuno distinguere lo stato relativo alla fatturazione rispetto agli stati puri dell'intervento (Eseguito/Completato/In programmazione, ecc) in modo che le gestioni della fattura non facciamo e modifichino questi stadi.
Vedrei una gestione degli stati con l'aggiunta di un campo fatturabile, dove identifica se quello stato rende l'intervento fatturabile.
Poi nelle righe degli interventi aggiungerei un campo, fatturato e non modificherei lo stato dell'intervento.

**Comment by fgambarelli** [comment]
Questa osservazione vale per tutti gli altri oggetti come i CONTRATTI , i PREVENTIVI, i DDT

**Comment by lucasalva87** [comment]
Mi sembra una buona osservazione. Il campo “completato” della tabella “in_statiintervento” forse avrebbe più senso chiamarlo “fatturabile”...
Poi dalla schermata degli stati intervento adiamo a definire quelli che vogliamo considerare come stati “fatturabili”. Ad esempio lo stato “Completato”.

Lo stato “Fatturato” invece sarebbe da togliere (se non ci sono obbiezioni) e considerare un intervento fatturato solo se effettivamente è stato aggiunto in una fattura di vendita.

**Comment by Dasc3er** [comment]
@fgambarelli Proponeva in pratica di introdurre una separazione tra gli stati contabili dei documenti (identificabili in generale in Bozza, Emesso, Evaso) con quelli di utilizzo del documento, variabili sulla base dello stesso. Per esempio, gli Interventi hanno Completato, In lavorazione, ... 

Recentemente sono stati introdotti dei flag relativi agli stati che ne indicano le proprietà, però la modifica potrebbe avere ancora senso.
@lucasalva87 @loviuz Che ne pensate?

**Comment by Pek5892** [comment]
Risolto con l'introduzione del campo is_fatturabile nelle tabelle relative agli stati.
