### ISSUE TITLE
Il widget contratti in scadenza non filtra per stato

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#171]
Il widget dei contratti in scadenza, nella dashboard, è filtrato per diversi fattori, tranne che per stato. Andrebbe, secondo me, inserito un flag "completato" negli stati contratti (come per gli stati attività), così da poterli cambiare per varie esigenze e filtrare anche queste scadenze escludendo appunto quelli completati.

**Comment by Dasc3er** [comment]
A partire dalla versione 2.4.11 è presente un controllo sul flag **is_fatturabile**.
