### ISSUE TITLE
Miglioria - Pulsanti

### ISSUE THREAD

**Issue by lexen77** [devcode-it/openstamanager#173]
Salve,
non sarebbe il caso di  evitare di ripetere piu' volte il pulsante "salva modifiche" nelle pagine di inserimento dati?
Magari posizionare il pulsante "salva modifiche" una sola volta in alto a destra insieme al pulsante elimina.
La ripetizione dei pulsanti fa sembrare quasi che la pagina è divisa in piu bloccchi indipendenti. Con ogni blocco con il suo pulsante di salva modifiche,
Inoltre si potrebbe aggiungere anche un pulsante "modifica e chiudi" utile per ritornare in automatico all'elenco dopo il salvataggio.

**Comment by lucasalva87** [comment]
Salve lexen77, nella nuova release 2.4 abbiamo già previsto queste logiche. Grazie comunque per la segnalazione.

**Comment by Dasc3er** [comment]
@lexen77 Per la precisione, prova a controllare la issue #22, dove questa implementazione è stata discussa e introdotta.
