### ISSUE TITLE
Email senza allegato

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#175]
Nella versione 2.4, invia tranquillamente l'email ma non arriva allegato (provato da più moduli sia fatture vendita che interventi)

**Comment by Andi-bz** [comment]
Ho riscontrato il stesso problema

**Comment by Dasc3er** [comment]
@fgambarelli @Andi-bz Il commit 9c6968a dovrebbe aver risolto correttamente il problema...
@devcode-it/openstamanager Inoltre ho cambiato la cartella di salvataggio temporaneo degli allegati durante la generazione (ora **files/attachments** e non basata sul modulo corrente).

**Comment by lepool** [comment]
@Dasc3er : L'allegato di stampa ora è presente. Se allego ulteriori file legati all'intervento, questi non sono presenti come allegato nella email.

**Comment by Dasc3er** [comment]
@lepool Potresti provare l'ultimo commit e8dba97c02bf3c0e8f3f454e8a0fcf72f2f85ed9?

**Comment by lepool** [comment]
@Dasc3er :  Funziona solo se ho aggiunto 1 ulteriore allegato. Con 2 mi allega solo l'allegato di stampa .

**Comment by lepool** [comment]
Il problema sono gli implode : 

per avere le query corrette , sarebbe da applicare una modifica in implode( "," ,$....)
Un altro problema poi è che se allego 2 stampe , la seconda stampa della lista ha i campi vuoti. Vedi i pdf allegati. Gli altri allegati modificando gli implode vengono allegati correttamente. 
Sembra che il problema sia nella parte Prints::render . Purtroppo mi manca un po di manualità per trovare l'errore :-/  Dovrebbero essere gli include_once in Prints::loader che chiaramente non vengono inclusi più volte. 

[Intervento - 1.pdf](https://github.com/devcode-it/openstamanager/files/1866646/Intervento.-.1.pdf)
[Intervento (senza costi) - 1.pdf](https://github.com/devcode-it/openstamanager/files/1866647/Intervento.senza.costi.-.1.pdf)

**Comment by Dasc3er** [comment]
@lepool Grazie mille per la contribuzione!
Con il commit 194b7677a1e2732043b02ac34618cf11a0f9aec6 la Pull Request è stata accettata, ed effettivamente dovrebbe risolvere entrambi gli ultimi problemi segnalati....
