### ISSUE TITLE
DDT di vendita non funziona la select destinazione merce

### ISSUE THREAD

**Issue by xxfuma85xx** [devcode-it/openstamanager#176]
Nel file modules/ddt/edit.php riga 72 c'è un errore nella query di ricerca delle sedi per la destinazione merce del ddt.
Manca il ? nell'apertura del tag php. Però anche aggiungendolo non risolve la variabile.
Sostituendo:
'<?php echo $idanagrafica; ?>'
con:
$idanagrafica$
funziona.
Ho controllato e anche nel file della versione 2.4 c'è lo stesso errore.

**Comment by Dasc3er** [comment]
Ciao @xxfuma85xx,
grazie mille per la segnalazione!

Puoi confermare che il bug è stato risolto con il commit 0bcde94f2dacf5bcca5130bbb497c0b0618a45bd?

**Comment by xxfuma85xx** [comment]
Confermo che il bug è risolto.

Grazie!

**Comment by Dasc3er** [comment]
Grazie a te!
Sentiti libero di contribuire anche attraverso modifiche effettive al codice, grazie alle Pull Request di GitHub 😄
