### ISSUE TITLE
ANAGRAFICA - Dal plugin Statistiche - Fatture 

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#177]
![image](https://user-images.githubusercontent.com/34273200/37366633-47192130-2701-11e8-91f6-b67d7f61af36.png)
Premendo sul link visualizza non filtra le fatture del Cliente di partenza.

**Comment by Dasc3er** [comment]
@fgambarelli Sei sicuro del problema in questione?
Testando nella versione 2.4 il tutto funziona correttamente....

**Comment by lepool** [comment]
Confermo che anche a me funziona il filtro clickando su visualizza. V2.4

**Comment by fgambarelli** [comment]
Purtroppo da me ne non funziona, non filtra, in entrambe le due versioni.

**Comment by lepool** [comment]
Potrebbe essere un problema di codifica database?

**Comment by Dasc3er** [comment]
Sarebbe piuttosto strano in questo caso, perché la gestione dei campi di ricerca da URL viene fatta tramite PHP e non riguarda il database...
O meglio, è possibile che l'interpretazione PHP invii correttamente i dati al codice JavaScript che gestisce la funzione, che però per qualche motivo non aggiorna la tabella DataTables.

**Comment by lepool** [comment]
Perche avevo il problema in passato aggiornano da una versione ad un altra quando sono state introdotte le codifice utf8mb4 delle tabelle mysql.

**Comment by fgambarelli** [comment]
Scusate ho trovato il problema... a causa dell'errore #167 per fare in modo che non fosse bloccante, avevo sostituito la colonna Ragione Sociale con Ragione_Sociale nel modulo delle Anagrafiche.
