### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#178]
Buongiorno a tutti... vorrei precisare che non sono un'esperto di programmazione ma sono in fase di studio. Non riesco a trovare il file .php dove poter modificare le voci del menu lato sinistro della videata. Ho trovato un riferimento del menu interessato nella cartella:
/include/top.php
echo Modules::getMainMenu();
infatti non riesco a trovare in nessuna cartella il file MainMenu da poter modificare eventuali voci di descrizione oppure per poter inserire nuovi pulsanti e altro ancora.
Gentilmente vi chiedo come poter affrontare questo problema grazie anticipatamente.

**Comment by Dasc3er** [comment]
Ciao @mdbrasco,
Come puoi osservare dalla sintassi PHP, per generare il menù viene utilizzato il metodo *getMainMenu* della **classe Modules*, chd puoi trovare nella cartella **src/**.

Scrivi pure se riscontri altri problemi nell'interpretazione del codice :smile:

**Comment by mdbrasco** [comment]
Ottimo... mi hai fatto capire che ho ancora... tanto ma tanto... da studiare :-) 
Non riesco a capire come siete riusciti a creare una tabella in Mysql per creare un menu (faccio riferimento alla tabella zz_modules) non vi sto chiedendo spiegazioni ma è la prima volta che mi capita di vedere una struttura di menu in questo modo, solitamente sono creati tramite file .php
Comunque vi faccio i complimenti per l'ottimo lavoro che avete svolto, lo trovo completo in tutti i suoi punti di vista ovviamente è specifico per piccole e medie imprese. Grazie mille...

**Comment by Dasc3er** [comment]
In pratica, la tabella **zz_modules** viene utilizzata per avere il controllo sui moduli installati nel gestionale e gestire i permessi...
Per la generazione del menu, semplicemente in base all'utente e ai permessi garantiti al suo gruppo, individuiamo i moduli a livelli gerarchici: quelli principali, quelli secondari, e così via, attraverso il campo *parent*. In base alla struttura che otteniamo creiamo quindi il menu fino ad un certo livello.

Sappiamo che per il momento la documentazione non è molto ampia e dettagliata soprattutto riguardo al database, se hai suggerimenti su come migliorare queste sezioni sei il benvenuto.

**Comment by mdbrasco** [comment]
La logica ci sta tutta ovviamente la pratica mi viene a mancare... ho ben notato i permessi di accesso avete pensato a tutto ribadisco della vostra bravura ed esperienza. Se volete vi posso fare dei video tutorial cosi ché gli utenti alle prime armi possono avere dei riferimenti. Prometto che vi preparo una demo del video tutorial per sostenervi in questo magnifico progetto e lascio a voi decidere se continuare o meno.

**Comment by fpsoftware** [comment]
Ciao @mdbrasco qualche video tutorial ci servirebbe proprio! Se riesci lo vediamo molto volentieri
