### ISSUE TITLE
Tabelle di riepilogo

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#179]
Buonasera a tutti, mi trovo nuovamente in difficoltà questa volta non riesco a trovare il file .php o da quello che sto imparare forse dovrei intervenire nuovamente in Mysql per riuscire a gestire le tabelle di riepilogo.
Faccio un esempio per capirci meglio:
- mi trovo nel menu del magazzino nella sezione articoli
- le voci della tabella di riepilogo sono Descrizione - Codice - Categoria - Sottocategoria - Q.tà
Bene vorrei aggiungere qualche voce e toglierne altre, gentilmente mi potete indicare quale file è da modificare? grazie mille...

**Comment by Dasc3er** [comment]
Solitamente definiamo le tabelle di riepilogo che intendi come la sezione generale del modulo...
A partire dalla versione 2.3 è disponibile il modulo **Viste**, disabilitato di default e attivabile dal modulo **Aggiornamenti**.

Una volta abilitato questo modulo puoi modificare in modo dinamico la sezione generale degli altri moduli, ma devi prestare particolare attenzione alle modifiche che fai, poiché puoi cambiare in modo drastico la navigazione nel gestionale.

**Comment by mdbrasco** [comment]
Bene... a quanto pare è stato più facile a fare che a dirsi ovviamente grazie al vostro Cpanel che siete riusciti a semplificare notevolmente il lavoro. E' da dire che un pò di linguaggio di programmazione è sempre da usare ma... ragazzi non finirò mai di farvi i complimenti per la riuscita di questo gestionale. Per risolvere il mio problema ho dovuto solamente crearmi una Query personalizzata e tutto magicamente si è risolto. Ciao a tutti presto....
