### ISSUE TITLE
Problemi su fatture

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#18]
Avrei rilevato anche i seguenti problemi sulle fatture:
- Fatto ordine fornitore, poi fatta fattura da ordine, mi ha cambiato il numero di pezzi della prima riga da 2 a 1 sulla fattura (anche se mantiene il totale corretto.
- Creata fattura di vendita con sconto 5% sul totale fattura, metodo di pagamento con 2 scadenze. Crea le 2 scadenze senza tener conto dello sconto. Il totale fattura è 3801, le scadenze sono da 2000.
- Nella riga di sconto creata come sconto totale sulla fattura vi è la dicitura dell'IVA ma manca a database il campo id_iva nella tabella delle righe dei documenti co_righe_documenti mi pare, se c'è descrizione credo sarebbe corretto inserire anche l'id di collegamento alla tabella dell'IVA.

**Comment by fpsoftware** [comment]
per queste segnalazioni ho riscontrato anch'io questi problemi

**Comment by Dasc3er** [comment]
Riguardo al terzo punto, il campo che identifica l'IVA nella tabella **co_righe_documenti** si chiama _idiva_.

**Comment by Dasc3er** [comment]
Riguardo al primo punto, ancora non sono riuscito a replicare il malfunzionamento...

@ldanese83 Potresti essere più dettagliato su come hai individuato il problema (numero di righe nell'ordine e tipologia - generiche, articoli)?

**Comment by ldanese83** [comment]
Ho ricreato lo stesso ordine e riprovato a creare la fattura da ordine come avevo fatto la prima volta, ma non mi si ripresenta più l'errore. Purtroppo non mi ricordo se avessi fatto qualcosa in particolare la prima volta perchè si verificasse l'errore, tra l'altro cancellando una fattura in seguito mi si sono cancellate anche le righe che presentavano l'errore quindi non riesco più a vederle per capire se avevano qualcosa di diverso da quello che ho poi replicato, anche se mi pare di no. Probabilmente è un problema che mi si è verificato per qualche particolare circostanza e che non si presenta facilmente o che non è dovuto a errori in OpenSTA (potrebbe anche essere un errore sul POST), non saprei.
