### ISSUE TITLE
Calcolo numerazione ddt errata

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#180]
Impostando come maschera 18-####, non calcola correttamente i numeri in progressione (riportato anche nel forum):
https://www.openstamanager.com/forum/viewtopic.php?f=4&t=90075&p=96154&hilit=ddt#p96154

**Comment by lucasalva87** [comment]
https://www.openstamanager.com/forum/viewtopic.php?f=4&t=90075&p=96154&hilit=ddt#p96154

**Comment by Dasc3er** [comment]
@loviuz Potresti controllare il codice inserito con il commit 038c9e767bcdc0bdcdcb7dac29d2995d0b4ec802?
Ho aggiunto una classe dedicata alla generazione di stringhe del genere (**Util\Generator**), sulla cui base funziona anche la classe **Backup**, che in pratica è un refactoring della vecchia funzione _get_next_code_ con alcuni miglioramenti nella comprensibilità e nel funzionamento 😄 .

Per fare alcuni test sulla generazione dei codici:
```php
// Creazione di un nuovo codice basato sul pattern previsto
Util\Generator::generate($pattern);

// Creazione di un nuovo codice basato sul pattern previsto e sui valori del precedente
Util\Generator::generate($pattern, $ultimo_codice_generato);
```

**Comment by mdbrasco** [comment]
Ciao a tutti pure io ho questo problema di dover impostare la numerazione sia delle fatture che DDT in questo modo esp. (2018-20). Ho cercato nella cartella src/util/Generator ma non trovo il file che Dasc3er dice di modificare, vedo solo il file Ini.php e Singleton.php
 
Ho risolto in modo drastico aggiungendo nel file header.php nella cartella templates/ddt la seguente stringa alla riga 19:
<p>$numero_doc$</p>
cambiandola in:
<p>2018-$numero_doc$</p>
Questa modifica l'ho apportata anche per le fatture nella cartella templates/fatture.

Ovviamente è una modifica manuale e quindi questo lo dovrò ripetere per ogni anno a seguire, vorrei precisare che non è una soluzione da programmatori ma la posso reputare  come soluzione alternativa affinché i programmatori possano trovare un modo più agevole. Aspetto quindi la prossima release grazie anticipatamente...

**Comment by Dasc3er** [comment]
@mdbrasco La modifica da me indicata è relativa alla versione 2.4 in sviluppo, e la puoi trovare nella branch 2.4.
In patricolare, dovrebbe permettere di migliorare la gestione dei codici da parte del gestionale, ma si tratta di una feature ancora in sviluppo e quindi non completamente testata e affidabile.

**Comment by mdbrasco** [comment]
@Dasc3er ho migliorato un pò la funzione per gestire il numero di fatturazione e DDT intervenendo semplicemente in questi due file: templates/fatture/init.php e leader.php

Nel primo file ho aggiunto la seguente stringa alla riga 57 e 58
$anno = date("y"),
'anno_doc' => $anno,
la lettera "y" in minuscolo mi farà comparire solamente le ultime due cifre dell'anno ossia "18" mentre se volessi avere l'intero anno esp. "2018" sostituisco semplicemente la "y" minuscola con quella maiuscola "Y".

Mentre nel secondo file "leader.php" ho modificato la riga 19 in questo modo
<p>$anno_doc$$numero_doc$</p>

**Conclusione:**
![schermata 2018-03-21 alle 14 23 24](https://user-images.githubusercontent.com/37365078/37712216-7c4fcf80-2d13-11e8-8309-8e687d45b306.png)

Non voglio insinuare che è il metodo più corretto ma attualmente sono costretto a trovare questa strategia per risolvere il problema e confido in voi programmatori a risolvere questo piccolo disagio. Non mi rimane altro di aspettare la versione 2.4 per vedere il problema risolto.

**Comment by mdbrasco** [comment]
Per concludere questo capitolo aggiungerei come si può generare il numero della fattura dal nostro gestionale uguale al numero fattura dell'ipotetico cliente.

Per pareggiare il numero attuale dovremmo gestire una Query andando direttamente in MySql e lanciare questa semplice stringa:
ALTER TABLE co_documenti AUTO_INCREMENT = 80;

"ALTER TABLE chiamerà la tabella delle fatture
AUTO_INCREMENT indicherò con che numero far partire la fatturazione, esempio nr. 80" 

Spostandoci sempre nella tabella co_documenti dovremmo modificare manualmente per la prima volta i numeri nelle seguenti colonne "NUMERO" "NUMERO_ESTERNO" esempio:
"NUMERO" inserire 80
"NUMERO_ESTERNO" inserire 080 (vi ricordo che per generare un numero a tre cifre sono andato a modificare nel gestionale sotto le impostazioni di fatturazione il seguente campo "**Formato numero secondario fattura**", mettendo semplicemente tre cancellati ### questo valore lo potremmo aumentare anche a quattro cancellati e questo significa che l'ipotetico cliente avrà la possibilità di fatturare ben si 9999 documenti. Nel mio caso mi sono fermato a 999 che è un bel po di fatture.

A questo punto quando andremo a generare una nuova fattura direttamente dal gestionale i campi a noi interessati aumenteranno di 1 e quindi correttamente potranno generare il numero di fatturazione esempio 18081.

**Comment by mdbrasco** [comment]
La legge prevede che:
Struttura del numero di fattura

Ci sono diverse disposizioni che indicano quale sia la numerazione obbligatoria per le fatture, rispettando quanto previsto dalla **legge n. 228 del 24 dicembre 2012, che stabilisce al comma 325 dell’art. 1 come a partire dal 1 gennaio 2013 ogni fattura debba contenere “un numero progressivo che la identifichi in modo univoco**”.

Questo ci fa capire che se ho una fattura nel 2018 che mi indica il numero progressivo uguale a  01 oppure 001 oppure 0001 e lo stesso numero verrà replicato nel 2019 vado incontro alla legge soprattutto all'articolo sopra indicato.

**Numeri di fattura: esempi di assegnazione**

Per poter ordinare le fatture ai corrispettivi periodi di fatturazione ricorrendo ai numeri di fattura, si consiglia di inserire la data di emissione secondo lo schema di assegnazione scelto. Sono ad esempio possibili i numeri di fattura con indicazione iniziale dell’anno. Nel seguente esempio i numeri di fattura vengono presentati separatamente in sequenze di numeri progressivi. 

**2018:**

2018-001

2018-002

2018-003

**2019:**

2019-001

2019-002

2019-003

Bene per evitare di incorrere in sanzioni a livello legislativo consiglio a tutti di apportare le seguenti modifiche sopra citate.

**Comment by Dasc3er** [comment]
@mdbrasco Il sistema di generazione dei codici presente al momento nella release 2.3.x è personalizzabile con successo con un buon numero di formati predefiniti e generalmente utilizzati...
La issue in questione è stata creata per discutere a livello di codice il miglioramento di questo sistema integrato, e non per indicare nello specifico come modificare manualmente il gestionale per adeguarlo in caso di necessità.

In particolare, se vuoi descrivere in modo più completo e dettagliato ciò che hai scritto sopra, saresti pregato di utilizzare il forum ufficiale (sezione Tutorial) così da rendere queste procedure più visibili e consigliare meglio gli utilizzatori finali del software.

Per questa issue vorremmo dedicarci a discutere e segnalare gli eventuali formati aggiuntivi da supportare (come quelli indicati nel primo post) in modo chiaro e espandibile in futuro :smile:.

**Comment by mdbrasco** [comment]
Chiedo scusa anche fpsoftware mi aveva già ripreso dicendomi di andare nella sezione forum... ora ho capito definitivamente. Bene provvederò a cancellare i commenti in questa sezione.

**Comment by Dasc3er** [comment]
@mdbrasco In ogni caso se hai proposte per migliorare il codice oppure trovi bug come quello in questione sei il benvenuto!
Cerchiamo solamente di usare GitHub per la gestione del codice e il forum per le questioni più varie :+1:

**Comment by lucasalva87** [comment]
Fix 2.4 con commit 74a659f

**Comment by Dasc3er** [comment]
@lucasalva87 Per distribuire la funzionalità potremmo semplicemente sovrascrivere la funzione *get_next_code* con la nuova classe...

**Comment by lucasalva87** [comment]
Mi sembra funzioni correttamente, per il  momento si ottengono gli stessi risultati di get_next_code ma magari con utilizzo più intenso la classe si prospetterà la soluzione migliore.

**Comment by Dasc3er** [comment]
@lucasalva87 Quello che intendevo era di modificare la funzione nel seguente modo:
```php
function get_next_code($str, $qty = 1, $mask = '')
{
return Util\Generator::generate($mask, $str, $qty);
}
```

**Comment by loviuz** [comment]
A questo punto la sostituirei dove è presente...

**Comment by Dasc3er** [comment]
Completato con il commit 3db010e53fee67e705697b0d294689705d3da6a7.
La funzione _get_next_code_ è ora tra le deprecate del progetto.
