### ISSUE TITLE
calcolo data fattura fine mese

### ISSUE THREAD

**Issue by cicalo** [devcode-it/openstamanager#182]
in impostazioni pagamenti ho impostato:
pagamento 100%
scadenza: come indicato " data fatturazione fine mese"
giorni 0

Opensta 2.3.1

imposto fattura con pagamento fine mese, ma invece mi calcola come data scadenza sempre il giorno della emissione.

Necessaria per chi, come me, fa interventi, invia fattura immediata al cliente , ma con scadenza fine mese.

Gracias.

**Comment by fpsoftware** [comment]
ciao @cicalo 
un'informazione al volo, dal modulo "Contabilità - Scadenzario" è possibile modificare manualmente la data della scadenza, intanto puoi sistemare manualmente la fattura in questione.

Per noi invece è un'altra funzione interessante da aggiungere!

**Comment by cicalo** [comment]
Ho lavorato sulla tabella  pagamenti  poichè anche sulla  stampa fattura  le date non corrispondevano!!. Grazie.

 

Per vostra info: oggi ho dovuto fare fattura con pagamento 30/60/90/120 a partire dal 31 marzo.

Inizialmente sul modulo pagamenti avevo impostato:

primo blocco: 25%, data fattura fine mese , giorni 0 ( pensavo prendesse il fine mese come default)

secondo : 25% data fattura fine mese, giorni 60

terzo:25% data fattura fine mese , giorni 90

quarto: 25% data fattura fine mese, giorni 120.

Non calcolava… ed ho fatto manualmente, mettendo il primo blocco con scadenza fissata al 31 marzo, il secondo con fine mese, ma giorni 30 e così via,sino a giorni 90…

 

Sicuramente da migliorare ragazzi. 

Eccezionali, Grazie sempre per le celeri risposte.

 

IAcopo

 

Da: fpsoftware <notifications@github.com> 
Inviato: lunedì 19 marzo 2018 17.29
A: devcode-it/openstamanager <openstamanager@noreply.github.com>
Cc: cicalo <cicalo@imtsol.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [devcode-it/openstamanager] calcolo data fattura fine mese (#182)

 

ciao @cicalo <https://github.com/cicalo> 
un'informazione al volo, dal modulo "Contabilità - Scadenzario" è possibile modificare manualmente la data della scadenza, intanto puoi sistemare manualmente la fattura in questione.

Per noi invece è un'altra funzione interessante da aggiungere!
