### ISSUE TITLE
Fatture di acquisto

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#183]
## Comportamento richiesto
aggiungere un'opzione per le fatture di acquisto: "Formato numero fattura di acquisto" 
il campo "Numero" può essere utilizzato come numero di protocollo per l'archiviazione delle fatture cartacee, e quindi può tornare comodo modificare la numerazione (es. 2018-001 etc.)

## Comportamento attuale
il campo "Numero" è un semplice progressivo, inoltre è di "sola lettura" e quindi non è nemmeno possibile modificarlo manualmente

**Comment by lucasalva87** [comment]
Introdotto nella 2.4 con commit 926b5c8
