### ISSUE TITLE
Cassa fiscale

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#184]
Buongiorno a tutti ma soprattutto ai sviluppatori poiché oggi vi provoco un pochettino....

Ho notato che per scaricare un prodotto a magazzino lo si può fare in molteplici modi esempio gestire la fatturazione - DDT oppure gestendo le attività e fino a qui tutto chiaro è semplice.

**Avete mai pensato di gestire lo scarico a magazzino gestendo anche la cassa giornaliera?** infatti se emano uno scontrino fiscale dovrei gestire lo scarico a magazzino del ipotetico prodotto manualmente.

Da esperienze di altri gestionali ho notato che c'è la possibilità che il gestionale stesso può erogare uno scontrino fiscale, tutto questo avviene unicamente se la cassa fiscale è programmabile e quindi abbia i collegamenti usb oppure la porta COM e altre funzioni. 

Ovviamente questa richiesta la si può applicare solamente quando il cliente richiede questo intervento e mi pare logico che non sarà un'opzione di default ma a pagamento poiché ogni cassa avrà un suo linguaggio di programmazione per interfacciare essa con il gestionale in questione.
Al massimo per invogliare sempre di più i nuovi utenti a utilizzare il gestionale potrete creare una maschera di esempio standard per far capire la potenzialità del gestionale ovvero riuscire a gestire anche i scontrini fiscali. 

Abbiate pazienza ma mi state coinvolgendo sempre di più in questo progetto....

**Comment by fpsoftware** [comment]
ciao @mdbrasco 
abbiamo già sviluppato un modulo "Vendita al banco" che contiene praticamente tutte le funzioni che hai descritto, se ti interessa è in vendita, scrivici via email a info [AT] openstamanager [DOT] com per maggiori informazioni.

Riguardo le casse fiscali ci siamo interfacciati alle casse di ultima generazione che ricevono input via rete lan, sempre via email possiamo dirti marca e modello. 

Per questo genere di domande/provocazioni/informazioni ti chiederei gentilmente di utilizzare il nostro forum https://www.openstamanager.com/forum/  in quanto stiamo cercando di dividere le richieste più tecniche da queste più generiche. 
Grazie.

**Comment by mdbrasco** [comment]
Non so più cosa dirvi avete pensato già a tutto... ottima come notizia quindi non mi resta che all'occorrenza di utilizzare il modulo da te indicato "Vendita al banco". Non mi resta altro che rinnovare i complimenti e cercherò di seguire le tue indicazioni riguardante il Forum.
