### ISSUE TITLE
STAMPE - Preventivi

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#185]
![image](https://user-images.githubusercontent.com/34273200/37699725-0c659cc4-2ce9-11e8-9bfb-e42f2665cf71.png)
Purtroppo viene ripetuto sotto lo spazio della firma anche nella prima pagina e non viene gestito la corretta impaginazione del titolo delle CONDIZIONI DELLA FORNITURA, quando è fra 2 pagine come da immagine.

**Comment by Bacca1997** [comment]
Nell'ultima versione il problema non si presenta...

**Comment by Dasc3er** [comment]
Confermo il corretto funzionamento nella versione 2.4 in sviluppo...
@fgambarelli In quale versione hai riscontrato il problema?
