### ISSUE TITLE
Utilizzo di keywords riservate in MySQL

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#187]
In alcune tabelle sono stati utilizzati nomi per le colonne che sono delle parole chiave riservate in MySQL.
Ad esempio nella tabella:  `zz_views`

> The column name 'order' is a MySQL reserved keyword.
> The column name 'slow' is a MySQL reserved keyword.
> The column name 'default' is a MySQL reserved keyword.
> 

Qui è possibile trovare una lista di tutte le parole chiave riservate che sarebbe meglio non utilizzare come nomi delle colonne: https://guide.dev2web.org/parole-chiave-riservate-in-mysql/

**Comment by Dasc3er** [comment]
Il problema è risolvibile utilizzando gli apici in modo corretto nelle query relative, come implementato nelle nuove classi...
Se vogliamo normalizzare i nomi dei campi, sarebbe corretto usare anche gli apici di conseguenza nelle nuove query.
