### ISSUE TITLE
Stampa schermata illeggibile

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#188]
Rivedere css per la stampa delle schermate, le stampe (soprattutto in controller) non risultano formattate in maniera leggibile.

![anagrafiche openstamanager 20](https://user-images.githubusercontent.com/30728163/37764361-cbcb13f4-2dc1-11e8-98a2-72922a7119ca.png) 

Per la corretta formattazione delle videate in fase di stampa vedere OSM 2.2

**Comment by Dasc3er** [comment]
@lucasalva87 Il commit relativo dc238faf57df2950a8fadb539808298e0a60475c risolve completamente il problema?

**Comment by lucasalva87** [comment]
@Dasc3er sì, ma da testare/migliorare.
