### ISSUE TITLE
Tecnici: anagrafica creata non accessibile

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#190]
Quando un tecnico aggiunge un’anagrafica (es. Cliente) poi non la visualizza nella lista delle `Anagrafiche `ne può accedere alla sua scheda. Appena creata infatti viene restituito il messaggio “Record non trovato”

![anagrafiche openstamanager 22](https://user-images.githubusercontent.com/30728163/37769471-65fa1fb0-2dd1-11e8-8acc-11d23f2af0a0.png)

**Comment by lucasalva87** [comment]
@Dasc3er sì esatto, era quello che si pensava anche con @loviuz . Se non ci sono altre idee...

**Comment by lepool** [comment]
Oppure se non vi sono presenti interventi con quel cliente, potrebbero vederlo tutti. Ma per motivi di privacy o provigioni potrebbero esserci problemi :-)

**Comment by loviuz** [comment]
Il filtro attuale, mostra ai tecnici solo i propri. Si potrebbe inserire di default che il tecnico veda gli interventi suoi (come ora) e quelli senza nessun tecnico, ed aggiungere un secondo filtro (disabilitato di default) per vedere solo i propri. In questo modo, si può scegliere che filtro usare.

**Comment by loviuz** [comment]
non mi sono venute altre per ora...
