### ISSUE TITLE
Permessi di stampa in ddt e fatture errati

### ISSUE THREAD

**Issue by xxfuma85xx** [devcode-it/openstamanager#191]
Ho notato un problema nella stampa dei ddt e delle fatture di vendita quando non è un amministratore ad effettuarle.
Ho creato un gruppo di utenti nuovo e dati i permessi in lettura e scrittura sia sul modulo fatture di vendita che sul modulo ddt di vendita, i moduli sono accessibili tramite menu e correttamente editabili (creo, disfo tranquillamente) però quando stampo mi dice che non ho i permessi.

Nei files templates/ddt/init.php (riga 61), templates/fatture/init.php (riga 65) e templates/fatture_accompagnatorie/pdfgen.fatture_accompagnatorie.php (riga 30) la condizione della if è sbagliata.

Quella corretta è questa: 

`( (!empty(Auth::user()['idanagrafica']) && $id_cliente != Auth::user()['idanagrafica'] && !Auth::admin()) && Modules::getPermission($module_name)=='-')`

Sarebbe utile inserirlo anche negli altri templates.
Lo farei volentieri io ma non ho ancora dimestichezza con le pull request di github.

**Comment by Dasc3er** [comment]
In effetti la questione potrebbe essere un po' più complessa da gestire, perché nella versione in sviluppo (2.4) l'accesso alle stampe viene gestito in base ai permessi di accesso ai moduli.
In pratica, per aprire una qualsiasi stampa un utente deve avere accesso al modulo, quindi il controllo in questione non è più utilizzato al momento.

@devcode-it/openstamanager L'obiettivo originale era quello di permettere al cliente in questione di visualizzare la stampa anche senza avere il permesso di vedere il modulo?
Se sì, la possibile soluzione al problema sarebbe utilizzare il seguente codice::
```php
if ($user['gruppo'] == 'Cliente' && $id_cliente != $user['idanagrafica']) {
```

In alternativa, potremmo considerare la possibilità di aggiungere permessi specifici per l'accesso alle stampe.

**Comment by xxfuma85xx** [comment]
No, l'obiettivo originale era far stampare i documenti da un utente appartenente ad un gruppo creato adhoc per un reparto particolare che deve accedere solo a determinati moduli.
Se l'utente fa parte del nuovo gruppo e al gruppo vengono dati i permessi di lettura e scrittura sul modulo fatture di vendita, l'utente vede tutte le fatture e le può modificare ma cliccando su "Stampa Fattura" riceve il messaggio "Non hai i permessi per effettuare questa stampa".

**Comment by Dasc3er** [comment]
Per il momento, il controllo sui permessi di accesso alle stampe viene effettuato in modo separato rispetto agli eventuali controlli che vengono aggiunti nei file **init.php**.

Per esempio, supponiamo di avere il gruppo Cliente:

- Se ha accesso al modulo relativo alla stampa, allora può vederla e i controlli aggiuntivi sul file **init.php** vengono effettuati.
- Se non ha accesso al modulo relativo alla stampa, non può vedere la stampa

@devcode-it/openstamanager Era questo il problema che intendevo sottolineare, e il commit 85fe2e5 non permette di aggirare questo comportamento...

**Comment by lucasalva87** [comment]
Perché un utente di un dato gruppo dovrebbe poter visualizzare la stampa relativa al modulo per il quale  il suo gruppo non ha permessi di accesso?

**Comment by Dasc3er** [comment]
E allora si pone il problema su controllo aggiuntivo sui Clienti su Fatture e DDT...

**Comment by loviuz** [comment]
Con l'ultimo commit sulle stampe di fatture e ddt, ho fatto in modo che le stampe di questi documenti avvengano in queste condizioni:
- l'utente è admin
- se l'utente è del gruppo "Clienti" e il ddt o fattura sono intestati a lui
- se l'utente non è del gruppo "Clienti" e ha i permessi in lettura sul modulo

**Comment by loviuz** [comment]
Più avanti si gestiranno i permessi sulle stampe in modo diversi, con il rapporto gruppo-stampe, ma per ora mi limiterei a farle uscire in base ai permessi del modulo
