### ISSUE TITLE
DDT - Destinazione Merce non legge le sedi

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#192]
In Anagrafica inserito le diverse sedi per spedizione, ma nel momento della compilazione del DDT in Destinazione Merci non compare la lista delle sedi presenti in anagrafica del cliente

**Comment by lucasalva87** [comment]
Con la versione 2.4 il problema descritto sembra non verificarsi. Qualcun'altro mi conferma?
