### ISSUE TITLE
REGISTRO IVA VENDITE

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#194]
La stampa del registro non è in ordine di n. documento/Data
![image](https://user-images.githubusercontent.com/34273200/37843812-4669f6a2-2ec6-11e8-8f79-5f73f3aba44f.png)
Contiene onoltre delle righe vuote a 0, credo siano le righe generate da fatture che hanno righe di tipo descrizione.
![image](https://user-images.githubusercontent.com/34273200/37843932-94d36864-2ec6-11e8-98e4-b2d93fa0dc25.png)

**Comment by Dasc3er** [comment]
@lepool Puoi confermare se il commit c8c9cdbeeca0b1d7715f21d41e0823b0694a8a3e corregge l'ordinamento per data?

**Comment by lepool** [comment]
Confermo, con il mio test le stampe sono ordinate sia per numero documento che per data. Se magari qualcun'altro può confermare dato che io al momento ho poche posizioni.

**Comment by Dasc3er** [comment]
@lepool Errore mio, ho citato la persona sbagliata 😄 
@fgambarelli

**Comment by lepool** [comment]
No problem. :-D Il problema citato da @fgambarelli  delle righe vuote (descrizioni) è comunque ancora presente .

**Comment by Dasc3er** [comment]
@fgambarelli In riferimento alle righe vuote, bisogna controllare la tipologia di IVA applicata sulle diverse componenti della fattura. In pratica, se il campo _data_ e _numero documento_ sono vuoti, la riga indica un dato dell'ultima fattura indicata.

In ogni caso ora le righe di tipo descrizione non vengono considerate.
