### ISSUE TITLE
CONTRATTI IN SCADENZA 

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#195]
![image](https://user-images.githubusercontent.com/34273200/37844538-6d2ef90c-2ec8-11e8-910b-fa9b8f5e77a9.png)
Il widgets dei contratti in scadenza mostra un numero (47) ma quando si apre (mettendoci tantissimo) ne mostra solo uno!
![image](https://user-images.githubusercontent.com/34273200/37844654-c5df5ed4-2ec8-11e8-8730-a1cb864d2f5b.png)

**Comment by lucasalva87** [comment]
Effettivamente il widget non elenca i contratti nello stato "Completato" che invece vengono riportati nell’elenco riepilogativo della pop-up.

![contratti openstamanager 4](https://user-images.githubusercontent.com/30728163/38134090-f230c0f6-3411-11e8-8255-b08e01a22e1b.png)
