### ISSUE TITLE
Fattura accompagnatoria di vendita

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#196]
Problemi in stampa poiché non ci sono i collegamenti nel file pdfgen.fatture_accompagnatorie.php nella cartella templates/fattua_accompagnatorie. Riferimento alle seguenti voci:
Aspetto beni, Causale trasporto, Porto ecc...

Un'altro problema consiste che non gestisce la Destinazione, se un cliente in anagrafica clienti ha l'indirizzo di fatturazione diverso all'indirizzo di consegna merce, in stampa compaiono nella sezione Destinazione entrambi gli indirizzi.
![stampa](https://user-images.githubusercontent.com/37365078/37862861-5d3b3ab0-2f54-11e8-9824-e13add5219a9.jpg)

Un ultimo miglioramento sarebbe se il riepilogo del Subtot.  Iva e Totale documento fosse come nella stampa della fattura immediata di vendita ossia in questo modo
![schermata 2018-03-24 alle 11 05 29](https://user-images.githubusercontent.com/37365078/37862800-6070950a-2f53-11e8-8a21-236deb654fa7.png)
 
Ovviamente a seguire dovrebbero comparire gli altri dati del documento.

**Comment by Dasc3er** [comment]
@mdbrasco Nella branch 2.4 la stampa delle fatture accompagnatorie è già stata uniformata con quella delle fatture normali, e potenzialmente potrebbero essere stati risolti i problemi indicati inizialmente.
Potresti provare a dare un'occhiata alla stampa aggiornata?

**Comment by mdbrasco** [comment]
Gentilmente mi spieghi dove posso scaricare la versione 2.4 ? ho già cercato ma non trovo riferimenti... grazie.

**Comment by mdbrasco** [comment]
Ottimo direi... soprattuto il fatto che avete integrante nel mysql la tabella zz_prints ottima per gestire come nel mio caso le stampe multilingua.

**Comment by mdbrasco** [comment]
Non si riesce a impostare quante righe di prodotti devono comparire in una pagina.
Ho inserito un totale di 22 righe prodotti di cui 21 righe sono nella prima pagina mentre nella seconda pagina compare l'ultima riga. Il problema estetico della stampa sta che se ho inserito più aliquote IVA esempio al 4% - 10% e al 22% la stampa si comporta in questo modo:
![schermata 2018-03-25 alle 13 03 11](https://user-images.githubusercontent.com/37365078/37874297-1064860e-302d-11e8-9c0a-311e1a515a8f.png)

Allora ho pensato di intervenire nel file body.php intervenendo in questa porzione di codice
$autofill = [
    'count' => 0, // Conteggio delle righe
    'words' => 70, // Numero di parolo dopo cui contare una riga nuova
    'rows' => $fattura_accompagnatoria ? 15 : 20, // Numero di righe massimo presente nella pagina
    'additional' => $fattura_accompagnatoria ? 10 : 15, // Numero di righe massimo da aggiungere
    'columns' => 5, // Numero di colonne della tabella
];
ma cambiando i valori aumentandoli o diminuendoli non si ottiene nessuna variazione in fase di stampa.
La mia idea era di diminuire le righe per pagina passando da 21 a 15, cosi che ogni 15 righe prodotti si crea una nuova pagina, questo forse permette di avere un layout di stampa molto più gradevole e si risolve il problema sopra citato.

**Comment by Dasc3er** [comment]
@mdbrasco Il problema in questione non è causato dall'autofill ma dall'altezza del footer.
Semplicemente, prova ad aumentare il valore in questo modo alla fine del file **init.php**:
```php
if($fattura_accompagnatoria) {
    $settings['footer-height'] += 40;
}
```

**Comment by mdbrasco** [comment]
Ottimo grazie ora il Layout è perfetto. La stringa da modificare sempre in riferimento alla versione 2.4 la trovate in Settings.php

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager Nel caso la stampa riguardi una fattura accompagnatoria, ho aggiunto l'aumento automatico dell'altezza del footer di 40 unità.
