### ISSUE TITLE
Anagrafiche

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#198]
Da quando ho aggiornato la versione 2.3.1 a 2.4 l'anagrafiche non funzionano più. Posso modificare i clienti già inseriti ma non ne posso più crearne di nuovi. Quando finisco di inserire i primi due campi ossia Ragione sociale* e Tipo di anagrafica* viene schermata bianca. Torno indietro per verificare se è avvenuto l'inserimento ma niente nuovo inserimento.

Mi rendo conto che non è una versione ufficiale ma forse sbaglio io a usare la versione 2.4 ditemi voi... ho copiato tutti i file della versione 2.4 e sovrascritte la cartella del gestionale V. 2.3.1, automaticamente il gestionale mi ha chiesto di aggiornare il database e cosi ho fatto. Al momento noto che non posso inserire nuovi clienti in Anagrafiche.

**Comment by mdbrasco** [comment]
Ho letto il seguente articolo su come aggiornare una versione con un'altra:
https://devcode-it.github.io/openstamanager/aggiornamento.html
Non cambia nulla, non posso inserire nuovi clienti.

**Comment by Dasc3er** [comment]
Potresti controllare i contenuti della cartella **logs/**?
Potrebbe infatti trattarsi di un errore particolare...

**Comment by mdbrasco** [comment]
Noto che neppure le Attività posso inserire... questo è l'errore che mi continua a dare nel file error.log

[2018-03-25 18:06:37] Logs.ERROR: Uncaught Exception Error: "Call to undefined function Util\Generator()" at /Applications/MAMP/htdocs/Felix/modules/interventi/add.php line 95
{"url":"/Felix/add.php?id_module=3","ip":"::1","http_method":"GET","server":"localhost","referrer":"http://localhost:8888/Felix/controller.php?id_module=3","uid":"a43f0d1"} 

non ho idea di cosa fare... domanda quando è prevista una beta della V. 2.4 ? cosi per evitare questi problemi.

**Comment by mdbrasco** [comment]
Risolto ma non so se è un errore di programmazione o solo nel mio caso si comporta in questo modo "spero ovviamente che non sia questa ultima ipostesi".
Il problema sta nella stringa modules/interventi/add.php line 95 questo vale sia per inserire nuovi Attività che Anagrafiche.
stringa attuale versione 2.4
**$codice = Util\Generator(get_var('Formato codice anagrafica'), $rs[0]['codice']);**
cambiandola con quella della versione 2.3.1 tutto funziona correttamente.
**$codice = get_next_code($rs[0]['codice'], 1, get_var('Formato codice anagrafica'));**

Domanda questo problema si verifica anche ad altri utenti?

**Comment by Dasc3er** [comment]
@mdbrasco Grazie mille per il log!
Il commit 3d77d5a45a6ddfa75ba32cb2df1c989f17d18a20 dovrebbe aver risolto il problema; in pratica, con la sostituzione della funzione _get_next_code_ era stata richiamata la classe corretta ma non la relativa funzione.

**Comment by mdbrasco** [comment]
scusami mi hai messo in panico hahahah cosa posso fare per correggere l'errore? mantenere l'attuale stringa **$codice = get_next_code($rs[0]['codice'], 1, get_var('Formato codice anagrafica'));** 
oppure se volessi riutilizzare **$codice = Util\Generator(get_var('Formato codice anagrafica'), $rs[0]['codice']);** dove scarico i file aggiornati?

**Comment by Dasc3er** [comment]
La soluzione da te implementa è corretta, ma dovresti fare la modifica in tutti i file dove si presenta l'errore...

In alternativa prova ad aggiornare i file modificati nel commit presente sopra.

**Comment by mdbrasco** [comment]
Preferisco fare come indichi nel commit quindi modifico i file sopra elencati. Grazie
