### ISSUE TITLE
Nella dashboard  indicazione scadenze di interventi anche se sono stati pianificati?

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#199]
## Comportamento richiesto

La scadenza di un intervento dovrebbe essere indicato dopo la scadenza e se non pianificato. 

## Comportamento attuale

La scadenza viene indicato anche se ho intervento pianificato. 

## Passi per riprodurre il comportamento

Creare un promeoria per un contratto con scadenza per i giorni succcessivi

* Modulo: Dashboard
* Versione del progetto: 2.4
* Versione PHP: 5.6.33
* Tipo di server: apache 2.4.10

**Comment by lepool** [comment]
Allego grafica

![grafik](https://user-images.githubusercontent.com/32035706/37875922-e4ba1d70-3045-11e8-97c0-ca9929f8dbd7.png)

**Comment by loviuz** [comment]
Non ho ben capito... intendi che, se c'è un promemoria di attività da pianificare che è scaduto, si dovrebbe vedere diversamente? Negli ultimi commit, sulla destra del calendario, si possono visualizzare i promemoria delle attività da programmare raggruppati per mese, con una notifica se ci sono attività scadute.

**Comment by lepool** [comment]
Guarda lo sfondo dell'immagine. Li vedi interventi da pianificare scaduti. Ma aprendo le scadenze non ci sono interventi da pianificare scaduti. infatti sono tutti nel futuro. 
Non so se mi sono spiegato. Altrimenti provo ad inviarti altre immagini.

**Comment by lepool** [comment]
La cosa strana è che ora non mi indica piu un intervento da pianificare scaduto. Forse il problema è stato risolto con un altro commit? Faccio delle prove e in caso chiudo l'issue.

**Comment by loviuz** [comment]
Si, non riesco a riprodurlo... se con gli ultimi commit non riscontri problemi, può essere che sia stato già risolto, magari involontariamente! :-D

**Comment by lepool** [comment]
Al momento mi è ricomparso, ma il database contiene dati sensibili. Riprovo a installare una versione pulita. Effettuo altre prove e vi invio l'eventuale Database di Backup. :+1:

**Comment by loviuz** [comment]
Hai novità?

**Comment by Dasc3er** [comment]
@lepool Ci sono novità sulla questione?

**Comment by lepool** [comment]
Sto facendo delle prove . Per ora non me lo indica. Ma come l'ultima volta dopo un giorno me lo indicava nuovamente come nelle immagini. Domani dovrei riuscire a darvi risposta. In caso di errore vi invio tutto il backup da poter effettuare eventuali controlli.

**Comment by lepool** [comment]
@Dasc3er , oggi ho fatto altre prove ed il problema non mi si presenta più . Ho cancellato e riprogrammato piu volte un intervento collegato ad un promemoria di un contratto. Direi che per me si puo chiudere.
