### ISSUE TITLE
Problema visualizzazione prima nota

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#20]
Non so se avete già risolto, comunque segnalo questo piccolo problema di visualizzazione: se vado ad inserire un nuovo movimento in prima nota e il movimento supera i 1000 euro, sul totale a fondo pagina mi compare 1 euro, in pratica il totale vede il punto di separazione delle migliaia come una virgola. E' solo un problema di visualizzazione, poi salva i dati correttamente.

**Comment by Dasc3er** [comment]
Grazie ancora per la segnalazione!

Questo problema è presente in fondo alla pagina della singola Prima Nota?
In questo caso, è già stato risolto...

**Comment by ldanese83** [comment]
Si' è quello. Allora avete già risolto.
