### ISSUE TITLE
FATTURE calcolo iva in presenza di sconto globale 

### ISSUE THREAD

**Issue by cicalo** [devcode-it/openstamanager#200]
OPENSTAMAN 2.3.1 modulo fatture

Fattura immediata: inserito sconto globale in EURO (no percentuale)
Inserito righe generiche nel dettaglio. 
Sconto globale OK con importo ed iva a zero.

PROBLEMA:
Il calcolo dell'va sulle righe è calcolato facendo una somma degli importi dell'iva di ogni singola riga, ovviamente nellosconto globale iva è zero, quindi nel totale iva esce importo di tutta iva e non tiene conto che bisognerebbe togliere importo iva dello sconto.

Vi allego estratto di dettaglio per meglio comprendere.
Sbaglio qualche cosa io, oppure avete già una patch per risolvere? dovrei fatturare entro fine mese.
grazie
![fattura con sconto globale non calcola iva correttamente](https://user-images.githubusercontent.com/24680908/37965848-ce0649dc-31c6-11e8-9ed4-f7955f2d9632.JPG)

**Comment by cicalo** [comment]
precisazione: ho messo importo fisso in euro. Con la percentuale funziona.

**Comment by lucasalva87** [comment]
Ciao @cicalo grazie per la segnalazione. Ho verificato, effettivamente abbiamo lo stesso problema nella 2.4. Il problema si presenta solo con lo sconto unitario, mentre lo imposti in % dovrebbe funzionare correttamente.

**Comment by lucasalva87** [comment]
In 

> modules/fatture/modutil.php

 alla riga 810 aggiungere:

```
$rs = $dbo->fetchArray('SELECT SUM(subtotale - sconto) AS imponibile, SUM(iva) AS iva FROM (SELECT '.$tables['row'].'.subtotale, '.$tables['row'].'.sconto, '.$tables['row'].'.iva FROM '.$tables['row'].' WHERE '.$fields['row'].'='.prepare($id_record).') AS t');
$subtotale = $rs[0]['imponibile'];
$iva += $sconto[0]['sconto_globale'] * $rs[0]['iva'] / $subtotale;
```

**Comment by lucasalva87** [comment]
Commit #27ddf42 dovrebbe risolvere la problematica.

**Comment by cicalo** [comment]
Ok,grazie, sembra funzionare. 
A presto.
