### ISSUE TITLE
Anagrafica cliente Bug

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#201]
Versione 2.4:
Ho notato che i caratteri inseriti sia nel campo P.IVA che nel CODICE FISCALE non corrispondono ossia nel Mysql avete impostato nel campo piva "varchar(15)" e nel codice_fiscale "varchar(16)".
Quindi se vado nel gestionale in anagrafica e inserisco nei campi sopra citati i loro valori, l'inserimento si ferma a 11 caratteri o numeri in entrambi i campi. 

**Soluzione spartana** sono andato nella cartella modules/anagrafiche/edit.php
ho cambiato le stringhe nelle righe 50 e 54 da:
"text-center alphanumeric-mask",
in
"text-center alphanumeric", 
togliendo "mask" riesco a inserire i campi impostati dal file edit.php ossia per la P.IVA 13 caratteri e per il CODICE FISCALE 16 caratteri alfanumerici.
Non so a cosa fa riferimento il comando -mask ma togliendolo l'inserimento della P.IVA e del CODICE FISCALE funziona.

**Comment by lucasalva87** [comment]
![anagrafiche openstamanager 23](https://user-images.githubusercontent.com/30728163/37970768-92bce01c-31d4-11e8-8882-54af2baf4249.png)

**Comment by mdbrasco** [comment]
Ho inserito nuovamente nella cartella modules/anagrafiche/edit.php nella riga 50 e 54
"class": "text-center alphanumeric-mask",
e non mi fa inserire i caratteri. 
Forse devo vedere se nel file CSS? 
Vorrei una conferma da tre per aggiornare la versione 2.3 nella 2.4 semplicemente ho preso i file della versione 2.4 e soprascritta quella della versione 2.3 mi ha aggiornato il database e sembra che tutto funziona. Domanda è la procedura corretta per testare la versione 2.4?

**Comment by lucasalva87** [comment]
Come già segnalato da @antonioscarpino dopo aver sovrascritto i file in questo modo bisogna fare un "yarn run develop-OSM" in modo tale che vengano aggiornate anche le dipendenze.

**Comment by mdbrasco** [comment]
Grazie mille ho risolto il problema del CODICE FISCALE e P.IVA istallando in modo corretto la versione 2.4 ovviamente aggiornando le dipendenze php.
