### ISSUE TITLE
problema con installazione ver. 2.4 da zero

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#203]
Versione del gestionale ultimo commit.

Procedendo all'installazione del gestionale da 0 e dopo aver inserito tutti i dati per la connessione al database, viene riportato un errore di non avvenuta connessione al database anche se tutti i dati inseriti nella form sono corretti.
Ho provato la procedura sia su server locale che su hosting remoto con lo stesso risultato.
allego file di log dell'errore

* Versione del progetto: 2.4
* Versione PHP: 7.1.12

[error.log](https://github.com/devcode-it/openstamanager/files/1852753/error.log)

**Comment by mdbrasco** [comment]
Dovresti seguire questa semplice guida per installare la versione 2.4 ovviamente non è una versione ufficiale. https://devcode-it.github.io/openstamanager/aggiornamento.html

In pratica dovrai installare prima di tutto la versione 2.3 con relativo database e poi copiare le cartelle/file che le trovi qui in githug e incollarle nella cartella principale della versione 2.3. Quando ti chiede  di sovrascrivere le cartelle e i relativi file fallo pure e quando andrai ad avviare per la prima volta il gestionale con la versione 2.4 ti chiederà di aggiornare il database, anche in questo caso conferma. Magicamente  a fine installazione avrai la versione 2.4.

Comunque chiedo pure io conferme dai programmatori di quanto ho scritto poiché noto alcuni problemi esempio in Anagrafiche quando voglio inserire il codice fiscale o la P.IVA mi blocca l'inserimento a 11 caratteri. Ho già sollecitato questo problema e mi hanno risposto che loro non riscontrano il seguente problema.

**Comment by antonioscarpino** [comment]
Ciao @mdbrasco quello che hai indicato tu è uno dei metodi per aggiornare il gestionale però diciamo che non è il migliore.
Infatti dovresti fare un "git pull" del master è poi eseguire il comando "yarn run develop-OSM" in modo tale che vengano aggiornate anche le dipendenze (sopratutto dal passaggio tra una versione e l'altra).
Infatti lo zip che scarichi da git non ha al suo interno la cartella verdor dove sono presenti tutte le dipendenze e quindi questo potrebbe causare degli errori.
Comunque detto questo se io non avessi la versione 2.3.1 e volessi installare in questo momento il gestionale all'ultimo commit non lo potrei fare a causa di questo problema.

**Comment by mdbrasco** [comment]
Ciao @antonioscarpino gentilmente mi indicheresti un tutorial o una guida su come gestire il git pull ma soprattutto come si esegue il comando "yarn run develop-OSM" ? Grazie...

**Comment by antonioscarpino** [comment]
La guida che hai lincato va bene trovi altre indicazioni utili nel file readme del gestionale

**Comment by mdbrasco** [comment]
scusamei @antonioscarpino ma seguendo quella procedura tu hai il problema della cartella Vendor? quindi non serve che faccio tutta quella procedura per installare la versione 2.4? Oppure sto capendo tutt'altra cosa? grazie....

**Comment by antonioscarpino** [comment]
@mdbrasco no io non ho problemi con la cartella verdor. In quella cartella vengono scaricate e compilate tutte le dipendenze della versione corrente del gestionale. Per esempio se tu fai un pull del master tramite git scarichi tutti i file aggiornati all'ultimo commit disponibile. Questa operazione (quindi "git pull") è la stessa cosa di scaricare lo zip tramite la home di github. Il problema nasce dal fatto che quando fai un git pull o scarichi lo zip da github la cartella verdor non è compresa perchè tutte le dipendenze vanno aggiornate tramite yarn. Se tu non aggiorni queste dipendenze potrebbe capitare che una funzione inserita nel gestionale non funzioni o dia errore. Il problema che ho indicato io non è dovuto all'aggiornamento delle dipendenze ma probabilmente a qualche errore che è stato introdotto quando è stato fatto il merge tra la versione 2.3.1 e la versione 2.4. Spero di essere stato chiaro.

**Comment by mdbrasco** [comment]
Ottimo ora ho capito... pure se sto incontrando difficoltà a installare yarn e compose ma provvederò a risolvere. Ultima domanda yarn la devo installare nella cartella del gestionale? oppure è uguale dove la installo?

**Comment by Dasc3er** [comment]
@antonioscarpino Tornando alla segnalazione iniziale, l'errore riscontrato è il seguente:
```
php_network_getaddresses: getaddrinfo failed: Host sconosciuto
```

Il problema si verifica anche creando manualmente il file **config.inc.php** configurato come per la versione 2.3?

**Comment by antonioscarpino** [comment]
verifico e riferisco

**Comment by antonioscarpino** [comment]
creando manualmente il file config.inc.php ho questa schermata
![errore](https://user-images.githubusercontent.com/34765237/38145911-e6737cb0-344b-11e8-8b20-c0ceb01f7dda.png)
cliccando su installa per creare il database non succede nulla.
Inoltre nella cartella logs non viene creato alcun log di errore

**Comment by loviuz** [comment]
@Dasc3er ho riscontrato anch'io questo problema stasera provando ad installare l'ultima versione da zero, stavamo rilasciando OSM 2.4... :-D

**Comment by antonioscarpino** [comment]
@Dasc3er se ho interpretato bene la tua richiesta pare che le variabili globali di base siano corrette ad eccezione della variabile ROOTDIR che non è valorizzata

![errore](https://user-images.githubusercontent.com/34765237/38148469-f7171f4e-3456-11e8-8b94-7f157384956c.png)

**Comment by Dasc3er** [comment]
@antonioscarpino Il commit 30024fd3537de51d520d2be66c79f0df330ee6ed dovrebbe aver risolto i problemi nella fase di test del database e connessione iniziale...

Riguardo al problema successivo, sembra invece che gli assets non vengano caricati correttamente.
Il percorso _ROOTDIR_ dovrebbe essere corretto, poiché il gestionale è nella root del server, ma apparentemente gli assets non vengono individuati: potresti vedere che errore segnala la console del browser?

**Comment by antonioscarpino** [comment]
@Dasc3er ti confermo che l'ultimo commit risolve il problema della connessione al db.
Per quanto riguarda gli assets nella console del browser non vedo nessun errore.
