### ISSUE TITLE
Periodi temporali per campo “Validità”

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#205]
Per il modulo "Contratti" modificare campo “Validità” e "Preavviso per rinnovo" con possibilità di scegliere la tipologia del valore digitato, come succede già per i campi sconto.

Le possibili scelte saranno:
- Giorni
- Mesi
- Anni

![fatture di vendita openstamanager 10](https://user-images.githubusercontent.com/30728163/38133570-1132429c-3410-11e8-996f-ebb43f57074e.png)

**Comment by fpsoftware** [comment]
Attenzione che il campo "Preavviso per rinnovo" è usato sul widget "Contratti in scadenza" che quindi deve essere aggiornato di conseguenza

**Comment by maicol07** [comment]
Ciao! Novità su questa funzionalità?
C'è un problema: mettendo una validità di 4 anni, quindi pari a 1460 giorni viene automaticamente inserito 999 giorni invece che 1460

**Comment by Dasc3er** [comment]
Ciao @maicol07, per il momento non ci sono novità.
Se necessiti e desideri sviluppare personalmente la correzione siamo più che disponibili a metterla in release :D.

**Comment by maicol07** [comment]
Dove vengono effettuati i calcoli per la data di conclusione? Ho cercato ma non c'è nessun riferimento al campo validità nei calcoli...

**Comment by Dasc3er** [comment]
Infatti, data conclusione e accettazione non dipendono in alcun modo da validità.

**Comment by Dasc3er** [comment]
Grazie a @maicol07 , la funzionalità è stata completata e inclusa nella versione 2.4.16.
