### ISSUE TITLE
Errore nella generazione della query al db per l'inserimento di una fattura di vendita nella prima nota

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#207]
![errore](https://user-images.githubusercontent.com/34765237/38153564-b6c2b022-346d-11e8-834b-8e09d0e23498.png)

dallo screen si nota un errore di sintassi (manca una parentesi tonda) nella generazione della query di inserimento dei dati nel db.

**Comment by Dasc3er** [comment]
@antonioscarpino Il commit 34a33ae dovrebbe risolvere il problema...

In pratica, nel completamento della query non era stato aggiunto il metodo _prepare_ per salvare correttamente i valori nel database.

**Comment by antonioscarpino** [comment]
Sembra che l'ultimo commit abbia risolto la generazione della query però adesso è presente un nuovo errore
![immagine](https://user-images.githubusercontent.com/34765237/38166336-9cf90280-3522-11e8-9459-ade8b69a9584.png)
dove viene detto che idsede non può avere valore null.
Se idsede si riferisce alla sede di fatturazione del cliente essa è settata di default come "sede legale".

**Comment by lepool** [comment]
Il problema sembra essere nella nuova struttura del gestionale. Quando vengono inserite prime note alcune variabili come $idanagrafica non vengono trasmesse durante il submit. queste però sono neccessarie.

**Comment by antonioscarpino** [comment]
@lepool infatti se vedi la query che si genera l'unica variabile valorizzata è quella relativa al numero di fattura, le altre sono tutte null. Non vorrei spararla grossa ma forse il problema è dovuto come @Dasc3er aveva già detto al non corretto caricamento degli assets in questa nuova versione del gestionale.

**Comment by Dasc3er** [comment]
@antonioscarpino DI certo gli assets non sono relativi al problema in questione.
Sembra che siano stati inseriti alcuni nuovi campi a database che, come ha indicato @lepool, portano ad alcuni errori in alcune sezioni...

**Comment by antonioscarpino** [comment]
Ok ho avanzato un'ipotesi errata. L'importante e che abbiate individuato il problema in modo da poterlo risolvere.

**Comment by lepool** [comment]
@Dasc3er : Una mia curiosità, come funzionano i segmenti? Se magari riesci a spiegarmi brevemente la loro operatività senza che spulcio il codice come un poraccio :-) Grazie.

**Comment by lucasalva87** [comment]
@lepool i “segmenti”, inizialmente denominati “sezionali”, servivano per poter separare il calcolo della numerazione delle fatture che potevano quindi seguire n. “filoni” diversi. Da li poi abbiamo sviluppato e rivisto la struttura per permettere, in maniera più generica, la creazione di “segmenti” per qualunque modulo si voglia. Altro non sono delle clausole che verranno accodate alla query del modulo creando di fatto delle sotto-viste selezionabili da un menù a tendina in alto a destra del controller.
Esempio pratico: Si possono creare per il modulo “Attività” due segmenti, uno che seleziona tutte le attività completate e uno che seleziona le NON completate.

**Comment by Dasc3er** [comment]
@antonioscarpino Il problema è stato corretto completamente con gli ultimi commit?

**Comment by antonioscarpino** [comment]
@Dasc3er appena possibile aggiorno all'ultimo commit e do conferma della risoluzione del problema. Grazie

**Comment by antonioscarpino** [comment]
@Dasc3er confermo che non l'aggiornamento all'ultimo commit si risolve il problema in oggetto. Grazie
