### ISSUE TITLE
Conformare il Piano dei Conti

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#21]
Conformare il modulo **Piano dei Conti** con il nuovo sistema di calcolo, per evitare problemi di pochi centesimi come segnalato negli altri moduli.

**Comment by loviuz** [comment]
aggiungo: caricare i dettagli dei conti al click (conti di co_pianodeiconti3) tramite ajax, perché in molti casi, chi ha più di 1000 clienti, riscontra rallentamenti nel caricamento della schermata, perché per ogni anagrafica cliente o fornitore vengono creati dei conti correlati.

**Comment by loviuz** [comment]
Qualcuno vuole provare?
