### ISSUE TITLE
aggiornamento da 2.3.1 a 2.4

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#213]
segnalazione dal forum
https://www.openstamanager.com/forum/viewtopic.php?f=4&t=90097

versione 2.3.1 , dal modulo aggiornamenti dopo upload zip 2.4 si apre correttamente la pagina per avviare l'aggiornamento, ma compare questo errore: 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'osmdbnew.zz_segments' doesn't exist

**Comment by Dasc3er** [comment]
Il problema si verifica solo nel caso venga effettuato l'upload dal modulo **Aggiornamenti**.
La causa è la seguente query della classe **Modules**, dove è stato aggiunto un controllo sulla nuova tabella *zz_segments*:
https://github.com/devcode-it/openstamanager/blob/da843a1113273ee287bb10fdef9fafab8e6c2646/src/Modules.php#L41

Si tratta in ogni caso di un bug che non presenta conseguenze nella procedura di aggiornamento.
Si potrebbe dividere la query in questione per evitare problematiche con le nuove tabelle, ma l'utilità sarebbe estremamente ridotta...

**Comment by loviuz** [comment]
Il problema che ho riscontrato è che più di qualcuno ci chiede come mai dà errore in fase di aggiornamento (per ora durante i test), per cui pensavo se ci fosse un modo per ignorare eventuali errori in certi casi. Come potremmo fare @Dasc3er ?

**Comment by Dasc3er** [comment]
@fpsoftware @loviuz Dovrei essere riuscito ad isolare il problema e a risolverlo...
In particolare, erano state previste in modo errato alcune operazioni sui segmenti nel **include/manager.php**.

Inoltre ho migliorato la funzione di log, in modo che se il debug è attivo vengano mostrata anche la _stack trace_ dell'errore.
@devcode-it/openstamanager Inoltre sarebbe da evitare l'utilizzo dei **short tag**, poichè i loro vantaggi sono estremamente ridotti e sarebbero un requisito aggiuntivo effettivamente non necessario.
