### ISSUE TITLE
CONTRATTO - Fatturazione parziale

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#214]
Fatturando un contratto di vendita solo in parte, dopo l'emissione della fattura non è più possibile fatturare la parte del contratto rimasto, cioè creando una nuova fattura di quel cliente il pulsante +Contratto non è attivo.

**Comment by loviuz** [comment]
Perché lo stato del contratto cambia. Andrebbe aggiunto anche qua "parzialmente fatturato", ed anche nei preventivi. Che ne dici?

**Comment by fgambarelli** [comment]
Io terrei una gestione simile agli interventi

**Comment by loviuz** [comment]
Attualmente, nella 2.4.1, la fatturazione del contratto è per il contratto completo, non gestisce la fatturazione parziale. Quali sono i casi reali in cui potresti fatturare parzialmente un contratto?

**Comment by fgambarelli** [comment]
Abbiamo il 60% dei contratti di durata annuale in cui il cliente richiede la fatturazione in due rate, la prima parte all'inizio del contratto, la seconda spesso dopo 6 mesi.

**Comment by Dasc3er** [comment]
@fgambarelli La funzione è stata completata con la nuova struttura del passaggio tra documenti.
