### ISSUE TITLE
Miglioramento cambio stato automatico su ordini e ddt

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#216]
Gli stati dei ddt e degli ordini ora cambiano automaticamente, però gli utenti vedono lo stato modificabile e non capiscono perché non si salvi, quando in realtà si salva ma viene subito reimpostato.
Andrei a inserire 2 nuove opzioni (una per ddt e una per ordini) che indica se utilizzare il cambio stati automatico e, in quel caso, il campo dello stato diventerebbe readonly.

**Comment by lucasalva87** [comment]
Da gestire, in caso di cambio stato manuale, il calcolo dei i movimenti a magazzino (carico/scarico), quantità e relativi riferimenti al documento.

**Comment by loviuz** [comment]
Lo stato dei vari documenti non incide sui movimenti, o mi sfugge qualcosa? Nel senso che i movimenti avvengono quando si aggiunge un articolo, al di là dello stato documento (ordine, ddt, fattura, ecc)

**Comment by loviuz** [comment]
Visto insieme con me, sembra ok
