### ISSUE TITLE
Testa il database su hosting Aruba

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#217]
Versione 2.4, quando si prova ad installare su Aruba il test del database da esito negativo.

![configurazione openstamanager](https://user-images.githubusercontent.com/30728163/38548406-ff1b0f44-3cb1-11e8-8af1-efff9717c2e4.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Per analizzare le cause del problema, bisognerebbe controllare quali permessi vengono restituiti dalla seguente query e in quale modo sono successivamente interpretati:
https://github.com/devcode-it/openstamanager/blob/9b38ef0f675e6fa68e7c9ea23775e69358bfcd06/include/configuration.php#L55
