### ISSUE TITLE
Stampa interventi 

### ISSUE THREAD

**Issue by mdkdog** [devcode-it/openstamanager#218]
## Comportamento richiesto

stampare totale ore lavorate

## Comportamento attuale

stampa "0,00" come "Ore lavorate:"

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto
Il bug è presente anche sulla demo "https://www.openstamanager.com/demo_24/"

**Comment by Dasc3er** [comment]
Ciao @mdkdog,
grazie mille per la segnalazione!

Il commit 6729b99 dovrebbe risolvere correttamente il problema in questione, modificando una sola riga della stampa...
Potresti confermare il corretto funzionamento?

**Comment by mdkdog** [comment]
Confermo il fix. Ero arrivato alla stessa soluzione. 

Il 13 aprile 2018 17:58:31 CEST, Thomas Zilio <notifications@github.com> ha scritto:
>Ciao @mdkdog,
>grazie mille per la segnalazione!
>
>Il commit 6729b99 dovrebbe risolvere correttamente il problema in
>questione, modificando una sola riga della stampa...
>Potresti confermare il corretto funzionamento?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/devcode-it/openstamanager/issues/218#issuecomment-381181281

-- Inviato dal mio cellulare Android con K-9 Mail.
