### ISSUE TITLE
Aggiunta codice IPA in anagrafica

### ISSUE THREAD

**Issue by xxfuma85xx** [devcode-it/openstamanager#219]
Si potrebbe aggiungere in anagrafica il campo codice IPA per le pubbliche amministrazioni o il codice destinatario della fatturazione elettronica anche per i privati.

Sto cercando di sviluppare un modulo aggiuntivo per la creazione dell'XML per la fatturazione elettronica e questo campo è necessario nell'anagrafica.

Inoltre sarebbe utile averlo anche solo per stamparlo sulle fatture di vendita.

**Comment by loviuz** [comment]
Grazie, infatti ci stiamo avvicinando anche noi ala fatturazione elettronica...

**Comment by Dasc3er** [comment]
Codici aggiunti a partire dal commit d3bbecd2f46a0a0ccd71de7c1d5b5e13b6fed1e5.
