### ISSUE TITLE
Operazioni veloci su anagrafica

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#22]
Qualcuno chiede di aggiungere la creazione intervento dall'anagrafica. Io propongo: perché non creare, ad esempio, un riquadro "Operazioni veloci" da dentro l'anagrafica?
Un tot di pulsanti del tipo "Nuovo intervento", "Nuova fattura", "Nuovo preventivo", ecc... così da aver già pre-selezionata l'anagrafica senza andare avanti e indietro fra i moduli.

**Comment by fpsoftware** [comment]
approvo, bella idea!

**Comment by gabrielepiccinnu** [comment]
Anche io approvo. Ottima idea!

**Comment by Dasc3er** [comment]
Senza re-inventare nuove strutture, non si potrebbe applicare questa iniziativa all'interno di un plugin specializzato?

**Comment by lucasalva87** [comment]
L’idea era quella di modificare “editor.php” in maniera di dare al programma una struttura standard che permetta di far visualizzare nelle varie schermate di modifica i pulsanti prima del form principale. 
All’interno di questa riga presente ad inizio pagina i pulsanti di default saranno “Salva modifiche” e “Torna all’elenco”. Saranno poi visualizzati i pulsanti di stampa e invio email (ove previsto).

Introducendo poi un uovo file “button.php” per ogni modulo si potranno definire dei pulsanti personalizzati quali ad esempio quelli prima menzionati: Nuovo intervento", "Nuova fattura", "Nuovo preventivo” ecc..
“button.php” funzionerà alla stregua di “bulk.php” permettendo di specificare sia struttura che eventuali operazioni da eseguire sul database (Es. “Salva e clona”).

**Comment by Dasc3er** [comment]
Il supporto alla nuova struttura per i pulsanti è stato completato.
Per ora, il file **buttons.php** all'interno di ogni modulo permette di stampare qualsiasi contenuto HTML e lo inserisce su una riga successiva ai pulsanti principali. Se i pulsanti devono prevedere delle funzioni aggiuntive, per il momento sono da gestire normalmente con il file **actions.php** del modulo.

Esempio nel modulo Interventi:
![immagine](https://user-images.githubusercontent.com/15911489/36533389-b1d49eca-17c3-11e8-982a-d5587f4becf8.png)

![immagine](https://user-images.githubusercontent.com/15911489/36533402-ba387c4e-17c3-11e8-9d7a-86db694d0eeb.png)

**Comment by loviuz** [comment]
Molto bene! Ho provato in modalità mobile, sullo schermo di uno smartphone, e in attività ad esempio, i pulsanti vengono uno sotto l'altro, di lunghezze diverse, e portano via spazio ai contenuti... Non so se conviene lasciarli sopra o se compattarli in un'unico menu...

**Comment by Dasc3er** [comment]
Con il commit 0a4a9c14eade4ed60a4ba37ccf1e303b6de13544 i pulsati rimangono statici se si sta navigando da mobile.

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager La funzionalità dovrebbe ora essere completa....
