### ISSUE TITLE
Fatturazione - calcolo errato iva su rivalsa inps

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#221]
Vedi segnalazione su forum:
https://www.openstamanager.com/forum/viewtopic.php?p=96285

L'iva sulla rivalsa inps dovrebbe essere quella di ogni riga della fattura, non calcolare l'iva sulla rivalsa inps prendendo come iva quella di default.

**Comment by loviuz** [comment]
Verificato anche da me, ora è corretto!
