### ISSUE TITLE
Sezionali e fatture pro-forma / auto-fatture

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#222]
Nei sezionali per le fatture prevedere un falg "statistics" con label "Mostra nelle statistiche" per dividere quelle che sono fatture di vendita delle pro-forma o auto-fatture e vedere queste fatture nella schermata statistiche.
Per le fatture pro-forma serve anche flag "fiscal" per mostrare poi il campo "aggiungi prima nota" nella scheda delle fattura.

**Comment by Dasc3er** [comment]
@lucasalva87 Per quanto riguarda il flag per la componente fiscale, è stato inserito come `is_fiscale`.
Rimarrebbe da considerare il flag per l'inclusione nelle statistiche, se ancora utile...

**Comment by Pek5892** [comment]
Le autofatture e le fatture pro-forma sono attualmente escluse dalle statistiche, con il controllo se is_fiscale=1 e se autofatture = 0
