### ISSUE TITLE
Miglioramento installazione moduli e plugins

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#223]
Bisognerebbe verificare il corretto funzionamento dell'installazione e aggiornamento moduli, e rendere possibile installazione + aggiornamento anche di plugins.

**Comment by Dasc3er** [comment]
A livello pratico, le differenze tra plugins e moduli sono estremamente ridotte...
In futuro si potrebbe unificarli in modo completo prevedendo un sistema di moduli e sotto-moduli, semplificando in questo modo la loro intera gestione.

**Comment by Dasc3er** [comment]
@loviuz Implementato all'interno della branch master per la versione 2.4.1, attraverso una generalizzazione delle operazioni di installazione e aggiornamento.
Allo stato attuale i plugin non possono presentare query, al contrario dei moduli che devono averle nella cartella **update/**.

**Comment by loviuz** [comment]
@Dasc3er intendi che non possono presentare query in fase di installazione?

**Comment by Dasc3er** [comment]
I plugin non possono presentare query né in fase di installazione né durante l'aggiornamento.
I moduli possono invece averne seguendo la struttura degli aggiornamenti del progetto (per esempio, file *0_1.sql* e *0_1.php* dentro la cartella **update/**).

**Comment by loviuz** [comment]
avremmo già un plugin che necessita di eseguire delle query, per creare alcune nuove tabelle. per ora le abbiamo eseguite a mano, però arriveremo a gestire la loro esecuzione in qualche modo...

**Comment by Dasc3er** [comment]
Il commit 06ab3b0 dovrebbe completare la funzione, aggiungendo il supporto alle query per l'installazione e l'aggiornamento dei plugin.
Questo adeguamento ha richiesto alcune modifica nella tabella **update** per mantenere correttamente traccia delle versioni.

Con la nuova versione è inoltre stata semplificata la gestione automatica di aggiornamenti per eventuali nuove strutture (installazione tramite Composer, ...).
