### ISSUE TITLE
Calcolo costo chilometrico

### ISSUE THREAD

**Issue by s0und0ut** [devcode-it/openstamanager#224]
## Comportamento richiesto

Calcolo costo chilometrico automatico

## Comportamento attuale

Pur avendo inserito all'interno del cliente i km e avendo impostato sul tipo d'intervento il costo al km, in fase di inserimento di intervento, con calcola in modo automatico il costo

## Passi per riprodurre il comportamento

Inserire un nuovo intervento e constatare che non avviene il calcolo.

## Contesto

* Versione del progetto: 2.3.1
* Versione PHP: 5.3.4
* Tipo di server: hosting e wamp

**Comment by loviuz** [comment]
Funziona

**Comment by s0und0ut** [comment]
Buondì! Ho visto che è stato messo funziona. Sbaglio io qualcosa, o è stato sistemato e lo si troverà nella futura rev?

**Comment by iMatte81** [comment]
Ho provato ora sulla versione di prova online e non funziona, così come non funziona sulla mia installazione
ver. 2.4.4
php 5.6.36
