### ISSUE TITLE
Costo fisso uscita tecnico (miglioria)

### ISSUE THREAD

**Issue by mdkdog** [devcode-it/openstamanager#225]
## Comportamento richiesto

avere un campo su anagrafica cliente dove poter inserire un costo fisso (forfetario?) complessivo di KM, ore viaggio, autostrade...etc (già concordato con il cliente).
riportare questo valore come costo riga "Trasferta intervento nr....".

**Comment by loviuz** [comment]
Attualmente non è gestito, però si potrebbe (per ora) gestire così:

- creare un tipo attività con costi orari a 0€
- nell'attività con costo fisso concordato, inserire una spesa aggiuntiva con il costo fisso concordato

**Comment by mdkdog** [comment]
dovrei creare un'attività per ogni singolo cliente (il costo fisso concordato cambia in base ai KM).
non credo sia una strada percorribile.
