### ISSUE TITLE
Problema articoli e magazzino

### ISSUE THREAD

**Issue by cast941** [devcode-it/openstamanager#227]
Buongiorno,
dopo l'aggiornamento alla versione 2.4 quando vado su articoli o cerco di aggiungerlo su un ddt o una fattura mi da questo errore:

Whoops \ Exception \ ErrorException (E_RECOVERABLE_ERROR)
Argument 1 passed to DebugBar\DataCollector\PDO\PDOCollector::__construct() must be an instance of DebugBar\DataCollector\PDO\TraceablePDO, instance of PDO given, called in ../include/top.php on line 19 and defined

dove la linea 19 è 

$debugbar->addCollector(new DebugBar\DataCollector\PDO\PDOCollector($dbo->getPDO()));

e non riesco a risolvere il problema.

Riuscite ad aiutarmi ?

Grazie

**Comment by Dasc3er** [comment]
@cast941 Potresti disabilitare il debug dal file **config.inc.php**?
In questo modo il problema non dovrebbe presentarsi...

Se utilizzi altre parti del gestionale si verifica lo stesso problema?

**Comment by cast941** [comment]
Ciao, il debug lo ho attivato per capire.
Il gestionale funziona bene in tutte le sue parti tranne che su articoli.
Se lo disattivo quando clicco su articoli carica la barra in alto ma il resto della pagina rimane bianca.

**Comment by cast941** [comment]
Ciao,
fatto come richiesto.

ecco cosa dice il log:
2018-04-28 18:21:44] Logs.ERROR: E_RECOVERABLE_ERROR: Argument 1 passed to DebugBar\DataCollector\PDO\PDOCollector::__construct() must be an instance of DebugBar\DataCollector\PDO\TraceablePDO, instance of PDO given, called in ../include/top.php on line 19 and defined
{"url":"../index.php","ip":"192.168.1.151","http_method":"GET","server":"melanie.lasertecsrl.net","referrer":null,"uid":"226aa0d"} 
[2018-04-28 18:21:44] Logs.ERROR: Uncaught Exception Whoops\Exception\ErrorException: "Argument 1 passed to DebugBar\DataCollector\PDO\PDOCollector::__construct() must be an instance of DebugBar\DataCollector\PDO\TraceablePDO, instance of PDO given, called in ../include/top.php on line 19 and defined" at ../vendor/maximebf/debugbar/src/DebugBar/DataCollector/PDO/PDOCollector.php line 27
{"url":"/fatture/index.php","ip":"192.168.x.xxx","http_method":"GET","server":"xxx.xxx.net","referrer":null,"uid":"226aa0d"}

**Comment by Dasc3er** [comment]
La cosa più strana è l'effettiva presenza di questo errore nei casi in cui il debug è disabilitato...
@cast941 Potresti temporaneamente commentare la riga 19 del file **include/top.php**, in modo che non venga eseguita... Questo risolve il problema?

**Comment by cast941** [comment]
Ciao,
rimane uguale...
Allego schermata
<img width="1146" alt="schermata 2018-04-28 alle 19 24 31" src="https://user-images.githubusercontent.com/35063245/39399195-e0f1868a-4b19-11e8-82d5-eeeee1a0b116.png">

**Comment by cast941** [comment]
Commentando la riga 
$upload_dir = $docroot.'/files/'.Modules::getModule('Articoli')['directory'];
del file modules/articoli/action.php
funziona.
La directory files ha I permessi giusti www-data:www-data
e lasciando commentata anche la riga 19 del file top.php (che mi avevi segnalato tu).

provendo dalla beta 2.3, successivamente passata a stabile 2.3 e dopo 2.4

**Comment by Dasc3er** [comment]
@cast941 Ricapitolando: il problema viene rimosso sole se viene cancellata l'assegnazione della variabile _$upload_dir_ nel file **modules/articoli/actions.php**?
Il commit 9b38ef0f675e6fa68e7c9ea23775e69358bfcd06 effettua proprio questa rimozione (poiché effettivamente il codice era solo una ripetizione...).

**Comment by Dasc3er** [comment]
@cast941 Il problema si presenta ancora oppure è stato risolto?

**Comment by cast941** [comment]
è stato risolto
grazie
