### ISSUE TITLE
Stampe PDF/A

### ISSUE THREAD

**Issue by s0und0ut** [devcode-it/openstamanager#228]
## Comportamento richiesto

Generazione stampe in PDF/A

**Comment by s0und0ut** [comment]
Non volevo aprirla come problema ma come miglioria.

Ti ringrazio per il link.

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager Può tornare utile generare tutte le stampe in automatico utilizzando questo standard PDF?

**Comment by mdbrasco** [comment]
Dasc3er il link non funziona....

**Comment by Dasc3er** [comment]
@mdbrasco Appena testato, è corretto.

**Comment by fpsoftware** [comment]
@Dasc3er penso che la richiesta di @s0und0ut sia dettata dalla necessità di "conservazione digitale" delle fatture, infatti viene consigliato da più parti di adottare il formato PDF/A che assicura il rispetto del requisito di "Leggibilità nel tempo del documento archiviato".

**Comment by s0und0ut** [comment]
@Dasc3er si puo' tornare utile per tutte le stampe in automatico, anzi sarebbe super
@fpsoftware infatti hai centrato in pieno la richiesta, forse dovevo essere più dettagliato ^_^ grazie che hai precisato

**Comment by Dasc3er** [comment]
@s0und0ut @devcode-it/openstamanager Ho aggiunto il codice necessario nella classe dedicata alle stampe.
Per il momento ho messo tutto a commento, poichè il rispetto dello standard rallenta la generazione dei PDF e li rende di dimensione maggiore.
Inoltre, come documentato da MPDF (https://mpdf.github.io/what-else-can-i-do/pdf-a1-b-compliance.html):
```
Important: mPDF is not guaranteed to produce fully PDF/A1-b compliant files in all circumstances. It is the users responsibility to check compliance if this is essential.
```
