### ISSUE TITLE
Errore se edito riga in fattura

### ISSUE THREAD

**Issue by AndreasNogler** [devcode-it/openstamanager#23]
Se cambio una riga generica nella fattura di vendita ricevo errore 404. 
`The requested URL /modules/fatture/editor.php was not found on this server.`

apache_error.log

`[Fri Sep 22 08:14:39 2017] [error] [client ::1] File does not exist: /Applications/MAMP/htdocs/modules/fatture/lib, referer: http://localhost:8888/editor.php?id_module=14&id_record=563
[Fri Sep 22 08:14:44 2017] [error] [client ::1] script '/Applications/MAMP/htdocs/modules/fatture/editor.php' not found or unable to stat, referer: http://localhost:8888/editor.php?id_module=14&id_record=563`

**Comment by Dasc3er** [comment]
Ciao @AndreasNogler,
che versione stai utilizzando al momento?

**Comment by AndreasNogler** [comment]
Versione 2.3 Beta 2

**Comment by Dasc3er** [comment]
@AndreasNogler, possiedi una personalizzazione del modulo fattura?

Per maggiori chiarimenti sull'errore, dovrebbe essere disponibile un file _error.log_ all'interno della cartella **logs** del gestionale...
Se per favore puoi postare i suoi contenuti...

Potresti inoltre provare a replicare l'errore all'interno della demo online (http://www.openstamanager.com/demo23beta/), così da fornirci una base condivisa di partenza?

**Comment by AndreasNogler** [comment]
Non é una versione personalizzata. Versione standard con il database aggiornato dalla versione 2.1
Non ci sono errori nella error.log.
Nel demo online va a buon fine se provo a replicare il errore

**Comment by Dasc3er** [comment]
@AndreasNogler Avresti tempo per inserire una riga all'interno del file core.php per aiutarci a fare alcuni test?

Nella riga 22, dovresti inserire il seguente codice:
`print_r($docroot);exit();`
Potresti per favore postare il testo che compare poi e poi ricaricando la pagina?

Grazie mille...

**Comment by AndreasNogler** [comment]
Ok inserito il codice nella linea 22. Se accedo alla pagine principale mi esce il root del webserver (/Applications/MAMP/htdocs). Se provo a modificare la riga nella fattura non viene eseguita il code della riga 22 e il webserver mi da `The requested URL /modules/fatture/editor.php was not found on this server.`

Sto testando con MAMP sotto macos.

**Comment by Dasc3er** [comment]
Potresti specificare in quale file si verifica il problema alla riga 22?

Inizialmente pensavamo che il nuovo sistema di individuazione del percorso avesse fallito su Mac, ma considerando il percorso da te indicato sembra corretto...
Sembra invece che ci sia un richiamo erroneo al file editor.php senza il prefisso della variabile $docroot...

**Comment by AndreasNogler** [comment]
Ho inserito il code `print_r($docroot);exit();` nel file core.php in riga 22. Se accedo al sito mi esce il percorso di MAMP. Se però ricarico la pagina il errore rimane  `The requested URL /modules/fatture/editor.php was not found on this server.`
Forse mi sono spiegato male.

**Comment by Dasc3er** [comment]
Ok, potrei aver trovato il problema.
Potresti sostituire le seguenti righe nel file core.php:
```
$rootdir = substr($_SERVER['SCRIPT_NAME'], 0, strrpos($_SERVER['SCRIPT_NAME'], '/'));
if (strrpos($rootdir, '/'.basename($docroot).'/') !== false) {
    $rootdir = substr($rootdir, 0, strrpos($rootdir, '/'.basename($docroot).'/')).'/'.basename($docroot);
}
$rootdir = str_replace('%2F', '/', rawurlencode($rootdir));
```

Con queste?
```
$rootdir = substr($_SERVER['SCRIPT_NAME'], 0, strrpos($_SERVER['SCRIPT_NAME'], '/')).'/';
if (strrpos($rootdir, '/'.basename($docroot).'/') !== false) {
    $rootdir = substr($rootdir, 0, strrpos($rootdir, '/'.basename($docroot).'/')).'/'.basename($docroot);
} else {
    $rootdir = '/';
}
$rootdir = rtrim($rootdir, '/');
$rootdir = str_replace('%2F', '/', rawurlencode($rootdir));
```

**Comment by AndreasNogler** [comment]
Ok adesso funziona. Veramente ottimo lavoro :)

**Comment by Dasc3er** [comment]
Perfetto! :D

Grazie ancora per la segnalazione!
