### ISSUE TITLE
Calcolo IVA errato nel preventivo

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#230]
Buongiorno attualmente uso la versione 2.4 e incontro ancora problemi per quanto riguarda il calcolo IVA nel Preventivo.

![schermata 2018-05-04 alle 15 30 16](https://user-images.githubusercontent.com/37365078/39630816-cc76b0e0-4fb0-11e8-8843-ed612dd72cc9.png)

Se dovessi fare i calcoli a mano il risultato diventa  **36,90**
Non capisco dove va a prendere quel centesimo in più poiché gli importi delle singole righe sono corrette ma il suo totale non corrisponde. Questo avviene anche in fase di stampa.
Gentilmente potete verificare grazie anticipatamente

**Comment by loviuz** [comment]
E' lo stesso problema presente prima nelle fatture, verifichiamo...

**Comment by loviuz** [comment]
Dovrebbe ora essere risolto

**Comment by mdbrasco** [comment]
Ottimo... ora funziona correttamente ma si dovrà migliorare anche il totale che è presente nella VISTA sia delle fatture di acquisto che quelle di vendita

![schermata 2018-05-12 alle 15 51 05](https://user-images.githubusercontent.com/37365078/39958036-1bff336a-55fd-11e8-9ab3-720fa035cbf6.png)

Pure se ora l'arrotondamento è corretto in fattura mi continua a comparire nella tabella principale dove seleziono crea fattura nuova o modifica una esistente il totale sbagliato ossia con l'arrotondamento errato.
Grazie

**Comment by mdbrasco** [comment]
Il problema persiste ma ho capito forse il Bug

![schermata 2018-05-12 alle 17 33 07](https://user-images.githubusercontent.com/37365078/39958979-29154b3a-560b-11e8-9390-ff6f01ac8a2d.png)


Analizzando questi calcoli il gestionale sia nei preventivi che nelle fatture di acquisto e di vendita non arrotonda l'iva in modo corretto, mi spiego meglio:
In excel o altri programmi di calcolo l'importo IVA si arrotonda in modo corretto mentre il gestionale arrotonda l'iva non in modo statico.

![schermata 2018-05-12 alle 18 08 39](https://user-images.githubusercontent.com/37365078/39959276-98be0edc-560f-11e8-9561-3f7e2de3c461.png)


Ciao aspetto vostre notizie
