### ISSUE TITLE
INTERVENTI - Problema visualizzazione Calendari Ora inizio e Ora Fine

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#231]
Il calendario di scelta della data ed ora purtroppo non è visibile correttamente.
Occorre spostarsi con le bande laterali o aprire i costi per poter compilare correttamente la data.
![cattura](https://user-images.githubusercontent.com/34273200/39639019-55504504-4fc8-11e8-98b7-f87fee9b4b81.JPG)

**Comment by Dasc3er** [comment]
@fgambarelli Grazie per la segnalazione!
Il problema è causato dall'utilizzo della classe _table-responsive_ per mantenere la tabella consultabile all'interno della pagina, e apparentemente non esiste una soluzione pratica per evitare questo problema oltre a rimuovere la classe in questione.

@devcode-it/openstamanager Che ne pensate? Rimuovendo la classe che causa il problema la tabella rischierebbe di essere troppo ampia...

**Comment by loviuz** [comment]
Capita quando si usanorisoluxionoi basse. Con 1024x768 dovrebbe nascondersi la barra di sinistra, ma non lo fa. Si potrebbe fare in modo che lo faccia.
@fgambarelli, se premi il tasto in alto a sinistra per nascondere il menu, vedi la tabella completa?

**Comment by fgambarelli** [comment]
Se premo il tasto per nascondere il menu non cambia nulla, la visualizzazione del calendario rimane come quella della foto che ho postato.

Il comportamento dovrebbe essere uguale a quando il check "Mostra dettagli Costi" è selezionato.
Come nella foto che vi allego.
<img width="765" alt="schermata 2018-05-17 alle 22 31 40" src="https://user-images.githubusercontent.com/34273200/40202427-39f4b3bc-5a22-11e8-8364-77eedf694533.png">

**Comment by lucasalva87** [comment]
Il fix è temporaneo, in futuro vediamo di sistemare anche la modifica degli orari che risulta ancora difficoltosa da mobile.
Aperto nuovo issue #241
