### ISSUE TITLE
Aggiungere colonna "Prezzo di vendita" sulla lista articoli

### ISSUE THREAD

**Issue by cast941** [devcode-it/openstamanager#233]
Ciao a tutti, 
è possibile una volta andati nel menù "Magazzino --> Articoli" visionando la lista di tutti gli articoli aggiungere anche la colonna con i prezzi di vendità? 
Attualmente non è presente.
Grazie

**Comment by loviuz** [comment]
Sì può aggiungere dal modulo "Viste". Se non è visibile sotto "Strumenti", puoi abilitarlo dal modulo Strumenti -> Aggiornamenti

**Comment by cast941** [comment]
Grazie mille !
