### ISSUE TITLE
Sui select multipli, se cancello il valore e lo ri-seleziono mi carica anche un valore vuoto.

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#234]
![contratti openstamanager 7](https://user-images.githubusercontent.com/30728163/39825386-f6d44ffa-53b1-11e8-90b2-eaf09b72a72e.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Dovrebbe essere stato risolto, potresti confermare?

**Comment by lucasalva87** [comment]
@Dasc3er , perfetto il problema sembra risolto!
