### ISSUE TITLE
Fatture arrotondamento  Migliora

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#235]
Versione 2.4
Salve a tutti ho notato un'anomalia del gestionale nella sezione Fatture di vendite e anche di acquisto.
![schermata 2018-05-10 alle 21 06 18](https://user-images.githubusercontent.com/37365078/39889040-040e4c4e-5497-11e8-8685-bb1ea3d600a4.png)

In pratica quando vado a selezionare la voce Emessa noto che l'importo della fattura viene arrotondato e questo comportamento viene  salvato nella parte Contabilità / Piano dei conti / Scadenzario / Prima nota ecc.
Mi potete spiegare come poter evitare questo fastidiosissimo arrotondamento? 
Grazie...

**Comment by loviuz** [comment]
Stesso problema di arrotondamento dei preventivi
