### ISSUE TITLE
Iva arrotondamento da Migliorare

### ISSUE THREAD

**Issue by mdbrasco** [devcode-it/openstamanager#237]
Il problema persiste ma ho capito forse il Bug

![schermata 2018-05-12 alle 17 33 07](https://user-images.githubusercontent.com/37365078/39958979-29154b3a-560b-11e8-9390-ff6f01ac8a2d.png)

Analizzando questi calcoli il gestionale sia nei preventivi che nelle fatture di acquisto e di vendita non arrotonda l'iva in modo corretto, mi spiego meglio:
In excel o altri programmi di calcolo l'importo IVA si arrotonda in modo corretto mentre il gestionale arrotonda l'iva non in modo statico.

![schermata 2018-05-12 alle 18 18 53](https://user-images.githubusercontent.com/37365078/39959390-0e7019a8-5611-11e8-9a14-24db06a1f709.png)

Questo comportamento alla lunga mi fa sfalsare l'importo totale della fattura esempio:
Con excel 
Imponibile: 3.993,64 €
IVA al 10%: 399,36 €
Tot fatt: 4.393,00 €

Con il Gestionale
Imponibile: 3.993,64 €
IVA al 10%: 399,39 €

**Comment by fgambarelli** [comment]
Aggiungo che questo problema su arrotondamento calcola erroneamente le scadenze, visibili anche in fattura.
![image](https://user-images.githubusercontent.com/34273200/39989186-8d609a36-5769-11e8-8867-9f75bce3674d.png)

**Comment by lucasalva87** [comment]
@fgambarelli confermo che con la nuova versione 2.4.1 facendo delle prove con gli stessi importi, il problema non si presenta.

**Comment by mdbrasco** [comment]
Scusate ho aggiornato il gestionale e rifacendo i calcoli mi compare sempre la stessa cosa però ho capito che il gestionale arrotonda l'IVA anche in queste occasioni esempio:

Imponibile=  194,545 inserendo questo numero è giusto che arrotonda a 194,55
IVA= 19,455 sbaglia arrotondando a 19,46
Totale=  214,00 

Ora in excel l'iva non la arrotonda mentre sul gestionale l'iva la arrotonda e questo crea lo scompenso di 0,01

![schermata 2018-05-18 alle 20 57 26](https://user-images.githubusercontent.com/37365078/40253357-b85683a8-5adf-11e8-9208-1487faa628d0.png)

C'e un modo che non arrotonda quando si trova un numero con queste condizioni 19,455 e quindi che rimanga a 19,45? 
Grazie aspetto vostre notizie

**Comment by mdbrasco** [comment]
Ti chiedo scusa io continuo a inserire le fatture sia di acquisto che di vendita e mi trovo in difficoltà a far combaciare i totali.
![schermata 2018-05-18 alle 22 44 33](https://user-images.githubusercontent.com/37365078/40257137-54056136-5aed-11e8-8200-05cefdb85f74.png)

Anche in questo esempio i totali dell'IVA mi sembrano errati e automaticamente il totale non combacia e il suo risultato e di 497,75.
Accetto la logica della terza cifra decimale che va da 0 a 4 arrotonda per difetto ma alla fine qualche centesimo se li salta... mentre il totale nella lista fatture è corretto

![schermata 2018-05-18 alle 22 49 31](https://user-images.githubusercontent.com/37365078/40257295-0005c0e8-5aee-11e8-8143-85555c66f27b.png)

**Comment by lucasalva87** [comment]
@mdbrasco  come diceva correttamente il mio collega @loviuz . L’arrotondamento è sempre ponderato.
Quindi partendo dalla regola base che tutti gli importi da contabilizzare in Euro devono essere arrotondati al secondo decimale, eventuali arrotondamenti del terzo decimale dovranno essere di tipo matematico, ovvero, se il terzo decimale è inferiore a 5 si arrotonda per difetto, se invece è uguale o superiore a 5 si arrotonda per eccesso.

Esempi:

- Il valore €123,432 si arrotonda a 123,43.
- Il valore €321,238 si arrotonda a 321,24
- Il valore €569,355 si arrotonda a 569,36

Queste regole si devono applicare a tutti gli importi che si definiscono “da contabilizzare”: imponibile, iva,  totale fattura e gli altri elementi riepilogativi devono essere arrotondati seguendo queste regole.

In realtà quindi è proprio il totale nella tabella riepilogativa delle fatture ad essere errato.

**Comment by fgambarelli** [comment]
Il problema è che in fattura il Totale imponibile e l'IVA ottenuta non sono coerenti rispettoa i totali visibili in fattura.
Capisco il problema matematico, allego calcolo,dove il totale dell'iva è dato dalla somme delle singole righe IVA e gli arrotondamenti sono fatti sulla singola riga; 
ma un cliente che riceve la fattura e calcola l'iva dall'imponibile totale indicato in fattura, ritiene l'importo (giustamente) non corretto. Dal mio esempio la fattura riporta come iva 179,37 ma se si calcola il 22% sull'imponibile mostrato in fattura 815.24 il totale iva è 179.35 
Tenendo il concetto dell'arrotondamento, sarebbe più corretto arrotondare sul totale e non sulle singole voci, anche perchè non si contabilizzano le singole voci di fattura, ma il totale delle diverse aliquote.
![image](https://user-images.githubusercontent.com/34273200/41334331-8f3f2fdc-6ee5-11e8-9cda-3fe77702e4d0.png)
