### ISSUE TITLE
FATTURE: split payment per fatture verso PA

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#238]
## Comportamento richiesto
gestione split payment, vedi Art. 17-ter D.P.R. n. 633/72, il totale iva viene trattato come rivalsa, banalmente il totale fattura è uguale all'imponibile

## Possibile soluzione
necessario flag sulla tabella co_iva e modifica su stampa fattura

**Comment by Dasc3er** [comment]
Aggiunto con commit efd23c4783cbe04cbb887851dd6fd3486328003d , 02cf6716c09a909fb31871f79dd1d3422405d3dd, 8c3cc48f33b2e144abeaf20a9cf957423a16450d, ffbbb73ddc92cf2f7823f08760d8516663939364.
