### ISSUE TITLE
Possibile Problema Sola Lettura beta2

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#24]
Stavo provando la versione beta2 che avete rilasciato in questi giorni ed ho riscontrato un possibile problema: da amministratore sono entrato su strumenti->utenti e permessi->tecnici dove ho inserito un nuovo utente tecnico e aggiornato i permessi per il gruppo.  Ho dato ai menu anagrafiche e magazzino e relativi sottomenu il permesso Sola Lettura. Mi sono disconnesso da amministratore e sono entrato con il nuovo utente tecnico creato. A questo punto se entro nel magazzino e voglio accedere ad un articolo per visionare i dati in sola lettura come da permesso, cliccando sull'articolo entra nella pagina di edit, ma mi dice record non trovato anzichè mostrarmi i dettagli dell'articolo (in teoria senza darmi la possibilità di modificarne i dati). La stessa cosa anche nelle anagrafiche che compaiono dopo aver inserito un intervento per il tecnico.  E' un funzionamento corretto o c'è un problema?

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione, @ldanese83 ! 
Si tratta effettivamente di un bug, la cui soluzione puoi trovare nel commitd 45aeb0343806916303f923936685e16062cc5aa :D
