### ISSUE TITLE
EMAIL - Destinatari

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#240]
Nei destinatari non vengono elencate le email dei referenti inseriti nel dettaglio Referenti , ma appare solo l'email generica messa nella scheda principale dell'anagrafica del Cliente

**Comment by lucasalva87** [comment]
Se si cancella l'indirizzo email proposto in automatico, poi compaiono anche le email dei referenti.

![fatture di vendita openstamanager](https://user-images.githubusercontent.com/30728163/40259500-9b96f6f0-5af6-11e8-969b-b69a2aa4cab2.png)
