### ISSUE TITLE
Sessioni di lavoro intervento

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#241]
Migliorare la gestione / visualizzazione delle ore di lavoro in fase di modifica scheda dell’intervento.
Gestire dunque le righe o sessioni di lavoro con il tasto modifica che apre una finestra modale. Alla stregua dell’inserimento materiale utilizzato o altre spese. 
Questo per risolvere i problemi di modifica dei valori se si utilizza il gestionale da dispositivi mobili.

**Comment by Dasc3er** [comment]
Con il commit eb19f8610ade38f2a306e1ac01fe0a4e4b523e4e è stato aggiunto il modal di base per la gestione delle sessioni.
Resta da definire il funzionamento previsto:

- La modifica cancella la sessione precedente e ne crea una nuova (comportamento attuale delle sessioni)
- La modifica cambia la sessione, senza eliminarla
- Spostare la creazione delle sessioni con questo modal?
