### ISSUE TITLE
Migliorare aggiunta intervento permettendo il caricamento di promemoria.

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#242]
Migliorare l’aggiunta delle attività dando la possibilità di:

1. Inserire in maniera facoltativa i dati relativi all’intervento (orario inizio, fine, data intervento ecc...)
2. Aggiunge la possibilità di caricare si da subito materiali, altre spese o allegati

Le attività caricate senza nessun tecnico associato saranno poi visualizzate a destra della Dashboard come promemoria da pianificare con il drag and drop.

**Comment by idraulicadueci** [comment]
Ciao, se non lo hai già considerato, sarebbe importante anche avere la possibilità di aggiungere una breve descrizione dell'intervento nella riga. In alcune attività l'intervento si svolge in più step e da differenti tecnici.

**Comment by Dasc3er** [comment]
@lucasalva87 La funzionalità non è stato già sviluppata?

**Comment by lucasalva87** [comment]
In parte. Il punto #1 è completo. Mentre il punto #2 sarà da sviluppare
