### ISSUE TITLE
API - retrieve interventi formato iCal

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#243]
## Comportamento richiesto
sincronizzazione del calendario appuntamenti con un calendario esterno (esempio Outlook o Smartphone)

## Comportamento attuale
vedere post sul forum: https://www.openstamanager.com/forum/viewtopic.php?f=4&t=91008&p=97250

**Comment by Dasc3er** [comment]
@fpsoftware Il sistema è già stato implementato nell'API ed è accessibile seguendo le istruzioni nella nuova schermata utente.

**Comment by fpsoftware** [comment]
ottimo grazie... mi mancava questa nuova schermata utente!
