### ISSUE TITLE
gestione attività

### ISSUE THREAD

**Issue by cicalo** [devcode-it/openstamanager#246]
## Comportamento richiesto
GESTIONE ATTIVITA' inserimento nuova attività
Avrei la necessità che la data intervento selezionabile NON sia selezionabile nel passato ma dal giorno attuale. E' possibile disinibire la selezine di data non uguali al giorno di inserimento?
Abbiamo fatto diversi errori e devo andare a modificare diverse date inizio lavoro e fine lavoro risalendo con il cartaceo a quanto abbiamo effettuato l'intervento e quando abbiamo avuto la richeista.
Questo mi serve per capire i tempi di risposta che abbiamo.

grazie per la vostra.

**Comment by idraulicadueci** [comment]
Si potrebbero impostare i permessi per la modifica della data intervento in modo che chi non è autorizzato non possa inserire una data diversa da quella corrente.

**Comment by cicalo** [comment]
Grazie Thomas,

era proprio quello di cui avevo bisogno. E bastato aggiungere min-date. Grazie mille.

 

…..

P.S.:

non è che sai come posso disabilitare, per gli utenti con permission di sola lettura,  i tasti  “seleziona tutto, deseleziona tutto, esporta, copia , stampa”  presenti nelle viste tabellari, ad esempio elenco fatture?

 

Grazie

 

Da: Thomas Zilio <notifications@github.com> 
Inviato: domenica 17 giugno 2018 17.26
A: devcode-it/openstamanager <openstamanager@noreply.github.com>
Cc: cicalo <cicalo@imtsol.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [devcode-it/openstamanager] gestione attività (#246)

 

@cicalo <https://github.com/cicalo>  Potresti risolvere il problema modificando la seguente riga:
https://github.com/devcode-it/openstamanager/blob/3a483e975a8a6b9883c2a8eae41cedeaf30a5e09/modules/interventi/add.php#L189

in questo modo:

{[ "type": "date", "label": "<?php echo tr('Data intervento'); ?>", "name": "data", "required": <?php echo ($get['ref']) ? 1 : 0; ?>, "value": "<?php echo $data; ?>", "min-date": "-now-" ]}
