### ISSUE TITLE
Miglioramenti DDT di vendita

### ISSUE THREAD

**Issue by Fabio-Fox** [devcode-it/openstamanager#247]
## Comportamento richiesto

1. L'immissione dell'unità di misura durante il salvataggio dell'articolo sul DDT di Vendita.
2. La possibilità di selezionare la destinazione merce sui DDT di vendita.

## Comportamento attuale

1. Durante l'immissione degli articoli nei DDT di vendita non viene caricato e di conseguenza registrato poi     l'unità di misura.
2. Il richiamo della destinazione merce non viene filtrata dalla query anche se presente nell'archivio.

**Comment by Dasc3er** [comment]
@Fabio-Fox Grazie mille per la segnalazione!
Il problema delle unità di misura era presente anche negli Ordini, e dovrebbe essere risolto con il commit c90a161.

@devcode-it/openstamanager Ho notato che nel file **modutil.php** del modulo Preventivi solo la funzione **get_imponibile_preventivo** viene utilizzata. Le altre si possono rimuovere?
Similmente, il file **modutil.php** del modulo Contratti era solo una copia di quello dei Preventivi...

**Comment by Dasc3er** [comment]
@Fabio-Fox Riguardo al problema sulla selezione della Destinazione Merce, non sono riuscito a riprodurlo...

Potresti eventualmente descrivere meglio i passaggi che hai effettuato per ottenerlo?

**Comment by Fabio-Fox** [comment]
@Dasc3er  Ti ringrazio della risposta. 
Il problema riscontrato sui DDT di vendita è il seguente:
1. Ho verificato la presenza oltre la sede legale del cliente che sia presente una seconda destinazione.
2. La seconda destinazione è stata aggiunta successivamente alla creazione del cliente.
3. Ho iniziato un nuovo DDT di vendita compilato tutti i campi necessari al momento della selezione della destinazione merce la query mi filtra soltanto la sede legale salvata di default sul cliente.
