### ISSUE TITLE
Problemi Fatture di acquisto

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#25]
Ciao, stavo provando ad inserire delle fatture di acquisto ed ho trovato dei piccoli errori. Ho eseguito le prove anche nella demo online accedendo tramite il sito dal pulsante Prova OSM 2.3 beta2 in modo da indicare dove ho riscontrato i problemi.
1- Ho inserito un nuovo ordine di acquisto. Poi ho fatto Crea fattura da ordine. Ordine numero 2(o ED98) della demo. Nella fattura creata la riga non compare in modo corretto, inoltre da errore rosso per la query una volta che esco dalla fattura. Si può vedere dalla fattura numero 2.
2- Ho creato una fattura, la numero 3. L'ho emessa e sono entrato nello scadenziario per pagare la scadenza. Come per la beta 1 non riesco ad inserire il valore su pagato perchè mi dice  Il totale degli importi inseriti non corrisponde al totale da pagare! 
3- Ho creato la fattura numero 4 come la 3 e sono andato su scadenziario a pagarla, questa volta inserendo direttamente la prima nota. Tutto corretto a parte il fatto che poi la fattura risulta in stato Parzialmente pagato anche se ho effettuato tutto il pagamento completo dell'importo. Dovrebbe risultare credo in stato Pagato

**Comment by Dasc3er** [comment]
Grazie ancora per la segnalazione.

Ho risolto i problemi con il commit a65fccf6b8a6f7b37e018b18ca003bf019fda510 e ho caricato la versione corretta online...
Potresti controllare se adesso il funzionamento risulta corretto?

**Comment by ldanese83** [comment]
1 e 2 sono a posto. Per quanto riguarda il 3 ho visto che quando salvi la prima nota dallo scadenziario, ti mette l'importo in automatico nella prima riga, ma poi non lo salva e fa la scrittura senza l'importo del primo conto. Per questo motivo immagino poi mette parzialmente pagato invece che Pagato. Nella versione online c'è ancora l'errore. Vedi prima nota fattura TRY3

**Comment by Dasc3er** [comment]
Colpa mia, mi sono dimenticato di aggiornare la prima nota nella beta online...
@ldanese83 Adesso funziona :D
Fattura di acquisto come esempio: TESTX.
