### ISSUE TITLE
Preventivi con opzioni 

### ISSUE THREAD

**Issue by dariosera** [devcode-it/openstamanager#250]
Ho la necessità di sviluppare una funzionalità che consenta di creare preventivi "a scelta".

Per offrire ad un cliente varie alternative, si possono creare nel preventivo dei gruppi. Ogni gruppo contiene **n** sottogruppi formati da **m** righe (intese come righe di OSM: righe semplici, articoli, descrizioni). Alla fine di ogni sottogruppo viene indicato un subtotale.

In seguito si potrà trasformare il preventivo in ordine, selezionando per ogni gruppo **un solo** sottogruppo.

È utile per mostrare in un unico preventivo varie soluzioni, ma senza _spaventare_ il cliente facendogli vedere un totale pari alla somma di tutte le soluzioni proposte! (Come totale documento io pensavo di mostrare l'importo massimo, cioè quello che si ottiene scegliendo sempre l'opzione più cara).

Giusto per dare una idea a grandi linee della stampa che dovrebbe risultare:

![prev_sezioni](https://user-images.githubusercontent.com/34642278/41260505-fc2695e0-6dd7-11e8-9110-bc1c7def84ec.jpg)

Se può interessare questa funzionalità, la sviluppo in modo da integrarla nel progetto, direttamente nel modulo "preventivi". In questo caso vi chiederò supporto per sviluppare il tutto in modo coerente con il resto del progetto.
Altrimenti la sviluppo come "modulo aggiuntivo".

Cosa ne pensate?

**Comment by fpsoftware** [comment]
ciao @dariosera non abbiamo mai avuto una richiesta del genere, sarebbe interessante integrarla, ma la soluzione più veloce è un modulo aggiuntivo, partendo da una copia del modulo preventivi attuale e delle relative tabelle sul database, dipende anche dal budget del cliente ;-)

il problema più grosso è integrare questa funzionalità con il resto del gestionale, mi spiego meglio prendendo come esempio l'immagine che hai caricato, il cliente ha davanti 2 soluzioni per il suo pavimento, sceglie logicamente una delle due, questa informazione va inserita nel programma, perchè se vado a fatturare questo preventivo devo prendere il costo della soluzione scelta dal cliente, stessa cosa se un domani devo creare un ordine/ddt partendo dal preventivo (oggi mancano questa funzioni)

La cosa è comunque interessante, tienici aggiornati su come vuoi procedere

**Comment by dariosera** [comment]
ciao @fpsoftware 
A questo punto direi di procedere creando un modulo aggiuntivo. Non so bene come si gestisca l'installazione e la disinstallazione del modulo, la creazione delle tabelle e via dicendo, ma leggerò la documentazione e se ho dubbi vi scrivo.

La funzione per trasformare un preventivo in ordine l'ho creata ( #249 ), e andrebbe poi modificata per chiedere, al momento della trasformazione in ordine, quali righe copiare.
Anche la trasformazione da preventivo a fattura va gestita allo stesso modo: non memorizzerei nelle righe del preventivo la scelta effettuata, ma semplicemente importerei nel nuovo documento (ordine, ddt, fattura) solo le righe scelte.
