### ISSUE TITLE
Chilometraggio in modulo attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#251]
## Comportamento richiesto

Inserire i chilometri indicati in anagrafica

## Comportamento attuale

Aggiungendo un intervento nella sezione "Ore di lavoro" non viene inserito il valore sotto la colonna Km

* Modulo: Interventi
* Versione del progetto: Openstamanager 2.4 Rc795995

**Comment by gabrieledaltoe** [comment]
Direi, che dipende anche dalla sede scelta del cliente...

**Comment by idraulicadueci** [comment]
È vero. Però quella indicata nel modulo principale di anagrafica non la prende.

**Comment by Dasc3er** [comment]
Con la versione 2.5 si provvederà alla separazione delle **sedi** dalla tabella delle **anagrafiche**.

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere stato risolto anche nella versione 2.4.11 in sviluppo, in uno dei commit più recenti con l'aggiornamento della logica dietro agli Inteventi.
