### ISSUE TITLE
gestione permessi utenti sola lettura

### ISSUE THREAD

**Issue by cicalo** [devcode-it/openstamanager#252]
#versione opensta 2.3.1

ho notato che se imposto i permessi utenti in sola lettura rimane comunque abiitato il bottone "+" di inserimento in tutti i moduli.
ad esempio utente sola lettura, va in fatture, appare elenco fatture, ma anche il bottone di inserimento nuova fattura e mi fa inserire la testata, poi ovviamente entrando nel dettaglio il resto è tutto disabilitato, ma intanto la fattura l'ha creata.
Questo  accade per tutti i moduli ove presente elenco con la possibilità di inserire un nuovo record.
Sbaglio qualcosa non conoscendo bene la procedura? oppure è proprio così? Si può fare qlcs per ovviare ?
grazie.

**Comment by dariosera** [comment]
A me non si presenta questo problema, ho provato con la 2.3, 2.3.1 e 2.4.
Sei sicuro di aver impostato bene i permessi per il singolo modulo?

**Comment by cicalo** [comment]
mi  devi scusare veramente. Facevo le prove con admin pensando di essere utente. era tardi.
Mi dispiace farvi perdere tempo inutilmente. colpa mia e del rinc.......mento!!
ho fatto anceh io le prove adesso a mente lucida e sì funziona tutto. scusatemi nuovamnete.
chiudo subito.

**Comment by dariosera** [comment]
Ah tranquillo, non sono uno sviluppatore di Osm ma solo un utilizzatore come te. Buona giornata!
