### ISSUE TITLE
Miglioramento pianificazione interventi da dashboard

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#253]
Semplice modifica: raggruppare per zone le pianificazioni sulla destra della dashboard, perché a molti risulta utile pianificare le manutenzioni in base alla zona

**Comment by Dasc3er** [comment]
@loviuz Considerando la generale rimozione delle zone nell'utilizzo generale del gestionale, questa issue è ancora valida?

**Comment by lucasalva87** [comment]
Alla fine se uno non utilizza le zone non cambia nulla, quindi direi che si può prevederla. @loviuz  che dice?

**Comment by Pek5892** [comment]
Questa modifica verrà introdotta con le migliorie al modulo Mappa
