### ISSUE TITLE
Problema fatturazione DDT acquisto

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#254]
## Comportamento attuale

Selezionando il DDT di acquisto--> CREA FATTURA andando nella sezione ACQUISTI--> FATTURE DI ACQUISTO viene restituito il seguente messaggio di errore:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'idsede' cannot be null

Sarebbe inoltre utile processare la creazione di una fattura di acquisto come avviene per quelle di vendita, cioè avere la possibilità, all'interno del modulo di creazione della fattura di acquisto, di selezionare i DDT relativi a quel fornitore.

* Versione del progetto: OSM 2.4

**Comment by Dasc3er** [comment]
@idraulicadueci Il problema non si verifica nell'ultima versione in sviluppo...
Molto probabilmente è stato risolto in uno dei commit recenti.
Potresti confermare?

**Comment by Dasc3er** [comment]
Riguardo alla possibilità di aggiungere i **DDT di acquisto** in una _Fattura di acquisto_, mi sembra che al momento non sia permesso perché il gestionale è specializzato in questo senso alla gestione della contabilità dell'azienda nel flusso di vendita.
@devcode-it/openstamanager Mi sto sbagliando?

**Comment by idraulicadueci** [comment]
Provo a rifare la procedura e ti faccio sapere. Ma per aggiornare con le modifiche recenti, cosa devo fare?
Riguardo la tua seconda risposta, la funzione esiste. Dentro DDT di acquisto, sopra la tabella righe c'è il pulsante "Crea fattura da DDT"; quello funziona e genera correttamente la fattura di acquisto.

![senza nome](https://user-images.githubusercontent.com/40104356/42732356-521a7f0e-8820-11e8-9d32-699c021b4f48.png)

Invece la funzione presente nella pagina dell'elenco DDT di acquisto

![senza nome2](https://user-images.githubusercontent.com/40104356/42732381-d9855f54-8820-11e8-9a2a-db99653c1b21.png)

mi restituisce l'errore.

**Comment by loviuz** [comment]
si dovrebbero poter inserire ddt di acquisto in fattura di acquisto per chi vuole mantenere un collegamento fra ddt e fattura, può servire negli acquisti come controverifica su ciò che è arrivato tramite ddt e ciò che è stato poi fatturato.

**Comment by Dasc3er** [comment]
@idraulicadueci Il problema sulla fatturazione bulk dovrebbe ora essere risolto, ma la funzionalità è limitata ai DDT di vendita (veniva erroneamente mostrata per quelli di acquisto).
