### ISSUE TITLE
Modifica stampa contratti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#255]
## Comportamento richiesto

Far scomparire la dicitura "Il tutto S.E. & O. In attesa di un Vostro Cortese riscontro, colgo l'occasione per porgere Cordiali Saluti" una volta che il contratto è accettato.

Far comparire i dati relativi all'impianto oggetto del contratto (se indicato), va bene anche nelle righe articoli; ad esempio "Impianto X n. matricola Y e luogo di installazione"

* Modulo: Contratti
* Versione del progetto: OSM 2.4

**Comment by Dasc3er** [comment]
Con il commit 25c4e3e la modifica è stata inserita nella branch master.
Ecco la visualizzazione degli impianti:
![immagine](https://user-images.githubusercontent.com/15911489/42808047-9ef29f12-89b2-11e8-9251-098c5884568a.png)

@lucasalva87 Per la rimozione della scritta, ho impostato il controllo sul flag _fatturabile_ in **co_staticontratti**.
