### ISSUE TITLE
BUG: preventivi, ddt, margini e filtri permessi

### ISSUE THREAD

**Issue by deltacomputers** [devcode-it/openstamanager#258]
Buongiorno,
Innanzitutto complimenti per il software. Ho iniziato ad usarlo da poco, in attesa di alcune personalizzazioni, e devo dire che e' veramente ben strutturato.

Volevo porre l'attenzione su dei problemi rilevati nella versione 2.4 ;

- [x] Quando si genera un DDT (non ho attualmente provato con altri documenti), spostando l'elenco delle righe e descrizioni dopo averle inserite, cambia l'ordine visivamente ma in stampa ripropone l'ordinamento originario.
- [ ] Margini di stampa: Nella stampa delle Fatture, DDT e preventivi, il foglio risulta decentrato verso il basso. Non crea problemi nella parte superiore ma nella parte inferiore del foglio viene tagliata la griglia di riepilogo.
- [x] Preventivi: Dal preventivo, in qualsiasi stato esso venga posto, non consente di generare un DDT automaticamente, per poi essere convertito a fine mese in fattura (da preventivo a ddt il passaggio deve essere fatto manualmente ricopiando tutto, mentre da ddt a fattura e' automatico con la generazione fattura differita).
- [x] Prolema Seriali: Se nel DDT si inseriscono i seriali degli articoli venduti, generando la fattura nella visualizzazione del programma gli articoli con i seriali vengono evidenziati con la dicitura rossa che avvisa della mancanza del serial number. Stampando la fattura il codice viene correttamente riportato.
- [x] Prolema autorizzazioni: Ho notato che, impostando le autorizzazioni cliente e mettendo i permessi in sola lettura ad un anagrafica, il filtro non sempre funziona. Ad esempio nella sezione delle attivita', dando il permesso di sola lettura, il cliente può comunque modificare il contenuto. In molte sezioni inoltre (attività, DDT Vendita quelle attualmente verificate in quanto sarebbero a mio avviso le piu importanti da far visualizzare ad un cliente oltre alle fatture e preventivi) il filtro non funziona, se si da' il permesso di sola lettura a un cliente questo vede tutto il contenuto, compresi i DDT delle altre anagrafiche.
- [ ] Suggerimento link DDT: vorrei suggerire lo spostamento della voce DDT acquisto sotto il menu' Acquisti e la voce DDT vendita sotto la voce Vendite, in quanto sarebbe piu immediato rispetto ad utilizzarli nella voce menu Magazzino

Grazie, 
Stefano

**Comment by Dasc3er** [comment]
@deltacomputers Grazie per i suggerimenti e le problematiche indicate!

Riguardo ai seriali nei DDT, il funzionamento del gestionale sembra corretto:

- Creo un DDT con un articolo
- Aggiungo dei seriali nell'articolo
- Sposto il DDT come Evaso/Parzialmente Evaso
- Utilizzo il pulsante Crea fattura (selezionando i seriali da riportare)
- Nella nuova fattura, vengono riportati solo i seriali selezionati (se il numero è inferiore alla quantità dell'articolo, compare giustamente il messaggio in rosso)

In particolare, non sono riuscito a replicare il problema dei margini delle stampe...
Potresti indicare con maggior dettaglio come hai riscontrato il malfunzionamento (eventualmente con screenshot)?

**Comment by deltacomputers** [comment]
Allego screenshot della fattura generata da "genera fattura" su un ddt

In fase di stampa esce il seriale, ma nella descrizione fattura no.

Saluti,
Stefano

Il 2018-07-14 20:58 Thomas Zilio ha scritto:

**Comment by Dasc3er** [comment]
@deltacomputers Con gli ultimi commit sono stati risolti il problema dei seriali e parzialmente quello delle autorizzazioni. In particolare, sono stati aggiunti dei filtri di base (da abilitare a scelta nel modulo **Viste**) per impedire la visualizzazione di Fatture/DDT/Ordini di clienti diversi per gli account Clienti. 

Il fatto che la modifica non venga bloccata per gli utenti in sola lettura sembra causato però da un malfunzionamento locale, potresti controllare se ci sono errori segnalati nella console JavaScript del browser?
