### ISSUE TITLE
Problema con caratteri speciali nei tag personalizzati

### ISSUE THREAD

**Issue by AndreasNogler** [devcode-it/openstamanager#26]
Ciao,

Ho provato inseriere nella descrizione del articolo un carattere speciale (tipo "). Se inserisco l'articolo nella fattura non ci sono problemi. Se però provo a modificarlo non compare più la descrizione e viene tolta dalla fattura. Si può riprodurre nella demo con articolo 123 descrizione 1/4"

**Comment by Dasc3er** [comment]
Effettivamente, questo è un problema distribuito nelle varie sezioni di aggiunta/modifica e viene causato dal formato JSON che utilizziamo per gestire la generazione dei form HTML...

La seguente sezione di codice del file **modules/fatture/edit_riga.php**:
{[ "type": "textarea", "label": "'.tr('Descrizione').'", "name": "descrizione", "required": 1, "value": "'.$rsr[0]['descrizione'].'" ]}

Diventa, a livello di runtime:
{[ "type": "textarea", "label": "Descrizione", "name": "descrizione", "required": 1, "value": "**articolo 123 descrizione 1/4"**" ]}

Proprio la presenza dell'apice doppio all'interno del formato genera il problema in questione.

Credo ci siano due soluzione possibili:

- Utilizzare una funzione che codifica questi caratteri speciali all'inserimento nel formato.
`{[ "type": "textarea", "label": "'.prepareToField(tr('Descrizione')).'", "name": "descrizione", "required": 1, "value": "'.prepareToField($rsr[0]['descrizione']).'" ]}`

- Introdurre un metodo PHP utilizzato per generare direttamente il formato (o l'output).
```
HTMLBuilder\HTMLBuilder::build([
    "type" => "text",
    "label" => tr('Descrizione'),
    "name" => "descrizione",
    "required" => 1,
    "value": $rsr[0]['descrizione'],
]);
```

@loviuz @lucasalva87 @fpsoftware Cosa ne pensate?

**Comment by lucasalva87** [comment]
@Dasc3er 
Ciao Thomas, penso che un "prepareToField" (ex save) possa andare più che bene per risolvere la questione.

**Comment by Dasc3er** [comment]
@lucasalva87 Da inserire su tutti i campi **Descrizione** nella modifica righe e articoli?

**Comment by lucasalva87** [comment]
Sarebbe da prevedere per tutti i campi input e texarea. (es. ragione sociale, note, ecc..)

**Comment by Dasc3er** [comment]
Il punto è che questo problema si verifica esclusivamente nei campi in cui il contenuto viene stampato direttamente sul formato...
Quindi ad esempio gli edit.php generali dei moduli ne sono esenti, mentre i form di aggiunta e modifica no. 

Un'altra alternativa sarebbe passare anche questi dati con la sostituzione automatica attraverso le variabili $$.
