### ISSUE TITLE
Impedire l'eliminazione di documenti completati

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#261]
## Comportamento richiesto

Impedire l'eliminazione di un documento quando ha lo stato "COMPLETATO"

## Possibile soluzione

Far acquisire lo stato disabilitato al comando "ELIMINA" quando il documento è stato flaggato come "COMPLETATO", in modo che l'utente sia obbligato a modificarne lo stato prima della cancellazione.

**Comment by Dasc3er** [comment]
Per completare la funzione è necessario aggiungere il flag **is_completato** all'interno delle seguenti tabelle:
- `co_statidocumento`
- `co_staticontratti `(per ora è presente `fatturabile`, con comportamenti simili)

Inoltre, le tabelle `co_statipreventivi`, `dt_statiddt`, `in_statiintervento`, `or_statiordine `presentano il campo **completato**, da aggiornare di conseguenza.

**Comment by Dasc3er** [comment]
@loviuz I falg relativi per questa funzionalità sono disponibili da diverse versioni, ma al momento nella maggior parte dei documenti l'eliminazione è permessa in ogni caso. Anche se ci sono altri documenti collegati, il limite massimo imposto dal gestionale è un alert informativo che afferma possibili problematiche in caso di eliminazione.

**Comment by loviuz** [comment]
Alcuni utenti chiedono di "blindare" dei documenti, ad esempio quando una fattura è stata inviata elettronicamente e ricevuta dall'agenzia entrate non deve essere più modificata. La stessa logica dovrebbe essere anche per i ddt una volta spedita la merce, però capita che a volte si voglia correggere qualche dato in un ddt evaso perché ci si è dimenticati ad esempio di collegare l'articolo in una riga. In realtà questo potrebbe succedere anche per le fatture, per questo al momento non vorrei che questa blindatura fosse troppo poco permissiva. Al massimo si può bloccare l'eliminazione in base al flag is_completato=true e, nel caso serva eliminare il documento, si cambia prima di stato per apporre un ostacolo in più.

**Comment by Pek5892** [comment]
Controllo introdotto per le fatture di vendita inviate allo SDI, modifica invece permessa per gli altri documenti.
