### ISSUE TITLE
Miglioria: aggiunta dei flag STAMPATO e INVIATO

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#262]
## Comportamento richiesto

Dare la possibilità all'utente di conoscere se un documento è stato già stampato e/o spedito per email.

## Possibile soluzione

Far modificare l'etichetta dei pulsanti STAMPA e INVIA EMAIL che una volta eseguiti i comandi diventeranno RISTAMPA e REINVIA EMAIL.

**Comment by lucasalva87** [comment]
Più che variare l'etichetta dei pulsanti l'invio va registrato e inserito all'interno di un log generalizzato che tiene traccia di tutte le azioni svolte dall'utente, tra cui appunto l'invio dell'email. 
L'argomento è discusso qui #137

**Comment by Dasc3er** [comment]
A partire dalla versione 2.4.2 si potrà mostrare eventualmente un messaggio nel caso l'invio delle email sia già stato effettuato, ma non è possibile risalire all'effettiva stampa dei PDF poichè vengono generati _ad hoc_ per ogni richiesta da parte dell'utente.

**Comment by idraulicadueci** [comment]
Grazie! L'importante è sapere se uno ha già stampato/inviato un documento, per evitare di ripetere il lavoro più di una volta.

**Comment by Dasc3er** [comment]
La funzione relativa ai log di invio email è stata completata nella versione 2.4.2 attraverso la classe **HTMLBuilder\Manager\EmailManager** e il codice `{( "name": "log_email", "id_module": "$id_module$", "id_record": "$id_record$" )}`.
