### ISSUE TITLE
Reso da clienti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#263]
## Comportamento richiesto

Non è prevista la registrazione di un reso da parte del cliente. In questo modo è difficile gestire i noleggi.
Sarebbe opportuno che gli articoli e relativi lotti o matricole, potessero rientrare in magazzino.
Questo in virtù del fatto che esistono degli articoli, in genere apparecchiature, che vengono date in sostituzione durante una riparazione.

## Possibile soluzione

Aggiungere un flag "NOLEGGIO" all'anagrafica articolo, che dia la possibilità sulla riga articoli di riportarlo in magazzino, magari aprendo una ulteriore finestra dove indicare la data di restituzione, senza rimuovere la riga dal documento e aggiungendo ad essa "RICONSEGNATO IN DATA XX/XX/XXXX"

**Comment by fpsoftware** [comment]
ciao @idraulicadueci 
il nostro programma infatti non prevede la gestione dei noleggi di apparecchiature.

Per altri abbiamo già realizzato personalizzazioni ad hoc per gestire questi casi, valuta anche tu l'acquisto di un pacchetto ore per sviluppare questa funzionalità.

Grazie.

**Comment by idraulicadueci** [comment]
Ciao Fabio,
avevo messo i noleggi come esempio, però la gestione dei resi è una cosa che va di pari passo con il documento di trasporto; infatti nella registrazione dei carichi di magazzino spesso ci sono i resi per materiale difettoso, per quantità superiore a quella ordinata, ecc. e quindi la possibilità da parte del cliente di restituire la merce è da considerare nella strutturazione base del vostro software. Allo stato attuale non è impossibile effettuare l'operazione, però è necessario che il cliente sia anche fornitore, in modo da gestire i resi come DDT di acquisto. Resterebbe il problema per le merci facenti parti di un lotto o aventi una matricola. Adesso non è possibile caricare un s/n già caricato in precedenza.
Un saluto
