### ISSUE TITLE
SCADENZIARIO - Errore Prima Nota

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#264]
In Scadenzario va in essere nell'inserire la scadenza di Prima Nota

![image](https://user-images.githubusercontent.com/34273200/42081576-1733f556-7b86-11e8-89de-34880b7b2210.png)

**Comment by Dasc3er** [comment]
@fgambarelli Questo problema si verifica nella versione stabile precedente (2.3) oppure nella versione in sviluppo (2.4.1)?
Perchè sembra già essere stato risolto nella versione in sviluppo...

**Comment by fgambarelli** [comment]
Ho installato la versione di Sviluppo (2.4.1) ma va in errore perché non esiste lo script di creazione della tabella co_contratti_promemoria

**Comment by lucasalva87** [comment]
Il commit aebb508 dovrebbe impedire il verificarsi del problema. Di fatto il programma prevedeva, erroneamente, di poter associare più banche allo stesso conto sul piano dei conti.

**Comment by fgambarelli** [comment]
Dopo aver fatto un git pull, dopo il logon, l'errore sulla tabella "co_contratti_promemoria" rimane.

Probabilmente non è legato all'errore della prima nota.
