### ISSUE TITLE
BUG: errore pagamento parziale fattura

### ISSUE THREAD

**Issue by miatmax** [devcode-it/openstamanager#265]
Ho fatto le prove direttamente nel demo online.
Mettendo in emessa una fattura crea giustamente scadenza e tasto "aggiungi prima nota"

![schermata1](https://user-images.githubusercontent.com/39586203/42122375-320c8eea-7c41-11e8-9e83-9f45f5a0c847.png)

Premendo il suddetto tasto per pagare la fattura di acquisto nella prima nota avendo anche spese bancarie per il bonifico l'ho registrato nel seguente modo
![schermata2](https://user-images.githubusercontent.com/39586203/42122391-77c7c03a-7c41-11e8-8baf-6e0a71f24184.png)

Qui mi aspetterei come miglioria se possibile che nella scadenza ora mi mostri solo il residuo (ma questa è un mio gusto personale, quindi sentite anche altri cosa ne pensano)

Il problema nasce ora, quando pago una seconda rata (Il problema nasce ovviamente se avevo una scadenza di pagamento, ma non sono riuscita a pagarla tutta e quindi ho dovuta "dividerla")

Dovrebbe comparire la differenza dei pagamento 1490.84-490.84 = 1000 euro,  invece   

![schermata4](https://user-images.githubusercontent.com/39586203/42122424-03a6cfd8-7c42-11e8-9463-2f8bc2030537.png)
Non ha scalato dalla scadenza solo il conto  "PPP", ma ha scalato tutto il totale della colonna dare

## Possibile soluzione
Dovrebbe scalare solo l'importo del conto del cliente, e non anche le spese bancarie che ho sostenuto

Spero di essere stato chiaro e aver creato un post non troppo "pesante"

Grazie

**Comment by miatmax** [comment]
Buongiorno,
ho appena fatto un'altra prova in un "conto pulito" ed ho notato una cosa.
Il conto del cliente è corretto --> residuo 500 euro

![prova2](https://user-images.githubusercontent.com/39586203/42122514-56967152-7c43-11e8-93a0-59dd08a2e6fb.png)

ma se faccio il pagamento della seconda rata mi indica 499

![prova1](https://user-images.githubusercontent.com/39586203/42122518-5e336fd2-7c43-11e8-99f7-5b450d64604e.png)

Spero torni utile

**Comment by loviuz** [comment]
Credo sia sbagliato inserire la commissione della banca nello stesso movimento. Lo facevamo anche noi per comodità, ma non è corretto. Va fatto un movimento a parte, come lo è nel conto corrente ad esempio. Lascio comunque eventuali commenti a chi ha più esperienza di me in ambito contabile, ma non è un bug, piuttosto un approfondimento ed eventuale miglioria.

**Comment by miatmax** [comment]
Buongiorno, purtroppo la nostra banca (UNICREDIT) crea un unico movimento nell'estratto conto comprensivo di spese bancarie.
Per quello cercavo di farlo nello stesso movimento, per farlo uguale all'estratto conto.
Grazie

**Comment by Dasc3er** [comment]
@miatmax Con la versione in sviluppo 2.4.11 è stata rivista la gestione della Prima Nota, e di consguenza il problema potrebbe essere stato risolto.
Riusciresti a controllare?

**Comment by loviuz** [comment]
@Dasc3er il problema c'è ancora in master (futura 2.4.11). Esempio:

Fattura da 1000€ + iva
Pagamento: 30/60gg (quindi 2 rate da 610€ ciascuna)

Se in prima nota inserisco:
![immagine](https://user-images.githubusercontent.com/1647128/66717882-31784900-edde-11e9-88db-c9b821a03630.png)

viene rilevato che ho pagato 610€ della prima rata e 2€ della seconda:
![immagine](https://user-images.githubusercontent.com/1647128/66717943-7ef4b600-edde-11e9-801e-6a416af6412a.png)

In realtà della seconda rata non ho pagato nulla. I 2€ sono delle spese bancarie.

Una soluzione potrebbe essere che l'importo da impostare come pagato nello scadenzario sia quello presente nel conto del cliente (610€ in questo caso), perché è quello l'importo reale che va a ridursi fino ad arrivare a 0€ quando è pagato tutto.

**Comment by Dasc3er** [comment]
@loviuz questo era voluto perché era richiesto che si potessero dividere le rate in conti diversi: 612 euro in due righe da 306 euro nella stessa prima nota. Se invece è semplicemente richiesto che solo le prime due righe siano collegate al documento si può modificare la logica per scollegare tutte le altre, ma non dovrebbe essere possibile inserire totali che non tornano come in questo caso: la prima riga indica 612 euro per la fattura, la seconda -610 euro per la fattura e la terza non legata alla fattura potrebbe provocare errori di totali sulle scadenze.

**Comment by Dasc3er** [comment]
Proporrei quindi una ulteriore modifica al sistema di prima nota: al posto di mostrare tutti i pagamenti in righe sequenziali senza che sia presente un riferimento diretto al documento, potrebbe essere utile fare dei raggruppamenti per fattura.

### Esempio
Fattura 01-2019(pulsante per aggiungere riga)
Conto | 612 | 0
Conto | 0 | 610
Conto | 0 | 2

Fattura 02-2019(pulsante per aggiungere riga)
Conto | 60 | 0
Conto | 0 | 60

Generale (pulsante per aggiungere riga)
Conto | 2 | 0
Conto | 0 | 2

In questo modo sarebbe più chiaro a cosa le diverse righe sono riferite. Dunque sulle fatture andrebbero indicate le sole rate, e in Generale gli altri importi che non devono essere considerati nello scadenziario.

**Comment by loviuz** [comment]
L'esempio sopra lo intendi come modifica grafica della popup di inserimento prima nota?

**Comment by Dasc3er** [comment]
Si, ma anche come logica...
Se aggiungo una riga alla fattura essa sarà collegata al documento e inclusa nel controllo dei totali per il solo documento.

**Comment by Dasc3er** [comment]
@miatmax Abbiamo completato le modifiche nella PR #670 per gestire al meglio le informazioni presentate in Prima Nota ed evitare problemi di comprensione del sistema come avvenuto in questo caso.

Di seguito un esempio della nuova grafica:
![immagine](https://user-images.githubusercontent.com/15911489/68224783-91ce6500-ffef-11e9-9050-cf8d40e4ba4d.png)
In questo caso tutti gli elementi aggiunti al documenti tramite la Prima Nota vengono scalati dalle scadenze, ed è possibile aggiungere delle righe separate e indipendenti dalla fattura come cercavi di fare.

Il sistema dovrebbe essere rilasciato in una versione successiva alla 2.4.11, a che non vengano effettuati ulteriori test più completi.
