### ISSUE TITLE
MIGLIORIA: modifica input sconto

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#266]
## Comportamento richiesto

Modificare l'input dello sconto % nella forma Sc1 + Sc2 + Sc3. Infatti molti fornitori applicano delle scontistiche del tipo (per es.)  50%+10%+5%, che ovviamente non è uno sconto del 65%, ma il 50% del prezzo di listino, dal risultato viene scontato il 10% e dal successivo scontato un altro 5%.

**Comment by idraulicadueci** [comment]
Ok, non lo avevo trovato. Grazie

**Comment by Dasc3er** [comment]
Per riferimento: #112
