### ISSUE TITLE
Miglioria: flag "Obsoleto" in anagrafica

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#267]
## Comportamento richiesto

Aggiungere un flag "Obsoleto" nelle anagrafiche articoli e clienti/fornitori, quando questi non sono più attivi (per es. attività cessate, clienti perduti, articoli non più esistenti).

**Comment by lucasalva87** [comment]
Gli articoli hanno il flag "Seleziona per rendere attivo l'articolo" che permette di disattivare l'articolo e non renderlo più visibile nel programma. Mentre per le anagrafiche cliente attualmente è possibile sfruttare la relazione "Dormiente".

**Comment by idraulicadueci** [comment]
Chiedo scusa, non avevo fatto caso alle funzioni.
