### ISSUE TITLE
Articoli: prezzo e codice per fornitore

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#268]
## Comportamento richiesto

Mi riaggancio alla discussione #52, con qualche aggiunta.
Gestione separata del codice fornitore collegata all'articolo per una rintracciabilità immediata in fase di registrazione del documento di acquisto;
prezzo collegato a quell'articolo caricato da quel fornitore, con la possibilità di aggiornare in tempo reale il prezzo.

Es: ARTICOLO1 codice XXXXX del fornitore A prezzo € 1,00 - codice YYYYY del fornitore B prezzo € 2,00, quando in fase di inserimento di documento di acquisto del fornitore A richiamo ARTICOLO1 o  XXXXX il prezzo di acquisto restituito è € 1,00, se lo richiamo con ARTICOLO1 o YYYYY del fornitore B il prezzo restituito è € 2,00.

**Comment by Dasc3er** [comment]
@idraulicadueci Posso confermare che questa funzionalità è stata completata, ma al momento non verrà rilasciata nella versione pubblica del gestionale poiché fa parte della **componente aggiuntiva a pagamento Distinta base.**
