### ISSUE TITLE
Dati dell'articolo non vengono inseriti nel modulo attività

### ISSUE THREAD

**Issue by AndreasNogler** [devcode-it/openstamanager#27]
Ciao,

Ho provato a inserire un articolo nel modulo attività. Non viene inserito prezzo e descrizione.
Negli alti moduli funziona senza problemi (fatture, preventivi, ordini...)

**Comment by Dasc3er** [comment]
@AndreasNogler Intendi all'interno della sezione per l'inserimento?
Nel senso che quando si seleziona un articolo prezzo e descrizione non vengono completati in automatico?

**Comment by AndreasNogler** [comment]
Esatto

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione!
