### ISSUE TITLE
Controllo delle partite Iva comunitarie

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#270]
aggiungere nel modulo Anagrafiche la possibilità di verificare se la partita iva del cliente/fornitore inserita è valida ed inserita nell'archivio VIES (Vat Information Exchange System)

L'inserimento nell'archivio è obbligatorio se si emettono/ricevono fatture da o per l'estero

**Comment by Dasc3er** [comment]
@fpsoftware Il sistema di validazione introdotto con la versione 2.4.1 contiene la libreria [Mpociot\VatCalculator](https://github.com/mpociot/vat-calculator#validate-eu-vat-numbers) che effettua di default questo controllo se è abilitata l'estensione SOAP di PHP, aggiunta di conseguenza ai requisiti facoltativi.

In effetti uno dei possibili miglioramenti del sistema attuale è la separazione di questo controllo dal salvataggio delle informazioni, magari aggiungendo un pulsante generale "Valida" che controlla gli eventuali campi validabili esternamente (tipo la partita IVA e le email).

Documentazione: https://github.com/mpociot/vat-calculator#validate-eu-vat-numbers

**Comment by Dasc3er** [comment]
Con il commit c56df15 è stato aggiunto un controllo di base sulla sintassi delle partite IVA.
In ogni caso il messaggio informativo è ora:
`Attenzione: la partita IVA ------ sembra non essere valida. Per conferma il servizio Verifica partita iva del sito dell'agenzia delle entrate.`
