### ISSUE TITLE
Possibilità di convertire xml fattura elettronica in pdf

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#271]
![fatture di acquisto openstamanager 7](https://user-images.githubusercontent.com/30728163/42867378-b7c8b23e-8a6f-11e8-8499-f7aeb15d2939.png)

Potenziare uploads affinché quando viene caricato un file “.xml” che contiene nell’header il tag "FatturaElettronica" venga visualizzato un pulsante per scaricare il pdf della fattura. Questo pulsante consentirà di convertire al volo l’xml in pdf e scaricarlo in un formato più leggibile (vedasi esempio qui sotto).

![c users luca vdftce tmp it05024030289_it_186oj html](https://user-images.githubusercontent.com/30728163/42868205-07339dc8-8a72-11e8-9302-e76cb97c3a6d.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Al momento non esistono librerie manutenute che effettuano la trasformazione da XML a PDF.
Non si potrebbe semplicemente rendere possibile la visualizzazione dell'XML in formato grafico, secondo le linee guida ufficiali?

**Comment by Dasc3er** [comment]
Aggiunta possibilità di visualizzare l'XML con lo stile predefinito.
Commit 0c1d9c4.
