### ISSUE TITLE
Miglioria: Avviso se esco senza salvare dopo modifica

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#272]
## Comportamento richiesto

Se esco senza salvare da un documento che ho modificato, appare una finestra decisionale tipo "Il documento è stato modificato. Salvare prima di uscire?"

**Comment by Dasc3er** [comment]
@idraulicadueci La funzionalità dovrebbe essere già presente se la modalità di debug non è attiva...

**Comment by idraulicadueci** [comment]
@Dasc3er Grazie

**Comment by Dasc3er** [comment]
Il commit 73e66a2786779afba004738ec66ccba3a0582bee ha migliorato la gestione della problematica.
