### ISSUE TITLE
ERRORE - Impostazioni Generali

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#273]
Andando dentro a Impostazioni Generali filtra le anagrafiche per il campo 'deleted' che non esiste più
![image](https://user-images.githubusercontent.com/34273200/43122792-862eab36-8f22-11e8-8ef5-dfef9db612d8.png)

**Comment by lucasalva87** [comment]
Dovrebbe essere già risolto qui: 370d9f7

**Comment by fgambarelli** [comment]
Ho rilanciato a mano gli script update/2_4_1.sql per capire come mai non era stato eseguito. Ho individuato il blocco: alla riga 342, nell' INSERT INTO `zz_views` si blocca non avendo dichiarato il campo "format".

**Comment by lucasalva87** [comment]
Il campo format dovrebbe avere un valore predefinito che è 0 in quanto non si tratta nè di un id nè di un campo che deve essere obbligatoriamente definito.
Per risolvere esegui questa query: `ALTER TABLE `zz_views` CHANGE `format` `format` TINYINT(1) NOT NULL DEFAULT '0';`
