### ISSUE TITLE
FATTURA - Aggiunta contratto

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#276]
Quando si fattura un contratto il comportamento dovrebbe essere analogo alla fatturazione dei preventivi ed interventi, cioè che riportasse in fattura tutti gli elementi/righe/articoli presenti nel contratto, in quanto un contratto può contenere diversi e differenti articoli di servizi.
![image](https://user-images.githubusercontent.com/34273200/43125253-c71e8b96-8f29-11e8-9a3a-5e64a20d3c07.png)

**Comment by Dasc3er** [comment]
Risolto nelle versioni 2.4.* con la standardizzazione dei passaggi tra documenti.
