### ISSUE TITLE
ANAGRAFICA CLIENTE - MASTRINO Collegamento semplice dall'anagrafica e dallo scadenzario

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#277]
Non è di facile identificazione, specialmente se per errore si corregge il nome del Cliente, la ricerca e l'apertura del relativo Mastrino del cliente/fornitore. Sarebbe utile un plugin di apertura del Mastrino sia dall'anagrafica che dallo scadenziario, per avere la situazione del Cliente/Fornitore

**Comment by Dasc3er** [comment]
Ogni volta che si modifica la ragione sociale è necessario quindi aggiornare i conti collegati all'anagrafica.
Eventualmente considerare l'aggiunta del collegamento con l'anagrafica.

**Comment by Dasc3er** [comment]
Per il momento ho implementato un testo di base per l'informazione.

In **Anagrafiche**:
![immagine](https://user-images.githubusercontent.com/15911489/47167568-1c69f680-d2ff-11e8-80d9-c61ffa4c70a0.png)

In **Piano dei Conti**:
![immagine](https://user-images.githubusercontent.com/15911489/47167595-27bd2200-d2ff-11e8-9c72-b6f54117b156.png)

**Comment by Dasc3er** [comment]
@fgambarelli Questa soluzione completa la richiesta?

**Comment by fgambarelli** [comment]
E' un'ottima idea, sarebbe funzionale se il link collegasse direttamente al partitario indicato, mentre riporta solo al piano dei conti
