### ISSUE TITLE
Fatture ACQUISTO - Manca Data Fattura Fornitore

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#279]
Quando si registrano le fatture Acquisto, deve essere possibile inserire 4 campi:
Protocollo fattura fornitore  --> Numero Fornitore
Data fattura fornitore           --> ??
Protocollo registrazione       --> Numero fattura/protocollo
Data registrazione                --> Data emissione
Dove la progressione della data/numero protocollo va rispettato, mentre il numero e data della fattura va registrato per collegamento.
![image](https://user-images.githubusercontent.com/34273200/43126531-4096fcd0-8f2d-11e8-80e9-7ea403d8c1ad.png)

**Comment by lucasalva87** [comment]
In realtà la Data emissione è la "Data fattura fornitore". Ovvero quando il fornitore ha emesso la fattura.
Eventualmente si può prevedere un secondo campo non obbligatorio "Data registrazione".

**Comment by fgambarelli** [comment]
Scusa ma a livello fiscale è obbligatorio registrare la DATA DI RICEVIMENTO DELLA FATTURA, chiamata anche data registrazione.
La data di ricezione della fattura diviene quindi importante per individuare il mese a partire dal
quale poter detrarre l’IVA a credito.

**Comment by loviuz** [comment]
Campi presenti dalla 2.4.8, con l'aggiunta anche di "Data competenza" per futuro miglioramento con la stampa registro iva.
