### ISSUE TITLE
DDT auto-intestati per lavori in cantiere

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#28]
modulo DDT vendita, permettere l'auto-intestazione, è previsto dalla normativa vigente

Nel caso il materiale venga inviato ad un cantiere, il ddt va auto-intestato, ovvero nel campo "cliente" si può impostare l'azienda predefinita (è sufficiente aggiungere tipo anagrafica cliente) è necessario poi selezionare anche un cliente finale e l'eventuale sede del cliente finale. Aggiungere quindi un ulteriore idanagrafica sul database.

Nel campo "destinazione diversa" della stampa quindi possiamo avere:
1. l'indirizzo del cliente
2. l'indirizzo di una sede del cliente
2. l'indirizzo del cliente finale
3. l'indirizzo di una sede del cliente finale

- stampa da aggiornare di conseguenza
- aggiungere nuova "causale di trasporto": "installazione"

**Comment by loviuz** [comment]
Dalla 2.4.9 si può utilizzare come cliente la propria anagrafica se impostata come "Cliente", e come sede di partenza e destinazione proprie sedi per poter spostare materiale da un proprio magazzino ad un altro.
