### ISSUE TITLE
SCADENZARIO - Inserimento prima nota (MIGLIORIA)

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#281]
Quando si registra il pagamento dello fattura da scadenzario, 
![image](https://user-images.githubusercontent.com/34273200/43127440-c178d024-8f2f-11e8-800e-af60c3b7197a.png)

![image](https://user-images.githubusercontent.com/34273200/43127770-941cd4bc-8f30-11e8-913d-b8d19e5a0948.png)

1 - sarebbe utile, visto l'introduzione del modello, che con questo si potrebbe gestire le diverse tipologie di registrazione modificando la causale con "Pagamento tramite ASSEGNO della fattura di vendita n.x ....." oppure Pagamento tramite BONIFICO della fattura di vendita n.x...", mentre un modello ora è fisso.

2 - Al salvataggio si dovrebbe ritornare allo scadenziario, mentre si rimane in prima nota.

**Comment by Pek5892** [comment]
Personalizzazione dei modelli prima nota con variabili introdotta nelle release successive:
![immagine](https://user-images.githubusercontent.com/102604205/183458426-257933d7-8fb1-4e42-adf4-c07581f778ce.png)
