### ISSUE TITLE
Perdita campo "Calcola ritenuta d'acconto su" quando inserisco articolo in fattura

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#284]
## Comportamento richiesto

Il campo "Calcola ritenuta d'acconto su" deve essere salvato nel caso inserisco un' articolo in fattura.

## Comportamento attuale

Il campo "Calcola ritenuta d'acconto su" non viene salvato. 

## Passi per riprodurre il comportamento

1. Creare una fattura
2. Inserendo un articolo il valore di default "imponibile" e premere "aggiungi"
3. modificare l'articolo appena inserito. quando appare la maschera di inserimento dati il campo "Calcola ritenuta d'acconto su" non ha valori. Impostare il valore e confermare con "modifica". 
4. rieffettuare la modifica all'articolo appena modificato. Ora nella maschera appare il valore corretto.

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto: 2.4.1
* Versione PHP:
* Tipo di server:

**Comment by Dasc3er** [comment]
@lucasalva87 Il problema può essere considerato risolto?
