### ISSUE TITLE
SCADENZARIO - Gestione Solleciti (miglioria)

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#285]
Sarebbe utile poter spedire un'email direttamente dalla scadenza, con la gestione dei solleciti.
Per gestione dei solleciti si intende l'invio di email o fax o posta di lettere/comunicazione di segnalazione di mancato pagamento con la registrazione del numero di sollecito e della data.
Es. 
Segnalazione mancato pagamento - 1° Sollecito
"Con la presente segnaliamo il mancato saldo dei seguenti pagamenti, per un totale di ...
Vi invitiamo a regolamentare al più presto quanto sopra indicato"
Tenendo traccia che l'invio di tale sollecito è stato alla data x via email, e successivamente gli altri solleciti: 
Segnalazione mancato pagamento - 2° Sollecito.

**Comment by Dasc3er** [comment]
Riferimento #315 

>E' stato aggiunto il template email **Sollecito di pagamento** nelle email di base che permette proprio la funzionalità richiesta.
Inoltre per ora la gestione delle email è stata migliorata (versione in sviluppo 2.4.11) prevedendo l'introduzione di un hook apposito che viene richiamato automaticamente per l'invio delle email. Questo ha permesso l'introduzione del modulo sperimentale Newsletter.
