### ISSUE TITLE
Attività: restrizione sugli utenti che possono modificare gli orari

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#286]
## Comportamento attuale
creo un nuovo gruppo di utenti con i relativi utenti, imposto permessi lettura/scrittura sul modulo Attività, entro quindi su una attivitàe modifico gli orari di un tecnico, premo salva e compare il messaggio "Informazioni salvate correttamente". L'orario però non viene aggiornato per via di questo controllo:
https://github.com/devcode-it/openstamanager/blob/73e66a2786779afba004738ec66ccba3a0582bee/modules/interventi/actions.php#L76

vedi segnalazione sul forum
https://www.openstamanager.com/forum/viewtopic.php?f=4&t=91028

Limitazione esistente da parecchio tempo e poi riportata su questa nuova versione.

Secondo me la possiamo eliminare in quanto blocca il caso di un utente "segretaria" che cambia gli orari ai tecnici, se ci sono altri motivi per cui lasciarla, si potrebbe almeno segnalare all'utente che può modificare tutti i campi dell'attività, ma non gli orari dei tecnici.

Ancora meglio se ci fosse un'opzione per scegliere questo comportamento!

**Comment by Dasc3er** [comment]
Si potrebbe semplicemente modificare il controllo sul gruppo "Amministratori" in "diverso da Tecnico".

**Comment by fpsoftware** [comment]
@Dasc3er quindi il controllo diventa "uguale a Tecnici" oppure "diverso da Tecnici" .... praticamente tutti... a questo punto togliamo il controllo

**Comment by Dasc3er** [comment]
Con il commit ba186cd il controllo è stato messo a commento (versione 2.4.2), così da poterlo eventualmente ripristinare secondo necessità.

**Comment by loviuz** [comment]
La modifica sarebbe impostare un "if" che fa modificare gli orari dei tecnici:
- se il gruppo di appartenenza è "Tecnici" e la sessione è mia

oppure
- se il gruppo di appartenenza è diverso da "Tecnici"

**Comment by loviuz** [comment]
Il funzionamento attuale è già stato corretto e mi sembra funzioni in modo corretto.
