### ISSUE TITLE
Abilitare orario lavorativo

### ISSUE THREAD

**Issue by lexen77** [devcode-it/openstamanager#287]
Salve,
credo che sarebbe utile, 
quando si abilita l'orario lavorativo per il calendario della Dashboard,
indicare la fascia oraria tramite un campo preposto nella schermata delle impostazioni.
Attualmentè mi sembra di capire che è possibile farlo solo tramite codice.
#272

**Comment by Dasc3er** [comment]
Con il commit f12103192bb9621c8575e509314dcdf90d3e5777 l'impostazione precedente *Abilitare orario lavorativo* è stata rimossa in favore di *Inizio orario lavorativo* e *Fine orario lavorativo*.
