### ISSUE TITLE
Attività: cambio stato automatico se collegata ad una fattura

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#288]
## Comportamento richiesto
lo stato di una attività cambia in automatico in "Fatturato" se questa viene collegata ad una fattura
vedi segnalazione sul forum:
https://www.openstamanager.com/forum/viewtopic.php?f=4&t=91068

**Comment by Dasc3er** [comment]
Nella versione 2.4.1 in sviluppo il cambio dello stato funziona correttamente...
