### ISSUE TITLE
FATTURAZIONE Dicitura errata Rivalsa INPS 4%

### ISSUE THREAD

**Issue by mmagnani70** [devcode-it/openstamanager#289]
In caso di Fatture con Rivalsa INPS in calce alla fattura [documento pdf] l'intestazione della casella di riepilogo della RIVALSA INPS dovrebbe riportare la dicitura "Rivalsa INPS 4 %".

In realtà l'intestazione riportata in fattura è "Rivalsa INPS 0 %"

Il comportamento è riproducibile richiedendo la stampa di una fattura, previa selezione in Impostazioni, Fatturazione, Percentuale di rivalsa INPS della Rivalsa INPS 4 %.

Stante che l'aliquota della rivalsa INPS è una sola e da una verifica sulla tabella "co_rivalsainps" i campi sembrano correttamente compilati sono intervenuto sul codice sostituendo le seguenti righe del file
/var/www/openstamanager/templates/fatture/footer.php :

```

echo '

   <tr>
       <th class="text-center small" colspan="'.$first_colspan.'">
          '.tr('Rivalsa INPS _PRC_ %', [
            '_PRC_' => Translator::numberToLocale($rs2[0]['percentuale'], 0),
          ], ['upper' => true]).'
      </th>';
```

con le seguenti:     

```
 echo '
    <tr>
        <th class="text-center small" colspan="'.$first_colspan.'">
            '.tr('Rivalsa INPS 4 %',  ['upper' => true]).'
        </th>';


```

Contesto

* Modulo:  fatture
* Versione del progetto: 2.4 (Rc795995)
* Versione PHP:
* Tipo di server: ubuntu 16.04

**Comment by Dasc3er** [comment]
Ciao @mmagnani70,
grazie per la segnalazione!

@devcode-it/openstamanager Il problema è generato dal fatto che la percentuale è impostata a 0 a livello di database.
