### ISSUE TITLE
Rivalsa INPS/Ritenuta d'acconto

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#29]
Come segnalato nel post del forum relativo (https://www.openstamanager.com/forum/viewtopic.php?f=4&t=88303), vorrei controllare il funzionamento corretto per i campo di Rivalsa INPS e Ritenuta d'acconto...

Ho controllato il codice, e attualmente i due campi compaiono come **obbligatori**:

- Sempre per le fatture di acquisto
- Per le fatture di vendita, se sono stati impostati dal modulo Impostazioni

@fpsoftware @lucasalva87 Questo comportamento è corretto?

Oppure sarebbe più corretto che comparissero nel seguente modo:
- Obbligatori per le fatture di vendita, se sono stati impostati dal modulo Impostazioni
- Sempre facoltativi per le fatture di acquisto

**Comment by lucasalva87** [comment]
Ciao Thomas, esatto. Per le fatture di acquisto sarebbe ancora meglio se fossero obbligatori e popolati automaticamente quando definiti nella scheda anagrafica del fornitore (prevedere queste due nuovi campi per le anagrafiche di tipo fornitore).
