### ISSUE TITLE
FATTURE DI VENDITA - Errore somme con righe con importi negativi

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#290]
Nella Fattura deve essere possibile mettere valori negativi e visibili i sia a video che in stampa, mentre ora viene calcolato in il Valore assoluto e riporta degli errori nei totali. 
Es: se inserisco una descrizione di sconto generica non legata a nessun articolo, questa deve essere con segno negativo visibile sia a video che in fattura. 
A video il totale della fattura è corretto (cioè viene sottratto la riga essendo in negativo) mentre in stampa viene sommata.

**Comment by lucasalva87** [comment]
Per il calcolo stiamo risolvendo in questi giorni. 

Per quanto riguarda il sengo in fattura nessuna norma vigente regola la modalità di esposizione di un importo in nota di credito come numero in valore relativo o assoluto.
Da un punto di vista puramente tecnico lo schema fatturaPA permette di distinguere vari tipi di documento sulla base del valore assunto dall’elemento informativo <TipoDocumento>, pertanto si può evitare di ricorrere all’esposizione di un importo in termini relativi.

**Comment by Dasc3er** [comment]
Chiuso per inattività.
