### ISSUE TITLE
Modulo Viste: problema con campo _print_ del modulo Attività

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#291]
sul modulo Attività è presente una colonna con un pulsante per la stampa dell'attività, per ottenere questa "colonna con pulsante" viene creato un record su `zz_views` con 
name = "_print_" 
query = ''pdfgen.php?ptype=interventi&idintervento=**$id$**&mode=single''

Se entro in Viste e modifico/aggiungo una colonna del modulo Attività, la stringa query qui sopra viene sovrascritta in : 
query = ''pdfgen.php?ptype=interventi&idintervento=**3**&mode=single''

questo perché la stringa $id$ viene sostituita dall'id del record aperto quando viene generata la textarea.... sì però il numero 3 in questa fase è id del modulo Attività.... non serve fare questo replace, io lascerei $id$ , oppure scegliamo un'altra stringa, tipo $idintervento$

L'effetto è, che dopo aver fatto una qualsiasi modifica al modulo Attività tramite il modulo viste, il tasto per la stampa non funziona più, o meglio manda sempre in stampa l'attività con idintervento=3

**Comment by Dasc3er** [comment]
Il commit c68b35cd6bd0751a5c8a015d544bdc8c5eb2a48b risolve il problema modificando il comportamento della colonna stampe.
Viene ora utilizzata la classe **Prints** per individuare l'URL corretto, e il campo **_print_** deve contenere al proprio interno il nome o l'id della stampa da considerare.

Per esempio, negli **Interventi**:
```ini
name = "_print_"
query = "'Intervento'"
```
