### ISSUE TITLE
testSMTP usare procedura ufficiale

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#292]
https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp_check.phps

**Comment by Dasc3er** [comment]
@lucasalva87 Il codice della funzione **smtpConnect** fa esattamente la stessa cosa.

https://github.com/PHPMailer/PHPMailer/blob/59495db0b14c17f5a370359df0ad7b2e004391a2/src/PHPMailer.php#L1841

**Comment by lucasalva87** [comment]
Allora va rivista la procedura in quanto se i dati di accesso non sono corretti smtpConnect testando continuamente la connessione fa andare in timeout la pagina. Provare eventualmente ad introdurre $mail->Timeout = 30; ?

**Comment by Dasc3er** [comment]
Dal codice, sembra che il timeout di default sia di 5 minuti a causa di uno standard...
```php
/**
     * The SMTP server timeout in seconds.
     * Default of 5 minutes (300sec) is from RFC2821 section 4.5.3.2.
     *
     * @var int
     */
    public $Timeout = 300;
```

Eventualmente si potrebbe provare proprio questa modifica, oppure vedere il controllo come separato e farlo fare all'utente con un pulsante apposito.

**Comment by lucasalva87** [comment]
Avevo pensato anch'io al pulsante separato. Però se con il timeout impostato risolviamo non ce ne sarà bisogno. :wink:
