### ISSUE TITLE
Area clienti per documenti PDF

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#294]
Possibilità per i clienti, previa attivazione da parte del superuser, di visualizzare direttamente nel server i propri documenti solo in formato PDF.

**Comment by idraulicadueci** [comment]
Potrebbe essere un'idea aggiungere all'elenco permessi "Visualizza documento PDF", poiché nei moduli vi sono troppe informazioni riservate (per es. prezzi di acquisto) che il cliente non dovrebbe poter visionare.

**Comment by Dasc3er** [comment]
@idraulicadueci Considerando che la funzione non è stata richiesta in modo considerevole, e che la gestione della relativa grafica con permessi sarebbe piuttosto complessa per il caso generale, ti consiglio di considerare una personalizzazione (personale o comprata) per l'implementazione della funzionalità di interesse.
Potrebbe inoltre tornare utile separare questa Area clienti dal gestionale effettivo, in modo da permettere una maggiore libertà nello sviluppo e nel mantenimento del codice.
