### ISSUE TITLE
Stampa per le anagrafiche

### ISSUE THREAD

**Issue by lexen77** [devcode-it/openstamanager#296]
Salve a tutti,
sarebbe interessante  aggungere un pulsante per stampare
la scheda dell' anagrafica clienti o fornitori

**Comment by Dasc3er** [comment]
@lexen77 Si tratterebbe di creare una stampa per il modulo **Anagrafiche**.

**Comment by Dasc3er** [comment]
@lexen77 Per quali utilizzi potrebbe essere utile permettere una stampa del genere?
Dovrebbe contenere sole informazioni anagrafiche (sedi, referenti, ...) o sarebbe utile avere altre informazioni generali?
