### ISSUE TITLE
Flag "main" su stampe non permette l'esportazione fatture

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#299]
Ho rilevato che il flag "main" non è correttamente impostato su zz_prints per alcune stampe. Le stampe funzionano lo stesso, però l'esportazione fatture in zip non funziona perché non trova la stampa di default. Rilevato in OSM 2.4.1

**Comment by Dasc3er** [comment]
Nel caso non sia presente nessuna stampa impostata come predefinita, viene utilizzata la prima disponibile.
Commit 411662f7c54ca7641ba41ee0fcbef441349a5f7c.
