### ISSUE TITLE
Problema salvataggio scadenze su scadenzario

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#3]
Creata fattura di acquisto da 103,70 euro con 2 scadenze (tipo pagamento: bonifico 30/60 gg d.f). Vado sullo scadenziario e cerco di inserire il pagamento della prima rata. Inserisco l'importo e salvo. Non salva dicendomi "Il totale degli importi inseriti non corrisponde al totale da pagare!", stesso problema anche con 1 sola scadenza. Su fatture di vendita non accade.

**Comment by Dasc3er** [comment]
Apparentemente, il problema è relativo al fatto che per le fatture di acquisto il valore salvato nel campo _da_pagare_ nella tabella **co_scadenziario** è negativo...

@loviuz E' corretto questo comportamento?
Se si, basterebbe un controllo sul valore assoluto del totale da pagare.

Un'altra cosa: all'interno del file **actions.php** del modulo Prima Nota viene aggiunto al totale da pagare il valore presente in _$dare_ sia nel caso questo sia assegnato che quando viene utilizzata la variabile _$avere_. Questo comportamento è corretto?
```
if ($dare != '' && $dare != 0) {
    $totale = $dare;
    $totale_pagato += $dare;
} elseif ($avere != '' && $avere != 0) {
    $totale = -$avere;
    $totale_pagato -= $dare;
} 
```

**Comment by loviuz** [comment]
> Apparentemente, il problema è relativo al fatto che per le fatture di acquisto il valore salvato nel campo da_pagare nella tabella co_scadenziario è negativo...

Sì, è corretto

> Un'altra cosa: all'interno del file actions.php del modulo Prima Nota viene aggiunto al totale da pagare il valore presente in $dare sia nel caso questo sia assegnato che quando viene utilizzata la variabile $avere. Questo comportamento è corretto?

Devo verificare

**Comment by Dasc3er** [comment]
@loviuz Dovrei aver risolto il primo problema, che era relativo all'inizializzazione di [InputMask con valori negativi con la nuova configurazione](https://github.com/RobinHerbots/Inputmask/issues/1500)...
In attesa di chiarimenti per il secondo comportamento.

**Comment by loviuz** [comment]
> Un'altra cosa: all'interno del file actions.php del modulo Prima Nota viene aggiunto al totale da pagare il valore presente in $dare sia nel caso questo sia assegnato che quando viene utilizzata la variabile $avere. Questo comportamento è corretto?

ho verificato nelle precedenti versioni, ed è così. per il fatto che la prima nota deve avere il totale di dare e avere uguali, ovviamente il $totale_pagato torna, però concettualmente è sbagliato :-)
meglio cambiarlo così:
```
if ($dare != '' && $dare != 0) {
    $totale = $dare;
    $totale_pagato += $dare;
} elseif ($avere != '' && $avere != 0) {
    $totale = -$avere;
    $totale_pagato -= $avere;
}
 ```

Una cosa che ho visto non funzionare invece è che, se emetto una fattura e poi creo la prima nota, che serve per segnare l'incasso della fattura, la trovo ancora nello scadenzario perché non si aggiorna il campo "pagato" su co_scadenzario.
Nella data di scadenza dello scadenzario poi c'è ancora il formato DATETIME, per cui vedo ad esempio
`01/09/2017 00:00`

**Comment by Dasc3er** [comment]
Riguardo le date nel database, all'interno di **co_scadenziario** sono presenti tre attributi impostati a DATETIME: _data_emissione_, _scadenza_, _data_pagamento_.
Sarebbero da convertire tutti e tre?

**Comment by loviuz** [comment]
yesss. basta solo la data, non l'ora. se li converti nel file di update, possiamo chiudere anche questa segnalazione

**Comment by Dasc3er** [comment]
Li ho inseriti anche nella segnalazione #19, quindi lavoriamo su quella per i DATETIME.

@loviuz Servirebbe anche un controllo sulla risoluzione di questo bug, per sicurezza...
