### ISSUE TITLE
Backup parametrico

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#300]
Specificare nella creazione backup, con delle checkbox, se eseguire il backup di:
- solo DB
- programma (codice)
- allegati (cartella /files)
- backup completo (eventualmente tutte le spunte sopra)

Che ne pensate?

**Comment by Dasc3er** [comment]
@loviuz Per quale motivo potrebbe essere utile avere dei backup parziali di questo tipo?
A livello pratico, in particolare per gli allegati, molte funzioni sono una combinazione di database e file effettivi, quindi fare il backup di una singola componente sarebbe praticamente inutile...

**Comment by loviuz** [comment]
**🎯 BOUNTY!**
Questo issue fa parte del [Bounty Program](https://github.com/devcode-it/openstamanager/blob/master/README.md#bounty-program), per cui riceverai una ricompensa se lo risolverai seguendo i requisiti descritti di seguito.

Al termine dovrai eseguire una pull request e segnalare la risoluzione da qui:
https://app.bountysource.com/issues/63376059-backup-parametrico

REQUISITI:
1. aggiungere al backup il numero di versione nel nome del file per poi visualizzarlo anche nella lista backup del modulo Backup:
![immagine](https://user-images.githubusercontent.com/1647128/229184263-a0a57d90-597d-4466-ad7d-77654e4facf9.png)

2. nella visualizzazione del backup in lista aggiungere anche la tipologia di backup eseguito, aggiungendo eventualmente un'indicazione nel nome del file per distinguerne la tipologia:
![immagine](https://user-images.githubusercontent.com/1647128/229184791-ce4e6c60-6dd4-4e2f-9030-e8f3a8265273.png)

3. nel pulsante di creazione backup inserire la possibilità di creare un backup completo o solo del database. In entrambi i casi il ripristino backup deve funzionare:
![immagine](https://user-images.githubusercontent.com/1647128/229184584-8116d05f-6ef0-44d5-b71e-3db077bcbe83.png)

**Comment by Pek5892** [comment]
Introdotto nella versione 2.5 beta
