### ISSUE TITLE
Funzione di aggiornamento automatico

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#302]
## Comportamento richiesto

Inserire un pulsante "CERCA AGGIORNAMENTI" che consenta di implementare le nuove funzioni testate con successo. Non so se è possibile, ma sarebbe utile.

* Versione del progetto: OSM 2.5

**Comment by Dasc3er** [comment]
Funzione completata con il commit f37a47df71c58d0320a365993ae56e73aea9c72a.

Nel modulo **Aggiornamenti** sarà disponibile già a partire dalla versione 2.4.2 una nuova sezione per la ricerca degli aggiornamenti:
![screenshot_2018-11-03 aggiornamenti - openstamanager](https://user-images.githubusercontent.com/15911489/47951367-fcbe0980-df5f-11e8-8523-a7048cb3fea8.png)

![screenshot_2018-11-03 aggiornamenti - openstamanager 1](https://user-images.githubusercontent.com/15911489/47951365-fc257300-df5f-11e8-9a63-6bf2f4e9f324.png)

![screenshot_2018-11-03 aggiornamenti - openstamanager 3](https://user-images.githubusercontent.com/15911489/47951390-4eff2a80-df60-11e8-900c-e5ef14ea9fd5.png)

------

Con la 2.5 sarà possibile procedere in automatico al download dell'aggiornamento e all'installazione come definito in #343:
![screenshot_2018-11-03 aggiornamenti - openstamanager 2](https://user-images.githubusercontent.com/15911489/47951366-fcbe0980-df5f-11e8-8a19-2a25a489b6f3.png)
