### ISSUE TITLE
problemi gui

### ISSUE THREAD

**Issue by s0und0ut** [devcode-it/openstamanager#303]
aggiornamento versione 2.3.1 a 2.4.1 genera seguenti problemi:

primo problema: se la barra di sinistra è stata impostata su nascondi prima dell'aggiornamento non viene visualizzata cliccando sull'apposito tasto. Se nei settings si disabilita il "Nascondere la barra sinistra di default" cliccando sul tasto la barra non si nasconde

secondo problema: 
barra su fatture o s interventi
![barra](https://user-images.githubusercontent.com/36164956/45677796-6069b000-bb35-11e8-938e-16f47edfe2f3.JPG)

scorre lungo la pagina ma viene coperta dalle altre maschere
![barra2](https://user-images.githubusercontent.com/36164956/45677922-a3c41e80-bb35-11e8-9017-84af0005190c.JPG)

il problema sembra che si presenti anche su un'installazione pulita

## Contesto
* Browser: Chrome
* Versione del progetto: 2.4.1
* Versione PHP: sia 5 che 7
* Tipo di server: wamp

**Comment by Dasc3er** [comment]
@s0und0ut Credo che tu stia avendo dei problemi di cache...

Potresti provare ad aprire OpenSTAManager usando un altro browser, oppure ricaricare con `Ctrl+F5`?

**Comment by s0und0ut** [comment]
@Dasc3er e credo che tu abbia proprio ragione! XD 

Errore banale e mio...chiedo scusa. cancello la issues
