### ISSUE TITLE
Ripristino serial number dopo reso materiale

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#304]
Attualmente se un cliente effettua un reso materiale, il serial number dell'articolo non viene ripristinato nel magazzino. Sarebbe utile prevedere un flag nelle causali "CONSIDERA RESO" per fare in modo che un DDT con causale reso o simile faccia reintegrare il serial number nel magazzino oltre, ovviamente, alla quantità. Questo è utile anche quando si tratta di apparecchiature che vengono portate in laboratorio per la riparazione e successivamente rese al cliente una volta riparate. A tal proposito si potrebbe anche prevedere nella riga articoli del DDT un campo "MATRICOLA/SERIAL NUMBER" per articoli non precedentemente presenti in magazzino.

**Comment by Dasc3er** [comment]
@idraulicadueci Questa funzione non è compatibile nativamente con il sistema di seriali da noi implementato, e non verrà implementata.
L'unico modo per rendere disponibili i seriali una volta utilizzati un un documento di vendita è rimuoverli da quel documento a mano.
