### ISSUE TITLE
BUG: Visualizzazione non corretta della finestra indirizzo nel template ordine

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#307]
La finestra dell'indirizzo rimane nascosta sotto alle righe articoli
![image](https://user-images.githubusercontent.com/40104356/46195149-c4456300-c303-11e8-9b15-9b1dd0d80af7.jpg)

**Comment by Dasc3er** [comment]
@idraulicadueci Per favore, controlla il commit https://github.com/devcode-it/openstamanager/commit/0458ce920298fab54c6a0ae453641e9d7be16355-
