### ISSUE TITLE
Tabella con righe dinamiche fatture/preventivi/...

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#308]
Ciao a tutti,
Il processo di aggiunta di varie righe ad una fattura o ad un preventivo può risultare molto lungo e stancante se ci sono molti elementi da inserire. Sarebbe un'idea per le future versioni rendere la tabella dinamica con dei campi modificabili all'interno. [Esempio](https://datatables.net/examples/api/form.html) 
Grazie

**Comment by Dasc3er** [comment]
Ciao @maicol07,
grazie per il suggerimento ma non abbiamo al momento la possibilità di introdurre un cambiamento così consistente e integrarlo con la grafica predefinita del gestionale.

In realtà, il sistema simile a quello da te proposto è attualmente in utilizzo negli **Interventi** (Attività) per la gestione delle sessioni di lavoro, ed è prevista la rimozione e sostituzione con _modal_ per maggiore consistenza e semplificazione grafica. #241

**Comment by maicol07** [comment]
@Dasc3er magari si potrebbe effettuare un controllo del dispositivo e, se è un dispositivo mobile, mantenere la classica gestione a finestre, mentre con i computer desktop o portatili (magari anche tablet) si potrebbe implementare il sistema che è attualmente in uso per gli interventi.

**Comment by Dasc3er** [comment]
Il problema è che duplicare questa funzione renderebbe molto più complessa sia la gestione della componente grafica che del _back-end_, e renderebbe la manutenzione insostenibile.

**Comment by maicol07** [comment]
Non so se ne siete già a conoscenza, Datatables ha rilasciato un suo "plugin" denominato Editor (link: https://editor.datatables.net/) che però è a pagamento (con un periodo di prova gratuita), ma permette di modificare le righe della tabella, anche se con popup modali.

**Comment by Dasc3er** [comment]
@maicol07 Purtroppo, la base del gestionale è costruita per essere gratuita e open source, e quindi non possiamo implementare soluzioni simili a pagamento.
Se fosse disponibile qualche altro sistema, e fosse richiesto da qualcuno, si tratterebbe comunque di una personalizzazione.
