### ISSUE TITLE
Piccolo problema statistiche

### ISSUE THREAD

**Issue by ldanese83** [devcode-it/openstamanager#31]
Ciao, ho un dubbio sul modulo statistiche: la colonna del primo grafico Fatturato non dovrebbe mostrare le fatture di vendita? Mi sembra che al momento mostri invece gli acquisti..

**Comment by Dasc3er** [comment]
@ldanese83 Grazie mille per la segnalazione!
In effetti avevo erroneamente impostato il flusso di denaro in "uscita", mentre come hai fatto notare si tratta di un "entrata".
