### ISSUE TITLE
Magazzino: Stampa inventario

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#313]
## Comportamento attuale
il valore degli articoli che rimangono a magazzino, riportato nella stampa inventario, è calcolato sul prezzo di acquisto indicato nella scheda articolo.

## Comportamento richiesto
il realtà il valore dovrebbe essere calcolato sulla media ponderata del costo di acquisto, che si può recuperare dalle fatture di acquisto, oppure con i metodi: LIFO, FIFO.

vedi link per maggiori dettagli: https://it.wikiversity.org/wiki/Giacenze_di_magazzino

Questa miglioria farebbe parte del calcolo del bilancio, da valutare se ha senso implementarla

**Comment by Pek5892** [comment]
Introdotto nella v. 2.4.27
