### ISSUE TITLE
Bug ripristino backup

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#314]
Il ripristino del backup tramite l'apposito form funziona solamente se all'interno del file zip è presente un datbase.sql o una singola cartella. In caso di più cartelle contenute nello zip il ripristio non viene eseguito.

Inoltre non viene mai visualizzato un messaggio che avvisi del completamento o del mancato ripristino.

![backup openstamanager 4](https://user-images.githubusercontent.com/30728163/46343801-4b197900-c63f-11e8-9d35-4c2722eb39ac.png)

![immagine](https://user-images.githubusercontent.com/30728163/46343980-e3176280-c63f-11e8-8455-8914db0335df.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Ho appena testato e il funzionamento sembra corretto.
I file vengono ripristinati anche senza il **database.sql**.

**Comment by lucasalva87** [comment]
@Dasc3er che versione di php stai utilizzando?

**Comment by Dasc3er** [comment]
Ho completato con la 5.6, comunque in questo caso non dovrebbero esserci differenze perché per l'estrazione viene usata la stessa procedura degli aggiornamenti.
Ho cancellato due cartelle dalla root, ripristinato con un bacup caricato con il form e sono ricomparse anche senza il **database.sql** dentro lo zip.

**Comment by lucasalva87** [comment]
Ho fatto ulteriori prove e credo che dipenda dalla dimensione del file. Sotto i 8MB sembra ripristinare tutto correttamente. Credo dipenda da alcune configurazioni nel file php.ini come  post_max_size e upload_max_filesize

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere stato risolto con la rimozione delle direttive PHP dal file *.htaccess*.
