### ISSUE TITLE
Problemi di sicurezza

### ISSUE THREAD

**Issue by cippaciong** [devcode-it/openstamanager#318]
Ciao a tutti, a chi posso segnalare (privatamente) dei problemi di sicurezza che ho riscontrato?

**Comment by Dasc3er** [comment]
Per segnalare problemi di sicurezza scrivi una mail a info@openstamanager.com.
Grazie per il contributo ;-)

**Comment by cippaciong** [comment]
Grazie, ho visto solo ora che c'era scritto anche nella guida tecnica. Cerco di scrivervi il prima possibile.
