### ISSUE TITLE
Esportazione massiva stampe Interventi

### ISSUE THREAD

**Issue by s0und0ut** [devcode-it/openstamanager#319]
## Comportamento richiesto

Azione di gruppo su Interventi per esportare n. interventi senza la specifica dei costi, come già presente entrando nel singolo intervento.

* Modulo: Interventi
* Versione del progetto: 2.4.1
* Versione PHP: 7
* Tipo di server: Wamp e Web

**Comment by Dasc3er** [comment]
Funzione completata tempo fa.
