### ISSUE TITLE
Suggerimenti

### ISSUE THREAD

**Issue by cent89** [devcode-it/openstamanager#32]
Ciao, sto provando la beta2 della 2.3, qualche primo suggerimento:
- C'è ancora qualche problema con gli sconti/rincari: Se nel listino metto una percentuale negativa (= rincaro, anche se secondo me per logica è uno sconto...), nella pagina dell'articolo il prezzo, nella sezione listini, il prezzo è mostrato rincarato della percentuale giusta, mentre nel preventivo viene applicato uno sconto, quindi l'opposto. 
- Mi sembra giusto mostrare nel preventivo gli sconti applicati ai singoli articoli, ma non i rincari. Non ha senso dire al cliente "Guarda che questo articolo costa 10€ ma per te lo rincaro del 20%";
- Nella beta precedente avevo fatto una modifica veloce ai preventivi, cioè in corrispondenza di ogni articolo avevo aggiunto anche l'immagine dell'articolo, per completezza. Sarebbe possibile aggiungere tale modifica nella versione finale?

Grazie
Roberto

**Comment by Dasc3er** [comment]
Ciao @cent89 ,
grazie mille per i tuoi suggerimenti!

Riguardo il calcolo costi nel modulo **Articoli**, in effetti c'è un'incongruenza rispetto alla gestione delle stesse operazione nel resto del gestionale. In generale, per una mancata previsione iniziale, sconti e rincari sono gestiti in modo opposto alla logica comune: nei campi relativi, **un valore positivo indica uno sconto mentre uno negativo un rincaro**.
Questa incongruenza logica potrebbe essere una delle problematiche da risolvere per le prossime release :D.
Nel frattempo, ho unificato la gestione in **Articoli** con il comportamento generale.

Riguardo gli altri due suggerimenti, sono operazioni piuttosto semplici da inserire in release, e quindi chiedo il parere degli altri sviluppatori.
Comunque, nel caso non venissero incluse, puoi sempre fare richiesta di una personalizzazione.

@loviuz @lucasalva87 @fpsoftware

**Comment by loviuz** [comment]
ok per la modifica, così è più uniforme la logica dello sconto e del rincaro.
dovrei fare alcuni test per verificare se ovunque viene gestito correttamente questo nuovo valore.
