### ISSUE TITLE
Aggiungere la funzione Duplica Preventivo (Simile a quella per la duplicazione delle fatture)

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#322]

**Comment by maicol07** [comment]
Nella mia installazione il numero del preventivo non aumenta, è normale?

**Comment by lucasalva87** [comment]
v. 2.4.4 o 2.4.5? Dovrebbe calcolare il numero successivo. Ci hanno già segnalato il problema con numeri >100 se nella maschera della numerazione del preventivo è stato specificato un solo cancelletto #

**Comment by maicol07** [comment]
@lucasalva87 2.4.5
Come numerazione ho un solo #.
Per esempio, duplica il preventivo n. 2 e come numero del nuovo preventivo è il n. 1

_Inviato dal mio ZenFone 3 (ZE520KL) usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Dasc3er** [comment]
Completato in passato e con aaf6153a.
