### ISSUE TITLE
SCADENZARIO - Errore importo pagato

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#324]
Pagando con l'importo suggerito, in scadenzario rimangono le voci.
![image](https://user-images.githubusercontent.com/34273200/46803479-721f2b80-cd60-11e8-859b-e26d1dcda99e.png)
Verificando da DB si vede che pagato è arrotondato
![image](https://user-images.githubusercontent.com/34273200/46803596-c4604c80-cd60-11e8-9657-7474339874f2.png)
Non solo, se si torna dentro alla scadenza, la procedura ha generato una seconda rata:
![image](https://user-images.githubusercontent.com/34273200/46803738-186b3100-cd61-11e8-824c-2ee576a3f449.png)
Con importo da pagare uguale al precedente e su db si vede invece 
![image](https://user-images.githubusercontent.com/34273200/46803839-55372800-cd61-11e8-9dc4-f4564aa96054.png)

**Comment by lucasalva87** [comment]
Ho fatto diverse prove sia in fatture di acquisto che di vendita con la 2.4.2 ma non sono riuscito a replicare il problema. Nello specifico non so come si è riusciti a valorazzare a -0.0037 il pagato 

![scadenzario openstamanager 3](https://user-images.githubusercontent.com/30728163/46805387-3470d180-cd65-11e8-80a2-fb4e04e27c5c.png)

**Comment by fgambarelli** [comment]
Purtroppo nello specifico dei 0,0037 non so, perchè hanno provato in diversi modi a chiudere le scadenze rimaste aperte, che sono tantissime.
