### ISSUE TITLE
EMAIL - Campi automatici importo

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#326]
Gli importi sono a 4 cifre, occorre correggerli ad ogni email.
![image](https://user-images.githubusercontent.com/34273200/46809588-0f815c00-cd6f-11e8-80e4-efb376460fd3.png)

**Comment by Dasc3er** [comment]
Mi correggo: il campo importo non è previsto di default nei template email attuali.
Il problema è causato dal mancato utilizzo delle funzioni di arrotondamento `Translator::numberToLocale()`.
