### ISSUE TITLE
Errore codice articolo, valori che iniziano con numeri vengono alterati 

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#328]
## Comportamento richiesto
Codice articolo deve essere salvato come immesso.

## Comportamento attuale
Ad esempio il codice 8005543486122 viene convertito in 8.00554348612E12

Versione OSM 2.4.1

**Comment by lepool** [comment]
in actions.php del modulo articoli se inserisco :
         ...
        $dbo->update('mg_articoli', [
            'codice'_ => post('codice', $raw=true),
         ...
con $raw=true posso avere problemi di sicurezza?

**Comment by Dasc3er** [comment]
Ciao @lepool,
Il parametro $raw permettere di prendere i valori dell'input senza la formattazione di date e numeri, quindi non si dovrebbero verificare problemi do sicurezza.
Non è però detto che risolva il problema, poiché potrebbe essere causato da PHP in generale...
L'unico modo è provare.

PS: basta mettere *post('codice', true)*.

**Comment by lepool** [comment]
Infatti con post senza raw mi vengono convertiti numeri anche se tag = testo

**Comment by lucasalva87** [comment]
Credo possa dipendere anche dall'**estensione** PHP **intl**.
Riporto qui sotto un esempio di salvataggio codice fiscale **senza** l'estensione attiva:
![anagrafiche openstamanager 29](https://user-images.githubusercontent.com/30728163/46945654-a1da7600-d075-11e8-96e5-2359ba311cdb.png)

e **con** l'estensione attiva:
![anagrafiche openstamanager 30](https://user-images.githubusercontent.com/30728163/46945666-abfc7480-d075-11e8-9d8b-b633ce7499e7.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Potresti fare alcuni controlli che gli importi normali siano convertiti correttamente?

**Comment by lucasalva87** [comment]
Con intl **non** attiva sì. Con intl attiva si verifica quanto segue:
Provando a salavare ad esempio 10.000,00 si ottiene 10,00
![fatture di vendita openstamanager 27](https://user-images.githubusercontent.com/30728163/46952207-7f068c80-d08a-11e8-87de-617c11f6163e.png)

**Comment by Dasc3er** [comment]
Con il commit b9365cd il problema dovrebbe essere stato risolto completamente.
La correzione ha modificato il comportamento previsto dal fix di #30, ma da alcuni test rapidi sembra ora funzionare tutto correttamente.

@lucasalva87 Se puoi confermare che il problema originale è risolto, come quello degli importi, e che altri campi numerici (CAP, ...) non vengono troncati.

**Comment by Dasc3er** [comment]
@lepool Si verificavano però dei problemi sugli altri numeri, come quantità e prezzi...

**Comment by lucasalva87** [comment]
@Dasc3er ok per codice fiscale cap ecc... però con le righe nei documenti questo probelma persiste.

Provando a salavare ad esempio 10.000,00 si ottiene 10,00
> lavare ad esempio 10.000,00 si ottiene 10,00
> ![fatture di vendita openstamanager 27](https://user-images.githubusercontent.com/30728163/46952207-7f068c80-d08a-11e8-87de-617c11f6163e.png)

**Comment by lepool** [comment]
Io ho provato ad inserire una spesa aggiuntiva ed un articolo ad un intervento ed il problema non me lo ha fatto. Sto usando la versione OSM 2.4.1

**Comment by lucasalva87** [comment]
OSM 2.4.2 (3441705)
php 7.2.9
apache 2.4.18
intl ATTIVO

Il prblema sembra essere stato risolto.
