### ISSUE TITLE
Suggerimenti nelle funzionalità in "Azioni di gruppo" - Anagrafica

### ISSUE THREAD

**Issue by gabrielepiccinnu** [devcode-it/openstamanager#33]
Ho importato con MySQL, dopo vari adattamenti con Excel, l'anagrafica proveniente da un precedente gestionale. Non ho capito come funziona l'attribuzione della caratteristica (Cliente, Azienda, Fornitore, etc..) nelle tabelle in database. Sarebbe fantastico procedere con delle modifiche "rapide" di gruppo, con la possibilità di attribuire ad n anagrafiche la caratteristica/ruolo esatta.

Sto sperimentando tra l'altro la possibilità di sincronizzare il Database con uno Foglio Google+Script con l'utilizzo di JDBC (un pò troppo limitato su Google)

**Comment by Dasc3er** [comment]
@gabrielepiccinnu La gestione delle tipologia di anagrafiche viene gestita attraverso la tabella di collegamento **an_tipianagrafiche_anagrafiche**, che mette in relazione **an_anagrafiche** e **an_tipianagrafiche**.
Per maggior dettagli puoi analizzare la struttura di questa tabella :D.

Riguardo il tuo suggerimento sulle azioni di gruppo, sarebbe un ampliamento piuttosto consistente perchè bisognerebbe creare un elemento nel menu per ogni tipologia di anagrafica che si vuole impostare in modo generico.
@lucasalva87 @fpsoftware @loviuz Che ne dite riguardo l'aggiunta di queste opzioni?

**Comment by loviuz** [comment]
non ci avevo mai pensato. potrebbe essere utile, però finora non ce l'ha mai chiesto nessuno, mi sembra una richiesta piuttosto specifica, anche perché solitamente un cliente può diventare fornitore, ma che lo diventino tanti in una sola volta è un po' raro. forse la richiesta è specifica per un caso particolare. a meno che non sia una cosa banale da sviluppare, non la metterei tra le priorità di questa release o la prossima...
