### ISSUE TITLE
calcolo sconto % errato su rigo ordine

### ISSUE THREAD

**Issue by osm-gc** [devcode-it/openstamanager#331]
In fase di inserimento di uno sconto in % sul rigo dell'ordine esso non viene calcolato.
Viene calcolato solo se ritorno in variazione del rigo.

**Comment by lucasalva87** [comment]
Grazie mille @osm-gc  per la segnalazione.
Confermo il presentarsi dell'anomalia sia nella 2.4.1 che nella 2.4.2

![ordini cliente openstamanager 1](https://user-images.githubusercontent.com/30728163/46944636-d862c180-d072-11e8-934c-e9e67266e230.png)
