### ISSUE TITLE
Sconto percentuale con passaggio parziale tra documenti

### ISSUE THREAD

**Issue by osm-gc** [devcode-it/openstamanager#332]
Se effettuo un passaggio parziale da preventivo ad ordine come proposto con il crea ordine nel preventivo se ho inserito uno sconto globale per % esso non viene ricalcolato correttamente sugli articoli selezionati ma riportato per intero sfalsandone il valore e non riportando la % nel campo sconto globale nella testata dell’ordine. Andando poi successivamente a completare il passaggio degli articoli rimasti dello stesso preventivo forse sarebbe opportuno proporre solo gli articoli residui o evidenziare quelli già passati in precedenza in modo avere un quadro più chiaro.

**Comment by Dasc3er** [comment]
@osm-gc Controlla la seguente issue #542 per rimanere aggiornato sul nuovo funzionamento degli sconti.
Purtroppo, anche con le nuove modifiche, la gestione automatica delle percentuali di sconto sulla base di un sottoinsieme di righe del documento non è possibile, e dubito che verrà implementato in futuro.
