### ISSUE TITLE
Conservazione dei dati (fatturazione elettronica) e collegamento con commercialista

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#335]
## Comportamento richiesto

Conservazione dei dati in merito alla fatturazione elettronica (possibilmente tramite [piattaforma AGYO](https://www.teamsystem.com/store/agyo-piattaforma/) e collegato con il commercialista)

## Comportamento attuale

N/D

## Contesto

Salve,
come avverrà la conservazione dei dati su OpenStaManager in merito alla fatturazione elettronica? È possibile integrare OSM con la [piattaforma AGYO](https://www.teamsystem.com/store/agyo-piattaforma/)?
Grazie

* Modulo: Fatturazione
* Versione del progetto: 2.4.1
* Versione PHP: 7.1
* Tipo di server: Apache

**Comment by lucasalva87** [comment]
Ciao @maicol07 sai se ci sono delle API per potersi interfacciare con la piattaforma AGYO?

**Comment by maicol07** [comment]
Credo di sì
[https://www.01net.it/fatturazione-elettronica-b2b-teamsystem-agyo-ce/](https://www.01net.it/fatturazione-elettronica-b2b-teamsystem-agyo-ce/)

**Comment by Dasc3er** [comment]
Il Sistema di Interscambio prevede la conservazione gratuita delle fatture elettroniche: https://www.agenziaentrate.gov.it/wps/content/nsilib/nsi/aree+tematiche/fatturazione+elettronica/fatturazione+elettronica+site+area/servizi+consultazione+e+conservaz+fatture+elettroniche.

**Comment by lucasalva87** [comment]
Grazie mille per la segnalazione @Dasc3er, volevamo evitare i servizi offerti dall'agenzia delle entrate che di solito sono complicati e poco efficienti. Ho appena sentito il supporto di AGYO e mi hanno confermato che non esistono API. Hanno un applicativo client chiamato "Directory Analyzer". Qui trovi i dettagli e link per scaricarlo: https://agyo.elevio.help/it/articles/171

**Comment by maicol07** [comment]
Quindi, Directory Analyzer lavora in contemporanea con l'SDI (dopo aver scaricato le fatture in una cartella speciale nel proprio PC)?

**Comment by lucasalva87** [comment]
Per ora non è prevista la conservazione, ne invio all'SDI.

**Comment by Dasc3er** [comment]
La versione attuale del plugin prevede la sola creazione della fattura elettronica a partire dalla fattura registrata da OpenSTAManager.
Per la firma e l'invio a SdI sarà necessario sfruttare servizi esterni, anche se è possibile che in futuro vengano integrati alcuni sistemi tramite moduli/plugin a pagamento o perfino in modo pubblico.

Allo stesso modo sarà possibile registrare automaticamente le fatture elettroniche ricevute attraverso un plugin nella sezione di Acquisto.

**Comment by maicol07** [comment]
@Dasc3r ho letto sul forum riguardo ad una partnership e ad un nuovo plugin a pagamento. A che punto è lo sviluppo?

**Comment by Dasc3er** [comment]
Il sistema integrato è nelle ultime fasi di rifinitura, per le tempistiche di rilascio ufficiale @lucasalva87.

**Comment by maicol07** [comment]
@Dasc3er quali funzionalità in specifico saranno presenti nella prossima versione?

_Inviato dal mio ZenFone 3 (ZE520KL) usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Dasc3er** [comment]
Dovrebbero essere integrate tutte le funzioni di invio all'SdI e di ricezione di ricevute e fatture di acquisto, attraverso un API proprietaria.
In futuro saranno rilasciate ulteriori personalizzazioni a pagamento per l'integrazione con API di altri servizi sulla base delle richieste (Aruba, Agyo,...).

Per il momento, queste funzioni sono ottenute come modifiche minime del sistema manuale:
- quando si visita il plugin *Fatturazione elettronica* in **Fatture di acquisto** viene automaticamente eseguito un controllo sulla presenza di fatture non importate.
- è stato inserito un nuovo pulsante "Invia" nel plugin *Fatturazione elettronica* in **Fatture di vendita**.
- è stato creato un nuovo plugin *Ricevute* in **Fatture di vendita** che effettua i controlli sulle ricevute dall'SdI tramite un pulsante apposito.

Quindi le funzionalità richiederanno comunque una minima interazione con l'utente, per permettere di individuare le nuove fatture o ricevute effettivamente importate e impedire la comparsa di "fantasmi".

**Comment by maicol07** [comment]
@Dasc3er le funzioni descritte saranno quindi utilizzabili nella prossima versione gratuitamente, oltre al modulo a parte per la ricezione automatica?

_Inviato dal mio ZenFone 3 (ZE520KL) usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Dasc3er** [comment]
Saranno tutte funzioni a pagamento.
