### ISSUE TITLE
Modal su modal

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#336]
OSM 2.4.2
Se si apre una finestra modale per visualizzare l'allegato ma si è già dentro un'altra finestra modale, non è poi più possible  scrollare la pagina ed eventualmente cliccare la "x" per uscire dal primo modale

Plugin in cui si verifica il problema: Pinanificazione attività
Modulo: Contratti.

![contratti openstamanager 13](https://user-images.githubusercontent.com/30728163/47495160-b7108b00-d853-11e8-8a29-3da8113f34ae.png)

**Comment by Dasc3er** [comment]
Con il commit af85cee il problema dei modal dovrebbe essere risolto.

**Comment by lucasalva87** [comment]
Confermo! :smile:

**Comment by beppe9000** [comment]
Ho riscontrato un problema simile una installazione pulita dell'ultima versione.
In particolare durante l'aggiunta di una categoria durante l'aggiunta di un articolo durante l'aggiunta di una riga di ddt in entrata il click sul "+" per aggiungere la categoria ha chiuso il modal dell'articolo.
Chiudendo tutto rimango con lo sfondo nero trasparente che impedisce di interagire con la pagina.
