### ISSUE TITLE
Errore su anagrafiche con debug a true

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#337]
![immagine](https://user-images.githubusercontent.com/1647128/47562498-f5bf4780-d91e-11e8-9f46-3b644ea59eb1.png)

Succede solo con il debug attivo...

**Comment by Dasc3er** [comment]
@loviuz Non riesco a replicarlo, stai utilizzando una versione aggiornata agli ultimi commit?

**Comment by lucasalva87** [comment]
Provato anch'io con 2.4.2 e ultime fix (8f083dc). Non riscontro il problema.

**Comment by loviuz** [comment]
Ho solo provato ad aggiornare l'ultimo src/Modules.php... ora verifico in modo più approfondito.

**Comment by loviuz** [comment]
Ho trovato da dove proviene l'errore: disabilitando alcuni moduli, nel mio caso "Preventivi", probabilmente salta qualcosa nelle statistiche e dà questo errore.

**Comment by Dasc3er** [comment]
Effettivamente si trattava proprio di un problema con il nuovo sistema di _include_ attraverso gli oggetti.
Se il modulo viene disabilitato, non **devono** essere utilizzabili i suoi contenuti e quindi non riusciva ad istanziare l'oggetto per raggiungere il percorso corretto.

Ora se il modulo è disabilitato l'inclusione viene ignorata.
