### ISSUE TITLE
Sovrapposizione dei dati dell'azienda a quelle del cliente nelle stampe

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#339]
## Comportamento attuale

I dati anagrafici dell'azienda vengono sovrapposti a quelli del cliente (vedi immagine), tyttavia nella beta disponibile sul sito non è presente questo problema, in quanto il carattere è più piccolo.
![immagine](https://user-images.githubusercontent.com/9463142/47584770-cb3faf80-d95b-11e8-87dd-9e1ac8a37404.png)

## Passi per riprodurre il comportamento

Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Inserire tanti campi nell'anagrafica dell'azienda (es. Ragione sociale, via, città, p.iva, CF, telefono, email e sito web)
2. Creare un preventivo
3. Effettuare la stampa

## Contesto

* Modulo: Preventivi e altri... (Stampe)
* Versione del progetto: 2.3.1
* Versione PHP: 7.1
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Duplicato di #293.
È stato risolto utilizzando un carattere più piccolo, e non ci sono altri metodi validi e generali.

**Comment by maicol07** [comment]
Ho aggiunto il fix sulla mia installazione. Funziona perfettamente
