### ISSUE TITLE
Limitazione modifica "Tipo di anagrafica" nei record

### ISSUE THREAD

**Issue by gabrielepiccinnu** [devcode-it/openstamanager#34]
Se aggiorno l'anagrafica modificando il campo "Tipo di anagrafica" funziona.

![image](https://user-images.githubusercontent.com/25913492/31004236-cf090604-a4f3-11e7-836a-8eff1f348022.png)

Ad una eventuale successiva modifica, nella stessa scheda questo campo risulta non più modificabile, con classe CSS "disabled"
![image](https://user-images.githubusercontent.com/25913492/31004221-bf61072e-a4f3-11e7-9c7a-1b0e64313e25.png)

**Comment by Dasc3er** [comment]
@gabrielepiccinnu Questo è un blocco intenzionale, per evitare che un'anagrafica di tipo Azienda venga modificata e spostata in un'altra categoria...
@lucasalva87 Effettivamente però la selezione per questo caso si potrebbe rendere un po' più "elegante": potremmo lasciare il select "Tipo di anagrafica" per le tipologie normali, e inserire un checkbox per la tipologia Azienda.

**Comment by gabrielepiccinnu** [comment]
Si ho appena individuato questo blocco intenzionale, se però per errore attribuisco una tipologia errata, non posso più modificarla...
![image](https://user-images.githubusercontent.com/25913492/31005030-4048ff88-a4f7-11e7-9021-f3734a240b64.png)

Ho rimosso la riga 21 su /anagrafiche/edit.php

**Comment by lucasalva87** [comment]
Ciao a tutti, questo avviene perché volta definita l’anagrafica “azienda” non è più possibile eliminarla ne modificarne la tipologia. Come non è neanche più possibile caricare nuove anagrafiche di tipo “azienda”. Giustamente **ce ne può essere una sola per installazione**. Se modifico le informazioni della mia anagrafica, aggiorno sempre e solo quella scheda.

**Comment by Dasc3er** [comment]
Per il momento averi migliorato la funzionalità nel seguente modo:
![cattura](https://user-images.githubusercontent.com/15911489/31022946-afb324be-a53a-11e7-9d2c-b293bac93bec.PNG)

Nel caso l'anagrafica Azienda non sia ancora selezionata, compare nel select; altrimenti non risulta più selezionabile e compare il messaggio nell'immagine sopra.
