### ISSUE TITLE
Bug impianti

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#342]
Tentando di inserire la matricola: 

> 12049207370079061

il risultato è:
![immagine](https://user-images.githubusercontent.com/30728163/47908704-1131d180-de8e-11e8-980b-7849589c4798.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Ho appena provato e non riesco a replicarlo.
PHP 5.6.31 con Intl attivo e non.

**Comment by lucasalva87** [comment]
Io ho PHP 7.2.9 , Intl attivo.

**Comment by Dasc3er** [comment]
Per la versione 2.5 propongo il completamento della issue #333 per risolvere il problema in modo definitivo.
