### ISSUE TITLE
Aggiornamento attraverso fasi

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#343]
## Comportamento richiesto

Propongo la separazione della procedura di aggiornamento tramite ZIP nelle seguenti fasi:
- Caricamento dello ZIP
- Visualizzazione del CHANGELOG e di eventuali messaggi informativi (con schermata dei requisiti), con possibilità di effettuare un backup o annullare l'aggiornamento
- Aggiornamento effettivo

In questo modo sarebbe più semplice rilasciare versioni con modifiche consistenti nel comportamento, avvertendo l'utente finale di tali modifiche e in particolare segnalare più volte l'eventuale condizione di _beta_ dell'aggiornamento.

## Comportamento attuale

Una volta caricato lo ZIP, l'aggiornamento procede immediatamente a sovrascrivere i file ed aggiornare il database senza dare la possibilità di messaggi aggiuntivi/backup e controllo dei nuovi requisiti.

**Comment by lucasalva87** [comment]
@Dasc3er ottima idea. Però, solo per sicurezza, io lascerei un prompt dove si chiede se si vuole effettuare il backup prima di procedere all'aggiornamento. Così in caso estremo si ha la possibilità di effettuare un restore.

**Comment by loviuz** [comment]
forte!! riguardo il downgrade però, non credo sia utile, ed anche un po' complesso da gestire. farei ripristinare un backup al posto di gestire il downgrade

**Comment by Dasc3er** [comment]
@loviuz In effetti si tratta più di un bug piuttosto che una feature.

**Comment by Dasc3er** [comment]
Ora il sistema impedisce l'aggiornamento se lo ZIP contiene una versione precedente del gestionale.
Se invece lo ZIP contiene moduli/plugin, vengono rimossi quelli già installati e aggiornati alla versione presente.

Il completamento di queste funzioni e di #302 è stato ottenuto con due nuove librerie (che dovrebbero avere un impatto estremamente ridotto sulle dimensioni):
- https://github.com/erusev/parsedown
- https://github.com/guzzle/guzzle
