### ISSUE TITLE
Bug: totale ore interventi

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#344]
Versione 2.4.2
Non vengono calcolate  le ore di intervento.
![attivita openstamanager 36](https://user-images.githubusercontent.com/30728163/47912281-5d820f00-de98-11e8-9cbc-acf112b2553b.png)

**Comment by Dasc3er** [comment]
Risolto con il commit d1d9b17.
C'era un errore sul nome della variabile.

**Comment by lucasalva87** [comment]
Ok. Il però problema persiste nell'esploso dei costi.

![attivita openstamanager 38](https://user-images.githubusercontent.com/30728163/47913446-6ecd1a80-de9c-11e8-8950-4d1ebfc0b2d0.png)
