### ISSUE TITLE
OWASP CSRF PROTECTOR VALIDATION FAILURE

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#345]
OSM 2.4.2
Modulo: Contratti
Plugin: Pianificazione promemoria
Se protezione contro CSRF attiva viene restituito l'errore in oggetto.

**Comment by Dasc3er** [comment]
Se il problema si verifica in casi ristretti, è possibile disattivare il controllo CSRF tramite la configurazione *$disableCSRF*.
Potresti controllare che non ci siano errori JavaScript?

**Comment by Dasc3er** [comment]
Nella versione 2.5 sarà possibile sostituire il sistema attuale con uno integrato a livello HTML, e dunque questi problemi dovrebbero venire risolti.
