### ISSUE TITLE
Nota di credito

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#347]
Se da una fattura di vendita creo una nota di credito, anche se spuntate, le righe descrizione non vengono copiate. 
![fatture di vendita openstamanager 28](https://user-images.githubusercontent.com/30728163/48365890-7d8dab80-e6ac-11e8-9059-c3763b3ac81b.png)

**Comment by Dasc3er** [comment]
Il commit c1dcf3de7118c341779e79fad077e76928536269 dovrebbe risolvere completamente il problema.
