### ISSUE TITLE
Miglioramento del sistema di sviluppo

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#35]
Con il passaggio a Github come gestore del progetto, si è aperta la possibilità di integrare il processo di sviluppo con strumenti automatizzati quali [Continuous Integration](https://it.wikipedia.org/wiki/Integrazione_continua) e [Unit Testing,](https://it.wikipedia.org/wiki/Unit_testing) che risulterebbero molto utili per controllare in modo automatico il funzionamento di alcune sezioni di base del codice.

In particolare, propongo innanzitutto l'introduzione di un sistema di testing PHP basato sul framework open source [PHPUnit](https://github.com/sebastianbergmann/phpunit).
Questo porterebbe alla creazione di un'apposita cartella (**tests**) contenente un insieme di casistiche su cui richiamare le funzioni del gestionale (derivanti da classi o altre fonti) e controllarne l'effettivo funzionamento.

Un'esempio di base in questo senso è fornito dalla classe _Formatter_, al momento responsabile della conversione automatica dei formati per il gestionale: nel caso si presentassero future necessità di ampliamento delle casistiche (come nel caso #30), questi test controllerebbero l'effettivo funzionamento della classe in tutte le situazioni prevedibili e di interesse.
Lo stesso vale per tutte le altre classi, oltre che per le funzioni responsabili di individuare scadenze, prezzi e altro all'interno dei singoli moduli.

In questo modo, sarebbe possibile migliorare il controllo sull'effettivo funzionamento delle funzioni di base del progetto a seguito di piccole e grandi correzioni.

Una volta completata (o introdotta) questa funzionalità, si potrebbe individuare uno strumento CI tra i molti disponibili e integrarlo con il sistema Github dei commit, ottenendo in questo modo un feedback automatico basato sul sistema di testing.

**Comment by loviuz** [comment]
non ho mai provato personalmente gli unit test su PHP. ovviamente è ben accetta se vuoi provare ad implementarla :-)

**Comment by Dasc3er** [comment]
I tests automatici sono stati introdotti a partire dalla versione 2.4.2 al fine di velocizzare la procedura di release.
Resta da individuare l'eventuale implementazione di un sistema CI per la loro esecuzione automatica

**Comment by Dasc3er** [comment]
Le funzionalità di testing automatico sono al momento in sviluppo nella repository [devcode-it/openstamanager-tests](https://github.com/devcode-it/openstamanager-tests).
Negli anni scorsi una prima versione dei test era stata completata con Codeception (disponibile nella cartella tests/ della repository corrente delle versioni attuali), sostituita infine da test Selenium in Python per maggiore libertà e flessibilità. L'integrazione con CI di GitHub (GitHub Actions) è sperimentalmente disponibile in https://github.com/devcode-it/openstamanager/tree/master/.github/workflows.
