### ISSUE TITLE
Controllo inserimento CodiceFiscale

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#350]
Sarebbe utile inserire un controllo sulla coerenza e correttezza del Codice Fiscale inserito in anagrafica

**Comment by Dasc3er** [comment]
La proposta potrebbe essere completata con l'implementazione della seguente libreria: https://github.com/DavidePastore/codice-fiscale

**Comment by lucasalva87** [comment]
Sì, l'avevo provato a fine Giugno. Mi sembrava molto valido :+1:

**Comment by Dasc3er** [comment]
Controllo completato con il commit f5ef5a64f23dd1e9222cae573ff8f51a01a98eb3.
In futuro si potrebbe prevedere l'eventuale auto-compilazione dei campi _Ragione Sociale_, _Data di Nascita_, ...
