### ISSUE TITLE
BUG: Finestra di errore all'apertura del modulo contratti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#351]
Appena clicco su Vendite-->Contratti mi appare questa finestra:

![immagine](https://user-images.githubusercontent.com/40104356/48572316-6a2b4c00-e909-11e8-9b1a-9c9c01b72bae.png)

OSM 2.4.2

**Comment by Dasc3er** [comment]
Ciao @idraulicadueci ,
hai per caso effettuato delle modifiche sulle query previste dal modulo oppure nella struttura del database?
A partire da quale versione hai aggiornato?

_Potresti condividere il contenuto dei log dentro la cartella **logs/**?_

**Comment by idraulicadueci** [comment]
Ciao,
la storia è un po' lunga: in pratica feci l'aggiornamento alla 2.4.1 partendo dalla beta release. Mi dava dei problemi e quindi feci delle modifiche alla query DATABASE.SQL
[2_4_1.zip](https://github.com/devcode-it/openstamanager/files/2586608/2_4_1.zip)
Finora ha funzionato tutto perfettamente senza bug, ne' errori, quindi ho dato per scontato che la modifica della query del backup fosse corretta. Evidentemente c'è qualcosa che ora entra in conflitto con la 2.4.2.
Grazie per la risposta. Un saluto.
PS Gran bel lavoro la 2.4.2!! Complimenti

**Comment by Dasc3er** [comment]
@idraulicadueci Potresti condividere il contenuto dei log dentro la cartella logs/?

**Comment by idraulicadueci** [comment]
Dimenticavo il file log
[error.log](https://github.com/devcode-it/openstamanager/files/2586628/error.log)

**Comment by Dasc3er** [comment]
Potresti provare ad eseguire il seguente comando in PhpMyAdmin?
```sql
DELETE FROM `zz_views` WHERE `query` = 'co_preventivi.idanagrafica' LIMIT 4
```

Il problema sembra proprio relativo ad alcune modifiche e esecuzioni molteplici di query di aggiornamento.

**Comment by idraulicadueci** [comment]
Ho provato ma non cambia niente, mi dà anche questo errore:
![immagine](https://user-images.githubusercontent.com/40104356/48602075-3c2e2200-e972-11e8-9f5c-02e0ae1e88dc.png)
Ho provato a inserire un contratto ma non appare nell'elenco

**Comment by Dasc3er** [comment]
Ci servono sempre log...
Potresti provare a cancellare il file **error.log** (che è decisamente pieno di informazioni) e riprovare a caricare la pagina, condividendo poi i log?

**Comment by idraulicadueci** [comment]
[error.log](https://github.com/devcode-it/openstamanager/files/2590266/error.log)

**Comment by idraulicadueci** [comment]
Ora funziona, sei un grande!! Grazie Thomas.
