### ISSUE TITLE
ATTIVITA - Non considera lo sconto nell'imponibile

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#352]
![image](https://user-images.githubusercontent.com/34273200/48614129-d3ed3980-e98d-11e8-97ad-c0cbcaab49da.png)
Anche nella stampa
![image](https://user-images.githubusercontent.com/34273200/48614234-13b42100-e98e-11e8-930e-75f0e59e1892.png)

**Comment by lucasalva87** [comment]
Con versione 2.4.2 rilasciata il 14/11/2018 il problema non si presenta:

![attivita openstamanager 39](https://user-images.githubusercontent.com/30728163/48619362-8c21de80-e99c-11e8-9f4a-97436c044b0b.png)

**Comment by fgambarelli** [comment]
Scusa ma l'ho provato sulla versione online, l'errore lo presenta quando lo sconto è in percentuale, mentre funziona correttamente se lo sconto è inserito in cifre.

**Comment by lucasalva87** [comment]
La versione on-line è una beta di 2 mesi fa. Oggi ho provveduto ad aggiornarla alla versione stabile.
