### ISSUE TITLE
SCADENZARIO - Individuazione della rata 

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#356]
Nel caso di fatture su più rate, le diverse  rate sono identificabili nell'elenco, 
![image](https://user-images.githubusercontent.com/34273200/48622382-d6a85880-e9a6-11e8-92b5-9818093f9168.png)

ma quando si apre la rata, in realtà si apre tutte le rate della fattura e viene sempre pagata in automatico la prima, usando il pulsante della prima note; sarebbe più utile che si aprisse solo la rata selezionata dall'elenco precedente.
![image](https://user-images.githubusercontent.com/34273200/48622571-76fe7d00-e9a7-11e8-816e-7a35c1f8a9a6.png)

Inoltre sarebbe utile avere un campo note, nel quale poter registrare attività o info sulla scadenza.

**Comment by Dasc3er** [comment]
Per quanto riguarda il campo note, potrebbe essere certamente utile.

Aprire invece in modo separato le rate renderebbe più complesso le informazioni presentate, oltre che la nuova funione di creazione rate aggiuntive.
Sarebbe più sensato miglioare l'organizzazione grafica per indicare più chiaramente la rata che si è cercato di aprire.

**Comment by Pek5892** [comment]
Pagamento delle singole rate in release nella versione 2.4.52 
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/3e244b20-5c74-42ff-96ea-d13b4de9a2ef)
