### ISSUE TITLE
PRIMA NOTA - Registrazione movimento fattura

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#357]
All'emissione della fattura, la registrazione in prima nota non ha la quadratura corretta del DARE ed AVERE, perchè l'iva viene registrata a 4 cifre decimali .
Es. la fattura seguente 
![image](https://user-images.githubusercontent.com/34273200/48626061-3277df00-e9b1-11e8-88c4-566ce7355945.png)
in prima nota in co_movimenti risulta contabilmente non corretto, l'iva deve essere uguale all'iva totale della fattura.
![image](https://user-images.githubusercontent.com/34273200/48626186-8aaee100-e9b1-11e8-97f8-02c8c350894b.png)

**Comment by Dasc3er** [comment]
@loviuz Potrebbe essere che con le diverse modifiche applicate alla procedura di prima nota il problema sia stato risolto?

**Comment by loviuz** [comment]
Non ho ben capito il problema, mi servirebbe un esempio pratico. Comunque, le registrazioni contabili devono essere per legge a 2 cifre decimali, non esiste l'iva a 3 o più decimali, per questo anche a video e in stampa i totali e l'iva sono stati forzati a 2 decimali da qualche release in poi, a memoria credo dalla 2.4.11

**Comment by Dasc3er** [comment]
Chiuso per mancanza di dettagli.
