### ISSUE TITLE
Aggiunta badge sul README

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#36]
Propongo l'aggiunta di alcuni badge per migliorare la visibilità del progetto in modo visivo:

- Release corrente (solo release ufficiale oppure anche pre-release)
[![GitHub release](https://img.shields.io/github/release/devcode-it/openstamanager.svg)](https://github.com/devcode-it/openstamanager/releases)
[![GitHub release](https://img.shields.io/github/release/devcode-it/openstamanager/all.svg)](https://github.com/devcode-it/openstamanager/releases)

- Download (release ufficiale o totali)
[![Github Releases](https://img.shields.io/github/downloads/devcode-it/openstamanager/total.svg)](https://github.com/devcode-it/openstamanager/releases)
[![Github Releases](https://img.shields.io/github/downloads/devcode-it/openstamanager/latest/total.svg)](https://github.com/devcode-it/openstamanager/releases)

- Download totali da Sourceforge (per le versioni precedenti)
[![SourceForge](https://img.shields.io/sourceforge/dt/openstamanager.svg)]()

- Licenza del progetto
[![license](https://img.shields.io/github/license/devcode-it/openstamanager.svg)](https://github.com/devcode-it/openstamanager/blob/master/LICENSE)

- Commit dall'ultima release ufficiale
[![Github commits (since latest release)](https://img.shields.io/github/commits-since/devcode-it/openstamanager/latest.svg)](https://github.com/devcode-it/openstamanager/commits/master)

- Donazione PayPal
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)]()

@loviuz @lucasalva87 @fpsoftware Voi che ne pensate?
Per maggiori dettagli sulle possibilità, il gestore automatico di questi badge è [Shields.io](http://shields.io).
Gli stili disponibili sono [qui](http://shields.io/#styles).

**Comment by loviuz** [comment]
per me ok
