### ISSUE TITLE
Miglioria template preventivi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#361]
## Comportamento richiesto

Far scomparire la dicitura **"In attesa di un Vostro Cortese riscontro, colgo l'occasione per porgere Cordiali Saluti"** una volta che il preventivo è stato accettato o convertito in fattura.

**Comment by Dasc3er** [comment]
@lucasalva87 Ragionando su questa modifica, le stampe non dovrebbero essere sempre uguali a meno di cambiamenti dei dati da mostrare?
Non sarebbe quindi tecnicamente sbagliato rimuovere la dicitura dalla stampa sulla base dello stato del documento? Potrebbe essere meglio creare un'impostazione per mostrare/nascondere sempre la dicitura.

**Comment by Pek5892** [comment]
Introdotta dicitura standard:
"Gentile Cliente,
inviamo in allegato il preventivo numero # del ##/##/####.
Distinti saluti"
