### ISSUE TITLE
Sicurezza email STARTTLS

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#362]
## Comportamento richiesto

Aggiunta dell'opzione di sicurezza STARTTLS, in quanto alcuni hosting hanno solo questa opzione per il server SMTP (vedi [Tophost](https://www.tophost.it/supporto/posta-elettronica/come-configuro-un-indirizzo-email-nel-mio-client/))

## Comportamento attuale

Le opzioni disponibili per la sicurezza del server SMTP sono solo due: SSL e TLS.

## Contesto

* Modulo: Gestione Email
* Versione del progetto: 2.4.2
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by maicol07** [comment]
C'è qualche modo per ottenerle? Magari abilitando la funzione di debug?

**Comment by Dasc3er** [comment]
Purtroppo non ho conoscenze molto estensive sulle comunicazioni necessarie con il server per completare l'invio di una mail.
@lucasalva87

**Comment by maicol07** [comment]
Aggiornamento 2.4.5: L'account email funziona benissimo se si abilita l'opzione Disattiva verifica SSL

**Comment by Dasc3er** [comment]
Possiamo quindi considerare il problema risolto?

**Comment by Dasc3er** [comment]
@maicol07 I teoria vengono inviati tramite SSL, ma non vengono controllati i certificati.
