### ISSUE TITLE
Dashboard: Correzione valore "Data conclusione" nell'elenco dei preventivi in lavorazione

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#363]
## Comportamento richiesto

Se il campo nel modulo è vuoto viene restituito una valore non corretto (es. 30/11/-0001). Sarebbe corretto che non venisse resstituito alcun valore o almeno la dicitura "IN CORSO"

**Comment by loviuz** [comment]
Corretto in https://github.com/devcode-it/openstamanager/commit/56fcdb54e483a8ac343da2ebfe00a75aea0867bb
