### ISSUE TITLE
BUG: Il link "INDIETRO" all'interno dei moduli riporta all'elenco principale

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#365]
## Comportamento attuale

Quando sono all'interno di un modulo di inserimento dati, se entro in un sotto-modulo, il tasto INDIETRO non riporta al modulo principale, ma all'elenco. Per esempio se entro in una scheda anagrafica e clicco su SEDI, il tasto INDIETRO all'interno del modulo sedi, non mi riporta alla scheda anagrafica ma all'elenco anagrafiche.

**Comment by Dasc3er** [comment]
Il finanziamento previsto è proprio questo.
Per tornare al modulo principale devi cliccare sul nome "Anagrafiche".
