### ISSUE TITLE
MIGLIORIA: Orario fine lavori deve rimanere vuoto

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#366]
## Comportamento richiesto

L'inserimento della data e ora fine lavori deve essere opzionale, poiché quando prendo l'appuntamento con il cliente conosco la data e ora di inzio al momento che ho assegnato il tecnico, ma non posso conoscere quando il tecnico avrà terminato l'intervento. Ovviamente l'inserimento deve diventare obbligatorio per poter flaggare l'intervento come COMPLETATO

Versione attuale: OSM 2.4.2

**Comment by loviuz** [comment]
Attualmente, se specificato un orario di inizio, serve specificare anche un orario di fine attendibile, altrimenti il calcolo ore dell'intervento viene calcolato in modo errato. Si potrebbe usare come workaround l'inserimento di un orario fine identico all'orario inizio, così da far risultare l'attività di 0 ore non essendo ancora stata svolta, però non si vedrebbe a calendario. Credo anche che, a livello di gestione aziendale, si debba prevedere un tempo indicativo di quanto il tecnico può impiegare, altrimenti se ci fossero diversi interventi pianificati senza orario di fine, la dashboard mostrerebbe il calendario del tecnico vuoto.
