### ISSUE TITLE
Prezzo interventi non viene considerato il prezzo specificato nel tecnico

### ISSUE THREAD

**Issue by sam48** [devcode-it/openstamanager#370]
## Comportamento richiesto

Come prezzo per l'attività di un intervento viene sempre preso quella di default e non quello del tecnico

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by lucasalva87** [comment]
Ciao sam48 potresti dirci che versione di OSM stai utilizzando. Non risulta questo malfunzionamento con la 2.4.2
Grazie.

**Comment by sam48** [comment]
Ciao,
Sto usando la 2.4.2 con wamp, con la 2.4.1 non mi capitava.
Avevo un intervento ancora in bozza fatto con la 2.4.1 ho aggiunto delle
righe, ma mi ha messo come tariffa 42€(che è la tariffa generale per gli
interventi generici) invece che 35€ (che è la tariffa del tecnico per
interventi generici). Provo a creare un nuovo intervento e vedo se cambia.

Distinti saluti,
Samuele Minelli

Il giorno lun 3 dic 2018, 12:46 Luca <notifications@github.com> ha scritto:

**Comment by sam48** [comment]
Ciao luca,
Confermo, anche generando un nuovo intervento non cambia.
allego qualche screen.
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
Cordiali saluti,

Samuele


Il giorno lun 3 dic 2018 alle ore 12:56 Samuele Minelli <
samuele.minelli@gmail.com> ha scritto:

**Comment by lucasalva87** [comment]
Scusa Samuele ma non vediamo gli screenshot. Potresti ricaricarli?

**Comment by sam48** [comment]
Riallego gli screenshot e vi do anche il link per scaricare le immagini.

https://drive.google.com/folderview?id=1taaZgqAoF6HwboR1BqDOKlEFUPRJToqz

Distinti saluti,
Samuele Minelli

Il giorno mar 4 dic 2018, 10:45 Luca <notifications@github.com> ha scritto:

**Comment by lucasalva87** [comment]
Non riesco a riprodurre il malfunzionamento. Se non è un problema ti consiglio di aspettare venerdì 07/12 che rilasceremo la versione 2.4.3 ed aggiornare eventualmente a quella.

**Comment by sam48** [comment]
Nessun problema,
Grazie.

Distinti saluti,
Samuele Minelli

Il giorno mar 4 dic 2018, 12:30 Luca <notifications@github.com> ha scritto:

**Comment by sam48** [comment]
Ciao luca,
Ti scrivo per quanto riguarda un'altra argomento, non l'ho visto tra gli
issue aperti per la 2.4.2, ma non mi stampa più le fatture pro forma. È
stata tolta questa funzionalità?

Grazie.

Distinti saluti,
Samuele Minelli

Il giorno mar 4 dic 2018, 16:15 Samuele Minelli <samuele.minelli@gmail.com>
ha scritto:

**Comment by sam48** [comment]
Nella 2.4.1 se una fattura era in stato bozza e facevo stampa fattura, mi
stampava una fattura con dicitura fattura pro forma, adesso, anche se è in
bozza, me la stampa come fattura di vendita.

Distinti saluti,
Samuele Minelli

Il giorno gio 6 dic 2018, 09:24 Luca <notifications@github.com> ha scritto:

**Comment by lucasalva87** [comment]
Questa funzionalità è stata rivista ed è stato aggiunto il relativo sezionale “fatture pro forma” per poter gestire anche le numerazioni diverse.

![fatture di vendita openstamanager 36](https://user-images.githubusercontent.com/30728163/49573438-46728900-f93e-11e8-9839-2099f29053cb.png)
