### ISSUE TITLE
CKEditor come input di modifica

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#372]
Inserire ckeditor anche nei form di modifica e inserimento righe per evitare di visualizzare caratteri html non interpretati.

![fatture di vendita openstamanager 31](https://user-images.githubusercontent.com/30728163/49361105-66564280-f6db-11e8-8991-84de365ee3d1.png)

**Comment by loviuz** [comment]
Attenzione però che nella fattura elettronica questi tag potrebbero dare problemi o essere visualizzati come testo nel formato XML, non molto bello esteticamente. Oppure andrebbe permesso, eseguendo lo strip dei tag html nella generazione dei file XML @Dasc3er @lucasalva87

**Comment by Dasc3er** [comment]
Gli input di tipo `ckeditor `sono presenti ormai da diverse versioni, resta da studiare l'applicazione in campi relativi alle righe.
In questo caso credo che, in relazione all'utilizzo in Fattura Elettronica, convenga abilitare CKeditor per le descrizioni manualmente secondo necessità dell'utente, per evitare problemi in XML.
