### ISSUE TITLE
MIGLIORIA: Correggere query per campo "Per conto di" nel modulo interventi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#373]
## Comportamento richiesto

Sarebbe corretto che il campo restituisse l'elenco dei referenti relativi all'anagrafica indicata

## Comportamento attuale

Il campo restituisce tutte le anagrafiche

**Comment by Dasc3er** [comment]
@loviuz Il funzionamento non è corretto con l'utilizzo delle anagrafiche?

**Comment by lucasalva87** [comment]
Secondo me é corretta la visualizzazione di tutte le anagrafiche cliente (com’è attualmente) il per conto di stabilisce qual’è il cliente a cui andrò a fatturare. Se collego i referenti mi mancherebbero alcuni campi fondamentali come ad esempio la partita iva.
