### ISSUE TITLE
Nuovo widget "Preventivi da fatturare" sul simile di "Preventivi in lavorazione"

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#375]
Aggiungere widget elencante i preventivi che hanno il flag completato = 1 ma che non risultano fatturati (ne come preventivo né come eventuale ordine cliente)

**Comment by NicolaNext** [comment]
Buonasera,
sto testando questa interessante funzione sull'ultima versione rilasciata. Sulla demo non è possibile provarla perchè il widget non è abilitato.
E' tutto come mi aspetto tranne per un dettaglio, forse voluto.
Se io converto un preventivo/ordine in fattura e la lascio in bozza, nel widget non è più segnalato il preventivo da fatturare.
La fattura bozza in effetti c'è ma non è ancora un documento "fiscale" quindi non è davvero una fattura.
