### ISSUE TITLE
Piano dei conti: clienti mancanti

### ISSUE THREAD

**Issue by s0und0ut** [devcode-it/openstamanager#378]
Salve,

ho iniziato da poco ad usare la prima nota, anche se uso da tempo osm, quindi non so precisamente ove collocare il problema.

Comunque quando vado a selezionare un utente specifico non lo trovo, ma ne trovo solo alcuni.

Sembrerebbe che ci siano solo i clienti registrati nell'ultimo anno, quindi dalle ultime versioni di osm.

Non credo che sia un problema riproducibile da altri, ma potrebbe essere un problema, che si sia generato nelle varie migrazioni di versione.

C'è un modo per far si che rigeneri id dell'elenco dei clienti, nella tabella co_pianodeiconti3, che mi sembra di capire è quella che contiene l'elenco dei clienti per il piano dei conti.

Grazie a tutti anticipatamente

* Modulo: prima nota/piano dei conti
* Versione del progetto: 2.4.2
* Versione PHP: 7.1.9
* Tipo di server: wamp

**Comment by Dasc3er** [comment]
Per rigenerare i conti relativi cliente/fornitore basterebbe togliere la tipologia Cliente/Fornitore all'anagrafica e salvare, per poi ri-selezionarla e salvare di nuovo.

**Comment by s0und0ut** [comment]
ho fatto un po di test, ma non funziona modificando la tipologia, non crea automaticamente il relativo conto

ho provato anche creando il codice del conto manualmente (es. 110.100001) e il sistema automaticamente assegna un'anagrafica a random

**Comment by loviuz** [comment]
@s0und0ut hai modo di provare nell'ultima release 2.4.10, o in master? Mi risulta che la funzione sia ora corretta.
