### ISSUE TITLE
Creazione file .xml per la Fatturazione Elettronica alla Pubblica Amministrazione

### ISSUE THREAD

**Issue by gabrielepiccinnu** [devcode-it/openstamanager#38]
Ciao a tutti,

Ho letto nel sito OpenSTAManager che è in fase di sviluppo il modulo per la creazione delle fatture elettroniche alla Pubblica Amministrazione. 

Ci sono novità in merito?

Documentazione FatturaPA
http://www.fatturapa.gov.it/export/fatturazione/it/normativa/f-2.htm

**Comment by fpsoftware** [comment]
segnalo intanto il seguente progetto (compatibile però con la versione 2.2) che permette l'importazione del file xml FatturaPA
https://github.com/LitesysNet/fattura_pa

**Comment by fpsoftware** [comment]
Riguardo la creazione di fatturePA tramite OpenSTAManager è necessario portare nella nuova release la gestione dei sezionali, in quanto questo genere di fatture potrebbero avere una numerazione diversa dalle normali fatture.

**Comment by Dasc3er** [comment]
@gabrielepiccinnu Il plugin per la fatturazione elettronica è attualmente in sviluppo all'interno della branch 2.4.2.
