### ISSUE TITLE
BUG: DDT entrata e uscita inserisce altra anagrafica

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#380]
## Comportamento attuale

Quando creo DDT entrata o uscita, inserisco il destinatario, ma nella schermata successiva del modulo, nel campo destinatario riporta la mia ditta, invece dell'anagrafica scelta.

OSM 2.4.2

**Comment by lucasalva87** [comment]
Ciao, e grazie per la segnalazione. Questo è un bug noto della versione 2.4.2. Ti consiglio di attendere venerdi il rilascio della 2.4.3 dove abbiamo rimediato a questo malfunzionamento.

**Comment by idraulicadueci** [comment]
Ok. Scusa il doppione e grazie per la risposta. Ciao.
