### ISSUE TITLE
SUGGERIMENTO: cambio generale della correlazione dei documenti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#381]
Buongiorno,
stavo pensando che sarebbe opportuno cambiare la logica della conversione dei documenti.
Il documento finale siamo tutti daccordo che è e rimane la fattura. Allo stato attuale però alcuni "sottodocumenti" (preventivi, ordini, ddt, ecc.) non sempre sono correlabili fra loro, per esempio negli interventi non posso riportare un preventivo come posso fare nella fattura. Credo che dovrebbe essere cambiato l'attuale flag "FATTURATO" con il flag "CONVERTITO", magari indicando il documento di conversione come INFO, però dare la possibilità di inserire preventivi e ordini anche negli interventi, oppure come accade ora, direttamente nella fattura. Per rendere meglio l'idea allego il flusso logico
![img](https://user-images.githubusercontent.com/40104356/49497917-d0045700-f869-11e8-852e-53cbeed2d434.jpg)

In poche parole ogni "sottodocumento" può essere inserito nei doc principali (interventi, proforma, fatture) e una volta flaggati come "CONVERTITI" non essere più disponibili per altri documenti.
ES. Faccio un intervento di riparazione dove emetto al cliente un preventivo relativo a una parte di ricambio. Il preventivo accettato lo rendo disponibile per essere inserito nell'intervento con un tasto "+PREVENTIVO", oppure come "+ORDINE" se lo ho convertito in ordine. Successivamente nella fattura inserirò l'intervento che ho creato, ma non avro più disponibile il preventivo convertito precedentemente, questo per evitare doppioni. Per ogni documento avrò una INFO che mi dice che il preventivo X è stato convertito in ORDINE X, oppure INTERVENTO X o direttamente in FATTURA X.

OSM X.X

**Comment by Pek5892** [comment]
"negli interventi non posso riportare un preventivo come posso fare nella fattura"
Funzione introdotta nella release 2.4.31

"ma non avro più disponibile il preventivo convertito precedentemente, questo per evitare doppioni"
Funzione introdotta nelle versioni successive
