### ISSUE TITLE
MIGLIORIA: Inserimento righe articoli

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#382]
## Comportamento richiesto
Prevedere un pulsante "AGGIUNGI e NUOVO" nella schermata di aggiunta articolo che apra subito una nuova schermata di aggiunta riga, per velocizzare l'inserimento degli articoli nei documenti.

**Comment by lucasalva87** [comment]
Ti confermo che l'inserimento di un nuovo articolo, non censito a magazzino, è prevista in fase di inserimento righe articoli nella fattura dalla prossima 2.4.3

**Comment by idraulicadueci** [comment]
Ciao. Scusa non mi sono spiegato bene. Intendevo l'inserimento righe nei documenti, cioè avere la possibilità, dopo avere inserito l'articolo X nell'INTERVENTO X, FATTURA X, ecc., di poterne inserire subito un'altro, senza ritornare alla schermata principale del modulo. Non so se questa modifica sia già stata richiesta.

**Comment by Dasc3er** [comment]
@idraulicadueci Potresti spiegare meglio quali passaggi richiederesti per questa modifica?
Non credo di aver ben compreso ciò che intendi...

**Comment by idraulicadueci** [comment]
![immagine](https://user-images.githubusercontent.com/40104356/49667604-e07c2380-fa5b-11e8-872b-c839ca926841.jpg)

**Comment by Pek5892** [comment]
Migliorata la gestione delle righe dalla versione 2.4.40
