### ISSUE TITLE
Causale movimenti magazzino

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#383]
Rivedere visualizzazione causali movimenti magazzino affinché riportino il numero del documento attuale.
Esempio: una fattura pro forma che è stata poi convertita in fattura di vendita dovrebbe mostrare l'attuale numero del documento. Oppure più genericamente una qualsiasi fattura o ddt che vengono rinominati da 0005/2018 a 0006/2018

![articoli openstamanager 13](https://user-images.githubusercontent.com/30728163/49573996-a0c01980-f93f-11e8-95a6-fa58f39e96fe.png)

**Comment by Dasc3er** [comment]
Corretto con l'introduzione dei riferimenti a documenti tramite classi.
