### ISSUE TITLE
BUG: Importo intervento errato in fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#386]
Quando riporto un intervento in fattura, viene calcolato due volte lo stesso importo.
Anche negli interventi gli importi totali non tornano.
Consiglio mio, nei documenti come Interventi, preventivi, ddt, ecc. riportare solo l'imponibile, magari con dicitura "Importi IVA escusa" e calcolare l'IVA solo nei documenti fiscali (fatture, note di credito, ecc.)
Inoltre il flag "Copia descrizione" non funziona (anche se deselezionato riporta tutte le righe)
OSM 2.4.3

![img1](https://user-images.githubusercontent.com/40104356/49716223-5e564f80-fc53-11e8-8143-96be81829041.png)

![img2](https://user-images.githubusercontent.com/40104356/49716236-6615f400-fc53-11e8-8da1-cd7bdca46a73.png)

**Comment by idraulicadueci** [comment]
Ho notato anche che nell'intervento viene calcolata l'IVA solo sugli articoli. Per questo ribadisco la necessità di eliminare del tutto il calcolo dell'IVA dagli interventi e riportarlo solo in fattura.

**Comment by lucasalva87** [comment]
Grazie per la segnalazione questo era un bug che avevamo riscontrato anche nella versione 2.4.2, probabilmente non è stato corretto in tutti i punti. In pratica il costo dell'intervento viene erroneamente inserito comprensivo del diritto di chiamata.

**Comment by lucasalva87** [comment]
> 
> 
> Ho notato anche che nell'intervento viene calcolata l'IVA solo sugli articoli. Per questo ribadisco la necessità di eliminare del tutto il calcolo dell'IVA dagli interventi e riportarlo solo in fattura.

Il realtà l'iva viene calcolata anche per le sessioni di lavoro.
La semplificazione che tu proponi però è da prendere in considerazione.

**Comment by idraulicadueci** [comment]
Ciao Luca,
ho fatto un'altra simulazione. Ora il calcolo negli interventi sembra corretto. Quando però riporto l'intervento in fattura, l'IVA che indico nella schermata iniziale (per capirsi quella che mi appare quando clicco il "+" per l'aggiunta del documento che chiede data, cliente, tipo di fattura e sezionale) viene presa solo per la manodopera, spese di trasferta e diritto di intervento, mentre per gli articoli e le spese viene considerata l'IVA indicata nella riga degli interventi.
Questo può creare problemi quando si tratta di interventi con aliquote IVA differenti, anche sulla stessa manodopera di prestazione. Lo scorporo dell'IVA dai documenti non fiscali potrebbe risolvere il problema, dando la possibilità all'utente di scegliere successivamente l'aliquota IVA voce per voce. Sarebbe il non plus ultra poterlo indicare nelle impostazioni (aliquota nel tipo di attività).
