### ISSUE TITLE
Aggiunta opzioni Mostra/Nascondi costi riepilogo ore tecnici nei rapporti operazioni ed interventi

### ISSUE THREAD

**Issue by gabrielepiccinnu** [devcode-it/openstamanager#39]
Nella stampa PDF dei rapporti operazioni ed interventi, potrebbe essere utile l'opzione Mostra/Nascondi riepilogo ore con i prezzi. In modo tale che il cliente vede il riepilogo di ore dell'attività svolta ma non i costi.

![image](https://user-images.githubusercontent.com/25913492/31438384-3b46769c-ae88-11e7-8615-c4c916796dc6.png)

**Comment by fpsoftware** [comment]
ciao Gabriele, esiste già questa opzione, dal menù:
Strumenti -> Impostazioni -> Interventi -> Visualizza i costi sulle stampe degli interventi

**Comment by gabrielepiccinnu** [comment]
@fpsoftware Infatti ho chiuso subito dopo averla vista in Impostazioni, Grazie!

**Comment by fpsoftware** [comment]
@gabrielepiccinnu nessun problema, lo volevo solo scrivere nel caso altri cercassero questa possibilità.
Grazie ancora per le varie segnalazioni.
