### ISSUE TITLE
Riportare descrizione ritenuta d'acconto nel template fatture

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#390]
Dato che nella fatturazione è previsto lo "Split Payment" che prevede il versamento dell'IVA da parte del cliente, nella fattura dovrebbe essere riportata la specifica dicitura. Potrebbero anche esistere anche altre diciture relative alle ritenute che devono essere riportate in fattura. Questo non è un problema, perché è possibile sfruttare la tabella delle ritenute d'acconto e riportare la relativa descrizione inserita al posto del label "Ritenuta d'acconto..." nel template.
![img1](https://user-images.githubusercontent.com/40104356/49743521-dc861680-fc92-11e8-896c-aba12ef7d1d7.png)
![img2](https://user-images.githubusercontent.com/40104356/49743528-e3ad2480-fc92-11e8-8028-58c0bf8d3192.png)

**Comment by lucasalva87** [comment]
Grazie per la segnalazione, però con questo escamotage non possiamo sapere che stiamo applicando un split payment nell’xml della fattura elettronica non riusciremmo ad impostare il nodo EsigibilitaIVA su "S" (scissione dei pagamenti) . Inoltre sono diversi i movimenti per la prima nota.
