### ISSUE TITLE
Stampa Fatture: partita iva coperta

### ISSUE THREAD

**Issue by GiuseppeFreddy** [devcode-it/openstamanager#391]
Quando da ordine trasformo in fattura la riga: Descrizione; quantità; prezzo unitario; importo; iva mi va a coprire la riga partita iva del cliente.
Quello che ho notato che se la denominazione della ditta a cui devo intestare la fattura è corto la fattura va bene non subisce nessuna variazione e quando vado a stampare la fattura non si evince nessuna anomalia; invece se l'intestazione dell'azienda è un po lunga mi va a coprire la  riga della P.Iva.
Esiste una funzione che mi vincola la tabella quantità, prezzo unitario, ecc, a partire da sotto la riga Partita Iva indipendentemente dalla lunghezza del nome dell'azienda?
Grazie anticipatamente

**Comment by lucasalva87** [comment]
Ciao Giuseppe, prova a ridurre la grandezza del font utilizzato nell'header della stampa attraverso l’impostazione 'header-font-size' che trovi in 'templates\base\settings.php'
