### ISSUE TITLE
BUG: Riga fattura non prende importo negativo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#393]
Inserendo un importo negativo nella riga fattura, non viene restituito il valore con il segno "-"; il calcolo del totale risulta corretto, ma nel riquadro IVA viene restituito il valore errato.
![img](https://user-images.githubusercontent.com/40104356/49835349-31af4e80-fd9f-11e8-9b3e-7531c32fc039.png)

**Comment by lucasalva87** [comment]
Di solito gli importi negativi vengono inseriti o come sconti o come note di credito in riferimento a delle fatture precedentemente emesse. E' corretto che non vengano visualizzati i segni '-'. Concordo sull'inesattezza del campo importo iva.

**Comment by idraulicadueci** [comment]
Ciao,
è anche vero che talvolta in fattura è necessario indicare importi negativi qualora si tratti di detrazioni non rientranti nella sfera scontistica, per es. "Importo già addebitato nelle precedenti fatture" su una prestazione aggiuntiva in fase di fornitura servizi, senza necessariamente ricorrere alla nota di credito.
![img1](https://user-images.githubusercontent.com/40104356/49856327-d0639b80-fdef-11e8-9558-16e9248182e8.png)

Può andar bene anche indicarlo come sconto, però sarebbe bene che se il campo "Costo unitario" è zero nell'importo mi venga riportato il valore. Allo stato attuale viene indicato solo il valore dello sconto e gli importi restituiscono valore null. Il riepilogo IVA resta non corretto.
![img2](https://user-images.githubusercontent.com/40104356/49856660-b080a780-fdf0-11e8-895c-876e77217f96.png)

**Comment by idraulicadueci** [comment]
Con la versione 2.4.4 il problema è risolto.
