### ISSUE TITLE
BUG: Non viene generata la fattura elettronica

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#394]
Cliccando su GENERA, mi appare una pagina vuota. In base a quanto visto dall' error.log, ho inserito manualmente il campo mancante 'xml_generated_at e allora la fattura viene generata. Sicuramente manca qualcos'altro nel database. Inoltre non riesco a visualizzare la fattura tramite il pulsante VISUALIZZA.
Non so se dipende da me, comunque ho fatto un'installazione pulita. Faccio un test per vedere se dipende dall'import del database estrapolato dal backup dell'installazione precedente.
[error.log](https://github.com/devcode-it/openstamanager/files/2671543/error.log)

**Comment by Dasc3er** [comment]
Il problema è probabile causato dall'import del database precedente.

**Comment by idraulicadueci** [comment]
In effetti è come detto e come da te confermato. Ho provato a fare un'installazione pulita della 2.4.2 e poi a reimportare il database. A questo punto però, nemmeno con la funzione di aggiornamento risolvo. C'è una procedura esatta da seguire per fare in modo che i campi mancanti vengano inseriti correttamente nel db, magari una query?

**Comment by Dasc3er** [comment]
Se hai aggiornato con la procedura ufficiale alla versione 2.4.2 e poi alla 2.4.3 non saresti potuto arrivare a questo punto, quindi gli errori sembrano causati da tue modifiche al database...

**Comment by idraulicadueci** [comment]
Grazie
Credo di aver risolto inserendo manualmente il campo 'xml_generated_at' nella tabella co_documenti. Resta il problema della visualizzazione della fattura elettronica.

**Comment by Dasc3er** [comment]
Ci sono dei log?
