### ISSUE TITLE
op: send-email doppio

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#397]
Versione 2.4.4

Ogni volta che invio una e-mail l'op 

> send-email

 viene salvata due volte in `zz_operations`, generando così di fatto un doppio log (Una volta con `id_email `a null e una volta con `id_email `valorizzato correttamente)
![fatture di vendita openstamanager 38](https://user-images.githubusercontent.com/30728163/50086400-3344a080-01fd-11e9-9e05-97ca69c97287.png)

**Comment by Dasc3er** [comment]
Risolto con il commit ac2c2e0a6f7bc39096872f6cc4de99808e3db152.
Resta da definire se rimuovere i log doppi generati in precedenza.

**Comment by loviuz** [comment]
li lascerei come traccia che possono essere state inviate doppie, l'importante è che non partano più doppie
