### ISSUE TITLE
Miglioria: duplicazione preventivi, riportare righe del documento

### ISSUE THREAD

**Issue by osm-gc** [devcode-it/openstamanager#398]
Anomalia in fase di 'duplicazione preventivi' introdotta con la versione 2.4.4 nel modulo preventivi
Il dettaglio dei righi non viene riportato in qualsiasi modo il rigo è stato inserito sia per articolo sia per riga 
sia per descrizione. Viene riportata solo la testata del preventivo da duplicare

**Comment by lucasalva87** [comment]
Non si tratta di un anomalia, per il momento veniva volutamente riportata solo la testata.

**Comment by loviuz** [comment]
Risolta da @lucasalva87 con db2fd236c8abea7e28430ab5b050dc27053391ed
