### ISSUE TITLE
Problema: Non riesco a visualizzare l'xml della FE generata

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#399]
Sto testando la 2.4.4 su server locale XAMPP, ma non riesco a visualizzare il file xml generato (pagina vuota dopo click su VISUALIZZA). Non so se dipende dal server oppure è un problema del plugin. Da considerare che ho fatto la prova su un'installazione pulita di OSM 2.4.4

**Comment by idraulicadueci** [comment]
Aggiungo che, inoltre, la fattura non compare nemmeno nell'elenco fatture in VENDITE--->Fatture di Vendita

**Comment by idraulicadueci** [comment]
Ho fatto il test installando OSM 2.4.4 su server remoto e funziona tutto. C'è da capire quale problema si presenta su server locale.

**Comment by Dasc3er** [comment]
Forse ti manca un'estensione...
Prova a controllare i **Requisiti** nel modulo **Aggiornamenti**.

**Comment by idraulicadueci** [comment]
Manca l'estensione SOAP, per il resto c'è tutto.

**Comment by Dasc3er** [comment]
La versione minima richiesta per mysql è 5.6.*.
Se non ci sono log riguardanti il problema non possiamo replicarlo correttamente, potresti condividerli?

**Comment by idraulicadueci** [comment]
No, non ci sono log. Provo a cambiare le versioni PHP e MYSQL e faccio risapere.

**Comment by idraulicadueci** [comment]
Trovato il problema: non era attivata l'estensione php_xsl.dll.
Nel file **PHP.INI** è necssario togliere ";" dalla voce **extension=php_xsl.dll** e salvare.
STOP e START per riavviare APACHE con la nuova configurazione.
