### ISSUE TITLE
Problema nel creare un ddt di acquisto da ordine fornitore

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#4]
Non riesce a creare DDT di acquisto da Ordine Fornitore (Errore: Uncaught Exception PDOException: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dt_ddt.descrizione' in 'field list' - SELECT numero, numero_esterno, dt_ddt.descrizione AS tipo, dt_ddt.dir FROM dt_ddt LEFT JOIN dt_tipiddt ON dt_tipiddt.id = dt_ddt.idtipoddt WHERE dt_ddt.id='1'" at C:\xampp\htdocs\opensta2.3\lib\classes\Database.php line 610 ), nè se creo diretamente un DDT di acquisto, stesso errore. Stesso errore anche per DDt di Vendita (ovviamente).

**Comment by Dasc3er** [comment]
Il problema è lo stesso di #1, causato da un errore nella query nella funzione add_movimento_magazzino.
