### ISSUE TITLE
Problema scadenzario e migliorie

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#401]
## Comportamento richiesto

Creare in automatico una riga con nuova scadenza, quando si inserisce un valore PAGATO inferiore a IMPORTO. Questo perché molto spesso i clienti non pagano l'intero importo e si rende necessario stabilire una o più date di scadenza ulteriori. Magari si potrebbe integrare la possibilità di inserire altre scadenze (per es. pulsante AGGIUNGI RATA)

## Comportamento attuale

Se la fattura prevede una sola scadenza, quando entro nella scadenza relativa, ho una sola riga. Inserendo in PAGATO un valore inferiore a IMPORTO, la fattura assume lo stato "Parzialmente pagata" (fra l'altro questo stato non blocca il documento alla stregua di EMESSA), ma questo non consente di tenere traccia dello stato di avanzamento dei pagamenti.
OSM 2.4.4
![img](https://user-images.githubusercontent.com/40104356/50272520-50b17e80-0438-11e9-9346-373b2e1d1c7e.jpg)

**Comment by Dasc3er** [comment]
E' ora possibile aggiungere ulteriori scadenze all'interno dello Scadenzario, modificando manualmente le scadenze presenti. Dovrebbe essere nella versione in sviluppo 2.4.11.
