### ISSUE TITLE
Problema dopo aggiornamento 2.4.4

### ISSUE THREAD

**Issue by MALEFIKOIT** [devcode-it/openstamanager#402]
Salve,
Dopo aver effettuato correttamente l'aggiornamento da 2.4.3 a 2.4.4 riscontro problematiche nella sezione Fatture di Acquisto.

1) Nell'anteprima del documento messo in allegato non lo fa visualizzare ed esce la scritta Forbidden
Failed to load resource: the server responded with a status of 403 (Forbidden) 

2) Non mi appare più la schermata per l'aggiunta di una riga o di una descrizione, premendo i seguenti pulsanti nei log error di chrome mi presenta questo:
editor.php?id_module=15&id_record=30:1148 
Uncaught ReferenceError: buttonLoading is not defined
    at HTMLAnchorElement.<anonymous> (editor.php?id_module=15&id_record=30:1148)
    at HTMLAnchorElement.dispatch (app.min.js:2)
    at HTMLAnchorElement.g.handle (app.min.js:2)
(anonymous) @ editor.php?id_module=15&id_record=30:1148
dispatch @ app.min.js:2
g.handle @ app.min.js:2

Questo invece è quello che esce nel error_log del ftp:

[Thu Dec 20 14:39:43.266696 2018] [:error] [pid 30519] [client 5.152.152.206:52947] [client 5.152.152.206] ModSecurity:  [file "/etc/httpd/conf/modsecurity.d/rules/tortix/modsec/10_asl_rules.conf"] [line "202"] [id "340007"] [rev "46"] [msg "Atomicorp.com WAF Rules: Generic Path Recursion denied"] [data "/../,ARGS:file"] [severity "CRITICAL"] Access denied with code 403 (phase 2). Pattern match "(?i)(?:\\\\x5c|(?:%(?:2(?:5(?:2f|5c)|%46|f)|c(?:0%(?:9v|af)|1%1c)|u(?:221[56]|002f)|%32(?:%46|F)|e0%80%af|1u|5c)|\\\\/))(?:%(?:2(?:(?:52)?e|%45)|(?:e0%8|c)0%ae|u(?:002e|2024)|%32(?:%45|E))|\\\\.){2}(?:\\\\x5c|(?:%(?:2(?:5(?:2f|5c)|%46|f)|c(?:0%(?:9v|af)|1%1c)| ..." at ARGS:file. [hostname "mmcomputer.it"] [uri "/pannello/assets/dist/pdfjs/web/viewer.html"] [unique_id "XBubn9PII6W-bBnF6He9LwAAABY"], referer: http://mmcomputer.it/pannello/editor.php?id_module=15&id_record=30

Adesso non capisco perchè i due errore sono comunicanti.

Attendo vs,
Grazie

**Comment by Dasc3er** [comment]
@MALEFIKOIT Prova a cancellare la cache del browser.

**Comment by MALEFIKOIT** [comment]
Sisi, come dicevi tu, cancellato cache e cookie ed ha funzionato
correttamente.

Grazie mille!

Il giorno sab 29 dic 2018, 13:25 Thomas Zilio <notifications@github.com> ha
scritto:
