### ISSUE TITLE
ADDON: Calcolo ripartizione IVA per beni significativi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#404]
Questa sarebbe un'aggiunta importante ai fini fiscali: è un po' complesso spiegarlo, però il calcolo è semplice. Qualora venga applicata in fattura l'IVA agevolata, la normativa fiscale vigente prevede che per l'installazione di beni significativi (caldaie, trattamento aria, sanitari e rubinetterie, alza carichi e ascensori) venga applicata in parte l'aliquota massima corrente (adesso 22%) sulla differenza tra imponibile del bene significativo e l'imponibile totale della manodopera di installazione e i materiali inerenti all'installazione stessa.
Faccio un esempio:
(A) Installazione caldaia totale € 2.000,00
(B) Costo della caldaia € 1.500,00
(C) Manodopera e materiale di installazione € 500,00
IVA agevolata al 10%
IVA bene significativo 22%
Calcolo dell'imponibile IVA al 22% --> 1500 - 500 = 1000 oppure 2000 - (500 (C) + 500 (parte di B che corrisponde a C)
L'IVA al 22% viene applicata a un'imponibile di € 1000,00 e quella al 10% a un'imponibile di € 1000,00

Per chiarimenti visitare [https://www.fiscoetasse.com/approfondimenti/13170-beni-significativi-2018-la-guida-dell-agenzia.html](url)

**Comment by idraulicadueci** [comment]
Non credo, dato che è decreto ministeriale del 29 dic 1999 riconfermato con la legge finanziaria del 2018. Infatti riguarda un'ampia fetta delle ditte artigiane installatrici (ascensoristi, frigoristi, idraulici, serramentisti). 
Quello che ti posso dire è che io personalmente, nel gestionale che ho utilizzato fino ad ora, utilizzo un metodo che restituisce correttamente i valori nel riepilogo IVA:

**Prospetto di calcolo imponibili per l'applicazione IVA ai sensi del DM 29 dicembre 1999

(A)Importo totale dell'opera = ?
(B)Totale beni significativi = ?
(C)Totale manodopera e materiale di installazione = ?

Differenza su cui applicare l'IVA al 22% (B-C) = ? 

ISTRUZIONI:

1) Inserire i dati richiesti
2) Inserire il valore C nella casella "Prezzo senza IVA", 1 come quantità e nella casella IVA l'aliquota 10%
3) Creare una riga solo descrizione inserendo 1 come quantità, il valore negativo di C e nella casella IVA l'aliquota massima vigente.
4) Cancellare le istruzioni.

In caso di differenza B-C negativa:

1) Inserire i dati richiesti, specificando accanto al valore B-C "Il costo della manodopera e materiale di installazione superano quello dei beni significativi, pertanto l'aliquota IVA al 10% viene applicata sull'intera fattura"
2) Inserire il valore di B negativo nella casella "Prezzo senza IVA" e nella casella IVA l'aliquota massima vigente.
3) Creare una riga solo descrizione inserendo 1 come quantità e il valore di B positivo e nella casella IVA l'aliquota del 10%.

NB Le righe indicanti i beni significativi devo avere aliquota massima, mentre manodopera e materiale di installazione al 10%.**

Il problema sta nel fatto che in OSM non è possibile inserire un prezzo negativo, e quindi mi ritrovo alla fine l'imponibile a cui si sommano i valori utilizzati nel metodo per far tornare l'IVA

**Comment by loviuz** [comment]
E' un caso particolare che abbiamo gestito tramite un plugin personalizzato (per un paio di clienti) nel quale, una volta inseriti gli importi di manodopera e beni significativi, vengono inserite in fattura 1 o 2 righe con iva diversa in base ai criteri di quel decreto. E' un caso però abbastanza specifico che per ora non intendavamo inserire in release, perché ci sono molti altri casi particolari che è da dedidere se e come includere in OSM.
