### ISSUE TITLE
Calcolo totale fatture

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#405]
Con il commit a371c24f4b2be24c6ae2e1ba14aeffad5d5ae609 è stato introdotto un nuovo sistema di calcolo per i totali delle Fatture, basato sulle nuove classi Eloquent al fine di centralizzare la logica relativa.
I test automatici presenti confermano la correttezza degli importi per i casi di base (righe multiple, con sconti percentuali e in euro, con sconto globale).
E' però necessario controllare che i calcoli relativi siano completamente funzionanti anche nei casi in cui vi è l'applicazione aggiuntiva di Rivalsa INPS e Ritenuta d'Acconto in combinazione agli sconti globali, poichè per il momento non sono presenti controlli indipendenti.

Una volta controllato questo sistema, sarà possibile include il totale del documento nelle Fattura Elettronica senza dover riportare individuare e copiare la logica dal funzionamento di base.

**Comment by loviuz** [comment]
Appena verificato e completato con l'integrazione della rivalsa inps (cassa previdenziale) con il commit 3b4ca8f22cb66bbd3629c72cf7197ba5d6733279

**Comment by loviuz** [comment]
Ulteriori correzioni qui: 39da35401b76ffeed5f593d40b6f657d2f653e77
