### ISSUE TITLE
Miglioria: Cartella Custom

### ISSUE THREAD

**Issue by lexen77** [devcode-it/openstamanager#406]
Cartella Custom non funziona per:
 templates/registo iva
 templates/fatturato
 templates/scadenzario

**Comment by Dasc3er** [comment]
Puoi indicare nel dettaglio quale procedura hai utilizzato per personalizzare queste stampe?

**Comment by lexen77** [comment]
Ciao Dasc3er,
ho creato la cartella custom e messo dentro i file che mi interessava modeificare es header, body ecc. ecc.
Ho notato che il software li ignora chiamandosi sempre quelli della cartella principale.
Premetto però che provengo dalla versione 2.4.3 e non vorrei che l'aggiornamento alla 2.4.4
abbia scaturito questo errore.

**Comment by Dasc3er** [comment]
Non su tratta di un errore: le stampe in questione utilizzano la versione vecchia del sistema di generazione pdf, e quindi i file da te indicato non sono validi. Controlla la struttura della stampa e replicala completamente, poi inizia a fare modifiche.

**Comment by Dasc3er** [comment]
@lexen77 Sei riuscito a completare la personalizzazione?

'
