### ISSUE TITLE
Bug: Impossibile creare fattura da ordine

### ISSUE THREAD

**Issue by lexen77** [devcode-it/openstamanager#407]
Salve,
ho aggiornato la versione 2.4.3 a 2.4.4 
ed ho notato che nella sezione ordine di vendita se provo a creare una fattura tramite il pulsante in alto a destra, mi carica l'area per la creazione della fattura ma alla fine non la crea. 
Ho provato anche la versione installata su https://demo.osmcloud.it/ e  da lo stesso problema.

Ecco il messaggio di errore nel log 

[2018-12-26 20:36:11] Logs.ERROR: Uncaught Exception BadMethodCallException: "Call to undefined method Illuminate\Database\Query\Builder::getNumero()" at C:\xampp\htdocs\fpm\vendor\illuminate\database\Query\Builder.php line 2445
{"url":"/fpm/editor.php?id_module=14","ip":"::1","http_method":"POST","server":"localhost","referrer":"http://localhost/fpm/editor.php?id_module=24&id_record=384","uid":"55fbea2"}

**Comment by Dasc3er** [comment]
@lexen77 Per risolvere il problema è sufficiente modificare la riga 13 del file **modules/fatture/modutil.php**
con il seguente codice:
```php
    return Fattura::getNextNumero($data, $dir, $id_segment);
```
e la riga 24 in 
```php
    return Fattura::getNextNumeroSecondario($data, $dir, $id_segment);
```

**Comment by lexen77** [comment]
Salve,
ho effettuato la modifica da voi consigliata e purtroppo non funziona ugualmenti :( .
Il messaggio del log di errore è sempre lo stesso:

[2019-01-11 02:06:35] Logs.ERROR: Uncaught Exception BadMethodCallException: "Call to undefined method Illuminate\Database\Query\Builder::getNumero()" at C:\xampp\htdocs\fpm\vendor\illuminate\database\Query\Builder.php line 2445
{"url":"/fpm/editor.php?id_module=14","ip":"::1","http_method":"POST","server":"localhost","referrer":"http://localhost/fpm/editor.php?id_module=24&id_record=670","uid":"2f47f3d"}
