### ISSUE TITLE
Inclusione di file da moduli disattivati

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#408]
Nei vari moduli, quando viene incluso un file, viene utilizzato il metodo filepath per l'inclusione di file esterni, ad esempio nel file **actions.php** delle fatture:

`include_once` Modules::filepath('Ordini cliente', 'modutil.php');

Se il modulo "Ordini cliente" è disattivato, il modulo delle fatture dà errore eseguendo qualsiasi operazione, perché al termine di **actions.php** delle fatture vengono utilizzati dei metodi dichiarati nel file modutil.php di **Ordini cliente**.

@Dasc3er, secondo te è possibile far restituire comunque a filepath() il percorso?

**Comment by Dasc3er** [comment]
@loviuz L'errore in questione dovrebbe essere un semplice *warning* o *notice* e quindi non dovrebbe causare problemi...

**Comment by Dasc3er** [comment]
Se invece intendi risolvere i problemi relativi all'utilizzo di funzioni poi non presenti, si potrebbero includere automaticamente tutti i file **modutil.php** di tutti i moduli e plugin dal **core.php** ed evitare di conseguenza malfunzionamenti vari...

@loviuz Procedo così?

**Comment by loviuz** [comment]
non male così, almeno ci sono sempre tutte le funzioni disponibili
