### ISSUE TITLE
Problema generazione codice intervento

### ISSUE THREAD

**Issue by gabrielepiccinnu** [devcode-it/openstamanager#41]
Aggiungevo alcuni interventi completati dell'anno 2016 per dei test e il mi è stato restituito il sequente errore:
![image](https://user-images.githubusercontent.com/25913492/31483598-5060d0a4-af2d-11e7-84cb-791812bc2ef3.png)
Potrebbe essere un mio problema nel DB o un bug?

**Comment by Dasc3er** [comment]
L'errore viene generato dal fatto che esiste già un codice intervento "10", e quindi la creazione dell'intervento fallisce.
Il problema è che il codice al momento viene generato in modo automatico basandosi sul formato indicato nelle impostazioni e sui codici inseriti in precedenza, e sembra che per qualche motivo la procedura fallisca.

**Comment by fpsoftware** [comment]
@Dasc3er notavo lo stesso problema anche sulla demo online del nostro sito, è un bug.

**Comment by gabrielepiccinnu** [comment]
Pensavo di aver combinato qualcosa nella mia installazione :simple_smile:

**Comment by gabrielepiccinnu** [comment]
Si crea una sorta di discordanza in fase di creazione. Dal mio DB rilevo questo:
![image](https://user-images.githubusercontent.com/25913492/31484544-f581c536-af30-11e7-909d-ff4bb397e09c.png)

![image](https://user-images.githubusercontent.com/25913492/31484556-02665096-af31-11e7-9402-f8b9b7ccd288.png)

**Comment by Dasc3er** [comment]
Il problema è presente tra le righe 220-221 del file _modules/interventi/actions.php_, dove viene aggiunto al codice più grande un'unità attraverso il metodo **get_next_code**.
In questo caso, potrebbe essere la query che individua il codice più grande ad essere erronea, oppure il metodo stesso che crea il nuovo codice...

**Comment by lepool** [comment]
Da quello che ho notato nella query c'è un confronto con la lunghezza del codice e quella del formato impostato. Se nelle impostazioni generali viene cambiato il valore lunghezza del campo del codice, potrebbero risultare problemi con nuovi interventi. La stessa cosa vale se un codice intervento supera la lunghezza impostata nelle impostazioni.

**Comment by Dasc3er** [comment]
@gabrielepiccinnu Il problema dovrebbe essere stato risolto con il commit 8ae46049d3ff5c2c4caa4b99431b16c52b491f61.
In pratica, sono stati rimossi i controlli sulla lunghezza del codice; la procedura ora prende semplicemente l'ultimo codice generato.

**Comment by gabrielepiccinnu** [comment]
Perfetto, sto testando e funziona tutto. Chiuderei l'issue a questo punto.
