### ISSUE TITLE
MIGLIORIA: STATI DI ATTIVITÀ disponibili per gli altri documenti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#411]
## Comportamento richiesto

Spostare il modulo STATI DI ATTIVITÀ sotto a IMPOSTAZIONI, per renderli disponibili per tutti gli altri documenti, magari inserendo degli stati standard e non modificabili come PAGATO, FATTURATO che abbiano di default il flag COMPLETATO. Infatti sarebbe opportuno che i documenti non siano modificati e come loro tutti i documenti relazionati (es. DDT, ORDINI, PREVENTI, ecc. fatturati), con la dicitura "Questo documento è fatturato e non può essere modificato".

## Comportamento attuale

Attualmente nei preventivi lo stato PAGATO o CONCLUSO non proteggono il documento da modifiche

**Comment by Dasc3er** [comment]
@idraulicadueci Stiamo lentamente procedendo alla standardizzazione degli stati tramite alcuni flag di base (**completato**, **fatturato**, **annullato**), ma è corretto mantenere gli stessi separati tra i diversi documenti.
