### ISSUE TITLE
Totale documento non presente nella fattura elettronica

### ISSUE THREAD

**Issue by osm-gc** [devcode-it/openstamanager#412]
Con l'attuale versione stabile 2.4.4 mi non viene inserito il totale documento della fattura nel file xml
Ho provato ogni tipo di fattura con dettaglio con articoli o solo come riga.
Di seguito un esempio
[IT08801151211_19Lyc.xml.pdf](https://github.com/devcode-it/openstamanager/files/2727702/IT08801151211_19Lyc.xml.pdf)

**Comment by Dasc3er** [comment]
Previsto nella prossima versione 2.4.5.
