### ISSUE TITLE
Uso del codice a barre Zebra

### ISSUE THREAD

**Issue by DoctorAlfred** [devcode-it/openstamanager#416]
Gentilissimi, come si potrebbe gestire il lettore di codice a barre della zebra con il gestionale?

**Comment by Dasc3er** [comment]
Nella versione di base del gestionale non è presente la lettura di codici a barre e qr code, e quindi neanche una gestione dei lettori dedicati.
Questa funzione potrebbe essere implementato in futuro a livello generale, ma nel frattempo considera l'acquisto di una personalizzazione, se ne hai bisogno.
