### ISSUE TITLE
BUG prima nota

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#417]
Dopo l'inserimento di una fattura di acquisto
Test su OSM 2.4.5

[error.log](https://github.com/devcode-it/openstamanager/files/2731769/error.log)

**Comment by Dasc3er** [comment]
@idraulicadueci Il problema è causato da un aggiornamento manuale ad una versione in sviluppo.
Dovresti poterlo risolvere con la seguente query:
 ```sql
UPDATE `zz_views`
SET `query` = '(SELECT numero_esterno FROM co_documenti WHERE id = iddocumento)'
WHERE `name`= 'Rif. fattura';
 ```
