### ISSUE TITLE
Calcolo errato ritenuta di acconto

### ISSUE THREAD

**Issue by xxfuma85xx** [devcode-it/openstamanager#419]
## Comportamento richiesto

Devo emettere una fattura con ritenuta di acconto del 23% sul 50% dell'imponibile.
Creo la ritenuta di acconto con percentuale 23 nella colonna percentuale e 50 nella colonna indetraibile.
Vorrei che mi calcolasse la ritenuta di acconto sul 50% dell'imponibile, sia se imposto la ritenuta di acconto generica nella fattura, sia se la imposto sulle singole righe.
Leggendo la issue #309 vedo che la ritenuta verrà impostata direttamente solo genericamente sulla fattura e poi si potranno selezionare le righe a cui applicarla singolarmente.

## Comportamento attuale

Al momento viene calcolata la ritenuta di acconto sul totale dell'imponibile senza tenere conto della percentuale di indetraibile inserita nella tabella delle ritenute di acconto.

## Possibile soluzione

Se mi date una dritta su dove viene fatto il calcolo della ritenuta faccio una patch. Sto diventando matto a trovarlo sto calcolo...

## Passi per riprodurre il comportamento

1. Crea una nuova ritenuta di acconto valorizzando il campo "indetraibile" diverso da 0
2. Crea nuova fattura.
3. Aggiungi una riga con la ritenuta di acconto appena creata.
4. Il totale calcolato è su tutto l'imponibile e non su (imponibile - percentuale indetraibile dell'imponibile).

## Contesto

* Modulo: Fatture
* Versione del progetto: 2.4.4
* Versione PHP: 5.6.31
* Tipo di server: Debian - Apache

**Comment by xxfuma85xx** [comment]
L'ho trovato, è diverso nella versione 2.4.4 ma ho fatto la modifica anche all'ultima.
Ho fatto una branch ma mi ha preso anche l'altra pull request. Più tardi faccio la PR della sola modifica.

**Comment by Dasc3er** [comment]
@xxfuma85xx Non credo che la colonna indetraibile sia stata creata con lo scopo di gestire la percentuale di imponibile su cui applicare la ritenuta.
Per esempio, nella nuova ritenuta contributi è utilizzata la colonna **percentuale_imponibile**.
@loviuz

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager

**Comment by xxfuma85xx** [comment]
In questo periodo non riesco a metterci mano ma quando ho segnalato il problema non esisteva la colonna percentuale_imponibile che è stata aggiunta nella 2.4.6.

**Comment by Dasc3er** [comment]
La colonna in questione non esiste ancora per le ritenute d'acconto, proprio per questo sto sentendo gli altri sviluppatori.

**Comment by lucasalva87** [comment]
La colonna percentuale_imponibile è stata prevista per le tabelle co_ritenutaacconto e la nuova co_ritenuta_contributi.

La colonna indetraibile invece è prevista invece solo per co_ritenutaacconto . Anche se non è mai stata utilizzata.

**Comment by Dasc3er** [comment]
Solo che percentuale_imponibile non c'è sulle ritenute, quindi è da aggiungere.

**Comment by Dasc3er** [comment]
Completato con il commit ba4aa13b0106f0b720056ce92e25e38fd9186228.
