### ISSUE TITLE
Malfunzionamento della prima nota

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#42]
Non funziona la primanota da fattura di vendita.  Il valore nel campo "Dare" dopo che viene confermato con "Aggiungi" risulta "0" . Il problema sta nella condizione "if" nel file actions nel modulo "primanota" .
Quando invece una primanota viente modificata la funzione è corretta.

**Comment by Dasc3er** [comment]
Il problema era già stato segnalato con l'issue #25, e dovrebbe essere stato risolto con il commit

**Comment by lepool** [comment]
@Dasc3er 
Ho notato che nella versione HEAD che mi sono scaricato sul mio server era ancora presente l'errore.

**Comment by Dasc3er** [comment]
@lepool, adesso il problema dovrebbe essere stato risolto in modo completo (commit 7d2fed121fe91aea9ba00eb659e0342b2f0294c1).

**Comment by lepool** [comment]
@Dasc3er 
Ho provato a installare OSM dalla versione Branch master. Il problema persiste ancora. Ma è possibile che il [commit 7d2fed1](https://github.com/devcode-it/openstamanager/commit/7d2fed121fe91aea9ba00eb659e0342b2f0294c1) non viene applicata nella versione Branch master?

**Comment by Dasc3er** [comment]
@lepool, il commit in questione è stato fatto esclusivamente sulla branch master, quindi dovrebbe essersi aggiornato tutto...
Eventualmente potresti controllare che siano stati aggiornati i singoli file modificati per risolvere il problema, perchè provando in locale con la procedura che prima non funzionava ora i risultati sono corretti...

**Comment by lepool** [comment]
@Dasc3er 
Purtroppo se faccio il clone della repository la prima nota non funziona. Se applico la modifica della commit [a65fccf](https://github.com/devcode-it/openstamanager/commit/a65fccf6b8a6f7b37e018b18ca003bf019fda510)  manualmente la prima nota da fattura funziona. Qualcosa nella repository comunque non quadra, perche nella versione master tali modifiche non ci sono.

**Comment by Dasc3er** [comment]
@lepool Allora, inizialmente il problema era stato risolto con il commit a65fccf6b8a6f7b37e018b18ca003bf019fda510, ma a seguito della tua segnalazione ho effettuato il commit 7d2fed121fe91aea9ba00eb659e0342b2f0294c1 che dovrebbe aver risolto il bug in modo completo (c'era un problema nella conversione dei numeri uguali a zero).

Attualmente, con la versione master della repository il funzionamento è corretto nei miei controlli in locale...
Potresti altrimenti indicare passo per passo il modo in cui si verifica il problema nella tua installazione?

@lucasalva87 Potresti controllare se il bug è ancora presente anche da voi?

**Comment by lepool** [comment]
eseguo :
- git clone https://github.com/devcode-it/openstamanager.git
- poi mi scarico tutto il necessario come descritto nel fil INSTALLAZIONE.md
- configuro il file config.inc.php
- installo il database di prima installazione e tutte le prime impostazioni azienda ecc.
- creo un cliente con un intervento abbinato e in sequito creo la fattura.
- la prima nota da fattura mi riporta prima l'importo corretto. Appena confermo il valore della prima nota va a 0.
Non saprei dove ho sbagliato, premetto che non sono un esperto di GIT. A mio avviso è stata presa una versione intermedia per il bugfix.

**Comment by loviuz** [comment]
ho provato ieri durante una sessione di test, ma non riesci a riprodurre l'errore. riesci a caricare uno screenshot di dove vedi lo zero?

**Comment by lepool** [comment]
Che strano, oggi con un' installazione fresca tutto ok. Meglio cosi! :+1: 
Avrò sbagliato qualcosa. Scusatemi :sweat_smile:
