### ISSUE TITLE
<DatiOrdineAcquisto> su export fattura elettronica

### ISSUE THREAD

**Issue by ria0** [devcode-it/openstamanager#420]
Non riesco ad includere i dati dell'ordine cliente nella fattura elettronica.
Ho visto che nel modulo exportFE/FatturaElettronica.php c'è la funzione ma non so come mai nel xml non risulta.

**Comment by Dasc3er** [comment]
Ciao @ria0 ,
gli unici campi per ora da noi supportati nel campo DatiOrdineAcquisto sono CodiceCIG, CodiceCUP e IdDocumento dedicati alla fatturazione verso pubblica amministrazione.
Intendi dire che questi campi non sono presenti anche se dovrebbero, o te ne servirebbero di altri?

**Comment by ria0** [comment]
Ciao @Dasc3er ,
grazie per la risposta. Come non detto, è una richiesta per una e-fattura b2b. Verificherò con il cliente se necessita espressamente questi tag o se è sufficiente il riferimento dell'ordine in DettaglioLinee. Grazie.

**Comment by Dasc3er** [comment]
@ria0 Lentamente stiamo implementando anche tutti i campi secondari, quindi se hai suggerimenti indicali pure 😄
