### ISSUE TITLE
Spostare automaticamente lo stato del contratto in "Attesa di pagamento" solo se l'intero importo viene fatturato

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#421]

**Comment by Dasc3er** [comment]
I cambiamenti più recenti sull'automatizzazione del cambio di stato prevedono l'utilizzo degli stati 'In lavorazione',  'Parzialmente fatturato' e 'Fatturato' in base all'effettivo stato di evasione del documento.
@lucasalva87 Posso considerare chiusa questa issue?

**Comment by lucasalva87** [comment]
Certamente ;) grazie
