### ISSUE TITLE
Errore aggiunta articolo nell'intervento

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#424]
Aggiungendo un articolo nell'ordine, il risultato è questo errore:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ritenutaacconto' in 'field list' (SQL: insert into `mg_articoli_interventi` (`idintervento`, `prezzo_vendita`, `iva`, `sconto`, `ritenutaacconto`, `rivalsainps`, `created_at`) values (1, NAN, NAN, 0, NAN, NAN, 2019-01-10 18:23:22))

**Comment by Dasc3er** [comment]
@loviuz Non sono riuscito a replicare il problema...

**Comment by loviuz** [comment]
scusa, ho scritto "ordine". in realtà il problema è aggiungendolo all'intervento
