### ISSUE TITLE
Aggiunta modulo fatture internazionali

### ISSUE THREAD

**Issue by andry2895** [devcode-it/openstamanager#431]
Salve vorrei sapere se esiste un modo per avere una fattura in inglese.
Se c'è un modulo per le fatture estere, oppure se si puo tradurre quella parte.

grazie mille.
Andrea.

**Comment by Dasc3er** [comment]
Quello di cui hai bisogno è:
- tradurre la schermata del gestionale in inglese?
- generare una stampa tradotta in inglese?
- generare una fattura elettronica di riferimento per uno stato estero (se ha senso)?

Tutti questi casi sono certamente possibile, ma poiché non di utilità generale non verranno implementati nella versione di base del gestionale.
Se ne hai bisogno, considera l'acquisto di un pacchetto di personalizzazione dal sito ufficiale.

PS: scusa per il ritardo di risposta. Ti consiglio di utilizzare il forum ufficiale per domande di questo tipo, poiché teniamo GitHub per la parte tecnica e spesso tralasciamo le domande non relative.
