### ISSUE TITLE
 Export FE - Utilizzo delle 4 cifre decimali per i prezzi

### ISSUE THREAD

**Issue by aambrogini** [devcode-it/openstamanager#434]
## Comportamento richiesto

Quando si esporta una fattura elettronica utilizzando 4 cifre decimali per i prezzi si ottiene un errore nel file xml in quanto i valori del prezzo unitario delle righe vengono normalizzati a due decimali ed il totale della riga quindi non viene calcolato correttamente ed il file viene scartato dall'sdi

## Comportamento attuale

Errato inserimento valore PrezzoUnitario in DettaglioLinea, vengono inseriti prezzi in formato con due decimali, si dovrebbero inserire tutte le unità decimali interessate altrimenti il calcolo della riga non risulta essere corretto e lo sdi rifiuta il file xml

## Possibile soluzione

In FatturaElettronica.php nel metodo prepareForXML troviamo la formattazione dei decimali per normalizzare i valori a due cifre decimali, si dovrebbe modificare il comportamento e gestire il caso riportato, inoltre si dovrebbe gestire anche il campo Arrotondamento per eventuali sconti e nei dati di riepilogo

## Passi per riprodurre il comportamento

1. Impostare 4 cifre decimali per i prezzi
2. Creare una fattura con valori significativi (es. prezzo riga 1.234)
3. Esportare la FE e controllare il risultato

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Plugin FE
* Versione del progetto: 2.4.5
* Versione PHP: 7.0
* Tipo di server: Ubuntu 16.04

**Comment by lucasalva87** [comment]
Ho provato a seguire le indicazioni ma la fattura viene correttamente validata.

**Comment by Dasc3er** [comment]
Il codice effettua già l'arrotondamento a 4 cifre per i campi _['Quantita', 'PrezzoUnitario', 'PrezzoTotale']_, mentre per gli altri procede ad arrotondare a 2 cifre.
