### ISSUE TITLE
Pulsante "consuntivo interno" per i consuntivi 

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#436]
Con il pulsante "consuntivo interno" vengono presi costo orario dei tecnici e prezzo di acquisto specificato nelle varie righe generiche / articoli (al posto di addebito orario e prezzo di vendita com'è attualmente).

![contratti openstamanager 17](https://user-images.githubusercontent.com/30728163/51111148-501fc400-17fb-11e9-852e-7734c16154a1.png)

Da fare per contratti e preventivi.

**Comment by Dasc3er** [comment]
La stampa Consuntivo interno è stata implementata.
