### ISSUE TITLE
BUG: Nuova fattura di vendita / preventivo non inserisce automaticamente il numero progressivo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#439]
All'inserimento di una nuova fattura, non viene inserito il numero progressivo.

OSM 2.4.5

**Comment by lucasalva87** [comment]
Stesso problema anche per i preventivi

**Comment by lucasalva87** [comment]
calcola sempre 0001/2019

**Comment by idraulicadueci** [comment]
Me lo fa solo con le fatture di vendita, però a me dà il campo vuoto, senza alcun progressivo; nei preventivi di vendita il problema tuo non si presenta

**Comment by Dasc3er** [comment]
@lucasalva87 Forse il problema di @idraulicadueci è già stato risolto nei commit dopo la release...
Riguardo quello delle fatture, era causato da una variabile sbagliata.

**Comment by idraulicadueci** [comment]
OK. Ora sembra tutto a posto.
