### ISSUE TITLE
[Miglioria] Aggiunta delle priorità nel modulo "Attività"

### ISSUE THREAD

**Issue by gabrielepiccinnu** [devcode-it/openstamanager#44]
Nel modulo "Attività" sarebbe secondo me, interessante poter aggiungere la priorità ad ogni attività

**Comment by fpsoftware** [comment]
ciao Gabriele, solitamente si crea uno stato attività "URGENTE" con il relativo colore.
Per esempio se gestisco il classico stato "DA PIANIFICARE" andrei a creare un secondo stato "DA PIANIFICARE URGENTE".

Logicamente è una soluzione molto soggettiva, in 8 anni abbiamo seguito aziende che offrono "assistenza" di ogni tipo e trovare la soluzione "standard" per tutti è praticamente impossibile.

**Comment by fpsoftware** [comment]
Perdona la domanda, ma tu che tipo di assistenza stai gestendo con OSM ?
per esempio: assistenza informatica, caldaie, impianti elettrici, etc...

**Comment by gabrielepiccinnu** [comment]
@fpsoftware Assistenza informatica. Si capisco molto bene per quanto riguarda le soluzioni "standard".

**Comment by fpsoftware** [comment]
altrimenti per gestire le "urgenze" solitamente proponiamo un modulo aggiuntivo per gestire i ticket, ovvero le richieste di intervento, quindi un passo prima dell'intervento vero e proprio. Su questo modulo puoi inserire la "richiesta urgente" che poi diventa un'attività sul calendario pianificata/completata/fatturata. 
Certo, si aggiunge un passaggio in più al flusso di lavoro ma in questo modo la situazione è ancora più completa e rispecchia ancora di più la realtà!
