### ISSUE TITLE
Import FE non considera ritenuta acconto

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#441]
L'importazione delle fatture elettroniche non considera la ritenuta d'acconto e quindi non crea la fattura di acquisto correttamente. Da verificare anche la rivalsa inps.

**Comment by Dasc3er** [comment]
@loviuz Il problema dovrebbe essere stato risolto alcune versione fa con il passaggio ad Eloquent anche per la fatturazione elettronica...
