### ISSUE TITLE
MIGLIORIA: Salvataggio dati modulo prima di inserire articoli

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#443]
## Comportamento richiesto

Alla pressione del tasto aggiungi articolo, tecnico, ecc. che si appoggiano su altre maschere di input, dare automaticamente il comando di salvataggio

## Comportamento attuale

Se non clicco SALVA e vado ad aggiungere un articolo, un tecnico, ecc., i dati inseriti precedentemente vanno perduti

OSM attuale 2.4.5

**Comment by Dasc3er** [comment]
Una procedura simile è stata implementata per l'aggiunta righe delle fatture, in modo da salvare le modifiche apportate prima di far inserire una riga.

**Comment by Dasc3er** [comment]
Riferimento per issure simile: #636
