### ISSUE TITLE
Errore di logica nella visualizzaione delle fatture xml.

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#444]
Quando visualizzo l'xml della fattura di acquisto (ma in modo più generale per tutti gli allegati .xml) tramite apposito tastino dovrebbe andare a prendere l'xml allegato e non interrogare il db. Potrebbero esserci infatti delle differenze tra l'xml allegato e quanto trasposto nel documento. Senza considerare il fatto che l'xml potrebbe venire allegato anche in un intervento o nella gestione documentale.

![fatture di acquisto openstamanager 12](https://user-images.githubusercontent.com/30728163/51308806-47213380-1a43-11e9-9019-67b514ff4bbf.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Ho risolto aggiungendo un file apposito per la visualizzazione degli allegati.
Potrà essere utilizzato come generalizzazione in futuro.

**Comment by lucasalva87** [comment]
Ho visto @Dasc3er, direi semplicmente perfetto! :+1:
