### ISSUE TITLE
Rivalsa INPS

### ISSUE THREAD

**Issue by Massi1975** [devcode-it/openstamanager#448]
## Comportamento richiesto

Mi aspetto che nella fattura elettronica venga inserita la rivalsa INPS, mentre adesso essa la trovo su quella cartacea, ma non su quella elettronica.

## Comportamento attuale

Nella fattura cartacea trovo la voce e i calcoli relativi alla rivalsa INPS del 4%, ma non trovo ne la voce ne il calcolo nella fattura elettronica, pur riportando il giusto totale fattura

## Possibile soluzione

Ritengo che il problema si verifichi al momento della generazone della fattura elettronica: sembra che il programma non contenpli l' inserimento della voce e dell' importo, perche alla fine in totale fattura torna.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: openstamanager fatturazione elettronica
* Versione del progetto: 2.4.4
* Versione PHP: 7.1.11
* Tipo di server: hosting linux su aruba

**Comment by Massi1975** [comment]
Ho notato che lo stesso problema lo si evidenzia sulla versione di prova che si trova sull' homepage di openstamanager: impostando la ritenuta di acconto e la rivalsa INPS nella fattura cartacea tutto ok, ma nella fattura elettronica compare la ritenuta di acconto, ma non la rivalsa INPS, il totale comunque torna con la fattura cartacea; quanto accade è esattamente quanto riscontro io.

**Comment by Massi1975** [comment]
Si è evinto che il problema è conosciuto ed è stato riasolto con la 2.4.5, ma io installandola ho visto esplodere il mio OSMDopo l' aggiornamento collegandomi mi arriva il seguente errore:
"Fatal error: Cannot redeclare rimuovi_articolo_dapreventivo() (previously declared in /web/htdocs/www.massimoirrati.com/home/contabosmb/modules/contratti/modutil.php:10) in /web/htdocs/www.massimoirrati.com/home/contabosmb/modules/preventivi/modutil.php on line 26"
Forse, almeno nel mio caso meglio attendere la prossima versione, comunque si sapeva che la 2.4.5 ha molti bug.
Quanto scrivo è chiaramente il mero racconto di quanto mi è accaduto, spero sia utile a chi sa lavorare a questo magnifico progetto che costantemente sa stupire per le sue performance.
Grande Openstamanager!!

**Comment by Dasc3er** [comment]
@Massi1975 Dovresti poter risolvere il problema rimuovendo il file **modules/contratti/modutil.php**
