### ISSUE TITLE
Importazione contratto in fattura di vendita: campi mancanti

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#449]
![fatture di vendita openstamanager 41](https://user-images.githubusercontent.com/30728163/51697267-b7155800-2007-11e9-9723-b2d38a3299ca.png)

In fase di importazione del contratto nella fattura non vengono riportati i valori quali: qta, um, prezzo unitario, iva
Versione 2.4.6

**Comment by Dasc3er** [comment]
@lucasalva87 Dovrebbe essere risolto, anche se non ho fatto particolari modifiche.
