### ISSUE TITLE
Bootstrap 4 e AdminLTE 3

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#451]
Ciao,
Bootstrap 3 è ormai datato e non è più supportato dai loro sviluppatori. Si potrebbe pensare ad un passaggio a Bootstrap 4, molto più moderno sul punto di vista stilistico e al passo con i tempi.

**Comment by maicol07** [comment]
Sembra che lo sviluppatore non aggiorni il codice (branch v3-dev) da luglio...
A quanto pare è già disponibile una versione alpha: https://github.com/almasaeed2010/AdminLTE/releases/tag/v3.0.0-alpha.2

**Comment by Dasc3er** [comment]
È necessario attendere pa versione stabile.

**Comment by Dasc3er** [comment]
Riferimento al piano di rilascio di AdminLTE 3: https://github.com/almasaeed2010/AdminLTE/issues/710

In aggiunta: https://github.com/almasaeed2010/AdminLTE/issues/2046

**Comment by maicol07** [comment]
Non riesco a capire bene lo stato della v3. L'issue principale è stato chiuso mentre gli altri sono rimasti aperti. Inoltre, la v3 è ancora in sviluppo e l'ultimo rilascio è una alpha...

**Comment by Dasc3er** [comment]
@maicol07 Se vuoi puoi provare a creare una branch (ti consiglio della 2.5) 
e aggiornare la base HTML del gestionale (cartella resources/views/twig) poiché gli autori rochiedono un po' di testing: https ://github.com/ColorlibHQ/AdminLTE/issues/2078#issuecomment-490869710

In alternativa prossimamente provo a controllare la base del codice e aggiornarla di conseguenza. Dubito comunque che ci saranno novità prima della fine dell'estate.

**Comment by maicol07** [comment]
@Dasc3er stasera proverò ad aggiornare

**Comment by Dasc3er** [comment]
In teoria dovresti usare la branch 2.5 esistente...
Però mi sono reso conto che la documentazione sulla 2.5 e la nuova organizzazione delle strutture è inesistente, quindi potresti perdere tanto tempo per niente.

**Comment by maicol07** [comment]
Credo di aver capito come funziona. Twig non l'ho mai usato ma sembra abbastanza semplice. Una cosa: quali sono i file CSS/JS di AdminLTE?

**Comment by Dasc3er** [comment]
@maicol07 Prova a controllare il commit https://github.com/devcode-it/openstamanager/commit/c22a7708588898928d6abcdf78d3b59e9c8abd3b.
Ho implementato la versione di base di AdminLTE 3 con Bootstrap 4: ovviamente saranno necessari numerosi test per controllare che tutto funzioni correttamente.

**Comment by maicol07** [comment]
Mi potresti mandare la cartella vendor che non riesco a crearla (problemi con yarn)?

**Comment by Dasc3er** [comment]
In alternativa puoi utilizzare npm: npm run develop-OSM

**Comment by maicol07** [comment]
@Dasc3er ho fatto dei test e ho notato alcuni problemi:

- Configurazione iniziale:
    - Pulsanti troppo vicini alle caselle di testo soprastanti:
![immagine](https://user-images.githubusercontent.com/9463142/57933621-100e4200-78be-11e9-9c5e-be48abaec6cd.png)
- Maschera di inserimento:
   - Caselle troppo vicine:
![immagine](https://user-images.githubusercontent.com/9463142/57933934-c7a35400-78be-11e9-9502-24ead5af1ddf.png)
- Menu laterale:
    - Le voci di menu principali che hanno una pagina (ad esempio **Anagrafiche**) non si aprono. Le voci secondarie e le voci primarie che non hanno una pagina ma aprono solo la lista delle voci secondarie funzionano perfettamente.

Appena ho un pò di tempo vedo di iniziare a sistemare qualche bug

**Comment by Dasc3er** [comment]
Ti sconsiglio comunque di perderci tempo, visto che la versione è ancora in sviluppo e certamente molti fix non sono ancora stati rilasciati.
Inoltre la versione 2.5 non vedrà l'inizio dei lavori effettivo prima di settembre...

**Comment by maicol07** [comment]
Ok, fatemi sapere quando inizieranno effettivamente i lavori. Comunque siamo sulla buona strada 👍

**Comment by Dasc3er** [comment]
La versione 3 di AdminLTE si sta lentamente avvicinado al rilascio: è uscita una prima beta.

**Comment by maicol07** [comment]
Ormai AdminLTE 3 è prossima al rilascio: è uscita la 4a versione RC (_Release Candidate_ )

**Comment by maicol07** [comment]
Versione stabile di AdminLTE 3 uscita (anzi, la 3.0.1): https://github.com/ColorlibHQ/AdminLTE/releases/tag/v3.0.1

**Comment by Dasc3er** [comment]
La versione 2.5 (per ora rinominata nella branch future) è in ogni caso molto lontana dal rilascio, e gli assets non verranno aggiornati separatamente.

**Comment by Dasc3er** [comment]
Aggiornamento degli assets per la branch future completato.

**Comment by maicol07** [comment]
@Dasc3er non sarebbe meglio identificare il prossimo major update con 3.0? Introduce numerosi cambiamenti maggiori alla struttura interna, oltre che ad un design migliorato (grazie a Bootstrap 4 e admin lte 3)

**Comment by maicol07** [comment]
@Dasc3er i lavori per la futura versione (2.5 o 3.0?) quando inizieranno effettivamente? Ci sono numerosi bug aperti nella 2.4, ma viene data priorità a nuove funzionalità (che potrebbero essere benissimo inserite nella prossima _major release_) invece che sistemarli...

La branch future mi sembra già solida nella sua struttura, anche se anche lei piena di bug (giustamente, dato che si tratta di una versione completamente nuova)

**Comment by lucasalva87** [comment]
Attualmente lavoriamo per una 2.4.18. La 2.5 è in previsione ma non credo a brevissimo. Purtroppo la cosa non è così semplice: riceviamo ogni giorno richieste anche da clienti che ci supportano economicamente e ci permettono di continuare con lo sviluppo del gestionale che magari ci chiedono nuove funzionalità alle quali diamo priorità; un pò alla volta chiuderemo anche i bug che sono rimasti. Nel breve infatti valutiamo prima di tutto una versione 2.4.x davvero stabile e poi passeremo al rilascio di una beta per la 2.5.

**Comment by Dasc3er** [comment]
È sempre possibile contribuire alla versione future: per controllare quali sono alcuni degli obiettivi di base puoi controllare la roadmap. 
A livello pratico, sospetto inoltre non ci sarà un aggiornamento a bootstrap 4 fino alla versione successiva alla future.

**Comment by Dasc3er** [comment]
Devo comunque dire che i bug al momento segnalati su GitHub sono nella maggior parte dei casi relativi a funzionalità da rivedere (lavoro in corso sulla master con le versioni 2.4.x) oppure a problemi noti in aggiornamento che si verificano in installazioni specifiche.

**Comment by Dasc3er** [comment]
@maicol07 Segnalo anche che al momento la branch più aggiornata sulle modifiche previste per la versione 2.5 è https://github.com/devcode-it/openstamanager/tree/slim.
La branch **future** infatti implementa al momento un numero eccessivo di cambiamenti, che sono stati di difficile aggiornamento sulla base della **master**. Di conseguenza, nella branch slim sono stati replicati alcuni dei cambiamenti principali, introducendo un miglior livello di retro-compatibilità per semplificare la transizione al team di sviluppo principale. Le modifiche introdotte in **future** e **laravel-mix** saranno quindi riportate in **slim** con delle dovute correzioni per essere più graduali.

**Comment by maicol07** [comment]
Magari dato che il problema è la retrocompatibilità si potrebbe rendere la versione `future` un aggiornamento semiautomatico, caricando l'intera cartella dei file e aggiornando il database automaticamente (non passando dall'aggiornamento dei file come avviene al momento con i file `*.php` della cartella `updates`).
In questo modo si avrebbe una reinstallazione semipulita della nuova versione.
Sì potrebbe comunque mantenere l'attuale branch master per evenetuali bug fix mentre le versioni future otterranno tutte le nuove funzionalità (un po' come il sistema di mantenimento delle versioni di Laravel)

**Comment by Dasc3er** [comment]
Probabilmente non mi sono espresso bene: la retrocompatibilità è necessaria soprattutto per agevolare la vita a tutti gli sviluppatori del progetto.
Il progetto non è abbastanza vasto da giustificare una struttura più complessa come quella indicata.

**Comment by maicol07** [comment]
Perchè Slim e Twig invece che utilizzare Laravel e Blade (dato che si utilizzano già alcuni componenti di Laravel)?

**Comment by Dasc3er** [comment]
Perchè Laravel, come gli altri framework completi esistenti, richiederebbe una ristrutturazione completa del progetto, con un utilità pratica piuttosto ridotta rispetto al lavoro richiesto per l'aggiornamento.
Slim è piuttosto basilare e limitato, pertanto è una buona scelta per separare le logiche del gestionale in modo graduale.
Twig è migliore di Blade a livello di sicurezza intrinseca, oltre che template di default per Symfony ed è molto semplice da usare standalone.

Ti segnalo #710 per alcuni dettagli pratici.
