### ISSUE TITLE
Bug su movimenti articoli con note di accredito

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#454]
Riporto una segnalazione da un utente:
> Nel movimento magazzino ogni volta che apro e salvo la nota di credito visualizzo:
"carico magazino da nota di credito nr. 2/33" (cioe' il numero di documento emesso dal mio fornitore) di nr. 2 quantita' ma scritte piu volte;
> 
> quindi la stessa riga in movimento replicata per 2 o 3 o 4 volte (quindi la quantita' aumenta, ad esempio, di +4 o di +6 o di +8...)
> 
> Preciso che per l' articolo che ho reso al fornitore ho fatto un ddt in uscita e l'ho evaso.

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere stato risolto con l'aggiornamento del passaggio dati tra documenti, ma necessita di conferma.
