### ISSUE TITLE
DOMANDA: Nome e cognome in anagrafiche

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#455]
I campi NOME e COGNOME presenti in anagrafica sono disabilitati. Si tratta di un bug nella mia installazione oppure è previsto lo stato attivo nelle prossime versioni? Lo chiedo perché i dati sono richiesti nella FE qualora si tratti di persona fisica o di ditta individuale. 

Versione attuale 2.4.5

**Comment by idraulicadueci** [comment]
Ho controllato: i campi vengono resi abilitati al momento che si cancella la ragione sociale. Questo però non è corretto, perché anche per le ditte individuali devono essere indicati il nome e cognome del titolare. 
Una soluzione sarebbe quella di legare l'abilitazione dei due campi all'inserimento del codice fiscale; infatti le società hanno solo la partita IVA, mentre privati e ditte individuali hanno il codice fiscale, oltre nell'ultimo caso la partita IVA.

**Comment by Dasc3er** [comment]
I campi nome e cognome sono utilizzati esclusivamente per la fatturazione elettronica al momento.

**Comment by idraulicadueci** [comment]
La fattura elettronica va fatta anche a soggetti privati, anche se non la ricevono sul sistema di interscambio e comunque anche a ditte individuali che invece sì.

**Comment by Dasc3er** [comment]
@idraulicadueci I campi Nome e Cognome sono stato implementati **esclusivamente** per la fatturazione elettronica: se l'anagrafica deve essere indicata tramite Denominazione si usa la Ragione Sociale, altrimenti Nome e Cognome.
Per le ditte individuali si applica lo stesso ragionamento: se in FE devono essere indicate tramite Denominazione si usa la Ragione Sociale, altrimenti Nome e Cognome.
