### ISSUE TITLE
fattura elettronica problemi risolti

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#456]
RISOLTO: elenca i ddt per articolo nelle fatture elettroniche differite

    protected static function getDatiBeniServizi($fattura)
    {
        $documento = $fattura->getDocumento();

        $database = database();

        $result = [];

        // Righe del documento
        $righe_documento = $fattura->getRighe();
		$indiceriga=0;
        foreach ($righe_documento as $numero => $riga) {
			$indiceriga++;
            $riga['subtotale'] = abs($riga['subtotale']);
            $riga['qta'] = abs($riga['qta']);
            $riga['sconto'] = abs($riga['sconto']);

            $prezzo_unitario = $riga['subtotale'] / $riga['qta'];
            $prezzo_totale = $riga['subtotale'] - $riga['sconto'];

            $iva = $database->fetchOne('SELECT `percentuale`, `codice_natura_fe` FROM `co_iva` WHERE `id` = '.prepare($riga['idiva']));
            $percentuale = floatval($iva['percentuale']);
			

			//INERISCE LA RIGA DEL DDT DI RIFERIMENTO ARTICOLO SE ESISTE
			if($riga['idddt']>0){
				$dettaglio = [
					'NumeroLinea' => $indiceriga,
				];				
				$ddt = $database->fetchOne('SELECT `data` FROM `dt_ddt` WHERE `id` = '.prepare($riga['idddt']));
				$dettaglio['Descrizione']='DDT  n. '.$riga['idddt'].' del '.$ddt['data'];
				$dettaglio['Quantita'] =1;
				$dettaglio['PrezzoUnitario']=0;
				$dettaglio['PrezzoTotale'] = 0;
				$dettaglio['AliquotaIVA'] = $percentuale;
			
				$result[] = ['DettaglioLinee' => $dettaglio,];
				
				$indiceriga++;
			}

            $dettaglio = [
                'NumeroLinea' => $indiceriga,
            ];			
			
            if (!empty($riga['tipo_cessione_prestazione'])) {
                $dettaglio['TipoCessionePrestazione'] = $riga['tipo_cessione_prestazione'];
            }

**Comment by Dasc3er** [comment]
Per proporre modifiche del codice crea delle Pull Request.
