### ISSUE TITLE
accettazione file fattura elettronica

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#457]
RISOLTO: in fatturaself non viene accettato il file xml generato per una non conforme intestazione.

    public function toXML()
    {
        if (empty($this->xml)) {
            $this->errors = [];

            $cliente = $this->getCliente();

            // Inizializzazione libreria per la generazione della fattura in XML
			//opzione stylesheet crea rifiuto in fatturaself 
            //$fattura = new FluidXml(null, ['stylesheet' => 'http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/fatturaPA_v1.2.1.xsl']);
			$fattura = new FluidXml(null);
			
            // Generazione dell'elemento root
			$fattura->namespace('p', 'http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2');
            $root = $fattura->addChild('p:FatturaElettronica', true);
            $rootNode = $root[0];

            // Completamento dei tag
            // $attributes = [
                // 'versione' => ($cliente['tipo'] == 'Ente pubblico') ? 'FPA12' : 'FPR12',
                // 'xmlns:ds' => 'http://www.w3.org/2000/09/xmldsig#',
                // 'xmlns:xsi' => 'http://www.w3.org/2001/XMLSchema-instance',
                // 'xsi:schemaLocation' => 'http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/Schema_del_file_xml_FatturaPA_versione_1.2.xsd',
            // ];
			
			//xsi:schemaLocation  non corretto
			
            $attributes = [
                'versione' => ($cliente['tipo'] == 'Ente pubblico') ? 'FPA12' : 'FPR12',
                'xmlns:ds' => 'http://www.w3.org/2000/09/xmldsig#',
                'xmlns:xsi' => 'http://www.w3.org/2001/XMLSchema-instance',
                'xsi:schemaLocation' => 'http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 fatturaordinaria_v1.2.xsd',
            ];

**Comment by Dasc3er** [comment]
Per proporre modifiche del codice crea delle Pull Request.
