### ISSUE TITLE
BUG non risolto fattura elettronica

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#458]
le fatture con più scadenze di pagamento, per esempio bonifico 60/90 o riba 30/60 etc., sono gestite correttamente come documenti. Elencate correttamente nella preparazione file xml.
Il risultato del file xml scaricato riporta sempre solamente l'ultima delle date in elenco.

**Comment by pubblisoft** [comment]
le scadenze multiple di pagamento si vedono in tutti i documenti e tutte le viste tranne che all'interno del file xml generato.

**Comment by lucasalva87** [comment]
#475

**Comment by cicalo** [comment]
vero!! ho letto e fatto un pò di prove 2.4.4 ed ho lo stesso problema. in attesa della nuova versione avete per caso una soluzione tampone?
grazie

**Comment by Dasc3er** [comment]
In realtà sembra che il problema sia nella fase di esportazione: è questo che intendi @pubblisoft ?
Nel caso, concentriamo la discussione in #472.
Se invece il problema è relativo alla mancata importazione delle scadenze: #475.
