### ISSUE TITLE
Pagamenti con carta di Credito

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#459]
## Comportamento richiesto

Sarebbe utile che ci fosse scadenza del pagamento "un giorno fisso del mese successivo alla data di pagamento. Comportamento tipico degli acquisti con carta di credito. Acquisto oggi, pago il 10 del mese successivo

## Comportamento attuale
E' permesso solo il data fattura fine mese

**Comment by Dasc3er** [comment]
@leonardocalabretta Questa funzione non è prevista negli prossimi sviluppi, ma vedremo di implementarla se è di utilità comune.
Per il momento, se hai urgenza ed è per te fondamentale, valuta l'acquisto di un pacchetto di personalizzazione.

**Comment by leonardocalabretta** [comment]
Ok ti ringrazio :-) per ora sono riuscito a farmi la modifica da solo :-)

**Comment by Dasc3er** [comment]
Eventualmente se vuoi proporla come modifica ufficiale prova a fare una Pull Request, altrimenti passerà parecchio tempo prima che venga definitamente implementata (perché numerose altre priorità al momento)...

**Comment by loviuz** [comment]
@leonardocalabretta in realtà dovresti già poterlo farlo tramite la gestione dei pagamenti in questo modo:
![immagine](https://user-images.githubusercontent.com/1647128/66717062-34227080-edd5-11e9-9dd6-536170d53eaf.png)
