### ISSUE TITLE
Statistiche : non funziona la rappresentazione fatturato/entrate 

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#46]
![errore_statistiche](https://user-images.githubusercontent.com/32035706/32350907-01646ad8-c01c-11e7-8667-07c0e32be94a.png)
![lista_fatture](https://user-images.githubusercontent.com/32035706/32350908-0187c320-c01c-11e7-9e0b-1be7dcd887aa.png)
![prima_nota](https://user-images.githubusercontent.com/32035706/32350909-01a8659e-c01c-11e7-9a79-27dba86fb8fb.png)

Qui il file Database:

[osmtest.sql.zip](https://github.com/devcode-it/openstamanager/files/1439561/osmtest.sql.zip)

**Comment by fpsoftware** [comment]
@lepool grazie per la segnalazione abbiamo notato anche noi questo problema, lo risolviamo nella sessione di test in programma la prossima settimana!

**Comment by loviuz** [comment]
aggiornato. abbiamo rimoso "entrate" e "uscite" che non avevano molto senso in questa schermata, eventualmente faremo delle statistiche a parte. qui abbiamo lasciato solo "Fatturato" e "Acquisti"
