### ISSUE TITLE
Regimi fiscali per Cassa e non per competenza

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#461]
## Comportamento richiesto

Nei regimi dei minimi, al fine di imputare correttamente la fattura di acquisto/vendita, è necessario tenere conto della data di pagamento/ricezione del pagamento.

Es. Se acquisto e pago con carta nel mese di dicembre, quella fattura è da "conteggiare" nell'anno successivo

Es. Se emetto fattura nell'anno 2018 ma questa mi viene saldata nell'anno 2019, la fattura è da "conteggiare" nell'anno 2019. E' una funzione abbastanza importante in quanto va anche ad inficiare per esempio nei conteggi del fatturato dell'anno (quindi anche nelle stampe) 

## Comportamento attuale

Non si può indicare la data di incasso

**Comment by leonardocalabretta** [comment]
Anche qua per ora sono riuscito a farmi la modifica in autonomia :-)

**Comment by Dasc3er** [comment]
Se vuoi proporla ufficialmente puoi provare a creare una Pull Request

**Comment by loviuz** [comment]
@leonardocalabretta rinnovo l'invito, sarebbe molto utile vedere se la modifica è integrabile in modo strutturato in OSM :-)
