### ISSUE TITLE
scadenza 60ggfm spostata di un giorno

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#463]
applicando una scadenza di 66 d.f. f.m. ad un documento generato il 31/01, la scadenza generata non è ultimo giorno di 31/3, bensì 01/04.

**Comment by Dasc3er** [comment]
@pubblisoft Indica il pagamento utilizzato se è previsto in quelli di default, altrimenti potrebbe trattarsi di un tuo errore di configurazione.
Di fatto, il calcolo è corretto con pagemento **Bonifico 60gg d.f.f.m.**.
