### ISSUE TITLE
aggiunto tipo doc. pro-forma

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#464]
aggiunto record nella tabella: co_tipidocumento
id=11
descrizione=Fattura pro-forma
dir=entrata
codice=TD01

**Comment by Dasc3er** [comment]
Quale è la issue?

**Comment by pubblisoft** [comment]
l'impossibilità di stampare una fattura con intestazione pro-forma, invece che differita di vendita. Tale voce viene visualizzata nell'intestazione del documento generato.

**Comment by pubblisoft** [comment]
e' una funzionalità del programma? cosa intendi per sezionale?

**Comment by pubblisoft** [comment]
La richiesta delle aziende è una stampa di una normale fattura, dove nell'intestazione ci sia scritto pro-forma. La cosa più semplice è selezionare il tipo di stampa dal menù a tendina che elenca i tipi di fatture (immediata, differita, etc).

**Comment by lucasalva87** [comment]
Per ora le fatture pro-forma sono gestite con il sezionale apposito per motivi di anche legati al struttura del gestionale e logiche interne del software. Questo potrebbe essere un automatismo di facilitazione futuro sul quale ragionare. Ne prendiamo nota.
