### ISSUE TITLE
Domanda su prima nota

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#467]
Salve,
Quando premo il pulsante Aggiungi prima nota da una fattura di acquisto viene visualizzata questa schermata:
![schermata_2019-02-01-12-00-35-202](https://user-images.githubusercontent.com/9463142/52119552-affad500-2619-11e9-8e0d-05478553fe74.jpeg)
È normale che il conto del fornitore viene indicato automaticamente in dare e invece quello del cliente (che sarei io) viene riportato in Avere?
Avete anche una stima per il rilascio della versione 2.4.6?
Grazie

**Comment by maicol07** [comment]
@devcode-it/openstamanager

**Comment by lucasalva87** [comment]
Sì è corretto. La 2.4.6 verrà rilasciata entro sabato.

**Comment by maicol07** [comment]
Cioè il fornitore (in fattura di acquisto) deve dare e io devo avere?

**Comment by lucasalva87** [comment]
Esatto, devi avere, quindi ti entrano in cassa i soldi presi dal fornitore (dare)

**Comment by maicol07** [comment]
Ok, grazie
