### ISSUE TITLE
errore aggiornamento da 2.4.5

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#468]
dalla versione 2.4.5 (dd38d855)

l'accesso alla lista fatture di vendita genera un popup  con il seguente errore

DataTables warning: table id=main_53 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by Dasc3er** [comment]
@pubblisoft Devi fornire i log dell'errore (dalla cartella **logs/**)...

**Comment by pubblisoft** [comment]
passaggi: 
1)installazione 2.4.4
2)mediante voce aggiornamenti si è installata la 2.4.5

poi ha dato l'errore

**Comment by Dasc3er** [comment]
Prova ad eseguire le seguenti query:
```sql
-- Fix icon_Inviata Fatture di vendita per errore subquery
UPDATE `zz_views` SET `query` = '(SELECT GROUP_CONCAT(DISTINCT `name` SEPARATOR \'\r\n \') FROM zz_operations INNER JOIN zz_emails ON zz_operations.id_email = zz_emails.id WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = \'Fatture di vendita\') AND op = \'send-email\' AND id_record = co_documenti.id ORDER BY zz_operations.created_at DESC LIMIT 1)' WHERE `zz_views`.`name` = 'icon_title_Inviata' AND id_module = (SELECT id FROM zz_modules WHERE name = 'Fatture di vendita');

UPDATE `zz_views` SET `query` = 'IF((SELECT GROUP_CONCAT(DISTINCT `name` SEPARATOR \'\r\n \') FROM zz_operations INNER JOIN zz_emails ON zz_operations.id_email = zz_emails.id WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = \'Fatture di vendita\') AND op = \'send-email\' AND id_record = co_documenti.id ORDER BY zz_operations.created_at DESC LIMIT 1) IS NOT NULL, \'fa fa-envelope text-success\', \'\') ' WHERE `zz_views`.`name` = 'icon_Inviata' AND id_module = (SELECT id FROM zz_modules WHERE name = 'Fatture di vendita');
```

**Comment by pubblisoft** [comment]
provato. lista fatture ok
ma quando provo ad apprirne una: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'osm.co_rivalsainps' doesn't exist
[error.log](https://github.com/devcode-it/openstamanager/files/2821822/error.log)

**Comment by Dasc3er** [comment]
@pubblisoft Evidentemente hai effettutato delle modifiche manuali, cercando di passare alla versione 2.4.6

**Comment by pubblisoft** [comment]
provo a reinstallare il tutto, 2.4.4 e poi, tramite il pulsante 2.4.5. da zero. vedo cosa succede.

**Comment by pubblisoft** [comment]
ho installato 2.4.4.
Oggi provo a fare aggiornamento dall'area aggiornamento del programma.

**Comment by lucasalva87** [comment]
Invito per queste tipologie di segnalazioni o per altre ad utilizzare il nostro `https://www.openstamanager.com/forum/`

Grazie.
