### ISSUE TITLE
Fattura elettronica non viene caricata

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#470]
Alcune fatture elettroniche restituiscono il messaggio di fattura già importata anche se non è stata inserita.
Esempi di fatture che non vengono caricate: 

[IT07155170157_1KS89.zip](https://github.com/devcode-it/openstamanager/files/2822055/IT07155170157_1KS89.zip)

**Comment by Dasc3er** [comment]
Questo avviene perchè il codice attuale non riesce a gestire completamente tutte le codifiche possibili che si possono utilizzare durante la firma.
In particolare, bisognerebbe considerare l'utilizzo della funzione _openssl_pkcs7_verify_ di PHP per vedere se si riescono a gestire anche questi file particolari.

**Comment by Dasc3er** [comment]
Lo avevo già testato senza successo.

**Comment by maicol07** [comment]
Ho dato un'occhiata alle funzioni di `openssl_pkcs7`, ma c'è bisogno di certificati e chiavi personali che non so dove si possano ottenere (vedi `[openssl_pkcs7_decrypt](http://php.net/manual/en/function.openssl-pkcs7-decrypt.php)`)

**Comment by maicol07** [comment]
@Dasc3er questo è solo per la verifica dell'XML o funziona anche per il salvataggio (c'è scritto uso commerciale nel repo di github ma non vedo nessuna tabella dei prezzi)?
https://forum.italia.it/t/decodifica-firma-cades-bes-php/7903

**Comment by Dasc3er** [comment]
Credo entrambi, ma non ha senso utilizzare un servizio esterno per procedure che basta approfondire per completarle...

**Comment by maicol07** [comment]
Dopo un pò di ricerca credo di aver trovato degli script che potrebbero risolvere il problema: https://forum.italia.it/t/p7m-codificato/6470/87
Stasera li provo e vediamo...

**Comment by Dasc3er** [comment]
@maicol07 Sei riuscito a risolvere il problema?

**Comment by maicol07** [comment]
Ho implementato il codice, ma i test falliscono quando legge l'XML tramite SimpleXML

**Comment by maicol07** [comment]
@Dasc3er prova a vedere se riesci a capire perchè simplexml ritorna False. Non avendo mai usato questa libreria non mi è semplicissimo capire subito i messaggi di errore XML.
Ti passo quel che ho fatto fino ad ora: https://pastebin.com/QgT4zEpY

**Comment by Dasc3er** [comment]
@maicol07 Credo tu abbia frainteso il problema: il file XML è illeggibile.
Per quanto si facciano le sostituzioni previste, il file XML resta illeggibile.

L'unica speranza è che, in qualche modo, sia possibile prendere i contenuti dell'XML e interpretarli attraverso la funzione **openssl_pkcs7_verify**, che dovrebbe occuparsi della conversione: prima di questa operazione non è possibile leggere il file, e quindi SimpleXML va in errore.

**Comment by lepool** [comment]
Il file xml si puo decodificare con stripcslashes. Non capisco però il motivo per il quale un file XML venga codifcato in questa maniera.

**Comment by Dasc3er** [comment]
@lepool il file XML è firmato, e dunque la procedura da te indicata non è utilizzabile.

@maicol07 avevo tentato l'applicazione della funzione openssl_pkcs7_verify su diverse versioni del file: quello normale, quello trasformato in smime e alcune varianti. Senza successo. Eventualmente nei prossimi giorni provo di nuovo, se neanche tu riesci a completare la conversione.

**Comment by lepool** [comment]
Ma il secondo file a che serve?

**Comment by Dasc3er** [comment]
Esattamente, ma è necessario solo se si intende verificare la firma: nel nostro caso, si considera affidabile qualunque XML l'utente inserisca.
L'obiettivo della funzione è estrarre il Conte puramente XML dal file firmato.

**Comment by lepool** [comment]
Perciò serve nel casi di Maicol per verificare la firma del file p7m se ho capito bene. Solo che dal codice postato mi sembra che tutti i caratteri speciali simplexml non li gestisce.

**Comment by maicol07** [comment]
Quello che possiamo fare è estrarre un certificato di una fattura qualsiasi (i root certificate sono tutti uguali da quel che ho capito) anche usando openssl da linea di comando e poi utilizzarlo in openssl_pcks7_verify

**Comment by Dasc3er** [comment]
Riguardo i file caricati, sono riuscito ad interpretare il primo p7m convertendo il file originale (dal forum.italia) dalla codifica base64: il file da te passato è infatti illeggibile.
Per quanto riguarda il secondo file, mi sembra che non sia correttamente formattato, visto che contiene delle sintassi improbabili.

**Comment by maicol07** [comment]
Controllando gli XML delle fatture che mi sono arrivate che non sono state accettate nell'importazione la maggior parte sono tutti errori di sintassi nell'XML. Solo quella che ho inviato al primo post è veramente illeggibile

**Comment by Dasc3er** [comment]
@maicol07 Prova a testare la branch p7m: https://github.com/devcode-it/openstamanager/tree/p7m

Ecco il contenuto di prova, fornito dalla tua fattura iniziale **IT01879020517_jaFv5.xml.p7m**:
[p7m.zip](https://github.com/devcode-it/openstamanager/files/2860043/p7m.zip)
Il file _IT01879020517_jaFv5.xml.p7m_ è quello originale codificato in base64, quello _decodificato.p7m_ è quello che ci avevi fornito inizialmente per il problema, e _IT01879020517_jaFv5.xml_ è il risultato ottenuto dal file originale.
Come puoi osservare, per qualche motivo il file da te fornito (non l'originale) non è interpretabile, mentre quello originale lo è. Si potrebbe trattare di un malfunzionamento del codice, ma per il momento non ritengo.

Se hai altre informazioni da forum Italia (https://forum.italia.it/t/errore-importazione-fattura-elettronica-unexpected) sul funzionamento di **openssl_pkcs7_verify**, potrebbero tornarmi utili perchè in locale non riesco a farlo funzionare (ho provato con i certificati, senza e diverse varianti).

**Comment by maicol07** [comment]
Ho provato la branch p7m con 2 fatture ma mi restituiscono tutte e due l'errore:
`Errore: Start tag expected, '<' not found`

**Comment by Dasc3er** [comment]
@maicol07 Credo di aver individuato il problema: si tratta della codifica del file.
Il commit 8dcc7046 risolve i problemi di compatibilità con la maggior parte dei file finora acquisiti da noi; rimane il problema per alcuni che al posto di essere codificati in UTF-8 sono in Windows-1252 o altre codifiche particolari.
Purtroppo, non siamo in grado di gestire la conversione in PHP.

**Comment by Dasc3er** [comment]
Il sistema integrato nella branch **p7m** è ora stato inserito nella **master**. Non esistono altri metodi effettivi per intrepretare il formato P7M.
