### ISSUE TITLE
Collegamento ddt - articolo in FE

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#471]
formalmente ogni rigo della fattura di vendita merce può avere un ddt di origine associato.
Nel file xml della fattura elettronica non venivano riportati i ddt relativi alle righe articolo inserite.
La spedizione dei ddt nel file xml è obbligatorio, tramite il tag ddt apposito, altrimenti bisogna allegare al file i vari ddt.
La modifica risolve questo problema.

**Comment by Dasc3er** [comment]
@pubblisoft Quale modifica?

**Comment by pubblisoft** [comment]
quella che avevo inserito come post in issues e poi in pull requests

**Comment by Dasc3er** [comment]
Descrivi a parole la modifica, per favore.

**Comment by pubblisoft** [comment]
file fatturaelettronica.php  dalla riga 680 alla 695 è stata modificata come segue:

  // Righe del documento
    $righe_documento = $fattura->getRighe();
	$indiceriga=0;
    foreach ($righe_documento as $numero => $riga) {
		$indiceriga++;
        $riga['subtotale'] = abs($riga['subtotale']);
        $riga['qta'] = abs($riga['qta']);
        $riga['sconto'] = abs($riga['sconto']);

        $prezzo_unitario = $riga['subtotale'] / $riga['qta'];
        $prezzo_totale = $riga['subtotale'] - $riga['sconto'];

        $iva = $database->fetchOne('SELECT `percentuale`, `codice_natura_fe` FROM `co_iva` WHERE `id` = '.prepare($riga['idiva']));
        $percentuale = floatval($iva['percentuale']);
		

		//INERISCE LA RIGA DEL DDT DI RIFERIMENTO ARTICOLO SE ESISTE
		if($riga['idddt']>0){
			$dettaglio = [
				'NumeroLinea' => $indiceriga,
			];				
			$ddt = $database->fetchOne('SELECT `data` FROM `dt_ddt` WHERE `id` = '.prepare($riga['idddt']));
			$dettaglio['Descrizione']='DDT  n. '.$riga['idddt'].' del '.$ddt['data'];
			$dettaglio['Quantita'] =1;
			$dettaglio['PrezzoUnitario']=0;
			$dettaglio['PrezzoTotale'] = 0;
			$dettaglio['AliquotaIVA'] = $percentuale;
		
			$result[] = ['DettaglioLinee' => $dettaglio,];
			
			$indiceriga++;
		}

        $dettaglio = [
            'NumeroLinea' => $indiceriga,
        ];

**Comment by pubblisoft** [comment]
in questo modo il risultante file xml sarà per esempio:

.......
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>DDT  n. 5 del 2019-01-15</Descrizione>
        <Quantita>1.00</Quantita>
        <PrezzoUnitario>0.00</PrezzoUnitario>
        <PrezzoTotale>0.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <Descrizione>mouse ottico usb nero portatile per pulpiti macchine</Descrizione>
        <Quantita>4.00</Quantita>
....
....

**Comment by pubblisoft** [comment]
il file xml sarà del tipo:

...
...

>     <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>DDT  n. 5 del 2019-01-15</Descrizione>
        <Quantita>1.00</Quantita>
        <PrezzoUnitario>0.00</PrezzoUnitario>
        <PrezzoTotale>0.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <Descrizione>mouse ottico usb nero portatile per pulpiti macchine</Descrizione>
        <Quantita>4.00</Quantita>

> 
...
...

**Comment by Dasc3er** [comment]
Se l'obbiettivo è avere all'interno della descrizione il riferimento, è già stato aggiunto e sarà sulla prossima release.
Il problema non è il codice, ma la descrizione della richiesta.

**Comment by Dasc3er** [comment]
@pubblisoft Per ora è prevista il seguente funzionamento: se la riga è derivata da un ddt/ordine/preventivo/contratto viene riportata la seguente descrizione:
```
Descrizione riga
Rif. contratto num. 1 del 03/02/2018
```

E' quello che intendi?

**Comment by pubblisoft** [comment]
no, questo è il riferimento all'ordine. il ddt è relativo al trasporto dei singoli beni elencati in fattura. Normalmente ci sono più ddt per fattura, in quanto generata in via differita.

**Comment by Dasc3er** [comment]
@pubblisoft Quello che intendi quindi è la presenza del tag DatiDDT (2.1.8 di riferimento)?
Nel caso, sarebbe stato **molto meglio dirlo a parole da subito**, perchè come puoi notare non siamo riusciti a capire cosa volevi fino ad ora.

**Comment by Dasc3er** [comment]
In ogni caso non è possibile indicare l'origine della riga all'intero dello standard, a meno che non sia aggiunto il testo relativo (per esempio, _Rif. contratto num. 1 del 03/02/2018_).
