### ISSUE TITLE
Esportazione FE: pagamenti mancanti

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#472]
nel file xml non vengono riportate tutte le righe di pagamento, ma solo l'ultima.
Esempio: si decide un pagamento riba 30/60dffm.
Le scadenze sono 50% importo a 30gg e 50% importo a 60gg.
Nel file devono comparire entrambe le date, non solo quella a 60gg.

**Comment by lucasalva87** [comment]
Credo che il problema segnalato sia lo stesso discusso qui  #475, già risolto con la nuova versione di OSM.

**Comment by lucasalva87** [comment]
> 
> 
> questo è un file generato da un programma di fatturazione che funziona correttamente.
> [IT03947000240_2.zip](https://github.com/devcode-it/openstamanager/files/2823224/IT03947000240_2.zip)

Attenzione che il file `IT03947000240_2.xml` "generato da un programma di fatturazione funziona correttamente" una volta validato con lo strumento ufficiale dell'AdE restituisce gli errori che allego.

![fatturazione elettronica per la p a esito del controllo](https://user-images.githubusercontent.com/30728163/52162248-43dba800-26d1-11e9-89d9-03c75d8331a0.png)

Invito per queste tipologie di segnalazioni o per altre ad utilizzare il nostro `https://www.openstamanager.com/forum/`
Grazie.

**Comment by pubblisoft** [comment]
Ovviamente parlo dell'intestazione del file non del contenuto che ho parzialmente cancellato per non trasmettere all'esterno i nostri dati.

**Comment by Dasc3er** [comment]
@pubblisoft Ho appena controllato, e il problema non si verifica nella versione in sviluppo.
Dovrebbe quindi essere risolto con la prossima release.
