### ISSUE TITLE
errore accetazione file xml fe per formato

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#473]
con questa intestazione il caricamento nel portale di invio del commercialista il file viene accettato, con l'intestazione della versione 2.4.4. no.

<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" encoding="UTF-8" indent="yes" href="/assets/xsl/FatturaPrivati_v1.2.xsl"?>
<p:FatturaElettronica xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" versione="FPR12" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 fatturaordinaria_v1.2.xsd">
  <FatturaElettronicaHeader>

**Comment by pubblisoft** [comment]
il programma usato è di uno delle principali aziende italiane, costantemente attive nel seguire la FE, specializzate nel contabile.

**Comment by lucasalva87** [comment]
Nessun problema con l'intestazione, utilizzata e già testa con successo per invio delle FE da portali quali Aruba, Unimatica ecc..

**Comment by pubblisoft** [comment]
i file che vi ho allegato agli altri post, funzionano correttamente. hanno qualcosa di diverso immagino.
