### ISSUE TITLE
Registro vendite IVA

### ISSUE THREAD

**Issue by 27vivi** [devcode-it/openstamanager#474]
Quando viene emessa una nuova fattura di vendita, quando vado a stampare il registro iva delle vendite non mi appare il n° protocollo, il numero del documento e la data.
E' un problema solo mio?

**Comment by Dasc3er** [comment]
@27vivi Grazie mille per la segnalazione!
In effetti si trattava di un problema per il registro iva delle vendite, puoi trovare la soluzione al commit d57cb3f8.
