### ISSUE TITLE
Import FE: scadenze mancanti

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#475]
Quando si importa una fattura elettronica, le scadenze non vengono inserite e neanche riportate sulla scheda della fattura. Un modo per risolvere temporaneamente è segnare la fattura come bozza e poi ritrasformarla in emessa...

**Comment by Dasc3er** [comment]
@loviuz Questo non dovrebbe essere stato risolto con il commit 182098a8466eef99ceb97b8baf506d7b69922cd2?

**Comment by lucasalva87** [comment]
Esatto. E vengono riportate tutte le date in caso di pagamenti con più scadenze. Es 30/60 o 30/60/90 ecc...

**Comment by maicol07** [comment]
Con la 2.4.6 questo problema è quasi del tutto risolto: se si preme il pulsante SALVA dopo aver importato una fattura viene inserita una seconda scadenza:
![immagine](https://user-images.githubusercontent.com/9463142/52666446-9f4a3900-2f0e-11e9-95a2-5379ff6967fc.png)
Mentre se la fattura non ha nell'XML una scadenza già inserita viene riportato : 0,00 € come nell'immagine.

**Comment by Dasc3er** [comment]
@maicol07 Il problema dovrebbe essere risolto con i commit più recenti...
Rimane un problema da risolvere: è possibile che nella fattura XML vengano indicate le scadenze con gli importi ma senza le date: in questo caso è necessario decidere quale comportamento mantenere.
@devcode-it/openstamanager

**Comment by maicol07** [comment]
Confermo che il problema è stato risolto (farò ulteriori test per accertarmi che il problema sia stato risolto definitivamente)

**Comment by Dasc3er** [comment]
@maicol07 Con il commit 5a0ed167 le scadenze senza data prendono in considerazione la data attuale: questo è il comportamento che abbiamo scelto internamente,
