### ISSUE TITLE
BUG: Errore link documenti collegati ORDINE FORNITORE

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#477]
Creando un DDT da ORDINE FORNITORE, in DOCUMENTI COLLEGATI il link generato punta al modulo  FATTURE DI ACQUISTO invece che a quello dei DDT in entrata.

**Comment by lucasalva87** [comment]
@idraulicadueci, versione di OSM?

**Comment by idraulicadueci** [comment]
chiedo scusa, 2.4.5
