### ISSUE TITLE
Conversione proforma a fattura

### ISSUE THREAD

**Issue by kekkog** [devcode-it/openstamanager#478]
Ragazzi come scritto nell'altro post https://github.com/devcode-it/openstamanager/issues/466 .
Ho ancora il seguente problema, ho visto che avete chiuso la discussione ma non ho capito se ci sarà un fix o meno...neffrattempo vorrei fare downgrade mi sapreste indicare come gentilmente?

**Comment by Dasc3er** [comment]
Hai chiuso tu la issue...

**Comment by Dasc3er** [comment]
Per fare il downgrade è necessario rispristinare un backup della versione precedente, perdendo così gli ultimi dati.

Inoltre, Github è dedicato alle segnalazioni tecniche e ai contributi nello sviluppo: per segnalazioni e domande come questa sei pregato di usare il forum https://www.openstamanager.com/forum/, dove sono presenti molte indicazioni utili.

**Comment by Dasc3er** [comment]
@kekkog Il problema si è risolto?
