### ISSUE TITLE
Numerazione automatica

### ISSUE THREAD

**Issue by omar2kkb** [devcode-it/openstamanager#479]
Ho un problema con la numerazione di fatture, DDT e preventivi che purtroppo non è più automatica ma di default quando creo un nuovo documento viene impostata sempre a 1.

#

**Comment by Dasc3er** [comment]
Questo problema è noto e dovrebbe essere risolto a partire dalla prossima versione 2.4.6.

**Comment by Dasc3er** [comment]
Issue di riferimento: #422

**Comment by NicNal** [comment]
Nell'ultima versione in sviluppo il bug non è presente.
