### ISSUE TITLE
Mappatura tipo documento su segmento

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#480]
Un utente chiede se è possibile mappare il tido di documento (Fattura immediata di vendita, Fattura differita, Nota di credito, ecc) al sezionale. In questo modo, la nota di credito sarà possibile mapparla su un sezionale apposito, in modo da gestirla con una numerazione a parte.

**Comment by Pek5892** [comment]
Introdotto nelle versioni successive
![immagine](https://user-images.githubusercontent.com/102604205/201319732-e4194d0c-3c7d-4e80-a4c3-26b1b54c1595.png)
