### ISSUE TITLE
Il pulsante copia dati contabili durante l'import di un fattura elettronica

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#482]
## Comportamento richiesto

Il pulsante copia dati contabili dovrebbe inserire automaticamente l'IVA di ogni riga della fattura nella select relativa.

## Comportamento attuale

Il pulsante non fa niente.

## Possibile soluzione

Utilizzare lo stesso metodo per la visualizzazione dell'IVA sotto all'importo per inserirla in automatico nella select

## Passi per riprodurre il comportamento

Importare un XML in formato .xml.p7m.
Premere COPIA DATI CONTABILI

## Immagine

![immagine](https://user-images.githubusercontent.com/9463142/52667178-6dd26d00-2f10-11e9-83d0-c71487a1c7ae.png)

## Contesto

* Modulo: Fatture di acquisto
* Versione del progetto: 2.4.6
* Versione PHP: 7
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
@maicol07 Hai selezionato i dati contabili nella prima riga?

**Comment by maicol07** [comment]
Ah ok. Credevo che inseriva i dati dalla fattura. Ho fatto una prova e funziona compilando prima la prima riga. Magari si potrebbe mettere un avviso se la prima riga non è stata compilata.
Chiudo.

**Comment by Dasc3er** [comment]
E' scritto **Copia dalla prima riga**...

**Comment by maicol07** [comment]
Sì ma non so perchè pensavo dalla prima riga dell'XML... 🤣
