### ISSUE TITLE
Partita IVA estera

### ISSUE THREAD

**Issue by infotrend** [devcode-it/openstamanager#483]
https://github.com/devcode-it/openstamanager/blob/f419db587200709c71f6eca3982f1f07e971f993/modules/anagrafiche/actions.php#L94

Se la partita IVA è UK (GB + 9 numeri) viene trasformata in GBGB + 9 numeri.

**Comment by pecunia-pools** [comment]
Soluzione trovata:
`$partita_iva = strlen($partita_iva) == 11 && is_numeric(substr($partita_iva,0,1))? $anagrafica->nazione->iso2.$partita_iva : $partita_iva;`

**Comment by Dasc3er** [comment]
@infotrend Una soluzione più generale potrebbe essere:
```
        $partita_iva = is_numeric($partita_iva) ? $anagrafica->nazione->iso2.$partita_iva : $partita_iva;
```

Cosa ne pensi?

PS: se sei interessato a contribuire maggiormente, potresti approfondire l'utilizzo delle Pull Request di GitHub 😸

**Comment by Dasc3er** [comment]
@infotrend Puoi confermare che con le modifiche del commit 0ef7f7ad09b64c8ce90278b51199b7c9073d78ad il problema è risolto?
