### ISSUE TITLE
Procedura di aggiornamento

### ISSUE THREAD

**Issue by kekkog** [devcode-it/openstamanager#484]
Salve, ho scaricato la versione nuova 2.6

Quando provo a fare l'update dalla sezione aggiornamento, seleziono l'archivio compresso ma non effettua l'aggiornamento. C'è un'altra modalità per aggiornare?

**Comment by Dasc3er** [comment]
@kekkog Consulta la documentazione ufficiale: https://devcode-it.github.io/openstamanager/2.4.2/guide/configurazione/aggiornamento/

**Comment by kekkog** [comment]
Si conosco la procedura, ho provato anche con il comando force ma non fa
nulla

Il giorno gio 14 feb 2019 alle ore 18:37 Thomas Zilio <
notifications@github.com> ha scritto:

**Comment by Dasc3er** [comment]
@kekkog Descrivi i passaggi effettuati e il comportamento del software.

**Comment by kekkog** [comment]
Quando mi reco su aggiornamento scelgo tramite scegli file l'archivio con l'aggiornamento scaricato da github, quindi premo su carica. Compare l'ingranaggio di caricamento per qualche secondo dopodichè scompare l'ingranaggio e non cambia nulla

**Comment by kekkog** [comment]
ho provato a sovrascrivere da ftp, mi è uscito aggiornare tabella è si è
bloccato.

[image: image.png]

Il giorno gio 14 feb 2019 alle ore 18:43 Thomas Zilio <
notifications@github.com> ha scritto:

**Comment by kekkog** [comment]
![immagine](https://user-images.githubusercontent.com/47228963/52807081-de04fe00-308a-11e9-8098-cf0117d0372d.png)

**Comment by Dasc3er** [comment]
Stai utilizzando pa versione in sviluppo, e non la 2.4.6.

**Comment by kekkog** [comment]
Mi puoi girare il link per piacere, quello giusto ho perso tutto quello che
avevo fatto come posso ripristinare

Il giorno gio 14 feb 2019 alle 20:09 Thomas Zilio <notifications@github.com>
ha scritto:

**Comment by Dasc3er** [comment]
Devi aggiornare agli ultimi commit e fare ripartire l'aggiornamento: dovresti poter accedere nuovamente, ma ci potrebbero essere dei comportamenti inattesi.
Non devi **mai** scaricare la versione in sviluppo, e ti consiglio di fare un backup prima di aggiornare.

Altrimenti devi ripristinare un backup e *"aggiornare alla 2.4.6 scaricabile dalle release**.

**Comment by kekkog** [comment]
Ok sono riuscito a ripristinare e si è risolto anche il bug che non
visualizzava più le fatture convertite da proforma.
Ho scaricato la versione 2.6 dal sito, rimosso da update l'SQL 2.7 ed è
andato tutto liscio. Volevo solo chiederti se c'è un modo per integrare la
trasmissione tramite sdi aruba anche pagando, avete fatto un ottimo lavoro

Il giorno gio 14 feb 2019 alle ore 21:12 Thomas Zilio <
notifications@github.com> ha scritto:

**Comment by Dasc3er** [comment]
Certamente, per questo devi scriverci un'email: si trattava di un modulo pagamento che stiamo sviluppando.
