### ISSUE TITLE
BUG : Con debug attivo e utilizzo api per lettura calendario errore php

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#485]
Se ho attivo la funzione di debug ho una schermata bianca con l'utilizzo della api per la funzione lettura calendario con una app esterna.

attivando in core.php   ini_set('display_errors', 1) esce il seguente errore
 Fatal error: Call to a member function parse() on null in /var/www/https/osm/src/Filter.php on line 143

Per riprodurre il problema 
1. chiamata https://_il_mio_url_/api/?token=_il_mio_token_&resource=sync

Facendo alcune prove ho trovato che il problema si presenta in core.php alla riga 114.

Se disattivo il debug funziona tutto. 

* Versione del progetto: 2.4.6 (R5ff8fe84)
* Versione PHP: Version 5.6.39-0+deb8u1
* Tipo di server: debian stretch con apache2

**Comment by lepool** [comment]
Mi dimenticavo di dire che non ho nessun logfile.

**Comment by Dasc3er** [comment]
@lepool Grazie mille per la segnalazione!
