### ISSUE TITLE
BUG ritenuta in export fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#486]
Creando una fattura da un intervento (per anagrafica in cui è stata specificata "Nessuna ritenuta") e esportando la fattura, quando importo l'XML su gestionale esterno, gli articoli vengono indicati correttamente senza ritenuta, mentre manodopera, viaggio, diritto di intervento e altre spese la richiedono, e devo cancellarle manualmente una a una.
OSM 2.4.6

**Comment by Dasc3er** [comment]
@idraulicadueci Puoi indicare con precisione i passaggi?

Il comportamento della Ritenuta è il seguente:

1. Fatture di vendita: viene preso il valore impostato nelle **Impostazioni** (la presenza per le anagrafiche era un refuso tecnico)
2.  Fatture di acquisto: se presente, viene presa quella dell'**Anagrafica**, altrimenti da **Impostazioni**.

**Comment by idraulicadueci** [comment]
@Dasc3er Ciao. Grazie per la risposta. In realtà nelle impostazioni (FATTURE) ho indicato "nessuna ritenuta", anche se ritengo sarebbe più corretto adottare il sistema utilizzato per le fatture di acquisto, cioè prendere la ritenuta indicata in anagrafica; questo perché alcuni clienti hanno la ritenuta (vedi condomini) e altri no. Tuttavia nell'importazione del XML del software di FE che utilizza il mio commercialista, viene richiesta la ritenuta su alcune righe della fattura e per toglierla devo fare come ho detto sopra.
Ora ho provato nelle impostazioni (FATTURE ELETTRONICHE) a togliere la "Causale ritenuta d'acconto" ma non cambia niente
I passaggi che faccio:
Creo la fattura con OSM, poi genero il file XML;
Entro nel gestionale che uso per il trasferimento della fattura al SDI e carico l'XML;
nel menù a tendina vedo che sotto a "contributi" ho un triangolo giallo che mi indica che ci sono delle inesattezze, entro e trovo selezionate le opzioni "dati cassa previdenziale" che posso tranquillamente eliminare mettendo "NO" e confermando; mentre per la voce "ritenuta" ho questa possibilità disabilitata. Per abilitarla devo andare su ogni singola riga e togliere "SI", dopo di che posso tornare sotto la voce ritenuta e disabilitarla.

**Comment by idraulicadueci** [comment]
Nessun problema. L'errore che facevo stava nel fatto che nelle impostazioni ---> fatturazione indicavo una ritenuta che avevo nella tabella delle ritenute (Nessuna ritenuta con aliquota = 0) e quindi OSM considerava comunque l'esistenza di una ritenuta in fattura. Lasciando vuoto il campo nelle impostazioni, il problema non si presenta e OSM prende la ritenuta indicata in anagrafica dove sia indicata.
Grazie ancora.
