### ISSUE TITLE
Problema gestione sconti fattura elettronica ricevuta

### ISSUE THREAD

**Issue by deltacomputers** [devcode-it/openstamanager#487]
Ci sono dei problemi sul calcolo degli sconti nell'import della FE .
Quando vengono importate delle righe con scontistiche in percentuale, il software inserisce la riga correttamente, ma la scontistica la sbaglia. Imposta in automatico anziche' il valore in percentuale l'importo come Euro di sconto, e prende solamente il primo carattere presente nell'xml.
Esempio
Riga con totale 100 euro Sconto 20%, il gestionale la importa come riga totale 100 euro sconto 2 Euro.
Riga con totale 100 euro Sconto 14%, il gestionale la importa come riga totale 100 euro sconto 1 Euro 

Versione Openstamanager 2.4.6

**Comment by Dasc3er** [comment]
@deltacomputers Non sono riuscito a replicare il problema...
Con il commit c21b03e9 abbiamo aggiornato il sistema per gli sconti multipli, forse si trattava di un bug precedente...
