### ISSUE TITLE
Ordini - Anomalia inserimento Sede

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#488]
Se inserisco un ordine non è possibile inserire la sede corretta. 

Iter A:
- Primo accesso al modulo ordini dopo il login
- Inserisco un nuovo ordine su un qualsiasi cliente
- Il campo sede risulta vuoto e non impostabile
- Cancello l'ordine
- Inserisco un nuovo ordine su un un altro cliente
- Mi vengono proposte le sedi del cliente precedente

Iter B
- Primo accesso al modulo ordini dopo il login
- Inserisco un nuovo ordine su un qualsiasi cliente
- Il campo sede risulta vuoto e non impostabile
- Sostituisco il cliente con un altro cliente che ha più sedi
- Mi vengono regolarmente proposte le sedi del db e sono tutte impostabili tranne la sede legale

Questo problema è stato segnalato anche sul forum da un altro utente.

* Modulo: Ordini
* Versione del progetto: 2.4.6
* Versione PHP: 7.1.25
* Tipo di server: Aruba Linux

**Comment by Dasc3er** [comment]
Grazie per la segnalazione dettagliata!
Il problema non si verifica nella versione 2.4.5 o precedenti?

**Comment by peropepero** [comment]
A voi!
Nella 2.4.4 non era implementata la sede negli ordini. Nella 2.4.5 non ho provato.

**Comment by Dasc3er** [comment]
Perfetto, grazie ancora! In settimana provvediamo a controllare la causa del problema.

**Comment by Dasc3er** [comment]
Con il commit a711ed92da1e77a0418f4f1a6593543f97971b8e il problema dovrebbe essere risolto.

**Comment by peropepero** [comment]
Confermo che modificando modules/ordini/edit.php come da commit risolvo il problema.
Unico dubbio è il file editor.php del commit che non corrisponde a quello della 2.4.6 che ho installato. Ho lasciato quello che avevo.

**Comment by Dasc3er** [comment]
Hai fatto bene, poiché si trattava di un fix per la versione in sviluppo.
