### ISSUE TITLE
BUG: Totale attività errato su statistiche cliente

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#489]
Cliccando su statistiche nell'anagrafica cliente, il totale relativo alle attività svolte è errato.

OSM 2.4.6

**Comment by Dasc3er** [comment]
@idraulicadueci Il plugin Statistiche per le Anagrafiche è stato rivisitato nella versione in sviluppo 2.4.9.
Potresti controllare se il problema si verifica ancora?

**Comment by idraulicadueci** [comment]
ancora non ho installato la 2.4.9. Hai una data per il rilascio?

**Comment by Dasc3er** [comment]
Putroppo non ancora.
Stiamo cercando di renderla il più possibile stabile, ma sospetto che comunque verrà rilasciata come beta per le numerose modifiche effettuate sulla gestione di sconti, marca da bollo, supporto alle fatture elettroniche semplificate...

@loviuz Potresti controllare che gli importi siano ora corretti?
