### ISSUE TITLE
Domanda: Scadenze negative

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#490]
Le scadenze negative vengono indicate per le fatture di acquisto? Nel mio caso, alcune sono positive mentre altre negative... (mi riferisco alle fatture di acquisto)
È normale?
Grazie

Immagine di riferimento (preso dal report delle scadenze dei fornitori):
![immagine](https://user-images.githubusercontent.com/9463142/52976502-0f9f0180-33ca-11e9-8e8a-b95203979a93.png)

**Comment by Dasc3er** [comment]
@maicol07 Le scadenze sono relative agli XML importati in precedenza?
Perchè nella versione 2.4.6 c'è un bug che ricalcola le scadenze con segno errato.

**Comment by maicol07** [comment]
Sì

**Comment by Dasc3er** [comment]
Quello negativo è corretto per le fatture di acquisto.
