### ISSUE TITLE
BUG: Esportazione XML fattura di vendita

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#492]
Non esporta l'imponibile soggetto a ritenuta
![immagine](https://user-images.githubusercontent.com/40104356/52995522-32a5d180-341b-11e9-8b50-e9c146841c45.png)

OSM 2.4.6

**Comment by Dasc3er** [comment]
@idraulicadueci Potresti indicare con maggiore precisione quale tag XML è mancante? Molto probabilmente è un campo facoltativo, che il software di immagine però considera obbligatorio...
Ecco la rappresentazione ufficiale: https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.pdf

**Comment by idraulicadueci** [comment]
Non saprei, in poche parole deve essere la base imponibile su cui viene calcolata la ritenuta, quindi dovrebbe prendere tutte le righe dove sia indicato "SI" a ritenuta d'acconto. Potrebbe trattarsi anche di un bug del programma esterno, visto che nelle righe è corretta l'indicazione rispetto alla ritenuta.

**Comment by Dasc3er** [comment]
Perché non ho visto un nodo specifico del tipo ImportoImponibileRitenuta o simile..m

**Comment by idraulicadueci** [comment]
È probabile che il programma esterno non prenda in automatico l'imponibile soggetta a ritenuta. Vedremo più avanti.

**Comment by Dasc3er** [comment]
@idraulicadueci Ci sono novità sulla questione?

**Comment by Dasc3er** [comment]
Il supporto all'esportazione FE con Ritenute e Rivalsa INPS è stato aggiunto alcuni mesi fa, con diversi fix successivi.
Nella versione 2.4.11 è stata implementata completamente l'importazione di queste informazioni, in modo sperimentale e da verificare nel dettaglio.
