### ISSUE TITLE
Problema gestione anagrafica condominio

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#493]
Il condominio è una persona fisica, pur avendo un codice fiscale simile a una partita IVA. Nell'esportazione del XML generato, in automatico il cessionario/committente viene preso come persona giuridica e OSM considera errato il codice fiscale indicato, non essendo del tipo XXX XXX 99 X 99 X999X.

OSM 2.4.6

**Comment by loviuz** [comment]
Risolto nelle versioni più recenti.
