### ISSUE TITLE
DDT fatturato dopo eliminazione fattura

### ISSUE THREAD

**Issue by deltacomputers** [devcode-it/openstamanager#494]
Ho rilevato il seguente problema nella generazione di una fattura da DDT.
Se effettuo un DDT e poi premo il pulsante CREA FATTURA dopo averlo spostato nello stato EVASO, mi veine creata correttamente la fattura di vendita. Se però, per qualsiasi motivo, devo eliminare la fattura per riemetterla, aprendo la fattura e cliccando il tasto ELIMINA la stessa viene cancellata, ma il DDT rimane in stato FATTURATO e non me lo fa piu' selezionare in nessun modo.

OSM  Versione 2.4.6 (ec4adeac) 

Grazie

**Comment by Dasc3er** [comment]
Risolto con il passaggio automatico dello stato dei documenti tramite Eloquent, versione 2.4.11
