### ISSUE TITLE
Associazione Fatture Elettroniche passive a DDT e Magazzino

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#496]
Attualmente l'importazione della fattura elettronica passiva è un evento a se. Quindi se ho già caricato un ddt che mi ha movimentato il magazzino, dopo l'importazione della relativa fattura e l'associazione manuale degli articoli alla descrizione, mi ritroverò due movimenti per il solito articolo.

La soluzione temporanea che ho adottato è di creare la fattura passiva 'alla vecchia maniera', inserendo un nuovo documento senza importazione di file xml e scaricando i vari ddt evasi. Poi associo la fattura xml come allegato alla fattura creata.
Questa soluzione non è molto pratica e non consente di importare in automatico i costi di acquisto, tanto meno di fare con semplicità la verifica tra fattura e ddt associati.

Credo che la soluzione si potrebbe trovare in fase di importazione della fattura elettronica. Nel form di inserimento, oltre alla possibilità di associare il codice articolo alla descrizione presente, si potrebbe indicare anche il relativo ddt, magari con una bella query che aiuta ad individuare i codici tra i ddt in stato evaso relativi al cliente...
Perdonate la faciloneria... è solo un idea. Non so quanto sia impegnativa questa strada in quanto a codice. Ne quanto possa essere valida.

Grazie!

* Modulo: Fatture / DDT / Magazzino
* Versione del progetto: 2.4.6
* Versione PHP: 7.1.25
* Tipo di server: Aruba Linux

**Comment by Dasc3er** [comment]
@peropepero Con il commit 458b4c54 la funzionalità è stata aggiunta con un flag apposito "Movimenta gli articoli", da selezionare a piacimento.
