### ISSUE TITLE
Invio email da PHP

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#497]
Come è possibile aprire il popup per l'invio delle email da PHP (Sto sviluppando una funzionalità di invio fatture al commercialista (in formato XML) via email)? Ho guardato qualche classe legate alle email ma non ho trovato nessuna funzione che permette di aproire il modal...

**Comment by Dasc3er** [comment]
Per aprire il modal devi richiamare il file **mail.php** nella root, che però è funzionante esclusivamente con email del sistema ufficiale.
Se devi farne una personalizzazione ti consiglio di copiarlo nel modulo che stai personalizzando e modificarlo di conseguenza, anche se potrebbe essere piuttosto complesso scollegarlo dal sistema di default.

**Comment by maicol07** [comment]
Ok, sto personalizzando il fiel `bulk.php` per inserire un nuovo comando nelle azioni di gruppo ma non viene visualizzato il modal...

**Comment by Dasc3er** [comment]
Perché il file bulk.php non viene richiamato nella stessa pagina a meno che non lo configuri a mano.
