### ISSUE TITLE
Prima nota non viene aggiunta al database

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#498]
## Comportamento attuale

La prima nota non viene aggiunta al database e non viene generato alcun errore

## Passi per riprodurre il comportamento

1. Aggiungere un movimento in prima nota, sia dal tasto + sia da una fattura.

## Contesto

* Modulo: Prima nota
* Versione del progetto: 2.4.7
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
@maicol07 Il funzionamento sembra invece corretto: si apre il modal e viene permesso l'inserimento delle informazioni come in precedenza.

**Comment by maicol07** [comment]
Strano... forse è la mia installazione in locale di test... proverò con la installazione normale

**Comment by maicol07** [comment]
Anche con una installazione pulita non sembra funzionare su XAMPP...

**Comment by maicol07** [comment]
Ho provato anche su un altro server ma continua a non funzionare...

**Comment by lucasalva87** [comment]
Testato con 2.4.7, PHP 7.2.9. La prima nota viene aggiunta correttamente.

**Comment by lucasalva87** [comment]
Testato con OSM 2.4.6 e 2.4.7, PHP 5.6.40. La prima nota NON viene aggiunta, nessun errore dai log.

**Comment by maicol07** [comment]
@lucasalva87 possibile che magari le nuovi versioni di PHP interpretino le query SQL in modo differente?

**Comment by lucasalva87** [comment]
A dire il vero ora ho provato con una nuova installazione, diversa da quella utilizzata per il test, e in questo caso nonostate la versione PHP 7.2.9, la prima nota sembra non funzionare.

**Comment by lucasalva87** [comment]
Il problema è dato da questo controllo: https://github.com/devcode-it/openstamanager/blob/dd6fa69fbb8b0d699b7de630b4b013169d4e2fe3/editor.php#L20 non viene aggiunto il file actions.php

**Comment by maicol07** [comment]
Quindi... come si può risolvere?

**Comment by lucasalva87** [comment]
Ho notato anche che se in $modules "groups" è vuoto non funziona l'accesso non è permesso. Mentre se valorizzato il problema si risolve.

**Comment by Dasc3er** [comment]
@lucasalva87 Ora controllo...

**Comment by Dasc3er** [comment]
@lucasalva87 Se la variabile **groups** del modulo è vuota, nessuno ha accesso al modulo dalla configurazione di OpenSTAManager...
Dove hai riscontrato questo comportamento?

**Comment by lucasalva87** [comment]
> 
> 
> @lucasalva87 Se la variabile **groups** del modulo è vuota, nessuno ha accesso al modulo dalla configurazione di OpenSTAManager...
> Dove hai riscontrato questo comportamento?

Qui, ad esempio:
![fatture di acquisto openstamanager 14](https://user-images.githubusercontent.com/30728163/53359995-b2a8cb80-3934-11e9-869c-de9f35534e46.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Si tratta di un problema nella conversione che hai effettuato per vedere i dati.
Ti consiglio di utilizzare la funzione **dd**.

@maicol07 La issue dovrebbe essere risolta con il fix di cui sopra.

**Comment by maicol07** [comment]
Problema risolto!
Grazie!
