### ISSUE TITLE
errore generazione elettronica

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#499]
versione 2.4.7:

durante generazione elettronica:

Uncaught Exception Whoops\Exception\ErrorException: "Non-static method Plugins\ExportFE\FatturaElettronica::chunkSplit() should not be called statically" at C:\wamp64\www\gest\plugins\exportFE\src\FatturaElettronica.php line 621

nota inserita in fattura:

Richiesta ing. pippo per installazione programmi pippo 4.0 linea pippo.

**Comment by Dasc3er** [comment]
@pubblisoft Grazie per la segnalazione!
SI tratta di un problema che si verifica su alcune installazioni con configurazioni particolari...

**Comment by idraulicadueci** [comment]
@Dasc3er ho fatto la modifica e adesso genera correttamente la fattura elettronica, però mi dà un errore quando provo a visualizzarla
[error.log](https://github.com/devcode-it/openstamanager/files/2902229/error.log)

**Comment by Dasc3er** [comment]
Sembra ci fosse un ulteriore problema dovuto alla documentazione ufficiale PHP: http://php.net/manual/en/domdocument.loadxml.php

La soluzione è ai commit 0a7cee972640abe32f069fbf6da85b199d676441 e c20ce9bfb62f01e645322ecc2b76071484d3d314
