### ISSUE TITLE
Problema valori numerici decimali (0,xx) - Beta 2

### ISSUE THREAD

**Issue by robygladio** [devcode-it/openstamanager#50]
Salve,
inserendo la tariffa oraira e kilometrica in attività generica o tariffe tecnici il costo chilometrico 0,6 per es non viene memorizzato. solo 1 o 1,frazione 
è simile al bug dell'anagrafica che non prendeva gli zero iniziali per PIVA e telefono? 
sperem :)

Roberto

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere stato risolto con gli stessi commit per gli zero iniziali, infatti con la versione master dalla repository non si verifica...

In ogni caso, grazie mille per la segnalazione!
