### ISSUE TITLE
miglioria: num fattura in nome file xml

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#501]
versione 2.4.7:

miglioria: aggiungere num. fattura nel nome del file xml per la fe.
Attualmente il nome del file xml generato è formato da piva_code.xml del tipo _19fxU.xml.
Dovendo importarne più di una in un portale esterno, chiaramente è difficoltoso controllare eventuali problemi del portale senza un riferimento al numero di fattura nel file.

**Comment by lucasalva87** [comment]
Non è possibile in quanto il nome del file così formattato non rispetterebbe gli standard definiti dalla Sogei.

**Comment by pubblisoft** [comment]
Altri programmi tipo teamsystem salvano il file con il numero fattura. Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [devcode-it/openstamanager] miglioria: num fattura in nome file xml (#501)Da: Luca A: devcode-it/openstamanager CC: pubblisoft ,Author Non è possibile in quanto il nome del file così formattato non rispetterebbe gli standard definiti dalla Sogei.

**Comment by Dasc3er** [comment]
Ecco la documentazione relativa alla nomenclatura, che non prevede altro oltre al metodo già implementato: https://www.fatturapa.gov.it/export/fatturazione/it/c-11.htm
