### ISSUE TITLE
miglioria: variazione stato fattura in pro-forma

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#502]
versione 2.4.7:

miglioria: in caso di registrazione fattura come standard-vendite, 
non è possibile tornare indietro a pro-forma, se non forzando nel database il campo
id_segment.

**Comment by Dasc3er** [comment]
Il passaggio tra documenti pro-forma e "validi" può avvenire in un solo senso, l'inverso non dovrebbe essere possibile.
