### ISSUE TITLE
miglioria: menu operazioni quotidiane

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#503]
versione 2.4.7.

miglioria: voce di menu delle operazioni più frequenti.
Creare un articolo, una categoria, registrare un ddt, una fattura, sono le operazioni comuni di tutti
i giorni. risulta scomodo aprire continuamente le varie voci padre di menu per eseguire
queste operazioni.

**Comment by Dasc3er** [comment]
Si tratta effettivamente di una personalizzazione, poichè non di utilità generale.
