### ISSUE TITLE
Problema dopo aggiornamento a 2.4.7

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#504]
Credo sia un problema della mia installazione.

Dopo l'aggiornamento dalla 2.4.6 alla 2.4.7 il modulo preventivi mi consente di inserire un nuovo record, ma al momento del passaggio alla pagina di modifica mi genera i seguenti errori:

![screenshot_2019-02-26 preventivi - openstamanager](https://user-images.githubusercontent.com/35023949/53391769-b1f55100-3997-11e9-87fa-d32fdd9b4e40.png)

Altro segnale di anomalia è il seguente:

![screenshot_2019-02-23 aggiornamenti - openstamanager](https://user-images.githubusercontent.com/35023949/53391822-da7d4b00-3997-11e9-972a-2cebe5279057.png)

Ho un'altra installazione in test sul medesimo server ma con un database pressoché vuoto e si è aggiornata senza nessuno degli errori sopra. Su questa installazione ho eliminato il database e importato il database popolato dell'altra versione che utilizzo e mi si è ripresentato l'errore.
Credo che il problema sia nel mancato aggiornamento del database dalla 2.4.6 alla 2.4.7.
Ogni suggerimento è gradito. Grazie.

* Modulo: Preventivi - Aggiornamenti
* Versione del progetto: 2.4.7
* Versione PHP: 7.1.25
* Tipo di server: Aruba Lunux

**Comment by Dasc3er** [comment]
@peropepero Hai effettuato un aggiornamento tra versioni stabili, senza modificare manualmente il database?
Prova ad eseguire le seguenti query:
```sql
ALTER TABLE `co_statipreventivi` ADD `fatturabile` BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE `co_statipreventivi` SET `fatturabile` = 1 WHERE `descrizione` IN('Parzialmente fatturato', 'Concluso', 'Pagato', 'In lavorazione', 'Accettato', 'In attesa di conferma');
```

Controlleresti di avere un nuovo template email per il sollecito di pagamento?
Altrimenti devi eseguire anche tutte le query dalla riga 13 in poi del file **update/2_4_7.sql**

**Comment by peropepero** [comment]
Confermo l'aggiornamento tra versioni stabili e senza modifiche manuali del db. Ci sono solo tre templates di stampa personalizzati ed alcuni campi personalizzati attraverso l'apposito modulo.

Ho eseguito tutte le query del file update/2_4_7.sql ed ho risolto gli errori.
Adesso vedo anche il template 'sollecito di pagamento', che prima non vedevo.

Resta solo la pagina aggiornamento che mi riporta tutti i moduli fermi alla 2.4.6 e non compatibili. Ma sembra funzionare tutto.
Sarà il caso di inserire la versione 2.4.7 su version e compatibility di tutti i record di zz_modules?
Mi auguro di non accorgermi di qualche errore tra due o tre settimane di inserimenti.....

Grazie!!!

**Comment by Dasc3er** [comment]
Puoi lasciare tutto com'è ora, al prossimo aggiornamento  la versione dei moduli si sistemerà automaticamente.

**Comment by peropepero** [comment]
ok, Grazie!
