### ISSUE TITLE
miglioria: banche di appoggio e campo in visualizzazione fattura

### ISSUE THREAD

**Issue by deltacomputers** [devcode-it/openstamanager#505]
Buongiorno,

Sarebbe comodo se il programma, nel momento in cui si acquisisce e si stampa una fattura, in caso di pagamenti tramite Ri.Ba. , visualizzasse la banca di appoggio del cliente anziche' visualizzare i propri dati bancari.

Sarebbe inoltre comodo se, nell'elenco fatture, venisse mostrato un campo con il tipo di pagamento della fattura, in modo da poter filtrare le stesse per tipo di pagamento (per fare un controllo cassa ad esempio si potrebbero cosi filtrare tutte le fatture pagate in contanti).

Grazie
Stefano

Vers. 2.4.7

**Comment by Dasc3er** [comment]
La modifica in relazione alla banca del cliente dovrebbe essere attiva in versioni recenti (2.4.22 minimo mi sembra), dove è stata introdotta la gestione delle banche.
L'introduzione di una colonna con il tipo di pagamento può essere effettuata con il moduli Viste.
