### ISSUE TITLE
miglioria: stampa foglio ri.ba. di riepilogo

### ISSUE THREAD

**Issue by deltacomputers** [devcode-it/openstamanager#506]
Buongiorno,

Sarebbe utile se il programma desse la possibilità di stampare un elenco delle ricevute bancarie in formato testo, con indicazione del numero fattura, dell'intestazione del cliente completa di partita iva, importo e scadenze, da poter utilizzare per inserire tutte le scadenze nell'internet banking. (non necessariamente un modulo da importare nel sito inbank, basterebbe anche un foglio stampato per avere le scadenze sott'occhio e depennare man mano che si inseriscono manualmente nell'internet banking).

Grazie
Stefano

Versione 2.4.7

**Comment by Dasc3er** [comment]
Per migliorare la gestione dei Ri.Ba. consiglio di contattare gli sviluppatori ufficiali a info@openstamanager.com, poichè credo esista un modulo a pagamento che permette di effettuare le operazioni richieste.
