### ISSUE TITLE
Sconto incondizionato non viene riportato nel passaggio tra i documenti.

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#507]
Versione 2.4.8.
Partendo da un preventivo con applicato uno sconto incondizionato, provare a convertilo in ordine. 
Lo sconto non viene riportato nel nuovo documento. Lo sconto sembra non essere riportato per qualsiasi passaggio. 
Preventivo-> Ordine
Ordine -> DDT
DDT -> Fattura

**Comment by Dasc3er** [comment]
In effetti sembra che ce siamo dimenticati...

**Comment by Dasc3er** [comment]
Similmente sembrano esserci dei problemi nel passaggio tra documenti dove vengono utilizzati i campi id_conto e idiva anche se precedentemente non previsti.
Provvedo a rimuovere il problema? Perché vedo che ne hai aggiunti alcuni nel database...

**Comment by Dasc3er** [comment]
@lucasalva87 Con il commit d943531a42211bc2596c4da980d636e2c30e69ec dovrebbe essere risolto il problema in questione e anche la presenza di id_conto dove non previsto.
Sarebbe inoltre da prevedere, nel passaggio del documento in fattura, l'applicazione della ritenuta contributi.

**Comment by Dasc3er** [comment]
Riferimento per miglioria: #533
