### ISSUE TITLE
BUG: Elenco vuoto in categorie impianti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#508]
## Passi per riprodurre il comportamento

Clicco + per aggiungere una categoria e inserisco i dati richiesti, salvo.

Nella schermata dell'elenco categorie impianti non compare niente

![immagine](https://user-images.githubusercontent.com/40104356/53413498-6e690a00-39cc-11e9-9481-2df8b5a188c9.png)

OSM 2.4.7

**Comment by maicol07** [comment]
Il problema è dato dalla seguente linea:
https://github.com/devcode-it/openstamanager/blob/b273a7ea9a7146b623ffee0f59f3a63871e1e5bc/modules/categorie_impianti/add.php#L11
Vedi #498

**Comment by idraulicadueci** [comment]
@Dasc3er ho modificato il file come da commit, però il risultato è questo
 
![immagine](https://user-images.githubusercontent.com/40104356/53472351-ad986900-3a67-11e9-85c9-1b6ddc2e253c.png)

**Comment by Dasc3er** [comment]
Sembra che il tuo account non abbia i permessi per le **Viste** specifiche del modulo...
Dovresti andare nel modulo Viste e aggiungere ogni gruppo tra quelli con accesso agli elementi del modulo **Categorie impianti**.

È strano però per alla fine dell'aggiornamento dovrebbe essere tutto impostato automaticamente...

**Comment by idraulicadueci** [comment]
Ho provato anche con un'installazione pulita, ma il problema esiste anche lì.

**Comment by lucasalva87** [comment]
Testato con 2.4.8, PHP 7.2.9. Il problema NON si presenta:

![categorie impianti openstamanager](https://user-images.githubusercontent.com/30728163/53502962-72ba2380-3aaf-11e9-940f-0916c24de136.png)

**Comment by Dasc3er** [comment]
@idraulicadueci Sembra essere un problema locale della tua installazione.
Prova ad andare nel modulo **Viste** (abilitabile da **Aggiornamenti**), dentro **Categorie impianti**.
Controlla quindi che i gruppi utenti abbiano accesso alle singole componenti:
![immagine](https://user-images.githubusercontent.com/15911489/53517536-2d0d5300-3acf-11e9-9669-053fc13705c2.png)

**Comment by idraulicadueci** [comment]
Probabilmente era un problema del DB. Ho cancellato il record relativo e l'ho importato nuovamente dal DB dell'installazione pulita. Ora funziona tutto.
