### ISSUE TITLE
MIGLIORIA SCADENZARIO: Fattura allegata nel sollecito di pagamento

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#509]
È buona pratica allegare la fattura, oggetto del sollecito; a tal proposito sarebbe utile far comparire nel template la fattura, allegata automaticamente.

**Comment by idraulicadueci** [comment]
Ho notato inoltre che viene data la possibilità di allegare lo scadenzario e questo sarebbe bene evitarlo perché verrebbe inoltrata la stampata di tutte le anagrafiche in elenco, in violazione delle normative sulla privacy.

**Comment by Dasc3er** [comment]
Questo perché il sistema delle email permette fi includere di default esclusivamente le stampe legate al modulo stesso...

**Comment by idraulicadueci** [comment]
@Dasc3er non si potrebbe legare il template al modulo fatture, in modo da evitare che qualcuno commetta l'errore di allegare lo scadenzario?

**Comment by Pek5892** [comment]
![immagine](https://user-images.githubusercontent.com/102604205/201319265-420c02d4-e64f-43f2-9e17-d8125f8cb533.png)
Introdotto nelle versioni successive
