### ISSUE TITLE
Ragazzi manca molto per la versione stabile 2.3?

### ISSUE THREAD

**Issue by robygladio** [devcode-it/openstamanager#51]
Salve ragazzi, 
So che lavorate a pieno ritmo e mi complimento per i progressi fatti.
egoisticamente siccome sto inserendo molti articoli a listino e le conversioni lavorando su sql danno spesso qualche errore vorrei lavorare nativamente sulla 2.3.
Se però sarà pronta l'anno prossimo lavorerò sulla 2.2 

grazie anticipatamente per la cortese risposta
Roberto

**Comment by fpsoftware** [comment]
Ciao Roberto, speriamo entro fine novembre, comunque massimo entro fine anno.

Grazie per l'interesse.

**Comment by fpsoftware** [comment]
https://github.com/devcode-it/openstamanager/milestone/1

**Comment by loviuz** [comment]
Rilasciata :-)
https://github.com/devcode-it/openstamanager/releases/tag/v2.3
