### ISSUE TITLE
Inserimento materiale utilizzato in attività

### ISSUE THREAD

**Issue by infotrend01** [devcode-it/openstamanager#510]
versione: 2.4.5 (Rdd38d855)
Non riesco ad aggiungere i materiali utilizzati nelle attività.
I materiali sono già presenti a magazzino, apro l'elenco a discesa, li seleziono, clicco il bottone aggiungi e il cursore si trasforma in un divieto e non accede nulla.
Come mai?
![photo_2019-02-28_14-49-05](https://user-images.githubusercontent.com/48093221/53571051-3ac2e700-3b68-11e9-8dea-33084eed5fe3.jpg)

**Comment by Dasc3er** [comment]
Potresti controllare se sono presenti dei log nella cartella** logs/**?

**Comment by infotrend01** [comment]
dove la trovo?

**Comment by Dasc3er** [comment]
Nel percorso principale del programma

**Comment by loviuz** [comment]
se non ricordo male, era un bug della 2.4.5

**Comment by lepool** [comment]
Confermo, era un bug nella 2.4.5

**Comment by infotrend01** [comment]
Ottimo, grazie mille
