### ISSUE TITLE
BUG: Creazione fattura di acquisto da DDT

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#511]
Entro nel DDT di acquisto e clicco CREA FATTURA. Si apre la schermata iniziale. Inserisco i dati. Mi viene dato un errore. Questo è il LOG:

[error.log](https://github.com/devcode-it/openstamanager/files/2916431/error.log)

OSM 2.4.7

**Comment by Dasc3er** [comment]
@idraulicadueci Ci servono maggiori informazioni: potresti provare ad abilitare il debug?

**Comment by idraulicadueci** [comment]
Questo è il log dopo aver attivato il debug:
[error-2019-03-01.log](https://github.com/devcode-it/openstamanager/files/2918220/error-2019-03-01.log)

![immagine](https://user-images.githubusercontent.com/40104356/53621309-61c7fa00-3bf6-11e9-9f2f-918b7711e26b.png)

**Comment by idraulicadueci** [comment]
@Dasc3er il problema si presenta anche quando creo un DDT da ORDINE FORNITORE.
Ho provato anche con l'installazione pulita di OSM 2.4.7 in locale

**Comment by Dasc3er** [comment]
Ora che hai abilitato il debug, tra i log ci sono informazioni più dettagliate...
Puoi condividerle?

**Comment by idraulicadueci** [comment]
[error.log](https://github.com/devcode-it/openstamanager/files/2921012/error.log)
[error-2019-03-01.log](https://github.com/devcode-it/openstamanager/files/2921013/error-2019-03-01.log)

**Comment by Dasc3er** [comment]
@loviuz Sembra che il problema sia generato dalla seguente query:
```php
$dbo->query('UPDATE or_ordini SET idstatoordine=(SELECT id FROM or_statiordine WHERE descrizione="'.get_stato_ordine($rs[$i]['idordine']).'") WHERE id = '.prepare($rs[$i]['idordine']));
```

**Comment by idraulicadueci** [comment]
@Dasc3er ho provato a creare una fattura da un altro DDT e non mi è stato restituito alcun errore. Allora sono tornato al DDT che mi aveva dato i problemi sopra descritti, ho cancellato l'articolo (l'unico che era inserito) e lo ho reinserito. Questa volta non ho avuto errori.
Facendo però la prova partendo dall'ordine fornitore, creando il DDT, il problema si ripresenta nella creazione della fattura dal DDT stesso.

**Comment by idraulicadueci** [comment]
@Dasc3er il problema è stato risolto?

**Comment by Dasc3er** [comment]
@idraulicadueci Purtroppo non posso darti conferma, poichè fino ad ora non siamo mai riusciti a replicare il problema...
@loviuz Ci possono essere dei motivi per cui la query in questione dia problemi?

**Comment by loviuz** [comment]
Dovrei fare un test anch'io, perché non è mai stato segnalato da nessuno finora...

**Comment by lucasalva87** [comment]
Potrebbe essere che in fase di aggiornamento siano stati aggiunti degli stati ordine doppi a database?

**Comment by idraulicadueci** [comment]
@lucasalva87 credo il problema fosse p[roprio quello che dici tu. Infatti ho eliminato delle voci doppie dalla tabella or_statiordine e il problema non si presenta. Grazie
