### ISSUE TITLE
MIGLIORIA Stampata fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#512]
## Comportamento richiesto

1- Se è possibile eliminare il numero da q.tà quando si inserisce una riga descrittiva; inoltre estendere il testo a tutta la riga, invece che dentro la colonna come avviene per gli articoli valorizzati.
2- All stato attuale se inserisco una riga, per es. "arrotondamento", lascio a zero il prezzo di acquisto e inserisco il valore da detrarre in sconto, viene preso il valore assoluto che viene sommato al totale; quindi invece di togliere, aggiungo. Ho provato anche inserendo un valore negativo nel prezzo di vendita: nel prezzo unitario viene restituito correttamente con il segno - mentre nell'importo viene restituito il valore assoluto; il totale in questo caso è giusto e il valore viene decurtato, però anche nella fattura elettronica risulta un valore positivo.

OSM 2.4.7

**Comment by Dasc3er** [comment]
@idraulicadueci Alcune di queste migliorie sono probabilmente state implementate in modo indiretto con l'aggiornamento degli sconti per la 2.4.9...
Quanto al resto, grazie per i suggerimenti!

**Comment by Dasc3er** [comment]
@loviuz I problemi elencati erano stati quindi risolti?

**Comment by loviuz** [comment]
secondo me si
