### ISSUE TITLE
BUG: Calcolo sconti da attività a fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#513]
Creo un intervento e inserisco l'orario di lavoro e indico uno sconto %. 
Aggiungo una fattura e aggiungo l'intervento. Nella fattura viene preso lo sconto dell'intervento come totale in Euro, però come sconto unitario, quindi, se il numero di ore lavorate è 2, nel totale lo sconto viene considerato doppio.
Non so se lo stesso comportamento si ha anche aggiungendo altre tipologie di documenti.

OSM 2.4.7

**Comment by Dasc3er** [comment]
@idraulicadueci Lo sconto che hai aggiunto è sulla singola sessione di lavoro oppure è incondizionato?
Ci servirebbero maggiori informazioni, anche numeriche...

**Comment by idraulicadueci** [comment]
Sulla sessione di lavoro

**Comment by Dasc3er** [comment]
Nella versione in sviluppo 2.4.11 la traspozione degli Interventi in Fattura è stata rivista e aggioranta.
Il problema dovrebbe essere quindi risolto.
