### ISSUE TITLE
Timeout per test configurazione account email

### ISSUE THREAD

**Issue by dariosera** [devcode-it/openstamanager#514]
Potrebbe servire un timeout (breve) per il test della configurazione dell'account email.
Se la connessione non funziona resta bloccata la pagina per... boh! Un tempo indefinitamente lungo, tanto che sono andato a killare il processo da terminale.

**Comment by Dasc3er** [comment]
Di riferimento: #292.
E' necessario separare la verifica delle credenziali dal timeout, magari attraverso un pulsante apposito.

**Comment by Dasc3er** [comment]
Completato con il commit eb44f1d6
