### ISSUE TITLE
Esportazione massiva FE

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#515]
## Comportamento richiesto

Prevedere l'esportazione massiva di Fatture Elettroniche (se generate) attraverso le azioni generali della vista principale del modulo.

* Modulo: Fatturazione Elettronica
* Forum: https://www.openstamanager.com/forum/viewtopic.php?f=1&t=92442

**Comment by maicol07** [comment]
Per la mia installazione avevo già sviluppato questa funzionalità. Ho creato la PR #517

**Comment by Dasc3er** [comment]
Grazie @maicol07, in settimana provvedo a controllare...
