### ISSUE TITLE
Mancato ripristino backup - 2.4.8

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#516]
- Avvio la procedura di ripristino
- Compare pagina bianca senza alcun feedback 
- Dopo qualche minuto chiudo la pagina e rientro in OSM e mi appare questo:

![screenshot_2019-03-03 installazione - openstamanager](https://user-images.githubusercontent.com/35023949/53695285-a5b72c80-3db9-11e9-86bf-8f145d0d0cb0.png)

Ho ripetuto la procedura più volte (dopo aver ripristinato l'installazione), ma ho lo stesso problema.
Ho verificato il db e dopo la procedura di backup risultano create le sole tabelle an_anagrafiche e updates.

* Modulo: Backup
* Versione del progetto: 2.4.8
* Versione PHP: 7.1.25
* Tipo di server: Aruba Linux webx1214

**Comment by Dasc3er** [comment]
Grazie per la segnalazione, in settimana provvediamo a controllare.
Il problema si verifica in versioni precedenti, per tua conoscenza?

**Comment by peropepero** [comment]
2.4.3/4/5/6/7 funzionava correttamente. Grazie.

**Comment by Dasc3er** [comment]
Sembra che ci sia un problema nelle query di tipo **LOCK** su PDO, che però si verifica senza giustificato motivo perchè non sono state effettuate modifiche sulla parte della classe Database che si occupa di queste query dalla versione 2.4.6...

Per il momento per risolvere il problema devi andare dentro al file database,sql del backup e rimuovere tutte le query di tipo:
```sql
LOCK TABLES `*` WRITE;

UNLOCK TABLES;
```

**Comment by Dasc3er** [comment]
Con il commit c04cfca7 puoi fare in modo che backup futuri non abbiano queste query...

Per curiosità, se provi a ripristinare un backup più vecchio cosa succede?

**Comment by peropepero** [comment]
Ho fatto diverse prove e ho riscontrato quanto segue:

2.4.4: nessun problema
2.4.5: nessun problema
2.4.6: ha il problema indicato sopra
2.4.7: ha il problema indicato sopra
2.4.8: ha il problema indicato sopra

Comunque, mi resta il dubbio di aver eseguito nelle scorse settimane diversi ripristini senza problemi anche per la 2..4.6/7/8...

Il commit risolve il problema!
