### ISSUE TITLE
Nota di credito - Errore 00422 SDI

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#518]
La nota di credito viene scartata dall'SDI con il seguente codice errore:
00422 - ImponibileImporto non calcolato secondo le regole definite nelle specifiche tecniche

## Contesto
* Modulo: Fatture di vendita
* Versione del progetto: 2.4.7 (quando è stata inviata la nota di credito)
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by maicol07** [comment]
L'errore si presenta solo se viene creata una nota di credito dal pulsante +.
Se si usa il pulsante Crea all'interno di una fattura l'SDI non rilascia errori

**Comment by Dasc3er** [comment]
Il campo ImponibileImporto è stato corretto in uno degli ultimi commit: https://github.com/devcode-it/openstamanager/commit/197f7390ef8ad1787aced9a167032a3c95e1dd8a
Il problema dovrebbe quindi essere risolto a partire dalla versione 2.4.10
