### ISSUE TITLE
Miglioria: Filtri ricerca

### ISSUE THREAD

**Issue by deltacomputers** [devcode-it/openstamanager#519]
Sarebbe comodo se il filtro ricerca venisse modificato per la ricerca in tutto il campo, non necessariamente sequenziale.
Allo stato attuale,  se i caratteri di ricerca non sono consecutivi, non vengono visualizzati risultati.
Ad es. Pagamento, se cerco un pagamento Ricevuta Bancaria a 60 giorni, e nella tabella è seganta come Ri. Ba. 60gg dffm, se io nel campo ricerca non digito Ri.Ba. 60 non visualizzo risultati.
La miglioria proposta consisterebbe appunto nel inserire nella ricerca in oggetto "Ri 60" e ricevere il risultato che contenga le parole ricercate, non necessariamente scritte in modo sequenziale ma come ricerca di tutto il campo. (questo sarebbe molto comodo soprattutto per gli articoli).

vers. 2.4.8

**Comment by loviuz** [comment]
@Dasc3er potrebbe essere risolto facendo una sostituzione del carattere spazio ricercato con il simbolo "%"?

**Comment by Dasc3er** [comment]
Si potrebbe procedere così, ma sarebbe meglio aggiungere un ordinamento di base per favorire i match completi a quelli con %.

**Comment by loviuz** [comment]
si, esatto, altrimenti si rischia che vengano eseguite delle ricerche troppo ampie se c'è qualche spazio di mezzo

**Comment by Pek5892** [comment]
Introdotto filtro con "%" nelle versioni successive
