### ISSUE TITLE
Miglioria / Plugin: Integrazione Wordpress - Woocommerce

### ISSUE THREAD

**Issue by deltacomputers** [devcode-it/openstamanager#520]
Sarebbe comodo se si potesse generare un'associazione tra il gestionale e wordpress, in modo che, se un utente si registri nel sito web ed effettui un ordine, lo stesso venga riproposto automaticamente nel gestionale, e venga automaticamente inserita l'anagrafica con i dati forniti.

**Comment by Dasc3er** [comment]
La funzionalità dovrebbe essere già stata sviluppata come plugin a pagamento...
@lucasalva87

**Comment by lucasalva87** [comment]
Non abbiamo ancora nulla per Woocommerce. Abbiamo invece disponibile qualcosa per Prestashop
