### ISSUE TITLE
Stampa anteprima/visualizzazione XML

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#521]
## Comportamento richiesto
Utilizzare il file view.php per poter stampare l'XML, oltre che visualizzarlo

**Comment by Dasc3er** [comment]
Cosa intendi per stampare l'XML? 
Potresti provare ad utilizzare la stampa da browser...

**Comment by maicol07** [comment]
Se stampo dal modal, viene stampato anche il contenuto della pagina della fattura

**Comment by Dasc3er** [comment]
Vero, probabilmente è corretto inserire sul nome il link per la pagina di visualizzazione...

**Comment by maicol07** [comment]
O magari un pulsante a fianco

**Comment by lucasalva87** [comment]
Ottima idea :+1:

**Comment by maicol07** [comment]
Per creare il pulsante a fianco ho inserito un pulsante dentro la stringa alla riga 102:
```
<a class="btn btn-xs btn-warning" href="'.ROOTDIR.'/view.php?file_id='.$r['id'].'" target="_blank">
                    <i class="fa fa-print"></i>
                </a>
```
nel file src/HTMLBuilder/Manager/FileManager.php

**Comment by Dasc3er** [comment]
È meglio modificare il link sul nome, perché il pulsante di stampa così non stamperrebbe...
