### ISSUE TITLE
Inserimento fatture non saldate in email cliente

### ISSUE THREAD

**Issue by gifrigio93** [devcode-it/openstamanager#522]
Sarebbe molto comodo allegare alla email che si sta per mandare al cliente, anche le fatture che risultano non saldate con relativa nota nel testo se possibile. Oppure in caso di fatture saldate omettere la nota.
E' possibile farlo secondo voi?

**Comment by Dasc3er** [comment]
Non si tratta del sollecito di pagamento inserito nella versione 2.4.8?
Puoi trovarlo nel modulo **Scadenzario**...
