### ISSUE TITLE
ragione sociale FE

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#523]
versione 2.4.7.

e' importante segnalare che 
se nei dati aziendali vengono impostati oltre la rag.soc. azienda anche nome e cognome, 
il file xml generato della FE conterrà nome e cognome e non la ragione sociale azienda.

**Comment by Dasc3er** [comment]
Perché questi campi sono alternativi: inserisci o l'uno e l'altro.

**Comment by pubblisoft** [comment]
se erroneamente vengono compilati, i documenti vengono stampati con la ragione sociale, la FE con nome e cognome.

**Comment by Dasc3er** [comment]
Se erroneamente vengono compilati si tratta di un errore dell'utente.
In ogni caso, puoi compilare o nome e cognome o ragione sociale, e non entrambi insieme. Se compili nome e cognome la ragione sociale viene corretta di conseguenza.

**Comment by pubblisoft** [comment]
c'è una parte del manuale d'uso in cui si spiega come introdurre questi dati?
perchè nelle stampe non viene stampato nome e cognome, ma solo nella FE?

**Comment by Dasc3er** [comment]
Potresti condividere screenshot dell'anagrafica in questione, della stampa e dell'xml?
