### ISSUE TITLE
Suddivisione scadenzario per clienti e fornitori

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#524]
Alcuni clienti chiedono (giustamente) di poter visualizzare lo scadenzario diviso per clienti e per fornitori. Valutare se visualizzarli su 2 menu distinti (versione più richiesta) o filtrando nell'unico modulo "Scadenzario".

**Comment by peropepero** [comment]
Sarebbe comodo...

mi permetto di suggerire anche la presenza del riferimento n. fattura nell'elenco e la possibilità di poter selezionare le scadenze 'da' - 'a' .
In questo, attraverso 'selezione' e 'stampa' potremmo generare stampe mirate.

Grazie.

**Comment by Dasc3er** [comment]
@peropepero Purtroppo questo suggerimento è completamente scollegato alla questione, se desideri proporlo crea una issue apposta.

**Comment by peropepero** [comment]
ok.

**Comment by loviuz** [comment]
Aggiunta la divisione dello scadenzario tramite i segmenti in:
 - scadenzario totale
- scadenzario clienti
- scadenzario fornitori
- scadenzario riba

con il commit 1e495d76d81fa7a8da25ca53ca623383ae3796fd

E' stata aggiunta anche la colonna con il riferimento fattura con il commit d6b486d4fb54a89e94e976b44bdf78cbb0237d6d

Il filtro per date non è ancora implementato.
