### ISSUE TITLE
Selezione IVA predefinita da anagrafica/impostazioni (Interventi)

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#525]
Nelle impostazioni ho lasciato vuoto il campo IVA predefinita, poiché l'aliquota è differente a seconda dell'anagrafica. Nella singola anagrafica, però ho indicato l'aliquota IVA. 
Aggiungo una nuova attività, con diritto di chiamata, ore di lavoro e articolo.
Nel calcolo IVA viene considerata solo l'aliquota indicata nell'anagrafica dell'articolo, restituendo solo il calcolo per il totale articoli, mentre diritto di chiamata e manodopera non vengono considerati.

La soluzione potrebbe essere quella di considerare in primis l'IVA indicata nell'anagrafica cliente e, se non presente, andare a prendere quella delle impostazioni (IVA predefinita). Lo stesso dovrebbe valere per gli articoli.

OSM 2.4.8

**Comment by Dasc3er** [comment]
Da ricontrollare con la versione 2.4.11
