### ISSUE TITLE
Sconto Incondizionato - Notifica di Scarto SDI

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#527]
Se inserisco uno sconto incondizionato in una attività, mi viene riportato in fattura in questo modo:

![Screenshot_2019-03-09 Fatture di vendita - OpenSTAManager](https://user-images.githubusercontent.com/35023949/54069509-0088d200-4259-11e9-92cb-63332cf4ec68.png)

Ho un importo negativo nella colonna prezzo unitario e positivo nella colonna importo.
Anche se in OSM il totale del documento è corretto, non lo è la sua rappresentazione pdf (sconto positivo) e soprattutto la fattura elettronica viene scartata dal sistema di interscambio in quanto non passa il controllo sul totale documento (codice 00422).

L'errore generato è indipendente dal porre il campo 'Tipo Cessione Prestazione' nei 'Dati di Fatturazione Elettronica' relativi alla riga dello sconto a 'SC - Sconto' o vuota.

Risolvo il problema andando a modificare l'importo dello sconto da positivo a negativo dopo aver generato l'xml.

Segnalo anche la necessità di dover impostare manualmente il conto relativo allo sconto. Vine associato come tutti gli altri all'unico impostabile di default, in questo caso 'Ricavi vendita prestazione di servizi'.
Stessa cosa per i 'Dati di Fatturazione Elettronica', visto che conosciamo il tipo di dato dal documento precedente, l'impostazione a 'SC - Sconto' potrebbe essere automatica.

Grazie.

* Modulo: Fatture - Fatture Elettroniche
* Versione del progetto: 2.4.8
* Versione PHP: 7.1.25
* Tipo di server:

**Comment by lucasalva87** [comment]
Infatti non sono gestiti gli importi negativi. Per generare correttamente l’xml è sufficiente impostare l’imponibile della riga a 0 e impostare 183,25 come sconto in €

**Comment by lucasalva87** [comment]
Va comunque rivisto il passaggio dello sconto incondizionato dall'attività alla fattura.

**Comment by lucasalva87** [comment]
#316799b

**Comment by Dasc3er** [comment]
Sarà inoltre necessario controllare che il nuovo sistema di sconti sia completamente compatibile con la fattura elettronica, visto che è stato modificato apposta.
