### ISSUE TITLE
Errore conteggio Bolli

### ISSUE THREAD

**Issue by infotrendsrl** [devcode-it/openstamanager#528]
Il bollo non deve essere conteggiato nel totale a pagare a meno che non venga esplicitamente indicato nel corpo della fattura come "Rivalsa Bolli" con esenzione IVA articolo 15.

https://github.com/devcode-it/openstamanager/blob/02af26b525c3b31f0a6a2842935d5077bb28dcea/modules/fatture/src/Fattura.php#L147

**Comment by zeon4** [comment]
La soluzione per questa riga è:
`return $this->calcola('netto');`
eliminando la somma del bollo.

**Comment by zeon4** [comment]
Anche la fattura elettronica è conseguentemente sbagliata perchè riporta un totale a pagare diverso dalla somma delle voci della fattura (include erroneamente i bolli senza specificarne la rivalsa).

**Comment by lucasalva87** [comment]
In realtà se il bollo è a carico del cliente è corretto che venga contemplato per il calcolo del netto.

**Comment by infotrendsrl** [comment]
Il bollo è **l'indicazione dell'imposta che chi emette la fattura deve pagare**. Se il bollo viene poi deciso di metterlo a carico del cliente, deve essere indicato espressamente nel corpo fattura (una dicitura del tipo "Rivalsa bolli") e specificato il trattamento iva Esente Art. 15. Il bollo quindi non va mai calcolato nel totale della fattura a meno che non sia espressamente indicato nel corpo della stessa come riga a se stante con apposita indicazione iva.
Il cliente che registra contabilmente (contabilità ordinaria) la fattura elettronica infatti si trova uno sbilanciamento di 2 euro perchè il bollo virtuale non viene rilevato come costo essendo a carico di chi emette la fattura e non indicato per rivalsa.
Come esempio: https://www.iprogrammatori.it/forum-programmazione/fatturazione-elettronica/fattura-elettronica-rivalsa-bollo-t37015.html

**Comment by loviuz** [comment]
Ne parlavo anche qui: https://github.com/devcode-it/openstamanager/issues/531

**Comment by Dasc3er** [comment]
Con gli ultimi commit è stato ampiamente modificato il sistema di calcolo e applicazione dei bolli: ora dovrebbero essere gestiti correttamente.
