### ISSUE TITLE
BUG: Filtro statistiche fornitore

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#529]
Nell' anagrafica relativa a un fornitore, nelle statistiche , sotto fatture vengono restituite 2 voci relative alla stessa fattura:

> Sono state emesse 1 fatture di vendita per un totale di 39,9800 €
> Visualizza>

> Sono state registrate 1 fatture di acquisto per un totale di 39,9760 €
> Visualizza 

La prima è sbagliata, perché rimanda all'elenco delle fatture di vendita.

OSM 2.4.8

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere risolto con la revisione delle statistiche delle anagrafiche.
