### ISSUE TITLE
Soglia quantità minima articoli 

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#53]
La soglia minima quantità non è impostabile a zero. Se tento di impostare 0, mi restituisce sempre il valore 1.
Sto provando la versione HEAD.

**Comment by Dasc3er** [comment]
Ciao @lepool,
ho risolto il problema impostando il minimo della soglia a 0.

Potresti confermare, per sicurezza?
Grazie mille della segnalazione!

**Comment by lepool** [comment]
@Dasc3er  
👍  Confermo, ora funziona.
