### ISSUE TITLE
Marca da bollo opzionale

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#531]
Con la fatturazione elettronica sono cambiati un po' di aspetti riguardanti la gestione della marca da bollo, in particolare viene applicata a determinate esenzioni iva.

Vari utenti hanno richiesto di NON addebitarla in fattura al cliente finale, ma va comunque specificato nella marca da bollo il nodo apposito per indicare che è stata assolta virtualmente, per cui andrebbe introdotta una nuova impostazione per decidere se applicarla o meno ai vari conteggi della fattura. Ora viene sempre applicata.

### Risultato finale con addebito al cliente (come ora)
Totale fattura: 100,00 € (esente iva)
Marca da bollo in fattura: 2,00 €
Totale a pagare: 102,00 €
Totale a scadenzario: 102,00 €
XML:
<BolloVirtuale>SI</BolloVirtuale>
<ImportoBollo>2.00</ImportoBollo>

### Risultato finale senza addebito al cliente
Totale fattura: 100,00 € (esente iva)
Marca da bollo in fattura: non presente
Totale a pagare: 100,00 €
Totale a scadenzario: 100,00 €
XML:
<BolloVirtuale>SI</BolloVirtuale>
<ImportoBollo>2.00</ImportoBollo>

**Comment by Dasc3er** [comment]
Con gli ultimi commit è stato ampiamente modificato il sistema di calcolo e applicazione dei bolli: ora dovrebbero essere gestiti correttamente.
