### ISSUE TITLE
Record non trovato quando tento di aprire un documento che non rientra nel periodo temporale impostato da calendario.

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#532]
Versione in sviluppo (2.4.9)
Record non trovato quando tento di aprire un documento che non rientra nel periodo temporale impostato da calendario.

Es. provando ad aprire una scadenza rif. ad un documento del 2018 lasciando impostato il periodo 2019.
![Scadenzario   OpenSTAManager(5)](https://user-images.githubusercontent.com/30728163/54690754-5d6e6d00-4b22-11e9-81b0-bd28bb0dfc00.png)

![Fatture di vendita   OpenSTAManager(52)](https://user-images.githubusercontent.com/30728163/54690659-28fab100-4b22-11e9-8e6e-3dfa9cf5a8f8.png)

**Comment by lucasalva87** [comment]
Possibile soluzione: prevedere eccezzione getQuery in Util/Query.php dove vengono rimossi eventuali |period_start| e |period_end|

**Comment by Dasc3er** [comment]
Questo è causa dalla nuova gestione dei filtri per i permessi, che utilizza la query principale del modulo per centralizzare i permessi e semplificarli

**Comment by lucasalva87** [comment]
Non potremmo controllare che se siamo all'interno di una scheda editor andiamo a rimuovere tutti i filtri che verrebbero impostati da sessioni.
Rimuovendo dunque dalla query di struttira la parte `  |segment| AND `data` >= '|period_start|' AND `data` <= '|period_end|'`

**Comment by Dasc3er** [comment]
No, perché la data non è generale per ogni modulo.

**Comment by lucasalva87** [comment]
Però con una regular expression partendo dal valore cardine |period_start| e |period_end| che è sempre presente potremmo andare a rimuovere tutto quello che si trova concatenato prima dell'operatore >= e <=. Che sia data, data_inizio, data_ conclusione ecc...

**Comment by Dasc3er** [comment]
Troppo rischioso, sarebbe una limitazione enorme per tutte le altre query.
