### ISSUE TITLE
Ritenuta contributi in passaggio tra documenti

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#533]
## Comportamento richiesto

Riportare la ritenuta contributi nelle righe delle nuova fattura create a partire da DDT, Ordini o altri documenti.

Da riconsiderare anche il comportamento con la ritenuta d'acconto con la futura implementazione come per la ritenuta contributi.

## Comportamento attuale

Per il momento viene riportata solo a livello di documento, non venendo selezionata per le singole righe e quindi non venendo applicata.

**Comment by Pek5892** [comment]
Attualmente gestito
