### ISSUE TITLE
IMPIANTI - Visualizzazione dei contratti collegati

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#534]
Nelle versioni precedenti era possibile, entrando in un impianto, verificare in che contratto è presente, ora non c'è più questo plugin ?
![image](https://user-images.githubusercontent.com/34273200/54826378-04ccda80-4cb0-11e9-9e8d-23d550e5f5fc.png)

**Comment by loviuz** [comment]
Non mi risulta ci fosse...
