### ISSUE TITLE
BUG: Preventivo non disponibile per la fatturazione

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#535]
Se creo una fattura ho il preventiv XXX disponibile per l'importazione. Se cancello le righe del preventivo importate in fattura, il preventivo resta non disponibile; stessa cosa accade se cancello la fattura, comne se il preventivo resti flaggato come già fatturato.

OSM 2.4.8

**Comment by Dasc3er** [comment]
@idraulicadueci Grazie per la segnalazione!
Credo che il commit 117c09b40bfe3e0791a011199a87c5acb482b97d e la issue #538 abbiano già risolto il problema...

@loviuz
