### ISSUE TITLE
Bug su aggiornamento quantità evase preventivi

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#538]
## Comportamento richiesto

Quando si fattura un preventivo vengono evase le relative righe, e quando si eliminano dalla fattura dovrebbero essere ripristinate nel preventivo per essere nuovamente fatturabili.

## Comportamento attuale

Quando si eliminano dalla fattura le righe del preventivo non si ripristinano le quantità da evadere nel preventivo, per cui non si riesce più a fatturarlo.

## Contesto

* Modulo: Preventivi
* Versione del progetto: 2.4.9 (in sviluppo)
* Versione PHP: 5.6
* Tipo di server: LAMP

**Comment by loviuz** [comment]
Risolto in rimozione riga e rimozione fattura con 117c09b40bfe3e0791a011199a87c5acb482b97d.

Da completare quando si modifica la quantità sulla riga.

**Comment by Dasc3er** [comment]
Sarebbe da correggere con la rimozione delle righe tramite Eloquent...

**Comment by Dasc3er** [comment]
@loviuz Ecco un esempio di come può essere gestito in futuro: https://github.com/devcode-it/openstamanager/blob/0d5b63a5149348fe1e8ae050346a4834a3871053/modules/fatture/src/Components/RelationTrait.php#L158

Per ora il fix così può andare bene, ma in futuro sarà da aggiornare con il metodo **evasione()**.
