### ISSUE TITLE
Problema su sconti in fattura

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#542]
**Problema 1**
Ci siamo accorti di un problema nella generazione delle fatture elettroniche, che deriva in realtà da un conteggio errato dello sconto in fattura: se creo una fattura con una riga di 100€ + 22% di di iva, e applico 50€ di sconto globale, mi aspetterei di vedere in stampa:
![immagine](https://user-images.githubusercontent.com/1647128/55162927-24a94600-5169-11e9-9b19-7ffeb041ba8b.png)

invece vedo:
![immagine](https://user-images.githubusercontent.com/1647128/55162967-312d9e80-5169-11e9-809c-ea4030aab5c8.png)

Questo perché il riepilogo iva in stampa non trova "desc_iva" valorizzato nella riga dello sconto, per cui non raggruppa correttamente gli importi.

Soluzione proposta: valorizzare anche nella riga con sconto globale il campo "desc_iva".

**Problema 2**
Sempre utilizzando l'esempio di prima, se genero l'XML della fattura elettronica, lo sconto viene ignorato. Viene inserito nel campo "Sconto globale" che sembra essere solo un dato riepilogativo, infatti anche qui nell'XML troviamo imponibil 100€ e iva 22€ invece che imponibile 50€ e iva 11€.

Versione errata:
![immagine](https://user-images.githubusercontent.com/1647128/55163195-9ed9ca80-5169-11e9-9f2e-2529712c5cc1.png)

Versione corretta:
![immagine](https://user-images.githubusercontent.com/1647128/55163231-b1ec9a80-5169-11e9-91d3-6a4f32bd72d8.png)

Per ulteriore chiarezza: il campo Sconto/Maggiorazione è puramente informativo, infatti cambiandolo con importi casuali il flie XML viene sempre validato.

**Problema 3**
Importando una fattura XML passiva che ha il nodo <ScontoMaggiorazione> valorizzato, viene importato come sconto, ma in effetti deve essere ignorato perché è un dato puramente informativo. Infatti, da alcune fatture elettroniche ricevute, ScontoMaggiorazione è presente se nelle righe ci sono delle righe con sconti. ScontoMaggiorazione è solo un riepilogo.

**Comment by Dasc3er** [comment]
Risolto con il commit c72c01a690d46d6f83bf393708cc7b770b73bb1b, da testare.

**Comment by Dasc3er** [comment]
@loviuz L'unico difetto dell'implementazione attuale è che, per gli sconti di fatture precedenti, potrebbero esserci dei valori sbagliati nell'IVA degli sconti incodizionati traslati come righe.
Prima infatti veniva calcolato erroneamente un'IVA senza percentuale precisa, mentre ora questa viene sempre ricalcolata in automatico dal sistema di gestione degli importi.

Esempio: più righe con IVA diverse. Sconto incodizionato al 20%. L'IVA dello sconto ha un valore misto sulla base degli effettivi importi delle altre righe.
Nella trasformazione in riga normale, il campo IVA della nuova riga sconto viene sempre ricalcolato (come è corretto) ma sull'IVA predefinita, il che quindi provocherebbe importi diversi anche per fatture già chiuse.

**Comment by Dasc3er** [comment]
Il commit f0f755eb dovrebbe migliorare anche questo aspetto, ma sarebbero da fare diversi test di retrocompatibilità con fatture precedenti.

**Comment by Dasc3er** [comment]
**Esempio pratico**
Righe normali
![immagine](https://user-images.githubusercontent.com/15911489/55574956-93832380-56c2-11e9-86f0-1fb8d0fed17a.png)

Righe con sconto incodizionato
![immagine](https://user-images.githubusercontent.com/15911489/55574942-8a925200-56c2-11e9-9a4f-4047719a3909.png)

In questo caso, l'iva dello sconto è mista tra quella indicata dalle due righe (non è il 20% o il 10% dello sconto effettivo). Con il nuovo sistema, il tutto viene riportato nel seguente modo per "retrocompatibilità" della classe **Common\Components\Discount**:
![immagine](https://user-images.githubusercontent.com/15911489/55575563-fde89380-56c3-11e9-925e-17a8f71d9fc5.png)

La retrocompatibilità è ottenuta attraverso un fix per i soli sconti, che utilizza direttamente il campo iva della tabella, il quale in futuro sarà deprecato perchè calcolabile direttamente tramite PHP. ll risultato alla rimozione del campo sarà il seguente (calcolo di IVA errato al 22%):
![immagine](https://user-images.githubusercontent.com/15911489/55575636-2a9cab00-56c4-11e9-9a1b-dcccda07a8be.png)

**Comment by Dasc3er** [comment]
@loviuz Hai letto l'ultimo commento?

**Comment by loviuz** [comment]
si. se nelle fatture precedentemente salvate c'era un'iva mista o errata, se queste fatture sono già state emesse, non c'è modo di farle tornare corrette automaticamente. anzi, se sono state inviate così devono rimanere tali ed usciranno corrette le prossime

**Comment by Dasc3er** [comment]
Il problema è nel fatto che, con la futura revisione della struttura delle tabelle per le righe verrà rimosso il campo iva, poichè inutilizzato e sostituito dal ricalcolo automatico. In questo caso verranno visualizzati, per le fatture più vecchie, degli importi errati.

**Comment by loviuz** [comment]
Al momento mi è difficile trovare una soluzione per dei cambiamenti futuri ancora da definire, anche se la parte più importante è la rimozione del calcolo iva. Per il momento direi che va bene il cambiamento attuale, discutiamo la rimozione del campo iva e di questo problema in un secondo momento
