### ISSUE TITLE
Problema visualizzazione importi con 3 o 4 decimali.

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#544]
Versione 2.4.9 (in sviluppo)
Per riprodurre il problema:
Abilitare a 3 decimali in Impostazioni --> Generali --> Cifre decimali per importi
Aprire una sheda articolo e provare a salvare ad esempio il prezzo di vendita 0,022.

**Comment by Dasc3er** [comment]
Qual è il problema? La descrizione...

**Comment by lucasalva87** [comment]
Non l'avevo inserito perchè se fai la prova è  lampante. 0,022, viene convertito da js in 22,000

**Comment by Dasc3er** [comment]
Non riesco a replicare il problema. Potresti provare a cancellare la cache e creare nuovamente gli assets?

**Comment by lucasalva87** [comment]
Prova pure sulla demo pubblica: https://demo.osmcloud.it/248/

**Comment by Dasc3er** [comment]
Prova in locale.

**Comment by lucasalva87** [comment]
Provato in locale, browser modalità anonima, asstes rigenerati. Stesso problema.

**Comment by Dasc3er** [comment]
Provato anch'io, nessun problema :confounded:

**Comment by lucasalva87** [comment]
Sulla nostra demo https://demo.osmcloud.it/248/ il problema ti si presenta?

**Comment by Dasc3er** [comment]
No. Dalla demo online:
![immagine](https://user-images.githubusercontent.com/15911489/55569993-654c1680-56b7-11e9-81a1-b09633dcf65f.png)

**Comment by lucasalva87** [comment]
Non 0,220 ma 0,022

**Comment by Dasc3er** [comment]
Nessuna differenza.

**Comment by lucasalva87** [comment]
@loviuz riesci a provare anche tu?

**Comment by loviuz** [comment]
Succede anche a me, con Firefox. Attenzione, modificando il prezzo di vendita dalla scheda articolo, mentre da una fattura ad esempio viene salvato correttamente

**Comment by Dasc3er** [comment]
@loviuz Grazie per la segnalazioene, il commit dovrebbe aver risolto questo problema nello specifico (sembra che per qualche motivo i campi venissero inizializzati due volte, solo per gli Articoli).
Ma in ogni caso l'altro non riesco a replicarlo in assoluto.

**Comment by lucasalva87** [comment]
Per me il problema sembra risolto :+1:

**Comment by Dasc3er** [comment]
Sembra o è?
