### ISSUE TITLE
Bug registrazione contabile pagamento nota di credito

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#545]
Dopo la registrazione contabile del pagamento di una nota di credito, permane il pulsante di registrazione.
![Fatture di vendita   OpenSTAManager(55)](https://user-images.githubusercontent.com/30728163/55562869-22109880-56f5-11e9-8e5d-682de19ecfe3.png)

Questo perché in `co_scadenziario`, l’importo pagato viene salvato come valore positivo, non chiudendo la scadenza. Invece dovrebbe venire valorizzato con segno negativo.

![localhost   mysql wampserver   osm_totino_249   co_scadenziario   phpMyAdmin 4 1 14](https://user-images.githubusercontent.com/30728163/55562879-250b8900-56f5-11e9-831f-3744e52cea1d.png)

**Comment by Dasc3er** [comment]
@lucasalva87 L'importo in `co_scadenziario` è corretto?

**Comment by lucasalva87** [comment]
Sì,  come importo è corretto.

**Comment by Dasc3er** [comment]
@lucasalva87 Credo il problema sia causato da questa riga : https://github.com/devcode-it/openstamanager/blob/0d5b63a5149348fe1e8ae050346a4834a3871053/modules/fatture/buttons.php#L51

**Comment by Dasc3er** [comment]
Bug da controllare nuovamente in considerazione delle rivisitazione della registrazione contabile
