### ISSUE TITLE
Miglioramento struttura righe/articoli/sconti/descrizioni

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#546]
## Comportamento richiesto

Per la versione 2.5 sarebbe da rivedere almeno parzialmente il comportamento delle tabelle dedicate alla memorizzazione delle righe dei documenti.
In particolare, sarebbero da rimuovere i seguenti campi poichè calcolabili/individuabili di volta in volta:
- desc_iva
- iva
- iva_indetraibile
- rivalsainps (co_righe_documenti)
- ritenutaacconto (co_righe_documenti)

Il campo **subtotale** sarebbe da modificare in **prezzo_unitario_vendita**.

Si potrebbero prevedere, al fine di semplificare alcuni operazioni di calcolo, dei campi con prefisso **calcolo_** da utilizzare solo per eventuali query manuali all'interno delle pagine principali dei moduli (per esempio, sarebbe sufficiente un semplicie _calcolo_totale_ , in modo da sommare questo valore nella tabelle delle Fatture). **Questi campi non sarebbero da utilizzare in alcun modo oltre alle query di visualizzazione.**
In alternativa, sarebbe possibile prevedere che ad ogni modifica delle righe vengano aggiornati dei campo **calcolo_** disponibili nel documento (e non nelle righe principali).

**Comment by beppe9000** [comment]
mantenere i valori calcolati nel database è di sicuro utile per chi genera report a partire direttamente dalle tabelle mysql
