### ISSUE TITLE
MIGLIORIA: Importo preventivo nelle statistiche cliente

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#547]
Nelle statistiche cliente, di un preventivo scontato viene riportato l'importo lordo invece di quello netto.

Esempio:
ho un preventivo con Imponibile 2990 euro
sconto totale  645 euro
imponibile scontato 2345 euro

Nelle statistiche cliente compare "Sono stati fatti 1 preventivi per un totale di 2.990,00 €"

OSM 2.4.8

**Comment by loviuz** [comment]
Risolto per la 2.4.9
