### ISSUE TITLE
Campi personalizzati 

### ISSUE THREAD

**Issue by omar2kkb** [devcode-it/openstamanager#548]
Buongiorno,
sto provando a testare la funzionalità campi personalizzati, di seguito riporto lo screen che ho impostato dal pannello strumenti.

![Immagine](https://user-images.githubusercontent.com/42521006/55686401-f7c31300-5960-11e9-9a08-31be1bf97545.jpg)

il campo personalizzato mi compare nel modulo preventivi, tuttavia sembra che non memorizzi il valore che vado ad impostare.

![2](https://user-images.githubusercontent.com/42521006/55686461-c139c800-5961-11e9-84cc-a87b1ccce019.png)

c'è qualcosa che sbaglio nella sintassi?
Grazie

**Comment by Dasc3er** [comment]
@omar2kkb Grazie per la segnalazione!
Si tratta effettivamente di un bug specifico per il modulo Preventivi.
Puoi trovare la soluzione al commit 9d230c2b.
