### ISSUE TITLE
problema accetazione FE con sconto

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#549]
Versione del progetto: 2.4.7.

La FE non viene accettata se si inserisce lo sconto percentuale nella lista degli articoli. 
Il motivo che i totali dichiarati e parziali scontati nel file xml generato sono diversi.

**Comment by lucasalva87** [comment]
Potresti provare con la versione 2.4.8, ultima release disponibile?
Grazie mille.
