### ISSUE TITLE
"visualizza scheda" da attivita genera errore per utente tecnico

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#55]
Occorre modificare la query in zz_plugins per la visualizzazione corretta delle sedi e referenti per utente tecnico, altrimenti l'errore si presenta nella WHERE addizionale per i tecnici:

[2017-11-24 08:47:14] Logs.ERROR: Uncaught Exception PDOException: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'an_anagrafiche.idanagrafica' in 'where clause' - SELECT SQL_CALC_FOUND_ROWS an_sedi.id, an_sedi.nomesede AS Nome, an_sedi.indirizzo AS Indirizzo, an_sedi.citta AS Città, an_sedi.cap AS CAP, an_sedi.provincia AS Provincia, an_referenti.nome AS Referente FROM an_sedi LEFT OUTER JOIN an_referenti ON idsede = an_sedi.id WHERE 1=1 AND  an_anagrafiche.idanagrafica IN (SELECT idanagrafica FROM in_interventi_tecnici INNER JOIN in_interventi ON in_interventi_tecnici.idintervento=in_interventi.id WHERE in_interventi.idanagrafica=an_anagrafiche.idanagrafica AND idtecnico='3') AND an_sedi.idanagrafica='128' HAVING 2=2 ORDER BY an_sedi.id DESC LIMIT 0, 144" at /var/www/https/osm/src/Database.php line 761

Ecco le modifiche che dovrebbero risolvere il problema nel file 2_3.sql

-- modifica per i plugin Sedi in Anagrafiche
UPDATE `zz_plugins` SET `script` = '', `options` = '	{ "main_query": [	{	"type": "table", "fields": "Nome, Indirizzo, Città, CAP, Provincia, Referente",	"query": "SELECT an_sedi.id, an_sedi.nomesede AS Nome, an_sedi.indirizzo AS Indirizzo, an_sedi.citta AS Città, an_sedi.cap AS CAP, an_sedi.provincia AS Provincia, an_referenti.nome AS Referente , an_anagrafiche.idanagrafica FROM an_sedi LEFT OUTER JOIN an_referenti ON idsede = an_sedi.id LEFT OUTER JOIN an_anagrafiche ON an_anagrafiche.idanagrafica = an_sedi.idanagrafica WHERE 1=1 AND an_sedi.idanagrafica=|idanagrafica| HAVING 2=2 ORDER BY an_sedi.id DESC"}	]}', `directory` = 'sedi', `version` = '2.3', `compatibility` = '2.*' WHERE `name` = 'Sedi';

-- modifica per i plugin Referenti in Anagrafiche
UPDATE `zz_plugins` SET `script` = '', `options` = '	{ "main_query": [	{	"type": "table", "fields": "Nominativo, Mansione, Telefono, Indirizzo email, Sede",	"query": "SELECT an_referenti.id, an_referenti.nome AS Nominativo, mansione AS Mansione, an_referenti.telefono AS Telefono, an_referenti.email AS \\'Indirizzo email\\', an_sedi.nomesede AS Sede , an_anagrafiche.idanagrafica FROM an_referenti LEFT OUTER JOIN an_sedi ON idsede = an_sedi.id LEFT OUTER JOIN an_anagrafiche ON an_anagrafiche.idanagrafica = an_referenti.idanagrafica WHERE 1=1 AND an_referenti.idanagrafica=|idanagrafica| HAVING 2=2 ORDER BY an_referenti.id DESC"}	]}', `directory` = 'referenti', `version` = '2.3', `compatibility` = '2.*' WHERE `name` = 'Referenti';

**Comment by Dasc3er** [comment]
Approfondendo le cause dell'errore, ho scoperto che viene generato dal fatto che i filtri generici in **zz_group_module** vengono applicati a tutte le operazioni del modulo, quindi oltre alla query iniziale vengono filtrati anche i relativi plugin.

@loviuz @lucasalva87 @fpsoftware Questo comportamento può considerarsi corretto?
Dipende infatti dalla nuova struttura dei plugin simile a quella dei moduli...
Sarebbe forse più corretto aggiungere un campo per specificare se il filtro deve essere applicato sulla query generica del modulo o su un determinato plugin?

**Comment by Dasc3er** [comment]
Se effettivamente le query dei plugin non devono essere filtrate con gli stessi filtri dei moduli, la soluzione al problema sarebbe piuttosto semplice (un `if ` all'interno di **ajax_dataload.php**).
Se invece sarebbe utile avere una gestione dei filtri per i plugin, l'implementazione si potrebbe effettuare con l'aggiunta di un campo _id_plugin_ in **zz_group_module**: se impostato a NULL il filtro è riferito al modulo, altrimenti al plugin indicato. Questa soluzione però potrebbe essere implementata in futuro, se ne si vede la necessità...

**Comment by fpsoftware** [comment]
Anche per me si possono escludere questi filtri dai plugin.
