### ISSUE TITLE
Errore passaggio da Preventivi a ordine/fattura

### ISSUE THREAD

**Issue by NicNal** [devcode-it/openstamanager#552]
## Comportamento richiesto

Creazione di ordine/fattura da preventivo 

## Comportamento attuale

Una volta su "Crea" se clicco su "Ordine" o "Fattura" non succede nulla. Se torno indietro o ricarico la pagina visualizza questo:
![Preventivi](https://user-images.githubusercontent.com/47529265/55890335-ce99c100-5bb2-11e9-8777-39eec75fd0f1.png)

## Passi per riprodurre il comportamento

1. Aggiungere una riga generica
2. Creare -> ordine/fattura
3. Confermare

## Contesto

* Modulo: Preventivi
* Versione del progetto: master
* Versione PHP: 7.2
* Tipo di server: apache

**Comment by Dasc3er** [comment]
@NicNal Non riesco a replicare il problema: sarebbero più utili i contenuti del file **logs/error.log** sul problema.

**Comment by Dasc3er** [comment]
Sono riuscito a replicarlo, ora controllo...
