### ISSUE TITLE
Errore registrazione contabile pagamento

### ISSUE THREAD

**Issue by NicNal** [devcode-it/openstamanager#557]
## Comportamento richiesto
Registrare parzialmente il pagamento togliendolo dallo scadenzario 

## Comportamento attuale

Effettuando una registrazione contabile registra il movimento in prima nota ma non viene barratto nella fattura e non viene tolto dallo scadenzario 

## Passi per riprodurre il comportamento

1. Registro il pagamento 
![Schermata da 2019-04-12 11-57-08](https://user-images.githubusercontent.com/47529265/56029627-19cee380-5d1b-11e9-8db2-0f44eadafc28.png)
![Schermata da 2019-04-12 11-57-25](https://user-images.githubusercontent.com/47529265/56029642-22271e80-5d1b-11e9-85be-980f1d90b215.png)

2. Clicco su Salva 

3. Il pagamento è stato registrato in prima nota ma non è tolto dallo scadenzario ne barrato nella fattura. Prima di fare salva invece la scadenza viene chiusa normalmente
![Schermata da 2019-04-12 11-57-08](https://user-images.githubusercontent.com/47529265/56029716-4daa0900-5d1b-11e9-8626-5404fccf49e3.png)

![Schermata da 2019-04-12 11-58-30](https://user-images.githubusercontent.com/47529265/56029752-631f3300-5d1b-11e9-9e22-571ca49c62c9.png)

![Schermata da 2019-04-12 12-02-07](https://user-images.githubusercontent.com/47529265/56029701-42ef7400-5d1b-11e9-8e62-fea245354b94.png)

## Contesto

* Modulo: scadenzario, fatture di acquisto, contabilità
* Versione del progetto: master
* Versione PHP: 7.2
* Tipo di server: apache

**Comment by NicNal** [comment]
Lo stesso errore è presente anche per quanto riguarda le fatture di vendita

**Comment by Dasc3er** [comment]
@NicNal Ho appena provato e il comportamento sembra corretto.

1. Registrazione contabile di un pagamento (senza modifiche agli importi)
2. Il movimento in prima nota viene creato dal passaggio precedente
3. Tornando sulla fattura la scadenza è stata segnata, e sullo Scadenzario è scomparsa

Ho per caso frainteso un passaggio?

**Comment by loviuz** [comment]
Subito dopo aver creato la prima nota, se dalla schermata di edit della prima nota si preme "Salva", stranamente viene sballato qualcosa nello scadenzario, infatti la scadenza non risulta più barrata (pagata)

**Comment by Dasc3er** [comment]
Ho provato anche questo, senza modificare la prima nota: non so verificava...

**Comment by NicNal** [comment]
La GIF sottostante dovrebbe rendere meglio l'idea 
![GIFFatturediAcquisto](https://user-images.githubusercontent.com/47529265/56128432-e640c300-5f7f-11e9-96db-49e7a75648e7.gif)

**Comment by Dasc3er** [comment]
@NicNal Grazie, stavo provando con le fatture di vendita...

@loviuz Il problema è causato dalla seguente query:
https://github.com/devcode-it/openstamanager/blob/fc8cc28f7a64695f972c344d6701c0dd1c2a3c05/modules/primanota/actions.php#L171

In pratica, la funzione aggiorna_scadenziario prende solo le rate con pagato > 0, che però vengono rimosse dalla query precedente.
https://github.com/devcode-it/openstamanager/blob/fc8cc28f7a64695f972c344d6701c0dd1c2a3c05/modules/fatture/modutil.php#L173

**Comment by Dasc3er** [comment]
Da ricontrollare con la nuova gestione nella 2.4.11 in sviluppo.

**Comment by Dasc3er** [comment]
La gestione degli importi in scadenzario dalla prima nota è stata completamente rivista e corretta nella versione in sviluppo 2.4.11, risolvendo il problema.
