### ISSUE TITLE
eliminare dicitura rif ordine

### ISSUE THREAD

**Issue by ale82x** [devcode-it/openstamanager#559]
## Comportamento richiesto
creazione fattura da ordine senza la dicitura 
 Rif. ordine xxx del xx/xx/xxxxx
## Comportamento attuale
quando viene creata la fattura da ordine compare la scritta
Rif. ordine xxx del xx/xx/xxxxx

## Possibile soluzione
come faceva nelle versioni precedenti non è un problema vedere il rif ordine a video/gestionale ma che non compaia nella fattura PDF/elettronica

## Passi per riprodurre il comportamento

1. creare fattura partendo da un ordine cliente
2. controllare in fattura la dicitura

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto
* Modulo: vendite ordini clienti / fatture vendita
* Versione del progetto:
* Versione PHP: 7.1
* Tipo di server: apache

grazie mille

**Comment by loviuz** [comment]
@Dasc3er @lucasalva87 dato che anche altri utenti mi hanno riferito che non sempre è utile/carino mostrare i riferimenti automaticamente alle righe in fattura, potrebbe essere utile inserire un flag in co_righe_documenti per definire se mostrare o meno questi riferimenti in fattura? In particolare in stampa e nella fattura elettronica (flag unico per entrambe). Per rendere il tutto flessibile, farei un flag "mostra_riferimenti" che di default viene impostato a true da impostazioni, e si può variare di volta in volta, salvandolo in co_righe_documenti.

**Comment by Dasc3er** [comment]
Sarebbe meglio prevedere qualcosa a livello di Impostazioni generali, senza complicare eccessivamente le logiche delle singole righe.

**Comment by ale82x** [comment]
anche per me sarebbe più comodo avere un'impostazione generale.
Dove posso dire metti la dicitura su tutti i documenti oppure non mettere la dicitura su tutti i documenti.

grazie mille

**Comment by loviuz** [comment]
per me ok l'impostazione generale, tanto viene semprr aggiunta "al volo"

**Comment by lucasalva87** [comment]
Ok l'impostazione. Viceversa sarebbe utile mostrare nelle righe dei documenti, ad esempio quando si fattura un ddt generato da un ordine, sì il riferimento del ddt ma anche il riferimento dell’ordine. Anche questo sarebbe utile:
1) Prevederlo
2) Gestirlo tramite impostazione

**Comment by Dasc3er** [comment]
Intendi risalire all'eventuale livello precedente di riferimento?
Del tipo con Ordine in DDT, DDT in Fattura mostrare anche il riferimento all'ordine?

**Comment by lucasalva87** [comment]
Esatto

**Comment by Dasc3er** [comment]
Questo complicherebbe molto la logica di gestione dei riferimenti, e non credo sia molto richiesto...
Non sarebbe da considerarsi come personalizzazione? Anche perché poi c'è chi vuole solo alcuni riferimenti a cascata, altri solo per alcuni documenti, oppure sulle stampe...
