### ISSUE TITLE
Android - Attività - Nuova anteprima e firma

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#56]
su dispositivo Android, con qualsiasi browser, dalla scheda di una attività se clicco su "Nuova anteprima e firma" appare il seguente messaggio: "Rapportino.pdf plugin PDF mancante."
il file viene generato correttamente, purtroppo Android non supporto l'apertura di pdf tramite iframe

**Comment by loviuz** [comment]
avevo visto una libreria pdf.js, si potrebbe vedere se funziona anche sui browser di uno smartphone

**Comment by lepool** [comment]
E se convertite il pdf in un jpg o png per gli smartphone android?

**Comment by loviuz** [comment]
non so se la libreria mpdf converte anche in jpg o png...

**Comment by Dasc3er** [comment]
@loviuz non credo si possa creare un'immagine (che comunque avrebbe utilità ridotta), però si potrebbe approfondire la questione...
Una soluzione più semplice può essere invece l'utilizzo di https://github.com/mozilla/pdf.js, come da te suggerito.

**Comment by lepool** [comment]
Ho provato von ViewerJS e sembra funzionare anche con Android Browser Stock senza plugin.

**Comment by lucasalva87** [comment]
Commit 9fe7b4ef754b9cf7ed55bc31bdf57cbbe3a4256f a fix del bug #56
