### ISSUE TITLE
Bug altre spese intervento 

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#562]
Versione 2.4.9 (in sviluppo) quando modifico la riga in altre spese della scheda intervento non salva il valore digitato in prezzo di vendita e in prezzo di acquisto. Stesso problema anche per lo sconto.

**Comment by lucasalva87** [comment]
![Attività   OpenSTAManager(44)](https://user-images.githubusercontent.com/30728163/56434734-27b1d500-62d6-11e9-9b94-1bb407fe5f42.png)

**Comment by NicNal** [comment]
Risolto, qualcuno può provare?

**Comment by Dasc3er** [comment]
@NicNal In realtà il tuo commit sembra aver introdotto il bug... 
Ripristinando il file alla versione precedente il comportamento è corretto. Puoi controllare per sicurezza?
