### ISSUE TITLE
Aggiungere controllo per partita iva o codice fiscale già presente

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#563]
Aggiungere un controllo se la partita iva o codice fiscale è già presente in fase di inserimento anagrafica o fase di modifica. Non possono esistere 2 anagrafiche con stessa partita iva o stesso codice fiscale.

**Comment by lucasalva87** [comment]
Il controllo andrebbe a questo punto introdotto anche in fase di importazione anagrafiche.

**Comment by Dasc3er** [comment]
Controllo aggiunto in fase di inserimento e modifica anagrafica con il sistema di validazione.
Da inserire nell'importazione anagrafiche, anche se è possibile selezionare la partita iva o il codice fiscale come primary key?

**Comment by loviuz** [comment]
Si potrebbe gestire in fase di importazione impostando come primary key la partita iva, sì. Altri metodi non saprei, perché se dovessimo gestirlo durante l'import con un'altra primary key, non saprei come altro gestire i doppioni.

**Comment by Dasc3er** [comment]
La funzione dovrebbe essere quindi già completa, a patto che nell'importazione la colonna partita IVA sia selezionata dall'utente.
