### ISSUE TITLE
Numero di decimali

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#564]
Attualmente vengono gestiti i decimali di importi e quantità in base al numero di decimali definiti nelle impostazioni. I campi con i totali, ad esempio "TOTALE IMPONIBILE", "TOTALE IVA" ecc a fine tabelle, devono essere sempre a 2 cifre decimali per legge, anche se le righe sono a 4 decimali. Deve essere così sia a video che in stampa.
I moduli da aggiornare sono:
 - attività
 - preventivi
 - contratti
 - ordini
 - ddt
 - fatture
 - piano dei conti (qualsiasi importo)

Nella fattura elettronica è già così.

**Comment by Dasc3er** [comment]
La soluzione potrebbe essere ottenuta nella modifica del seguente metodo imponendo un round a due cifre:
https://github.com/devcode-it/openstamanager/blob/9b859a89bfe1f12383aaaac54a38da15782fdafc/include/src/Document.php#L108

In questo modo, tutti gli importi (relativi ai documenti, cioè i totali vari) ottenuti con il nuovo sistema delle classi sarà automaticamente gestito a due cifre decimali. Resterebbero quindi da aggiornare manualmente il piano dei conti e le attività, se si replica il funzionamento del file row-list.php dalle fatture agli altri documenti.

**Comment by loviuz** [comment]
Il calcolo attuale è corretto, basterebbe solo arrotondare in fase di visualizzazione, quindi alla fine. Credo basti a questo punto arrotondare nei vari file row-list.php e nel piano dei conti, e dove altro c'è un totale, subtotale o conteggio di totali.
