### ISSUE TITLE
MIGLIORIA: Possibilità di modificare gli importi nelle righe "Ore di lavoro"

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#568]
Attualmente è solo possibile indicare le nel modulo "Tecnici e tariffe"
Sarebbe utile poter modificare il costo orario, il costo a km e il diritto di intervento, senza per forza applicare uno sconto; quindi è necessario che i campi relativi siano visibili e modificabili
OSM 2.4.8

**Comment by loviuz** [comment]
Implementato nella 2.4.11 in sviluppo. @idraulicadueci hai modo di provare?

**Comment by idraulicadueci** [comment]
> 
> 
> Implementato nella 2.4.11 in sviluppo. @idraulicadueci hai modo di provare?

Sì. Tutto ok. Grazie
