### ISSUE TITLE
Introduzione hook

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#569]
## Comportamento richiesto

Per effettuare una serie di azioni predefinite al primo accesso al gestionale, si può implementare un sistema di hook richiamato a livello JS con un sistema di cache.
Propongo in particolare:
- classe di base Hook con il metodo astratto *handle*
- tabella **zz_hooks** con la classe che implementa l'hook e un valore per indicare la frequenza di esecuzione
- tabella **zz_hook_cache** collegata alla precedente, per memorizzare i risultati delle precedenti esecuzioni dell'hook

Tramite questo sistema è possibile implementare i controlli automatici sugli aggiornamenti, sulla presenza di ricevute e fatture elettroniche da importare.
Se per le ricevute può tornare utile l'importazione automatica, si può considerare di aggiungere un metodo facoltativo **action** che viene richiamato se l'utente clicca su una icona vicino al risultato dell'hook. In alternativa, cliccare sull'hook reindirizza alla pagina che può essere utilizzata per eseguire l'azione (plugin Ricevute).

**Comment by loviuz** [comment]
in linea di massima mi sembra vada bene. anche la cache, in modo da non eseguire troppe richieste continuamente. vediamo se nel frattempo arrivano altre proposte...

**Comment by Dasc3er** [comment]
@loviuz @lucasalva87 Ho introdotto gli hook come da issue, con la prima versione dedicata per le ricevute e le fatture da importare.

**Comment by Dasc3er** [comment]
Nel campo _frequency_ della tabella **zz_hooks** è possibile impostare un qualunque tipo di periodo in stringa secondo lo standard di PHP per la modifica delle date, al fine di eseguire l'hook ogni:
- `1 day` per 1 giorno/`15 days` per 15 giorni (e similmente con altri periodi)
- `1 day 12 hours 15 minutes` per 1 giorno, 12 ore e 15 minuti 

Documentazione: https://www.php.net/manual/en/datetime.formats.relative.php
