### ISSUE TITLE
mancato controllo duplica articoli

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#570]
Quando si duplica un articolo, non si dovrebbe riuscire a sovrascrivere i dati del codice origine.
Manca il controllo che il codice dell'articolo duplicato sia diverso da quello originale, altrimenti è solamente una modifica articolo.

* Versione del progetto: 2.4.8

**Comment by Dasc3er** [comment]
@pubblisoft Giustifica la tua logica...
È vero che si dovrebbe cambiare il codice articolo, ma l'obbligo è dalla parte dell'utente.

**Comment by pubblisoft** [comment]
Ci dovrebbe essere un avviso se cerco di salvare un codice esistente, altrimenti si rischia di sovrascrivere un articolo presente. Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [devcode-it/openstamanager] mancato controllo duplica articoli (#570)Da: Thomas Zilio A: devcode-it/openstamanager CC: pubblisoft ,Mention @pubblisoft Giustifica la tua logica...

È vero che si dovrebbe cambiare il codice articolo, ma l'obbligo è dalla parte dell'utente.

**Comment by Dasc3er** [comment]
Non è possibile sovrascrivere un articolo con il comando di duplicazione...
