### ISSUE TITLE
Generazione documenti aggiuntivi basati su template

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#571]
Salve,

sarebbe possibile aggiungere una funzionalità di generazione di documenti basati su template custom da allegare alle fatture (ad esempio dichiarazione di conformità, rapporto tecnico intervento, regola d'arte ecc...)?

Ho delle conoscenze di programmazione e posso provare ad implementare qualcosa e contribuirlo se c'è una documentazione che mi aiuta in questo.

Grazie

**Comment by Dasc3er** [comment]
Ciao @marcus905 ,
se sei interessato a contribuire, sia per modifiche che per strutture più complesse, sei il benvenuto!

Puoi trovare la documentazione tecnica del gestionale al seguente link: https://docs.openstamanager.com/docs
Si tratta di una versione di base della documentazione, che spiega in modo generale in funzionamento inteso per la maggior parte dei file dei moduli: ti consiglio quindi di controllare alcuni tra i moduli più semplici (IVA, Stati dei contratti/preventivi) per prendere dimestichezza con la struttura. Inoltre, se ci sono questioni poco chiare, puoi sempre contattarci tramite le issure specifiche della documentazione (https://github.com/devcode-it/openstamanager-docs) oppure via mail.

Per quanto riguarda la funzionalità che vorresti sviluppare, potresti indicare più nel dettaglio cosa vorresti produrre?

Se infatti l'obiettivo è di permettere la generazione di ulteriori stampe PDF, una funzionalità simile si può ottenere con i contenuti della cartella **templates/**.

Se invece desideri creare degli interi documenti (tipo fatture/ordini/ddt) la questione diventa più complessa soprattutto nel momento in cui è necessario che questi interagiscano tra di loro oppure effettuino azioni particolari a livello del gestionale.

Se invece l'obiettivo è di permettere il completamento di informazioni generali aggiuntive alle sole fatture, puoi vedere qualcosa di simile già implmentano (malgrado in modo abbastanza grezzo) nel modulo **Gestione componenti**, sotto **MyImpianti**: quando un componente viene aggiunto ad un impianto, vengono richiesti alcuni contenuti che l'utente può personalizzare attraverso il modulo in questione.

**Comment by marcus905** [comment]
Grazie mille delle info, cerco di procedere da ciò che mi hai detto allora!

**Comment by marcus905** [comment]
Ciao,

sto provando a vedere che posso mettere su, ma in ogni caso spiego qual'è il risultato sperato.

Il sistema lo sto mettendo su in uso per una ditta di assistenza tecnica, vendita e installazione di impianti termici (climatizzazione, raffrescamento e riscaldamento oltre che assistenza autorizzata per garanzia di alcuni marchi)

Le migliorie desiderabili sarebbero:
- stampa opzionale di un certificato di installazione e annessa dichiarazione di conformità dell'impianto a regola d'arte -- la stampa quindi sarebbe da includere da qualche parte in MyImpianti credo.
- la gestione dei contratti di assistenza, che c'è già, ma con l'aggiunta di una funzionalità di reminder di scadenza contratti al termine degli stessi via email e sms (per gli sms specificamente l'intenzione era di sviluppare un applicazione mobile che si interfacciasse con il sistema via rest/webservice, ottenesse i contratti in scadenza in un certo periodo con annesse anagrafiche e inviasse gli sms con l'uso della sim inserita)
- una gestione della revisione degli impianti (molto simile ai contratti, ma con qualche parametro in più ad es. bollino della revisione ecc)

Per procedere ad implementare queste cose da dove potrei iniziare a guardare e leggere il codice?

Eventualmente si potesse commissionare a voi lo sviluppo di queste funzionalità a pagamento (anche rilasciabili a sorgente aperto per tutti una volta sviluppate) quanto sarebbe il costo stimato o a chi dovremmo contattare?

Scusatemi il post lungo e tutte le domande, e grazie!

**Comment by Dasc3er** [comment]
Per quanto riguarda la stampa, puoi controllare la struttura della stampa Contratti (**templates/contratti**) e replicarla con le modifiche necessarie per il modulo Impianti. L'unica cosa che devi fare, dopo aver ottenuto i dati della stampa dal file **init.php**, è gestire la visualizzazione HTML con gli altri file (https://docs.openstamanager.com/docs/structure/stampe).

Per la gestione della revisione impianti, devi obbligatoriamente controllare il modulo Contratti (### modules/contratti): a quanto ne so la gestione delle revisioni avviene attraverso una duplicazione completa del documento e l'impostazione del campo _master_revision_ sulle revisioni precedenti, ma dovresti controllare più nel dettaglio il codice.

Infine, per la gestione dei reminder, esiste una funzionalità simile nelle Attività: se così impostato negli Stati, alla modifica dell'attività (aggiunta/rimozione sessioni, conclusione) vengono inviate delle mail dal gestionale ai tecnici interessati. Purtroppo questo è utile se i reminder devono essere eseguiti dopo una certa azione da parte del'utente, ma se sei interessato controlla questi commit https://github.com/devcode-it/openstamanager/search?q=notifiche&type=Commits.
Per l'integrazione con un qualcosa di esterno, è presente l'API: una descrizione generica è fornita qui (https://docs.openstamanager.com/docs/more/api), ma per il funzionamento effettivo ti consiglio di controllare la cartella **modules/interventi/api/**.
Se invece non c'è necessità che ci sia interfacciamento con l'esterno (come credo in questo caso), puoi provare ad integrare un nuovo hook: non esiste ancora una documentazione ufficiale poichè è una feature piuttosto nuova e in sviluppo, ma puoi controllare qui https://github.com/devcode-it/openstamanager/search?q=hook&type=Commits i file InvoiceHook.php e ReceiptHook.php, oltre che la issue #569.
L'idea alla base è che gli hook vengano eseguiti in background al primo accesso dopo un periodo di tempo variabile, ed eseguano una determinata serie di azioni fornendo un feedback all'utente. Per ora sono stato implementati per controllare automaticamente la presenza di nuove fatture o ricevute elettroniche, e prossimamente inseriremo un controllo automatico sugli aggiornamenti del gestionale.

Per commissionare lo sviluppo di queste funzionalità a pagamento, o anche per informazioni di vario genere, puoi contattarci via email all'indirizzo info@openstamanager.com.

Spero di essere stato utile 😄
