### ISSUE TITLE
MIGLIORIA: Nuova gestione sconti su riga

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#573]
MODULO ATTIVITÀ
Aggiungo un nuovo sconto (+Sconto/Maggiorazione)
Valorizzo i campi richiesti nella maschera di input (Descrizione, sconto/maggiorazione, IVA).
Nel riepilogo "altre spese" i valori che compaiono sono tutti a zero.
Clicco sul pulsante giallo (modifica riga) e valorizzo i campi quantità e prezzo unitario di vendita e, nuovamente, sconto unitario. A questo punto viene correttamente calcolato il valore dello sconto applicato sul valore inserito nel campo "presso unitario di vendita. I totali sono corretti.

Credo sia necessario rendere disponibili i campi non mostrati in prima istanza. A mio parere risulta superfluo il campo quantità, essendo uno sconto applicato su un sub-totale.

OSM 2.4.9

**Comment by Dasc3er** [comment]
Se non ho capito male, una volta aggiunto uno sconto viene modificato come una riga normale? In questo caso si tratta di un bug...

**Comment by idraulicadueci** [comment]
@Dasc3er esattamente. Credevo si dovesse fare una miglioria, e in realtà non sarebbe fatta male se si potesse impostare una base su cui calcolare lo sconto (es. sconto su totale ore lavorate), invece che sul totale documento.

**Comment by Dasc3er** [comment]
La funzionalità di sconto è una semplice traslazione dello sconto incondizionato, e manterrà la logica attuale anche in futuro.

Potrebbe invece essere utile aggiungere un campo per eventualmente personalizzare l'importo su cui applicare lo sconto percentuale, anche se si tratterebbe di una complicazione abbastanza considerevole...
@loviuz che ne pensi?

**Comment by loviuz** [comment]
@Dasc3er Secondo me lo sconto generico dovrebbe essere applicato al documento per intero solamente, altrimenti se devo applicare uno sconto specifico su ore, km, materiale o spese generiche c'è già la funzione si sconto sulle singole entità. Se non ho capito male...

**Comment by idraulicadueci** [comment]
Nella versione 2.4.10 funziona tutto bene.
