### ISSUE TITLE
Aggiornare data ricezione per le fatture già importate

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#575]
## Comportamento richiesto

Aggiornare campo DATA RICEZIONE per le fatture di acquisto già importate.

## Comportamento attuale

Il campo DATA RICEZIONE rimane vuoto per le fatture di acquisto già importate.

## Possibile soluzione

Effettuare un ciclo su tutte le fatture di acquisto nel file update/2_4_9.php in modo che mentre viene eseguito l'aggiornamento vengono inserite anche le date di ricezione mancanti.

## Contesto

* Modulo: Fatture
* Versione del progetto: 2.4.8/2.4.9
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by lucasalva87** [comment]
Con il fix 4cf9856c ora le data di ricezione mancanti sono state allineate con la data della fattura.
