### ISSUE TITLE
Impossibile utilizzare  OSM 2.4.8 con dispositivi Android.

### ISSUE THREAD

**Issue by ManicMiner2017** [devcode-it/openstamanager#576]
Alcuni bug rendono impossibile l' utilizzo di OSM 2.4.8 con dispositivi Android.
Ho testato l'applicativo con Android 4.1.1, 4.3,  5.1.1 e 8.0  ma in nessun caso sono riuscito ad utilizzare il software in maniera soddisfacente. I vecchi android 4.1 4.3 hanno seri problemi con la barra laterale che rimane aperta https://www.openstamanager.com/forum/viewtopic.php?f=10&t=92406  e che non permette un utilizzo. Con Android 5.1.1 e 8.0, il problema della barra laterale non c'é, ma é impossibile aggiungere voci nel calendario, mentre é possibile modificare le voci già immesse.

**Comment by Dasc3er** [comment]
Grazie per aver riportato la segnalazione dal forum!
Vedremo di fare il possibile, ma potrebbe trattarsi di un problema di compatibilità del framework che utilizziamo per la grafica con le versioni più vecchie dei browser Android.

**Comment by ManicMiner2017** [comment]
Qual' è il framework ? Ci sono segnalazioni di bug al riguardo?

**Comment by Dasc3er** [comment]
Il framework in questione è AdminLTE (https://github.com/ColorlibHQ/AdminLTE), ma non posso escludere che si tratti di un problema nostro e quindi ti sconsiglio di creare una segnalazione anche a loro.
Prossimamente comunque dovrebbe essere rilasciata una nuova versione del loro framework, che potrebbe risolvere nativamente il problema.

**Comment by ManicMiner2017** [comment]
Il problema con le sidebar é stato riscontrato!
https://github.com/ColorlibHQ/AdminLTE/issues/1778

**Comment by Dasc3er** [comment]
@ManicMiner2017 Il problema si risolverà in automatico con il fix relativo di AdminLTE.
Purtroppo non abbiamo modo di risolverlo manualmente.
