### ISSUE TITLE
Impossibile esportare le stampe (Azioni di gruppo) per le fatture di acquisto (Errore 500)

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#577]
## Comportamento attuale

Selezionando una o più fatture di acquisto e premendo Azioni di gruppo --> Esporta stampe le stampe non vengono esportate e la pagina di richiesta termina con un errore 500

## Possibile soluzione

Se l'errore è causato dal fatto che non tutte le fatture di acquisto hanno una stampa (o un PDF allegato) si potrebbe stampare invece la visualizzazione del file XML (file view.php)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Selezionare una o più fatture di acquisto
2. Premere Azioni di gruppo --> Esporta stampe

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Fatture di acquisto
* Versione del progetto: 2.4.8
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Nelle fatture di acquisto non è presente l'esportazione delle stampe (versione 2.4.9).
Se invece intendi nelle fatture di vendita, non sono riuscito a replicare il problema. Potrebbe comunque trattarsi di un qualche bug relativo alla selezione di una specifica fattura.

**Comment by maicol07** [comment]
Ok, era solo nelle fatture di acquisto
