### ISSUE TITLE
Totale e Totale netto non vengono visualizzati in Fatture di acquisto e di vendita

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#578]
## Comportamento attuale

Totale e Totale netto non vengono visualizzati in Fatture di acquisto e di vendita:
![immagine](https://user-images.githubusercontent.com/9463142/57794467-fe089400-7743-11e9-856e-3d5133cdd743.png)

## Contesto

* Modulo: Fatture di vendita, Fatture di acquisto
* Versione del progetto: 2.4.9
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by lucasalva87** [comment]
Non mi risultano queste colonne nelle 2.4.9

**Comment by maicol07** [comment]
Ah si totale netto, guadagno e totale IVA le ho aggiunte io, ma il totale è inclusa di default e ha la seguente query non modificabile:
`(SELECT SUM(subtotale - sconto + iva + rivalsainps - ritenutaacconto) FROM co_righe_documenti WHERE co_righe_documenti.iddocumento=co_documenti.id GROUP BY iddocumento) + bollo + iva_rivalsainps`
