### ISSUE TITLE
Marca da bollo applicata automaticamente anche per fatture emesse da soggetti che operano nel campo IVA

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#579]
## Comportamento attuale

la maarca da bollo viene applicata automaticamente anche per fatture emesse da soggetti che operano nel campo IVA

## Contesto

* Modulo: Fatture di vendita, Fatture di acquisto
* Versione del progetto: 2.4.9
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
@maicol07 Con il nuovo sistema è possibile impedire il calcolo automatico del bollo con il flag apposito.

**Comment by Dasc3er** [comment]
Se entri nelle fatture di vendità c'è una nuova sezione **Marca da bollo** con l'opzione **Marca da bollo automatica**.

**Comment by maicol07** [comment]
La devo deselezionare ogni volta?

**Comment by Dasc3er** [comment]
In alternativa per disabilitare sempre la marca da bollo automatica puoi impostare l'impostazione **Importo marca da bollo** a 0, ma in ogni caso devi comunque disabilitare l'opzione **Marca da bollo automatica** se vuoi inserire il bollo a mano nella fattura.

**Comment by Dasc3er** [comment]
Il caso particolare per soggetti che operano nel campo IVA non è da noi prevedibile, e quindi è necessario procedere manualmente.
