### ISSUE TITLE
dicitura DDT di vendita e DDT di acquisto non vengono indicati in stampa pdf 2.3 beta

### ISSUE THREAD

**Issue by robygladio** [devcode-it/openstamanager#58]
Ok stavolta purtroppo ghe semo
ho provato a pasticciare ovunque ma non ho capito ilperchè non mette la dicitura DDT xxxx sopra la tabella dettagli ddt in header (come invece fa per le fatture) nomi corretti link corretto..  tabelle mi sembrano corrette.. boh mi arrendo 

ho provato a modificare header e init.php insomma boooo :D:D

**Comment by loviuz** [comment]
corretto, non veniva settato in certi casi
