### ISSUE TITLE
BUG: Quantità da evadere nei preventivi non viene ripristinata

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#580]
Creo un preventivo di vendita e inserisco gli articoli. 
Dal preventivo creo l'ordine cliente. Elimino l'ordine.
Le quantità da evadere nel preventivo restano a zero, quindi non ho la possibilità di creare un nuovo ordine da quel preventivo.

OSM 2.4.9

**Comment by Dasc3er** [comment]
Il problema è stato risolto nella futura 2.4.11 con la standardizzazione delle quantità evase nel passaggio tra documenti.
