### ISSUE TITLE
MIGLIORIA: Riferimento a documenti correlati anche negli ordini

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#581]
Se creo una fattura da un preventivo, la dicitura "Rif. Preventivo..." compare (se flaggata l'opzione in impostazioni), però non in un ordine creato dallo stesso preventivo.

OSM 2.4.9

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere risolto nella futura versione 2.4.11.
