### ISSUE TITLE
MIGLIORIA: Possibilità di creare ordini a fornitore da preventivo di vendita

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#582]
mi riaggancio alla issue #358 
sarebbe utile anche poter creare direttamente l'ordine a fornitore dal preventivo cliente, questo perché quando il cliente accetta un preventivo, si passa direttamente all'ordine del materiale, senza necessariamente fare il passaggio a ordine cliente. Semmai sarebbe utile poter creare un contratto dal preventivo, passaggio che normalmente si fa negli appalti.

OSM 2.4.X

**Comment by loviuz** [comment]
@Dasc3er potrebbe essere una miglioria del modulo di riordino materiale a fornitori, anche se potrebbe essere che il preventivo diventa un ordine cliente e da lì poi funzionerebbe già.

**Comment by Dasc3er** [comment]
E' ora possibile creare un ordine fornitore a partire da un ordine cliente in stato Accettato.
Non sono però presenti riferimenti ufficiali tra i due ordini, poichè i riferimenti vengono esclusivamente utilizzati per la gestione delle evasioni delle quantità in un singolo flusso di denaro.
