### ISSUE TITLE
BUG modulo attività: elenco contratti vuoto

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#583]
Creo un contratto con il cliente A e cambio lo stato da bozza ad accettato.
Creo un attività per il cliente A. Nella casella di ripilogo CONTRATTO l'elenco a discesa è vuoto.

OSM 2.4.9

**Comment by Dasc3er** [comment]
Non si tratta di un bug: per la revisione degli stati del contratti solo quelli in stato "In lavorazione" sono utilizzabili nelle **Attività**. Puoi eventualemente cambbiare il compoertamenteo dal modulo **Stati dei contratti**.
