### ISSUE TITLE
Colonna updated_at mancante

### ISSUE THREAD

**Issue by ale82x** [devcode-it/openstamanager#588]
## Comportamento richiesto

caricare l'aggiornamento zip e eseguirlo senza errori

## Comportamento attuale

una volta caricato lo zip e avviato l'aggiornamento da il seguente errore

![Annotazione 2019-05-23 102716](https://user-images.githubusercontent.com/40036611/58238289-4711a700-7d47-11e9-9b8d-8ee435e50988.png)
![Annotazione 2019-05-23 102425](https://user-images.githubusercontent.com/40036611/58238290-47aa3d80-7d47-11e9-8d4f-d30436e1e457.png)

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. andare in strumenti - aggiornamenti
2. caricare il file zip
3. avviare l'aggiornamento

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```
il problema che controllando nei log non c'e nessun errore in apache logs, stranissimo
come se non ci sia nessun errore 
## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: aggiornamenti
* Versione del progetto: 2.4.9
* Versione PHP: 7.1.27
* Tipo di server: Apache (FPM) - Testato anche con Apache (FCGI)

**Comment by ale82x** [comment]
le immagini sono invertite...
prima mi da l'errore al 15% poi facendo aggiorna pagina da l'altro errore ma da li non si esce mai...

grazie mille

**Comment by lucasalva87** [comment]
Per favore controlla il contenuto della cartella logs che trovi nella directory dove risiede il gestionale.

**Comment by ale82x** [comment]
ecco l'errore

> 
[2019-05-23 17:03:41] Logs.EMERGENCY: Aggiornamento fallito: ALTER TABLE `co_statipreventivi` ADD `deleted_at` DATETIME NULL AFTER `updated_at` []
{"url":"/XXX/index.php?action=do_update&firstuse=false","ip":"11.22.33.44","http_method":"GET","server":"xxx.dominio.it","referrer":"https://xxx.dominio.it/openstam/index.php","unique_id":"XOa2TYi1TvWUqcj8@DKKNwAAADI","uid":"350c7db"}

**Comment by ale82x** [comment]
grazie

**Comment by Dasc3er** [comment]
Ciao @ale82x,
potresti provare ad accedere al database con PHPMyAdmin e controllare se la tabella **co_statipreventivi** ha già la colonna **deleted_at**?
In alternativa, devi comunque accedere al database nella tabella **updates** e trovare la riga _2.4.9_, dove devi aumentare di 1 la colonna **done**...

**Comment by Dasc3er** [comment]
@ale82x Potrei aver trovato il problema effettivo: la tua installazione non presenta la colonna **updated_at**, che viene inserito solo per versioni di MySQL >= 5.6.5.

Ti consiglio di aggiornare la versione di MySQL almento alla 5.6.5, poichè le precedenti non sono più supportate ufficialmente da Orcle (https://en.wikipedia.org/wiki/MySQL#Release_history).

**Comment by ale82x** [comment]
confermo che sul server è installata la versione
mysql 5.5.60 
quindi aggiorno la versione di mysql e poi faccio l'aggiornamento alla versione 2.4.9 o devo comunque controllare e aggiungere manualmente la colonna?

grazie mille

**Comment by Dasc3er** [comment]
Procedi così:
- Aggiorni MySQL
- Sostituisci i contenuti del file **update/2_4_9.sql** con quelli presenti a questo indirizzo: https://raw.githubusercontent.com/devcode-it/openstamanager/master/update/2_4_9.sql
- Segui le istruzioni per riprendere l'aggiornamento: https://docs.openstamanager.com/guide/configurazione/aggiornamento#ripresa-forzata

Non serve che modifichi il database in questo caso 😄

**Comment by ale82x** [comment]
ho fatto tutto.
l'aggiornamento adesso è andato a buon fine.

però accedendo alla sezione 
vendite - ordini clienti mi da il seguente errore

![Annotazione 2019-05-24 184159](https://user-images.githubusercontent.com/40036611/58343633-d60be580-7e53-11e9-9340-b284cebe47c5.png)

è ancora un errore del db?
adesso c'è installato mariadb 10.2

grazie

**Comment by ale82x** [comment]
aggiornando la pagina o rientrando l'errore cambia con

DataTables warning: table id=main_59 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

non so se può servire...

**Comment by ale82x** [comment]
ho trovato questo nei log

> [2019-05-24 18:54:52] Logs.ERROR: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Totale' {"code":"42S21","message":"SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Totale'","file":"/home/fatt3/public_html/osm/src/Database.php","line":239,"trace":"#0 /home/fatt3/public_html/osm/src/Database.php(239): PDO->prepare('SELECT COUNT(*)...')\n#1 /home/fatt3/public_html/osm/src/Database.php(313): Database->fetchArray('SELECT COUNT(*)...', Array)\n#2 /home/fatt3/public_html/osm/ajax_dataload.php(40): Database->fetchNum('SELECT or_ordin...')\n#3 {main}"}
{"url":"/osm/ajax_dataload.php?id_module=24&id_plugin=&id_parent=&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=false&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%

**Comment by ale82x** [comment]
nulla scusate... ma ho risolto.
avevo creato una "vista" personalizzata con il totale degli ordini.
credo che adesso sia una funzione di default quindi ho tolto il campo che avevo aggiunto e adesso funziona...

grazie mille
