### ISSUE TITLE
BUG: codice SDI non visualizzato nel file XML generato

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#589]
Codice SDI correttamente indicato nell'anagrafica, ma non visualizzato nei file XML delle fatture emesse.

OSM 2.4.9

**Comment by Dasc3er** [comment]
Non visualizzato on non presente? Perché per la visualizzazione non possiamo farci praticamente niente...

**Comment by idraulicadueci** [comment]
Nel file XML il campo codice destinatario è vuoto.

**Comment by Dasc3er** [comment]
@idraulicadueci Il campo **CodiceDestinatario** viene impostato correttaente.
Sei sicuro di averlo impostato nell'anagrafica relativa?

**Comment by idraulicadueci** [comment]
Mi sono reso conto che lo fa solo con le fatture accompagnatorie di vendita, mentre con quelle immediate il problema non si presenta.

**Comment by Dasc3er** [comment]
@idraulicadueci Il problema non si verifica.

E' possibile che tu abbia selezionato una **sede** per la fattura, e quindi venga riportato il codice destinatario della sede (0000000 se vuoto).

**Comment by idraulicadueci** [comment]
@Dasc3er proprio così!! scusa era la prima volta che facevo una fattura elettronica accompagnatoria e non avevo notato il campo Codice Destinatario nella sede.
Grazie!
