### ISSUE TITLE
Bug: Le notifiche non riportano gli allegati

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#590]
Durante l'invio di una notifica legata al cambio stato di un'attività non vengono riportati gli allegati come specificato nel relativo template.

**Comment by Dasc3er** [comment]
@lucasalva87 Ho notato che avevo previsto un metodo apposito **includeTemplatePrints** che effettua proprio l'azione richiesta. Sarebbe però da richiamare ogni volta che viene creata l'email.

Modifico quindi il comportamento di base per includere sempre le stampe del template, eventualmente resettandole manualmente?

**Comment by lucasalva87** [comment]
Sì, per me è la soluzione migliore. Di default vengono incluse sempre le stampe previste dal template e si resettano nel caso di un'impostazione manuale :+1:
