### ISSUE TITLE
BUG: stampa scadenzario

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#591]
Nello scadenzario applico il filtro anagrafica. Se clicco "stampa scadenzario" nel PDF generato il filtro non viene applicato.
Altro problema che riscontro: seleziono alcune scadenze dell'anagrafica filtrata tramite i checkbox a fianco delle righe e clicco stampa; in questo caso viene correttamente mostrato l'elenco delle righe selezionate, però il totale a fondo pagina corrisponde a quello delle righe filtrate nel modulo scadenzario.

OSM 2.4.9

**Comment by lucasalva87** [comment]
Con il commit: 8d2d0772803f60f00d481ec2e208b7052344f955 il problema della stampa dello scadenzario dovrebbe essere risolto

**Comment by idraulicadueci** [comment]
@lucasalva87 tutto ok. Grazie
