### ISSUE TITLE
visualizzazione in Opera

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#593]
La versione 2.4.9 ha qualche problema (che la 2.4.8 non aveva)  di visualizzare il contenuto di alcuni menu a tendina (per esempio lista clienti) nella compilazione fatture o ricerca di avvisi, con il Browser Opera. Funziona correttamente con Edge.

**Comment by lucasalva87** [comment]
Il gestionale non è mai stato testato con Opera, ma sicuramente effettueremo delle verifiche. Grazie per la segnalazione.
