### ISSUE TITLE
miglioria template preventivi

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#594]
vers. 2.4.9., file preventivi, fiel body.php 
nella sezione "CONDIZIONI GENERALI DI FORNITURA", mancherebbe la voce "GARANZIA",

del tipo:

<tr>
        <th>
            '.tr('Garanzia', [], ['upper' => true]).'
        </th>

        <td>
            '."12 mesi".'
        </td>
    </tr>

**Comment by Dasc3er** [comment]
Duplicato di #541.
