### ISSUE TITLE
Nuovo modulo testi predefiniti e relativa funzionalità

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#598]
Prevedere la possibilità di popolare i campi di testo presenti all’interno dei moduli con dei testi predefiniti gestiti da apposito nuovo modulo.

**Comment by Dasc3er** [comment]
Potresti spiegare meglio?

**Comment by lucasalva87** [comment]
Preparo degli screenshot e integro l'issue

**Comment by Dasc3er** [comment]
@lucasalva87 Idee al riguardo?
