### ISSUE TITLE
temi personalizzati e aggiornamenti

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#599]
avendo creato un tema personalizzato seguendo [le istruzioni ](https://docs.openstamanager.com/docs/base/assets)della documentazione che accortezze sono necessarie durante un aggiornamento della versione di OSM ? per esempio bisogna rigenerare il file theme.min.css con `yarn run build-OSM` ?
Supponendo di sviluppare in locale e poi fare l'upload dei file, devo anche caricare il css non-minified della cartella src sul server o basta caricare la cartella dist ?

**Comment by Dasc3er** [comment]
Certo, è necessario eseguire il comando build -OSM.
Per quanto riguarda i file da caricare, è sufficiente il file dist ma anche quello src non provoca problemi.

**Comment by beppe9000** [comment]
invece per gestire modifiche più sostanziali (index.php , include/top.php e bottom.php e asset tipo il logo) in modo da non perderle con gli aggiornamenti c'è qualche linea guida ?

**Comment by Dasc3er** [comment]
No, purtroppo non è possibile personalizzare il file **index.php**, ma dovrebbe essere permessa la modifica di **include/top.php** e **include/bottom.php** con file omonimi in **include/custom/**: la base del gestionale dovrebbe supportare questo sistema specifico.
Per quanto riguarda gli assets, a seguito di ogni aggiornamento devi eseguire nuovamente `yarn run build-OSM` per riconfigurare gli stili modificati; per i loghi ti consiglio di creare delle immagini con nomi diversi da quelli pre-esistenti e correggere manualmente i file che devono richiamarli (altrimenti devi sovrascriverle nella cartella dist dopo ogni aggiornamento).

**Comment by beppe9000** [comment]
penso che userò un hook per controllare gli asset sovrascritti e ripristinarli in automatico allora

**Comment by Dasc3er** [comment]
Purtoppo non abbiamo mai avuto il tempo per aggiungere questi hook, anche perchè dovremmo lavorarci parecchio per renderlo generale per ogni installazione: per implementarlo manualmente puoi modificare il metodo **updateCleanup** della classe **Update**, che però viene sovrascitta ad ogni aggioranmento...

Ti consiglio quindi di provare localmente, e successivamente fare una PR per proporre la modifica in generale. 😄

**Comment by beppe9000** [comment]
sarà fatto :)
