### ISSUE TITLE
Problema nel caricamento di un nuovo modulo via zip

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#6]
- nella documentazione Moduli.md la directory del modulo viene indicata col nome module_dir, ma nel file aggiornamenti/upload_modules.php viene utilizzata la dicitura directory, quindi il file MODULE deve essere diverso
- controllo ZIP su aggiornamenti/upload_modules.php errato credo: carico un file .zip e mi dice
 Errore: il file caricato non è zip. Manca un not su riga 17 penso:
 `elseif (strstr($filename, '.zip')) { --errore`
 dovrebbe essere
 `elseif (!strstr($filename, '.zip')) { --errore`

**Comment by Dasc3er** [comment]
Per il primo punto, la struttura del file **MODULE** è stata mantenuta per retro-compatibilità...
Di fatto, nel file upload_modules.php viene letto il parametro _module_dir_ e inserito nel campo _directory_.

Sarebbe forse più corretto rinominare il parametro?

**Comment by ldanese83** [comment]
Non mi sembra che Fabio l'abbia aggiunto, ma ci sarebbe anche questo problema sempre nel caricamento dello ZIP di un modulo:
Se sul file MODULE inserisco come module_options una query del tipo SELECT |select| FROM tabella, non viene letto perchè il carattere '|' barretta è un carattere speciale e non salva la query sul database mettendo uno 0 al suo posto. Però mi pare di capire che vada inserita per forza la dicitura |select| che viene poi sostituita con i campi delle viste. Se non è così allora non è un bug..

**Comment by Dasc3er** [comment]
Il problema viene risolto con l'aggiunta dei doppi apici attorno ai contenuti da inserire:
`module_options = "SELECT |select| FROM `tabella` HAVING 1=1"`

**Comment by loviuz** [comment]
@Dasc3er ok, va bene ;-)
secondo me si può chiudere se il resto è risolto
