### ISSUE TITLE
suggerimento (essenziale) manca Riga generica in preventivi

### ISSUE THREAD

**Issue by robygladio** [devcode-it/openstamanager#60]
come da titolo in preventivi non è possibile inserire ad esempio mano d'opera extra senza che sia inserita in articoli. 
sarebbe utile anche se non prettamente indispensabile 
però nei preventivi capita di inserire articoli non ancora acquistati e non catalogati.

**Comment by lepool** [comment]
Ho visto che se non scegli alcun articolo e immetti una descrizione, inserisce come riga quello che hai messo in descrizione.

**Comment by fpsoftware** [comment]
Confermo quanto scritto da @lepool , il campo "Articolo" non è obbligatorio, è quindi possibile aggiungere una riga senza collegare una scheda articolo.

**Comment by robygladio** [comment]
ups.. chiedo scusa non avevo proprio provato.. sto andando a manetta :):)
