### ISSUE TITLE
Errore aggiornamento (mancanza di campi updated_at)

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#600]
aggiornando alla 2.4.9 ho avuto questo errore: 
```
Logs.EMERGENCY: Aggiornamento fallito: ALTER TABLE `co_statipreventivi` ADD `deleted_at` DATETIME NULL AFTER `updated_at` []
```
facendo un po' di caccia al ladro (lettura utile: https://www.openstamanager.com/forum/viewtopic.php?t=91091 ) ho notato che nel db (setup iniziale 2.4.8) mancava la colonna `updated_at`.

Per risolvere ho usato questo script da mettere nella cartella di index e aprire da browser:

```
<?php
$skip_permissions = true;
include_once __DIR__.'/core.php';
include_once $docroot.'/update/api.php';
```
Successivamente aprire l'url di osm aggiungendo `?force` come parametro

Condivido qua il mio problema e la mia soluzione in caso capiti ad altri ;)

Magari si potrebbe far pendere lo sviluppo anche verso la resilienza agli errori in fase di aggiornamento (ad esempio controlli più stretti o usando transazioni sql e quant'altro...). Nel mio caso ovviamente tutto il gestionale era divenuto inservibile  🤦

**Comment by Dasc3er** [comment]
@beppe9000 Il problema era già stato segnalato e risolto con la issue #588: si trattava infatti di una svista nella creazione dell'aggiornamento.
Il problema era causato da un tentativo di mantenere la compatibilità con versioni più vecchie di MySQL, che però prossimamente potrebbero non essere più considerate: #355.

Ti consiglio pertanto di aggiornare MySQL.

**Comment by beppe9000** [comment]
```
[th@k2 osm]$ mysql -V
mysql  Ver 15.1 Distrib 10.0.38-MariaDB, for Linux (x86_64) using readline 5.1
```
👍

**Comment by Dasc3er** [comment]
Purtroppo non so quali sono i requisiti per MariaDB, che non è supportato ufficialmente...

**Comment by beppe9000** [comment]
È funzionalmente equivalente a MySQL 5.7, per supportarlo ufficialmente basta verificare che non usiate funzioni esclusive di mysql dai vari elenchi di incompatibilità del sito loro (ci stanno per ogni versione)

https://mariadb.com/kb/en/library/incompatibilities-and-feature-differences-between-mariadb-103-and-mysql-57/
