### ISSUE TITLE
Come fare override di alcune stringhe ?

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#602]
Sono supportati più file `*.po` per la stessa lingua (italiano) ?

Ho provato ad inserire questo in `/locale/it/it.po`:
```
"Project-Id-Version: OpenSTAManager\n"
"POT-Creation-Date: 2018-09-03 15:45+0200\n"
"PO-Revision-Date: 2018-09-03 15:46+0200\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: it_IT\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.1.1\n"
"X-Poedit-Basepath: ..\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-KeywordsList: tr\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPathExcluded-0: .svn\n"
"X-Poedit-SearchPathExcluded-1: assets\n"
"X-Poedit-SearchPathExcluded-2: backup\n"
"X-Poedit-SearchPathExcluded-3: vendor\n"
"X-Poedit-SearchPathExcluded-4: assets\n"
"X-Poedit-SearchPathExcluded-5: bower_components\n"
"X-Poedit-SearchPathExcluded-6: node_modules\n"
"X-Poedit-SearchPathExcluded-7: logs\n"
"X-Poedit-SearchPathExcluded-8: files\n"
"X-Poedit-SearchPathExcluded-9: docs\n"
"X-Poedit-SearchPathExcluded-10: .*\n"
"X-Poedit-SearchPathExcluded-11: *.log\n"
"X-Poedit-SearchPathExcluded-12: *.md\n"
"X-Poedit-SearchPathExcluded-13: *.json\n"
"X-Poedit-SearchPathExcluded-14: *.lock\n"
"X-Poedit-SearchPathExcluded-15: *.phar\n"
"X-Poedit-SearchPathExcluded-16: *.css\n"
"X-Poedit-SearchPathExcluded-17: *.js\n"
"X-Poedit-SearchPathExcluded-18: .git\n"

msgid "Magazzino automezzo"
msgstr "Articoli contenuti"

```

Non sembra venire caricato... anche se vedo che nel codice dovrebbe aprire tutti i file in quella cartella...

https://github.com/devcode-it/openstamanager/blob/bb70fb7f4ee8d7ee1c2524941b1fa09b7169f411/core.php#L155

https://github.com/devcode-it/openstamanager/blob/b78503192e07d3307e12df51db436afdc33bb279/src/Translator.php#L43-L49

Devo cambiare qualcosa nelle intestazioni ?

**Comment by Dasc3er** [comment]
Credo sia presente un controllo per evitare l'inclusione del file italiano, ma devo controllare...
Se vuoi fare personalmente, dovrebbe essere tutto gestito dalla classe Translator

**Comment by beppe9000** [comment]
Stavo vedendo qua ma non ho (ancora) trovato nulla di irregolare...
https://github.com/devcode-it/openstamanager/blob/b78503192e07d3307e12df51db436afdc33bb279/src/Translator.php#L279-L300

**Comment by Dasc3er** [comment]
Controllando il codice credo che importiamo direttamente solo i file *.mo* (ottenibili dai *.po*), che dovrebbero essere appositamente dedicati...
Se suggerisci anche l'importazione dei file *.po*, potresti indicare quali miglioramenti comporterebbe?

**Comment by beppe9000** [comment]
sicuramente l'importazione diretta permette di evitare un passaggio in più in fase di personalizzazione :)
c'è un tool da linea di comando per produrre un _.mo_ su windows?

**Comment by Dasc3er** [comment]
Avevamo impostato il tutto in questo modo per rendere più rapido il gestionale nell'interpretazione dei file delle traduzioni.
Nel caso ti serva, per tradurre o modificare i nomi delle componenti del gestionale salvate a database ti consiglio l'utilizzo del campo *title*, presente nei moduli generali proprio a questo fine :smile:

**Comment by beppe9000** [comment]
Comunque un'altra soluzione sarebbe di controllare se esistono file .po nella cartella e se non esistono file mo con lo stesso nome si possono [compilare direttamente in quel momento](https://github.com/bigwhoop/potomoco). Impatto di performance quasi nullo perchè questo avviene solo la prima volta e poi funziona regolarmente.

Riapro perchè mi sembra pure facile come implementazione, e anche se al momento io sono occupato ma in futuro (non ben definito) ci metterò sicuramente mano

**Comment by Dasc3er** [comment]
Se ci sono novità crea pure una Pull Request relativa!
Grazie per i contributi... 😄
