### ISSUE TITLE
Modifica intestazione "Targa" degli automezzi ?

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#603]
Non riesco a modificare l'intestazione "Targa" copiando copiando e modificando il file sia in `osm/modules/automezzi/custom/ajax/search.php` che `osm/modules/automezzi/ajax/custom/search.php`.

BTW non dovrebbe usare la funzione di traduzione `tr`?

**Comment by beppe9000** [comment]
Anche modificando quel file non riesco a cambiare l'intestazione....
Sono approdato qui ma è tutto di sola lettura ?
![image](https://user-images.githubusercontent.com/6625123/59102919-c26d7e00-892d-11e9-80ab-a877fab7385c.png)

**Comment by Dasc3er** [comment]
Purtroppo le tabelle** zz_views** non presentano il campo title (a che ricordo), quindi al momento la modifica non è possibile senza modificare il nome.

Non è possibile utilizzare il metodo *tr* per valori salvati a database.

**Comment by beppe9000** [comment]
> Purtroppo le tabelle **zz_views** non presentano il campo title (a che ricordo), quindi al momento la modifica non è possibile senza modificare il nome.
> 
> Non è possibile utilizzare il metodo _tr_ per valori salvati a database.

Inizialmente pensavo fosse definito in search.php ma quando continuava a comparire ho compreso che era nel db... -_-

Ma il nome lo posso modificare senza problemi se lo modifico anche in search.php o viene usato anche altrove?

**Comment by Dasc3er** [comment]
In realtà lo usiamo per aggiornare i campi, quindi ti consiglierei di mettere il flag *enabled* a 0 e creare una nuova riga con le modifiche che desideri.

**Comment by beppe9000** [comment]
quindi copio la riga e gli cambio il nome, enabled=0 e l'id giusto ?

**Comment by Dasc3er** [comment]
Esattamente : smile:

**Comment by beppe9000** [comment]
Non trovo la colonna `enabled`. Intendevi `visible` ?

**Comment by Dasc3er** [comment]
Mmmh... Effettivamente non avevamo previsto una colonna _enabled_ per la tabella **zz_views**.
Puoi nascondere il campo con il campo _visible_, ma verrà comunque richiamato nella query e semplicemente non verrà mostrato 😄  

Potrebbe però essere utile l'aggiunta del campo _enabled_ 
@loviuz

**Comment by beppe9000** [comment]
Ho fatto ma non mi compare l'intestazione nuova...

**Comment by Dasc3er** [comment]
Ora devi andare nel modulo Viste ed aggiungere i permessi...

**Comment by beppe9000** [comment]
giustamente dovevo mettere default=0 per poterle modificare
