### ISSUE TITLE
BUG: Problema con le sedi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#604]
Entro dentro un'anagrafica, clicco SEDI e aggiungo una nuova sede.
Se inserisco il codice destinatario e salvo, il dato non viene salvato. Inoltre non riesco a eliminare la sede.

OSM 2.4.9

**Comment by lucasalva87** [comment]
Grazie per la segnalazione il fix dovrebbe risolvere il problema segnalato.

**Comment by idraulicadueci** [comment]
@lucasalva87 adesso tutto ok. Grazie
