### ISSUE TITLE
Aggiunta personalizzazione nome allegati delle stampe

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#606]
Vari utenti chiedono di poter personalizzare il nome del file PDF generato. Ad esempio, il PDF dell'intervento potrebbe diventare da **"Intervento.pdf"** a **"Int. 001 - Mario Rossi.pdf"**.

L'idea potrebbe essere di aggiungere un ulteriore campo in `zz_prints,` chiamato `template_name`, dove il nome viene definito sfruttando `variables.php` e con lo stesso formato dell'oggetto e del corpo email, inserendo fra parentesi graffe il nome del campo da sostituire. Per riprodurre l'esempio sopra, in questo caso template_name diventerebbe **"Int. {codice} - {ragione_sociale}.pdf"**.

Questo soprattutto in fase di aggiunta stampe nelle email da inviare, in modo che il destinatario possa archiviare l'allegato con dei nomi "parlanti".

@Dasc3er @lucasalva87 @Bacca1997 @CJBeppe @NicNal

**Comment by Dasc3er** [comment]
Può essere una buona idea per i template predefiniti.

Invece, per le mail attraverso il modal, possiamo prevedere un select singolo sugli allegati con input a parte per il nome, in modo simile agli indirizzi e-mail.

**Comment by Dasc3er** [comment]
In riferimento: #297

**Comment by Dasc3er** [comment]
Il campo si chiama `filename`, e permette la sostituzione dei valori indicati in **variables.php** oltre che alle sostituzioni naturali delle stampe (`$replaces` e `$custom`).
