### ISSUE TITLE
Api: ricerca tramite caratteri jolly nessun record trovato

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#607]
Se si effettua una chiamata api sfruttando i caratteri jolly come descritto qui:
https://docs.openstamanager.com/docs/more/api#personalizzazione
Non vengono restituiti risultati.

Es.
/api/?token=wEWqeyJ4kBBADKVILf7hLcG2KsIqiOZJ&resource=zz_logs&filter[username]=[adm%]

**Comment by Dasc3er** [comment]
Questo perché non è supportata.

**Comment by lucasalva87** [comment]
Quindi andrebbe rivista la documentazione? Anche il parametro order sembra non funzionare.

**Comment by Dasc3er** [comment]
Se serve, bisogna creare una resource apposita per la tabella, come si dovrebbe fare.
L'accesso diretto alle tabelle è solo temporaneao, e in futuro sarà rimosso per maggiore sicurezza.

In realtà, sarebbe ancora meglio rimuoverlo da subito visto che fino ad ora tutte le risorse utilizzate sono quelle implementate manualmente.
