### ISSUE TITLE
BUG: Importo scadenza non coincide con totale fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#608]
In fondo alla stampata fattura l'importo "Netto a pagare" e Importo indicato in scadenze non sono uguali.

![IMG](https://user-images.githubusercontent.com/40104356/59528939-e6a5fd80-8edf-11e9-9170-5cf5bfb46de6.png)

**Comment by Dasc3er** [comment]
@idraulicadueci Saresti in grado di fornire le informazioni relative alle righe della fattura?

**Comment by idraulicadueci** [comment]
![IMG](https://user-images.githubusercontent.com/40104356/63802530-21caa100-c913-11e9-9bf7-317ff1f9f968.png)
