### ISSUE TITLE
beta 2.3 iva fatturazione generica e iva articolo

### ISSUE THREAD

**Issue by robygladio** [devcode-it/openstamanager#61]
Vi segnalo che impostando un'iva fatturazione generica al 22% poi la tiene per tutti gli articoli. 
Anche quelli che hanno iva al 4% vengono registrati con iva 22 quindi vanno modificati a mano. 
(sperando di accorgersi prima della mancata quadratura fatture :)) 

mi sembra di ricordare il problema come già segnalato per la versione stabile ma ve lo ricordo anche qua ;)

**Comment by loviuz** [comment]
corretto. se c'è un'iva specifica nell'articolo viene utilizzata quella, altrimenti viene usata l'iva generica.

**Comment by loviuz** [comment]
corretto anche su ddt, preventivi e ordini
