### ISSUE TITLE
BUG elenco articoli dopo applicazione filtro

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#611]
Nell'elenco articoli, inserisco un nuovo articolo, compilo i campi. Quando torno all'elenco la pagina è vuota.

OSM 2.4.9

**Comment by lepool** [comment]
Ho appena fatto una prova con la mia 2.4.9 . A me non mi si presenta l'errore come descritto da te. 
Hai forse dei log di errore ?

**Comment by idraulicadueci** [comment]
Stranamente anche a me l'errore non si ripresenta. Cerco di riprodurre la procedura con cui il bug si è presentato e poi ti aggiorno.

**Comment by idraulicadueci** [comment]
@Dasc3er il problema si presenta di nuovo. Non riesco a capire cosa crei il bug, però quello che ho fatto l'ultima volta è di filtrare un articolo e apporvi delle modifiche (non il codice) come prezzo, categoria, ecc. Quando clicco "TORNA ALL'ELENCO", mi appare l'elenco vuoto, fra l'altro senza la dicitura "La ricerca non ha portato alcun risultato.".
Non si potrebbe fare in modo che con il click su "TORNA ALL'ELENCO" si azzerino i filtri applicati in precedenza?
