### ISSUE TITLE
BUG sconto percentuale in attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#612]
Inserisco uno sconto maggiorazione e valorizzo il campo "sconto percentuale"

![immagine](https://user-images.githubusercontent.com/40104356/59962524-eeb8fb00-94e6-11e9-9f01-ff7d03f864fc.png)

lo sconto non viene preso. Tutto ok invece per lo sconto in €

![immagine](https://user-images.githubusercontent.com/40104356/59962530-19a34f00-94e7-11e9-802f-7d9ee60e8638.png)

**Comment by loviuz** [comment]
Lo sconto percentuale calcola lo sconto effettivo in base al totale delle righe già inserite. Nell'esempio che hai inviato non vedi altre righe con un totale maggiore di 0 prima dello sconto, credo che il problema sia questo. Prova ad inserire con "+ Altre spese..." delle righe con un importo maggiore di 0 e poi applicare lo sconto, dovrebbe funzionare.

**Comment by idraulicadueci** [comment]
@loviuz ho provato, ma il problema persiste. Considera che lo sconto in euro lo prende normalmente, quello in % no; la funzione non dovrebbe servire ad applicare uno sconto, alla stregua di quello incondizionato? Quindi tenere conto del totale, incluse ore di manodopera e articoli?

**Comment by loviuz** [comment]
Forse ho capito il problema: credo sia solo un fraintendimento, perché lo sconto applicato su "Altre spese" è calcolato solo sulle altre spese inserite, non su manodopera, km, diritto chiamata e articoli.

Sarebbe stato introdotto in sostituzione dello sconto incondizionato, per cui effettivamente il calcolo dovrebbe farlo sul totale del costo intervento...

**Comment by Dasc3er** [comment]
In riferimento: #555

**Comment by loviuz** [comment]
Approfitto anche per dire che forse le attività andrebbero uniformate come fatture e ddt, mantenendo un'unica tabella con i costi, così anche lo sconto verrebbe uniformati. Per ora non cambierei il funzionamento dello sconto

**Comment by Dasc3er** [comment]
Con la versione in sviluppo (2.4.11) la gestione degli Interventi è stata parzialmente implementata con le nuove classi e la grafica relativa è stata migliorata.
In generale, gli sconti vengono applicati sugli importi dovuti a spese e articoli secondo la logica presente in ogni altro documento: per applicare sconti sulle sessioni esistono i campi appositi.
