### ISSUE TITLE
Aggiungere nuovi controlli in javascript ?

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#614]
Stavo implementando una schermata personalizzata per la movimentazione di articoli dove volevo raccogliere nel modal form di creazione delle entità tutti i dati necessari, tra cui articoli e quantità relative.

Non sapendo a priori quali articoli saranno selezionati pensavo di implementare una tabella dinamica in js con bottone per aggiungere le righe.

In ogni riga quindi ci sarebbero quindi almeno due elementi: un articolo e la quantità da spostare.

Per specificare l'articolo ho usato questo codice qua:
```
{[ "type": "select", "label": "Articoli", "name": "articoli_selezionati[]",
"value": "", "ajax-source": "articoli", "required": 1 ]}
```
Il problema mi si pone quando occorre aggiungere una riga dinamicamente.... come è possibile aggiungerere un nuovo campo di quel tipo in JS?

**Comment by Dasc3er** [comment]
Ti consiglio di controllare la struttura del modulo Viste, che inserisce proprio nuovi campi tramite JS.

**Comment by beppe9000** [comment]
Ottimo gli do' un'occhiata

**Comment by beppe9000** [comment]
Invece per quanto riguarda la validazione dei form dove potrei agire per inserire dei controlli da fare prima dell'invio, per esempio correttezza di alcuni campi (quantità diversa da zero, etc..)?

**Comment by Dasc3er** [comment]
Alcuni controlli di sono nativi nel formato semplificato (sulla quantità, per esempio), ma ti consiglio di implementarli manualmente.
Se hai consigli per un sistema generalizzato di validazione scrivi pure :smile:

**Comment by beppe9000** [comment]
Più che altro come al solito il mio dubbio nasce dal *dove* mettere il codice... sempre per la compatibilità con gli aggiornamenti...
<hr>
Se devo dare un consiglio suggerirei (oltre alle validazioni client-side) di fare un 'validation.php' customizzabile nei vari moduli che viene chiamato in ajax quando si invia un form e in base al risultato (un array json che abbia come indici i nomi dei campi e un messaggio di errore) annullare l'invio e mostrare invece i vari errori all'utente. In caso non ci siano errori si procede con la chiamata definitiva all'endpoint per inviare i dati. Una cosa del genere secondo me permette di avere un sistema abbastanza generico ma sopratutto flessibile perchè viene esteso all'occorrenza.

**Comment by beppe9000** [comment]
In sintesi per aggiungere un campo per selezionare un articolo dinamicamente è sufficiente questo:
```JavaScript
let cd = Date.now();
let template_9802212776dd73b010746e2a4e20ed48 = `<select type="select"
 name="art${cd}[id]" ajax-source="articoli" id="art${cd}-id" 
class="form-control superselectajax dynamic-select" data-source="articoli" 
placeholder="- Seleziona un'opzione -" data-placeholder="- Seleziona un'opzione -" 
data-parsley-errors-container="#art${cd}-id-errors" required></select>
<div id="art-${cd}-id-errors"></div>`;

$('#target').append(fullRow); // lo mettiamo da qualche parte
start_superselect(); // e si rigenera l'interfaccia di selezione

```
Sai invece come è possibile fare si che ogni prodotto sia inseribile una sola volta?

Come prima soluzione si potrebbe 'reagire' al fatto che venga fatta una nuova selezione. 

Pensavo una cosa del genere... 
```JavaScript
$('#modal select.dynamic-select').on('change', function(){
   // qui controllo se tra tutti i dynamic-select esiste il valore a cui si riferisce l'evento
  // in caso positivo svuoto il valore del select
 });
```

Però rimane l'inconveniente che nel menu a tendina per selezionare un prodotto ci troverò anche quelli già inseriti... È in qualche modo possibile collegarsi all'interfaccia e filtrare le opzioni del select prima che vengano mostrate?

**Comment by Dasc3er** [comment]
Per filtrare le opzioni mostrate dal select puoi provare ad implementare un controllo JS apposito, ma credo tu debba farlo manualmente.
In alternativa, se stai utilizzato la funzione di select tramite Ajax puoi provare a utilizzare le sessioni per passare i dati (trovi molti esempi nel modulo Interventi).

**Comment by beppe9000** [comment]
Ho visto che si può risolvere aggiungendo del codice a `lib/functions.js`

```

// Select
function start_superselect() {
    // Statico
    $('.superselect').each(function () {
        $this = $(this);
        $(this).select2({
            theme: "bootstrap",
            language: "it",
            width: '100%',
            maximumSelectionLength: $this.data('maximum') ? $this.data('maximum') : -1,
            minimumResultsForSearch: $this.hasClass('no-search') ? -1 : 0,
            allowClear: $this.hasClass('no-search') ? false : true,
            templateResult: function (data, container) {
                var bg; // templateSelection

                if (data._bgcolor_) {
                    bg = data._bgcolor_;
                } else if ($(data.element).attr("_bgcolor_")) {
                    bg = $(data.element).attr("_bgcolor_");
                } else if ($(data.element).data("_bgcolor_")) {
                    bg = $(data.element).data("_bgcolor_");
                }

                if (bg) {
                    $(container).css("background-color", bg);
                    $(container).css("color", setContrast(bg));
                }

                return data.text;
            },
            escapeMarkup: function (text) {
                return text;
            }
        });
    });

    // Dinamico (AJAX, per tabelle con molti record)
    $('.superselectajax').each(function () {
        $this = $(this);

        $(this).select2({
            theme: "bootstrap",
            language: "it",
            maximumSelectionLength: $this.data('maximum') ? $this.data('maximum') : -1,
            minimumInputLength: $this.data('heavy') ? 3 : 0,
            allowClear: true,
            escapeMarkup: function (text) {
                return text;
            },
            templateResult: function (data, container) {
                var bg; // templateSelection

                if (data._bgcolor_) {
                    bg = data._bgcolor_;
                } else if ($(data.element).attr("_bgcolor_")) {
                    bg = $(data.element).attr("_bgcolor_");
                } else if ($(data.element).data("_bgcolor_")) {
                    bg = $(data.element).data("_bgcolor_");
                }

                if (bg && !$("head").find('#' + data._resultId + '_style').length) {
                    $(container).css("background-color", bg);
                    $(container).css("color", setContrast(bg));
                }

                return data.text;
            },
            ajax: {
                url: globals.rootdir + "/ajax_select.php?op=" + $this.data('source'),
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        search: params.term,
                        page: params.page || 0,
                        length: params.length || 100,
                    }
                },
                processResults: function (data, params) {
                    params.page = params.page || 0;
                    params.length = params.length || 100;

                    var response = {
                        results: data.results,
                        pagination: {
                            more: (params.page + 1) * params.length < data.recordsFiltered,
                        }
                    };

                    // <<-------in questo punto rimuovo dai risultati non desiderati da response       

                    return response;
                },
                cache: false
            },
            width: '100%'
        });
    });
}

```

Siccome è un po' brutale come soluzione (e considerando che non si possono cambiare le impostazioni di select2 una volta inizializzato) vorrei proporre come miglioria la possibilità di utilizzare un evento personalizzato di jquery come callback di `processResults` per permettere di usare questa funzionalità con maggiore semplicità, con `processResults` che diventa una cosa del genere...

_(non sono troppo sicuro della sintassi, ma dovrebbe rendere l'idea)_

```


processResults: function (data, params) {
                    params.page = params.page || 0;
                    params.length = params.length || 100;

                    var response = {
                        results: data.results,
                        pagination: {
                            more: (params.page + 1) * params.length < data.recordsFiltered,
                        }
                    };

                    // questo permette di fare modifiche prima di usare la lista di opzioni da ajax
                    $this.triggerHandler("osm:select:processResults", [data, params, response]);               

                    return response;
                }

```

Quindi poi basta fare così per poter modificare i risultati appena vengono ricevuti nel browser:

```
$("#categoria").on("filter_results", function(e, data, params, response){
   // ... qui si può manipolare response.results per fare eventuale filtraggio o integrazione dei risultati
});
```

Sarebbe interessante poter filtrare anche i select statici, però....

**Comment by Dasc3er** [comment]
@beppe9000 Per quanto riguarda la validazione dei campi, è stata introdotta una nuova funzione nel commit 8d48d5c2 per il controllo sui valori più complessi (partita iva, codice fiscale, ...).

**Comment by Dasc3er** [comment]
Per quanto riguarda il tuo ultimo post, il modo corretto e più semplice per gestire il filtraggio è aggiungere il controllo a livello PHP: salvi nella sessione superselect gli id selezionati in precedenza e li filtri nella query che si occupa della presentazione dei risultati.

**Comment by beppe9000** [comment]
> @beppe9000 Per quanto riguarda la validazione dei campi, è stata introdotta una nuova funzione nel commit [8d48d5c](https://github.com/devcode-it/openstamanager/commit/8d48d5c2e71ee88e00c1a8d4f083736a2ed78e1a) per il controllo sui valori più complessi (partita iva, codice fiscale, ...).

questo mi semplificherà la vita anche su altri fronti :)

> Per quanto riguarda il tuo ultimo post, il modo corretto e più semplice per gestire il filtraggio è aggiungere il controllo a livello PHP: salvi nella sessione superselect gli id selezionati in precedenza e li filtri nella query che si occupa della presentazione dei risultati.


MA gli id selezionati quando vengono passati a php? Dovrei definire sia una validazione ajax che una sorgente ajax per sapere gli id e filtrarli in uscita, giusto ?



per rendere un select ajax dove vado a definire il file php se per esempio nel codice del campo inserisco `ajax-source="articoli_filtro_ajax"`

**Comment by Dasc3er** [comment]
>Qui però mi sipone un altro problema. Se vengono aperte due finestre sullo stesso modulo senza inviarlo il controllo duplicati creerà problemi perchè nel secondo modulo non saranno presenti gli id selezionati nel primo.
Questo è un problema noto e sarà risolto nella versione 2.5. Semplicemente, una soluzione più complessa a livello JS non ci è utile per la soluzione del problema che hai posto, poichè non ci si è mai presentato prima

>Quindi per esempio nel codice di un select per articoli inserisco ajax-source="articoli_univoci_ajax" e "validation": "articoli_univoci_ajax_validazione", quindi dovrei creare /modules/articoli/custom/ajax.php e /modules/articoli/custom/validation.php e agire in base al parametro (che sarà il nome passato a quegli attributi ed escludere gli id dalla sessione, giusto?
Mi sembra tu abbia compreso il funzionamento di base ma non l'utilizzo della funzione: il file validation.php è solo per controllare che un valore inserito sia valido (partita iva corretta, eventualmente non presente a database) e non ha nessuna relazione con il select.

**Comment by beppe9000** [comment]
> Per quanto riguarda il tuo ultimo post, il modo corretto e più semplice per gestire il filtraggio è aggiungere il controllo a livello PHP: salvi nella sessione superselect gli id selezionati in precedenza e li filtri nella query che si occupa della presentazione dei risultati.

Allora non ho capito come salvo la selezione.

**Comment by Dasc3er** [comment]
@beppe9000 Per la soluzione ti consiglio di attendere la 2.5, dove i contenuti della richiesta AJAX per il select sono salvati nell'HTML del select stesso. Il completamento della modifica sarà comunque piuttosto complesso, quindi non esiste ancora una data di rilascio effettivo o una lista di ulteriori modifiche previste.
