### ISSUE TITLE
totale mancante in vendite - fatture di vendita da aggiornamento 2.4.9

### ISSUE THREAD

**Issue by ale82x** [devcode-it/openstamanager#615]
## Comportamento richiesto

andando nella sezione 
vendite - fatture di vendita 
vedere il totale delle varie fatture

## Comportamento attuale

nella colonna totale non si vede nulla se non per le fatture vecchie, prima dell'aggiornamento 2.4.9

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. vendite - fatture di vendita 
2. controllare la colonna totale
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: 
* Versione del progetto: 2.4.9
* Versione PHP: 7.1.30
* Tipo di server: Apache 2.4.6 + mysql 10.2.25

**Comment by Dasc3er** [comment]
Le soluzioni sono indicate al seguente post del forum: https://www.openstamanager.com/forum/viewtopic.php?f=10&t=92646

**Comment by ale82x** [comment]
scusate se non ho cercato...
usata la soluzione consigliata e funziona tutto ok
grazie mille ancora
