### ISSUE TITLE
Nomeclatura Eloquent

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#616]
https://github.com/devcode-it/openstamanager/blob/ca9a480f92ba92821ea5c2ea39081be5037f7d98/view.php#L21

Non avrebbe più senso usare `$file->getOriginal()` qui?

**Comment by Dasc3er** [comment]
@beppe9000 Utilizziamo le componenti nativa di Eloquent (parte del framework Laravel) per la gestione a oggetti del database. Non è quindi disponibile il metodo `getOriginal`, ma `getOriginalAttribute`.
In generale, per accedere ai campi, cerchiamo di utilizzare gli attributi diretti forniti da Eloquent.

**Comment by beppe9000** [comment]
Chiedevo, perchè ho notato che è definito come `protected` quindi non dovrebbe essere accessibile dall' contesto nel quale viene eseguito il codice
