### ISSUE TITLE
Transazioni SQL

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#617]
ci sono degli esempi di utilizzo delle transazioni sql per 'update dei campi nei vari `actions.php' ?
prevedete ulteriori sviluppi verso questa direzione?

sicuramente potrebbe essere utile per operazioni che richiedono più query, come ad esempio i vari `op=editriga`

**Comment by Dasc3er** [comment]
Al momento tutte le azioni eseguite nei vari `actions.php` sono gestite attraverso una transazione che viene automaticamente inizializzata dal gestionale nel file `actions.php` della cartella principale.

**Comment by beppe9000** [comment]
quindi in caso di errori basta fare un `exit();` ?

**Comment by Dasc3er** [comment]
In caso di errore durante le operazioni la transazione non viene eseguita, quindi non c'è nessuna modifica nel database.
Se invece intendi causare tu il blocco, è sufficiente un `exit`.

**Comment by beppe9000** [comment]
Si, intendevo errori logici non eccezioni 😉 
Bisogna anche ricordarsi che vale anche il contrario, se si vuole terminare prima l'esecuzione è necessario fare il commit della transazione prima di chiamare `exit`. Ci sono stato un bel po' a fare il debug di valori che non si aggiornavano ...
