### ISSUE TITLE
Problema layout XML

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#619]
Quando esporto un file XML relativo ad una fattura emessa, se ho righe descrittive con testo a capo, nella stringa del file XML invece di avere il testo a capo ho una "n"
OSM 2.4.9

![IMG](https://user-images.githubusercontent.com/40104356/60738194-c1943000-9f5d-11e9-96db-a8bcbe1100b9.png)

**Comment by Dasc3er** [comment]
@idraulicadueci Da ultima verifica, il problema dovrebbe essere risolto.
Non si trattava infatti di un bug del gestionale, ma semplicemente del foglio di stile utilizzato per mostrare le fatture.
