### ISSUE TITLE
beta 2.3 ddt acquisto non tiene i centesimi

### ISSUE THREAD

**Issue by robygladio** [devcode-it/openstamanager#62]
aggiungendo una spesa di imballo assurda inserita come articolo a zero poi valore immesso a mano non tiene i centesimi 1,25 + iva 22% lo porta a 1,20 così come imballo 12,53 lo porta a 12.50 

generando la fattura e correggendo a mano i prezzi (che visualizza cvorrettamente ma aprendo il dettaglio li cambia arrotondando il centesimo per difetto) il calcolo dell'iva risulta poi corretto. 

le cifre appaiono corrette ovunque anche nel ddt ma il calcolo iva perde 2 centesimi in questo caso..

**Comment by loviuz** [comment]
ho appena provato, ma non trovo questi errori. stai usando la release 2.3beta2 o gli ultimi commit della release?
