### ISSUE TITLE
problema in fase creazione fattura da ordine cliente

### ISSUE THREAD

**Issue by osm-gc** [devcode-it/openstamanager#620]
Con la versione 2.4.2 mi si è presentato un problema in fase di creazione fattura da ordine cliente modulo 'ordini cliente'. Una volta creata una fattura andando nell'ordine come documenti collegati ne porta 2 inserendoci anche una fattura di altro cliente diversa anche come registro vendite e senza ordine collegato.
Ho analizzato il problema più dettagliatamente e sembra nascere al momento della creazione della fattura in quando mette lo stesso riferimento 'idordine' nella tabella co_righe_documenti in entrambe le fatture in una correttamente nell'altra sbagliando.
Prima della creazione della fattura ho visto che nell'idordine della fattura non è presente giustamente alcun riferimento visto come ho detto non ha legame con ordine.
Non so se avete incontrato il problema in precedenza.
esempio allegato iddocumento 119 e 269 e idordine 76. Nel documento 119 viene assegnato erroneamente l'idordine 76 quando come detto in precedenza risulta a 0.
Mi è stato segnalato anche in precedenza ma ora l'ho analizzato

![image](https://user-images.githubusercontent.com/44160300/60755283-cd2f3780-9fed-11e9-9da3-fbe853d23dd6.png)

**Comment by Dasc3er** [comment]
Il problema si verso nella versione 2.4.9?

**Comment by osm-gc** [comment]
Con la 2.4.9 non ho verificato ma con la 2.4.2 attualmente utilizzata si presenta in modo saltuario

**Comment by osm-gc** [comment]
Ho approfondito e ho trovato il bug
Versione 2.4.2 - Modulo fatture  - File actions.php - Fattura_da_ordine

                    // Imposto la provenienza dell'ordine
                    $dbo->query('UPDATE co_righe_documenti SET idordine='.prepare($idordine).' WHERE id='.prepare($idriga));

Avviene in modo saltuario perché nel riprendere le righe dell'ordine da passare in fattura l'update ha la clausola 'where' solo su '$idriga '. A questo punto capita se l' $idriga è gia presente e uguale su or_righe_ordini e co_righe_documenti non è sufficiente la clausola e prende dei record diversi aggiornandone l' idordine.
Ciò però non avviene in fase di insert ma solo in update.

**Comment by Dasc3er** [comment]
@osm-gc La componente che hai indicato è stata aggiornata nelle versioni successive alla 2.4.2, quindi il bug non dovrebbe essere più presente.
