### ISSUE TITLE
Impossibile stampare lo scadenziario

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#622]
## Comportamento attuale

Impossibile stampare lo scadenziario. Il server restituisce un errore 500 e nei log non viene riportato niente. Ho già provato ad aumentare la variabile max_execution_time a 300 ma non ha funzionato.

## Passi per riprodurre il comportamento

1. Andare in Contabilità --> Scadenziario
2. Cliccare su stampa scadenziario

## Contesto

* Modulo: Scadenziario
* Versione del progetto: 2.4.9
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
@maicol07 Puoi provare ad accedere ai log di Apache?
`max_execution_time ` impostato a 300 permette solo 6 minuti di esecuzione, che sono abbastanza pochi se il problema è il carico della stampa.

**Comment by maicol07** [comment]
Purtroppo il mio hosting (Tophost) non fornisce l'accesso ai log di sistema.
Vengono mostrati circa 200 record

**Comment by Dasc3er** [comment]
Il commit 7eda6ad aggiorna la stampa Scadenzario a MPDF, e dovrebbe essere visibile un elevato miglioramento delle prestazioni grazie al flush diretto di ogni singola riga della tabella principale.
Nel caso si rilevassero problemi ulteriori, prova ad aumentare la memoria disponibile a PHP: https://mpdf.github.io/troubleshooting/memory-problems.html
