### ISSUE TITLE
Filtri su select specifiche

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#623]
Ciao,
vorrei impostare filtri personalizzati su uno specifico campo select. Ad esempio quando si aggiunge un intervento mostrare solo i clienti selezionati per uno specifico gruppo di utenti (per esempio gli amministratori possono selezionare tutti i clienti mentre i tecnici solo una parte specificati da un amministratore (oppure nel codice). Quale file devo modificare?
Grazie

**Comment by Dasc3er** [comment]
Ciao @maicol07,
per modificare gli elementi mostrati dai select devi modificare i file **ajax/select.php**.
Purtoppo non esiste un modo universale per spiegare il modo in cui devi fare nello specifico, quindi ti consiglio di controllare i contenuti dei vari select del gestionale.

**Comment by maicol07** [comment]
Nel file select non ho trovato la query di questa select:
`{[ "type": "select", "label": "<?php echo tr('Cliente'); ?>", "name": "idanagrafica", "required": 1, "value": "<?php echo $idanagrafica; ?>", "ajax-source": "clienti", "icon-after": "add|<?php echo Modules::get('Anagrafiche')['id']; ?>|tipoanagrafica=Cliente||<?php echo (empty($idanagrafica)) ? '' : 'disabled'; ?>", "data-heavy": 0 ]}`

**Comment by Dasc3er** [comment]
https://github.com/devcode-it/openstamanager/blob/4b2e00e4ffeefdced8b42d31c1054d6b183012a2/modules/anagrafiche/ajax/select.php#L6

**Comment by maicol07** [comment]
Ah ok, io guardavo nel file degli interventi :sweat_smile:
