### ISSUE TITLE
Riferimento amministrazione FE

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#624]
Ciao a tutti,
mi è stato dato questo codice:
Codice Identificativo Filiale: F000000097 (Tale valore dovrà essere da voi inserito nel campo 1.2.6 del XML  <RiferimentoAmministrazione>).
Come è possibile inserirlo in una anagrafica? È obbligatorio in una fattura elettronica?
Grazie

Link AE: https://www.agenziaentrate.gov.it/wps/content/Nsilib/Nsi/Schede/Comunicazioni/Fatturazione+elettronica+PA/Comunicazione+fornitori+AdE/?page=ivacomentipa

**Comment by Dasc3er** [comment]
Il campo non è obbligatorio, e per il momento non è supportato.

**Comment by Dasc3er** [comment]
@maicol07 Se sei interessato, controlla gli ultimi commit della versione 2.4.11 in sviluppo dove abbiamo inserito il supporto a nuovi nodi con inserimento manuale dei dati in fattura elettronica.
