### ISSUE TITLE
BUG: Stampa scadenzario

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#625]
Nella colonna "Documento" della stampata dello scadenzario, viene visualizzata soltanto la data del documento (fra l'altro in formato YYYY/MM/DD) mentre viene omesso il progressivo del documento.

OSM 2.4.9

**Comment by Dasc3er** [comment]
La stampa è stata aggiornata negli ultimi commit, e il problema è stato risolto nella versione 2.4.10.

**Comment by Dasc3er** [comment]
Mi è appena venuto in mente che se il numero progressivo del documento non viene riportato, la scadenza è del documento riportato più vicino in alto con progressivo Indicato.

**Comment by idraulicadueci** [comment]
@Dasc3er io continuo a non vedere  il numero documento nella tabella. Sotto la colonna documento non dovrebbe essere riportato "Fattura n. XXX del DD/MM/YYYY?

**Comment by idraulicadueci** [comment]
forse il problema è nel file pdfgen.scadenzario.php alla riga 72?

**Comment by idraulicadueci** [comment]
> 
> 
> Mi è appena venuto in mente che se il numero progressivo del documento non viene riportato, la scadenza è del documento riportato più vicino in alto con progressivo Indicato.

Però sarebbe corretto riportare sulla colonna "Documento" numero documento e data emissione (es. Fattura n. XXX del DD/MM/YYYY). Questo perché se mando un estratto conto a un cliente deve poter identificare con facilità il documento.
