### ISSUE TITLE
Errore Firma Attività

### ISSUE THREAD

**Issue by Technology-Solutions** [devcode-it/openstamanager#626]
## Comportamento richiesto

Firma dell'Attività da parte del cliente

## Comportamento attuale

Al momento del salvataggio della firma (clicco su Salva firma) viene restituito un errore Not Found 404, inoltre anche la preview in pdf non restituisce lo stesso errore

## Passi per riprodurre il comportamento

1.Dal menù attività clicco su "Anteprima e firma...": manca la preview pdf
![openSTAmanager01](https://user-images.githubusercontent.com/52965320/61300248-e8febe80-a7e1-11e9-95ff-719cd491b17d.png)

2.Clicco su "Firma", scrivo nome e cognome e appongo la firma
![openSTAmanager02](https://user-images.githubusercontent.com/52965320/61300406-30854a80-a7e2-11e9-8030-fdd0b629e0f6.png)

3.Clicco su "Salva firma" ed ottengo questo errore
![openSTAmanager03](https://user-images.githubusercontent.com/52965320/61300111-adfc8b00-a7e1-11e9-81df-eb4c5edde6d8.png)

## Contesto

* Modulo: Firma attività
* Versione del progetto: 2.4.9 (Rc029f947)
* Versione PHP: 7.2.17
* Tipo di server: apache su aruba

**Comment by maicol07** [comment]
@Technology-Solutions controlla che i file che indica l'errore siano effettivamente presenti sul server

**Comment by Technology-Solutions** [comment]
> 
> 
> @Technology-Solutions controlla che i file che indica l'errore siano effettivamente presenti sul server

Ma i files devo esserci ? Perche li ritrovo nella root principale e non nella directory indicata. Come se cercasse i file nella cartella e non nella root. 
Inoltre se sposto i file (dove li sta cercando, quindi in "interventi/modules/interventi") non carica il css e l'ingranaggio di loading va in loop

**Comment by maicol07** [comment]
@Technology-Solutions È possibile che ci sia qualche errore con le costanti **`BASEURL`**, **`ROOTDIR`**  e **`DOCROOT`** . Ti consiglio di verificare che siano corrette nel file **`config.php`**
Il loro significato è espresso qui: https://docs.openstamanager.com/docs/structure/stampe#struttura

**Comment by Technology-Solutions** [comment]
@maicol07 Scusami, ma dove trovo questo file **config.php** ? nella root principale ho solamente il config.inc.php con i parametri di connessione al MySQL e le varie impostazioni.

Ho dimenticato di dirti che l'installazione è stata effettuata su una sottodirectory, ovvero: **www.nomedominio.it/interventi**

**Comment by maicol07** [comment]
@Technology-Solutions sì scusa è config.inc.php. Comunque dovrebbero essere giusti dato che l'hai installato nella cartella interventi. A questo punto prova ad aggiornare all'ultima versione 2.4.10 così da reinserire tutti i file

**Comment by Technology-Solutions** [comment]
@maicol07 ok grazie per risposta. Ma non mi è chiaro come modificarle le voci, se si devono aggiungere.. In ogni caso, ho già provveduto ad aggiornare alla versione 2.4.10

**Comment by maicol07** [comment]
@Technology-Solutions le costanti dovrebbero essere a posto, se vuoi controllale comunque. È cambiato qualcosa dopo l'aggiornamento?

**Comment by Technology-Solutions** [comment]
@maicol07 Purtroppo no, stesso errore.
Se ci fai caso, nell'anteprima della firma cerca di caricare "/interventi/modules/**interventi**/assets/dist/pdfjs/web/viewer.html". 

Ma il file è presente in "/interventi/modules/assets/dist/pdfjs/web/viewer.html".
Non capisco perchè mi carica una directory "**interventi**" di mezzo. (come puoi vedere nell'immagine di apertura del post)

**Comment by Technology-Solutions** [comment]
> 
> 
> @Technology-Solutions È possibile che ci sia qualche errore con le costanti **`BASEURL`**, **`ROOTDIR`** e **`DOCROOT`** . Ti consiglio di verificare che siano corrette nel file **`config.php`**
> Il loro significato è espresso qui: https://docs.openstamanager.com/docs/structure/stampe#struttura

@maicol07  ho controllato meglio, nel file core.php in root ho trovato le voci
$docroot = DOCROOT;
$rootdir = ROOTDIR;
$baseurl = BASEURL;

devo cambiare qualcosa ?

**Comment by maicol07** [comment]
No, vanno bene... @Dasc3er che ne pensi?

**Comment by Dasc3er** [comment]
@Technology-Solutions Potresti provare a vedere i contenuti di queste variabili e postarli qui?

**Comment by Technology-Solutions** [comment]
Questi cono i contenuti delle variabili, stampati dal file core.php
docroot: /web/htdocs/www.nomedominio.it/home/interventi
rootdir: /interventi
baseurl: https://www.nomedominio.it/interventi

**Comment by Dasc3er** [comment]
Sembra quindi che venga inserito un modules/interventi in più rispetto al necessario...

**Comment by Technology-Solutions** [comment]
Comunque questo è il contenuto della cartella modules/interventi
![Cattura0](https://user-images.githubusercontent.com/52965320/61877031-7e8b0400-aeee-11e9-9673-3d1652c6bb9d.PNG)

**Comment by Dasc3er** [comment]
Allora, il link generato per la stampa viene gestito nella seguente riga:
https://github.com/devcode-it/openstamanager/blob/4d3ef8cc2748738981ff025e36fcb146ccfaced1/src/Prints.php#L245

Il valore della variabile globale ROOTDIR sembra essere corretto, poichè è `/interventi` deriva dal percorso di base del gestionale e suppongo tu acceda al gestionale con l'URL `<URL_sito>/interventi`.
Dunque la funzione dovrebbe restituire il link `interventi/assets/dist/pdfjs/...`.
Il problema sembra però verificarsi anche nel link per il salvataggio della firma, quindi sembra che il file **core.php** non sia richiamato correttamente...

**Comment by Dasc3er** [comment]
@loviuz @lucasalva87 Qualche idea?

**Comment by Technology-Solutions** [comment]
`suppongo tu acceda al gestionale con l'URL <URL_sito>/interventi`
@Dasc3er proprio così, è una sottocartella del dominio principale

**Comment by Technology-Solutions** [comment]
Ho notato che lo stesso problema di percorso avvine anche quando si accede agli interventi direttamente dalla dashboard: infatti nel link in fondo a sinistra si vede che c'è  un "modules/interventi" in più
![61300248-e8febe80-a7e1-11e9-95ff-719cd491b17d](https://user-images.githubusercontent.com/52965320/62376015-f802a200-b53f-11e9-94c6-c0d0d7980af4.png)

**Comment by Dasc3er** [comment]
Ok, quindi il problema sembra più generico...
Purtroppo davvero senza poterlo replicare internamente da parte nostra non possiamo darti molti suggerimenti su come risolvere.

Mi verrebbe in mente di controllare che il problema potrebbe essere causato dal doppio interventi nell'URL: potresti provare a rinominare in altro modo la cartella principale del gestionale? 
Non ci dovrebbero essere effetti collaterali oltre alla modifica dell?URL per l'accesso.

**Comment by Technology-Solutions** [comment]
> Mi verrebbe in mente di controllare che il problema potrebbe essere causato dal doppio interventi nell'URL: **potresti provare a rinominare in altro modo la cartella principale del gestionale?**
> Non ci dovrebbero essere effetti collaterali oltre alla modifica dell?URL per l'accesso.

Incredibilmente cambiamo nome alla cartella principale il problema si è risolto.
Stranamente però avevamo già provato a farlo prima di aprire il thread qui e non risolse il problema
Mah...

Comunque problema risolto, grazie per il supporto

**Comment by Dasc3er** [comment]
In teoria il problema dovrebbe essere definitivamente risolto con la futura versione 2.5, che prevede una considerevole riscrittura del codice di base del gestionale per aggiornare la struttura.
