### ISSUE TITLE
MIGLIORIA: Aggiunta variabile "Tipo documento" a template email

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#627]
## Comportamento richiesto

Avere a disposizione la variabile {tipo_documento} nel template e-mail

## Comportamento attuale

Allo stato attuale se invio una nota di credito o una fattura, nel template non ho la possibilità di distinguere la tipologia di documento (per es. Spett.le cliente, si invia in allegato {tipo_documento}..."

OSM 2.4.9

**Comment by Dasc3er** [comment]
La variabile è stata aggiunta nella versione 2.4.11, attualmente in sviluppo in attesa del rilascio ufficiale della 2.4.10.
