### ISSUE TITLE
tabelle non previste dopo aggiornamento 2.4.10

### ISSUE THREAD

**Issue by ale82x** [devcode-it/openstamanager#629]
## Comportamento richiesto

nessun alert

## Comportamento attuale

dopo aver fatto l'aggiornamento 2.4.10 ma un alert
 Attenzione! Ci sono delle tabelle non previste nella versione standard del gestionale: co_tipi_scadenze, zz_user_sedi. 

## Possibile soluzione
è un alert che posso ignorare o conviene fare qualcosa prima che blocchi gli aggiornamenti futuri?
grazie

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. log in openstamanager
2. strumenti -> aggiornamenti
3.

Eventuale codice rilevante:

Eventuali log relativi (cartella **logs/**):

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: aggiornamenti
* Versione del progetto: 2.4.10
* Versione PHP: 7.1
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Ciao @ale82x ,
ci siamo accorti che non abbiamo incluso le due nuove tabelle della versione nella lista del gestionale per indicare le tabelle interne.
Il gestionale non dovrebbe presentare nessun problema, e puoi ignorare il messaggio. In alternativa è sufficiente aggioranre il file **update/tables.php**: https://github.com/devcode-it/openstamanager/blob/master/update/tables.php

**Comment by ale82x** [comment]
perfetto, fatto e adesso non da più nessun alert.

grazie mille
