### ISSUE TITLE
myimpianti -> impianto scelto -> interventi svolti viene passato id sbagliato al link

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#63]
In modules/interventi/plugins/my_impianti.interventi.php c'é il riferimento sbagliato per il link generato per arrivare al intervento collegato all'impianto scelto.

[my_impianti.interventi.php.patch.zip](https://github.com/devcode-it/openstamanager/files/1517803/my_impianti.interventi.php.patch.zip)

**Comment by Dasc3er** [comment]
Ciao @lepool,
per future proposte di fix saresti disponibile a utilizzare le Pull Request appositamente messe a disposizione da Github?
In questo modo renderesti più semplice individuare le modifiche effettuate per risolvere il problema e al tempo stesso sarebbe molto più rapida l'integrazione dei tuoi fix.

**Comment by lepool** [comment]
Certamente. Il mio problema è che sto cercando di capire i comandi git. Non appena ci riesco effettuero richieste pull.
👍
