### ISSUE TITLE
Invio email - Email cliente non presa in automatico

### ISSUE THREAD

**Issue by ale82x** [devcode-it/openstamanager#630]
## Comportamento richiesto

una volta creata la fattura, cliccando sul bottone "invia fattura" compila in automatico la mail da inviare, fino alla versione precedente compilava in automatico il campo A per il destinatario della fattura prendendolo dalla scheda cliente

## Comportamento attuale

cliccando sul bottone "invia fattura" compila in automatico la mail ma non inserisce la mail del cliente. non è un problema, apro la scheda cliente e faccio copia incolla... però prima lo faceva in automatico.

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

creare una fattura e provare a fare invia.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Fatture di vendita
* Versione del progetto: 2.4.10
* Versione PHP: 7.1
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Grazie per la segnalazione @ale82x !
Puoi trovare la soluzione alla seguente riga di codice:
https://github.com/devcode-it/openstamanager/blob/4d3ef8cc2748738981ff025e36fcb146ccfaced1/mail.php#L15

**Comment by ale82x** [comment]
ottimo, aggiunta la riga 15 e adesso funziona tutto ok.

posso approfittare per fare 2 domande stupide?
- se volessi inviare la fattura a 2 indirizzi email, posso aggiungere i 2 indirizzi nella scheda cliente separati dalal virgola? o punto e virgola? o non è possibile farlo?
- nella lista delle fatture vedo nella colonna FE "generata" ma nella colonna Inviata non c'è nulla, ma ricordo che qualche mese le vedevo se erano inviate ma non mi ricordo se è stato un aggiornamento a farle sparire... è possibile farle tornare?

grazie mille ancora

**Comment by Dasc3er** [comment]
1. Per inserire in automatico 2 indirizzi email puoi separarli con un punto e virgola
2. Stai utilizzando il servizio di invio automatico gestito internamente da OpenSTAManager?

**Comment by ale82x** [comment]
ok grazie 
1 ok grazie
2 si certamente ho configurato l'smtp e mi da correttamente il messaggio inviato correttamente

grazie

**Comment by Dasc3er** [comment]
@ale82x L'invio automatico della fattura elettronica gestito internamente da OpenSTAManager è fattibile con il pulsante **Invia** dello stesso plugin _Fatturazione Elettronica_ in cui generi la fattura elettronica.
L'invio della fattura tramite semplice email (con account SMTP collegato) non è valido a fini fiscali, e il gestionale non gestisce la cronologia email. Per maggiori informazioni sull'invio delle fatture elettroniche ti consiglio di consultare un commercialista o la documentazione online.

**Comment by ale82x** [comment]
ah perdonami.
pensavo che la colonna inviata stava per l'invio della "copia di cortesia" in pdf...
nulla non è un problema magari ricordavo male io che prima le vedevo... 

grazie mille per il suggerimento del punto e virgola :)

**Comment by ale82x** [comment]
scusami stavo provando ad inserire 2 mail ma digitando il punto e virgola non lo prende... nemmeno la virgola... praticamente è come se non scrive quei caratteri...

grazie

**Comment by Dasc3er** [comment]
In questo caso potrebbe essere stato rimosso il supporto a più indirizzi email...
Potresti provare ad inserire dei referenti, in modo tale da avere gli indirizzi suggeriti quando ne aggiungi manualmente all'email.

**Comment by netcall** [comment]
> Grazie per la segnalazione @ale82x !
> Puoi trovare la soluzione alla seguente riga di codice:
> https://github.com/devcode-it/openstamanager/blob/4d3ef8cc2748738981ff025e36fcb146ccfaced1/mail.php#L15

volevo segnalare che si risolve che ora mostra la email registrata su anagrafiche , ma non mostra le email dei referenti.
