### ISSUE TITLE
MIGLIORIA Filtro Scadenzario

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#631]
## Comportamento richiesto
Avere la possibilità di filtrare le scadenze entro due date
## Comportamento attuale
Attualmente si può filtrare una data di scadenza, quindi non è possibile, per esempio, sapere a quanto ammontano i pagamenti per il mese di luglio
## Possibile soluzione
Inserire un campo filtro da data XX/XX/XXXX a data YY/YY/YYYY

**Comment by Dasc3er** [comment]
Il filtro può essere effettuato con la selezione temporale generale del gestione.

**Comment by idraulicadueci** [comment]
Con il filtro generale a me non funziona

**Comment by Dasc3er** [comment]
Corretto con il commit a100cb33fa6493ca35fc19ec73cfdc4470ed73ba

**Comment by idraulicadueci** [comment]
@Dasc3er ho installato le modifiche, però non funziona.

**Comment by Dasc3er** [comment]
Hai eseguito anche le query relative?
Non devi utilizzare una versione mista del gestionale, altrimenti diventerà sempre più difficile aggiornare il tutto.
Ti consiglio quindi di ripristinare la versione originale e attender.
