### ISSUE TITLE
Problema con il Piano dei Conti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#632]
Ho notato di avere una serie di piani dei conti cliente senza il nominativo a fianco.

![immagine](https://user-images.githubusercontent.com/40104356/62296071-ae965200-b46e-11e9-83dd-965c58f29ac1.png)

Ho provato quindi a cancellare uno dei piano dei conti senza nominativo e l'anagrafica relativa presenta il campo "Piano dei conti cliente" vuoto, ma senza la possibilità di ricollegarlo a un nuovo piano dei conti.

![immagine](https://user-images.githubusercontent.com/40104356/62296265-05039080-b46f-11e9-87cd-5d31eb4b41fe.png)

Esiste un procedura per ricreare il piano dei conti senza ricreare l'anagrafica?

**Comment by Dasc3er** [comment]
Credo il problema del piano dei conti sia causato dall'eliminazione di alcune anagrafiche nelle versioni più vecchie del gestionale...

Per rigenerare il piano dei conti per il singolo cliente devi semplicemente rimuovere la tipologia Cliente, salvare e aggiungerla di nuovo. Per il momento non esiste altro modo.

**Comment by idraulicadueci** [comment]
non viene ripristinato nemmeno così, cioè viene assegnato il numero del piano dei conti, ma senza il nominativo accanto.

**Comment by Dasc3er** [comment]
Quale versione stai utilizzando?

**Comment by idraulicadueci** [comment]
2.4.10

**Comment by loviuz** [comment]
@idraulicadueci hai modo di provare con la versione in sviluppo? Mi risulta che funzioni...

**Comment by idraulicadueci** [comment]
> 
> 
> @idraulicadueci hai modo di provare con la versione in sviluppo? Mi risulta che funzioni...

ancora no. Appena posso faccio la prova in locale. Grazie.

**Comment by idraulicadueci** [comment]
@Dasc3er @loviuz ho provato con la versione 2.4.12, ma in anagrafica continua a darmi la casella vuota e disattivata. Nella creazione di una nuova anagrafica, invece va tutto bene.

**Comment by loviuz** [comment]
L'anagrafica ha il campo "Denominazione" o "Nome" e "Cognome"?

**Comment by idraulicadueci** [comment]
> 
> 
> L'anagrafica ha il campo "Denominazione" o "Nome" e "Cognome"? Inoltre, la casella rimane vuota e disattivata solo per le anagrafiche aventi già il problema?

Ho provato ad eliminare i valori contentui nei campi "nome", "Cognome" e "Denominazione". Ho reinserito i valori nei campi "nome" e "Cognome" e poi ho eliminato la tipologia di anagrafica, salvato e indicato nuovamente la tipologia come "cliente". Il problema persiste.

Il problema esiste solo per le anagrafiche aventi in origine il problema.
Come già descritto, sulle nuove anagrafiche il problema non c'è, anche eliminando la tipologia anagrafica e reinserendola.

**Comment by idraulicadueci** [comment]
Da quello che ho capito, smanettando nel database, è che OSM trova il campo idconto_cliente <> 0 (o idconto_fornitore se è FORNITORE). Quindi ho inserito manualmente nel campo il valore 0. Poi dal modulo anagrafica ho eliminato la tipologia cliente e salvato, poi reinserito nuovamente la tipologia e salvato. A questo punto il piano dei conti si è messo a posto.
Da completo ignorante, credo che si dovrebbe fare in modo che quando si elimina la tipologia cliente, il valore idconto_cliente - idconto_fornitore deve essere impostato a 0, perché non si verifichi il problema.
