### ISSUE TITLE
DOMANDA: Movimentazione degli articoli tra le sedi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#634]
Nel modulo giacenze all'interno di un articolo posso vedere l'elenco delle sedi con le relative giacenze, ma non trovo il modo di spostare una certa quantità di pezzi dal magazzino A al magazzino B.

**Comment by loviuz** [comment]
Effettivamente può essere molto utile ora che gestiamo le sedi multiple nel magazzino. Potrebbe essere inserita la possibilità di fare movimenti fra 2 sedi dell'anagrafica azienda, magari dal plugin "Movimenti" dell'articolo, così c'è già anche la funzione di eliminazione movimento manuale. @Dasc3er @lucasalva87 che ve ne pare?

**Comment by Dasc3er** [comment]
Chiusura per risposta completa, la funzionalità indicata è discussa in #784.
