### ISSUE TITLE
nuovo controllo ADE FE

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#635]
nuovo controllo ADE che scarta le FE:
Nell'anagrafica per le società si inserisce piva e c.f. uguali, per esempio IT00000000000.
Quando viene generata la FE il C.F. mantiene IT, mentre il tag <IdCodice> contenente
la piva, IT viene non è presente (probabilmente viene filtrato da sw solo numeri).
IT sarebbe da indicare in quanto le piva straniere possono iniziare con GB, DE etc.

**Comment by lucasalva87** [comment]
Grazie per la segnalazione. Il problema è stato già risolto nella 2.4.11 in sviluppo
