### ISSUE TITLE
Salvataggio parziale delle modifiche contratto

### ISSUE THREAD

**Issue by microcluster** [devcode-it/openstamanager#636]
## Comportamento richiesto

Dopo aver aggiunto nuovi dati nel contratto alla voce "Righe" premendo il tasto modifica dovrebbe salvare

## Comportamento attuale

Dopo aver premuto il tasto modifica vengono salvate le informazioni, ma compare un messaggio errato nel popup come in foto.

![Screenshot_20190807_172134](https://user-images.githubusercontent.com/31942122/62638114-0d5f3e00-b93d-11e9-878e-537d31ffc92f.png)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.Compilare un contratto
2.Aggiungere delle righe
3.Salvare
4.Modificare la riga esistente
5.Cliccare modifica

## Contesto

* Modulo: Contratti
* Versione del progetto: 2.4.10
* Versione PHP: 7.1.10
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Per il momento l'unico modulo a effettuare il salvataggio del record prima di inserire una riga è Fatture. Per gli altri moduli devi fare le modifiche, salvare e poi aggiungere una nuova riga.

Funzionalità effettivamente da implementare nelle prossime versioni a livello generale.

**Comment by Dasc3er** [comment]
Modifica non completata.

**Comment by Dasc3er** [comment]
La modifica è stata completata. Al momento, il click sui pulsanti per l'aggiunta di righe sui documenti provoca il salvataggio delle modifiche e successivamente l'apertura del modal.
