### ISSUE TITLE
SITO: link non valido

### ISSUE THREAD

**Issue by clabnet** [devcode-it/openstamanager#638]
Nel sito https://www.openstamanager.com/community/ 
in questo paragrafo il link al forum non è più valido :

Assistenza ad altri utenti:	
sei già esperto nell’installazione o sai risolvere alcuni problemi comuni? _**Iscriviti e segui il nostro forum**_ e aiuta altri utenti a farlo funzionare se hanno riscontrato ad esempio problemi già noti che anche tu sai risolvere!

**Comment by Dasc3er** [comment]
Il link prevede un reindirizzamento automatico a https://forum.openstamanager.com/
