### ISSUE TITLE
Supporto all'esecuzione di statement SQL multipli (query modulo Viste)

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#639]
Aggiungere il supporto a più query dal modulo viste.
Ad esempio se nel modulo viste si digita:
```
query1;
query2;
```

E la si esegue nel modulo relativo, datatables da errore.
Ho provato nel modulo Fatture di vendita impostando come prima query 
```
SET MAX_EXECUTION_TIME=1000
```
 mentre come seconda tutto il select generato dal modulo Viste

**Comment by Dasc3er** [comment]
Per cosa sarebbe utile supportare più query per modulo?

**Comment by maicol07** [comment]
@Dasc3er Per eseguire operazioni preliminari tramite SQL prima di visualizzare i dati. Ad esempio, il mio hosting ha il parametro MAX_EXECUTION_TIME di MySql ad un valore basso e non posso modificarlo, se non ad ogni query tramite il comando del messaggio precedente. Supportando query multiple si risolve anche il problema delle fatture scomparse (eseguendo il comando sopra)

**Comment by Dasc3er** [comment]
Ti consiglio di modificare la classe Database per gestire la query in questione.
L'utilità indicata non è rilevante per i moduli di per sè.
