### ISSUE TITLE
Info: ma il client email?

### ISSUE THREAD

**Issue by centoasa** [devcode-it/openstamanager#64]
Ma non c'è/non è previsto il client email, dove ricevere email e collegarle a contatti/aziende etc....?

**Comment by Dasc3er** [comment]
Ciao @centoasa,
per client email intenderesti forse la possibilità di collegare OpenSTAManager a un account email per leggere (e solo leggere?) la posta elettronica direttamente dal gestionale?

**Comment by centoasa** [comment]
Hai risposto esaustivamente alla mia domanda. Grazie

**Comment by Dasc3er** [comment]
@centoasa, il progetto è effettivamente dedicato alla gestione dell'assistenza tecnica e della relativa fatturazione; sono state sviluppate alcune personalizzazioni che permettono una maggiore integrazione con le email (ad esempio per inviare documenti, come indicato sopra), ma di propria natura il software non presenta queste caratteristiche e soprattutto non è rivolto alla completa sostituzione dei client email personali/aziendali.

Per maggiori informazioni sulle possibilità di adeguamento e personalizzazione del progetto potresti contattarci via email, esponendo in maggior dettaglio le tue richieste.

@fpsoftware

**Comment by fpsoftware** [comment]
Ciao @centoasa 
nel progetto base la nostra intenzione è di aggiungere solo il semplice invio di documenti tramite mail.
Per alcuni clienti abbiamo già sviluppato un sistema per l'apertura di ticket tramite l'invio di email, se ti interessa sono moduli extra al progetto.
Grazie per l'interesse.
