### ISSUE TITLE
invio sollecito con allegato fattura in pdf

### ISSUE THREAD

**Issue by ale82x** [devcode-it/openstamanager#640]
## Comportamento richiesto

inviare un sollecito di pagamento potendo allegare la fattura di vendita

## Comportamento attuale

invia il sollecito senza nessuna stampa allegata...

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Contabilità -> Scadenziario
* Versione del progetto: 2.4.10
* Versione PHP: 7.1
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Ciao @ale82x,
putroppo per ora questa funzione non è disponibile per l'organizzazione interna del gestionale: a una mail possono essere allegate solo le stampe collegate al modulo di origine dell'email. 
Questo ci impedisce di includere la stampa in questione poichè collegata al modulo **Fatture di vendita**, mentre il _Sollecito_ appartiene allo **Scadenzario**.

Se ciò si rivelasse necessario per te, puoi sempre duplicare il template del Sollecito all'interno del modulo **Fatture di vendita**, e procedere ad inviare l'email dal modulo Fatture di vendita invece che dallo **Scadenzario** aprendo il documento relativo con il link apposito _Apri documento_.

**Comment by ale82x** [comment]
Perfetto,
direi che la soluzione proposta è perfetta! :)
Ho già provato e va benissimo così.

Grazie mille ancora
