### ISSUE TITLE
Widget 'Attività in programmazione'

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#641]
Sarebbe utile poter visualizzare nell'elenco sia il cliente che la descrizione, come avviene per il Widget 'Promemoria attività da pianificare'

Attualmente il Widget visualizza il numero dell'intervento e la data della richiesta

* Modulo: Dashboard - Widget 'Attività in programmazione'
* Versione del progetto: 2.4.10
* Versione PHP: 7.1.28
* Tipo di server:

**Comment by Dasc3er** [comment]
Nel caso, da aggiungere anche al widget **Attività confermate**.

**Comment by Pek5892** [comment]
Introdotto nella release 2.4.28
