### ISSUE TITLE
DDT in uscita - Tipo di trasporto: Mittente - Campo 'Vettore' non necessario.

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#642]
Quando la spedizione è effettuata dal mittente, non è necessario specificare alcun vettore.

Attualmente il campo 'Vettore' è richiesto sia per la spedizione a cura del vettore che per quella a cura del mittente.

Per la spedizione a cura del mittente sarebbe opportuno disabilitare il campo 'Vettore', come avviene per il trasporto a cura del destinatario

* Modulo: DDT in uscita
* Versione del progetto: 2.4.10
* Versione PHP: 7.1.28
* Tipo di server:

**Comment by Dasc3er** [comment]
Potresti spiegare meglio la questione?

**Comment by peropepero** [comment]
Certo, ci provo...

La spedizione può essere effettuata dal mittente (cedente), dal destinatario (cessionario) oppure da un vettore (o più di uno...).
Nei primi due casi nel DDT è sufficiente indicare che il trasporto è a cura del mittente o del destinatario. Non è necessario aggiungere altri dati in quanto sono già presenti nel documento (cedente e cessionario).
Se ad effettuare il trasporto è un vettore, allora è necessario indicare i dati di quest'ultimo.

Ad oggi OSM obbliga a specificare il vettore anche nel caso in cui il trasporto è effettuato dal mittente.

![Esempio DDT](https://user-images.githubusercontent.com/35023949/63954265-1eeebe00-ca83-11e9-9735-da1524df4353.jpg)

**Comment by Dasc3er** [comment]
@peropepero La spedizione a mezzo mittente non è prevista da OpenSTAManager al momento, e per questo si verifica la questione.
Puoi sempre creare una nuova spedizione apposita dal modul **Tipi di spedizione** in **Strumenti** -> **Tabelle**.

**Comment by peropepero** [comment]
In effetti è quello che ho fatto qualche relase fa, ma qualsiasi **Tipo di spedizione** aggiunto, richiede comunque il vettore:

![Screenshot_2019-08-29 Ddt in uscita - OpenSTAManager](https://user-images.githubusercontent.com/35023949/63958018-d2f34780-ca89-11e9-95ed-e25086921ff2.png)

**Comment by lucasalva87** [comment]
Grazie per la segnalazione l'ultimo commit dovrebbe risolvere la problematica descritta.

**Comment by peropepero** [comment]
Ho provato ma non cambia molto. 

Potreste testare quanto segue, a me sembra funzionare. Non sono in grado di inserirlo su GitHub... allego due screenshot (i numeri delle righe non corrispondono, ho ancora il file ddt/edit.php originale della 2.4.10):

![Screenshot_2019-08-30 Hosting File Manager](https://user-images.githubusercontent.com/35023949/64039022-ec63c480-cb59-11e9-90b3-0b3aecb7a229.png)

![Screenshot_2019-08-30 Hosting File Manager(1)](https://user-images.githubusercontent.com/35023949/64039032-f1c10f00-cb59-11e9-940d-1d2848eec3b6.png)

**Comment by Dasc3er** [comment]
Il codice che devi modificare è 
`if ($(this).val() != 1 && $(this).val() != 2 ) {

**Comment by crisassistenza** [comment]
Ciao, riprendo questo piccolo bug per proporvi di aggiungere anche questo script:
`$(document).ready(function() {
                     //a parte Espressa o Vettore
                     if ($(this).val() != 1 && $(this).val() != 2 ) {
                         $("#idvettore").attr("required", false);
                         $("#idvettore").attr("disabled", true);
                         $("label[for=idvettore]").text("<?php echo tr('Vettore'); ?>");
                         $("#idvettore").selectReset("<?php echo tr("Seleziona un'opzione"); ?>");
                         $("#idvettore").next().next().find("button.bound:nth-child(1)").prop("disabled", true);
                     }else{
                         $("#idvettore").attr("required", true);
                         $("#idvettore").attr("disabled", false);
                         $("label[for=idvettore]").text("<?php echo tr('Vettore'); ?>*");
                         $("#idvettore").next().next().find("button.bound:nth-child(1)").prop("disabled", false);
                     }
                   })`

In caso contrario se riapro un DDT con spedizione "Mittente" lasciato in bozza per metterlo in stato "Evaso" crea dei problemi e non permette il salvataggio.

**Comment by Dasc3er** [comment]
@crisassistenza Potresti spiegare più nel dettaglio cosa proponi con questo codice?
Sarebbe ancora meglio se crei una nuova issue apposita, senza scrivere in issue chiuse ormai da un pezzo.

**Comment by crisassistenza** [comment]
> Sarebbe ancora meglio se crei una nuova issue apposita, senza scrivere in issue chiuse ormai da un pezzo

Sorry, sovrappensiero non ci ho pensato. 

> Potresti spiegare più nel dettaglio cosa proponi con questo codice?

Ci provo... Se creo un DDT in stato bozza selezionando come spedizione "Mittente" e lo salvo, quando poi vado a riaprire il DDT per metterlo in stato "Evaso" non me lo fa fare perché dice che il campo "Vettore" è obbligatorio.
Il codice che vi ho postato risolve proprio questo problema.
