### ISSUE TITLE
Lentezza inserimento interventi

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#644]
versione 2.4.9 in modulo interventi:

quando si aggiungono le ore di lavoro, dopo aver selezionato il tecnico, prima di vedere la riga ore aggiunta (e quindi compilarla), passa almeno un minuto con la rotella arancione che gira.
Succede anche con la cancellazione di una riga di ore inserita.

**Comment by Dasc3er** [comment]
@pubblisoft QUesto è probabilmente causato dalle mail automatiche ai tecnici interessati dall'intervento.
Nella 2.4.11 in sviluppo il problema non si dovrebbe verificare con l'aggiunta dell coda di invio.

**Comment by pubblisoft** [comment]
confermo che togliendo l'indirizzo mail dall'anagrafica tecnico, le operazioni funzionano in modo fluido, in virtù della riga "if (!empty($tecnico['email']))"   nel file action.php del modulo interventi.

grazie

**Comment by pubblisoft** [comment]
if (!empty($stato['notifica']) && !empty($stato['destinatari']) && $stato['idstatointervento'] != $record['idstatointervento']) {
            $n = new Notifications\EmailNotification();

**Comment by pubblisoft** [comment]
grazie

**Comment by Dasc3er** [comment]
> 
> 
> in teoria le notifiche mail dovrebbero essere attive solo se sono stati immessi i dati del mail server per spedire le mail.
> grazie

In effetti non esiste ancora questo controllo, poichè si suppone che per chiunque provi ad abilitare le notifiche dallo stato (non abilitate di default) si suppone abbia almento compilato l'account mail relativo.
