### ISSUE TITLE
scadenza di pagamento al mese successivo

### ISSUE THREAD

**Issue by pubblisoft** [devcode-it/openstamanager#645]
versione 2.4.9,

c'è un modo di far calcolare correttamente un pagamento riba 30gg d.f.f.m. +10gg,
ossia al giorno 10 del mese successivo?

grz

**Comment by lucasalva87** [comment]
Vado a memoria ma credo basti impostare nel pagamento che la data deve essere calcolata dalla data fatturazione. Poi si specificano 30 giorni distanza e si imposta 10 come giorno fisso

**Comment by pubblisoft** [comment]
grazie risolto,

imposto scadenza giorno fisso, metto 30 gg di distanza e 10 come giorno fisso, come indicato ed effettivamente le scadenze sono stampate al giorno 10 del mese successivo.
