### ISSUE TITLE
Contratti - Sede dell'impianto

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#646]
## Comportamento richiesto
Se creo un Contratto, aggiungo degli Impianti e poi creo il Promemoria la Sede dovrebbe essere  copiata da quella dell’Impianto o dal primo degli impianti se sono molti

## Comportamento attuale

Se creo un Contratto, aggiungo degli Impianti e poi creo il Promemoria la Sede viene copiata da quella del Contratto (non obbligatoria)

**Comment by Dasc3er** [comment]
@ivanopersico La sede dei documenti viene riportata tra documenti: gli impianti sono utilizzati per riferimento, e sarebbe sbagliato prendere la sede da essi.
