### ISSUE TITLE
Contratti - Promemoria vs interventi pianificati

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#647]
## Comportamento richiesto
Se creo un Contratto, aggiungo degli Impianti e poi creo il Promemoria la Data promemoria dovrebbe essere modificabile, inoltre il Promemoria quando creo gli interventi pianificati dovrebbe cancellarsi perchè ormai inutile

Descrivi il comportamento che ti aspetti dal progetto.

## Comportamento attuale

Se creo un Contratto, aggiungo degli Impianti e poi creo il Promemoria la Data promemoria è sempre oggi e non è modificabile, inoltre quando creo gli interventi (se non partono nella stessa data del promemoria) mi crea anche il promemoria inutilmente

**Comment by Dasc3er** [comment]
@ivanopersico 
Procedura di creazione con Impianto:
![immagine](https://user-images.githubusercontent.com/15911489/64515526-05543e80-d2ed-11e9-9a1c-13d9956aaa19.png)

Dopo la creazione dell'intervento, il promemoria non si cancella ma viene collegato: 
![immagine](https://user-images.githubusercontent.com/15911489/64515471-f077ab00-d2ec-11e9-84c1-dd423295c8db.png)

**Comment by ivanopersico** [comment]
Comportamento fino alla 2.4.9 - se creo un Contratto, aggiungo degli Impianti e poi creo il Promemoria la Data promemoria è sempre oggi e non è modificabile, inoltre quando creo gli Interventi se NON iniziano con la stessa data del Promemoria mi crea anche il Promemoria inutilmente
![1](https://user-images.githubusercontent.com/50906939/64533837-9c80bc80-d314-11e9-99c3-f36ff2db053d.jpg)

**Comment by Dasc3er** [comment]
Il problema dovrebbe essere risolto nelle ultime versioni, e ancora di più nella versione in sviluppo (2.4.14) poichè il sistema dei promemoria è stato leggermente rivisto.
