### ISSUE TITLE
Contratti - Duplicazione

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#648]
## Comportamento richiesto
Se duplico un Contratto il contratto nuovo dovrebbe essere uguale al contratto vecchio e mi dovrebbe dare la possibilità di pianificare gli stessi interventi previsti nel nuovo intervallo di tempo futuro

## Comportamento attuale

Se duplico un contratto ottengo sempre un errore bloccante
Si è verificato un'errore [uid: 712cda8]. Se il problema persiste siete pregati di chiedere assistenza tramite la sezione Bug. 
Call to a member function getRighe() on null

**Comment by Dasc3er** [comment]
@ivanopersico Che versione stai utilizzando?
Il problema non mi si verifica.

Inoltre, sei pregato di rimuovere dalla issue le sezioni che non utilizzi.

**Comment by ivanopersico** [comment]
Uso la versione 2.4.9, è possibile che il modulo Contratti per qualche motivo non si sia aggiornato?
Già con Fabio avevamo verificato che malgrado il corretto aggiornamento alla Versione 2.4.9 il modulo Attività non si era aggiornato all'ultimo livello pubblicato.
Va bene, sono i primi post che inserisco

**Comment by Dasc3er** [comment]
In questo caso, potrebbe essere che il problema sia stato risolto con la versione 2.4.10.
Trovi qui la possibile soluzione:

https://github.com/devcode-it/openstamanager/commit/ca9a480f92ba92821ea5c2ea39081be5037f7d98

**Comment by ivanopersico** [comment]
Grazie, effettivamente è stato risolto dalla 2.4.10, ho però visto che la duplicazione duplica il contratto e non duplica gli interventi previsti dal contratto che quindi sono da reinserire completamente, è corretto?
Grazie

**Comment by Dasc3er** [comment]
Per mia conoscenza è corretto, poiché i promemoria sono relativi ad alcuni specifiche date che devono essere impostate manualmente.
Era stato discusso in passato di duplicarli traslando le date secondo i nuovi periodi di accettazione e conclusione del contratto duplicato, ma poiché ci sono troppe varianti per l'utilizzo generale era stato scelto di lasciare libertà all'utente nella creazione da zero di tutti i promemoria.

Per esempio, alcune varianti possono essere:
- duplicare i promemoria tramite le distanze in giorni
- duplicare i promemoria con lo stesso giorno originale e traslati tra i mesi
- duplicarli con un ritardo, nelle due varianti di cui sopra
- gestire l'eventuale periodo di attivazione del contratto con lunghezza diversa rispetto l'originale
E così via: diventerebbe piuttosto complesso a livello di codice e manutenibilitá, almeno senza aver definito un solo sistema valido sempre per il nostro gestionale.
