### ISSUE TITLE
Componenti Impianti - Difficile consultazione e proposta DB Impianti

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#649]
## Comportamento richiesto
Se creo dei Componenti degli Impianti non ho nessuna lista per controllare il contenuto dei campi inseriti e se li esporto ottengo un file testo inutilizzabile
Sarebbe molto utile poter indicare negli Impianti un legame Padre-Figlio (distinta base di Impianto) in mod da limitare l'uso dei Componentidi Impianto a casi specifici

## Comportamento attuale
Se creo dei componenti degli Impianti il contenuto dei campi che ho inserito posso vederlo solo consultando singolarmente il componente dell'impianto limitando tantissimo questa funzionalità.
Una distinta base di Impianto non è disponibile

**Comment by Dasc3er** [comment]
Potresti chiarire meglio l'utilità e l'utilizzo pratico di questa funzione?
Se si tratta semplicemente di elencare dentro **Gestione componenti** l'elenco delle istanze dei componenti collegati ai vari impianti, ciò è certamente possibile, ma non mi sembra che tu stia richiedendo questo...

**Comment by ivanopersico** [comment]
Sono due necessità diverse:
1 - Avere la possibilità di vedere elencato il contenuto dei campi del Componente creato collegato ai vari Impianti, la funzionalità Componente è interessante perchè molto flessibile ma il contenuto inserito è difficilmente consultabile in modalità lista o tabella
2 - Per impianti complessi invece di gestire Componenti di Impianto penso sarebbe più utile collegare gli impianti con un legame Padre-Figlio im modo da creare tutte le parti dell'impianto come Impianti separati e vederli riassunti in una Distinta base di Impianto

**Comment by loviuz** [comment]
Questa diventerebbe a tutti gli effetti una distinta base, che è un po' più complessa rispetto ad una gestione dei componenti così com'è impostata ora. A tal riguardo, stiamo lavorando ad un modulo aggiuntivo che gestisce in modo più completo la distinta base.
