### ISSUE TITLE
Focus errato in modulo attività quando ho aggiunto un cliente dal modulo attività

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#65]
Mi spiego un po meglio:

- Creo attività nuova 
- effettuo una prova di scroll con il mouse, esito positivo
- aggiungo cliente nuovo e confermo
- riprovo scroll con il mouse, esito negativo dato che il lo scroll viene effettuato sulla maschera principale

Se provi nella console javascript "document.activeElement" prima e dopo aver aggiunto il cliente nuovo

il focus rimane su "btn bound"

**Comment by Dasc3er** [comment]
@lepool Per "aggiungo cliente nuovo e confermo" intendi forse l'aggiunta di una sessione di lavoro di un tecnico?

**Comment by lepool** [comment]
@Dasc3er , no come admin.
1. nel modulo attività attraverso il button aggiungi intervento
2. il cliente non esiste , perciò nel form creazione attività attraverso il button aggiungi cliente
3. se annullo chiudendo la finestra oppure premendo aggiungi mi chiude il form e non riesco piu a fare lo scroll nel form nuova attività.

![aggiungi_attivita](https://user-images.githubusercontent.com/32035706/33728715-9634ae14-db7b-11e7-9e3c-0f43b2751474.png)
![aggiunta_cliente_da_form_nuova_attivita](https://user-images.githubusercontent.com/32035706/33728718-984ce5ea-db7b-11e7-86c4-d7d947617ec6.png)
![form_cliente_nuovo](https://user-images.githubusercontent.com/32035706/33728737-a42b32ea-db7b-11e7-9f34-279950d27807.png)

**Comment by Dasc3er** [comment]
@lepool Grazie mille per aver specificato!
