### ISSUE TITLE
Materiali - Unità di misura

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#650]
## Comportamento richiesto
Se creo un Materiale senza Unità di misura dovrebbe essere impossibile salvarlo (campo obbligatorio)  in modo da evitare Movimenti a magazzino senza Unità di misura

## Comportamento attuale
Se creo un Materiale senza Unità di misura posso fare dei movimenti a magazzino senza ottenere nessun messaggio di blocco o avvertimento

**Comment by Dasc3er** [comment]
@ivanopersico Ciò non è possibile per garantire il supporto ai servizi, che non hanno in realtà quantità e unità di misura.

@loviuz Si potrebbe variare in modo dinamico l'obbligatorietà dei campi **Unità di misura** e **Questo articolo è un servizio**, se ha senso come richiesta.

**Comment by ivanopersico** [comment]
A mio parere avrebbe molto senso la richiesta, permettere movimenti di magazzino senza unità di misura è un grave errore gestionale che ne giustifica la miglioria
Buon lavoro
Ivano

**Comment by Dasc3er** [comment]
@ivanopersico Se il problema sono i movimenti, il problema non sussiste.
Poichè per ora non vengono supportate le conversioni tra unità di misura degli arrticoli, in automatico tutti i movimenti assumono l'unità dell'articolo anche a seguito di eventuali modifiche della stessa.

Esempio senza unità:
![immagine](https://user-images.githubusercontent.com/15911489/64515891-bce95080-d2ed-11e9-8b3f-31861bd4f057.png)
![immagine](https://user-images.githubusercontent.com/15911489/64515905-c2469b00-d2ed-11e9-9913-319ce8a73fe7.png)

Dopo la modifica dell'unità:
![immagine](https://user-images.githubusercontent.com/15911489/64515940-d5596b00-d2ed-11e9-8adb-7d8cb71b770b.png)
![immagine](https://user-images.githubusercontent.com/15911489/64515953-dbe7e280-d2ed-11e9-89a0-3e6adfdd2df9.png)

**Comment by loviuz** [comment]
Non andrei ad aggiungere questo vincolo dell'unità di misura, anche perché suppongo che un articolo abbia una unica unità di misura che non cambia nel tempo, per cui se si deve stampare un inventario o simili, se non è presente l'unità di misura, basta aggiungerla e rigenerare la stampa.
