### ISSUE TITLE
Materiale - Duplicazione con quantità a magazzino

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#651]
## Comportamento richiesto
Se Duplico un Materiale la Qtà a magazzino del materiale Origine non dovrebbe essere riportata sul Materiale Destinazione

## Comportamento attuale
Se duplico un Materiale Origine con quantità a magazzino >0 viene duplicata anche la quantità nel Materiale Destinazione e se si prova manualmente a resettare la Quantità a 0 si creano degli errori nei movimenti del Materiale di Origine

**Comment by Dasc3er** [comment]
Il problema è stato risolto da diverse versioni.

**Comment by ivanopersico** [comment]
Mi scuso per la duplicazione del post, non mi ero accorto che era stato chiuso.
Ho installato la versione 2.4.10 ed il comportamento errato è ancora presente:
1 - Duplico un materiale con 4 pz a magazzino (esempio UK30151)
![immagine](https://user-images.githubusercontent.com/50906939/64264552-c6f80180-cf31-11e9-9c67-a5ec9d360792.png)
2 - Creo il materiale duplicato (esempio UK30151COPIA )e azzero manualmente l'esistenza errata di 4 pz che mi viene proposta
![immagine](https://user-images.githubusercontent.com/50906939/64264745-163e3200-cf32-11e9-99cc-089425ae0ef1.png)
![immagine](https://user-images.githubusercontent.com/50906939/64264812-340b9700-cf32-11e9-8365-769adad43c07.png)
3 - Come risultato trovo dei movimenti totalmente sbagliati: 
-4 pz per UK30151COPIA
+4 pz che avevano caricato a magazzino il materiale origine UK30151 ora sono diventati il materiale destinazione UK30151COPIA
![immagine](https://user-images.githubusercontent.com/50906939/64265163-b98f4700-cf32-11e9-8622-09c660e95016.png)
Grazie

**Comment by Dasc3er** [comment]
@ivanopersico Putroppo devo dirti che il comportamento era corretto e l'articolo viene quindi duplicato con quantità 0.
Il problema è che dopo la duplicazione non veniva caricato il nuovo articolo, ma quello originale!
