### ISSUE TITLE
Filtri - Errore di pulizia dei vecchi filtri impostati nelle liste

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#652]
## Comportamento richiesto
Se imposto un Filtro in qualsiasi Lista quando rientro nello stesso modulo vorrei che il Filtro impostato in precedenza venga eliminato o almeno mostrato come impostato (colore arancio)

## Comportamento attuale
Spesso dopo aver impostato un Filtro in una Lista, rientrando nella stessa Lista trovo i contenuti filtrati ed il Filtro è nascosto (nessun colore arancione), l'unico modo per eliminare il Filtro è di cancellare manualmente il campo filtrato in precedenza

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Versione del progetto: 2.4.9

**Comment by Dasc3er** [comment]
Il problema non si verifica.
