### ISSUE TITLE
Materiale - Duplicazione con quantità a magazzino >0

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#653]
## Comportamento richiesto
Se Duplico un Materiale la Qtà a magazzino del materiale Origine non dovrebbe essere riportata sul Materiale Destinazione

## Comportamento attuale
Se duplico un Materiale Origine con quantità a magazzino >0 viene duplicata anche la quantità nel Materiale Destinazione e se si prova manualmente a resettare la Quantità a 0 si creano degli errori nei movimenti del Materiale di Origine

* Modulo: Materiali
* Versione del progetto: 2.4.9
* Versione PHP:
* Tipo di server:

**Comment by Dasc3er** [comment]
@ivanopersico #651
Sei pregato di non creare nuove issue uguali ad altre già chiuse.
