### ISSUE TITLE
Liste nei moduli - Filtri fantasma

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#654]
## Comportamento richiesto
Se imposto un Filtro in una Lista quando rientro nello stesso modulo vorrei che il Filtro impostato in precedenza venga eliminato o almeno mostrato come impostato (colore arancio)

## Comportamento attuale
Spesso dopo aver impostato un Filtro in una Lista, rientrando nella stessa Lista trovo i contenuti filtrati ed il Filtro è nascosto (nessun colore arancione), l'unico modo per eliminare il Filtro è di cancellare manualmente il campo filtrato in precedenza

* Modulo: Tutti (testate Liste di Materiali e di MyImpianti)
* Versione del progetto: 2.4.9
* Versione PHP:
* Tipo di server:

**Comment by Dasc3er** [comment]
@ivanopersico #652
Sei pregato di non creare nuove issue uguali ad altre chiuse.
