### ISSUE TITLE
Modifica Attività - Campo Impianti mancante

### ISSUE THREAD

**Issue by ivanopersico** [devcode-it/openstamanager#655]
## Comportamento atteso
Dopo aver Creato un'Attività ed averla collegata ad uno o più Impianti mi aspetto che in fase di Modifica dell'Attività il campo Impianti sia presente e sia possibile manutenerlo

## Comportamento attuale
Dopo aver Creato un'Attività ed averla collegata ad uno o più Impianti in fase di Modifica dell'Attività il campo Impianti non è presente e quindi nemmeno manutenibile

* Modulo: Attività
* Versione del progetto: 2.4.9
* Versione PHP:
* Tipo di server:

**Comment by Dasc3er** [comment]
Credo a partire dalla versione 2.3 è possibile utilizzare il plugin **Impianti** proprio per queste necessità:
![immagine](https://user-images.githubusercontent.com/15911489/64516055-0e91db00-d2ee-11e9-8517-e30efa071431.png)

**Comment by ivanopersico** [comment]
Visto grazie, pensavo di doverlo cercare nella schermata principale e non nei plugin
