### ISSUE TITLE
Autodeterminazione direzione DDT da record invece che dal nome del modulo

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#656]
Torno all'attacco sui DDT.... :)

Ho notato che i ddt in entrata e uscita sono implementati come due moduli che condividono lo stesso codice. 

Da ciò l'interfaccia mostrata per un dato ddt dipende dall'id del modulo passato nell'url, che viene letto in core.php e di cui poi viene letto il nome per determinare se la direzione è entrata o uscita.

Tutto ciò perchè vorrei creare una lista di tutti i DDT e pensavo di adattare la Vista del modulo 26: una volta modificata la query di select ho però il problema che tutti i ddt vengono aperti con la visualizzazione del modulo 26 anche se sono nell'altra direzione.

Non avrebbe più senso determinare la direzione a partire dal record (almeno in visualizzazione)?

Come workaround pensavo di modificare l'id del modulo nel file `custom/init.php` (che da quello che vedo dovrebbe essere eseguito sempre, giusto? dovrei solo verificare se il record esiste ed agire in quel caso) in base al valore del campo `dir` della tabella `dt_ddt` in questo modo: 
```
Modules::setCurrent(26 oppure 27);
$module = Modules::getCurrent();
$id_module = $module['id'];
```
È giusto? Potrebbero esserci effetti collaterali? Se si di che tipo?
Invece per quanto riguarda le azioni di gruppo è possibile disattivarle ?
<hr>

Un'altra soluzione potrebbe essere quella di creare una nuova vista ma non ho idea se la visualizzazione funzionerebbe correttamente... *edit*: ho provato a creare un nuovo modulo in cui la query sembra funzionare ma in tabella si vedono solo delle checkbox senza url in html

<hr>

Per ora la soluzione più semplice sembra creare un modulo custom in cui renderizzo io la tabella da php.

<details>
<summary>Oppure questo Frankenstein JS client side...</summary>

 ```javascript
$(document).ready(function () {
  var print_dbg = false;
  $("#tab_0 > div.row").hide();
  $('#tab_0 div.dataTables_scrollFoot').hide();
  $("#tab_0").on('user-select.dt', function (e, dt, type, cell, originalEvent) {
    e.preventDefault();
    return false;
  });

  function b9k__loop1_dt_hook() {
    try {
      $('#tab_0 div.dataTables_scrollBody table[data-idmodule=26] tbody tr td.select-checkbox').removeClass('select-checkbox');
      $('#tab_0 div.dataTables_scrollBody table[data-idmodule=26] tbody tr').each(function (index) {
        if(print_dbg) console.log("ROW " + index);
        var is_27 = false;
        $(this).find('td.select-checkbox').removeClass('select-checkbox');
        $(this).find("td").each(function (index2) {
          var txx = $(this).text();
          var t1 = (txx === "ENTRATA");
          if(print_dbg) console.log("   |-TD: " + index2 + " > " + txx);
          if(t1) {
            is_27 = true;
            return false;
          }
        });
        if(is_27) {
          if(print_dbg) console.log("   \-> SOSTITUZIONE ID NECESSARIA");
          $(this).find("[data-link^='/osm']").each(function (index3) {
            var dl = $(this).attr('data-link');
            dl = dl.replace(/\?id_module\=26\&/, "?id_module=27&");
            $(this).attr('data-link', dl); //.css('color','red');//degub
          });
        } else {
          if(print_dbg) console.log("   \-> ID CORRETTO");
        }
        if(print_dbg) console.log("DONE");
      });
    } catch (ex2) {
      console.log(ex2);
    }
  };
  b9k__loop1_dt_hook();
  $("#tab_0").on('draw.dt', function (e, dt, type, cell, originalEvent) {
    b9k__loop1_dt_hook();
  }); //setInterval(function(){b9k__loop1_dt_hook();},1000);
});
```

</details>

**Comment by Dasc3er** [comment]
Puoi semplicemente creare un modulo con solo query, per cui esistono delel impostazioni di personalizzazione dei link. In particolare, devi impostare entrambi i seguenti campi nelle viste collegate al nuovo modulo:

- ` _link_module_` ID del modulo da aprire
- `_link_record_` ID del recordda aprire

**Comment by Dasc3er** [comment]
Si, è sufficiente lasciare vuoto il campo **directory**.
E si, per ora è obbligatorio. Se vuoi puoi lavorare con i JS per nasconderlo.

**Comment by beppe9000** [comment]
Ok. Invece il codice js come faccio a farlo eseguire solo quando c'è l'elenco e solo in quel modulo? Sarebbe interessante prevedere una impostazione nelle Viste che permetta di aggiungere codice js e css per ogni modulo differenziando per le varie pagine (lista dei record, edit, etc..?).

In `include/custom/bottom.php` pensavo di controllare che il tipo di richiesta sia `GET` e che abbia un singolo parametro nella query string.

È giusto come ragionamento oppure sono previsti casi in cui i parametri siano più di uno?

**Comment by Dasc3er** [comment]
Basta che metti uno script JS che viene richiamato solo per il modulo dove ti serve...

**Comment by beppe9000** [comment]
> 
> 
> Basta che metti uno script JS che viene richiamato solo per il modulo dove ti serve...

nel caso di un modulo solo query dove lo metto?

**Comment by Dasc3er** [comment]
Puoi metterla nel bottom.php come dicevi, basta che in futuro ti ricordi di sincronizzare le modifiche ufficiali.

**Comment by beppe9000** [comment]
Quindi riguardo il numero di parametri è corretto dare per scontato che ce ne sia sempre uno solo (l'id del modulo) in caso di lista dei record ?

**Comment by loviuz** [comment]
@beppe9000 Oppure, se devi aggiungere codice JS solo per uno specifico modulo, a patto che sia una personalizzazione, puoi creare un file /modules/tuo_modulo/controller_before.php e scriverci all'interno codice php, html, js, ecc. E' un file che viene incluso dopo la tabella di datatables del modulo.
