### ISSUE TITLE
htaccess hell

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#657]
Questa riga sembra andare in conflitto con le rewrite rules di wordpress, se osm è installato in una sottocartella. A che serve? Si può disattivare? Se non la commento wordpress fa il redirect di `/osm` ad un errore 404 gestito da wordpress. Questo indipendentemente dalle regole che sono dopo quella riga..

https://github.com/devcode-it/openstamanager/blob/4f157aa5199ea1b404e95a841d31d2564911ae87/.htaccess#L34

Questo è l'htaccess di wp. ho provato anche ad aggiungere regole tipo `#RewriteRule ^osm\/? - [END]` ma non funziona...

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
```
Come si può risolvere?

**Comment by Dasc3er** [comment]
Dubito che il problema sia dovuto alla riga indicata, quanto al fatto che OpenSTAManager è in una sottocartella di WordPress...

**Comment by beppe9000** [comment]
Probabilmente è meglio passare a un sottominio apposito.... Nel frattempo però sai che tipo di conseguenze ci sono a disabilitare quella riga?

**Comment by Dasc3er** [comment]
Niente di particolare, dovrebbere essere l'impostazione di un flag aggiuntivo per PHP che noi non utilizziamo...

**Comment by beppe9000** [comment]
ottimo

**Comment by gbcelano** [comment]
Ciao. Ho lo stesso problema, come avete risolto?

**Comment by gbcelano** [comment]
Ciao. Ho lo stesso problema, come avete risolto?
Anche io ho WP nella root e OSM in una sottocartella, ma mai avuto questo problema con numerose installazioni sui diversi hosting (Aruba compreso) e con la stessa struttura; il problema mi si è presentato a seguito della migrazione su ServerPlan...
Certo, eliminando .htaccess della sottocartella di OSM funziona, ma sono certo che non è la soluzione corretta :-)
Se necessario sposto WP in una sua cartella, ma risolverei?
Bisogna lavorare sul .htaccess di OSM?
Grazie!

**Comment by beppe9000** [comment]
levando la riga incriminata da htaccess
https://github.com/devcode-it/openstamanager/blob/4f157aa5199ea1b404e95a841d31d2564911ae87/.htaccess#L34

**Comment by Dasc3er** [comment]
Aggiunto il commit 2d24c31eee7a2b48075855fd180c9799afb9f56d, che prevede un controllo sulla riga indicata da @beppe9000 .

**Comment by gbcelano** [comment]
Grazie @beppe9000 , non avevo letto il commento di @Dasc3er (_impostazione di un flag aggiuntivo per PHP che noi non utilizziamo..._)
Immagino di dover ignorare il messaggio di warning del Modulo mod-rewrite che esce nella procedura di controllo in fase di setup di OSM...  Grazie a tutti!
![osm](https://user-images.githubusercontent.com/64362921/98464773-4aac1e80-21c5-11eb-8af9-683f1ffb4966.jpg)
