### ISSUE TITLE
MIGLIORIA: Serial number deve essere univoco sullo stesso articolo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#658]
## Comportamento richiesto

Per ogni articolo dovrebbe essere prevista l'univocità del serial number

## Comportamento attuale

Adesso è possibile inserire più volte lo stesso serial number per un determinato articolo

## Possibile soluzione

Restituire un messaggio di errore se non viene rispettata la consizione di univocità

OSM 2.4.10

**Comment by Dasc3er** [comment]
@idraulicadueci Al momento l'unico modo per inserire più volte un serial number è tramite la funzione di collegamento e inserimento serial number sui documenti di acquisto.
In ogni caso, il serial number viene reso disponibile solo una volta per l'utilizzo.

**Comment by idraulicadueci** [comment]
@Dasc3er il problema è nella fase di inserimento dei documenti di acquisto, dove posso inserire lo stesso SN più volte.
Esempio:
Inserisco nuovo DDT in entrata, aggiungo un articolo per cui sia richiesto il S/N.
Se indico come quantità 3, mi viene data la possibilità di inserire 3 serial number, e in questo caso i valori devono essere univoci, altrimenti non vengono presi.
Se però nel DDT indico lo stesso articolo in una nuova riga, posso inserire un serial number già indicato nella riga precedente.
Questo succede quando per esempio si ha un ordine di n pezzi che vengono consegnati in diversi step, quindi evasi in diversi DDT.  e può succedere di inserire più volte lo stesso SN.

**Comment by Pek5892** [comment]
Corretto nelle successive versioni, nella versione 2.4.46 il problema non si presenta.
