### ISSUE TITLE
Sorgente dati select2 dinamiche

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#66]
Gestire le sorgenti dati dei menu a tendina del componente Select2 tramite database, per cui con "ajaxsource": "clienti" verrà utilizzata una query non più scritta su un file nella root, ma presa da db, così si potranno creare sorgenti dati personalizzati, crearne di nuove, e non dover modificare i file.

@Dasc3er, @fpsoftware, @lucasalva87 che ne pensate?

**Comment by Dasc3er** [comment]
Non sarebbe una cattiva idea, ma per operazioni un po' più complesse sarebbe comunque necessario usare un file con la procedura specifica...
In questi casi si potrebbe utilizzare una struttura modulare simile a quella introdotta nelle API, aggiungendo un file apposito per ogni modulo.

**Comment by Dasc3er** [comment]
Potrebbe essere utile implementare la stessa funzione per il file **ajax_autocomplete.php**.

**Comment by Dasc3er** [comment]
@loviuz Per la gestione del file **ajax_autocomplete.php** non sarebbe meglio impostarlo similmente al file **ajax_select.php**, cioè con richieste basate su una descrizione generica e non anche su un modulo?

Consiglierei la seguente separazione:
- File **ajax_search.php** per la gestione della ricerca
- File **ajax_complete.php** per la gestione di strutture HTML specifiche

Segnalo inoltre che di tutte le strutture HTML specificate in **ajax_autocomplete.php**, solo le seguenti sono utilizzate:
- get_sedi
- get_sedi_select
- getprezzi
- getprezzivendita
- getprezziacquisto

**Comment by loviuz** [comment]
Intendi quindi usare **ajax_search.php** per semplici liste, mentre **ajax_complete.php** per strutture più complesse, come ad esempio gli articoli che sono raggruppati per categorie/sottocategorie?

**Comment by Dasc3er** [comment]
@loviuz Intendo dedicare il file **ajax_complete.php** per la gestione di codice HTML per l'auto-completamento, come nel seguente esempio:
![immagine](https://user-images.githubusercontent.com/15911489/35778847-62299a2c-09c4-11e8-908a-a3778923148b.png)

Il file **ajax_search.php** sarebbe dedicato esclusivamente a gestire i risultati per la ricerca generale presente in alto a sinistra.

**Comment by Dasc3er** [comment]
Riguardo la struttura del database per le query dinamiche, credo che rischieremmo di rendere ancora più complesso la struttura interna del gestionale senza effettivi miglioramenti organizzativi.

Con la nuova suddivisione in branch 2.4, le query dinamiche sono già state suddivise in base al modulo a cui sono relative, migliorando la gestione prima estremamente concentrata.
A mio parere, già questa decentralizzazione può essere considerata sufficiente per le necessità di queste query.

-----------

Attualmente ogni singola query per il Select2 deve prevedere almeno 4 parti: la **query** di base, i campi che devono essere utilizzati per la **ricerca**, i campi che devono essere utilizzati come **identificatori** e i **campi aggiuntivi** che possono essere utilizzati come ulteriore restrizione.

Un esempio può essere la struttura necessaria per trovare i referenti di un'anagrafica:
```php
case 'referenti':
        if (isset($superselect['idanagrafica'])) {
            $query = 'SELECT id, nome AS descrizione FROM an_referenti |where| ORDER BY id';

            foreach ($elements as $element) {
                $filter[] = 'id='.prepare($element);
            }

            $where[] = 'idanagrafica='.prepare($superselect['idanagrafica']);

            if (!empty($search)) {
                $search_fields[] = 'nome LIKE '.prepare('%'.$search.'%');
            }
        }
        break;
```

Prevedere una struttura database che permetta di personalizzare tutti questi elementi (che sono quelli di base per queste query) e successivamente interpretarli nella query definitiva renderebbe la gestione esclusivamente più complesse e difficile da personalizzare in futuro.
