### ISSUE TITLE
MIGLIORIA: Aggiunta numero revisione nei preventivi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#660]
## Comportamento richiesto

Aggiungere il numero progressivo di revisione accanto al numero del preventivo. Per es: numero originale preventivo 1234/2019, creo revisione il numero diventa 1234/2019 rev. 2

## Comportamento attuale

Allo stato attuale viene lasciato il numero progressivo di origine.

**Comment by loviuz** [comment]
@lucasalva87 lo mettiamo di default nella stampa dove c'è scritto "PREVENTIVO NUM. X DEL dd/mm/yyyy", facendolo diventare "PREVENTIVO NUM. X rev. Y DEL dd/mm/yyyy"? Magari solo se la revisione è diversa dalla 1, o meglio lasciare sempre il numero di revisione?

**Comment by Dasc3er** [comment]
E' ora disponibile il campo ausiliare `{revisione}` che contiene il numero della revisione.
