### ISSUE TITLE
MIGLIORIA: Aggiunta nome impianto nell'elenco impianti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#661]
Se un cliente ha più impianti è difficile reperire dall'elenco my-impianti quello che si vuole visionare

**Comment by loviuz** [comment]
La colonna "Nome" nel modulo "MyImpianti" è stata introdotta dalla versione 2.4.3, per cui è già presente.

**Comment by idraulicadueci** [comment]
@loviuz chiedo scusa, avevo erroneamente cancellato il campo nella vista della tabella.
