### ISSUE TITLE
errore su sconto incondizionato

### ISSUE THREAD

**Issue by osm-gc** [devcode-it/openstamanager#662]
Sulla versione 2.4.2 in fase di creazione ordine cliente dal preventivo se esiste lo sconto incondizionato si comporta in modo errato nel caso che si effettua un passaggio parziale del preventivo stesso.
Riporta in sostanza, come rigo, lo stesso sconto calcolato sull'intero documento e non lo ricalcola solo sui righi selezionati. 
Sapete dirmi se questa problematica è stata già affrontata considerando che la versione indicata è quella usata 

Grazie

**Comment by Dasc3er** [comment]
@osm-gc Il comportamento è corretto: lo sconto è una riga a tutti gli effetti e non può essere riportata parzialmente.

**Comment by osm-gc** [comment]
Lo sconto però è calcolato sull'intero documento e se resta uguale in caso di scelte parziali, l'importo riportato è errato.

**Comment by osm-gc** [comment]
@Dasc3er Ho dimenticato di indicare che parlavo dello sconto incondizionato in **percentuale**. In euro naturalmente il comportamento è corretto come giustamente hai segnalato.

**Comment by loviuz** [comment]
@osm-gc Se è presente uno sconto sulle singole righe, quando le evadi viene riportato anche nel documento successivo. Se invece usi uno sconto su tutto il documento, diventando una normalissima riga in fondo alle altre, l'unico modo è evaderla singolarmente solo in uno dei documenti successivi.

Ad esempio, se hai uno sconto su un preventivo che evadi in 3 fatture, dovrai scegliere su quale delle 3 fatture inserire lo sconto, non viene riportato su tutte e 3 le fatture.
