### ISSUE TITLE
MIGLIORIA: Mostrare sede diversa su attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#663]
## Comportamento richiesto

Mostrare indirizzo di intervento

## Comportamento attuale

Viene mostrata la sede legale dell'anagrafica

## Possibile soluzione

Come per le fatture, mostrare la sede legale dell'anagrafica e aggiungere una altra riga dove viene mostrato il luogo in cui è stato effettuato l'intervento.

OSM 2.4.10

**Comment by Pek5892** [comment]
Introdotta nelle release successive.
Fix v.2.4.34
