### ISSUE TITLE
MIGLIORIA: aggiungere scadenze bollo automezzi e revisioni automezzi

### ISSUE THREAD

**Issue by miatmax** [devcode-it/openstamanager#664]
## Comportamento richiesto

Sarebbe carino che nella gestione automezzi si potesse inserire la scadenza bollo e la scadenza revisione, con eventuale notifica 1 settimana prima della scadenza

## Comportamento attuale

Al momento non mi sembra sia possibile.

**Comment by Dasc3er** [comment]
@miatmax A partire dalla versione 2.4.10 gli automezzi non sono più gestiti dal gestionale, per mia conoscenza.

**Comment by loviuz** [comment]
@miatmax puoi usare lo scadenzario generico per inserire scadenze generiche. Non è prevista però ancora una notifica per le scadenze ma le troveresti tutte in ordine di scadenza sotto "Contabilità" -> "Scadenzario"
