### ISSUE TITLE
Errore durante creazione promemoria

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#665]
**Versione:** 2.4.10

Durante la creazione del promemoria su un contratto, alla spunta di creare un promemoria ciclico e la creazione contemporanea dell'intervento, viene restituito questo errore:

![immagine](https://user-images.githubusercontent.com/1647128/66941698-c336bf00-f047-11e9-8998-6db97837ac16.png)

**Comment by lepool** [comment]
Presumo che idsede sia stato cambiato in idsede_destinazione con l'update mysql.
