### ISSUE TITLE
Problema con l'additional query

### ISSUE THREAD

**Issue by CJBeppe** [devcode-it/openstamanager#669]
Creando dei segments per il modulo Preventivi mi sono accorto che se modifico i dati di una scheda, questa poi non viene ricaricata dando "Record non trovato" se i dati inseriti non rientrano nel filtro impostato. Penso che in qualche punto al carimcamento dell'editor venga richiamato l'additional query, ma in questo andrebbero tolti i segment per evitare scomodità.

**Comment by CJBeppe** [comment]
Ora però non mi imposta mai i segments. Manca qualche controllo sulla pagina per distinguere l'editor dal controller?

**Comment by Dasc3er** [comment]
Errore mio, li avevo disabilitati in modo completo nella fase di test.
Ora dovrebbe funzionare correttamente.
