### ISSUE TITLE
MIGLIORIA: Disattivazione pulsante invio fattura per e-mail se BOZZA

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#671]
## Comportamento richiesto

Disattivare il pulsante INVIA FATTURA se STATO="BOZZA"

## Comportamento attuale

Allo stato attuale è possibile inviare la fattura anche se non è EMESSA. Nella fattura in stato BOZZA non vengono visualizzate le scadenze.

OSM 2.4.10

**Comment by loviuz** [comment]
io lo lascerei per poter inviare una bozza di fattura prima dell'accettazione.
