### ISSUE TITLE
Bug su aggiunta al volo di un record

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#672]
Quando tento di aggiungere un articolo in un documento con "+ Articolo", se premo il "+" di fianco al menu a tendina con la lista articoli, posso inserire al volo un articolo nuovo:

![immagine](https://user-images.githubusercontent.com/1647128/68655179-d6965680-052f-11ea-9dc4-c017f9813bf0.png)

Quando confermo l'inserimento del nuovo articolo, lo vedo popolato nel menu a tendina, però il campo "Descrizione" subito sotto non si compila e l'utente lo deve inserire a mano:

![immagine](https://user-images.githubusercontent.com/1647128/68655229-ef067100-052f-11ea-97f0-a5e484ebe981.png)

**Comment by Dasc3er** [comment]
@loviuz L'aggiunta di altri valori è ora possibile attarverso l'array _data_ all'interno della risposta AJAX al salvataggio del nuovo elemento aggiunto al volo. Ovviamente il completamento deve poi essere gestito a livello JS, come avviene ora di default.

**Comment by loviuz** [comment]
@Dasc3er ok, però forse non avevi inteso correttamente l'errore, perché guardando il commit e facendo nuovamente una prova non vedo il funzionamento corretto. Se dalla fattura premo "+ articolo", l'articolo non è presente in lista e premo il "+" a fianco del menu a tendina per creare un nuovo articolo al volo, quando viene creato via ajax e si ritorna alla popup di inserimento articolo, il nuovo articolo è selezionato nel menu a tendina ma non viene riportata la descrizione nel campo "Descrizione" della popup di aggiunta articolo:

![immagine](https://user-images.githubusercontent.com/1647128/68747234-686a9600-05fa-11ea-9755-7dc8032a8ecf.png)

**Comment by Dasc3er** [comment]
Hai ricompilato gli assets?

**Comment by loviuz** [comment]
Testato e risolto, ottimo! Erano gli assets da ricompilare in effetti...
