### ISSUE TITLE
Problema in fase di rinnovo contratto

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#673]
Quando provo a rinnovare un contratto contenente due o più righe generiche il gestionale va in errore come in allegato. La versione in test è la 2.4.11 (in sviluppo)

![Contratti   OpenSTAManager(1)](https://user-images.githubusercontent.com/30728163/68670107-62b67700-054c-11ea-847b-6bc57307eb85.png)

Inoltre il contratto rinnovato dovrebbe presentare lo stato "Bozza" e non lo stesso del contratto precedente.

**Comment by Dasc3er** [comment]
@lucasalva87 Puoi testare con gli ultimi commit? Il problema dovrebbe essere risolto...

**Comment by lucasalva87** [comment]
Confermo che ora il rinnovo del contratto avviene correttamente. Grazie!
