### ISSUE TITLE
inserimento diretto sottocategoria da inserimentonuovo articolo non possibile

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#674]
## Comportamento richiesto

Inserimento sottocategoria di una categoria direttamente da articolo

## Comportamento attuale

Quando inserisco la sottocategoria di una categoria direttamente da inserimento articolo, non viene generata la sottocategoria.

## Passi per riprodurre il comportamento

1. creare un articolo dal modulo articoli
2. selezionare una categoria
3. ora aggiungere una nuova sottocategoria 

Eventuale codice rilevante:

https://github.com/devcode-it/openstamanager/blob/dda875a75e92c9e1620b1e6fa0b3ce823dbf1549/modules/categorie_articoli/actions.php#L68

da sostituire con:

if (isset($id_record) && $id_record != "" ) {

È un fix temporaneo. Da qualche parte viene settato id_record vuoto. Presumo nella parte javascript ajax. Non sono riuscito a trovarlo.

Versione OSM 2.4.10

**Comment by Dasc3er** [comment]
@lepool Il funzionamento è corretto nell'ultima versione.
