### ISSUE TITLE
Produrre release

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#678]
Come posso ottenere un file zip identico a quello scaricabile dal sito del progetto a partire dal repository clonato?

È sufficiente eseguire `yarn run develop-OSM` o sono necessari altri comandi (oltre a quello per zippare tutto :) )?

Ps. Invece per produrre un pacchetto di aggiornamento come si procede?

**Comment by Dasc3er** [comment]
Per produrre lo zip è utilizzabile il comando `yarn run release-OSM`.
Se hai utilizzato la logica di default per le versioni puoi utilizzare il pacchetto di release come pacchetto di installazione e di aggiornamento.

**Comment by beppe9000** [comment]
Posso alterare l'archivio per omettere alcuni file o aggiungere update a cartelle /custom ?

**Comment by beppe9000** [comment]
Ho fatto un test e si blocca dopo avermi chiesto la versione e se è una beta...

**Comment by Dasc3er** [comment]
Dovrebbe aver creato uno zip di nome **release.zip** nella cartella principale.

**Comment by beppe9000** [comment]
Ok, c'è. È previsto un messaggio ad operazione terminata, o è normale che la procedura non restituisca il controllo al prompt dei comandi?

**Comment by Dasc3er** [comment]
Dovrebbe dire qualcosa tipo "zip creato con successo"

**Comment by beppe9000** [comment]
Boh, a me è rimasto fermo per ore prima che lo terminassi manualmente
