### ISSUE TITLE
Generare fattura elettronica da fattura parzialmente pagata corrompe dati su tabella fattura

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#679]
## Comportamento richiesto

Una fattura parzialmente pagata (come per un acconto) e correttamente contabilizzata come tale, all'atto della generazione della fattura elettronica la generi correttamente. 

## Comportamento attuale

Alla generazione della fattura elettronica il sistema fallisce la generazione e la fattura scompare dall'elenco. Risultano azzerati alcuni campi della tabella delle intestazioni fattura che ne impediscono la visualizzazione.

## Possibile soluzione

Verificare eventuali errori durante la modifica riga per progressivo FE.

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Creo una fattura verso il cliente (es da 100 euro)
2. Segnalo il pagamento parziale tramite "Registra contabile pagamento..."
3. Predispongo la fattura per la generazione, la genero e la fattura scompare.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Fatturazione in uscita
* Versione del progetto: 2.4.10
* Versione PHP: 7
* Tipo di server: Custom

**Comment by Dasc3er** [comment]
Questo problema dovrebbe già essere risolto nella versione master in sviluppo, che a breve dovrebbe essere rilasciato come 2.4.11. 
Al momento sono in corso numerosi test sull'intera versione per individuare e risolvere i malfunzionamenti presenti.
