### ISSUE TITLE
Problema logo di default per stampe

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#680]
Mi hanno segnalato che nella su alcune stampe di contabilità compare questa immagine invece che il logo per le stampe impostato in fase di installazione (v2.4.9).

![image](https://user-images.githubusercontent.com/6625123/69538171-ff800800-0f81-11ea-8ac2-acec705a5e50.png)

Io ho risolto rimpiazzando il file con l'immagine giusta, ma rimane un bug da investigare meglio.

**Comment by marcus905** [comment]
Confermo il problema, particolarmente evidente sulla stampa contabile IVA.

La contabile IVA non ha un file header.php, quindi prende dall'header.php in base, quindi il problema ha effetto per tutti i moduli che utilizzano l'header di base.

Probabilmente non viene caricata correttamente la variabile logo nella predisposizione dei dati.

**Comment by Dasc3er** [comment]
@beppe9000 @marcus905 Il problema sembra essere risolto nella versione 2.4.12, potete confermare?

**Comment by marcus905** [comment]
Confermo la risoluzione, ora funziona correttamente

**Comment by Dasc3er** [comment]
Grazie!

**Comment by beppe9000** [comment]
Ottimo!
