### ISSUE TITLE
Completamento piano dei conti

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#682]
Per tutti i conti sotto lo "Stato patrimoniale" è necessario che venga riportato nei totali la somma degli anni precedenti. Ogni inizio anno infatti, le aziende si ritrovano in questi conti anche il totale derivante dagli anni precedenti, come ad esempio il conto "Banca C/C", "Cassa", i crediti e debiti dei clienti e fornitori, poiché fanno parte del "patrimonio" dell'azienda.

Occorre visualizzarli sia a video nel piano dei conti che in stampa.

Visivamente, se la lista dei movimenti di "Banca C/C" si presenta ora così:
![immagine](https://user-images.githubusercontent.com/1647128/69568332-b0ef5f80-0fbb-11ea-8bd8-9aa403002126.png)

dovrebbe cambiarsi così:

![immagine](https://user-images.githubusercontent.com/1647128/69568459-eeec8380-0fbb-11ea-9eca-7061bab1bb58.png)
Stessa logica anche per le stampe.

**Note tecniche:**
 - se la differenza della banca è in positivo nel periodo precedente, l'importo deve andare in "Dare" e sommarsi al totale attuale, altrimenti l'importo va in "Avere" e si sottrae (stesse logiche attuali, è come se fosse un movimento fittizio)

L'idea iniziale era di fare un movimento fittizio, però i bilanci non si chiudono mai al 31/12, per cui fino a metà anno successivo gli anni precedenti possono sempre subire delle variazioni, per cui quel movimento fittizio andrebbe sempre aggiornato, soluzione forse da evitare.

**Comment by Dasc3er** [comment]
Sarebbe da creare una funzione apposita che esegue la somma per gli anni precedenti, oppure ancora meglio si potrebbe creare una classe fittizia da aggiungere in automatico alla lista dei movimenti per i conti, che in questo caso si dovrebbero convertire in classi essi stessi.

Dunque per il modulo Partitario o Piano dei conti servirebbero quattro classi: 
- Categoria (livello 1)
- Insieme (livello 2)
- Conto (livello 3), collegato ai Movimenti di Prima nota (individuati tramite anno specificato)
- Riepilogo storico, Movimento fittizio che include in automatico gli anni precedenti per le categorie di una certa tipologia (magari attraverso un flag) e viene inserito tra i movimenti dalla classe Conto interessata

Ció permetterebbe di aggiornare la logica attraverso le classi e al tempo stesso di prevedere uno storico del Piano dei conti, visualizzando i contenuti degli anni precedenti senza troppe modifiche interne.

@loviuz Avresti suggerimenti per i nomi?

**Comment by loviuz** [comment]
@Dasc3er Categoria, Insieme e Conto li chiamerei Conto1, Conto2 e Conto3, non per dare un nome generico, ma perché rappresentano i 3 livelli di profondità dei conti. "Riepilogo storico" potrebbe chiamarsi "AperturaConti" perché gli unici movimenti fittizi sono proprio questi movimenti che rappresentano l'apertura dei conti con il cambio anno.

Dato che finalmente presumo pubblicheremo la 2.4.11, possiamo lavorarci per la 2.4.12, che ne dici? :-D

**Comment by Dasc3er** [comment]
Conto1, Conto2 e Conto3 non sono il massimo come nome perchè non indicano chiaramente la dipendenza di livello...
@lucasalva87 Cosa ne pensi?

**Comment by loviuz** [comment]
Ho rivisto il funzionamento pratico di questa funzionalità e l'ho sviluppata in 7fefe724c038cca5eed0bdec39376cff13cd4524.
In partica il comportamento non dovrebbe essere automatico ma eseguito con funzioni specifiche, per questo sono stati aggiunti i pulsanti "Apertura bilancio" e "Chiusura bilancio" che eseguono i movimenti di prima nota in co_movimenti, perché nel mondo contabile questi saldi precedenti devono essere delle scritture contabili reali.
