### ISSUE TITLE
Reset istanza di OSM

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#683]
Come posso azzerare (= eliminare tutte le entità) il database di OSM mantenendo le varie personalizzazioni fatte tramite l'interfaccia?

**Comment by Dasc3er** [comment]
Un sistema di reset dell'installazione non è al momento previsto, né di prossima implementazione. 
È necessario quindi cancellare i contenuti del database e reinstallare il gestionale.

**Comment by beppe9000** [comment]
Quindi per eliminare i dati ma non le impostazioni e personalizzazioni faccio `TRUNCATE` sulle tabelle non  prefissate con `zz_` e ne resetto gli `auto_increment` dell'id, giusto ?

**Comment by Dasc3er** [comment]
No, perché ci possono essere delle righe predefinite nelle tabelle. Iva, tipologie documenti, ...

**Comment by beppe9000** [comment]
Il ripristino di un backup non mantiene nulla dell'istanza attuale, giusto?

Per esempio è possibile il downgrade?
O anche il ripristino di una versione successiva?

Pensavo di fare una cosa del genere:
Backup produzione > Ripristino backup su server di sviluppo > Aggiornamento a versione nuova > Backup del server di sviluppo > Ripristino su server di produzione

C'è un modo migliore ?

**Comment by Dasc3er** [comment]
No, quello che hai indicato è un modo diretto di procedere.

**Comment by beppe9000** [comment]
apposto
