### ISSUE TITLE
Personalizzazioni a oggetti

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#684]
Per quando osm sarà completamente gestito tramite classi...

Suggerirei di permettere la personalizzazione tramite subclassing attraverso un namespace diverso gestito con un autoloader personalizzato. Per esempio quando viene caricata la classe /OSM/Articoli verifica se esiste /OSM/Custom/Articoli e in tal caso si usa la seconda.

La stessa logica può anche essere implementata rendendo i vari constructor privati ed usando invece una funzione statica per ottenere una istanza della classe originale oppure di quella personalizzata, se esiste. In questi modi le modifiche si limiterebbero alle sole differenze e non necessiterebbero di duplicare tutto.

**Comment by Dasc3er** [comment]
Ciò avviene già in modo limitato: se si inserisce nella cartella **custom/src/** la classe Articolo modificata viene utilizzata questa rispetto all'originale. È però necessario che la classe personalizzata sia una copia dell'originale, con tutti i metodi relativi.

Non è possibile utilizzare un ulteriore namespace senza creare una serie di file vuoti per ogni classe per registrare esclusivamente il namespace Custom, a causa del sistema di implementazione dei namespace in PHP.

**Comment by beppe9000** [comment]
I file si potrebbero creare automaticamente con un commento che spiega il loro utilizzo ma certamente è poco elegante. La soluzione basata su constructor statico potrebbe quindi avere senso (controllando la logica di inclusione il problema non si pone).

**Comment by Dasc3er** [comment]
Ciò in ogni caso non è possibile per la struttura interna di Eloquent, che necessita di classi specifiche per la gestione delle relazioni. Nel creare file vuoti si svilupperebbe solo del codice inutilizzato e poco chiaro che causerebbe problemi nella logica di funzionamento del gestionale.

Inoltre è più corretto che sia implementata completamente la classe da personalizzare, in modo tale da costringere una maggiore attenzione alle operazioni di aggiornamento del gestionale alla base: se la classe Articolo personalizzata modifica i movimenti utilizzando un metodo nativo, niente esclude che il metodo nativo venga cambiato in una versione successiva portando quindi a malfunzionamenti difficili da individuare.

Certamente può essere più scomodo in caso di personalizzazioni di moduli preesistenti, ma fino a che le classi predefinite non vengono rese il più possibile generali questo comportamento è migliore, visto che per ora il comportamento interno può variare completamente tra una versione e l'altra.

**Comment by beppe9000** [comment]
Doctrine non mi sembra abbia questo problema... https://www.laraveldoctrine.org/

**Comment by beppe9000** [comment]
Potrebbe essere utile una cosa del genere per ovviare al problema oppure non funziona con eloquent?
https://stackoverflow.com/questions/47925618/laravel-5-5-override-vendor-class

**Comment by Dasc3er** [comment]
Questo è esattamente quello che facciamo.
Override completo della classe di default con i contenuti di custom/src. Quindi la classe custom deve essere una copia dell'originale, poi modificata, e non un esternsione.

**Comment by beppe9000** [comment]
però in quel link si parla chiaramente di una classe che va ad estendere l'originale...

```PHP
namespace App\Vendor;
class MyCustomClass extends Vendor\VendorName\Class {
    // blah....
}
```

**Comment by Dasc3er** [comment]
No, non viene detto questo... Viene parlato di override e non extend.
