### ISSUE TITLE
Estensione timeout sessione con pagina aperta

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#685]
Spesso capita che avvenga il logout automatico dopo parecchio tempo di inattività anche se osm è ancora aperto (magari mentre si sta compilando un modulo). Sarebbe utile usare javascript ( `setInterval()` + ajax ) per prolungare la sessione corrente fintanto che osm è aperto nel browser.

**Comment by Dasc3er** [comment]
Questa funzione dovrebbe essere già disponibile dalla versione 2.3 o perfino 2.2, attraverso il flag "Mantieni sessione attiva" al login.
Se il flag non è presente allora la funzione è abilitata di default, e viene eseguita una chiamata JS ogni 5 minuti (credo) per mantenere attiva la sessione.

**Comment by beppe9000** [comment]
Ok, pensavo la spunta fosse per rendere permanente la sessione attiva (la classica funzione 'ricordami' dei siti web).
