### ISSUE TITLE
Autodeterminazione componenti da file system

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#686]
## Comportamento richiesto

Poter creare plugin/moduli/etc. senza toccare il database.

## Possibile soluzione

Definizione delle informazioni all'interno del file php del modulo in modo da poter poi creare una procedura che facendo il loop dei moduli le estragga, permetta di visualizzarle/verificarne la correttezza e poi le inserisca nel db.

**Comment by Dasc3er** [comment]
L'idea non è efficiente al fine delle risorse richieste al server PHP, che sarebbe rallentato dalla necessità di individuare ad ogni esecuzione i moduli previsti.

Per la prossima versione più consistente è prevista una revisione delle logiche del funzionamento della maggior parte dei componenti, che non saranno più legati ad una struttura fissa oltre una interfaccia standard. Questo per permettere l'implementazione di moduli indipendenti e più complessi rispetto allo standard attuale, senza avere la necessità di una struttura fisica predefinita.
Il salvataggio a database è fondamentale per questa evoluzione, e pertanto non diventerà *mai* un'opzione facoltativa.

Se vuoi dare un'occhiata alle modifiche previste puoi controllare il branch *future*, ovviamente altamente sperimentale per ora.

**Comment by beppe9000** [comment]
> L'idea non è efficiente al fine delle risorse richieste al server PHP, che sarebbe rallentato dalla necessità di individuare ad ogni esecuzione i moduli previsti.

Infatti ciò che suggerivo non è di fare questa ricerca ad ogni caricamento di pagina, ma di permettere all'admin di premere un bottone per eseguire la rigenerazione delle tabelle manualmente.
Basta farla una volta sola..., sarebbe una specie di "setup".
<hr>

> Per la prossima versione più consistente è prevista una revisione delle logiche del funzionamento della maggior parte dei componenti, che non saranno più legati ad una struttura fissa oltre una interfaccia standard. Questo per permettere l'implementazione di moduli indipendenti e più complessi rispetto allo standard attuale, senza avere la necessità di una struttura fisica predefinita.

Buono che ci si muova in questa direzione. C'è già un periodo pianificato per la release ?

**Comment by Dasc3er** [comment]
Per il periodo di release, per il momento non è ancora previsto niente poiché le modifiche da completare sono piuttosto sostanziali. 

Per quanto riguarda il pulsante per il refresh dei moduli, è previsto qualcosa di simile ma ancora non è stato implementato.
