### ISSUE TITLE
Errore in fase di aggiornamento database

### ISSUE THREAD

**Issue by Bacca1997** [devcode-it/openstamanager#687]
Errore in fase di aggiornamento da 2.3.1 a master:

`Logs.ERROR: Class 'Update\v2_4_10\Components\Riga' not found {"code":0,"message":"Class 'Update\\v2_4_10\\Components\\Riga' not found","file":"/samba/dev1/osm2411/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php","line":487,"trace":"#0 /samba/dev1/osm2411/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php(56): Illuminate\\Database\\Eloquent\\Model->newRelatedInstance('Update\\\\v2_4_10\\\\...')`

**Comment by Dasc3er** [comment]
È necessaria una ricompilazione di composer, dopo di che puoi fare riprendere l'aggiornamento.
Prova `php composer.phar dump-autoload` oppure `yarn run develop-OSM`.

**Comment by lucasalva87** [comment]
Dovrebbe essere risolto nella 2.4.11 finale
