### ISSUE TITLE
Opzione per tornare alla vecchia generazione del numero delle fatture di vendita

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#688]
## Comportamento richiesto

Una opzione per disattivare il comportamento attuale e tornare a quello precedente

## Comportamento attuale

Il numero delle fatture di vendita viene generato all'emissione della stessa

## Possibile soluzione

Aggiungere una opzione nel modulo **Impostazioni**

## Contesto

* Modulo: Fatture di vendita
* Versione del progetto: 2.4.11
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
@maicol07 Il punto di questa nuova gestione è che logicamente più corretta rispetto alla precedente per la gestione della corretta numerazione fatture.
Per esempio, se con più fatture in Bozza generate il 01/01 e il 11/01 viene Emessa per prima quella dell'11/01, essa avrà una **numerazione fiscale** che precede quella del 01/01.

Per quale motivo vorresti tornare al sistema vecchio?

**Comment by maicol07** [comment]
Bisognerebbe aggiungere delle opzioni per permettere agli utenti di selezionare quale comportamento soddisfa meglio le sue esigenze...

**Comment by Dasc3er** [comment]
Sto appunto chiedendo la motivazione dietro questa esigenza...

**Comment by maicol07** [comment]
Se un utente si trova meglio con la vecchia generazione dovrebbe avere la possibilità di scegliere... magari uno di questi giorni mando una PR
