### ISSUE TITLE
Velocizzare caricamento modal e altre pagine

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#689]
## Comportamento richiesto

Maggiore velocità nel passare da una pagina all'altra del gestionale e nel caricamento dei modal

## Contesto

* Versione del progetto: 2.4.11
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Suggerimenti pratici?

**Comment by maicol07** [comment]
Non me ne viene in mente nessuno al momento 😅 
Magari al primo login dal dispositivo inserire qualche asset statico nella cache del browser?

**Comment by Dasc3er** [comment]
La cache è automatica del browser, quindi non possiamo fare molto...

**Comment by maicol07** [comment]
@Dasc3er mi è venuta un'idea: si potrebbe utilizzare una richiesta AJAX per il salvataggio dei dati in background e JavaScript per aggiungere i dati alla pagina (ad esempio con la lista delle righe)

**Comment by Dasc3er** [comment]
La funzionalità è già in progetto per la versione 2.5, ma non aiuterebbe per niente a velocizzare il gestionale e ne rallenterebbe invece l'utilizzo alla lunga da parte del browser.

**Comment by Dasc3er** [comment]
Chiudo la issue poichè non presenta particolari soluzioni a livello di codice.
Idealmente, la versione 2.5 dovrebbe ridurre la massa di codice che viene eseguita ad ogni richiesta al gestionale e dunque diventare più rapida (ma ovviamente è necessario attendere lo sviluppo effettivo),

**Comment by maicol07** [comment]
@Dasc3er ho notato un numero eccessivo di richieste dovute agli hook (file allegato) se può risultare utile per qualche ottimizzazione.
Ho anche notato la nuova branch laravel-mix. I lavori sulla 2.5 sono iniziati?
[console-export-2020-4-17_11-38-8.txt](https://github.com/devcode-it/openstamanager/files/4492138/console-export-2020-4-17_11-38-8.txt)

**Comment by Dasc3er** [comment]
I lavori sulla 2.5 sono iniziati da un pezzo ormai, ma vanno avanti molto lentamente per ora nella branch future. La branch laravel-mix prova ad aggiornare la gestione degli assets sempre per la versione 2.5.

Per quanto riguarda gli hook, non dovrebbero in alcun modo rallenta il gestionale perché sono gestiti tramite richieste ajax asincrone. Il numero di chiamate è necessariamente elevato per garantire che gli hook si aggiornino correttamente (per esempio, per l'invio email).

**Comment by Dasc3er** [comment]
@maicol07 Se sei interessato ad alcuni approfondimenti su ciò che è previsto per la versione della branch future, ti consiglio di consultare #710, e i relativi #793 #792 #791 #786.
Come puoi vedere, le modifiche sono considerevoli quindi fino a che non viene rilasciata una versione 2.4.* accettabilmente stabile lo sviluppo è limitato.

**Comment by maicol07** [comment]
@Dasc3er ho trovato questo esempio per caricare le righe di DataTables a blocchi: https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html
Pensi che potrebbe essere utile al fine di migliorare la velocità di caricamento dei record quando si hanno tante colonne (che equivale a tante operazioni in una sola query)?
Magari utilizzando la keyword LIMIT di SQL

**Comment by Dasc3er** [comment]
@maicol07 La funzionalità di caricamento via AJAX (server side) è già implementata dalla versione 2.3 ufficialmente con Datatables, e ancora in alcune installazioni della 2.2 tramite JS puro.
Al momento, tutte le nostre tabelle principali sono gestite da Datatables, che carica circa 120-200 righe sulla base del dispositivo in utilizzo.

**Comment by maicol07** [comment]
Strano... sulla mia installazione vengono caricate in un blocco unico e impiega una ventina di secondi a caricare... eppure il file `assets/src/js/datatables.js` è uguale all'originale (non è stato modificato)

**Comment by lepool** [comment]
@maicol07 hai percaso attivo il log in mysql? A me rallentava parecchio le operazioni .

**Comment by maicol07** [comment]
> @maicol07 hai percaso attivo il log in mysql? A me rallentava parecchio le operazioni .

No, non è attivo
