### ISSUE TITLE
Problema con il campo "DATA COMPETENZA"

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#690]
Dato che il campo DATA COMPETENZA è diventato obbligatorio, nelle fatture inserite con la ver. 2.4.10 se avevano il campo vuoto, non è possibile riportare la fattura allo stato bozza.

La soluzione è quella di far diventare il campo attivo al momento che seleziono lo stato BOZZA.

OSM 2.4.11

**Comment by Dasc3er** [comment]
Le query finali del file di aggiornamento dovrebbero risolvere il problema:
```
UPDATE `co_documenti` SET `data_registrazione` = NULL WHERE `data_registrazione` = '0000-00-00';
UPDATE `co_documenti` SET `data_registrazione` = `data` WHERE `data_registrazione` IS NULL AND idtipodocumento IN (SELECT id FROM co_tipidocumento WHERE dir = 'uscita');
UPDATE `co_documenti` SET `data_competenza` = `data_registrazione` WHERE `data_competenza` = '0000-00-00' OR `data_competenza` IS NULL;
```

Hai aggiornato normalmente l'installazione dalla 2.4.10?

**Comment by idraulicadueci** [comment]
L'aggiornamento l'ho fatto tramite FTP perché con la funzione di OSM mi si era bloccato, però l'aggiornamento del database non mi ha dato errori.

**Comment by Dasc3er** [comment]
Mmmh...
Riusciresti ad eseguire la seguente query?
```
UPDATE `co_documenti` SET `data_competenza` = `data` WHERE `data_competenza` = '0000-00-00' OR `data_competenza` IS NULL;
```

**Comment by idraulicadueci** [comment]
ok, ora è tutto a posto. Grazie mille

**Comment by Dasc3er** [comment]
Aggiungeremo la query sulla 2.4.12 per sicurezza
