### ISSUE TITLE
Segnalazione bug dettaglio costi ore lavorate

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#691]
I dettagli mostrati in 'ore' e 'km' dall'opzione `visualizza dettagli costi` escono deformati.

![image](https://user-images.githubusercontent.com/6625123/69904018-a230f000-13a1-11ea-81a1-1e2165d13916.png)

ps. dimensioni viewport 1440 X 800

**Comment by Dasc3er** [comment]
@loviuz @lucasalva87 Che ne dite di visualizzare i dettagli attraverso un modal apposito?
In questo modo possiamo migliorare la grafica relativa alle righe in modo anche consistente. Potrebbe essere utile creare un modal generale anche per Fatture, DDT, ... che mostra tutte le operazione che vengono fatte per il calcolo dei totali.

**Comment by loviuz** [comment]
direi di sì, l'ho notato giusto oggi, anche se forse si potrebbe ampliare il riquadro con il riepilogo dei costi rendendolo quasi identico a fatture/ddt/ecc, perché ormai anche negli interventi ci sono il costo di acquisto, prezzo di vendita, guadagno (quindi margine), ecc.

**Comment by beppe9000** [comment]
questo tipo di problema c'è anche per le righe dei rapporti in mobile
![image](https://user-images.githubusercontent.com/6625123/75783485-ef39af00-5d60-11ea-8a32-e58ad0e87ecb.png)

Suggerirei di valutare gli approcci alle tabelle responsive mostrati in questa pagina: https://elvery.net/demo/responsive-tables/#flip-scroll in particolare l'inversione delle colonne con le righe per schermi stretti

**Comment by Dasc3er** [comment]
@beppe9000 Con il commit precedente il problema dovrebbe essere risolto con un semplice scroll.@beppe9000 Con il commit precedente il problema dovrebbe essere risolto con un semplice scroll.

**Comment by beppe9000** [comment]
ok. questo e l'altro fix saranno nella 2.4.16 definitiva?

**Comment by Dasc3er** [comment]
Saranno nella versione 2.4.17.
Al momento il team di sviluppo sta sperimentando con un nuovo sistema di rilascio, dove le versioni a numero pari integrano nuove funzioni (potenzialmente con problemi e bug, quindi prerelease/beta) mentre le versioni dispari contengono bugfix e miglioramenti ridotti.

**Comment by beppe9000** [comment]
una scelta strana...

**Comment by Dasc3er** [comment]
@beppe9000 Per quale motivo?

**Comment by beppe9000** [comment]
io preferirei il semantic versioning, suffissando le versioni non stabili con `-beta` o altro
