### ISSUE TITLE
Stampa fattura con pagamenti completati segnati come tali

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#693]
## Comportamento richiesto

Inserire la dicitura "PAGAMENTO EFFETTUATO" nel campo pagamento e nascondere le scadenze in fattura

## Comportamento attuale

Allo stato attuale, anche se ho registrato il pagamento in prima nota, in fattura compare sempre il pagamento originario e le relative scadenze.

**Comment by Dasc3er** [comment]
Le relative scadenze sono però segnate come pagate.

**Comment by idraulicadueci** [comment]
Però non viene evidenziato nella copia di cortesia che si invia al cliente.

**Comment by Dasc3er** [comment]
Per copia di cortesia intendi oa stampa?

**Comment by idraulicadueci** [comment]
Esatto. È la copia che viene inviata a chi non ha codice di interscambio (condominio, persone fisiche, ecc.)
