### ISSUE TITLE
Errore vista Gestione Documentale e Liste newsletter

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#696]
## Comportamento attuale

Le viste non vengono caricate e la richiesta POST dà la seguente risposta:
`SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id'`

## Passi per riprodurre il comportamento

1. Aggiornare a 2.4.11
2. Andare su **Gestione documentale** o **Gestione Email --> Liste**
3.

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: **Gestione documentale**, **Gestione Email/Liste**
* Versione del progetto: 2.4.11
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
@maicol07 Il ptoblema non si verifica con un aggiornamento alla versione 2.4.11 rilasciata.
Sei sicuro di non avere una versione "sporca" con modifiche intermedie?

**Comment by maicol07** [comment]
Possibile, ho integrato le modifiche locali della versione precedente, ma non riguardano quei moduli

**Comment by Dasc3er** [comment]
Potrebbero però essere state eseguite delle query che riguardano proprio quei moduli, e che quindi ora infulenzano i risultati del gestionale. Potresti provare a controllare manualmente i contenuti delle query tramite il modulo Viste o direttamente da database?

**Comment by maicol07** [comment]
Gestione documentale:
```
SELECT * FROM `do_documenti`
INNER JOIN `do_categorie` ON `do_categorie`.`id` = `do_documenti`.`idcategoria`
WHERE 1=1 AND `deleted_at` IS NULL AND
     (SELECT `idgruppo` FROM `zz_users` WHERE `zz_users`.`id` = '1') IN (SELECT `id_gruppo` FROM `do_permessi` WHERE `id_categoria` = `do_documenti`.`idcategoria`)
     AND (`data` BETWEEN '2019-01-01' AND '2019-12-31')
HAVING 2=2
```

Liste:

`SELECT * FROM `em_lists` WHERE deleted_at IS NULL AND 1=1 HAVING 2=2`

**Comment by Dasc3er** [comment]
Queste query non generano errore, ma non sembrano quelle generate in automatico... Potresti includere quelle del riquadro **Query risultante**?

**Comment by maicol07** [comment]
Sono quelle

**Comment by Dasc3er** [comment]
Allora sono più che certo non si tratti della versione definitiva dei moduli.
Se vuoi correggerle a database:
https://github.com/devcode-it/openstamanager/blob/cc3d7ca954fe3067c05d2c75dacde730b144b462/update/2_4_11.sql#L676
https://github.com/devcode-it/openstamanager/blob/cc3d7ca954fe3067c05d2c75dacde730b144b462/update/2_4_11.sql#L706
Inoltre controlla che ci siano le singole colonne previste nelle query successive per entrambi i moduli.

**Comment by maicol07** [comment]
Sono identiche nel database

**Comment by Dasc3er** [comment]
Quindi mancano le singole colonne nella tabella zz_views. Puoi trovare tutto nelle righe successive.

**Comment by maicol07** [comment]
Le colonne ci sono:
![immagine](https://user-images.githubusercontent.com/9463142/70175098-5ac69e80-16d6-11ea-8f69-16536c05bf71.png)

**Comment by Dasc3er** [comment]
Ma probabilmente non i permessi per i gruppi.

**Comment by maicol07** [comment]
Nella tabella `do_permessi` non sono presenti dati e non vedo query nel file sql della versione 2.4.11 che li inseriscano. Ho risolto aggiungendo i dati manualmente e impostando nelle viste i gruppi di accesso per i moduli **Gestione documentale** e **Categorie documenti**

**Comment by Dasc3er** [comment]
No, intendo i permessi per le viste: ogni colonna delle tabelle principali deve essere inserita in una whitelist per gruppo nella tabella zz_group_view.
