### ISSUE TITLE
(Miglioria) Aggiunta permessi di default durante la creazione dei gruppi di utenti

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#697]
Per qualche motivo mi esce un errore di datatables. Questa è la richiesta ajax per il modulo dei ddt:

`/ajax_dataload.php?id_module=27&id_plugin=&id_parent=&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=false&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=160&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1575469293232`

Con risultato:
```
{"error":{"type":"PDOException","message":"SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id'","file":"\/home\/user\/web\/osm\/src\/Database.php","line":239}}
```
Entrando invece come amministratore la stessa richiesta diventa la seguente, e non provoca errori.

`
/ajax_dataload.php?id_module=27&id_plugin=&id_parent=&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=false&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=9&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=10&columns%5B10%5D%5Bname%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=160&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1575469363636
`

**Comment by Dasc3er** [comment]
Che tipologia di utente, che versione di OpenSTAManager e che modulo?

**Comment by beppe9000** [comment]
Dopo un'analisi più approfondita ho determinato che il problema è causato dal fatto che quando viene creato un nuovo gruppo utenti non viene assegnato alcun permesso per le viste preesistenti.

Ho risolto così:
```
INSERT IGNORE INTO `zz_group_view` (`id_gruppo`, `id_vista`, `created_at`, `updated_at`)
SELECT '6', `id_vista`, now(), now() -- 6 è l'id del gruppo utenti
FROM `zz_group_view`
WHERE `id_gruppo` = '1';
```

Probabilmente sarebbe il caso di gestire questo ti po di evenienza da lato client con un messaggio relativo ai permessi delle viste.

Da lato server invece si potrebbe chiedere se copiare i permessi da un altro gruppo in fase di creazione.

<hr>
```
SELECT *
FROM `zz_views`
WHERE `id` IN    ( SELECT id_vista FROM `zz_group_view` WHERE `id_gruppo` = '1' AND id_vista NOT IN ( SELECT id_vista FROM `zz_group_view` WHERE `id_gruppo` = '2') ) AND `visible` = '1'
```
Con questa query ho visto che ci sono alcune viste che sono assegnate solo agli amministratori e non ai tecnici:

|     |           |        |         |       |        |      |        |               |          |         |          |         |                     |                     | 
|-----|-----------|--------|---------|-------|--------|------|--------|---------------|----------|---------|----------|---------|---------------------|---------------------| 
| id  | id_module | name   | query   | order | search | slow | format | search_inside | order_by | visible | summable | default | created_at          | updated_at          | 
| 138 | 39        | Nome   | sezione | 2     | 1      | 0    | 0      |               |          | 1       | 0        | 1       | 2019-11-29 11:30:40 | 2019-11-29 11:30:40 | 
| 141 | 38        | Gruppo | nome    | 1     | 1      | 0    | 0      |               |          | 1       | 0        | 1       | 2019-11-29 11:30:40 | 2019-11-29 11:30:40 | 
| 142 | 37        | Numero | id      | 1     | 1      | 0    | 0      |               |          | 1       | 0        | 1       | 2019-11-29 11:30:40 | 2019-11-29 11:30:40 | 
| 143 | 37        | Icona  | icon    | 4     | 1      | 0    | 0      |               |          | 1       | 0        | 1       | 2019-11-29 11:30:40 | 2019-11-29 11:30:40 | 
| 144 | 37        | Nome   | title   | 3     | 1      | 0    | 0      |               |          | 1       | 0        | 1       | 2019-11-29 11:30:40 | 2019-11-29 11:30:40 | 

Detto ciò mi rimane solo il dubbio di aver assegnato troppi permessi...

**Comment by Dasc3er** [comment]
@beppe9000 Se aggiungi i permessi di accesso ad un modulo al nuovo gruppo tutte le viste relative dovrebbere essere rese accessibili.

**Comment by beppe9000** [comment]
ok, il gruppo era stato importato via sql senza importare i permessi delle viste.

Ps. Alcuni programmi hanno una procedura on-demand che verifica la consistenza del db. Dal momento che i permessi su osm dipendono da due tabelle potrebbe avere senso permettere di fare un controllo di coerenza da un eventuale modulo dedicato alle operazioni avanzate.
