### ISSUE TITLE
Importare magazzino prodotti

### ISSUE THREAD

**Issue by Denisov21** [devcode-it/openstamanager#70]

**Comment by Denisov21** [comment]
Ciao, mi piacerebbe molto poter importare file cvs nel magazzino! Che cosa ne pensate?

**Comment by fpsoftware** [comment]
Ciao @Denisov21 in questo periodo ci stiamo concentrando sulla risoluzione dei bug per poter rilasciare una versione stabile del programma, quindi nuove procedure restano in sospeso. 
Se interessato abbiamo già sviluppato le procedure per importare da csv clienti/fornitori/articoli, ad oggi le usiamo con clienti che acquistano un piano di assistenza e/o personalizzazioni, non abbiamo ancora deciso se rilasciare queste procedure nella versione base gratuita del software.
Maggiori informazioni qui [OpenSTAManager software gestionale](http://www.openstamanager.com/per-le-aziende/)

**Comment by loviuz** [comment]
Da sviluppare più avanti un import generico, magari nella 2.5

**Comment by Dasc3er** [comment]
@Denisov21  Dalla versione 2.4 è disponibile un modulo generico per l'importazione dei CSV.
Eventualmente potresti personalizzare la struttura a tuo piacimento attraverso il file **import.php** del modulo Articoli.

**Comment by Denisov21** [comment]
@Dasc3er Grazie mille
