### ISSUE TITLE
BUG: non vengono salvate le scadenze

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#700]
## Comportamento attuale

Quando viene creata una scadenza dal tasto "+" nel modulo Scadenzario non viene salvata.

## Passi per riprodurre il comportamento

1. ![image](https://user-images.githubusercontent.com/6625123/70344652-78bd0c00-185a-11ea-9876-7a2d88718a43.png)

2. ![image](https://user-images.githubusercontent.com/6625123/70344637-6fcc3a80-185a-11ea-812c-9d3320c745fb.png)

3. OSM comunica erroneamente la creazione della scadenza.

## Contesto

* Modulo: scadenzario
* Versione del progetto: 2.4.10
* Versione PHP: 7.3
* Tipo di server: Centos7

**Comment by beppe9000** [comment]
Immagino che l'esecuzione sia terminata prima di arrivare al commit del database.

**Comment by Dasc3er** [comment]
La versione 2.4.11 risolve il problema.

**Comment by beppe9000** [comment]
Avevo anche cercato 🤦‍... potresti linkarmi la segnalazione originale e il commit in cui viene risolto il problema? Vorrei applicare il fix alla 2.4.10 finchè non la aggiorno. Grazie

**Comment by Dasc3er** [comment]
Nessun problema, in effetti il problema era stato descritto in modo tecnico: #669

**Comment by beppe9000** [comment]
Grazie

**Comment by Dasc3er** [comment]
Grazie a te! Meglio un bug segnalato più volte che uno non segnalato :smile:
