### ISSUE TITLE
(Domanda) I tab 'Monolog' e 'Timeline' di Debug Bar sono vuoti

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#702]
È normale? In caso contrario come si risolve?

**Comment by Dasc3er** [comment]
È normale.
Per il momento Monolog viene utilizzato solo per il log errori, anche se in futuro può essere uno strumento utile per il debug.
Il settore timeline non viene utilizzato.

**Comment by beppe9000** [comment]
ok
