### ISSUE TITLE
File rimanenti dopo update ?

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#704]
Ho notato che sul server è presente il file `modules\stato_servizi\api\retrieve.php` che non è nel pacchetto di release con cui ho aggiornato da 2.4.10 a 2.4.11. 

Non andrebbe eliminato durante l'aggiornamento ?

**Comment by beppe9000** [comment]
Nel dubbio ho provveduto ad eliminare manualmente i file nell'array.

https://github.com/devcode-it/openstamanager/blob/4823258f75522c5876f1b8632d893a2e51fc6230/update/2_4_11.php#L61-L85

**Comment by Dasc3er** [comment]
È possibile che per un problema di permessi l'eliminazione dei file non vada sempre a buon fine.
Purtroppo non abbiamo altro modo per procedere.

**Comment by beppe9000** [comment]
Questa funzione si ferma al primo file eliminato.
https://github.com/devcode-it/openstamanager/blob/4823258f75522c5876f1b8632d893a2e51fc6230/lib/functions.php#L52-L65

Ho visto che nella procedura di aggiornamento non viene utilizzato il risultato della funzione... 

Penso sia il caso di avvertire l'utente quantomeno. -_-

```
    if (!delete($files)) {
        $rimanenti = [];
        foreach ($files as $file) {
            if (file_exists($file)) {
                if (!delete($file)) $rimanenti[] = $file;
            }
        }
        if (count($rimanenti) != 0) {
            // notificare l'utente in qualche modo
        }
    }
```

Non basta fare così?
