### ISSUE TITLE
(Miglioria) Rilevare file modificati utilizzando il checksum

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#705]
Nella schermata di aggiornamento suggerirei di elencare tutti i file personalizzati o modificati (quindi anche fuori dalle cartelle custom) utilizzando una lista di hash (nel formato `percorso:hash;\n` ad esempio, di facile creazione con uno script) inclusa nella release.

Sarebbe un ottimo strumento per poter avere un quadro generale, controllare e risolvere eventuali conflitti in fase di aggiornamento. È anche un modo per verificare l'integrità strutturale dei file del progetto ad esempio rilevando anche eventuali file eliminati o non previsti.

Per alleggerire il carico della pagina si potrebbe caricare su richiesta con un bottone ajax.

<hr>

Un passo in più potrebbe essere di aggiungere un indicatore per segnalare se l'originale del file che è stato modificato è diverso nell'ultima release ( ⚠️ ) oppure se è rimasto invariato ( ✔️ ).

**Comment by Dasc3er** [comment]
Il lavoro di implementazione corretta sarebbe piuttosto complesso a livello di release...
Per la versione "future" è in previsione la gestione dell'aggiornamento tramite trasferimento di tutti i file del gestionale in una sottocartella, per poi replicare esclusivamente la cartella files e poche altre all'interno del percorso originale. La questione è ancora da considerarsi approfonditamente.

**Comment by beppe9000** [comment]
> Il lavoro di implementazione corretta sarebbe piuttosto complesso a livello di release...

C'è qualche punto in particolare che è particolarmente complesso?

> Per la versione "future" è in previsione la gestione dell'aggiornamento tramite trasferimento di tutti i file del gestionale in una sottocartella, per poi replicare esclusivamente la cartella files e poche altre all'interno del percorso originale. La questione è ancora da considerarsi approfonditamente.

Qusta procedura darà sicuramente problemi a chi come me ha altre sotto cartelle nella cartella di osm...

**Comment by Dasc3er** [comment]
Il problema sarebbe che è necessario completare una lista di file con relativi checksum per permettere la verifica a livello generale. L'alternativa sarebbe di fare un controllo prima di rimuovere la cartella tmp che contiene lo zip di aggiornamento, ma ciò non sarebbe rapido e non funzionerebbe dove il caricamento zip non è possibile.

**Comment by beppe9000** [comment]
Questa potrebbe essere una buona base di partenza...

```php
<?php

        // Creazione
        $chk = '';
        $target = __DIR__;
        $old_dir = getcwd();
        chdir($target);
        foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator('.')) as $path => $file) {
            if ($file->isDir()) continue;
            $path = str_replace('\\', '/', $path);
            $sh1 = sha1_file($path);
            $chk .= "$sh1\t$path\n";
        }
        file_put_contents('checksum.bin', $chk);
        chdir($old_dir);

    // Verifica
    $checksum_file = __DIR__ . '/checksum.bin';
    $old_dir = getcwd();
    chdir(dirname($checksum_file));
    foreach (explode("\n", trim(file_get_contents($checksum_file))) as $file) {
        list($hash, $path) = explode("\t", $file, 2);
        if (($hash !== sha1_file($path))) {
            echo "[MODIFICATO] $path\n";
        } else {
            //echo "[OK] $path\n";
        }
    }
    chdir($old_dir);

```

**Comment by Dasc3er** [comment]
Il problema non è il codice, quanto la logica da implementare e il modo in cui garantire il funzionamento. 
@lucasalva87 sarebbe sensato fare un pulsante a parte che effettui i controlli di integrità, oppure una task in background? Altre idee?

**Comment by lucasalva87** [comment]
La funzionalità sarebbe utile sia per rilevare file modificati, sia per file non correttamente aggiornarti durante l'update; magari per problemi di scrittura. Il controllo potrebbe essere quindi eseguito al termine di un update ma anche tramite apposito pulsante in stato del sistema. Oppure pensare ad un nuovo modulo nascosto "Avanzate" dove raccogliere funzioni tipo questa o un pulsante per eseguire il reset dei dati nel gestionale ecc..

**Comment by Dasc3er** [comment]
Idealmente quindi:
- Introduzione di un pacchetto per il checksum dei file
https://www.npmjs.com/package/checksum
- Durante la release aggiungere nel glob per lo zip un checksum e salva in un file JSON i dato di tutti i file individuati
- Aggiungere un controllo a livello PHP tramite pulsante apposto nella sezione aggiornamenti, e un impostazione per eseguire il controllo in automatico a seguito di un aggiornamento

**Comment by beppe9000** [comment]
Ricordo anche di controllare file aggiunti oltre che quelli eliminati

<hr>

Altri spunti...
 
> Un passo in più potrebbe essere di aggiungere un indicatore per segnalare se l'originale del file che è stato modificato è diverso nell'ultima release ( ⚠️ ) oppure se è rimasto invariato ( ✔️ ).

```php

$url = 'https://github.com/devcode-it/openstamanager/releases/download/v2.4.12/openstamanager-2.4.11.zip';
$zipContent = file_get_contents($url);
$fp = tmpfile();
fwrite($fp, $zipContent);
$stream = stream_get_meta_data($fp);
$filename = $stream['uri'];
$zip = new ZipArchive();
if ($zip->open($filename)) {
    $checksumFile = $zip->getFromName("checksum.json");
    $zip->close();
    fclose($fp);
}

$checksumFile; // checksum della nuova versione 

```

**Comment by Dasc3er** [comment]
@beppe9000 La funzionalità è appena stata integrata nella branch master, e sarà quindi disponibile a partire dalla prossima versione.

Opzione di verifica nel modulo **Aggiornamenti**:
![image](https://user-images.githubusercontent.com/15911489/89187164-32f94480-d59d-11ea-81f4-2509f1c302d7.png)

Modal di verifica dei contenuti:
![image](https://user-images.githubusercontent.com/15911489/89187122-1e1cb100-d59d-11ea-8cdd-8f06fdd6e36a.png)

Se hai ulteriori suggerimenti sui controlli da effettuare oppure anche sulla grafica, sono i benvenuti :smile:

**Comment by beppe9000** [comment]
tutto buono! questo è un grosso passo avanti per poter tenere traccia delle proprie modifiche.

mancherebbe magari l'individuazione di tutti i file custom e la verifica dei cambiamenti dell'originale rispetto alla release più aggiornata che a questo punto potrebbe essere più afferente alla funzione di verifica degli aggiornamenti (dal momento che richiede il file checksum.json della versione successiva) quindi si potrebbe spostare su un nuovo issue a meno dilasciare aperto questo, a cui si fa riferimento per questa funzione specifica in #795

**Comment by Dasc3er** [comment]
@beppe9000 Per quanto riguarda l'individuazione dei file modificati, se si utilizza lo standard di mettere le modifiche nella cartella custom/ esiste già un avviso nel modulo **Aggiornamenti** che segnala i moduli personalizzati e anche le tabelle aggiuntive non registrate del database.

**Comment by beppe9000** [comment]
mi riferivo allo "livello sucessivo", ovvero verificare se gli originali dei file modificati tramite cartelle `/custom` siano invariati o meno rispetto alla versione più recente rilevata

**Comment by Dasc3er** [comment]
Le cartelle custom/ non vengono mai utilizzate per la versione di base del gestionale, e quindi non avrebbe senso applicare il controllo in relazione all'aggiornamento.

Inoltre, le modifiche alle cartelle custom/ dovrebbero in generale essere applicate manualmente, per cui l'utente si accorge di eventuali problemi con il salvataggio del file.
Infine, per verificare le modifiche a file non originalmente presenti, sarebbe necessario: un sistema in background che effettua in modo ricorrente la generazione del checksum e la relativa verifica, oppure un pulsante per permettere la generazione manuale di tutti i checksum dei file relativi.

Non vedo in ogni caso l'utilità effettiva dell'estensione della funzionalità, potresti indicare un caso d'uso?
Altrimenti dubito che questa verifica verrà mai implementata, considerando che la funzionalità di checksum è utile per verificare che tutti i file vengano correttamente aggiornati con l'installazione di una nuova versione.

**Comment by Dasc3er** [comment]
Può essere utile prevedere di estendere la funzionalità per i moduli aggiuntivi installabili bel gestionale.

**Comment by beppe9000** [comment]
> Non vedo in ogni caso l'utilità effettiva dell'estensione della funzionalità, potresti indicare un caso d'uso?

È utile nella manutenzione di personalizzazioni: verrebbe segnalato l'aggiornamento dei file precedentemente personalizzati.

> Infine, per verificare le modifiche a file non originalmente presenti, sarebbe necessario: un sistema in background che effettua in modo ricorrente la generazione del checksum e la relativa verifica, oppure un pulsante per permettere la generazione manuale di tutti i checksum dei file relativi

In effetti questo non è proprio ideale...

<hr>Ma voi come gestite l'aggiornamento delle installazioni con personalizzazioni su osm cloud?

**Comment by loviuz** [comment]
> mi riferivo allo "livello sucessivo", ovvero verificare se gli originali dei file modificati tramite cartelle /custom siano invariati o meno rispetto alla versione più recente rilevata

@beppe9000 se non ho capito male intendi fare un confronto se ad esempio un file actions.php è uguale a custom/actions.php?

**Comment by beppe9000** [comment]
Quello che intendevo è:

Se esiste `custom/actions.php`, si confronta `actions.php` con `actions.php` della versione successiva.
Se sono uguali non è ragionevole presumere che non sia necessario l'aggiornamento di `custom/actions.php`.
Se sono diversi allora si segnala la differenza nell'interfaccia perchè è cambiato il file usato come base della personalizzazione.
