### ISSUE TITLE
(Miglioria UX) Area di click per checkbox

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#706]
Per un'interfaccia più pratica suggerirei di implementare lo stesso comportamento della label anche per l'area del placeholder delle checkbox e quella intorno all'elemento della spunta. 

![image](https://i.imgur.com/U5EfySI.gif)

Si potrebbe trarre _spunto_ da bootstrap:
![image](https://i.imgur.com/zOLq8No.gif)

Rimarrebbe da capire come collocare i suggerimenti. Probabilmente un tooltip ha senso.

**Comment by Dasc3er** [comment]
@beppe9000 Con l'ultimo commit dovrei aver aggiornato le checkbox, risolvendo il problema che in effetti c'era da tempo nell'usabilità del componente.
