### ISSUE TITLE
BUG articoli con serial number attivo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#707]
## Comportamento attuale

Se l'articolo, di cui è richiesto il serial number, viene importato in fattura da un preventivo o un ordine, non viene visualizzato sulla riga il pulsante per l'inserimento del valore, ne' la dicitura "X serial number mancante"

OSM 2.4.11

**Comment by Dasc3er** [comment]
@idraulicadueci Ho appena testato e funziona tutto correttamente.
Da Ordine inserisco un articolo e seleziono i seriali, nell'importazione diretta in Fattura vengono fatti selezionare i seriali relativi e la visualizzazione è corretta.

**Comment by idraulicadueci** [comment]
ok. Ho testato anch'io e funziona correttamente. Potrebbe dipendere dal fatto che il preventivo che mi ha dato il bug era stato inserito con laversione precedente e abbia dato questo problema?

**Comment by Dasc3er** [comment]
Potrebbe essere... Ma al momento non mi sembra sia possibile inserire i seriali nei preventivi, anche se potrei sbagliarmi.
