### ISSUE TITLE
Aggiunta articoli senza codice fallisce

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#708]
## Comportamento richiesto

Aggiungendo un articolo senza indicare il codice, lo stesso viene generato.

## Comportamento attuale

Aggiungendo un articolo senza codice viene generato un errore come da screen allegato
![screencapture-ryritalia-it-openstamanager-controller-php-2019-12-12-16_53_53](https://user-images.githubusercontent.com/392762/70727855-b3162580-1d00-11ea-8d50-629f6ab0e5c5.png)

## Possibile soluzione

Non viene generato il codice prima di procedere alla insert

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Articoli, nuovo articolo
2. Riempire tutti i campi eccetto Codice articolo
3. Cliccare su salva

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Magazzino
* Versione del progetto: 2.4.11
* Versione PHP: 7
* Tipo di server: Apache 2

**Comment by Dasc3er** [comment]
Il codice è un campo obbligatorio, come hai fatto a evitare di inserirlo?

**Comment by marcus905** [comment]
![Screenshot_20191212-204954_Chrome](https://user-images.githubusercontent.com/392762/70743942-0d26e300-1d21-11ea-8855-eca68a45fd0e.jpg)
Non risulta obbligatorio, anzi col tooltip col punto interrogativo dice che se non indicato viene generato.

Sto sbagliando qualcosa?

**Comment by marcus905** [comment]
In tutto ciò, nell'import XML della fattura ricevuta, l'aggiunta articolo non funziona proprio ne con ne senza codice. Fallisce anche l'aggiunta della categoria/sottocategoria. Apro un altra issue?

**Comment by Dasc3er** [comment]
Non serve aprire un'altra issue, ma apparentemente non sono aggiornato su questo nuovo funzionamento. @lucasalva87
