### ISSUE TITLE
Magazzino - articoli: quantità totale

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#709]
Grazie in anticipo!!

## Comportamento richiesto

Mi aspetterei che nella scheda articoli, a seguito di un "ritorna al magazzino" di una certa quantità di un articolo precedentemente inserito in un intervento, la quantità visualizzata fosse quella che invece viene mostrata in quantità totale da movimenti. 

## Comportamento attuale

Attualmente se ho 100 pezzi e ne inserisco 10 in un intervento giustamente la scheda articoli mi mostra 90 ma se clicco su "ritorna in magazzino" da scheda intervento dello stesso articolo non ritorna a 100. Resta 90.

## Possibile soluzione

query diversa?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by antoniotrapasso** [comment]
Ciao Dasc3er!
la lable bug significa che un baco del sw?
Come verrà risolto?

grazie mille ciao

**Comment by Dasc3er** [comment]
Ciao, il label bug indica un malfunzionamento da risolvere di dimensione ridotta (che non stravolge il codice). Devo confermare il problema, e poi cercheremo di risolverlo.

**Comment by antoniotrapasso** [comment]
Se non ho capito male il problema sta nella query in moduli/interventi/action.php che ti riporto qui di seguito: 
$q = 'SELECT qta, idarticolo, idimpianto FROM mg_articoli_interventi WHERE id='.prepare($idriga);

Se potessi ricevere quella giusta potrei intanto testarla nel mio ambiente.

grazie

**Comment by Dasc3er** [comment]
Il problema non è quella query. Questo pomeriggio dovrei riuscire a dare un'occhiata.

**Comment by antoniotrapasso** [comment]
Grazie. Allora attendo un tuo gentile riscontro. Grazie ancora !!

**Comment by Dasc3er** [comment]
@antonioscarpino Stai utilizzando la versione 2.4.11?
Perchè non esiste più un pulsante "Ritorna a magazzino", ma solo uno generico "Elimina riga" che prevede il comportamente giusto.

**Comment by antoniotrapasso** [comment]
uso la 2.4.10!

**Comment by antoniotrapasso** [comment]
Ho fatto altre modifiche, come faccio a fare upgrade senza stravolgere le modifiche fatte? grazie

**Comment by antoniotrapasso** [comment]
Da dove scarico la versione superiore alla 2.4.11?

**Comment by beppe9000** [comment]
> Ho fatto altre modifiche, come faccio a fare upgrade senza stravolgere le modifiche fatte? grazie

se hai fatto le modifiche nelle varie cartele /custom dovresti riuscire a fare l'aggiornamento regolarmente e successivamente aggiornare le personalizzazioni basandole sulla nuova versione del file originale

> Da dove scarico la versione superiore alla 2.4.11?

**Comment by Dasc3er** [comment]
No, la release è scaricabile da https://github.com/devcode-it/openstamanager/releases/tag/v2.4.11

**Comment by beppe9000** [comment]
> No, la release è scaricabile da https://github.com/devcode-it/openstamanager/releases/tag/v2.4.11

"superiore alla 2.4.11"

**Comment by Dasc3er** [comment]
La versione superiore alla 2.4.11 non esiste, e soprattutto il branch future è dedicato alle modifiche sperimentali a lungo termine.
Per sovrascrivere le modifiche è necessario cancellare o aggiornare di conseguenza i contenuti della cartella custom/ modificata, se invece le modifiche sono nei file principali è necessario ripristinarli dalla release.

Se vuoi aggiornare alla 2.4.12 **in modo non ufficiale** puoi replicare la branch master, ma non lo consiglio perché dovrai dopo replicare le ulteriori modifiche manualmente.

**Comment by antoniotrapasso** [comment]
Se invece voglio introdurre solo la correzione relativa al ritorna in magazzino (o elimina riga della nuova versione) come faccio? per ora mi basterebbe quello. Basterebbe sostituire il modulo? quale?

grazie mille

**Comment by Dasc3er** [comment]
Dovresti già averla se hai una 2.4.11, altrimenti basta aggiornare o sostituire tutti i file. In alternativa devi controllare manualmente il codice.
