### ISSUE TITLE
Su "Sconto incondizionato" in preventivi viene sempre applicato "Iva predefinita"

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#71]
Su "Sconto incondizionato" in preventivi viene sempre applicato "Iva predefinita" dalle impostazioni fatturazione. Sarebbe opportuno applicare l'iva corretta impostata per il cliente in questione.

Presumo che anche in altri moduli l'errore sia presente visto che l'errore si trova nella funzione "aggiorna_sconto" in modules/fatture/modutil.php .

**Comment by lepool** [comment]
Non ho capito a che serve il parametro $options nella funzione "aggiorna_sconto". Si potrebbe dare alla funzione l'idiva corretto e se non viene passato alcun argomento allora uso l'iva apredefinita.

**Comment by Dasc3er** [comment]
Il parametro $options era stato introdotto per prevedere casi particolari relativi al singolo documento, per favorire la futura estensibilità del sistema degli sconti.
Se la modifica è generica, come quella proposta in questo caso, basterebbe impostare correttamente il comportamento generale.

@fpsoftware @lucasalva87 @loviuz Questa modifica sarebbe corretta nel confronto degli sconti?
Perché per il momento negli sconti incondizionati non è possibile modificare l'iva manualmente...

**Comment by lepool** [comment]
Un idea sarebbe di salvare l'idiva in ogni elemento in co_documenti. In questa maniera i singoli documenti possono essere gestiti indipendentemente. Quando creo un documento mi prende l'idiva cliente come default e se questo non è settato mi prende il default dalle impostazioni generali fatture. Al utente si potrebbe indicare tramite  un avviso l'incongruenza fra l'idiva dell' documento attualmente aperto e quello impostato per il cliente (potrebbe essere voluto).

**Comment by Dasc3er** [comment]
Questo comportamento è già impostato di default, l'unica parte esente è lo sconto incondizionato, dove per il momento viene sempre usata l'IVA predefinita...

**Comment by loviuz** [comment]
l'iva nell'attività serve solo per avere un'anteprima del costo finale, non è un calcolo definitivo, però se venisse presa quella del cliente e, se assentez quella predefinita, l'anteprima sarebbe più corretta

**Comment by lepool** [comment]
Ma secondo la logica attuale l'idiva impostato nell'anagrafica non viene mai considerata per l'inserimento degli articoli. Sulle righe generiche in qualche modulo ci sono ancora piccoli errori per quanto riguarda l'iva.
Ma come dice @loviuz ,è un modo di vedere le cose.

**Comment by loviuz** [comment]
Ho riletto le osservazioni di @lepool e non so se intendeva sollevare un problema che ho riscontrato solo ora: se ho un preventivo (ma anche fatture, contratti, ecc) con queste righe:
riga a 100€ + 22%
riga a 100€, esente iva

Il riepilogo è:
`imponibile: 200€`
`iva: 22€`
`totale: 222€`

Se applico uno sconto incondizionato del 10%, viene calcolato uno sconto di 20€ (giusto) e viene scontata anche l'iva di 4,4€ (il 10% dell'iva del documento).

Il riepilogo è:
`imponibile: 200€`
`imponibile scontato: 180€`
`iva: 17,60€`
`totale: 197,60€`

Se dal prezzo finale ivato. quindi 222€, togliessi il 10%, avrei 199,80€.

**DOMANDA**
Quale delle 2 versioni è corretta? Oppure: una delle 2 è sbagliata, o sono solo versioni diverse di fare i conti e quindi entrambe uguali?
E' più una domanda da finanziere che da programmatore :-)

**Comment by lepool** [comment]
http://www.marchegianionline.net/appro/appro_990.htm 
Forse ti è d'aiuto.  


[0000004789.pdf](https://github.com/devcode-it/openstamanager/files/1692080/0000004789.pdf)

**Comment by loviuz** [comment]
Ho corretto il calcolo dello sconto globale in percentuale nei casi di più aliquote iva. Rispetto all'esempio sopra, la versione corretta è questa:
![immagine](https://user-images.githubusercontent.com/1647128/36307213-72ecbc26-131b-11e8-9ddf-b043b49b6b8f.png)

Rimarrebbe il problema dello sconto globale in euro che quasi quasi vorrei togliere, perché quello si che è un bel problema, nel senso che se ci sono più aliquote iva non so come far tornare i conti dell'iva. Quasi quasi terrei solo lo sconto percentuale come sconto globale. Se c'è uno sconto in euro da fare, si dovrà fare solo nelle righe.

**Comment by lucasalva87** [comment]
In questo casò però non è corretto visualizzare "Iva 22%" sotto l'importo dello sconto 3,20 € in quanto in realtà l'iva applicata è dello 16% ovvero la media tra 22% e 10%. Idem per la stampa. Propongo 2 possibili soluzioni:

- Far scegliere in fase di definizione dello sconto anche l'iva da applicare
- Inserire gli sconti lordi quindi già con eventuale aliquota iva applicata

**Comment by Dasc3er** [comment]
Con il nuovo sistema degli sconti in uscita nella versione 2.4.9, gli sconti vengono gestiti come semplici righe. Pertanto, per ognuna deve essere indicata l'IVA da applicare.
![immagine](https://user-images.githubusercontent.com/15911489/55574058-4e5df200-56c0-11e9-9790-6b207f66e6ea.png)

Per il momento, puoi controllare la seguente issue per eventuali problemi di retrocompatibilità: #542
