### ISSUE TITLE
[BUG] Partita iva non valida in fase di creazione dell'anagrafica

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#711]
## Comportamento attuale

In `\Validate::isValidVatNumber` non viene impostato ` $result['valid-format'] = true;` se il codice di controllo della partita iva è valido ma `\API\Services::isEnabled` è `false`. Questo implica che l'interfaccia delle anagrafiche mi dia ogni partita iva come non valida.

## Possibile soluzione

cambiare
```PHP
        if (empty($vat_number)) {
            $result['valid-format'] = true;
        }
```

in 

```PHP
       $result['valid-format'] = true;
```

<hr>

Sarebbe anche opportuno disattivare i messaggi di errore riguardo l'origine della partita iva /mail/altro quando non si usa l'api. Ad esempio in validation.php delle anagrafiche si può fare così:

```PHP
if (\API\Services::isEnabled()) {
    if (empty($check['valid'])) {
        $result = false;
        $errors[] = tr("Impossibile verificare l'origine della partita iva");
    }
}
```

**Comment by Dasc3er** [comment]
Il problema è già stato risolto poiché segnalato nel forum. Grazie in ogni caso per la issue.

**Comment by beppe9000** [comment]
No problem. Puoi linkare il thread? Grazie

**Comment by Dasc3er** [comment]
https://forum.openstamanager.com/viewtopic.php?f=10&t=95079&p=103053&hilit=Partita+Iva#p103053
