### ISSUE TITLE
Problema di login

### ISSUE THREAD

**Issue by crisassistenza** [devcode-it/openstamanager#712]
Non so se capita solo a me, ma dopo l'aggiornamento alla versione 2.4.11 non riesco più a loggarmi con le credenziali che utilizzavo prima.

Ho provato le seguenti cose:
- procedura per il recupero della password -> non ho ricevuto alcuna mail
- eseguito comando "SQL UPDATE `zz_users` SET `password` = MD5('nuova_password') WHERE `username` = 'admin';" -> il login continua a non funzionare
- inserito token direttamente nel database e fatto un reset password senza aver ricevuto la mail -> il software conferma di aver modificato la password ma non funziona il login.

L'unico modo che ho trovato per accedere è bypassare i controlli di sicurezza modificando la function password_check affinché restituisca "true" sempre e comunque.

**Comment by Dasc3er** [comment]
Ciao, potresti condividere le informazioni sul server? Versione PHP, ...?

**Comment by crisassistenza** [comment]
Ciao, sono riuscito  risolvere tutti i problemi, condivido quanto successo in modo che possa essere d'aiuto anche ad altri.

Ho notato che non mi permetteva neanche l'inserimento di documenti, anagrafiche, ecc.. Ho pensato quindi ad un problema col metodo POST e mi è venuto in mente che l'unica cosa che avevo modificato è l'aggiunta dei parametri
`upload_max_filesize = 32MB`
`post_max_size = 32MB`
al file php.ini (come suggerito dal gestionale nella sezione aggiornamenti).

Ho tolto quei parametri e si è risolto tutto.
Grazie
