### ISSUE TITLE
English Language

### ISSUE THREAD

**Issue by GaneshKandu** [devcode-it/openstamanager#717]
Hi,

How can i install ``OpenSTAManager`` with default  English language ?

**Comment by Dasc3er** [comment]
Hi, during the configuration process at the beginning you should be able to select the language for the software (version >= 2.4.11). After that, the language is store in the variable `$lang` inside the `config.inc.php`.

The translation is currently being worked on, so it may be a bit off on the correct terms, and you should be advised that the software is defined to work with the Italian regulations (for example, the Italian Electronic Bill system).

For any questions you may have we'll try our best to answer, and if you are interested in contributing you are more than welcome!

**Comment by GaneshKandu** [comment]
Language is stored in the variable ``$lang`` inside the config.inc.php is ``en_GB``
```php
// Personalizzazione dei gestori dei tag personalizzati
$HTMLWrapper = null;
$HTMLHandlers = [];
$HTMLManagers = [];

// Lingua del progetto (per la traduzione e la conversione numerica)
$lang = 'en_GB';
//$lang = 'it_IT';
// Personalizzazione della formattazione di timestamp, date e orari
$formatter = [
    'timestamp' => 'd/m/Y H:i',
    'date' => 'd/m/Y',
    'time' => 'H:i',
    'number' => [
        'decimals' => ',',
        'thousands' => '',
    ],
];
```
English language is not completely translated
