### ISSUE TITLE
Aggiunta campo impianto su attività in dashboard

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#718]
## Comportamento richiesto

Ciao a tutti! mi servirebbe aggiungere l'impianto da lavorare (utile per i clienti per i quali abbiamo piu impianti) sull'attività della dashboard. Ho aggiunto altri campi facilmente in quanto campi delle tabelle incluse nella query già esistente ma questa prevederebbe delle join. come procedo? grazie mille!!!!!

**Comment by Dasc3er** [comment]
Ciao @antoniotrapasso,
puoi lavorare sull'azione _get_more_info_ del file `modules/dashboard/actions.php` e in particolare aggiungere a `$tooltip_text` i contenuti che ti interessano a riguardo gli Impianti, che puoi ottenere con la seguente query:
`SELECT * FROM my_impianti_interventi WHERE idintervento=_id_`

**Comment by antoniotrapasso** [comment]
Ciao e grazie!
l'azione get_more_info quando entra in gioco?
con _id_ intendi $id = get('id')?
la query dovrei accodarla a quella già esistente?

Io ci ho provat ma forse mi manca qlks...

grazie mille!!

**Comment by antoniotrapasso** [comment]
Scusa se aggiungo un'altra cosa: ma il suggerimento che mi hai dato funziona come tooltip (quindi solo quando si passa sopra con il cursore) oppure lo stampa sempre? a me serve quest'ultima!

grazie

**Comment by Dasc3er** [comment]
Il suggerimento di sopra è utile per aggiungere l'impianto al tooltip del calendario, se vuoi aggiungerlo sempre devi modificare il file edit.php relativo.
Al posto di _id_ devi mettere l'id dell'intervento, che probabilmente è indicato come tale nel codice.
La query devi eseguirla a parte, con un po' di PHP di base.
