### ISSUE TITLE
Piccolo bug stampe DDT

### ISSUE THREAD

**Issue by Shero08** [devcode-it/openstamanager#719]
[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Creazione DDT da ordine cliente;
2. Stampa del DDT di vendita;
3. Sulla stampa del DDT, negli articoli compare il riferimento allo stesso DDT invece che all'ordine.

**Comment by Dasc3er** [comment]
@Shero08 per favore, rimuovi i contenuti che non hai utilizzato.

**Comment by Shero08** [comment]
@Dasc3er Fatto, scusami il ritardo.

**Comment by Dasc3er** [comment]
Grazie, e grazie per la segnalazione! Nei prossimi giorni provvederemo a verificare il problema.
