### ISSUE TITLE
Problemi stampe intervento

### ISSUE THREAD

**Issue by Technology-Solutions** [devcode-it/openstamanager#722]
Già dalla versione 2.4.11 si presenta un errore nelle stampe degli interventi che siano con o senza costi. 
Nel dettaglio la voce della tipologia dell'attività non viene stampato.
Il problema si verifica da quando il rs è stato sostituito con
`$documento['tipointervento']` nel file gestionale/templates/interventi/body.php

Ho provato a fare qualche test/combinazione. Ma sembrerebbe non passare proprio l'informazione

**Comment by loviuz** [comment]
Puoi provare con il commit referenziato qui sopra? Dovrebbe essere risolto, ci sono 3 file da modificare se hai la possibilità di farlo prima di attendere la release successiva.

**Comment by Technology-Solutions** [comment]
> 
> 
> Puoi provare con il commit referenziato qui sopra? Dovrebbe essere risolto, ci sono 3 file da modificare se hai la possibilità di farlo prima di attendere la release successiva.

Confermo che ha funzionato così.
Grazie
