### ISSUE TITLE
Generazione numero errato per fatture dell'anno precedente

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#723]
## Comportamento attuale

Se si creano fatture con data nel 2019 (ad esempio 10/12/2019) viene generato il numero di fattura 0001/2019, non rispettando la numerazione dello scorso anno. La numerazione viene invece giustamente azzerata quando si creano fatture con data nel 2020

## Possibile soluzione

Il problema potrebbe essere causato dal metodo getNextNumeroSecondario del file **modules/fatture/src/Fattura.php**

## Contesto

* Modulo: **Fatture di vendita**
* Versione del progetto: 2.4.12
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by loviuz** [comment]
Puoi provare ad aggiornare i file del commit referenziato? Dovrebbe risolvere il problema, ho appena provato ad emettere fatture cambiando data ed ora il calcolo del progressivo si basa sulla data del documento.

**Comment by maicol07** [comment]
@loviuz il problema è risolto!
