### ISSUE TITLE
Problema calcolo data scadenza nelle fatture di vendita 

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#724]
v. 2.4.12

![Pagamenti   OpenSTAManager(1)](https://user-images.githubusercontent.com/30728163/71889452-747a5c00-3142-11ea-852a-f51b0ed5bf66.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Per favore, scrivi il commento nel testo normale 🤕 
Problema: se il numero di giorni impostato per una rata con scadenza "Data fatturazione giorno fisso" supera il numero di giorni del mese, non viene impostata nessuna data.

**Comment by Dasc3er** [comment]
Il commit precedente dovrebbe risolvere il problema, e aggiorna la gestione delle date interne alla classe PHP nativa DateTime per evitare problemi simili in futuro.
Per sicurezza, può essere utile un controllo che le scadenze vengano generate correttamente.
