### ISSUE TITLE
MIGLIORIA modulo attività come nella versione 2.4.11

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#727]
## Comportamento richiesto

Ritornare alla versione 2.4.11

## Comportamento attuale

Nella versione precedente era possibile modificare i valori nella sessione ore di lavoro

OSM 2.4.12

**Comment by Dasc3er** [comment]
È ancora possibile modificare i valori che hai indicato, secondo il seguente controllo:

https://github.com/devcode-it/openstamanager/blob/b561834fa6a38ac251bea1d9d236287d156dea13/modules/interventi/manage_sessione.php#L9

**Comment by idraulicadueci** [comment]
Però nella 2.4.11 potevo modificare anche tariffa oraria e gli altri costi; adesso posso solo modificare il chilometraggio e gli orari.

**Comment by idraulicadueci** [comment]
Ho dimenticato di indicarti che sono loggato come amministratore, quindi dovrei poter modificare tutti i valori senza impostare i permessi.

**Comment by Dasc3er** [comment]
@lucasalva87
