### ISSUE TITLE
Pop-up Widget Attività confermate

### ISSUE THREAD

**Issue by Technology-Solutions** [devcode-it/openstamanager#728]
## Comportamento richiesto
Mancata apertura del pop-up nel widget "attività confermate" da Dashboard

## Comportamento attuale
Questo è l'errore che si ottiene caricando direttamente il file 
 ../modules/interventi/widgets/interventi_confermati.php

`Si è verificato un'errore [uid: a89e5d9]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception PDOException: "SQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 row" at /web/htdocs/www.nomedominio.it/home/gestionale/src/Database.php line 240
Si è verificato un'errore [uid: a89e5d9]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
SQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 row `

In calce all'errore, viene stampata comunque la tabella delle attività confermate
## Possibile soluzione
Prima di questa segnalazione, in zz_widget del database ho sostituito la query del widget Attività confermate (ID: 25) perchè non veniva restituito il numero di attività confermate, ma era sempre 0.

DA
`SELECT COUNT(id) AS dato FROM in_interventi WHERE in_interventi.idstatointervento = (SELECT in_statiintervento.idstatointervento FROm in_statiintervento WHERE in_statiintervento.codice='In Programmazione') ORDER BY data_richiesta ASC`

A
`SELECT COUNT(id) AS dato FROM in_interventi WHERE in_interventi.idstatointervento = (SELECT in_statiintervento.idstatointervento FROm in_statiintervento WHERE in_statiintervento.codice='WIP') ORDER BY data_richiesta ASC`

* Modulo: Interventi
* Versione del progetto: 2.4.12 
* Versione PHP:  7.2.22
* Tipo di server: Aruba Linux

**Comment by Dasc3er** [comment]
@Technology-Solutions La query originale era `SELECT COUNT(id) AS dato FROM in_interventi WHERE in_interventi.idstatointervento = (SELECT in_statiintervento.idstatointervento FROM in_statiintervento WHERE in_statiintervento.descrizione='In programmazione') ORDER BY in_interventi.data_richiesta ASC` per Attività confermate, e infatti essa non provoca errori.

**Comment by Technology-Solutions** [comment]
> 
> 
> @Technology-Solutions La query originale era `SELECT COUNT(id) AS dato FROM in_interventi WHERE in_interventi.idstatointervento = (SELECT in_statiintervento.idstatointervento FROM in_statiintervento WHERE in_statiintervento.descrizione='In programmazione') ORDER BY in_interventi.data_richiesta ASC` per Attività confermate, e infatti essa non provoca errori.

Grazie per la risposta, ma tornando a questa query, non mi restituisce il numero delle attività, infatti adesso mi restituisce 0 (e non 4 come dovrebbe essere), inoltre non si apre ancora il pop-up. Se inserisco "WIP"mi restituisce il numero 4, ovvero corretto.

**Comment by Dasc3er** [comment]
Correzione della query per utilizzare il codice, ma il popup funziona correttamente.
