### ISSUE TITLE
Marca da bollo mancante

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#73]
Nella stampa fattura non esce da nessuna parte la marca da bollo se presente.
Nella tabella con le righe invece, esce alla fine, senza mostrare il totale comprensivo di marca da bollo.

**Comment by Dasc3er** [comment]
@loviuz per il momento nella stampa delle fatture la marca da bollo non è nemmeno presente...
Come bisognerebbe inserirla?

**Comment by lepool** [comment]
Se puo essere d'aiuto ho trovato questo su [Guidafisco](https://www.guidafisco.it/bollo-su-fatture-1-81-718).

**Comment by loviuz** [comment]
sto facendo uno screenshot con delle specifiche per vari casi, tra qualche minuto pubblico...

**Comment by loviuz** [comment]
A meno che non hai un'idea di dove inserirla (deve essere specificata che c'è), ci sono vari casi in cui può trovarsi, in base a com'è impostata la fattura:
- senza rivalsa inps e senza ritenuta d'acconto: come la rivalsa inps, cioè un'ulteriore riga con a sinistra marca da bollo e destra il totale comprensivo di marca da bollo
- solo con rivalsa inps: spezzando in 2 la riga della rivalsa inps (vedi screenshot sotto)
- solo con ritenuta d'acconto: spezzando in 2 la riga della ritenuta d'acconto
- con rivalsa inps e ritenuta d'acconto: spezzando in 2 la riga della rivalsa inps (perché è l'ultima riga)

Un esempio di solo con rivalsa inps:
![schermata del 2017-12-15 10 59 17](https://user-images.githubusercontent.com/1647128/34037261-65705d4c-e188-11e7-91ba-869f8e825af9.png)

Siccome la marca da bollo è una specie di francobollo da applicare alla stampa fattura, serve lo spazio per applicarlo, ed è una cosa che non era mai stata predisposta. Se noti, nello screenshot qui sopra, ho aggiunto con un grigio chiaro uno spazio per applicare la marca da bollo (se c'è). @Dasc3er, crea problemi alla tabella principale aggiungere un riquadro così ingombrante nel footer?

PS: dato che la marca da bollo può cambiare nel tempo, ed ora è larga 4x3 cm, fare quel quadratino largo 2.8x2.8 cm, così non fuoriesce dalla marca da bollo una volta applicata.

**Comment by Dasc3er** [comment]
@loviuz Questo quadratino deve essere presente in tutte le pagine, solo la prima o solo l'ultima?

**Comment by loviuz** [comment]
solo sulla prima, o almeno su una sola, perché va applicata una sola volta per fattura, anche su multipagina

**Comment by loviuz** [comment]
pardon: sarebbe meglio sull'ultima, ma ho risposto considerando i problemi con html2pdf, per il quale non riuscivamo a mettere solo sull'ultima pagina un elemento... :-/
meglio sull'ultima se riesci

**Comment by Dasc3er** [comment]
Ecco il risultato con la presenza di sola Rivalsa INPS:
![screenshot-2017-12-15 fattura_pro-14 pdf - pdfgen php 2](https://user-images.githubusercontent.com/15911489/34053667-f15c579a-e1c7-11e7-83f9-c1b1f964d221.png)

Ecco il risultato con la presenza di sola Ritenuta d'acconto:
![screenshot-2017-12-15 fattura_pro-14 pdf - pdfgen php](https://user-images.githubusercontent.com/15911489/34053668-f179fdd6-e1c7-11e7-9598-14c56c1855b6.png)

E il risultato combinato:
![screenshot-2017-12-15 fattura_pro-14 pdf - pdfgen php 1](https://user-images.githubusercontent.com/15911489/34053666-f13edbe8-e1c7-11e7-9de1-0bf21c3d9020.png)

Ho un po' falsificato i dati al database per fare gli screenshot di seguito, quindi qualcosa nei conti delle immagini potrebbe non tornare :D.

**Comment by Dasc3er** [comment]
Invece questo sarebbe il risultato per la marca da bollo, che viene inserita solo nell'ultima pagina:
![screenshot-2017-12-15 fattura_pro-14 pdf - pdfgen php 3](https://user-images.githubusercontent.com/15911489/34054193-128d8040-e1ca-11e7-8ca8-6bf9caf67718.png)

Dovrebbe essere impostata in fondo alla pagina grazie all'auto-inserimento delle righe nella tabella principale, quindi dovrebbe funzionare in automatico per la maggior parte dei casi.

**Comment by loviuz** [comment]
va benissimo, appena provato. ho appena fatto un commit per risolvere un bug nei calcoli con rivalsa inps e ritenuta acconto. in row-list poi non aggiungeva la marca da bollo.
ho fatto delle prove con casi vari, ora dovrebbero essere corretti i calcoli.

**Comment by konda619** [comment]
Come faccio ad attivare la visualizzazione del riquadro della marca da bollo e della voce? ho provato a copiare i file footer.php init.php e header.php che trovo qui su github, ma non mi compaiono le voci e non mi visualizza il totale con la marca da bollo come da file allegato. 
![senza titolo-1](https://user-images.githubusercontent.com/35132987/34607931-321743b8-f216-11e7-9924-2e1e3c37d463.jpg)

**Comment by Dasc3er** [comment]
@konda619 In teoria dovresti aggiornare tutti i file della stampa **templates/fatture**, compresi **init.php** e **body.php**...

**Comment by konda619** [comment]
forse ho capito, marca da bollo compare solo se ho rivalsa inps o ritenuta d'acconto. in mancanza di una di queste 2 voci non viene visualizzata la voce marca da bollo. per il riquadro devo controllare body.php

**Comment by Dasc3er** [comment]
@konda619 In teoria la Marca da bollo è separata da Rivalsa INPS e Ritenuta d'acconto...
Prova ad aggiornare l'intera stampa per sicurezza 👍

**Comment by konda619** [comment]
@Dasc3er ho provato ad aggiornare l'intera stampa e se non inserisco rivalsa inps, non compare la riga e quindi non carica neanche la voce marca da bollo, e da quel poco che ne capisco di php sembra che la riga in cui è presente il td della marca da bollo la carica solo se è presente la rivalsa inps. Correggetemi se sbaglio ma non ho mai studiato php e html.

**Comment by Dasc3er** [comment]
@konda619 Prima di creare le righe della fattura, hai impostato correttamente la marca da bollo nelle **Impostazioni** (_Importo marca da bollo_)? Perché altrimenti, se non erro, la marca da bollo non viene inserita all'interno della fattura...

Inoltre, i controlli sulla marca da bollo sono separati da quelli di Rivalsa INPS, a quanto mi risulta...
@loviuz Puoi confermare?

**Comment by konda619** [comment]
@Dasc3er Si, ho impostato correttamente, infatti sia sulla modifica della fattura "a monitor" che in scadenze pagamenti "a stampa" la marca da bollo viene visualizzata. L'unica cosa è che non compare il la voce marca da bollo con l'importo prima di totale documento. se invece imposto la rivalsa INPS mi compare a destra di rivalsa inps come qui

![](https://user-images.githubusercontent.com/15911489/34053667-f15c579a-e1c7-11e7-83f9-c1b1f964d221.png)

**Comment by Dasc3er** [comment]
@konda619 Errore mio nell'implementazione della stampa... Grazie per avermelo fatto notare, inizialmente non avevo capito il problema!

@loviuz @fpsoftware Ho aggiunto la seguente riga nel caso Rivalsa INPS e Ritenuta d'acconto non siano presenti ma la Marca da bollo sì.
![screenshot-2018-1-5 fattura_pro-1 pdf - pdfgen php](https://user-images.githubusercontent.com/15911489/34617513-fddac27a-f23b-11e7-9b2a-bc7c6e9280a8.png)

Una domanda: al momento ci sono due conti con il titolo "Totale documento", come sarebbe meglio gestirli?

**Comment by fpsoftware** [comment]
Sicuramente ci deve essere un'unica cella con il Totale documento, riusciamo ad aggiungere una eventuale cella tra il Totale iva ed il Totale documento, quindi tutto in una riga, senza sfalsare la tabella finale?

**Comment by Dasc3er** [comment]
@fpsoftware Il problema è che al momento la prima riga viene riempita dalle seguenti informazioni oltre al totale:

- Imponibile | IVA
- Imponibile | Sconto | IVA

in base alla presenza di sconti.
Le altre informazioni erano state separate in ulteriori righe, però consiglierei di mantenere comunque il formato attuale (immagini sotto).

Si potrebbe differenziare i totali nel seguente modo?

- Totale della prima riga
    1. "Totale documento" se Ritenuta d'acconto, Rivalsa INPS e Marca da bollo non sono presenti
    2. "Totale" se se Ritenuta d'acconto, Rivalsa INPS o Marca da bollo sono presenti
- Totale della riga con Rivalsa INPS: "Totale documento"
- Totale della riga con Ritenuta d'acconto: "Netto a pagare"
- Totale della riga con sola Marca da bollo: "Totale documento"

In pratica, la differenza dallo schema attuale è nella dicitura del primo totale .

**Schema attuale**
Rivalsa INPS e Marca da bollo:
![screenshot-2017-12-15 fattura_pro-14 pdf - pdfgen php 2](https://user-images.githubusercontent.com/15911489/34053667-f15c579a-e1c7-11e7-83f9-c1b1f964d221.png)

Ritenuta d'acconto e Marca da bollo:
![screenshot-2017-12-15 fattura_pro-14 pdf - pdfgen php](https://user-images.githubusercontent.com/15911489/34053668-f179fdd6-e1c7-11e7-9598-14c56c1855b6.png)

Ritenuta d'acconto, Rivalsa INPS e Marca da bollo:
![screenshot-2017-12-15 fattura_pro-14 pdf - pdfgen php 1](https://user-images.githubusercontent.com/15911489/34053666-f13edbe8-e1c7-11e7-9de1-0bf21c3d9020.png)

Marca da bollo:
![screenshot-2018-1-5 fattura_pro-1 pdf - pdfgen php 1](https://user-images.githubusercontent.com/15911489/34617599-3f482bee-f23c-11e7-9f72-15fb73e1ea48.png)

**Comment by loviuz** [comment]
il totale doppio (ultimo screenshot) non è l'ideale perché ho visto varie stampe e non va messo così esteticamente. in realtà, la marca da bollo molti la mettono come riga del documento con un'esenzione iva precisa (che devo trovare su internet, non ricordo qual è), per cui poi nei calcoli sarebbe tutto un po' più pulito, e non servirebbe aggiungerla in fondo, però non va calcolata l'eventuale rivalsa inps o ritenuta d'acconto sul totalr comprensivo di marca da bollo. in pratica, la marca da bollo non concorre a formare l'imponibile, per cui la terrei separata.

dopo questo riepilogo informativo, rimane il dubbio su come farla uscire in stampa. ci penso e vediamo come risolvere, nel frattempo teniamo l'issue aperto, non è concettualmente sbagliata la stampa, è solo presentata non nel migliore dei modi.

**Comment by loviuz** [comment]
cambiato "Totale documento" in "Netto a pagare" se c'è solo la marca da bollo
