### ISSUE TITLE
BUG: Errore calcolo IVA in attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#730]
## Comportamento attuale

Viene calcolata solo l'IVA delle righe

![IMG1](https://user-images.githubusercontent.com/40104356/72201491-e01b3c80-3454-11ea-923b-f31b7923e3d9.png)

OSM 2.4.12

**Comment by idraulicadueci** [comment]
Correggo l'importo IVA deve venire 18,74

**Comment by loviuz** [comment]
@Dasc3er sto analizzando il problema, sembra che ci sia anche un altro problema, ossia che se inserisco 2 righe generiche e 1 articolo nell'intervento con un db pulito, succede che mi ritrovo in questa situazione:
`in_righe_interventi`
riga1, id = 1
riga2, id = 2

`mg_articoli_interventi`
articolo1, id = 1

Con il merge di righe e articoli, mi ritrovo nell'intervento la riga 2 e l'articolo 1, perché pare che il merge tenga solo una delle 2 righe con id=1. Possibile?

**Comment by Dasc3er** [comment]
@loviuz Il problema che hai indicato in effetti era causato esclusivamente dalla gestione dedicata agli Interventi. Dovrebbe essere ora risolto.

**Comment by Dasc3er** [comment]
@idraulicadueci Non riesco a replicare il problema, ma potrebbe essere stato causato dal bug segnalato da @loviuz... Potresti provare a replicare il commit cb8b13e7, e il commit 155e4f94 per il file `modules/interventi/src/Intervento.php`?

**Comment by loviuz** [comment]
Confermo che il problema è risolto, sia quello segnalato da @idraulicadueci e il mio successivo.

**Comment by idraulicadueci** [comment]
Il problema non si è risolto.
Ho cambiato i 2 files (include/src/Document.php e modules/interventi/src/Intervento.php) come proposto da @Dasc3er, ma l'IVA continua a essere calcolata solo sugli articoli e righe aggiunte nell'intervento, e non sulle ore di lavoro.
Per riprodurre il problema:
creare una nuova attività, aggiungere le ore di lavoro, aggiungere una riga generica.
Ho controllato l'anagrafica, e ha l'aliquota IVA specificata.
Devo controllare qualcosa in particolare nel db?

**Comment by loviuz** [comment]
Non riesco a riprodurre il problema. Tuttavia stiamo pubblicando la versione 2.4.13, potresti riprovare con quella? Teoricamente la rilasciamo oggi

**Comment by idraulicadueci** [comment]
Aggiornato alla 2.4.13.
Ho notato che non ho indicato l'aliquota IVA predefinita in IMPOSTAZIONI- per ->FATTURAZIONE. Ho provato a inserire il valore (22%) e adesso nel modulo Interventi viene calcolata l'IVA anche per le ORE DI LAVORO (quindi su diritto di intervento, costi di trasferta, ecc.). Il problema sta nel fatto che nell'anagrafica inserita è stata impostata un'aliquota del 10%.
Credo che il problema stia nel blocco decisionale in cui non viene tenuto conto dell'esistenza dell'aliquota cliente e quindi prenda direttamente quella predefinita.
Prova a eliminare l'aliquota predefinita e forse riesci a ripordurre il bug.

**Comment by Dasc3er** [comment]
Solo per gli interventi viene sempre presa l'aliquota dalle Impostazioni, quindi il funzionamento dovrebbe essere corretto anche se non standard con il resto del gestionale.

**Comment by idraulicadueci** [comment]
> Solo per gli interventi viene sempre presa l'aliquota dalle Impostazioni, quindi il funzionamento dovrebbe essere corretto anche se non standard con il resto del gestionale.

Dovrebbe invece prendere l'aliquota dell'anagrafica, perché se beneficia di aliquota agevolata oppure a zero (reverse charge), il cliente non deve vedere un'importo IVA superiore.
Torno alla mia convinzione che negli interventi il calcolo IVA deve essere tolto e mettere solo TOTALE IMPONIBILE IVA ESCLUSA. L'IVA poi sarebbe poi riportata in fattura.

**Comment by Dasc3er** [comment]
Infatti l'IVA nelle sessioni di lavoro delle attività è esclusivamente indicativa, e viene sovrascritta all'importazione in fattura secondo la selezione dell'utente.
