### ISSUE TITLE
Numerazione preventivi come fatture

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#731]
## Comportamento richiesto
Numerazione preventivi come quella delle fatture o azzeramento numerazione quando si passa al nuovo anno

## Contesto

* Modulo: **Preventivi**
* Versione del progetto: 2.4.12
* Versione PHP: 7.4
* Tipo di server: Apache

**Comment by lucasalva87** [comment]
Proposte su come gestire la cosa? Potrebbe essere utile un campo "forza numerazione" in impostazioni vicino alla maschera del preventivo

**Comment by maicol07** [comment]
Come stanno procedendo i lavori su questa funzionalità, dato che non ci sono stati più aggiornamenti?
Grazie

**Comment by Dasc3er** [comment]
@maicol07 Si potrebbe inserire una nuova Impostazione che richiede il formato del codice Preventivo, come esiste per gli Interventi se non erro, e poi replicare la funzionalità del metodo getNextCodice() nella classe Preventivo.

**Comment by lucasalva87** [comment]
Riesumo questa issue per segnare la sua eventuale risoluzione. 
Con il commit beddb78b41e779534a5c11f53c4e3eed11f7ee82 era stato risolto se non erro.

**Comment by maicol07** [comment]
@lucasalva87 in realtà al momento la numerazione continua dall'anno precedente e non si riparte da 1. Inoltre, non viene neanche specificato l'anno come invece accade nelle fatture

**Comment by lucasalva87** [comment]
Qual'è la maschera inserita in Impostazioni -> Preventivi-> Formato codice preventivi?

**Comment by maicol07** [comment]
@lucasalva87
![immagine](https://user-images.githubusercontent.com/9463142/104575985-ee97c780-5657-11eb-901a-1549cffc27d7.png)

**Comment by maicol07** [comment]
Ok, modificato in 
![immagine](https://user-images.githubusercontent.com/9463142/104576977-39660f00-5659-11eb-8366-0b48339afbb8.png)

Così funziona.

Direi che quindi il problema è stato risolto
