### ISSUE TITLE
MIGLIORIA: Aggiungere banca predefinita su tabella pagamenti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#733]
## Comportamento richiesto

Avere la possibilità di indicare un conto (IBAN) predefinito per il tipo di pagamento

## Comportamento attuale

Non è possibile indicare il conto predefinito, con il rischio di emettere una fattura senza estremi per il pagamento

OSM 2.4.12

**Comment by maicol07** [comment]
Penso questo sia collegato al fatto che impostando la banca al cliente non viene automaticamente impostata nella fattura

**Comment by Dasc3er** [comment]
@idraulicadueci Questa funzionalità è ora disponibile con le modifiche effettuate al modulo Pagamenti e al nuovo modulo Banche.
