### ISSUE TITLE
Errore rinominazione 2.4.11

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#736]
Alcune query di rename per la 2.4.11 non funzionano sempre.
Forum: https://forum.openstamanager.com/viewtopic.php?f=2&t=95114#p103213

**Comment by Shero08** [comment]
Salve, per caso ci sono novità in merito? Grazie

**Comment by Dasc3er** [comment]
Per il momento no perchè non siamo riusciti a riprodurre il problema.
Potrebbe essere causato da alcune foreign key che non vengono spesso utilizzate, e pertanto richiede maggiori approfondimenti. Se hai urgenza, ti consiglio di scrivere una mail a info@openstamanager.com per considerare l'acquisto di un pacchetto di supporto.

**Comment by Dasc3er** [comment]
@Shero08 Se controlli il forum, sembra che un utente sia riuscito ad aggiornare manualmente, malgrado non possiamo assicurarti la sua procedura sia corretta e pertanto non sarà inserita in release per il momento.

**Comment by Shero08** [comment]
> 
> 
> @Shero08 Se controlli il forum, sembra che un utente sia riuscito ad aggiornare manualmente, malgrado non possiamo assicurarti la sua procedura sia corretta e pertanto non sarà inserita in release per il momento.

Alla fine ho risolto, mi spiace non averlo segnalato prima, in realtà la problematica era la versione del DB che non era aggiornata. Infatti spostando il tutto su un db aggiornato l'aggiornamento è andato a buon fine. Grazie

**Comment by Dasc3er** [comment]
Grazie a te!
Se non riceviamo ulteriori segnalazioni sul problema consideriamo la versione del database come la causa, ed in effetti non siamo mai riusciti a replicare il problema...

**Comment by loviuz** [comment]
@Shero08 se puoi provare, avevamo comunque risolto in questo modo:
https://github.com/devcode-it/openstamanager/commit/665dd823ae5aefaea683e8fdce857c177c53266a
