### ISSUE TITLE
BUG: Generazione errata numero intervento per anno precedente

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#737]
Mi ricollego alla issue #723

## Comportamento attuale

Se inserisco un intervento con data richiesta dell'anno precedente, viene generato un numero progressivo dell'anno attuale, fra l'altro duplicato.

## Passi per riprodurre il comportamento

Attività --> Nuova attività --> Data richiesta 31/12/2019 -->Inserimento altri dati obbligatori --> AGGIUNGI
Numero generato 0002/2020 (progressivo già esistente. Ultimo intervento generato era 0007/2020 e 0002/2020 già esiste.

OSM 2.4.12

**Comment by loviuz** [comment]
E' stato risolto dalla versione 2.4.13 del 5 febbraio.
