### ISSUE TITLE
MIGLIORIA: Aggiunta flag "QUESTO ARTICOLO E' UNA DESCRIZIONE" a modulo articoli

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#740]
## Comportamento richiesto

Inserire il flag "QUESTO ARTICOLO E' UNA DESCRIZIONE" al modulo articoli, in modo da inserire la voce ai documenti omettendo UM-Q.tà-Prezzo, come avviene per le righe aggiunte come DESCRIZIONE

**Comment by Dasc3er** [comment]
La descrizione è una riga non relativa a un articolo.
Devi pertanto inserirla tramite il pulsante apposito.

Se necessiti dei template per le descrizioni ti suggerisco di considerare una personalizzazione.
