### ISSUE TITLE
a slight change

### ISSUE THREAD

**Issue by ttodua** [devcode-it/openstamanager#741]
Hi.
I've seen that in a part of code:

https://github.com/devcode-it/openstamanager/blob/master/lib/util.php

line 525:
there is written:
* @source taz...../useful-php-scripts

please update that to correct username:

* @source ttodua/useful-php-scripts

thanks

**Comment by Dasc3er** [comment]
I actually removed the function because it wasn't used anymore.
Thanks for reporting our error on the source!
