### ISSUE TITLE
Creazione procedura per copia di un preventivo in un nuovo contratto

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#742]
Aggiungo come promemoria per prossime funzionalità: aggiungere la possibilità dal preventivo di creare un contratto evadendo le singole righe, così come avviene come la creazione di un ordine o una fattura dal preventivo con il tasto "Crea".

**Comment by Dasc3er** [comment]
@loviuz Ho creato una issue più generale per tutti queste funzioni #786

**Comment by Dasc3er** [comment]
In modo simile, risulta utile la creazione di DDT a partire dai Preventivi.

**Comment by Dasc3er** [comment]
La issue può essere chiusa, poiché la funzionalità è stata implementata. Resta da definire una generalizzazione di queste operazion.
