### ISSUE TITLE
Migliora: esportazione fatture in Pdf

### ISSUE THREAD

**Issue by lexen77** [devcode-it/openstamanager#743]
Sarebbe utile esportare piu fatture  in un unico file pdf.
Situazione utile quando dobbiamo espostare per lo stesso cliente il riepilogo delle fattue

**Comment by Dasc3er** [comment]
@lexen77 Non vedo l'utilità di questa funzione.
In particolare, se è necessario esportare le fatture di un cliente si può effettuare attraverso un azione bulk sulla tabella principale, che scarica un file zip con tutte le fatture separate. A partire da questa cartella, sono disponibili molti strumenti che permettono di lavorare con i PDF (per esempio unendoli) e procedere di conseguenza. Non si tratta quindi di una *funzionalità del gestionale*.

Se sei comunque interessato alla personalizzazione ti consiglio di scrivere a info@openstamanager.com.
