### ISSUE TITLE
modulo contabilità - stampe contabili

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#744]
## Comportamento richiesto

Visualizzazione valore imposta corretto

## Comportamento attuale

Visualizzazione valore imposta uguale a imponibile

## Passi per riprodurre il comportamento

1. cliccare su stampa registro iva vendite o acquisti a video appare il valore imposta uguale al valore imponibile esempio:
100 -100
Corretto dovrebbe essere
100 - 22
Nel mio caso che uso iva al 22%

* Versione PHP: 7.2.10

**Comment by Dasc3er** [comment]
Purtroppo devo chiederti di spiegare più nel dettaglio cosa intendi, e di cancellare le parti del formato che non hai completato.

**Comment by leo-spa** [comment]
Ho corretto come da richiesta

**Comment by Dasc3er** [comment]
Posso confermare che il comportamento è corretto.
![image](https://user-images.githubusercontent.com/15911489/75458220-ce96e100-597d-11ea-95e7-18b82eeb243b.png)

**Comment by leo-spa** [comment]
Il gio 27 feb 2020, 16:30 Thomas Zilio <notifications@github.com> ha
scritto:
