### ISSUE TITLE
checklist nella descrizione o stampa

### ISSUE THREAD

**Issue by Technology-Solutions** [devcode-it/openstamanager#745]
Salve,
sto utilizzando e testando la versione 2.4.12, mi chiedevo se fosse possibile in qualche modo, riportare nella stampa, o meglio ancora nella descrizione del tecnico la checklist con i soli campi spuntati

**Comment by Dasc3er** [comment]
@Technology-Solutions Per il momento ti consiglio di considerare una personalizzazione, poiché dubito che la miglioria verrà effettuata a breve. Grazie per il consiglio!
