### ISSUE TITLE
MIGLIORIA: Campo data non obbligatorio in gestione documentale

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#746]
## Comportamento richiesto

E' utile che il campo data nella gestione documentale non sia obbligatorio, per permettere di visualizzare i documenti che restano validi per gli anni successivi.

## Comportamento attuale

Alcuni documenti restano validi anche per gli anni successivi a quello di inserimento, ma per visualizzarli è necessario filtrare la data

## Possibile soluzione

Rendere il campo non obbligatorio

**Comment by Pek5892** [comment]
Risolto con release 2.4.23
