### ISSUE TITLE
Caricamento piano dei conti via ajax

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#75]
Caricare i dettagli dei conti al click (conti di co_pianodeiconti3) tramite ajax, perché in molti casi, chi ha più di 1000 clienti, riscontra rallentamenti nel caricamento della schermata, perché per ogni anagrafica cliente o fornitore vengono creati dei conti correlati.

**Comment by Dasc3er** [comment]
Correlato a #21, che prevede di introdurre il nuovo sistema unificato per i conti al fine di evitare problemi di arrotondamento.

**Comment by Dasc3er** [comment]
Completato con il commit 0396f9c3efaeb544f52523257206f674f72d20b7
