### ISSUE TITLE
BUG: attività associata a contratto risulta da fatturare in Fatture di Vendita

### ISSUE THREAD

**Issue by stefanostc** [devcode-it/openstamanager#751]
## Comportamento richiesto

Le attività inserite direttamente dalla pagina ATTIVITA' relative ad un CONTRATTO non dovrebbero apparire della dropdown +Attività in Vendite>FATTURE DI VENDITA (come già accade per le attività associate ad un preventivo)

## Comportamento attuale

Inserendo una nuova attività con riferimento ad un contratto dalla pagina ATTIVITA' questa risulta da fatturare in VENDITE>FATTURE DI VENTIDA> (CLIENTE) >**+Attività**.
Se invece l'attività viene creata a partire dalla pagina PIANIFICAZIONE del Contratto allora questo non accade

**Comment by stefanostc** [comment]
modules\fatture\add_intervento.php

 ```
   WHERE
        (in_interventi.idanagrafica='.prepare($idanagrafica).' OR in_interventi.idclientefinale='.prepare($idanagrafica).')
        AND in_statiintervento.completato=1
        AND in_interventi.id NOT IN (SELECT idintervento FROM co_righe_documenti WHERE idintervento IS NOT NULL)
        AND in_interventi.id_preventivo IS NULL
        AND NOT in_interventi.id IN (SELECT idintervento FROM co_promemoria WHERE idintervento IS NOT NULL)');
```

manca 

`AND in_interventi.id_contratto IS NULL`

**Comment by stefanostc** [comment]
vedi Pull request Fix fatturazione interventi associati a contratto #752

**Comment by Dasc3er** [comment]
PR accettata, grazie per il contributo!
