### ISSUE TITLE
[PREVENTIVI] Permettere di visualizzare il prezzo di vendita anche quando la quantità è 0

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#754]
## Comportamento richiesto

Permettere di visualizzare il prezzo di vendita anche quando la quantità è uguale a 0.

## Comportamento attuale

Il prezzo di vendita è uguale a 0 dopo il salvataggio della riga.

## Passi per riprodurre il comportamento

1. Creare un preventivo
2. Aggiungere una riga con Quantità = 0 e Prezzo di vendita = qualsiasi prezzo
3. Salvare la riga

## Contesto

* Modulo: **Preventivi**
* Versione del progetto: 2.4.13
* Versione PHP: 7.4
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Attenzione: il problema qui non è il fatto che il prezzo è nullo, quanto il fatto che la riga viene salvata con quantità uguale a zero. In questi casi la riga non deve mai essere salvata.

**Comment by maicol07** [comment]
@Dasc3er Infatti nelle fatture questo non deve mai avvenire ma nei preventivi è utile per mostrare al cliente quanto costa un articolo se non è stato acquistato (ad esempio un optional)

**Comment by Dasc3er** [comment]
Ciò non è gestito dal gestionale, e se implementato non deve essere inserito nelle righe normali ma in una sezione separata (almeno nel database)...

**Comment by Dasc3er** [comment]
@maicol07 Con la versione i sviluppo è ora possibile a causa di una modifica nel salvataggio dei prezzi, ma confermo che non è una funzionalità del gestionale e pertanto non verrà mantenuta ufficialmente. In pratica, in futuro potrebbe sparire nuovamente.
Riferimento: #758
