### ISSUE TITLE
Stampa fatture errata

### ISSUE THREAD

**Issue by kalipso52** [devcode-it/openstamanager#755]
## Comportamento richiesto

Quando viene stampata una fattura mi aspetto che il footer venga stampato una sola volta e sul pdf non venga stampato nulla in bianco.

## Comportamento attuale

Attualmente quando viene stampata una fattura in fondo alla pagina si visualizza correttamente la tabella. In realtà se si prova a fare una selezione di tutta la pagina si vede che la tabella è stampata di colore bianco sfalsata più in alto rispetto a quella originale. Questo può creare problemi nel caso in cui si imposti un'immagine di sfondo.

## Contesto

* Modulo: 
* Versione del progetto: 2.4.13
* Versione PHP: 7.3.14
* Tipo di server: Linux (Plesk)

![errorsta](https://user-images.githubusercontent.com/60991105/74387255-59150780-4df8-11ea-9f79-80293684d1c2.PNG)

**Comment by Dasc3er** [comment]
Ciao, questo è previsto solo perché la tabella di resoconto viene stampata esclusivamente nell'ultima pagina: l'unica soluzione individuata è stata proprio quella di inserire una tabella trasparente per occupare lo spazio e impostare il resto sul footer della stampa.
Non ci è possibile procedere in altro modo, quindi se si verificano problemi del genere ti consiglio di disabilitare l'opzione "last-page-footer" nella tabella zz_prints.

**Comment by kalipso52** [comment]
Ciao ok grazie mille per la spiegazione.

**Comment by Dasc3er** [comment]
Grazie a te per la segnalazione!
Possiamo provare a fare una richiesta nella libreria ufficiale per la generazione stampe e vedere cosa ci rispondono.
