### ISSUE TITLE
Problema con la stampa preventivo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#759]
## Comportamento attuale
Se la descrizione in una riga del documento è troppo lunga, il testo della stampa è troppo piccolo e risulta illegibile.

OSM 2.4.13

**Comment by Dasc3er** [comment]
Il problema non è risolvibile al momento, poichè dipende dalla libreria che utilizziamo per le stampe e non ha una soluzione semplice.
Ti consiglio di evitare descrizioni troppo lunghe dentro le tabelle.

**Comment by idraulicadueci** [comment]
Ok. scusa il doppione, ho provato a cercare prima di inserire la issue, ma non ero riuscito a trovare niente. La soluzione, al momento, sarà quella di inserire le descrizioni nel campo descrizione principale e poi nelle righe una voce ridotta.

**Comment by Dasc3er** [comment]
Ecco il riferimento iniziale #111.
Purtroppo per ora quella che hai indicato è una delle poche alternative disponibili, in attesa che la libreria venga migliorata ulteriormente. 
Issue di riferimento: https://github.com/mpdf/mpdf/issues/650

**Comment by marcus905** [comment]
Il problema persiste con le lettere accentate, l'issue probabilmente è meglio lasciarla aperta.

**Comment by Dasc3er** [comment]
L'issue non è del gestionale.
Se sono disponibili strumenti open source più avanzati che risolvono il problema, sei il benvenuto per indicarli 😁

**Comment by marcus905** [comment]
Forse ho trovato una soluzione.

Disattivando nell'inizializzazione PDF in src/Prints.php:445 la modalità compatibilità e settando il default font a dejavusanscondensed (tra l'altro già distribuito nel gestionale) le righe vengono stampate correttamente.

La issue di fondo, ho indagato, sta nel fatto che per il font di defualt, helvetica, che non è embeddato nel file ma viene preso come formato standard da PDF le metriche orizzontali non sono impostate per i caratteri UTF-8 -- perché gestite non come file TTF ma codificate in maniera fissa in un file php (chelvatica.php) in mPDF stesso, e questo fa si che per le lettere accentate o i simboli fuori tabella ASCII il width sia null e faccia saltare una qualche logica in mPDF (che ancora non ho trovato) nel calcolo dsel dimensionamento.

Controindicazione alla modifica citata (di cui se vi va faccio un pull-request) è che le fatture ingrassano di circa 30kb a file per via del font embeddato, ma penso che non sia un grosso problema.

Vi allego una stampa preventivo d'esempio prima e dopo la modifica.
[Preventivo-num.-1-del-28052020-helvetica.pdf](https://github.com/devcode-it/openstamanager/files/4710510/Preventivo-num.-1-del-28052020-helvetica.pdf)
[Preventivo-num.-1-del-28052020-dejavusanscondensed.pdf](https://github.com/devcode-it/openstamanager/files/4710511/Preventivo-num.-1-del-28052020-dejavusanscondensed.pdf)

**Comment by Dasc3er** [comment]
Una pull request al riguardo è certamente benvenuta, anche perché non mi sembra che ci sia una enorme differenza tra i due font utilizzati.
Grazie per il contributo!
