### ISSUE TITLE
Non si riesce a cambiare l'IVA, quando si aggiunge un articolo in Fattura

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#76]
![image](https://user-images.githubusercontent.com/34273200/34071313-dd9a1622-e274-11e7-8e3c-549b851012a5.png)

Questo blocco è presente sia nelle fatture che nei   ##preventivi.

**Comment by Dasc3er** [comment]
Ciao @fgambarelli,
grazie mille per la segnalazione!

Il problema era generato dall'utilizzo della funzione JS sbagliata per impostare in automatico il campo IVA.
Se stai utilizzando la versione master da GIT, potresti confermarne la risoluzione con il commit a41f50d7c59fe77b2fe8698516bf05e19eb50f60?

**Comment by fgambarelli** [comment]
Grazie.
Confermo ora funziona la scelta dell'IVA
F.

Il giorno 16 dicembre 2017 15:49, Thomas Zilio <notifications@github.com>
ha scritto:
