### ISSUE TITLE
STAMPE ddt e fatture 

### ISSUE THREAD

**Issue by cicalo** [devcode-it/openstamanager#761]
quando al riga in descrizione è lunga la procedura di stampa sia ddt che fatture non va a capo ma si rimpicciolisce

openstamanager 2.4.13

verificato anche su online presente su vs. sito.
trovate un ddt in uscita con codice "descrizione lunga"

ciao et grazie
cicalo

**Comment by Dasc3er** [comment]
Issue duplicata: https://github.com/devcode-it/openstamanager/issues/759
