### ISSUE TITLE
BUG: problema visualizzazione filtro data nei browser Android

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#762]
Nei browser Android non è visibile il filtro data. Solo se imposto l'opzione "Sito desktop" allora riesco a vederlo, però, ovviamente la pagina è troppo piccola per lavorarci.

**Comment by idraulicadueci** [comment]
il problema si verifica con Android 6.0. Con Android 7.0 il problema non c'è.

**Comment by Dasc3er** [comment]
Il problema non è causato da Android, quanto dalle dimensioni dello schermo del dispositivo.
