### ISSUE TITLE
Aggiungere nuovo campo immagine in componenti aggiuntivi my_impianti 

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#767]
## Comportamento richiesto

Vorrei aggiungere un nuovo campo immagine (meglio ancora se fosse possibile caricare N immagini) ad uno dei componenti aggiuntivi che ho configurato con i fil .ini

## Comportamento attuale

Qual è il comportamento attuale, e come ti aspetti che venga migliorato?

## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by lucasalva87** [comment]
Ti chiedo cortesemente di rimuovere dalla richiesta le parti non compilate (questo anche per eventuali segnalazioni o richieste).

Inoltre anticipo che questa funzionalità non sarà prevista in release. Se ti può interessare possiamo comunque svilupparla ad hoc configurandola come personalizzazione per la tua installazione.
Per info scrivi pure a : info@openstamanager.com
