### ISSUE TITLE
Codice fiscale uguale tra Persona giuridica e Ditta individuale

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#768]
Se creo una nuova anagrafica e inserisco un codice fiscale già censito, al momento del salvataggio il codice "doppione" viene cancellato.
Questo non è corretto, in quanto può verificarsi il caso in cui ho l'anagrafica di una ditta individuale, per la quale vengono indicati sia partita IVA che codice fiscale (persona giuridica), e lo stesso codice fiscale lo inserisco nell'anagrafica della persona , trattata come persona fisica e non giuridica.
Una soluzione potrebbe essere quella di effettuare un controllo incrociato sulla tipologia; quindi se ho lo stesso codice fiscale per due aziende, questo non è possibile e quindi è un errore, come se ce l'ho per due privati, mentre se le tipologie si differiscono non deve essere considerato un errore.

**Comment by Shero08** [comment]
> 
> 
> Se creo una nuova anagrafica e inserisco un codice fiscale già censito, al momento del salvataggio il codice "doppione" viene cancellato.
> Questo non è corretto, in quanto può verificarsi il caso in cui ho l'anagrafica di una ditta individuale, per la quale vengono indicati sia partita IVA che codice fiscale (persona giuridica), e lo stesso codice fiscale lo inserisco nell'anagrafica della persona , trattata come persona fisica e non giuridica.
> Una soluzione potrebbe essere quella di effettuare un controllo incrociato sulla tipologia; quindi se ho lo stesso codice fiscale per due aziende, questo non è possibile e quindi è un errore, come se ce l'ho per due privati, mentre se le tipologie si differiscono non deve essere considerato un errore.

Può capitare però che uffici diversi abbiano la stessa partita IVA, mi spiego meglio. Nel caso delle università ad esempio, ogni dipartimento ha un codice univoco differente ma stessa partita IVA. In questo caso ogni dipartimento può fare acquisti in autonomia con il proprio codice univoco, ma il gestionale non permette di inserire più anagrafiche con la stessa P.IVA. Si potrebbe fare qualcosa? Grazie

**Comment by Dasc3er** [comment]
Possiamo certamente fare qualcosa, e in particolare potremmo evitare il blocco ma aggiungere un semplice warning in caso di molteplici anagrafiche con stesso Codice Fiscale e Partita IVA.

**Comment by Dasc3er** [comment]
Il commit fc3ca2b145e7e23034425584ef485094a199d450 dovrebbe risolvere il problema e migliorare i messaggi di errore sull'anagrafica.

**Comment by idraulicadueci** [comment]
Direi che così va benissimo.
