### ISSUE TITLE
Aggiunta Articolo - Non mostra le sottocategorie e non funziona la ricerca per caratteri

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#77]
Gli articoli sono catalogati in categorie SERVIZI e SOTTOCATEGORIE, ma non si vedono le sottocategorie 
![image](https://user-images.githubusercontent.com/34273200/34072621-cdbe00ae-e28a-11e7-9320-f375749971fc.png)

Scrivendo una parte dell'articolo, non restituisce i risultati
![image](https://user-images.githubusercontent.com/34273200/34072629-0fdd64a2-e28b-11e7-95e0-88c6210f663d.png)

**Comment by Dasc3er** [comment]
Ancora grazie per la segnalazione!
Il primo problema era causato da una mancanza nella progettazione del select, che ora mostra **categoria (sottocategoria)** con sottocategoria impostata a "-" se non definita.
Il secondo punto era invece causato da un problema di ambiguità nella query per l'individuazione degli articoli filtrati.

@fgambarelli Potresti ancora una volta confermarne la risoluzione con il commit 8202e5a6272e61cc2441392e6f7ce0362689cd4c?
Grazie ancora!

**Comment by fgambarelli** [comment]
Confermo. 
Ora funzionano sia il cerca che il raggruppamento.

**Comment by Dasc3er** [comment]
@loviuz @fpsoftware @lucasalva87 Può andare la visualizzazione delle sottocategorie così impostata?
