### ISSUE TITLE
Viene passato un URL HTTP di un file inesistente al visualizzatore di PDFJS su HTTPS

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#770]
Nell'anteprima per la firma degli interventi ho riscontrato un problema con l'url dell'iframe di pdfjs: il visualizzatore da errore sulla discrepanza nel protocollo dell'url. 

![image](https://user-images.githubusercontent.com/6625123/75708844-dcbc6880-5cc1-11ea-91d9-d21a1f19a792.png)

Nonostante osm sia aperto in https e configurato per il redirect alla connessione sicura (`$redirectHTTPS = true` in `config.inc.php`) il parametro `file` ha protocollo http. 

```
https://osm.example.com/assets/dist/pdfjs/web/viewer.html?file=http://osm.example.com/modules/files/interventi/Intervento-num.-2-del-26022020.pdf
```

<hr>

Provando a caricare il file direttamente ottengo errore 404. Il percorso non sembra giusto...

L'url corretto infatti dovrebbe essere questo, che ho verificato funzionare:

```
https://osm.example.com/assets/dist/pdfjs/web/viewer.html?file=https://osm.example.com/files/interventi/Intervento-num.-2-del-26022020.pdf
```

<hr>

In sostanza ci sono due problemi:
 - [x] url del pdf non corretto
 - [ ] discrepanza del protocollo

<hr>

* Modulo: interventi
* Versione del progetto: 2.4.13
* Versione PHP: 7.3
* Tipo di server: cpanel/apache 2.4

**Comment by Dasc3er** [comment]
Il problema del protocollo potrebbe essere causato dalla seguente riga:
https://github.com/devcode-it/openstamanager/blob/665dd823ae5aefaea683e8fdce857c177c53266a/src/App.php#L132
Sembrerebbe che la funzione isHTTPS non resituisca il valore corretto.

Per quanto riguarda l'URL "modules/files/interventi" non saprei individuare la causa del problema così ad occhio.

**Comment by beppe9000** [comment]
> Per quanto riguarda l'URL "modules/files/interventi" non saprei individuare la causa del problema così ad occhio.

Anche io avevo dato un'occhiata ma invano... per ora ho messo una regola nel htaccess come workaround...

>  Sembrerebbe che la funzione isHTTPS non resituisca il valore corretto.

Secondo me andrebbe usato direttamente il valore di `$redirectHTTPS` per decidere il protocollo...

**Comment by loviuz** [comment]
Dovrebbe essere risolto nella 2.4.14 in rilascio. Puoi provare con questo commit?
https://github.com/devcode-it/openstamanager/commit/6218a418f09930ad3b28be1260bb4025c75c11f6#diff-17c72034d8e419ebbc168e46f2523409
