### ISSUE TITLE
Errore di parsing di una data

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#771]
Ho trovato questo errore nel log. Sembra sia un errore di parsing su una data. Non so se è già risolto anche questo ma cercando "carbon" non mi trova nessun bug report.

la versione in questo caso è 2.4.11 (questa versone ha scritto il log) che poi ho aggiornato a 2.4.13 

```log
[2020-01-29 06:51:47] Logs.ERROR: DateTime::__construct(): Failed to parse time string (2) at position 0 (2): Unexpected character {"code":0,"message":"DateTime::__construct(): Failed to parse time string (2) at position 0 (2): Unexpected character","file":"/home/webuser/web/osm.example.com/vendor/nesbot/carbon/src/Carbon/Carbon.php","line":555,"trace":"#0 /home/webuser/web/osm.example.com/vendor/nesbot/carbon/src/Carbon/Carbon.php(555): DateTime->__construct('2', Object(DateTimeZone))
#1 /home/webuser/web/osm.example.com/src/Hooks/CachedManager.php(80): Carbon\Carbon->__construct('2')
#2 /home/webuser/web/osm.example.com/src/Hooks/CachedManager.php(17): Hooks\CachedManager::isCached()
#3 /home/webuser/web/osm.example.com/src/Models/Hook.php(51): Hooks\CachedManager->needsExecution()
#4 /home/webuser/web/osm.example.com/ajax.php(122): Models\Hook->execute('true')
#5 {main}"}

{"url":"/ajax.php?op=hook-execute&id=3&token=true","ip":"113.134.74.1","http_method":"GET","server":"osm.example.com","referrer":"https://osm.example.com/controller.php?id_module=1","unique_id":"XjEdcq5ti4BmEH9RDMRp9gAAAAc","uid":"5944447"} 
```

**Comment by Dasc3er** [comment]
Il problema sembra causato da un valore non valido presente a database. Controlla gli hook.

**Comment by beppe9000** [comment]
La cosa strana è che non vi ho mai messo mano, quindi dovrebbe essere tutto ai valori di default...

![image](https://user-images.githubusercontent.com/6625123/75776872-230ed780-5d55-11ea-8066-2b1718cb5dd2.png)

L'unica cosa che mi salta all'occhio è quel `7 day`...

**Comment by Dasc3er** [comment]
Potrebbe essersi trattato di un troncamento della data, ma per ora non saprei dirti come risolverlo...
Nella versione in sviluppo (2.4.14) è stato rivisitato il sistema di cache interno, quindi il problema potrebbe essere già stato risolto, ma non ti saprei dire come procedere.

**Comment by beppe9000** [comment]
Mi sembra che avessi cliccato il bottone per controllare gli aggiornamenti e non era uscito il risultato, poi ho cliccato di nuovo ed è uscito correttamente.

Questa cosa non sono riuscito a riprodurla, e penso che potrebbe anche essere stato un problema di rete o di [github](https://www.githubstatus.com/), che ne ha avuti diversi recentemente.

Per ora lascerei aperto, con due problemi segnalati che saranno probabilmente risolti con il rilascio della prossima versione:
 - errore nel nome degli hook per gli aggiornamenti, che risulta `Ricevute`
 - possibile troncamento della data nel sistema di cache

**Comment by Dasc3er** [comment]
Per il problema del nome dell'hook, è possibile che hai installato una versione in sviluppo nella quale è stato introdotto? Mi sembra che il funzionamento sia corretto con una installazione da zero...

**Comment by beppe9000** [comment]
Ho controllato meglio... colpa della versione 2.4.12
https://github.com/devcode-it/openstamanager/blob/v2.4.12/update/2_4_10.sql#L27-L28
