### ISSUE TITLE
Problema su Invio rapporto di intervento (2.4.13)

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#772]
Buongiorno,

segnalo quanto segue:

quando invio un rapporto di intervento e seleziono nelle stampe 'intervento', anzichè 'intervento (senza prezzi)', OSM invia comunque l'intervento senza prezzi.

Stessa cosa se li selezioni entrambi. OSM invia solo l'intervento senza prezzi.

Anche se non seleziono nulla... invia comunque l'intervento senza prezzi.

Sono loggato come amministratore. Il problema si manifesta indipendentemente dalle impostazioni interventi (Mostra prezzi al tecnico e stampa per anteprima e firma).

Grazie

* Modulo: Interventi
* Versione del progetto: 2.4.13 (93387381)
* Versione PHP: 7.1.33
* Tipo di server:

**Comment by Dasc3er** [comment]
@peropepero Grazie per la segnalazione!
In effetti il problema è stato piuttosto complicato da individuare ma semplice da risolvere.
Puoi trovare la soluzione qui: https://github.com/devcode-it/openstamanager/commit/2690f94d4d05d915e5140446fc592f682ec5d436
