### ISSUE TITLE
MIGLIORIA: accorpamento degli sconti nelle attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#773]
## Comportamento richiesto

Aggiungere gli sconti applicati nelle ore di lavoro (sconto km e sconto manodopera) nei totali riepilogativi a fondo pagina:
SCONTO SU TRASFERTA (tot_costi_trasferta)--->€ XXX,XX
SCONTO SU MANODOPERA (tot_manodopera) ---> € XXX,XX

## Comportamento attuale

Vengono riportati il totale costi di trasferta e il totale manodopera, ma poi se sono stati applicati degli sconti, questi non vengono visualizzati; il cliente non capisce dove sia stato applicato lo sconto

## Possibile soluzione

Inserire righe di riepilogo aggiuntive come da "Comportamento richiesto"

OSM 2.4.13

**Comment by Pek5892** [comment]
Nella versione corrente (2.4.46) gli sconti vengono gestiti in fase di riepilogo dei costi:
![immagine](https://github.com/devcode-it/openstamanager/assets/102604205/a2ac2f23-50d9-48b1-b7a3-eaf3452950ee)
