### ISSUE TITLE
BUG: Costi di trasferta da attività a fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#774]
## Comportamento attuale

Se nelle ore di lavoro di un'attività sono stati applicati sconti differenti, in fattura viene applicato lo sconto più alto sul totale "trasferta dell'intervento"

## Possibile soluzione

Riportare più righe (per es. trasferta del ..... - Trasferta del .....)
oppure riportare la media degli sconti applicato
oppure riportare il costo totale come valore unitario con lo sconto totale applicato

## Passi per riprodurre il comportamento

Creare un nuovo intervento
Inserire due righe "ore di lavoro" inserendo i km percorsi (per es. 30 nella prima e 40 nella seconda)
Inserire lo sconto km del 40% nella prima e il 30% nella seconda
Creare una nuova fattura e richiamare l'intervento

OSM 2.4.13

**Comment by Pek5892** [comment]
![immagine](https://user-images.githubusercontent.com/102604205/183382182-6b96d63e-8d18-4ffc-81f1-0f0d3b125f27.png)
Risolto nelle versioni successive alla 2.4.13
