### ISSUE TITLE
Scadenziario

### ISSUE THREAD

**Issue by widstudios** [devcode-it/openstamanager#775]
## Comportamento richiesto

Nella sezione scadenziario quando inserisco una scadenza generica mi da il prezzo e poi non mi fa salvare mi dice "Il totale da pagare deve essere pari a 0,00 €."
## Comportamento attuale

Nella vostra demo online funziona come vorrei inserisco importo e scadenza salvo e funziona 
## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.Apro scadenziario faccio +
2. Clicco tipo scegliendo scadenze generiche 
3.inserisco importo 
4.apre la schermata come scritto io e poi non mi fa salvare torna all'elenco me lo da ma se rientro non posso salvare se ho pagato

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:SCADENZIARIO
* Versione del progetto:2.4.13 (R93387381)
* Versione PHP: (7.2.27)
* Tipo di server:APACHE

**Comment by Dasc3er** [comment]
Ciao, hai controllato che il problema non corrisponda al seguente?
https://github.com/devcode-it/openstamanager/issues/764
Nel caso puoi trovare la soluzione nel commit collegato...
