### ISSUE TITLE
Nuova tipologia anagrafica “Produttore”

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#777]
Potrebbe essere utile introdurre una nuova tipologia di anagrafica “Produttore” da associare all’articolo come già avviene per “Fornitore”

**Comment by Dasc3er** [comment]
Quali sarebbero i ruoli di questa tipologia?

**Comment by lucasalva87** [comment]
Per il momento l'unica applicazione sarebbe quella di poterla selezionare associandola ad un articolo

**Comment by Pek5892** [comment]
Issue duplicata https://github.com/devcode-it/openstamanager/issues/1065
