### ISSUE TITLE
Controllo pulsanti "Ultimo prezzo" per Articoli

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#779]
## Comportamento richiesto

Controllare che i pulsanti "Ultimo prezzo di acquisto" e simili presentino un funzionamento corretto.

Forum: https://forum.openstamanager.com/viewtopic.php?f=10&t=95172&p=103472#p103472

**Comment by lucasalva87** [comment]
Questo perchè attualmente gli ultimi prezzi di acquisto / vendita vengono presi interrogando unicamente la tabella co_documenti e quindi recuperando le informazioni dalle sole fatture, non ddt
