### ISSUE TITLE
FATTURE - Possibilità di inserire una riga descrittiva 

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#78]
Nei documenti formati da righe, per una migliore lettura della stampa, sarebbe utile poter inserire delle righe descrittive senza valori nelle colonne quantità/prezzo/importo/iva
![image](https://user-images.githubusercontent.com/34273200/34074668-7f816f1e-e2b4-11e7-8baa-cccdbaa8af99.png)

**Comment by loviuz** [comment]
@fpsoftware, @lucasalva87: ha senso mettere in release secondo voi?
perché attualmente si potrebbe inserire a capo di una riga i trattini come l'esempio. oppure inseriamo un altro tasto "+ note" dove non si mettono importi e quindi non escono in stampa.

**Comment by fgambarelli** [comment]
L'esigenza che mi hanno segnalato è proprio di una riga "nota", senza importi e quantità, ma che esca in stampa

**Comment by Dasc3er** [comment]
@fgambarelli, la riga "nota" non potrebbe essere convertita alla sezione "Note" già prevista dalla stampa?
Perchè in questo caso basterebbe aggiungere il testo che si vuole mostrare nella stampa nel campo "Nota" della fattura...
![screenshot-2017-12-17 fattura_pro-11 pdf - pdfgen php](https://user-images.githubusercontent.com/15911489/34078550-dcb07618-e31c-11e7-96c3-7761cb4f69d2.png)

**Comment by fgambarelli** [comment]
Le sto già usando queste note, quando sono riferire a tutta la fattura , vedi esempio.
![image](https://user-images.githubusercontent.com/34273200/34078679-5d96b5e2-e31f-11e7-8f33-7163262bfc02.png)

Ho visto anche le note aggiuntive sull'IVA, la riga "Note" è una riga che permette di spiegare meglio ed organizzare meglio la tabella delle righe di fattura.
Riporto Esempio :
CALDAIA COMPOSTA DAI SEGUENTI ARTICOLI:
- ARTICOLO 1
- ARTICOLO 2
---------------------------
La prima riga deve stare nella fattura, perchè spiega gli articoli sotto elencati

**Comment by fpsoftware** [comment]
É capitata anche a me una richiesta simile, si puó mettere in release.
Una soluzione banale potrebbe essere modificare solo la stampa, lasciando vuote le colonne q.ta, importo unitario, etc se la q.ta ed il prezzo sono a zero, la riga generica diventa quindi una riga nota, trucco che però va spiegato agli utenti, altrimenti si dovrebbe aggiungere un ulteriore "+Riga note" che inserisce solo il campo descrizione e lascia a zero gli altri campi.
Fatto per le fatture di vendita potrebbe servire anche sui ddt

**Comment by loviuz** [comment]
se mettiamo un flag, la popup di inserimento e modifica potrebbe uscire solo con la descrizione, così da far meno confusione all'utente. può essere che poi arrivi la richiesta di un utente che vuole mostrare una riga con importo a 0€ 😅

**Comment by fgambarelli** [comment]
Credo che il flag sulla riga possa essere una risposta per fare in modo che l'utente esigente scelga ed abbia entrambe le possibilità. 
A questo unisco una richiesta simile (non so se è corretto il luogo, ma è una proposta di miglioria) : poter decidere se stampare o no, in alcuni casi, i codici degli articoli in fattura. Esigenza nata dal fatto che per alcuni clienti non vogliono mostrare i codici dei pezzi venduti, utilizzando in anagrafica articoli i codici dei fornitori.

**Comment by loviuz** [comment]
bd7b95c93b05e851eb038f407dfa27fc412255bb
