### ISSUE TITLE
Problema Maggiorazioni in Fattura Elettronica

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#780]
Come segnalato sul forum, all'inserimento di uno ScontoMaggiorazione i valori nel caso delle maggiorazioni possono assumere segno negativo per la mancanza di un abs.

Riga di riferimento: https://github.com/devcode-it/openstamanager/blob/7e758d9e23b9f11306f8b5e3ebef5aab89d4bb8a/plugins/exportFE/src/FatturaElettronica.php#L1202

Forum: https://forum.openstamanager.com/viewtopic.php?p=103477&sid=4ed3ef4b030507fbd46532393c594b47#p103477

**Comment by lucasalva87** [comment]
Grazie Thomas per aver riportato la segnalazione, credo che sia effettivamente un bug.
Il nodo 2.2.1.10.2 infatti non dovrebbe riportare valori negativi ma sempre assoluti.
Se poi si tratta di uno sconto e una maggiorazione lo si evince dal nodo 2.2.1.10.1 dove si specifica rispettivamente SC o MG.
