### ISSUE TITLE
Uploading multiple files come allegato per impianti nella stessa categoria

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#781]
## Comportamento richiesto

Possibilità di caricare più files con un unico upload negli allegati degli impianti quando appartenenti alla stessa categoria; es. documento1 e documento2 nella categoria x in un solo upload.

## Comportamento attuale

Attualmente bisogna fare n upload tanti quanti sono i files della stessa categoria da caricare; Possibilità di selezionare da 1 a n files, un'unica categoria e caricarli tutti.

**Comment by Dasc3er** [comment]
La modifica è completata e disponibile in release recenti grazie all'introduzione di Dropzone e la revisione del sistema di caricamento degli allegati.

**Comment by antoniotrapasso** [comment]
Ciao come posso fare per avere questa funzionalità senza aggiornare l'intero software? ho fatto delle modifiche in modo anche non conforme mi rendo conto rispetto a quanto da voi indicato affinché un eventuale aggiornamento non impatti sulle customizzazioni. Che parte di codice/file/cartelle devo sostituire?

Grazie mille e complimenti
