### ISSUE TITLE
Campo upload files in componenti impianto 

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#782]
## Comportamento richiesto

Possibilità di caricare un file legato al componente di un impianto.

## Comportamento attuale

Non esiste la possibilità di fare upload di file per un componente impianto.

**Comment by Pek5892** [comment]
Ciao @antoniotrapasso, questa funzionalità è stata introdotta nella versione 2.4.24
https://docs.openstamanager.com/v/2.4.34/openstamanager/modules/impianti/plugin/componenti-1
