### ISSUE TITLE
Gestione permessi: consentire ad utente l'accesso ad un solo progetto o più progetti

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#783]
## Comportamento richiesto

consentire ad un utente creato l'accesso da 1 a n progetti/impianti;

## Comportamento attuale

attualmente si può limitare la macro sezione es. impianti ecc.. Rendere più approfondito il controllo ad esempio facendo accedere alla sezione impianti ma solo ad uno o più di essi.

**Comment by Dasc3er** [comment]
Puoi effettuare l'operazione relativa tramite una personalizzazione o un filtro SQL aggiuntivo.
Non è prevista neanche per il futuro l'introduzione di permessi specifici ai singoli record, compresi gli impianti.

**Comment by antoniotrapasso** [comment]
Per filtro SQL aggiuntivo intendi creare una query per la vista impianti attraverso la quale filtrare gli utenti? Per applicare questa soluzione dovrei aggiungere preventivamente un campo alla tabella utenti del tipo "Impianto abilitato" se cardinalità 1:1 oppure "Impianti abilitati" se cardinalità 1:N? Oppure mi suggerisci una soluzione più veloce?
Grazie

**Comment by Dasc3er** [comment]
Dipende molto da cio che vuoi filtrare, e non credo serva aggiungere nuovi campi.
Purtroppo devi ragionare personalmente sul funzionamento, se hai bisogno puoi acquistare un pacchetto di assistenza.
