### ISSUE TITLE
Giacenze per sedi

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#784]
Con lo spostamento degli automezzi nelle sedi è stata rimossa una funzionalità molto utile, ossia quella di poter vedere per ogni automezzo il contenuto, cioè la lista articoli. L'ideale sarebbe creare un modulo sotto "Magazzino" chiamato "Giacenze" e fare in modo che entrandoci si possa scegliere una sede e al click vedere gli articoli presenti con relative quantità, deducendolo dal calcolo dei movimenti.

@lucasalva87 @Dasc3er che ne pensate?

**Comment by lucasalva87** [comment]
Sì, e si potrebbe potenziare il plugin sedi delle anagrafiche introducendo un flag "automezzo". Una volta definita che quella è una sede "mobile" possiamo aggiungere altri dettagli come la targa o il tecnico responsabile (esattamente com'era prima della rimozione del modulo automezzi).

**Comment by Dasc3er** [comment]
E' sbagliato avere le sedi mobili, perchè non sono sedi in quel caso ma automezzi.
Se necessario bisogna ripristinare il modulo originale con gli automezzi.

E' però una buona idea utilizzare un plugin/modulo per gestire le giacenze nelle sedi.

**Comment by loviuz** [comment]
Pensavamo di aggiungere un flag alle sedi per indicare che le sedi con il flag attivo sono utilizzabili per la movimentazione merci, quindi sia magazzini che automezzi. Attenzione che potrei abilitare una sede per ricevere merci ed essere usata quindi come sede di partenza o destinazione, e rimuovere il flag successivamente, non vedendo più quindi la sede selezionabile nei vari menu a tendina ma senza perdere questa informazione in documenti dove è già stata utilizzata.

Per retrocompatibilità, il flag dovrebbe essere attivo a tutte le sedi già esistenti per chi effettua un aggiornamento.

Per nuove sedi lo proporrei già settato, rimuovibile dall'utente.

Tutto questo però non sarebbe possibile farlo per la "Sede legale" che ora è una sede fittizia, per cui lo andrei a gestire con la creazione (finalmente) della sede legale come una sede qualsiasi, quindi con il proprio record in an_sedi. Meglio dalla 2.4.15. Probabilmente sarebbe più sensato rinominare "Sedi" in "Ubicazioni" così da renderlo più generico in modo che vengano considerate sia sedi fisiche che mobili (automezzi).

@Dasc3er che ne pensi?

**Comment by Dasc3er** [comment]
Suggerisco di sviluppare la 2.5 per aggiornare il gestionale e per avere la sede legale già separata.
Inoltre sconsiglio l'utilizzo di una sede come automezzo, ma certamente può essere utilizzata come sistema di giacenze.

**Comment by lucasalva87** [comment]
Sono d'accordo con quanto definito sopra, unica cosa, ragionandoci meglio, non trovo corretto rinominare "Sedi" in "Ubicazioni". Anche perché finora le sedi venivano intese come uffici quando si parlava di ente pubblico, infatti c’è la possibilità di definire un codice destinatario.
Questo forse ci può aiutare a fare un po' di chiarezza: http://www.registroimprese.it/sede-legale-e-unita-locali 
Quindi ci sarà sempre obbligatoriamente 1 “Sede legale”, 1 o più “Sedi operative” (luogo dove viene effettivamente svolta l'attività imprenditoriale che può coincidere con la “Sede legale”), ed infine eventuali n “Localizzazioni” aperte dopo la “Sede legale” le quali possono essere di due tipi:

- Unità locale (es. laboratorio, officina, stabilimento, negozio, eccetera) o amministrativo/gestionale (es. ufficio, magazzino, deposito, eccetera), ubicato in luogo diverso da quello della sede legale, nel quale l’impresa esercita stabilmente una o più attività economiche. 
Una unità locale può essere: “Attiva”, “Chiusa”, “Inattiva”. Quest’ultima in particolare quando si tratta di mero magazzino che contribuisce al processo produttivo che però si svolge altrove
- Sede secondaria (Sede diversa dalla legale)

Concludo, dicendo che forse avrebbe più senso a questo punto vedere gli automezzi come entità separate in quanto molte delle informazioni inserite per la sede non sarebbero proprie (es. codice destinatario, indirizzo, città ecc…).

**Comment by Dasc3er** [comment]
Una cosa che può essere utile inoltre per il ragionamento delle giacenze: con la versione 2.5 si iniziano ad usare gli oggetti in molti più punti del gestionale rispetto a ora, in modo simile a quanto già introdotto per i riferimenti tra righe dei documenti.
Può essere utile generalizzare con una struttura definitiva a livello di codice, come un'interfaccia, che preveda l'interazione con il magazzino. Si può quindi procedere a sostituire la gestione delle giacenze tramite idsede con il corrispettivo delle classi, in modo da supportare anche altri elementi (automezzi, impianti, sedi o quel che si vuole).

**Comment by Pek5892** [comment]
Aggiunto modulo Automezzi nella versione 2.4.52
