### ISSUE TITLE
Miglioramento evasione contratti e preventivi

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#788]
## Comportamento richiesto
Quando un intervento è collegato ad un contratto (o preventivo), di default non facciamo fatturare l’intervento perché si presume che sia compreso a contratto (o a preventivo), ma ormai diversi clienti creano il contratto per far pagare le attività eseguite all'interno del contratto, per cui il comportamento standard di OpenSTAManager è troppo rigido e non flessibile. Ci sono dei casi abbastanza flessibili, di questo tipo:

Contratto 010/2019, cliente Mario Rossi, contenente (come righe):
- 10 ore
- 3 articoli
- fatturazione: non fatturo alcun intervento perché sono incluse sia ore che materiale

Contratto 011/2019:

- 10 ore
- fatturazione: fatturo solo gli articoli presenti negli interventi, perché non era prevista nessuna fornitura di materiale

Contratto 012/2019:

- 3 articoli
- fatturazione: fatturo tutte le ore di lavoro, niente articoli perché previsti nel contratto

Contratto 013/2019:

- no ore, no articoli (magari alcune righe generiche)
- fatturazione: fattura sia le ore che gli articoli

Queste sono diverse combinazioni da gestire che sono state richieste nel tempo.
La stessa logica andrebbe applicata anche ai preventivi, anche se solitamente un preventivo si presuppone sia solo un’offerta per fatturare quanto si è previsto, ma per semplicità si possono uniformare contratti e preventivi.

**Comment by Pek5892** [comment]
Dalla v.2.4.40 aggiunta impostazione per abilitare la fatturazione di interventi collegati a documenti: https://github.com/devcode-it/openstamanager/commit/7b53d2a1b76a26a6e2b578712f66d63876db8a29
