### ISSUE TITLE
ANAGRAFICA - Indirizzo di fatturazione non propone le sedi presenti

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#79]
Credo sia il medesimo problema di ambiguità nella query per l'individuazione delle sedi filtrate, in un cliente esistono due ulteriori sedi
![image](https://user-images.githubusercontent.com/34273200/34078401-fd600714-e319-11e7-8f4f-925ee76df542.png)

ma nella scelta dell'indirizzo di fatturazione non vengono proposte
![image](https://user-images.githubusercontent.com/34273200/34078404-0efa95e8-e31a-11e7-840f-f28a053f5872.png)

**Comment by Dasc3er** [comment]
Ciao @fgambarelli ,
questo bug era causato da una query impostata male, su cui non veniva inserito l'identificativo dell'anagrafica (simile al problema di ambiguità, ma non identico :D).

Dovrebbe essere stato risolto con il commit d6d06029351b91a13dffd625c82b4d0094a78861.
Grazie per la segnalazione!
