### ISSUE TITLE
2.4.14 - Modulo Viste: non è possibile eliminare i campi

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#794]
Come da oggetto, cliccando su 'Elimina' non si apre il popup di conferma.

Per eliminare una vista personalizzata creata con una versione precedente e che mi dava problemi con la 2.4.14, ho dovuto cancellarla in zz_wiews.

Differentemente dalle versioni precedenti, il pulsante 'Elimina' è presente in tutti i campi

* Modulo: Viste
* Versione del progetto: 2.4.14
* Versione PHP: 7.1.33

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione!
Il problema dovrebbe essere risolto con il commit precedente, era causato dalla rimozione di un'impostazione avanzata.
