### ISSUE TITLE
Gestione avanzata stampe

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#8]
Creazione dei modelli di stampa su database, con possibilità di creare più stampe per modulo e raggruppate in un'unica voce di menu.

**Comment by Dasc3er** [comment]
Al momento lo sviluppo nella branch 2.4 ha completato le seguenti sezioni:

- Registrazione delle stampe nel database;
- Gestione dinamica (attraverso il campo `options`) delle impostazione di base (tra cui la visualizzazione del prezzo);
- Creazione dinamica di un menu a tendina per mostrare tutte le stampe disponibili per un singolo modulo;
- Creazione personalizzata di un pulsante per una singola stampa specificata tramite nome (in modo simile all'identificazione a livello di programmazione dei moduli).

**Comment by Dasc3er** [comment]
Potrebbe essere inoltre utile permettere di abilitare/disabilitare la presenza di header e footer all'interno di tutte le pagine delle stampe tramite un'opzione specifica.

Caso default: header e footer presenti in ogni pagina (come è funziona attualmente).
Casi alternativi:
- header nella prima pagina e footer nell'ultima pagina 
- header in tutte le pagine e footer nell'ultima pagina 
- header  nella prima pagina e footer in tutte le pagine

@loviuz @fpsoftware @lucasalva87 Permettere questa configurazione avrebbe una qualche utilità?

**Comment by fpsoftware** [comment]
potrebbe essere utile, anche se il lavoro necessario per la modifica di tutte le stampe mi sembra eccessivo rispetto alle volte che si renderà utile questa opzione.
Inoltre ci dovrebbe essere questa opzione per ogni stampa in quanto ci può essere questa necessità solo su alcune stampe specifiche.

**Comment by Dasc3er** [comment]
Sarebbe implementabile in modo più rapido con la gestione delle stampe disponibile dalla versione 2.4, e in particolare con la nuova struttura...
Quanto all'opzione si potrebbe rendere disponibile qualcosa di generico nelle impostazioni e poi, per la relativa personalizzazione, procedere con le nuove opzioni specifiche per le stampe.
