### ISSUE TITLE
FATTURE - Nella stampa fattura, non viene visualizzato il bollo nel modello

### ISSUE THREAD

**Issue by atmarven** [devcode-it/openstamanager#80]
Se nelle impostazioni viene attivato il limite bollo, il programma in fase di generazione fattura lo calcola, ma in stampa non viene visualizzato

**Comment by Dasc3er** [comment]
Ciao @atmarven,
grazie per la segnalazione!

Potresti dare un'occhiata alla issue #73 per controllare che  questa mancanza non sia stata già risolta?
