### ISSUE TITLE
Esclusione mesi per il calcolo Scadenze

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#802]
## Comportamento richiesto

Per ogni Anagrafica può essere utile la sezione di mesi da escludere nel calcolo delle relative scadenze contabili. Per esempio, alcune aziende non effettuano mai pagamenti ai fornitori ad agosto o dicembre, per cui la scadenza calcolata slitterebbe al mese subito successivo.
Si potrebbe fare un'impostazione nella quale di default ogni anagrafica ha selezionati tutti i mesi e si toglie la spunta per i mesi non disponibili. L'impostazione potrebbe chiamarsi "Mesi in cui questa azienda può effettuare i pagamenti", valido sia per fornitore che per cliente.

E' importante notare che la richiesta considera mesi, e non periodi indipendenti. Il comportamento previsto richiede che tutte le scadenze dei mesi in cui sono chiuse vengono posticipate esattamente del numero di mesi corrispettivo.
Per esempio, se le fatture di Agosto devono essere posticipate al mese di Settembre, una fattura del 10 Luglio con scadenza a 30gg deve prevedere data di scadenza al 10 di Settembre.

Per escludere settimane specifiche (come vacanze di Natale o simili), la procedura deve essere gestita manualmente dall'utente.

**Comment by lucasalva87** [comment]
Sì, esatto. Oppure si può chiamare "Mesi utili per il calcolo dei pagamenti". Valutare se ha senso farla come impostazione per ogni singolo cliente o fornitore. Oppure prevederlo a livello di metodo di pagamento. Es. bonifico bancario 30 gg.. e nel campo "Mesi utili per il calcolo dei pagamenti" definisco quali mesi tenere in considerazione. Di default è sempre selezionato tutto.
