### ISSUE TITLE
Eliminare stato attività CALL

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#803]
Valutare di eliminare stato attività CALL che non ha un utilizzo pratico.

**Comment by loviuz** [comment]
Rimozione se non usata? Potrebbe andare. Era un vecchio stato di default di cui sinceramente non ricordo e non ne vedo particolare utilità

**Comment by lucasalva87** [comment]
@Dasc3er tu cosa ne pensi?

**Comment by Dasc3er** [comment]
Propongo di introdurre un campo deleted_at ed evitare la rimozione completa dello stato.

**Comment by lucasalva87** [comment]
Da nostre esperienze viene utilizzato veramente poco, possiamo introdurre il campo deleted_at e settarlo con valore diverso da NULL se non usato.

**Comment by Dasc3er** [comment]
Rimosso a partire dalla versione 2.4.17.
