### ISSUE TITLE
Potenziamento promemoria con info del tecnico che seguirà la richiesta

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#804]
In fase di creazione promemoria (dunque un'attività senza tecnico e con orario inizio e orario fine non definite) sarebbe utile poter prevedere chi dovrà prendere in carico la richiesta. L'idea è introdurre un nuovo campo "Tecnico assegnato" così da definire chi vedrà i promemoria a destra della dashboard.
Va allineato con la stessa logica anche il widget "Promemoria attività da pianificare."
Pensavo ad un nuovo campo id_tecnico nella tabella in_interventi.

**Comment by Dasc3er** [comment]
Intendi i promemoria di contratti? Perché in quel caso si tratta di co_promemoria.

**Comment by lucasalva87** [comment]
No, non quelli dai contratti. Quelli semplici aperti con il tasto + da attività.

**Comment by loviuz** [comment]
Forse conviene poter associare più tecnici visto che ci siamo...

**Comment by lucasalva87** [comment]
Vanno bene anche più tecnici. L’obbiettivo è quello di pre-assegnare i promemoria affinché il tecnico o uno dei tecnici designati lo prenda in carico.

**Comment by Dasc3er** [comment]
Quindi è da prevedere una nuova tabella, **in_interventi_tecnici_assegnati**, che permette di definire una relazione 1-n tra i tecnici e le attività proprio a questo fine.
Non ha senso prevedere una modifica a **in_interventi_tecnici** che renda impossibile utilizzare la tabella in modo coerente con il funzionamento attuale.

**Comment by lucasalva87** [comment]
Introdurre impostazione nella sezione "Dashboard" per consentire ai tecnici di vedere a destra del calendario solo le proprie attività a cui sono stati assegnati oppure vedere anche quelle degli altri tecnici.

**Comment by Dasc3er** [comment]
Funzionalità completata per la versione in sviluppo (2.4.18)
