### ISSUE TITLE
Errore in fase di caricamento immagine nella scheda articolo

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#808]
Provando a caricare un file con estensione tiff o altro formato diverso da JPG, PNG, GIF. viene restituito questo errore.

![Articoli   OpenSTAManager](https://user-images.githubusercontent.com/30728163/80734527-96438880-8b0f-11ea-9338-2dc713c5cec3.jpg)

**Comment by Dasc3er** [comment]
Possiamo utilizzare questa pagina come riferimento ai formati supportati come immagini, per la gestione delle immagini di dimensioni ridotte: http://image.intervention.io/getting_started/formats

**Comment by Dasc3er** [comment]
@lucasalva87 Ho risolto aggiungendo un controllo sui soli formati funzionanti nella generazione delle immagini di dimensione più piccola, e inoltre ho limitato le immagini caricabili poichè la maggior parte dei browser supporta solo alcuni formati.
Le TIFF in particolare non sono supportate da nessuno.

**Comment by lucasalva87** [comment]
Perfetto, va benissimo così. Provato e funziona. 👍
