### ISSUE TITLE
Backup non presente nonostante flash eseguito correttamente

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#809]
Ciao a tutti.
Ho notato che da qualche gg osm non esegue più il backup automaticamente al primo accesso nonostante il setting lo preveda. Quello che noto è che l'ultimo backup pesa 1.99 GB. È questione di setting? C'è qualche limite? Cosa posso fare? Grazie mille

**Comment by Dasc3er** [comment]
Versione del gestionale?
Le dimensioni sono corrette?
Ci sono errori nei log?

**Comment by antoniotrapasso** [comment]
"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS nome_tecnico, (SELECT colore FROM an_anagrafiche WHERE idanagrafica=idtecnico'

**Comment by Dasc3er** [comment]
@antoniotrapasso La risposta alle altre domande?

**Comment by antoniotrapasso** [comment]
Si scusa,,,
versione 2.4.10 
per quanto riguarda le dimensioni: i backup esistenti sono correttamente eseguiti e la dimensione dei file .zip è corretta. Si compattano anche correttamente.
Grazie
Ciao

**Comment by antoniotrapasso** [comment]
*si scompattano correttamente

**Comment by Dasc3er** [comment]
Il problema potrebbe essere causato da un esaurimento dello spazio disponibile oppure da permessi sulle cartelle?
Posso confermare che il servizio di backup automatico funziona correttamente, malgrado sia riuscito a testarlo sull'ultima versione disponibile.

**Comment by antoniotrapasso** [comment]
spazio ce n'è a sufficienza;
per i permessi ci avevo pensato anche io ma ho dato qualsiasi permesso come everyone  e niente.
Perché il log si riferisce ad una specifica query?
grazie

**Comment by antoniotrapasso** [comment]
confermo: il problema è la dimensione massima del bck pari a 2GB.
Ho un altro ambiente di test identico in tutto se non per il contenuto (meno files allegati e di conseguenza minor spazio) ed ha effettuato correttamente il backup. Ho fatto anche una contro prova: ho aggiunto all'ambiente di test (il cui peso del bck era circa 1.8GB) 300MB di files ed il backup è fallito.

**Comment by Dasc3er** [comment]
È possibile che questo sia un problema di PHP che limita le dimensioni del file...
Da verificare, ma purtroppo dubito sarà risolto nel breve periodo. Posso consigliarti di disabilitare la creazione del file zip, ma potrebbe essere abbastanza complesso come procedimento.

**Comment by antoniotrapasso** [comment]
Sì è una limitazione di PHP. Cercherò di modificare il codice per splittare l'unico file in più file di dimensioni inferiori a 2 gb

**Comment by Dasc3er** [comment]
@antoniotrapasso Puoi invece provare a disabilitare la creazione dell'archivio ZIP aggiungendo una negazione nella seguente riga:
https://github.com/devcode-it/openstamanager/blob/8706efd6c9ce0554c8addeb1eb8a1a4bb80d249f/src/Backup.php#L159

Questo permette di continuare con i backup, che verranno effettuati in una cartella piuttosto che in un archivio zip.

**Comment by antoniotrapasso** [comment]
Fatto. Funziona! 
molto più facile così.. 

Grazie mille! 

ciao 

Ing. Antonio Trapasso 
Cell. +39 392 94 78 917 
Responsabile Area Infrastrutture & Reti 



Sinapsys s.r.l. 
Sede Legale: Via Padre Semeria 65 - 00154 Roma (RM) 
Sede Operariva: Via S.Giuseppe Moscati, 3 - 88068 Soverato (CZ) 
Tel. +39 0967 22427 - Fax +39 0967 520630 
e-mail: info@sinapsys.it 
pec: sinapsys@certificatamail.it 
web: www.sinapsys.it 



Da: "Thomas Zilio" <notifications@github.com> 
A: "devcode-it/openstamanager" <openstamanager@noreply.github.com> 
Cc: "antoniotrapasso" <a.trapasso@sinapsys.it>, "Mention" <mention@noreply.github.com> 
Inviato: Domenica, 3 maggio 2020 15:14:57 
Oggetto: Re: [devcode-it/openstamanager] Backup non presente nonostante flash eseguito correttamente (#809) 






@antoniotrapasso Puoi invece provare a disabilitare la creazione dell'archivio ZIP aggiungendo una negazione nella seguente riga: 
https://github.com/devcode-it/openstamanager/blob/8706efd6c9ce0554c8addeb1eb8a1a4bb80d249f/src/Backup.php#L159 

Questo permette di continuare con i backup, che verranno effettuati in una cartella piuttosto che in un archivio zip.

**Comment by antoniotrapasso** [comment]
fatto funziona!

grazie

**Comment by cigo76** [comment]
come aggiungo la negazione?

**Comment by antoniotrapasso** [comment]
Io ho risolto semplicemente così:
if (!extension_loaded('zip')) { ...

**Comment by cigo76** [comment]
Ho provato ma a me non funziona, genera il file zip ma con nessun file salvato!!

Cmq il mio problema e' questo:

Con il php 7.4 mi da il seguente errore:
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Con php 7.3 questo problema non sussiste!!

**Comment by Dasc3er** [comment]
@cigo76 Di conseguenza il tuo problema non corrisponde con quello della issue.
Ti consiglio di controllare nuovamente se ci sono errori nei file di log di OpenSTAManager oppure di Apache, e di utilizzare o il post sul forum oppure una nuova issue qui su GitHub.

**Comment by Dasc3er** [comment]
Riferimento utile per un futuro tentativo di soluzione del problema: https://stackoverflow.com/a/22638907
