### ISSUE TITLE
Aumento dimensioni campo Descrizione per Articoli

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#811]
## Comportamento richiesto

Può essere utile la trasformazione del campo **descrizione** per gli Articoli in un campo di tipo TEXT, come previsto per le righe generali dei documenti. In questo contesto può essere di interesse l'inserimento di un nuovo campo, **nome**, che assume il ruolo attuale della descrizione con un limite di 255 caratteri.
Il campo nome verrebbe utilizzato nei select al posto della descrizione.

Forum: https://forum.openstamanager.com/viewtopic.php?f=1&t=95212

@loviuz @lucasalva87 Cosa ne pensate?

**Comment by lucasalva87** [comment]
Concordo, ne discutevamo giusto un mesetto fa e l'esigenza era la medesima:

1. nelle vendite la descrizione dell'articolo dovrebbe essere il più dettagliata possibile
2. negli acquisti si poteva optare invece per una descrizione più sintetica

**Comment by Dasc3er** [comment]
@lucasalva87 La modifica sarebbe più ridotta di quella da te indicata.
A partire della versione 2.4.16, è possibile personalizzare la descrizione degli articoli per i documenti di acquisto sulla base del fornitore, con il nuovo sistema di associazione tra articoli e fornitori.
Quello che invece propongo in questa issue è diverso: il campo descrizione attuale diventa lungo a piacere, e mantiene il funzionamento attuale. Per semplificare la ricerca e la navigazione tra gli articoli, si potrebbe introdurre un campo **nome** che riassume il contenuto dell'articolo in 255 caratteri (per esempio, nei select).
Per retro-compatibilità il campo nome sarebbe impostato inizialmente uguale alla descrizione.

**Comment by lucasalva87** [comment]
La soluzione da te proposta per me va bene. Standardizzeremo così anche il modulo dato che spesso troviamo questo binomio nome-descrizione. @loviuz che ne pensa?
