### ISSUE TITLE
Problema importazione file P7M

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#812]
Sto provando a importare una fattura elettronica di acquisto.
Il formato è P7M.
Mi viene restituito "Errore durante l'apertura della fattura elettronica IT***********_S9SoS.xml"

Ho cercato su internet e sembra che sia un problema legato a un comando di openssl.

Se è utile questo è il link [https://forum.italia.it/t/problema-decodifica-fattura-elettronica-p7m-di-e-distribuzione/12258](url)

**Comment by Dasc3er** [comment]
Abbiamo implementato tempo fa un sistema che sembrava funzionare con i file p7m.
Che versione stai utilizzando? 
Sei sicuro che non sia il file a essere corrotto?

In ogni caso, dubito possiamo aiutarti nel breve periodo.

**Comment by idraulicadueci** [comment]
Ti ringrazio, ma questo è un problema che molti riscontrano con un fornitore di energia elettrica. Comunque se può essere utile, ho risolto convertendo online il file in formato XML e poi lo ho importato. Al momento tutti gli altri file P7M sono stati importati senza errori.

**Comment by Dasc3er** [comment]
@idraulicadueci Non abbiamo modo di risolvere il problema direttamente senza il file che lo causa, che oltretutto non ti consiglio di distribuire a causa dei contenuti personali. Inoltre sono piuttosto sicuro che abbiamo implementato una serie di operazioni conformi al sistema per l'estrazione dell'XML dal file P7M.

Posso solo consigliarti di procedere in modo simile a come hai già fatto se il problema si verificasse di nuovo.
Se invece hai tempo a disposizione e un po' di esperienza con PHP, sei il benvenuto per contribuire con una soluzione diretta al problema.
