### ISSUE TITLE
Problema Backup con php7.4

### ISSUE THREAD

**Issue by cigo76** [devcode-it/openstamanager#813]
Salve,
su versione osm 2.4.15. con php7.4  quando creo un Backup si blocca IL WEBSERVER con questo errore:
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Il log php mi da questi errori:

[Fri May  08 11:46:16.262610 2020] [proxy_fcgi:error] [pid 27348:tid  140572333438720] [client 93.147.251.97:0] AH01067: Failed to read  FastCGI header, referer:  https://www.miosito.it/osm/controller.php?id_module=7"
--
[Fri May 08 11:46:16.262664 2020] [proxy_fcgi:error] [pid  27348:tid 140572333438720] (104)Connection reset by peer: [client  93.147.251.97:0] AH01075: Error dispatching request to : , referer:  https://www.miosito.it/osm/controller.php?id_module=7"

Con php 7.3 funziona tutto alla perfezione

Saluti

**Comment by Dasc3er** [comment]
@cigo76 CI sono altri errori oltre a questi?
In particolare ci interessano **Fatal error** di PHP, e non i log esclusivamente di apache.

**Comment by Dasc3er** [comment]
Chiuso per assenza di informazioni.
