### ISSUE TITLE
Problema di duplicazione codice articolo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#814]
## Comportamento attuale

Se duplico un articolo senza variare il codice, mi ritrovo nel database 2 articoli duplicati

## Possibile soluzione

Inserire un controllo sul codice che eviti la duplicazione

## Passi per riprodurre il comportamento

- Aprire un articolo.
- Cliccare su DUPLICA ARTICOLO
- Salvare

OSM 2.4.15

**Comment by Dasc3er** [comment]
Tecnicamente non si tratta di un errore o un problema, quanto una funzionalità della duplicazione...

@lucasalva87 @loviuz Come proponente di risolvere, se di interesse?

**Comment by lucasalva87** [comment]
Si potrebbe pensare di duplicare tutto tranne il codice che rimarrebbe vuoto o introdurre una modal intermedia che permetta di definire il codice prima di procedere alla duplicazione.

**Comment by Dasc3er** [comment]
Grazie per il suggerimento!
La modifica è stata implementata con una modal aggiuntive che permette di personalizzare le scelte relative alla duplicazione.
