### ISSUE TITLE
Promemoria Note - Permanenza nel widget dopo data impostata

### ISSUE THREAD

**Issue by peropepero** [devcode-it/openstamanager#816]
Se assegno ad una 'Nota' una data di notifica potrò visualizzarla nel widget nella data impostata, ma già il giorno seguente non sarà più visibile.

In questo modo se il motivo per il quale viene inserita la notifica non viene espletato, c'è il rischio che non lo sarà mai, a meno di imbattersi per caso nel record del modulo dove è stata creata la nota.

Credo che possa essere utile a tutti un promemoria che permanga nel widget fintanto che non viene eliminato dall'utente, in modo da poter gestire la nota evitando di dimenticarsene.

In alternativa o in affiancamento a quanto sopra, potrebbe essere utile un elenco delle note con evidenziata la data di eventuali promemoria, ponendo magari in rosso quelle scadute.

Grazie per l'attenzione

* Modulo: qualsiasi modulo con Plugin 'Note'
* Versione del progetto: 2.4.13
* Versione PHP: 7.1.33

**Comment by Dasc3er** [comment]
Se di interesse, la funzionalità dovrebbe essere stata richiesta anche nel forum: https://forum.openstamanager.com/viewtopic.php?p=104257#p104257
Qui è indicata una fix fatta dall'utente al riguardo.
