### ISSUE TITLE
BUG: Problema di riporto sconti da attività a fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#817]
## Comportamento attuale

Uno sconto % indicato nelle ore di lavoro, viene riportato in fattura in €. Fra l'altro lo sconto viene moltiplicato per la quantità e detratto dell'importo totale.
Per esempio se il costo a km è di € 1,00 e ho percorso 10 km e applico uno sconto del 100%, il sistema fa il seguente calcolo:
(-100x10)+(1x10)= -900
(non ho testato se lo stesso avviene per le altre voci di spesa come articoli e spese accessorie).

## Passi per riprodurre il comportamento

1. Creare un'attività con un tot di ore di lavoro e un tot di km percorsi (entrambi >1)
2. Nelle ore di lavoro inserire 100% nello "sconto ore" e 100% in "sconto km"
3. Creare una nuova fattura e aggiungere l'attività

OSM 2.4.15

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione!
Il problema dovrebbe ora essere risolto, con il commit presente sopra.

**Comment by idraulicadueci** [comment]
Grazie mille!! Confermo che il problema è stato risolto.
