### ISSUE TITLE
Mantenimento prima nota e scadenze durante riapertura fatture

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#818]
Attualmente, quando una fattura viene riportata in stato "Bozza", vengono eliminate le scadenze generate e anche la prima nota. Questo può essere un problema perché se ho già registrato il pagamento di una fattura con la prima nota, ne perdo traccia. Bisognerebbe fare in modo che, se c'è una prima nota per una fattura che viene riportata in bozza, la prima nota e le scadenze non vengano modificate. Se la fattura viene poi riemessa e ha importi diversi potrebbero però verificarsi dei problemi nello scadenzario che è già parzialmente chiuso.

@Dasc3er @lucasalva87 idee?

**Comment by idraulicadueci** [comment]
@loviuz a mio parere una fattura emessa deve essere assolutamente bloccata a qualsiasi modifica, specie se è già stata saldata. Il sistema fiscale prevede che una fattura, una volta emessa, può essere annullata soltanto mediante nota di credito. Quindi secondo me la strada più facile è quella di bloccare la fattura, attivando solo la possibilità di emettere una nota di credito o un buono sconto. In quest'ultimo caso andrebbe implementata la gestione dei vaucher da applicare a successive fatture come sconto.

**Comment by Dasc3er** [comment]
Credo sia una buona idea documentarsi prima sui casi d'uso che riguardano la riapertura di un documento, e in particolare su quelli degli utenti utilizzatori del gestionale. 
Ulteriore issue di riferimento, che pone un problema simile sui movimenti degli articoli: #787

**Comment by lucasalva87** [comment]
Secondo me @idraulicadueci ha ragione. E aggiungo anche che una fattura non dovrebbe essere eliminabile se é stata trasmessa la relativa fattura elettronica.

**Comment by Dasc3er** [comment]
Altre issue di riferimento grazie a @idraulicadueci : #829
