### ISSUE TITLE
Campi per componenti di myimpianti 

### ISSUE THREAD

**Issue by antoniotrapasso** [devcode-it/openstamanager#819]
Ciao,
volevo chiedere quali tipi di campo posso utilizzare nei file .ini dei componenti oltre ai seguenti?
input
select
textarea

GRAZIE MILLE!

**Comment by Dasc3er** [comment]
Ciao, tecnicamente i campi che hai indicato sono gli unici disponibili a livello di HTML.
Dovrebbe però essere possibile utilizzare i campi HTML personalizzati del gestionale, quindi in teoria puoi impostare i tipi "password", "ckeditor", "select con query", ...
E' però necessario che sperimenti un po' sulla questione, poichè non è al momento presente una documentazione comprensiva.
