### ISSUE TITLE
Errore Installazione 2.3

### ISSUE THREAD

**Issue by bydave69** [devcode-it/openstamanager#82]
Ho provato ad aggiornare alla 2.3, ma l'aggiornamento si è bloccato e mi è comparsa la pagina di errore "internal server error".
L'esame dei log del server apache riporta il seguente errore:
[Wed Dec 20 10:26:21.221588 2017] [core:alert] [pid 31221:tid 139810318477056] [client 62.11.1.142:45974] /home/xenosweb/domains/xenosweb.it/public_html/interventi/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration

Ho ripristinato il backup che avevo preventivamente fatto, ma non avevo pensato a backuppare anche il db (!) che pertanto non è stato ripristinato; adesso al login mi chiede di aggiornare il db alla versione 2.2, faccio ok, ma non succede nulla (c'è una barra di progressione che non si muove), mentre riesco ad effettuare il login e ad accedere al gestionale. Se chiudo il browser e provo a riloggarmi, mi chiede sempre di aggiornare il db alla 2.2: come procedo? è possibile ritentare l'aggiornamento alla 2.3?

**Comment by Dasc3er** [comment]
Ciao @bydave69,
l'errore da te segnalato è un nuovo problema di compatibilità htaccess.
Potresti inoltre specificare in che tipologia di server si è verificato l'errore (shared hosting, ...)?

Per provare a ritentare l'aggiornamento alla versione 2.3 dovresti ricaricare i file e commentarenel modo seguente le righe 6 e 7 del file .htaccess nella cartella principale del progetto.
```
#php_value upload_max_filesize 20M
#php_value post_max_size 20M
````

**Comment by Dasc3er** [comment]
Oppure potresti provare a sostituire le stesse righe con il seguente codice?
```
<IfModule mod_php5.c>
    php_value upload_max_filesize 20M
    php_value post_max_size 20M
</IfModule>
<IfModule mod_php7.c>
    php_value upload_max_filesize 20M
    php_value post_max_size 20M
</IfModule>
```

**Comment by bydave69** [comment]
Niente da fare.

Ho ripristinato la copia del sito  ver. 2.3 che avevo precedentemente scaricato con Filezilla (includendo però il file .htaccess modificato:
#php_value upload_max_filesize 20M
#php_value post_max_size 20M)

L'errore è scomparso, ma viene però visualizzata una pagina competamente bianca (mi era già successo stamane, quando avevvo tentato la strada di modifcare il file .htaccess in questo modo:
<IfModule mod_php5.c>
    php_value upload_max_filesize 20M
    php_value post_max_size 20M
</IfModule>)..

**Comment by bydave69** [comment]
Scusate per il ritardo con cui rispondo, ma sono appena rientrato in sede..
Ho attivato il debug, ecco cosa viene fuori:

 Whoops \ Exception \ ErrorException (E_ERROR)
Call to undefined function loadCSSModules()


Stack frame
 Whoops\Exception\ErrorException
…/include/custom/top.php40 

home/xenosweb/domains/xenosweb.it/public_html/interventi/include/custom/top.php

            
            $rs = $dbo->fetchArray("SELECT name, name2 FROM zz_modules WHERE id=\"".$id_module."\"");
            
            if( sizeof($rs) > 0 ){
                $module_name = $rs[0]['name'];
                ( $rs[0]['name2'] != '' ) ? $module_name2=$rs[0]['name2'] : $module_name2=$rs[0]['name'];
            }
        }
     
    ?><!DOCTYPE html>
    <html class="bg-black">
        <head>
            <meta charset="UTF-8">
            <title><?php echo $module_name2 ?> - Xenos</title>
            <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
            
            <link href="data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOW5ykAAAAAFYfm/xZ/5a4AAAAAGHDkWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGe55cTluf8AAAAABWH5v8Wf+W2AAAAABhw5P8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD67o/wAAAAAOda0KE5bn/xSP5v8Vh+b/Fn/l/xd35f8YcOT/Aw0dARRHqxIcWOPWAAAAAAAAAAAAAAAAAAAAAA+u6LwQpuj/Ep7n/xOW5/8Uj+b/FYfm/xZ/5f8Xd+X/GHDk/xpo5P8bX+P/FUKqKQAAAAAAAAAAAAAAAAVEVwILga4cEKbo/xKe5/8Tluf/FI/m/xWH5v4Wf+X+F3fl/xhw5P8aaOT/G1/j/wAAAAASMo41AAAAAA2+6aoOtuj/D6/o/xCm6P8Snuf/E5bn9w9rrQEAAAAAAAAAABRnyAMYcOT7Gmjk/xtf4/8cWOP/HVDj/xMujWwUMVr/FDFa/xQxWv8UU5j/FFOY/xQ0YP8UPnP/FFOY/xRTmP8UMl3/FEqG/xQxWv8UMFn/E0mF/xQxWv8UMVr/FDFa/xQxWv8TU5b/FDFa/xQxWv8TXKf/FDFa/xQxWv8UMVr/E3fY/xJ53P8ShO3/Ennd/xJ74P8UMVr/FDFa/xQxWv8UMVr/E1OW/xQxWv8UMVr/E1yn/xNvyv8UMVr/FDFa/xQxWv8SeNv/FDJb/xQxWv8ShvP/FDFa/xQxWv8UMVrzFDFa8xQ3Yf8UN2L/FDdi/xQxWvMUMVrzFDJc8xQyXPMUMVrzFDJb8xQ0Yf8UM2H/FTVj/xQxWvMUMVrzDb3pRw626P0Pr+j/EKbo/xKe5/8Tluf9AAAAAAAAAAAAAAAAAAAAABhv5P8aaOT/G1/j/xxY4/8dUOP/Ey6NYwAAAAAOtuicD63oehCm6P8Snuf/E5bn/xSP5v8Vh+b9Fn/l/Rd35f8YcOT/Gmjk/xtf4/8VQqoYFjyqSxMvjQIAAAAAAAAAAAIWHQ8Qpuj/Ep7n/xOW5/8Uj+b/FYfm/xZ/5f8Xd+X/GHDk/xpo5P8bX+P/BAscCwAAAAAAAAAAAAAAAAAAAAAPr+j3DH2uSxKe55wTluf/FI/m/xWH5v8Wf+X/F3fl/xhw5P8UTqskG1/kWBxY4/YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASnOcQE5bn/xJ8yRQVh+b/Fn/l8xRnyBMYcOT/EUKPIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2KQAxOW59cAAAAAFYfm/xZ/5a4AAAAAGHDkvwAAAAAAAAAAAAAAAAAAAAAAAAAA/n8AAPJfAADYGwAAwAcAAOAHAAADwQAAAAAAAAAAAAAAAAAAAAAAAIPBAACgBwAA4AcAANAbAAD6XwAA+l8AAA==" rel="icon" type="image/x-icon" />
            
            <?php
            loadCSSModules($css_modules);
            loadJscriptModules($jscript_modules);
            ?>
            
            
            
            
            
            <script>
                globals = { rootdir: '<?php echo $rootdir ?>', id_module: '<?php echo $id_module ?>' };
            </script>
        </head>
     
     
        <body class="skin-black">
            <div id="main_loading">
                <div>
                    <i class="fa fa-cog fa-spin text-danger"></i>

Arguments

1.    "Call to undefined function loadCSSModules()"

![immagine](https://user-images.githubusercontent.com/4057710/34263382-92b61666-e66f-11e7-9c52-5c7f189e5395.png)

**Comment by bydave69** [comment]
Invece l'unico file contenuto nella cartella logs/ è il file .htaccess con il seguente contenuto:
"Deny from all"

**Comment by Dasc3er** [comment]
@bydave69, il problema si verifica perché possiedi una versione personalizzata di alcuni file... 
In questi casi dovresti controllare l'effettiva compatibilità e aggiornare di conseguenza.

In effetti però è vero che la funzione in questione dovrebbe essere stata aggiunta all'interno del file **lib/deprecated.php**.

**Comment by Dasc3er** [comment]
Per risolvere il problema della funzione mancante dovresti aggiornare il file **lib/deprecated.php** con la versione più recente dalla repository (https://github.com/devcode-it/openstamanager/blob/master/lib/deprecated.php).
Continua comunque a tenere attivo il sistema di debugging, che rende più semplice individuare eventuali errori dello stesso tipo.

**Comment by Dasc3er** [comment]
Inoltre è strano il fatto che non sia stata effettuato l'inserimento dell'errore all'interno dei log...

**Comment by bydave69** [comment]
Grazie per la risposta, ma non ho ben capito quale è il problema nè come procedere per la risoluzione del blocco..
Non ho fatto particolari personalizzazioni, se non in alcune parti descrittive..

**Comment by Dasc3er** [comment]
Per risolvere l'errore, aggiungi il seguente codice al file **lib/deprecated.php**:
```
/**
 * Carica gli script JavaScript inclusi nell'array indicato.
 *
 * @param array $jscript_modules_array
 */
function loadJscriptModules($array)
{
    trigger_error('Funzione deprecata!', E_USER_DEPRECATED);

    $result = '';

    foreach ($array as $js) {
        $result .= '
<script type="text/javascript" charset="utf-8" src="'.$js.'"></script>';
    }

    echo $result;
}

/**
 * Carica i file di stile CSS inclusi nell'array indicato.
 *
 * @param array $css_modules_array
 */
function loadCSSModules($array)
{
    trigger_error('Funzione deprecata!', E_USER_DEPRECATED);

    $result = '';

    foreach ($array as $css) {
        if (is_array($css)) {
            $result .= '
<link rel="stylesheet" type="text/css" media="'.$css['media'].'" href="'.$css['dir'].'"/>';
        } else {
            $result .= '
<link rel="stylesheet" type="text/css" media="screen" href="'.$css.'"/>';
        }
    }

    echo $result;
}
```

Il problema è generato dal fatto che esiste il file **include/custom/top.php**, che secondo la struttura del progetto è una personalizzazione del file **include/top.php**.

**Comment by bydave69** [comment]
Ok, grazie Dasc3er per la precisazione, al momento del mio precedente commento non avevo letto i tuoi post (per qualche strana ragione non mi erano comparsi, colpa forse del fatto che stavo leggendo da smartphone..)
ho effettuato entrambe le modifiche suggerite: 
prima ho ricoperto il 'mio' deprecated.php con quello da te linkato nel post, ma mi dava lo stesso errore (classe 'HTMLHelper' not found);
poi, dopo aver fatto una rollback delle modifiche, ho aggiunto - sempre a quel file - il codice che mi hai indicato nell'ultimo post, e adesso l'errore è il seguente: class 'DBO' not found.
Ecco il dettaglio dell'errore:
![immagine](https://user-images.githubusercontent.com/4057710/34299212-016b8836-e722-11e7-9c4d-e370550eb2a7.png)

**Comment by bydave69** [comment]
Comunque ho la sensazione che l'aggiornamento alla 2.3 non sia stato completato...

**Comment by Dasc3er** [comment]
Credo che tu non abbia copiato nuovamente i file della versione 2.3. Potresti copiarli di nuovo?

**Comment by bydave69** [comment]
Allora, ho tentato nuovamente la copia dei file versione 2.3, ma non ho avito fortuna.. Ho provveduto nuovamente al ripristino della 2.2: non mi chiede più di aggiornare il db e sembra funzionare regolarmente. A questo punto attenderò l'uscita stabile della 2.3 per aggiornare nuovamente.
Grazie ancora per il supporto.
