### ISSUE TITLE
Perché non una struttura MVC?

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#820]
Ciao ragazzi,
mi chiedevo perché non utilizzare la struttura MVC?

Non è poco sicuro esporre tutta la cartella del progetto sul web anziché la sola cartella _public_ di Laravel ad esempio?

Non è una critica, solo una mia curiosità per capire perché non avete fatto il progetto in questo modo.

Grazie

**Comment by Dasc3er** [comment]
Ciao, in effetti è in progetto l'introduzione di una struttura MVC in una delle prossime versioni più consistenti.
In un primo momento progetteremo un framework personalizzato, di cui puoi vedere i primi componenti nelle branch future e laravel-mix. Successivamente può essere di interesse anche il passaggio completo a un framework completamente sviluppato come Laravel o Symfony, per esempio.

Al momento la struttura si mantiene per retrocompatibilità con le prime versioni del gestionale, e soprattutto poiché tra introduzione di nuove funzionalità e risoluzione bug è spesso difficile ritornare a una fase di progettazione strutturale.

**Comment by cristianviale** [comment]
Certo, mi rendo conto che il passaggio è una cosa piuttosto impegnativa. Speriamo di vedere la versione MVC al più presto.

**Comment by Dasc3er** [comment]
Se sei interessato a contribuire, ecco la roadmap generale pensata al momento: #710
Ammetto che si tratta di una bozza che contiene principalmente la mia idea di sviluppo futuro, e il resto del team di sviluppo la deve revisionare per bene. Nuove idee sono sempre le benvenute!
