### ISSUE TITLE
Compilazione automatica riferimenti in importazione FE

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#821]
All'interno dell'importazione fatturazione elettronica è stato aggiunto il pulsante "Compilazione automatica":
![immagine](https://user-images.githubusercontent.com/1647128/82055773-4a711180-96c1-11ea-8d3a-091221bfe80c.png)

L'ideale sarebbe che questa compilazione automatica pre-compilasse anche i riferimenti su ogni riga:
![immagine](https://user-images.githubusercontent.com/1647128/82055826-5f4da500-96c1-11ea-9759-76687153364e.png)

Se non c'è alcun codice articolo non pre-compilo nulla.
Se c'è un codice articolo:
 - DDT: se c'è un ddt di quel fornitore con quel codice articolo tra le righe, e non sono evase, collego quel ddt come riferimento
 - ORDINE: come sopra

![immagine](https://user-images.githubusercontent.com/1647128/82056198-e26efb00-96c1-11ea-9296-0a2db8395216.png)

@Dasc3er @lucasalva87 che ne pensate?

**Comment by Dasc3er** [comment]
Il principale problema in questo caso è effettuare il collegamento riga-riga tra la Fattura da importare e i documenti del gestionale.
In particolare, dobbiamo limitare il collegamento automatico alle righe che hanno gli stessi contenuti in Descrizione, Prezzo e IVA percentuale all'interno del documento identificato dalla Fattura tramite i riferimenti IdDocumento e simili.
Una cosa che può essere interessante è la gestione di questo collegamento allo stesso modo in cui è di interesse gestire i riferimenti tra DDT e Ordini. Questo perchè per il momento viene utilizzato il sistema di evasione, senza però i relativi controlli di quantità che sono fondamentali per il corretto funzionamento del gestionale.

**Comment by Pek5892** [comment]
Questa funzionalità è già stata introdotta in una versione successiva alla 2.4.22
