### ISSUE TITLE
Problema con il widget "Promemoria attività da pianificare"

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#823]
Ho creato un nuovo stato attività "ANNULLATO", con il quale annullo le attività richieste e poi disdette.
Lo stato è flaggato come COMPLETATO.
Non essendo ancora stato pianificato, quindi non avendo assegnato alcun tecnico, l'attività viene filtrata come da pianificare, senza tenere conto dello stato completato.

Quindi la modifica da apportare alla query è di filtrare le attività non ancora assegnate e il cui stato non sia considerato come completato.

OSM 2.4.15

**Comment by kenchu84** [comment]
si prevede la risoluzione di questa Issue a breve giro ?

**Comment by Dasc3er** [comment]
Il mio test ha evidenziato che la query del widget è corretta, ovvero il widget presenta un numero di elementi corretto prima dell'apertura.
All'apertura del modal, non veniva effettuato nessun controllo sullo stato delle attività da mostrare: è ora stato aggiunto con il commit di cui sopra.

**Comment by kenchu84** [comment]
Grazie, si avevo notato L incongruenza.
