### ISSUE TITLE
stampa registro iva mensile/trimestrale

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#824]
Per un utilizzo del sistema openstamanager che permette registrazioni di fatture acquisti/vendite e una gestione della prima nota contabile con alcune stampe base relative ai registri iva
Ritengo che vada implementata le stampa con la "liquidazione iva mensile/trimestrale" per un utilizzo quitidiano del gestionale, essendo un dato  essenziale per qualsiasi azienda.

Ho aggiunto un file di esempio di altro programma che utilizzo per una migliore spiegazione della richiesta di implementazione.

Liquidazione mensile e trimestrale
A seconda del regime contabile scelto (ordinario o semplificato), la liquidazione può avvenire su base mensile o trimestrale.

Bisogna ricordare che devono essere considerati solo gli importi delle operazioni detraibili.

Il regime naturale per il regime ordinario è quello mensile mentre a quello trimestrale possono accedere tutti coloro i cui ricavi annuali siano inferiori a 400.000 euro per i servizi o 700.000 euro per altri tipi di attività con un interesse dell'1%.

Ciò non toglie che anche quelli che dovrebbero contribuire su base trimestrale possano scegliere quella mensile.

I termini di pagamento per la liquidazione mensile è il 16 di ogni mese mentre per quella trimestrale si considera il 16 di due mesi dopo la fine del trimestre. Precisamente:

il 16 maggio per il primo trimestre
il 16 agosto per il secondo trimestre
il 16 novembre per il terzo trimestre
il 16 marzo dell'anno successivo con la dichiarazione IVA annuale per il quarto trimestre

![Schermata del 2020-05-19 12-33-54](https://user-images.githubusercontent.com/60449835/82316410-0b96d080-99cd-11ea-9fe8-be413ecef864.png)

**Comment by Dasc3er** [comment]
Ciao @leo-spa ,
Per favore modifica la descrizione inserendo un discorso completo e coerente sulla funzionalità, con casi d'uso e una spiegazione più completa.

**Comment by leo-spa** [comment]
> stampa registro iva mensile/trimestrale

 come da richiesta ho modificato la descrizione, ritengo di aver dato una spiegazione completa e coerente sulla funzionalità richiesta

**Comment by marcus905** [comment]
mi intrometto, @leo-spa ha provato a settare la data di riferimento della stampa dal selettore in alto a sinistra prima di cliccare sul bottone di generazione della reportistica?

**Comment by leo-spa** [comment]
![Schermata del 2020-05-19 13-32-33](https://user-images.githubusercontent.com/60449835/82321534-44d33e80-99d5-11ea-8a22-a3876af64596.png)

le due stampe attuali permettono solamente di avere l'importo dell'iva acquisti e l'importo dell'iva vendite non la liquidazione iva. 
Quest'ultima andrebbe calcolata a mano ogni volta e per chi ha una gestione trimestrale dovrebbe inoltre procedere manualmente al calcolo dell'1% sul totale.

**Comment by leo-spa** [comment]
le due stampe attuali permettono solamente di avere l'importo dell'iva acquisti e l'importo dell'iva vendite non la liquidazione iva.
Quest'ultima andrebbe calcolata a mano ogni volta e per chi ha una gestione trimestrale dovrebbe inoltre procedere manualmente al calcolo dell'1% sul totale.
![esempio](https://user-images.githubusercontent.com/60449835/82322433-cd061380-99d6-11ea-8657-deb99a81bf32.png)

**Comment by loviuz** [comment]
@leo-spa le stampe attuali del registro iva non sono da considerare a livello contabile perché mancano varie funzionalità, come la detraibilità parziale dell'iva e l'eventuale iva differita, infatti abbiamo inserito l'avviso ad inizio schermata. Di conseguenza la stampa liquidazione iva non è ancora disponibile. Probabilmente la integreremo, ma in questo momento consigliamo di usare l'output di questi dati a livello sperimentale.

**Comment by leo-spa** [comment]
@loviuz Certamente ho letto l'avviso riportato anche nell'immagine che ho postato, il mio era un consiglio visto che nella home page fare riferimento ad un gestionale completo  ed inserite anche: Gestisci le registrazioni contabili in modo semplice e veloce. Da Contabile oltre che assistente informatico, ho provato il vostro sistema, molto comodo in quanto è possibile inserirlo su un cloud personale, ha un buona partenza di piano dei conti e le registrazioni base: fatture acquisti/vendite e pagamenti è discreto. c'e' qualche errore ma si corregge manualmente, come il calcolo della rivalsa inps su professionisti al quale se si fa gestire dall'automatismo viene calcolata la ritenuta d'acconto erroneamente. Per questo mi sono permesso di suggerire il calcolo della liquidazione iva per una gestione quotidiana del software e non come semplice programma di nicchia in perenne beta testing.

**Comment by lucasalva87** [comment]
Scusa se devio temporaneamente la discussione: riusciresti ad indicarci perché viene calcolata la ritenuta d'acconto erroneamente? Riusciresti a riportare un esempio per i test e l’eventuale risoluzione? Grazie

**Comment by leo-spa** [comment]
@lucasalva87 il problema si ricrea semplicemente selezionando ritenuta contributi.
nel mio caso: inps 4% sul 100% inponibile.
Il sistema calcosa la ritenuta d'acconto sull'inps che non è soggetto a ritenuta
Per ovviare a questo errore inseriesco un rigo manualmente come da allegato
![Screenshot_2020-06-16 Fatture di vendita - OpenSTAManager](https://user-images.githubusercontent.com/60449835/84754333-89e09580-afc0-11ea-8d4e-4651ea8acb40.png)

**Comment by Dasc3er** [comment]
@leo-spa @lucasalva87 Posso chiedere se il problema della ritenuta d'acconto sussiste?
A livello pratico, se non si vuole far calcolare la ritenuta sulla Rivalsa INPS esiste l'opzione di "Calcola ritenuta d'acconto su".

**Comment by leo-spa** [comment]
non riuscendo ad aggiornare alla versione 2.4.16 nella quale è stato aggiunto: – Aggiunta rivalsa INPS e relativa IVA per il calcolo del totale ivato del documento, continuo ad aggiungere una riga di manuale dove calcolo manualmente la rivalsa inps corretta

**Comment by Dasc3er** [comment]
@leo-spa Temo tu abbia frainteso il contesto dell'aggiornamento, anche perchè effettivamente la descrizione è un po' fuoriviante: il commit relativo (b7d96630c3e578986222f7aff9b90d5bb2183670) modifica i totali visibili nella tabella principale del modulo Fatture, ma non modifica la logica del gestionale in alcun modo.

**Comment by Dasc3er** [comment]
@leo-spa Come indicato sopra, il problema della issue è risolvibile selezionando il periodo dal calendario globale del gestionale
Similmente, il problema del calcolo della ritenuta d'acconto non sussiste: una volta selezionata la ritenuta e impostato il "Calcola ritenuta su", la ritenuta d'acconto considera automaticamente la rivalsa INPS se presente.

Segno pertanto la issue come in chiusura.

**Comment by leo-spa** [comment]
la ritenuta d'acconto considera automaticamente la rivalsa INPS se presente. è un errore, non si calcola la ritenuta d'acconto sula rivalsa inps, come già riportato negli screen shot inviati precedentemente. ho risolto comunque inserendo una rigo manuale e togliendo la ritenuta 'acconto sull'importo inps inserito. se poi per @Dasc3er il sistema risponde correttamente o io non son in grado di spiegarmi chiuda pure il ticket, altrimenti se gentilmente spiega i passi per procedere ad una fatturazione corretta dove la ritenuta di acconto non viene calcolata sulla rivalsa inps
