### ISSUE TITLE
Problema con il numero progressivo dei preventivi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#825]
Se duplico un preventivo emesso in un anno diverso dall'attuale, il numero progressivo assegnato in automatico è lo 001/YYYY con data identica a quella del preventivo duplicato.

Esempio:
Preventivo n. 200/2019 del 20/03/2019.
In data odierna (20/05/2020) duplico questo preventivo. Il progressivo del duplicato è 001/2020 del 20/03/2019, nonostante l'ultimo preventivo emesso sia il 100/2020.
**Dovrebbe essere 101/2020 del 20/05/2020**

OSM 2.4.15

**Comment by loviuz** [comment]
@idraulicadueci hai modo di riprovare aggiornando il file presente nel commit https://github.com/devcode-it/openstamanager/commit/a71c45d4dd87e6a9171cc7e7ee6921486bced1d4?

**Comment by idraulicadueci** [comment]
@loviuz con il commit adesso sia il numero progressivo che la data vengono inseriti correttamente. Grazie.
