### ISSUE TITLE
è possibile disattivare o modificare le impostazioni riguardo la sicurezza delle password?

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#826]
Provando l'ultima versione... questa cosa è solo per l'amministratore durante l'installazione o per tutti gli utenti? È possibile disattivrlo nel config.inc.php? È un avvertimento anche se sembra un errore...
![image](https://user-images.githubusercontent.com/6625123/82597263-fb3b4d00-9ba8-11ea-98a4-a4e6b37b930e.png)

**Comment by Dasc3er** [comment]
Non è possibile evitare le informazioni sulla sicurezza della password, ma l'avviso non è bloccante.
 Purtroppo il plugin che utilizziamo sembra avere una traduzione errata, che si può però risolvere manualmente.
Se invece vuoi proprio evitare il tooltip (visibile a tutti gli utenti), ti consiglio di nasconderlo tramite CSS personalizzato nelle Impostazioni.

**Comment by beppe9000** [comment]
Grazie delle infomrazioni. Più che la traduzione secondo me è anche una questione cromatica: magari se si riuscisse di fabbrica a farlo giallo/arancione la sua presenza desterebbe meno dubbi: vorrei tenere questo issue aperto per cambiare il colore di default per quell'avviso (a meno che non vi sia già un duplicato)
