### ISSUE TITLE
redirect alla pagina di login

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#827]
## Comportamento richiesto

Redirect alla pagina di login

## Comportamento attuale

Viene visualizzato il pannello utente, privo di dati perchè manca la sessione

## Passi per riprodurre il comportamento

`GET /modules/utenti/info.php` senza aver fatto login

**Comment by Dasc3er** [comment]
Il problema è noto, ma risulta irrisolvibile fino allo sviluppo completo della branch future.
Grazie in ogni caso per la segnalazione!

**Comment by beppe9000** [comment]
ottimo
