### ISSUE TITLE
Miglioria tabella ORE TECNICI nel template attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#828]
## Comportamento richiesto

Rivedere la tabella ORE TECNICI

## Comportamento attuale

Allo stato attuale se un intervento si svolge in due date consecutive, nella stampa compare solo la data di inizio (sotto la colonna DATA) e accanto l'orario di inzio e di fine (DALLE... ALLE...) ma non l'eventuale data del giorno dopo. Quindi non viene evidenziato che l'orario di fine si riferisce alla data del giorno successivo.
Per es. se un'attività inizia alle 8.00 del giorno 22/05/2020 e termina alle ore 8.00 del 23/05/2020, nella stampata risulta che la data dell'intervento è 22/05/2020 dalle 8.00 alle 8.00. Il calcolo delle ore è comunque corretto.

## Possibile soluzione

Cambiare le colonne "data", "dalle" e "alle" in "data e ora di inizio" e "data e ora fine".
Oppure impedire all'utente di inserire una data differente da quella di inizio, obbligandolo a inserire una nuova riga per la data successiva (in questo caso la prima riga dalle 8.00 alle 23.59 del 22/05/2020 e la seconda dalle 0.00 alle 8.00 del 23/05/2020)

OSM 2.4.15

**Comment by Dasc3er** [comment]
Ecco la grafica introdotta nella versione in sviluppo, con valori puramente indicativi:
![image](https://user-images.githubusercontent.com/15911489/91695881-18e85d00-eb6f-11ea-92b8-24d17bd8acf9.png)

**Comment by idraulicadueci** [comment]
Direi che così è perefetto :+1:

**Comment by kenchu84** [comment]
Saranno introdotte più sessioni nello stesso rapporto d intervento quindi?
Se si, sarà applicabile alla 2.4.11?

**Comment by Dasc3er** [comment]
@kenchu84 L'unica modifica effettuata è nella visualizzazione delle sessione di lavori nella stampa, che ora mostra la data di inizio e di fine in modo completo se i giorni sono differenti (come da immagine).
Da sempre in una attività è possibile aggiungere più sessioni di lavoro, gestibili correttamente a livello del gestionale ma che presentavano questa incongruenza nel caso segnalato da @idraulicadueci .

**Comment by kenchu84** [comment]
Si scusa, intendevo più sessioni di lavoro con descrizioni diverse in modo
che se due tecnici effettuano due lavorazioni per la medesima attività
vengano palesate. Capito comunque.

Grazie

Il giorno mar 1 set 2020 alle 08:08 Thomas Zilio <notifications@github.com>
ha scritto:
