### ISSUE TITLE
MIGLIORIA Scadenzario

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#829]
## Comportamento richiesto

Mantenere lo storico dello scadenzario

## Comportamento attuale

Una volta registrato il pagamento, tutte le eventuali annotazioni inserite vanno perse. Quindi non è possibile avere a disposizione lo storico relativo. Se per esempio inserisco una nota "Pagato con assegno n. XXXXXXXX", questa nota dopo la registrazione del pagamento non è più disponibile.

## Possibile soluzione

Soluzione 1: Flaggare il record come pagato o chiuso e renderlo disponibile aggiungendo un filtro "Visualizza scadenze chiuse"
Soluzione 2: Migrare le informazioni in prima nota

**Comment by Dasc3er** [comment]
@loviuz @lucasalva87  Per registrare note interne del genere non sarebbe più corretto utilizzare alcuni dei campi di testo liberi dei documenti?
