### ISSUE TITLE
Errore rilevazione $docroot su cartelle con link

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#83]
Ho provato su Linux: se installo OSM su una cartella che in realtà è un link, $docroot non viene valorizzato correttamente ed esce un loop infinito.

**Comment by Dasc3er** [comment]
@loviuz Questo è un problema del nuovo sistema di rilevazione degli indirizzi (versione 2.3) o era presente anche nella versione 2.2?

**Comment by loviuz** [comment]
Nella 2.2 c'erano altri problemi con le path autocalcolate. in questo caso peró ho notato che il loop è causato dall'if sul core.php che verifica se si è nella cartella corretta di OSM, per evitare che chi si logga su OSM in una cartella, possa bypassare il login in un'altra cartella dove c'è un'altra installazione di OSM. Di per sé le path vanno bene, il vero problema sarebbe quello...

**Comment by loviuz** [comment]
Dal plugin della pianificazione interventi dentro i contratti, poter creare delle pianificazioni periodiche senza inserire ogni promemoria singolarmente.
Esempio: il contratto è valido dal 01/01/2017 al 31/12/2017. Voglio pianificare dei promemoria di attivita ogni 15 giorni.
Attualmente: devo inserire 24 promemoria manualmente.
Scorciatoia: poter impostare ogni quanto generare i promemoria, con un giorno da cui partire e ogni quanti giorni/mesi ripeterlo. Questo creerebbe in una sola volta tutti i promemoria. Tasto per azzerarli (solo quelli senza collegamento all'attività).

**Comment by lepool** [comment]
@Dasc3er , il commit [a2c6a69](https://github.com/devcode-it/openstamanager/commit/a2c6a6984d475f894b0357d67d2dee431da3de06) mi crea problemi di chiamate recursive ed Apache termina la connessione. 
Il problema si presenta se non ho una sessione autenticata attiva.
Ho OSM installato in /var/www/https/osm e osm non è un link ad una cartella.

DOCROOT-->/var/www/https/osm
ROOTDIR-->/osm
getURLPath nella riga 130 di core.php restituisce osm/index.php

Con la precedente versione al FIX di core.php tutto ok.

**Comment by Dasc3er** [comment]
@lepool Mi ero accorto di un problema simile, potresti provare ad aggiornare al commit 593464603da5da740304fe623fb33adff0cfb04a per controllare che non sia già stato risolto?
Eventualmente potremmo rimandare il fix alla versione 2.4, se il bug persiste nella tua installazione...

**Comment by lepool** [comment]
Ho fatto la prova dopo il merge upstream/master ed il problema persiste.

**Comment by Dasc3er** [comment]
Potresti provare la seguente soluzione?
```
$path = $_SERVER['SCRIPT_FILENAME'];
$prefix = rtrim($_SERVER['DOCUMENT_ROOT'], '/\\');
```

**Comment by lepool** [comment]
Confermo, ora sembra risolto.
