### ISSUE TITLE
Codice metodo pagamento associato alla rate

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#830]
Per poter prevedere metodologie di pagamento particolari come per esempio bonifico data fattura + ri.ba. 30 giorni sarebbe necessario collegare il codice mp della FE non più alla tipologia del pagamento ma bensì alle sue rate. Vedasi screenshot esplicativo.

![Pagamenti OpenSTAManager](https://user-images.githubusercontent.com/30728163/82914394-c09e2f80-9f6f-11ea-98a4-e069118d8132.jpg)

**Comment by lucasalva87** [comment]
Sfruttremo così il nodo 2.4.2 <DettaglioPagamento> del tracciato XML definendo per il sotto-elemento 2.4.2.2  <ModalitaPagamento> i codici corretti (es. bonifico + ri.ba. =  MP05 - MP12)

**Comment by sajotrei** [comment]
vedi suggerimenti 
Modalità di pagamento differente #1151

**Comment by Pek5892** [comment]
Introdotto nella versione 2.4.52
