### ISSUE TITLE
Gestione upload allegati

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#831]
Sarebbe utile prevedere per l'upload degli allegati:

1. La possibilità di fare l'upload gli allegati in modalità drag&drop (https://css-tricks.com/examples/DragAndDropFileUploading)

1. Poter caricare più allegati contemporaneamente senza dover necessariamente attendere il caricamento del singolo per poter procedere al successivo

**Comment by Dasc3er** [comment]
Può essere utile un sistema di questo tipo, ovviamente da vedere se compatibile con le nostre necessità: https://www.dropzonejs.com/
