### ISSUE TITLE
Miglioria filtri

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#832]
## Comportamento richiesto

Sarebbe più utile e corretto che alcuni input text field dei filtri fossero sostituiti da caselle a discesa, in quanto legate a valori predefiniti, come per esempio i campi-filtro Categoria e sotto-categoria nella vista globale Articoli

## Comportamento attuale

Adesso posso inserire anche valori non contenuti nelle tabelle a cui sono collegati, vanificando, in caso di errore di digitazione, la funzionalità.

## Possibile soluzione

Sostituire le caselle a digitazione libera con caselle di riepilogo a discesa

**Comment by lucasalva87** [comment]
Il campo di filtro è volutamente un input in quanto si potrebbero comunque voler ricercare tutte le categorie che iniziano con una determinata lettera o parola. Con un selettore questo non sarebbe più  possibile. Valutare, eventualmente, un auto completamento dei valori.
