### ISSUE TITLE
Aggiunta numero rata in Scadenzario e Prima Nota

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#833]
## Comportamento attuale

Ho una fattura i cui pagamenti sono suddivisi in più scadenze. Se clicco sulla seconda scadenza e "Registra contabile pagamento" viene registrato in prima nota il pagamento della prima scadenza.

Un'altra utile implementazione potrebbe essere quella di numerare le rate di pagamento (per es. rata 1/3, 2/3, 3/3) da avere in prima nota con le relative informazioni (numero rata, data di scadenza normale e data di scadenza concordata)

**Comment by Pek5892** [comment]
https://github.com/devcode-it/openstamanager/issues/877
