### ISSUE TITLE
MIGLIORIA duplicazione articoli

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#834]
## Comportamento richiesto

In fase di duplicazione evitare di riportare allegati e immagini

## Comportamento attuale

Se duplico un articolo al cui interno sono inclusi allegati (schede tecniche, depliant, ecc) e l'immagine, questi vengono riportati anche nell'articolo duplicato. Nella maggior parte dei casi immagini e allegati non sono congrui.

vedere anche issue #814

**Comment by Dasc3er** [comment]
In realtà la duplicazione in questo senso è corretta, poiché è stata introdotta appositamente.

**Comment by idraulicadueci** [comment]
Allora forse potrebbe essere utile un blocco decisionale "Duplica anche allegati". Spesso si utilizza la duplicazione per non dover inserire nuovamente categoria e sotto-categoria.
Per esempio, un articolo che fa parte della stessa categoria ha un altra brochure da allegare e un'immagine differente. In altre situazioni la duplicazione, invece può essere utile.

**Comment by Dasc3er** [comment]
Grazie per il suggerimento!
La modifica è stata implementata con una modal aggiuntive che permette di personalizzare le scelte relative alla duplicazione.
