### ISSUE TITLE
Domanda: Inserimento campo "Codice interno" in modulo articoli

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#836]
Ho provato a fare un test per inserire il campo in oggetto, in quanto in magazzino ho articoli censiti con codice interno. Funzione utile per ricercare l'articolo senza dover cercare il cod. fornitore.

1. Ho creato il campo "codint" nella tabella mg_articoli (VARCHAR 25)

2. Nel file /modules/articoli/actions.php ho inserito la riga

`$articolo->codint = post('codint');`

sia nella sezione di aggiunta articolo che in quella di modifica;

3. Nel file /modules/articoli/edit.php ho inserito la riga

`<div class="col-md-6">
                            {["type": "text", "label": "<?php echo tr('Codice interno'); ?>", "name": "codint", "value": "$codint$" ]}
                        </div>  `

Il problema sta nel fatto che se inserisco un valore nel nuovo campo, mi si azzerano i campi "Categoria" e "Sottocategoria"

Dove sta l'errore?

**Comment by Dasc3er** [comment]
Sinceramente non ti saprei dire, poiché la modifica che hai fatto non dovrebbe influenzare Categoria e Sottocategoria...
Sei sicuro di non avere fatto qualche modifica sbagliata al contenuto HTML oppure alle azioni di salvataggio?

**Comment by idraulicadueci** [comment]
Ho fatto modifiche anche al file /ajax/select, ma successivamente ho tolto la modifica, pensando dipendesse da quello. Approfondendo ho notato che il problema lo crea il file edit.PHP, però non riesco a capire dove.
(è già un miracolo che sia riuscito a far apparire il campo nel modulo, viste le mie altissime conoscenze di programmazione 
:-)
Comunque grazie mille per la risposta!

**Comment by idraulicadueci** [comment]
Il problema si è risolto spostando la riga di modifica del file edit.php insieme a quella relativa al campo "codice". È probabile che nella posizione precedente entrasse in conflitto con la query di selezione di categoria e sottocategoria?

**Comment by Dasc3er** [comment]
Può essere, anche se dipende tutto dal codice effettivo.
