### ISSUE TITLE
Problema in fase di interruzione operazioni

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#837]
Se inizio un'operazione, come ad esempio "Stampa inventario", se interrompo l'operazione, OSM resta bloccato. L'unico modo per sbloccarlo è svuotare la cache del browser e ricaricare la pagina.

OSM 2.4.15

**Comment by Dasc3er** [comment]
@idraulicadueci In questo caso non possiamo fare niente, poichè il problema non è del gestionale ma del server.
Per risolvere il problema è necessario ottimizzare ulteriormente la generazione delle stampa che causa il problema, o aumentare le risorse del server disponibili per PHP.
