### ISSUE TITLE
Problema gestione categorie e sottocategorie

### ISSUE THREAD

**Issue by projecta2020** [devcode-it/openstamanager#839]
buongiorno
sono a segnalare due piccoli problemi

-Magazzino>articoli
nella finestra di immissione di un nuovo articolo si possono compilare i campi nuova categoria e sottocategoria.
il campo categoria funziona correttamente anche creandone una nuova, il campo sottocategoria invece non funziona in quanto aggiungendo una nuova variante ne segnala il salvataggio ma in realtà non è salvata nè selezionabile

- Strumenti>tabelle>categoria articoli

non riesco ad eliminare un record categoria perché sostiene che ci sia abbinato un articolo in magazzino, in realtà era stato attribuito a un articolo "prova" che poi è stato eliminato quindi non più presente

* Versione del progetto: 2.4.15 (R8706efd6)

**Comment by medianik** [comment]
Buongiorno
hai ragione, ho notato anch'io lo stesso problema che ho segnalato qualche settimana fà 
speriamo che venga sistemato al più presto perchè è molto fastidioso per chi utizza sovente il carico di nuove sottocategorie-

Saluti
Antonio

**Comment by lucasalva87** [comment]
Confermo che è un problema che è stato già risolto nella 2.4.16 (in sviluppo)
2e7315a6216dab4d38c8e43b54187ad1c5d0ca6b
