### ISSUE TITLE
Promemoria periodici

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#84]
Dal plugin della pianificazione interventi dentro i contratti, sarebbe utile poter creare delle pianificazioni periodiche senza inserire ogni promemoria singolarmente.

Esempio: il contratto è valido dal 01/01/2017 al 31/12/2017. Voglio pianificare dei promemoria di attività ogni 15 giorni.
Attualmente: devo inserire 24 promemoria manualmente.

Scorciatoia: poter impostare ogni quanto generare i promemoria, con un giorno da cui partire e ogni quanti giorni/mesi ripeterlo. Questo creerebbe in una sola volta tutti i promemoria. Tasto per azzerarli (solo quelli senza collegamento all'attività).

**Comment by loviuz** [comment]
In parte quasi completo con il commit https://github.com/devcode-it/openstamanager/commit/ec97471c2eec28714e8142095583eca62137e571

**Comment by lucasalva87** [comment]
Chiuso con commit 8dbe2b6
