### ISSUE TITLE
BUG sconto attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#841]
## Comportamento attuale

Ho creato una attività per un cliente che ha listino con sconto 15%.
Quindi ho richiamato un articolo all'interno dell'attività con prezzo di vendita di 10 euro.
Sia a video che sulla stampa compare lo sconto 1,5% anziché 15% oppure € 1,5, cioè restituisce il giusto valore in euro ma con il segno %.

OSM 2.4.15

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione!
Si trattava semplicemente di un problema di visualizzazione delle informazioni, quindi non ci dovrebbero essere problemi a livello di conti e importi.
