### ISSUE TITLE
Problema con l'orario sul calendario Google

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#842]
L'orario riportato sul calendario di Google è di un'ora o due ore più avanti rispetto all'ora di inizio dell'intervento.

OSM 2.4.15

**Comment by Dasc3er** [comment]
Il problema è probabilmente causato dalla timezone dell'API, non impostata correttamente.

**Comment by Dasc3er** [comment]
@idraulicadueci Dalla documentazione iCal, il formato utilizzato è corretto: https://www.kanzaki.com/docs/ical/dateTime.html
Noi utilizziamo il formato senza riferimento alla timezone, che dovrebbe essere interpretato come data e ora assoluta della timezone locale. Posso solo supporre che le impostazioni di importazione sul calendario Google siano impostate in modo errato.

**Comment by idraulicadueci** [comment]
Io utilizzo Google Calendar. Il problema sta proprio nel Time zone che su Google calendar non è modificabile, almeno per il calendario di OSM. E infatti è impostato in automatico sul tempo coordinato universale. Non so se esite il modo di modificarlo.

**Comment by Dasc3er** [comment]
@idraulicadueci Puoi testare il commit https://github.com/devcode-it/openstamanager/commit/aaee6ee05d5d8795fc6b40ba10277c65571fe9f0 per verificare che il problema sia risolto?

**Comment by idraulicadueci** [comment]
Adesso è scomparso completamente.

**Comment by Dasc3er** [comment]
Scusa, ma il problema è scomparso o non funziona più la sincronizzazione?

**Comment by idraulicadueci** [comment]
> Scusa, ma il problema è scomparso o non funziona più la sincronizzazione?

Non funziona la sincronizzazione

**Comment by Dasc3er** [comment]
@idraulicadueci Per il momento il problema non sarà risolto, a meno che non riesci personalmente a introdurre un fix dedicato.
Ritengo comunque che ci siano delle impostazioni su Google per risolvere il problema, ma non saprei indicarti come individuarle.
