### ISSUE TITLE
errore installazione 

### ISSUE THREAD

**Issue by siacarini** [devcode-it/openstamanager#843]
## Comportamento richiesto

installazione OpenSTAManager 2.4.15

## Comportamento attuale

errore installazione si blocca il 93 e dire errore sullo script 2_4_14.sql
## Possibile soluzione

[Non obbligatorio] Hai suggerimenti su come risolvere il bug o individuarne le cause?

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1.
2.
3.

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo:
* Versione del progetto:
* Versione PHP:
* Tipo di server:

**Comment by Dasc3er** [comment]
Puoi condividere i file di log?
Li trovi nella cartella logs/.

**Comment by siacarini** [comment]
ecco il log
[setup.log](https://github.com/devcode-it/openstamanager/files/4803146/setup.log)

**Comment by Dasc3er** [comment]
Grazie per la segnalazione, puoi risolvere il problema applicando questo commit: https://github.com/devcode-it/openstamanager/commit/8ef491695970b3e89e56d2d6b1bf4fc8c7b11b81
Puoi infine far riprendere l'installazione aggiungendo `?force` all'URL.

**Comment by Dasc3er** [comment]
@siacarini In assenza di conferma, chiudo la issue poichè il problema dovrebbe essere risolto.
Se così non fosse, scrivi pure qui oppure in una nuova issue!
