### ISSUE TITLE
Problema partenza merce intervento

### ISSUE THREAD

**Issue by projecta2020** [devcode-it/openstamanager#846]
buongiono

anche da amministratore, nella creazione del report di un intervento aggiungendo nel modulo righe degli articoli impiegati non riesco a modificare la partenza merce, posso solo selezionare la mia sede legale e non le altre sedi, in realtà automezzi, a disposizione.

potete aiutarmi grazie

**Comment by loviuz** [comment]
buongiorno, quale versione hai in uso? nella versione attuale è possibile selezionare tutte le sedi dell'anagrafica di tipo "Azienda"
