### ISSUE TITLE
Suggerimento - Adozione di Conventional Commits

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#847]
Siccome è già stato adottato il modello [Keep a changelog](https://keepachangelog.com/it-IT/1.0.0/) per i changelog, si potrebbe adottare un modello per uniformare i commits come [Conventional Commits](https://www.conventionalcommits.org/it).

Ci sono inoltre plugin per le varie IDE di sviluppo che permettono di introdurre questa caratteristica in modo molto più versatile e flessibile

**Comment by Dasc3er** [comment]
Ancora quanto il gestionale era su Sourceforge venivano utilizzati commit di questo tipo.
Sono stati rimossi poichè non erano mai affidabili: un commit cambia spesso molte cose di parti diverse del gestionale, e pertanto non risulta un buono standard per noi.
In futuro è prevista una separazione dei diversi moduli dal codice di base del gestionale, nel qual caso i commit dovrebbero essere più organizzati.
