### ISSUE TITLE
Problema dimensione immagini nella stampa ordini

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#848]
## Comportamento richiesto

Ridimensionamento delle immagini in modo che rientrino nella cella della tabella

## Comportamento attuale

L'immegine esce dai margini della cella 

OSM 2.4.15

**Comment by idraulicadueci** [comment]
Credo di aver risolto modificando la riga 129 del file /templates/ordini/body.php:

`<img src="'.$riga->articolo->image.'" style="max-height: 80px", style="max-width:90px">`

però viene penalizzata la risoluzione.

**Comment by Dasc3er** [comment]
@idraulicadueci Ci servono maggiori dettagli.
Con quali dimensioni le immagini presentano problemi?

**Comment by idraulicadueci** [comment]
Sicuramente con quelle che superano larghezza 90 pixel. Con la riga che ho modificato il problema si risolve.
