### ISSUE TITLE
Utilizzo dashboard con dispositivi mobili

### ISSUE THREAD

**Issue by projecta2020** [devcode-it/openstamanager#849]
buongiorno

accedendo al gestionale da tablet o smartphone , il "tap" diretto sulla dashboard funziona solo per attività già inserite, non è possibile quindi inserire intervento selezionado direttamente da dashboard data e ora.

Ho provato con  dispositivi differenti android 7, android 8 e browser differenti Chrome e stock Samsung anche "richiedendo sito desktop".

E' un bug o è voluto?

Versione del progetto: 2.4.15 (R8706efd6)

grazie

**Comment by Dasc3er** [comment]
Ciao @projecta2020 ,
sospetto che il comportamento sia voluto. Infatti, la gestione della Dashboard viene fatta attraverso Fullcalendar e di conseguenza viene mantenuto il comportamento relativo previsto da questa libreria per la versione mobile.
Sarebbe molto difficile gestire il "tap" per creare direttamente gli interventi da mobile, e inoltre nessuno finora lo ha mai richiesto visto che si può usare normalmente il modulo Attività.
Se necessiti di una modifica simile, ti consiglio di considerare una personalizzazione. Se invece hai esperienza di programmazione e hai un'idea su come correggere il comportamento, puoi utilizzare GitHub e creare una PR così da aiutarci a migliorare il gestionale!

**Comment by lucasalva87** [comment]
Non so se può essere utile: https://fullcalendar.io/docs/touch

**Comment by kenchu84** [comment]
Dalle prove che ho fatto, sembra che fullcalendar non tratti la parte "insert". Anche nella loro documentazione non ho trovato riferimenti.

**Comment by kenchu84** [comment]
Sulla nuova versione di Safari la creazione funziona.Devi pero tenere il dipo molto fermo per 3 secondi.
