### ISSUE TITLE
Miglioramento del sistema dei seriali 

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#851]
## Comportamento attuale

Il sistema dei seriali attuale permette l'utilizzo di uno specifico seriale una sola volta per le entrate e una sola volta per le uscite.
Diviene quindi impossibile utilizzare uno stesso seriale che viene ripristinato per qualche motivo, quale utilizzo in una Fattura di vendita e una successiva Nota di credito.
Esempio dal forum: https://forum.openstamanager.com/viewtopic.php?f=10&t=95239&p=103739#p103738

## Possibile soluzione

Una prima soluzione potrebbe prevedere l'introduzione di un flag per indicare la disponibilità di un certo seriale, con il difetto che le logiche da implementare potrebbero essere piuttosto difficili: infatti, per ogni utilizzo in un documento, viene creata una riga in **mg_prodotti** con i relativi dati del seriale.

Potrebbe essere utile una ristrutturazione della tabella **mg_prodotti** per prevedere una maggiore flessibilità nell'uso dei seriali.
In particolare, tramite l'utilizzo delle classi Eloquent si potrebbe creare una struttura N-N dove **mg_seriali** mantiene i soli seriali in relazione agli articoli, **mg_seriali_righe** indica i collegamenti tra righe e seriali.
Questa struttura permetterebbe una semplificazione della logica, oltre che di individuare tramite la riga più recente di **mg_seriali_righe** lo stato del seriale (disponibile o meno).

**Comment by Pek5892** [comment]
Inserimento di seriali già utilizzati (es nel caso dei resi) presente nella versione 2.4.48
