### ISSUE TITLE
Miglioramento gestione maggiorazioni a livello grafico (per il cliente)

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#853]
## Comportamento richiesto

In generale, il sistema attuale di gestione degli importi è abbastanza completo e funzionale. Sorgono però dei problemi nel momento in cui si cerca di creare una logica impostata a nascondere alcune particolari informazioni relative ai conti finali.
In particolare, è solitamente buona norma nascondere (in stampa ed eventualmente in Fattura Elettronica) le maggiorazioni dirette effettuate su articoli/righe dei documenti. Al contrario, è necessario continuare a mostrare i relativi sconti.

Propongo quindi l'introduzione di un insieme di attributi virtuali nei modelli Eloquent dedicati alla gestione delle righe, da utilizzare in parallelo agli attributi attuali nei casi sopra indicati.
Pertanto:
- `prezzo_unitario_visualizzabile`: `prezzo_unitario` con eventuale maggiorazione incorporata
- `prezzo_unitario_ivato_visualizzabile`: `prezzo_unitario_ivato` con eventuale maggiorazione incorporata
- `prezzo_unitario_corrente_visualizzabile`: `prezzo_unitario_corrente` con eventuale maggiorazione incorporata
- `iva_unitaria_visualizzabile`: `iva_unitaria` con eventuale maggiorazione incorporata
- `sconto_unitario_visualizzabile`: `sconto_unitario` se effettivamente si tratta di uno sconto, altrimenti 0 (si nasconde la  maggiorazione)
- `sconto_unitario_ivato_visualizzabile`: `sconto_unitario_ivato` se effettivamente si tratta di uno sconto, altrimenti 0 (si nasconde la  maggiorazione)
- `sconto_percentuale_visualizzabile`: `sconto_percentuale` se effettivamente si tratta di uno sconto, altrimenti 0 (si nasconde la  maggiorazione)
- tutti gli altri campi come semplice alias della versione originale

Similmente, potrebbe essere utile una procedura simile per i totali dei documenti, in particolare per il campo Sconto.
Infatti, al momento il campo Sconto presenta un riepilogo di tutti gli sconti e le maggiorazioni applicate sulle righe di un documento: sempre nelle stampe, se il totale delle maggiorazioni è maggiore del totale degli sconti si genera una stampa non completa.

**Comment by lucasalva87** [comment]
Questo era stato introdotto?

**Comment by Dasc3er** [comment]
@lucasalva87 Le modifiche sulle righe sono state effettuate, resta da definire se può essere utile aggiungere degli ulteriori campi per i documenti.
In riferimento: #853

**Comment by Pek5892** [comment]
Attualmente la maggiorazione viene nascosta in stampa, e viene invece visualizzato lo sconto
![immagine](https://github.com/user-attachments/assets/d2c71e15-f43b-43b7-a1e4-93a0af6b5c03)
