### ISSUE TITLE
Impossibile modificare quantità riga in una fattura originata da un preventivo

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#857]
## Comportamento attuale

Creando una fattura da un preventivo, non è possibile modificare la quantità delle righe (la modifica della quantità non viene applicata)

## Passi per riprodurre il comportamento

[Per i bug] Descrivi dettagliatamente i singoli passi per riprodurre il malfunzionamento.

1. Creare un preventivo
2. Creare una fattura da un preventivo
3. Modificare la quantità di una riga
4. La quantità non è stata modificata
## Contesto

* Modulo: Fatture di vendita
* Versione del progetto: 2.4.15
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Il problema si verifica aumentando o diminuendo pa quantità?
Si noti che la quantità massima è limitata dalla quantità della riga originale del preventivo, come documentato nella descrizione del campo al momento della modifica.

**Comment by maicol07** [comment]
Aumentando. In effetti, è oltre la quantità del preventivo.
Qta preventivo: 10
Nuova qta: 11

**Comment by Dasc3er** [comment]
Il funzionamento è pertanto corretto, ma forse non visibilmente evidenziato...
Mi pare però che vanga mostrata anche la quantità massima ammessa, quindi non saprei come si potrebbe migliorare la spiegazione della funzionalità. Se hai suggerimenti scrivi pure qui, altrimenti nei prossimi giorni chiuso la issue.

**Comment by maicol07** [comment]
@Dasc3er dove? A me non sembra che venga mostrato qualcosa sulla quantità massima, neanche inserendo 11

![](https://user-images.githubusercontent.com/9463142/87874972-4d90c280-c9ce-11ea-8bf5-fe82f09f5591.png)

**Comment by Dasc3er** [comment]
@maicol07 Grazie per la segnalazione! La versione in sviluppo presentava un bug che impediva il salvataggio delle relazioni tra i documenti, che dovrebbe essere ora risolto.

**Comment by Dasc3er** [comment]
Mi correggo: a causa del merge con i riferimenti non diretti tra documenti, solo nelle fatture non veniva salvata la relazione tra le righe di altri documenti. In pratica, se adesso non viene visualizzato l'avviso sulla quantità ti consiglio di rimuovere le righe e importare di nuovo il documento.
