### ISSUE TITLE
gestionale versione 2.3 alcune funzioni ajax non funzionano su hosting aruba linux

### ISSUE THREAD

**Issue by antonioscarpino** [devcode-it/openstamanager#86]
Salve, sto provando la versione 2.3 del gestionale.
Ho riscontrato un bug su hosting aruba linux (in locale su xampp non è presente) riguardante l'inserimento degli articoli in un preventivo.
In pratica non viene caricato l'elenco degli articoli presenti nel db.
La stessa cosa succede per le unità di misura.
Facendo un piccolo debug con firefox ci sono vari errori nelle chiamate del file app.min.js

**Comment by loviuz** [comment]
ciao antonio. hai provato con la 2.3 beta scaricabile da github o con l'ultimo repository di git?

**Comment by antonioscarpino** [comment]
Ciao e grazie per la risposta.
Ho già installato la versione 2.3 beta 2 presa su github.
Se aggiorno con i file contenuti nell'ultimo repository non viene visualizzata nemmeno la pagina di login.
E' una cosa un po strana visto che provando la stessa verione 2.3 beta 2 su un serevr xampp locale gli errori non ci sono.
A questo punto penso che ci sia qualche incompatibilità con l'hosting aruba.

**Comment by Dasc3er** [comment]
Ciao @antonioscarpino,
potresti controllare se sono stati creati dei file all'interno della cartella **logs/** dell'installazione su Aruba?
In questo modo dovremmo essere in grado di vedere da cosa è stato originato il problema...

**Comment by antonioscarpino** [comment]
Buongiorno a tutti,
allego log errori.

PS.
Ho installato il gestionale su un hosting OVH con relativi aggiornamenti dei repository e tutto funziona (tranne qualche artefatto visivo).
[error.log](https://github.com/devcode-it/openstamanager/files/1592924/error.log)

**Comment by Dasc3er** [comment]
Innanzitutto grazie per il file di log, che ha permesso di individuare un'ulteriore errore in fase di installazione.

Riguardo al problema da te segnalato, sembrerebbe essere causato dalla riga 246 del file **actions.php**:
```
$id_records = post('id_records');
```
Si tratta però di un'errore decisamente strano, considerando che viene segnalato come "Function name must be a string".
Inizialmente inoltre sembra esserci un'ulteriore problema con il passaggio di un'array al posto di una stringa in un qualche punto del file **index.php** (o relativi)...

@loviuz @fpsoftware @lucasalva87 Cosa ne pensate?

@antonioscarpino Eventualmente potresti provare ad abilitare la modalità di debug per fornirci maggiori informazioni?
Basterebbe impostare nel seguente modo la riga 19 del file **config.inc.php**:
```
$debug = true;
```

**Comment by antonioscarpino** [comment]
Ho abilitato la modalità debug.
Nella creazione di un preventivo a livello di chiamate al db quindi creazione del preventivo, inserimento anagrafica e varie opzioni sembra filare tutto liscio.
Il problema nasce quando si va ad inserire una riga.
Infatti nel form d'inserimento dei valori non vengono generari gli elenchi degli articoli presenti nel magazzino e nemmeno l'elenco delle unità di misura.
Dal debug php non si riesce a vedere nulla che non vada, infatti a quanto ho capito tali elenchi vengono generati tramite delle funzioni ajax (correggetemi se mi sbaglio) che però per qualche motivo sull'host aruba danno quache errore.

qui screeshot

![errore](https://user-images.githubusercontent.com/34765237/34441255-ca5785f4-ecba-11e7-8158-28f7e1cb79b0.png)

Come puoi vedere l'elenco ariticoli non viene generato e se noti il debuger di firefox ci sono errori di chiamata tra il file edito.php, app.min.js e functions.js

**Comment by Dasc3er** [comment]
Grazie per l'approfondimento...
Gli errori JavaScript dovrebbero essere causati dal fallimento della richiesta AJAX al file **ajax_select.php**.
Potesti provare ad aggiornare solamente questo file alla versione più recente?

Si tratta però di un'errore diverso dal quello indicato nei file di log: sarebbe da testare su Aruba la versione master per controllare se il problema è già stato risolto.

**Comment by antonioscarpino** [comment]
Aggiornando solo il file ajax_select.php ci sono degli errori dovuti al fatto che probabilmente il file fa delle chiamate che non sono compatibili con la precedente versione.

Aggiornado al master non viene caricato nemmeno l'index.php dando un errore:

> Questa pagina non reindirizza in modo corretto
>
> Firefox ha rilevato che il server sta reindirizzando la richiesta per questa pagina in modo che non possa mai essere completata.

**Comment by antonioscarpino** [comment]
Fri, 29 Dec 2017  18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] - www.gestionalesa.online -  AH01215: PHP Fatal error:  Uncaught Error: Call to undefined method  Modules::get() in  /web/htdocs/www.gestionalesa.online/home/ajax_select.php:59:  /php-wrapper/php-cgi, referer  https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215: Stack trace:: /php-wrapper/php-cgi,  referer https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215: #0  /web/htdocs/www.gestionalesa.online/home/src/HTMLBuilder/Handler/SelectHandler.php(94):  include(): /php-wrapper/php-cgi, referer  https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215: #1  /web/htdocs/www.gestionalesa.online/home/src/HTMLBuilder/Handler/SelectHandler.php(33):  HTMLBuilder\\Handler\\SelectHandler->select2('clienti', Array):  /php-wrapper/php-cgi, referer  https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215: #2  /web/htdocs/www.gestionalesa.online/home/src/HTMLBuilder/HTMLBuilder.php(125):  HTMLBuilder\\Handler\\SelectHandler->handle(Array, Array):  /php-wrapper/php-cgi, referer  https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215: #3  /web/htdocs/www.gestionalesa.online/home/src/HTMLBuilder/HTMLBuilder.php(104):  HTMLBuilder\\HTMLBuilder::generate(Array): /php-wrapper/php-cgi,  referer https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215: #4  /web/htdocs/www.gestionalesa.online/home/lib/functions.php(594):  HTMLBuilder\\HTMLBuilder::replace('\\n

Fri, 29 Dec 2017  18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] - www.gestionalesa.online -  AH01215: #5 [internal function]: translateTemplate():  /php-wrapper/php-cgi, referer  https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215: #6 {main}: /php-wrapper/php-cgi,  referer https://www.gestionalesa.online/controller.php?id_module=13

Fri,  29 Dec 2017 18:21:58 GMT [error] [client xxx.xxx.xxx.xxx] -  www.gestionalesa.online - AH01215:   thrown in  /web/htdocs/www.gestionalesa.online/home/ajax_select.php on line 59:  /php-wrapper/php-cgi, referer  https://www.gestionalesa.online/controller.php?id_module=13

Ecco i log di errore

**Comment by Dasc3er** [comment]
Si, in effetti sono state effettuate un po' di modifiche anche nel file **ajax_select.php** per risolvere problemi simili.
@loviuz Qualche idea su come replicare e controllare il problema?

**Comment by antonioscarpino** [comment]
Se può servire posso mettere a disposizione l'hosting aruba per eseguire le varie prove.
Fatemi sapere

**Comment by Dasc3er** [comment]
@antonioscarpino Non è necessario!
A breve dovrebbe comunque essere rilasciata la nuova versione

**Comment by antonioscarpino** [comment]
Ok.
Comunque dovesse servire sono a disposizione.

**Comment by loviuz** [comment]
@antonioscarpino, per verificare l'errore nel tuo caso, l'unica soluzione penso sia provare direttamente su quell'hosting per eseguire un debug più approfondito. vuoi mandarci in privato i dati? poi posteremo qui solo la risoluzione del problema...

**Comment by antonioscarpino** [comment]
certo contattatemi pure su antonio.scarpino@gmail.com

**Comment by antonioscarpino** [comment]
risolto con ultimi commit
