### ISSUE TITLE
aggiungere evento js a selettore data degli interventi?

### ISSUE THREAD

**Issue by beppe9000** [devcode-it/openstamanager#861]
Vorrei aggiungere un evento al selettore dell'orario di inizio per gli interventi, in cui andrei poi ad aggiornare la data finale a aggiungendo 1h.

ho fatto diverse prove nella console del browser ma nulla sembra funzionare... qualche idea?

`$('#orario_inizio').on('changeDate', function (e) {console.log(e);});`
`$('#orario_inizio').datepicker().on('changeDate', function (e) {console.log(e);});` -> questo crea un secondo calendario
`$('#orario_inizio').datepicker("option", "onSelect", function(){}).on('changeDate', function(e) {console.log(e;)});`
`$('#orario_inizio').data('DateTimePicker').options('onSelect', function(event) {});`

`$("#orario_inizio").datepicker( 'option' , 'onSelect', function (e) {console.log(e);} );`
quest'ultimo non capisco perchè [in questo esempio](http://jsfiddle.net/nhmsZ/) funziona e dentro osm no...

**Comment by Dasc3er** [comment]
L'esempio non funziona perchè quella non è la libreria che stiamo utilizzando.
Puoi trovare un esempio qui: https://github.com/devcode-it/openstamanager/blob/f47c1ed25f308bf2e9b696205130c2212796a80a/modules/interventi/manage_sessione.php#L107

**Comment by beppe9000** [comment]
ottimo, la sintassi di inizializzazione mi aveva tratto in inganno...
penso che se ho modo provo ad implementare il fatto che vi sia sempre un'intervallo tra l'inizio e la fine, quando si modifica l'inizio. cosa che ora non sembra avvenire
<hr>
una domanda per agevolarmi lo sviluppo... è possibile scegliere tramite config (o altro modo) di servire la versione non minificata del js ?

**Comment by Dasc3er** [comment]
Per il momento non esiste una configurazione del genere, ma è sufficiente commentare la parte di minificazione delle task srcCSS e srcJS del file gulpfile.js.

**Comment by beppe9000** [comment]
aggiungo qui il codice che ho inserito in `/modules/interventi/add.php`, per agevolare la posterità:

```
<script>
                    $(document).ready(function () {
                        $("#orario_inizio").on("dp.change", function (e) {
                            let newTime = e.date.clone().add(1, 'hours');
                            setTimeout(function(){ // diamo tempo all'evento predefinito di agire
                                $("#orario_fine").data("DateTimePicker").date(newTime);
                            },200); 
                        });
                    });
</script>
```
