### ISSUE TITLE
Problemi con le stampe in PDF

### ISSUE THREAD

**Issue by gifrigio93** [devcode-it/openstamanager#862]
Buongiorno,

Da quando ho ripristinato il backup del mio gestionale alla versione 2.4.5, dopo fallimento update 2.4.6, vi allego errore che mi da appena generata una fattura e provo a stamparla:

Si è verificato un'errore [uid: adac125]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception Whoops\Exception\ErrorException: "Array and string offset access syntax with curly braces is deprecated" at /home/digitali/gest.digitaliaict.it/vendor/mpdf/mpdf/src/Mpdf.php line 2238
Si è verificato un'errore [uid: adac125]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Array and string offset access syntax with curly braces is deprecated 

Come posso risolvere? Grazie!!

**Comment by gifrigio93** [comment]
Se provo ad inviare una fattura via email esce questo errore:

Si è verificato un'errore [uid: 8ba6447]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception Whoops\Exception\ErrorException: "Array and string offset access syntax with curly braces is deprecated" at /home/digitali/gest.digitaliaict.it/vendor/mpdf/mpdf/src/Mpdf.php line 2238
Si è verificato un'errore [uid: 8ba6447]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Array and string offset access syntax with curly braces is deprecated

**Comment by Dasc3er** [comment]
La soluzione, come indicato in passato e sul Forum, consiste nell'aggiornamento della cartella vendor/ con le versioni più aggiornate delle librerie.
In particolare, con la futura versione 2.4.17 verrà aggiornato MPDF alla versione 8.*, che prevede il supporto per PHP 7.*.

Riferimento Forum: https://forum.openstamanager.com/viewtopic.php?p=103867#p103866
