### ISSUE TITLE
BUG: Prima nota

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#864]
## Comportamento

Se vado a modificare la prima nota generata durante il pagamento della fattura, il riferimento a tale fattura viene rimosso.

## Passi per riprodurre il comportamento

- Creare una fattura, emetterla e procedere con la registrazione tramite registra contabile.

- Andare al modulo prima nota e modificare la causale. Salvare

Il pulsante "VAI ALLA FATTURA" scompare. Scompare anche il riferimento nell'elenco.

OSM 2.4.15

**Comment by Dasc3er** [comment]
@idraulicadueci Non riesco a replicare il problema.

Registrazione contabile dal pulsante in Fatture:
![image](https://user-images.githubusercontent.com/15911489/89614735-582fd080-d885-11ea-975c-45d5da77e237.png)

Prima nota generata:
![image](https://user-images.githubusercontent.com/15911489/89614756-64b42900-d885-11ea-9400-9fb638f262de.png)

Prima nota con causale modificata:
![image](https://user-images.githubusercontent.com/15911489/89614789-772e6280-d885-11ea-9b29-e1fef6fbb0eb.png)

**Comment by idraulicadueci** [comment]
Ho provato anch'io a modificare una causale di una fattura dell'anno in corso e il problema non si verifica. Il problema si è verificato quando la modifica l'ho fatta su una prima nota di una fattura dell'anno scorso. 
Potrebbe essere causato dal timestamp?

**Comment by Dasc3er** [comment]
Non penso? Non c'è motivo per cui la data del movimenti o del documenti influenzi la modifica dei dati...
La modifica più consistente e recente fatta alla Prima Nota è relativa a #265, per separare in modo completo le diverse righe della prima nota sulla base dei riferimenti collegati. Questa modifica dovrebbe essere stata completamente retro-compatibile, oltre che principalmente incentrata nella grafica e la relativa logica di gestione delle singole righe.

A livello di codice, un problema simile si _potrebbe_ verificare nel caso in cui venga completamente rimossa la Scadenza collegata alla Prima Nota. Questo significa l'eliminazione diretta da **co_scadenziario** di una scadenza collegata a una Prima Nota: se poi modificassi la Prima Nota (la cui scadenza è stata rimossa), si _potrebbe perdere_ il riferimento alla fattura.
Più nel dettaglio, servirebbe quindi una Prima Nota collegata a un documento senza una Scadenza relativa. Il che è forse proprio il problema in questo caso: la Fattura, potrebbe aver avuto una Prima Nota generata prima dell'introduzione delle Scadenze in Prima Nota (?).
@lucasalva87 @loviuz Cosa ne pensate? Avete mai riscontrato un problema simile?

**Comment by Dasc3er** [comment]
@idraulicadueci Per il momento posso consigliarti di non modificare altre Prime Note risalenti a prima di Dicembre 2019 (v2.4.11)?

**Comment by Dasc3er** [comment]
@idraulicadueci Grazie per la segnalazione!
Il problema si verificava in una particolare situazione in cui l'ordine relativo delle righe della Prima Nta individuava o meno il documento relativo, ed era dovuta al fatto che la modifica effettuata aveva dato rilevanza alle scadenze in modo più consistente rispetto al documento stesso.
In ogni caso, il bug era presente solo modificando una Prima Nota precedente alla versione 2.4.11, il che dovrebbe ora essere supportato.
