### ISSUE TITLE
Mancato aggiornamento costo intervento al cambio di tipo attività

### ISSUE THREAD

**Issue by kenchu84** [devcode-it/openstamanager#865]
Scenario: 
Tipo intervento 1: costo orario 50€
Tipo intervento 2: costo orario 0€

Creo intervento di 1 hh con tipo intervento 1, chiudo intervento come completato.
Lo riapro, modifico il tipo intervento, ma il costo non viene ricalcolato.

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Intervento
*2.4.11 (75506424)

**Comment by Dasc3er** [comment]
@kenchu84 Stai modificando ill tipo dell'intervento o della singola sessione di lavoro?

**Comment by kenchu84** [comment]
Della singola sessione

Il giorno lun 10 ago 2020 alle 09:55 Thomas Zilio <notifications@github.com>
ha scritto:

**Comment by kenchu84** [comment]
Qualche novità?

**Comment by Dasc3er** [comment]
@kenchu84 Ho verificato appena adesso e il problema non si verifica.
Mi sembra però che il modulo Attività sia stato aggiornato dopo la versione 2.4.11 per avere una grafica con modal anche alla modifica delle sessioni:
![image](https://user-images.githubusercontent.com/15911489/90011523-067eb000-dca2-11ea-940e-18e71034969c.png)

Posso soltanto consigliarti di aggiornare il gestionale all'ormai prossima versione 2.4.17.

**Comment by kenchu84** [comment]
Stasera eseguo nuova installazione pulita all ultima versione e verifico..

**Comment by kenchu84** [comment]
Però quello che hai postato tu è lo screen della parte "add", li tutto ok. Io ho scritto che il problema del ricalcolo è nel pdf

**Comment by kenchu84** [comment]
Confermo, anche a me nella parte add il ricalcolo viene calcolato. Generando il pdf no.

**Comment by Dasc3er** [comment]
Non ho ben capito cosa intendi dire.
Puoi indicare passo per passo le operazioni effettuate, con screenshot?

**Comment by kenchu84** [comment]
Creo intervento, tipo : intervento a commessa ( costo orario 0 € ). Salvo. Stampo il pdf con i costi 

![image](https://user-images.githubusercontent.com/46252382/90014329-2cf31a00-dca7-11ea-914d-59edd49d9722.png)

Esco.
Riapro L intervento, cambio tipo di intervento : intervento tecnico ( costo 50 € / ora ). 
Salvo. Stampo il pdf con i costi. 
Risultato : tipo intervento in stampa corretto, costi no

![image](https://user-images.githubusercontent.com/46252382/90014444-5ca22200-dca7-11ea-9183-e320b3412ecb.png)

**Comment by Dasc3er** [comment]
Stesse operazioni, con Intervento di tipo Generico e sessione di tipo Generico
![image](https://user-images.githubusercontent.com/15911489/90016900-020ac500-dcab-11ea-995a-b22e78fc952e.png)

Con Intervento di tipo Generico e sessione di tipo Ordine di servizio (prezzi diversi)
![image](https://user-images.githubusercontent.com/15911489/90017001-28306500-dcab-11ea-91aa-598f691b45b2.png)

Con Intervento di tipo Ordine di servizio e sessione di tipo Ordine di servizio (prezzi diversi)
![image](https://user-images.githubusercontent.com/15911489/90017088-4f873200-dcab-11ea-8bfe-6b089ac76292.png)

Come già detto, ritengo tu abbia modifica solo il Tipo dell'Intervento e non quello della sessione di lavoro.

**Comment by kenchu84** [comment]
Ciao, ho fatto le prove da versione aggiornata e vergine, tutto ok . Copiato il mio modulo "templates/interventi" e si presenta il problema. Potete chiudere, farò debug sulla versione locale. Grazie per il supporto.
