### ISSUE TITLE
Errore bloccante in aggiornamento 2.4.16

### ISSUE THREAD

**Issue by clabnet** [devcode-it/openstamanager#868]
L'aggiornamento del database alla versione 2.4.16 non si è completato regolarmente ed ora l'applicativo è bloccato!

Attualmente l'applicativo risulta BLOCCATO !

Ho eseguito il backup della versione precedente ma non posso ripristinarlo se l'applicativo non parte.

Sono fermo, potete darmi una mano cortesemente ? 

Grazie,

**Comment by Dasc3er** [comment]
Ciao @clabnet ,
Puoi controllare che log sono presenti nella cartella logs/ e in particolare nel file setup.log?

**Comment by clabnet** [comment]
[
![errore-upgrade-openSTA](https://user-images.githubusercontent.com/6067610/90019258-72671580-dcae-11ea-883b-afe9ab48d77d.png)
](url)

**Comment by clabnet** [comment]
Grazie Thomas

Eccolo:

[2020-08-12 14:49:36] Logs.EMERGENCY: Aggiornamento fallito: ALTER TABLE 
`or_righe_ordini` ADD `id_dettaglio_fornitore` int(11) NULL,
   ADD FOREIGN KEY (`id_dettaglio_fornitore`) REFERENCES 
`mg_fornitore_articolo`(`id`) ON DELETE SET NULL []
{"url":"/opensta/index.php?action=do_update&firstuse=false","ip":"151.32.169.62","http_method":"GET","server":"work.oberonsecurity.com","referrer":"https://work.oberonsecurity.com/opensta/index.php","unique_id":"XzPlYCiUVozcCiY6dV8FTQAAACQ","uid":"25630e3"}

**Comment by clabnet** [comment]
Questo invece il file error.log

**Comment by Dasc3er** [comment]
Puoi fare una modifica al file **update/2_4_16.sql**?
https://github.com/devcode-it/openstamanager/blob/cd8c6bccdbdd15543313d72f6269a0dee5afcc4f/update/2_4_16.sql#L86
Alla riga 86 (visibile sopra) riusciresti a modificare in questo modo:
`
ALTER TABLE mg_fornitore_articolo ENGINE = InnoDB;
ALTER TABLE `or_righe_ordini` ADD `id_dettaglio_fornitore` int(11) NULL DEFAULT NULL,
  ADD FOREIGN KEY (`id_dettaglio_fornitore`) REFERENCES `mg_fornitore_articolo`(`id`) ON DELETE SET NULL;
`

**Comment by Dasc3er** [comment]
Dopodichè puoi provare a far riprendere l'aggiornamento aggiungendo `?force` all'URL della pagina principale?

**Comment by clabnet** [comment]
Certo lo faccio subito.

Vedo che questa fa un aggiornamento della struttura di un'altra tabella.

Quindi deduco che questa riga vada inserita PRIMA della riga 86, è 
corretto ?

**Comment by Dasc3er** [comment]
Esatto, in questo modo (prima era formattato male):
```
ALTER TABLE mg_fornitore_articolo ENGINE = InnoDB;
ALTER TABLE `or_righe_ordini` ADD `id_dettaglio_fornitore` int(11) NULL DEFAULT NULL,
  ADD FOREIGN KEY (`id_dettaglio_fornitore`) REFERENCES `mg_fornitore_articolo`(`id`) ON DELETE SET NULL;
```

In pratica, devi aggiungere `ALTER TABLE mg_fornitore_articolo ENGINE = InnoDB;` prima della riga esistente.

**Comment by clabnet** [comment]
Bravo Thomas,

ha funzionato. L'applicativo è ripartito e la versione risulta aggiornata.

Ti ringrazio per la qualità e l'eccellente tempestività della risposta.

Grazie, saluti

Claudio

**Comment by Dasc3er** [comment]
Grazie a te, ci hai permesso di verificare la soluzione effettiva al problema!
Buona giornata!
