### ISSUE TITLE
Dati mancanti nel widget attività da pianificare

### ISSUE THREAD

**Issue by Technology-Solutions** [devcode-it/openstamanager#869]
All'interno del widget attività da pianificare, non vengono popolati i campi "cliente" e "tipo intervento"

Nella versione 2.4.12 funzionava
![WIDGET_DA-PANIFICARE](https://user-images.githubusercontent.com/52965320/90149231-9006ae80-dd84-11ea-8d36-e1087e153acb.jpg)

**Comment by Dasc3er** [comment]
Ho appena verificato, e il funzionamento è corretto nella versione più recente.
In che versione si verifica il problema?
