### ISSUE TITLE
FATTURE - Calcolo errato IVA e arrotondamenti IVA

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#87]
Da una fattura che richiama un intervento, il calcolo dell'iva viene sbagliato:
viene calcolato due volte l'iva sul diritto di chiamata.
Allego immagine fattura emessa con altro programma, dove viene calcolata correttamente l'aliquota iva.
![image](https://user-images.githubusercontent.com/34273200/34424295-c54d7660-ec22-11e7-8569-2dfa1ee50606.png)

Fattura su OSM:
![image](https://user-images.githubusercontent.com/34273200/34424312-dbcaa78c-ec22-11e7-9aee-b793d33eb752.png)

Rifacendo i conti su un xls, si capisce che la differenza è proprio la cifra 3,84:
![image](https://user-images.githubusercontent.com/34273200/34424337-0d7df112-ec23-11e7-8c27-4ab9ff77ffef.png)

------------------------
Arrotonda erroneamente:
![image](https://user-images.githubusercontent.com/34273200/34424376-62a0d498-ec23-11e7-8ce5-4d12c7c86716.png)

Il totale IVA è diverso dall'importo IVA.

**Comment by Dasc3er** [comment]
Ciao @fgambarelli ,
il bug dovrebbe essere stato risolto con il commit ff678eb60055f511ca42cef828ce9d6e461b312b.
Se stai usando la versione master dalla repository, potresti  confermare la risoluzione del problema?

**Comment by fgambarelli** [comment]
Il primo problema è un calcolo sbagliato sull'imponibile dell'iva, il commit non lo risolve.
Mentre l'arrotondamento sembra risolto.

**Comment by Dasc3er** [comment]
Si, in effetti non avevo considerato il primo punto segnalato...

**Comment by loviuz** [comment]
Dall'array che calcolava il totale manodopera ho separato il diritto di chiamata, era quello che creava forse confusione nei calcoli in fattura. In più, nell'intervento, nella tabella dei costi, ho aggiunto la voce del diritto di chiamata in una riga a parte, così è più chiara la lettura.
Se qualcun'altro vuole provare per confermare il fix... grazie :-)

**Comment by loviuz** [comment]
Appena corretto il calcolo anche nei consuntivi di Preventivi e Contratti, perché nel totale manodopera veniva sommato anche il diritto di chiamata.

**Comment by Dasc3er** [comment]
@loviuz Il problema è stato quindi risolto completamente?

**Comment by loviuz** [comment]
yesss! se qualcun'altro potesse provare non mi dispiacerebbe :-)

**Comment by Dasc3er** [comment]
@fgambarelli Puoi confermare la risoluzione del problema?

**Comment by fgambarelli** [comment]
Verificherò sabato mattina.

**Comment by Dasc3er** [comment]
@fgambarelli Puoi confermare la risoluzione del problema?

**Comment by Dasc3er** [comment]
@fgambarelli Novità?

**Comment by fgambarelli** [comment]
Confermo OK
