### ISSUE TITLE
Problema creazione articoli da importazione fattura elettronica - vengono creati duplicati articoli

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#870]
## Comportamento richiesto

Creazione di articoli se non presenti nel gestionale quando importo una fattura elettronica di un fornitore

## Comportamento attuale

Vengono creati X articoli  con lo stesso codice per articolo dove X non è un numero definito

## Passi per riprodurre il comportamento

- Importazione di una fattura elettronica di un fornitore
- Nella fattura ci devono essere articoli non ancora presenti nel gestionale
- attraverso l'apposito tasto nel modal inserisco i dati mancanti confermando gli 'articoli
- quando confermo la procedura di importazione risulteranno poi diversi articoli duplicati nel database

## Contesto

Nella versione 2.4.15 funziona correttamente l'importazione

* Modulo: fattura acquisti
* Versione del progetto: 2.4.16
* Versione PHP: 7.3.19-1
* Tipo di server: debian Apache/2.4.38

**Comment by lepool** [comment]
Ho anche notato che il browser ha un utilizzo del 100% della CPU. Ho fatto l'aggiornamento dalla 2.4.15 alla 2.4.16. Il problema persiste anche nella versione 2.4.17 .

**Comment by lepool** [comment]
Provato ora con una installazione fresca della 2.4.17. Stesso problema.

**Comment by lepool** [comment]
Il problema non si presenta con la generazione automatica degli articoli, ma solamente usando il tasto creazione manuale dell'articolo.

**Comment by Dasc3er** [comment]
Ciao @lepool ,
non sono riuscito a replicare il problema.
La gestione delle fattura elettroniche non è stata modificata nelle ultime versioni se non per l'aggiunta di commenti e correzioni minori, come puoi controllare dalla cronologia dei file relativi.

Il comportamento previsto è il seguente:
- Se crei manualmente un articolo per la riga, viene selezionato in automatico per la riga stessa
- Se esiste un articolo con lo stesso codice della fattura elettronica, viene selezionato in automatico

 La generazione automatica dell'articolo procede quindi in questo modo:
- Se una riga ha un articolo associato,  non genera niente
- Se una riga non ha un articolo associato ma ha dati relativi a un articolo dalla fattura elettronica, genera in automatico un articolo di conseguenza

Non saprei dirti nel tuo caso dove si verifica il problema.

**Comment by lepool** [comment]
provo su un altro server e faccio sapere

**Comment by lepool** [comment]
@Dasc3er , puoi indicarmi le tue impostazioni php.ini?

**Comment by Dasc3er** [comment]
Le impostazioni php.ini non dovrebbero essere rilevanti.
Le uniche che ho modificato sono quelle per il caricamento degli allegati (post_max_size e upload_max_filesize), ma non influenzando questa componente.

**Comment by lepool** [comment]
provato ora su un altro server
apache2
php7.3
mysql 8.0.21
osm 2.4.17

stesso problema

**Comment by lepool** [comment]
@Dasc3er , ho salvato il traffico tra browser e server. Ti potrebbe essere utile?

**Comment by Dasc3er** [comment]
@lepool Sarebbe più utile se riuscissi a indicare con screenshot tutti i passaggi fatti, rimuovendo i dati personali relativi.
Questo ovviamente se hai tempo, altrimenti proveremo nuovamente nei prossimi giorni a verificare il problema.

**Comment by lepool** [comment]
questa sera invio gli screenshot

**Comment by lepool** [comment]
- Installazione fresca osm 2.4.17
- importo la mia prima fattura di acquisto allegata
- seguo i passi indicati negli screenshot per inserire manualmente gli articoli
- alla verifica negli articoli risultano dei ricambi duplicati

[fattura_elettronica001.zip](https://github.com/devcode-it/openstamanager/files/5141992/fattura_elettronica001.zip)

![Bildschirmfoto von »2020-08-28 14-06-48«](https://user-images.githubusercontent.com/32035706/91560106-8d39bb00-e939-11ea-9347-26e74e5eaf26.png)
![Bildschirmfoto von »2020-08-28 14-06-58«](https://user-images.githubusercontent.com/32035706/91560118-92970580-e939-11ea-9418-eb6b2a7dcabe.png)
![Bildschirmfoto von »2020-08-28 14-07-15«](https://user-images.githubusercontent.com/32035706/91560123-94f95f80-e939-11ea-8f00-4edea14ff046.png)
![Bildschirmfoto von »2020-08-28 14-07-20«](https://user-images.githubusercontent.com/32035706/91560137-9b87d700-e939-11ea-9a37-fb0c47e4d6eb.png)
![Bildschirmfoto von »2020-08-28 14-07-23«](https://user-images.githubusercontent.com/32035706/91560145-9d519a80-e939-11ea-8fd5-b077f2044103.png)
![Bildschirmfoto von »2020-08-28 14-07-27«](https://user-images.githubusercontent.com/32035706/91560150-9f1b5e00-e939-11ea-8970-c3392194e26b.png)
![Bildschirmfoto von »2020-08-28 14-07-32«](https://user-images.githubusercontent.com/32035706/91560152-a0e52180-e939-11ea-8b63-22c4f835a989.png)
![Bildschirmfoto von »2020-08-28 14-07-35«](https://user-images.githubusercontent.com/32035706/91560157-a2164e80-e939-11ea-9198-0620bf329137.png)
![Bildschirmfoto von »2020-08-28 14-08-15«](https://user-images.githubusercontent.com/32035706/91560160-a3e01200-e939-11ea-8a81-d1027f2f647f.png)

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione, oltre che per il file di esempio e gli screenshot!
Il problema era infatti abbastanza difficile da individuare, e si presentava solo nel caso in cui si effettuava la generazione manuale di più articoli nella stessa pagina.
