### ISSUE TITLE
Errore modifica `em_templates` durante aggiornamento v2.4.11

### ISSUE THREAD

**Issue by bebbus** [devcode-it/openstamanager#871]
Dopo il download del file e upload in ftp sul server ho il blocco al passo 17 di 23

```
Installazione
E' la prima volta che avvii OpenSTAManager e non hai ancora installato il database.

Premi il tasto "Installa!" per procedere con l'installazione!

76%
Log
Aggiornamento 1 di 23 (2.0)

     Aggiornamento del database (2_0.sql)

Aggiornamento 2 di 23 (2.1)

     Aggiornamento del database (2_1.sql)

     Esecuzione dello script di aggiornamento (2_1.php)

Aggiornamento 3 di 23 (2.2)

     Aggiornamento del database (2_2.sql)

     Esecuzione dello script di aggiornamento (2_2.php)

Aggiornamento 4 di 23 (2.3)

     Aggiornamento del database (2_3.sql)

     Esecuzione dello script di aggiornamento (2_3.php)

Aggiornamento 5 di 23 (2.3.1)

     Aggiornamento del database (2_3_1.sql)

     Esecuzione dello script di aggiornamento (2_3_1.php)

Aggiornamento 6 di 23 (2.4)

     Aggiornamento del database (2_4.sql)

     Esecuzione dello script di aggiornamento (2_4.php)

Aggiornamento 7 di 23 (2.4.1)

     Aggiornamento del database (2_4_1.sql)

Aggiornamento 8 di 23 (2.4.2)

     Aggiornamento del database (2_4_2.sql)

     Esecuzione dello script di aggiornamento (2_4_2.php)

Aggiornamento 9 di 23 (2.4.3)

     Aggiornamento del database (2_4_3.sql)

     Esecuzione dello script di aggiornamento (2_4_3.php)

Aggiornamento 10 di 23 (2.4.4)

     Aggiornamento del database (2_4_4.sql)

     Esecuzione dello script di aggiornamento (2_4_4.php)

Aggiornamento 11 di 23 (2.4.5)

     Aggiornamento del database (2_4_5.sql)

Aggiornamento 12 di 23 (2.4.6)

     Aggiornamento del database (2_4_6.sql)

     Esecuzione dello script di aggiornamento (2_4_6.php)

Aggiornamento 13 di 23 (2.4.7)

     Aggiornamento del database (2_4_7.sql)

     Esecuzione dello script di aggiornamento (2_4_7.php)

Aggiornamento 14 di 23 (2.4.8)

     Aggiornamento del database (2_4_8.sql)

Aggiornamento 15 di 23 (2.4.9)

     Aggiornamento del database (2_4_9.sql)

     Esecuzione dello script di aggiornamento (2_4_9.php)

Aggiornamento 16 di 23 (2.4.10)

     Aggiornamento del database (2_4_10.sql)

     Esecuzione dello script di aggiornamento (2_4_10.php)

Aggiornamento 17 di 23 (2.4.11)

 Errore durante l'esecuzione dell'aggiornamento alla versione 2.4.11
```

Eventuali log relativi (cartella **logs/**):
```
setup.log
[2020-08-25 13:21:00] Logs.EMERGENCY: Aggiornamento fallito: ALTER TABLE `em_templates` CHANGE `id_smtp` `id_account` INT(11) NOT NULL []
{"url":"/ticket/index.php?action=do_update&firstuse=true","ip":"89.207.111.114","http_method":"GET","server":"www.xxxx.it","referrer":"http://www.xxxx.it/ticket/index.php","unique_id":"X0T0G38AAAEAABvb0icAAACW","uid":"134d2a7"} 
```

## Contesto

* Versione del progetto: 2.4.17
* Versione PHP 7.1.11
* Tipo di server: aruba linux

**Comment by Dasc3er** [comment]
Ciao @bebbus ,
Il problema in questo caso si verifica durante l'aggiornamento della versione 2.4.11.
Nel forum era stato presentato lo stesso errore, e sembra che qualcuno sia riuscito a risolvere: https://forum.openstamanager.com/viewtopic.php?p=103408#p103408

Puoi controllare se la risposta è completa e funzionante per te?

**Comment by bebbus** [comment]
non riesco a registrarmi sul forum. cmq ho letto ma lanciando lequery da mysql.aruba.it/phpMyAdmin-5 ho come risposta Table 'Sql732045_3.zz_emails' doesn't exist su tutte le query  puoi scrivermi in privato se vuoi collegarti con anydesk

**Comment by bebbus** [comment]
cmq l'installazione era vergine partendo dalla 2.4.17

**Comment by Dasc3er** [comment]
Posso chiederti che versione di MySQL hai in utilizzo?
Nel caso sia precedente alla 5.7, puoi provare ad aggiornare almeno alla 5.7?

**Comment by bebbus** [comment]
purtroppo con aruba non posso migrare alla versione superiore alla 5.7 ho 5.6.6

**Comment by idraulicadueci** [comment]
Il mio piano di Aruba non mi permette il cambio di versione. Ovvero il cambio di versione è a pagamento. Prima dell'acquisto, dovrei essere sicuro che con l'aggiornamento di versione il problema si risolve.

**Comment by Dasc3er** [comment]
L'alternativa in questo caso è che riusciate a effettuare un po' di debug per verificare quale è la causa del malfunzionamento per la query:
```sql
ALTER TABLE `em_templates` CHANGE `id_smtp` `id_account` INT(11) NOT NULL;
```

Potete anche considerare di acquistare un pacchetto di supporto dagli sviluppatori ufficiali, per ottenere un assistenza diretta e puntuale. In alternativa, dovreste provare ad eseguire la query su PHPMyAdmin e sperimentare sulla soluzione indicata nel forum.

**Comment by Dasc3er** [comment]
Nel forum la soluzione indicata consiste nella rimozione delle chiavi esterne con la seguente query:
```sql
ALTER TABLE `em_templates` DROP FOREIGN KEY `zz_emails_ibfk_1`, DROP FOREIGN KEY `zz_emails_ibfk_2`;
```

**Comment by idraulicadueci** [comment]
Se può tornare utile, nel mio caso, l'errore bloccante era dato dal comando SQL

``ALTER TABLE `mg_prodotti` DROP FOREIGN KEY `mg_prodotti_ibfk_4``

nel file di UPDATE 2_4_16.sql

Eliminando la riga tutto procede per il verso giusto. Devo constatare ancora se il gestionale funziona.

**Comment by Dasc3er** [comment]
Il tuo caso è quindi distinto da quello della issue corrente, che riguarda l'aggiornamento durante il passaggio per la versione 2.4.11.
Ottimo però che tu sia riuscito a trovare il problema, può essere di riferimento ad altri utenti :smile:

**Comment by idraulicadueci** [comment]
Si fa quel che si può. 
Nei prossimi giorni provo la nuova versione sul lato produzione. Comunque le ultime modifiche sono veramente eccellenti. Ottimo lavoro come sempre!!

**Comment by idraulicadueci** [comment]
Questo invece è l'errore che mi dà in fase di aggiornamento sul lato server Aruba.
[error.log](https://github.com/devcode-it/openstamanager/files/5127795/error.log)

**Comment by Dasc3er** [comment]
Questo errore è stato più complesso da individuare, e viene risolto da questo commit: https://github.com/devcode-it/openstamanager/commit/3318f97434e596ea8869137092f09aa0152da58c
Dovrebbe essere sufficiente fare la modifica e far riprendere l'aggiornamento.

**Comment by bebbus** [comment]
ma perchè se installo l'ultima versione vengono lanciate le query di tutte le versioni? quello che non funziona nel mio caso è installazione della 2.4.17 che prova ad installare la 2.4.11

**Comment by idraulicadueci** [comment]
> Questo errore è stato più complesso da individuare, e viene risolto da questo commit: [3318f97](https://github.com/devcode-it/openstamanager/commit/3318f97434e596ea8869137092f09aa0152da58c)
> Dovrebbe essere sufficiente fare la modifica e far riprendere l'aggiornamento.

credo che il problema sia un altro, perché facendo l'aggiornamento da windows il problema non si presenta, invece da piattaforma linux mi scombina tutti i file PHP.
Da windows ho fatto nuovamente l'upload via FTP delle nuova versione e tutto è andato a buon fine.

**Comment by Dasc3er** [comment]
@idraulicadueci Credo dipenda dal metodo che utilizza PHP per l'inclusione dei percorsi. In ogni caso, il problema è causato da una funzione che viene temporaneamente duplicata durante l'aggiornamento. Se modifichi la funzione come nel commit, dovrebbe riprendere tutto correttamente.

@bebbus La procedura di installazione e aggiornamento di OpenSTAManager è sequenziale: per installare l'ultima versione del database è necessario passare per tutte le versioni precedenti. È quindi corretto che vengano installate tutte le versioni dalla 2.0 in poi. Il problema si verifica in particolare durante l'aggiornamento del database per la versione 2.4.11, dove una query va in errore. 
Riesci a controllare se la query che ti ho indicato sopra funziona per il tuo caso, e se il post relativo nel forum ha informazioni di interesse?

**Comment by bebbus** [comment]
@Dasc3er  ciao se lancio questa, 

ALTER TABLE `em_templates` DROP FOREIGN KEY `zz_emails_ibfk_1`, DROP FOREIGN KEY `zz_emails_ibfk_2`; 

ho come risposta questa.:

#1025 - Error on rename of './Sql732045_3/em_templates' to './Sql732045_3/#sql2-b4a4-853e647' (errno: 152)
come si potrebbe riparare la query nel file di aggiornamento del fil e 2.4.11...

**Comment by Dasc3er** [comment]
Puoi provare ad eseguire le istruzioni della prima risposta a questo link? https://stackoverflow.com/a/4081101

**Comment by Dasc3er** [comment]
Il problema si verificava con MariaDB e non MySQL. In ogni caso, è ora presente un fix relativo.
Non viene assicurato il funzionamento corretto con DBMS diversi da MySQL.
