### ISSUE TITLE
Problema inserimento articolo in attività

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#873]
## Comportamento attuale

Provando a inserire un articolo in attività (pulsante 
![immagine](https://user-images.githubusercontent.com/40104356/91288779-aef83e00-e791-11ea-9ff1-e88c5a5fa0a8.png)
non mi appare la schermata di inserimento. Non viene generato alcun file error.log.

## Passi per riprodurre il comportamento

Creare una nuova attività
Cliccare sul pulsante 
![immagine](https://user-images.githubusercontent.com/40104356/91289054-11513e80-e792-11ea-8bd4-dc5e1282a8bb.png)

OSM 2.4.17
Modulo INTERVENTI

**Comment by idraulicadueci** [comment]
Potrebbe dipendere dal fatto che ho eliminato la riga che bloccava l'aggiornamento alla versione 2.4.16 cioè:

`ALTER TABLE `mg_prodotti` DROP FOREIGN KEY `mg_prodotti_ibfk_4`

**Comment by Dasc3er** [comment]
Non credo dipenda dalla query che hai evitato.
Ho appena verificato e nella mia installazione locale funziona correttamente. Puoi provare a cancellare la cache del browser?
Inoltre puoi vedere se ci sono degli errori indicati nella console del browser?

**Comment by idraulicadueci** [comment]
Il problema si verifica su Firefox, mentre su Chrome funziona tutto. Se mi dici cosa ti serve del debug di firefox, te lo posto.

**Comment by Dasc3er** [comment]
Grazie per aver specificato Firefox, ho individuato un problema sui pulsanti che però potrebbe essere diverso: https://github.com/devcode-it/openstamanager/commit/1d44f64cb6e58938f40e677168feaf41f2577ca6
Puoi provare a replicare la modifica sulle Attività e vedere se il problema si verifica ancora?

**Comment by idraulicadueci** [comment]
Fatto. Ti confermo che con il commit il problema è stato risolto. :+1:

**Comment by Dasc3er** [comment]
Grazie ancora per la segnalazione!

**Comment by idraulicadueci** [comment]
Scusa, mi correggo. Ho verificato anche il modulo preventivi, e il problema c'è ancora. Non ho verificato gli altri moduli, a parte quello delle attività che funziona sia senza modifica che con la modifica (commit  1d44f64).
Anche ripristinando i file il problema si presenta, tranne che per il modulo attività (solo se aperto in Chrome).

Questo è il file log 
[error.log](https://github.com/devcode-it/openstamanager/files/5131587/error.log)

**Comment by idraulicadueci** [comment]
Ho provato a fare un'installazione in locale, identica a quella che avevo eseguito su server e l'errore non si presenta. In locale la versione di mysql è aggiornata. **Credo che a questo punto dipenda dalla versione di mysql che ho sul server che è antecedente alla 5.7.**
Ti confermo anche che applicando il commit  1d44f64 funziona tutto anche in firefox.

**Comment by Dasc3er** [comment]
Non credo, sembra che ti manchino alcune modifiche della versione 2.4.16.
Puoi provare ad eseguire manualmente le query di questo file da qui in poi?
 https://github.com/devcode-it/openstamanager/blob/6096979f430ad9c2f8996aa553569d08d15b7b02/update/2_4_16.sql#L112

**Comment by idraulicadueci** [comment]
Ok. Quindi resta da capire come può essere che facendo l'aggiornamento della versione 2.4.15 a 2.4.17 l'unico errore me lo dà il comando sql

  `ALTER TABLE `co_contratti` ADD COLUMN `tipo_validita` ENUM('days', 'months', 'years') NULL DEFAULT NULL AFTER `validita`; `

dopo la cui eliminazione l'installazione si completa senza ulteriori errori e il comando che mi hai appena indicato non venga eseguito...

Provo a dare il comando e ti aggiorno...

**Comment by Dasc3er** [comment]
Quando chiedi qui come risolvere un qualche bug e ti viene detto di utilizzare un determinato commit, esattamente cosa fai?
Perchè solitamente quando diciamo che la soluzione è in uno specifico commit, è sufficiente e necessario replicare solo quel commit e non tutti i precedenti o successivi...

**Comment by idraulicadueci** [comment]
> 
> 
> Quando chiedi qui come risolvere un qualche bug e ti viene detto di utilizzare un determinato commit, esattamente cosa fai?
> Perchè solitamente quando diciamo che la soluzione è in uno specifico commit, è sufficiente e necessario replicare solo quel commit e non tutti i precedenti o successivi...

Mi limito semplicemente a modificare i file indicati nel commit. è probabile che abbia commesso qualche errore importando i file. Comunque per quanto riguarda l'aggiornamento del database, ho fatto la procedura automatica di OSM, quindi è qui che non capisco come mai non sia stato inserito il campo. Qui mi viene il dubbio della compatibilità con versioni precedenti alla 5.7 di mysql. Poi non si spiega perché in locale funziona tutto (mysql 5.7) e sul server no (versione precedente 5.6.44)
