### ISSUE TITLE
Problema con l'inserimento fornitore articolo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#874]
## Comportamento attuale

Il plugin FORNITORI non funziona

## Passi per riprodurre il comportamento

1. Apro modulo articoli
2. Inserisco un nuovo articolo o apro un articolo esistente
3. Clicco su FORNITORI
4. Nell'elenco a discesa scelgo un fornitore e clicco aggiungi

Il modulo non va avanti
[error.log](https://github.com/devcode-it/openstamanager/files/5131469/error.log)

OSM 2.4.17

Modulo ARTICOLI

**Comment by idraulicadueci** [comment]
Il problema si verifica dopo aver applicato il commit  1d44f64 (vedi issue #873)

**Comment by Dasc3er** [comment]
@idraulicadueci Il commit che hai indicato non è la causa del problema, ma una modifica che hai fatto sul plugin Fornitori.
Credo tu abbia erroneamente importato anche altri commit, come https://github.com/devcode-it/openstamanager/commit/8ccee151f9d8841f5ae1dd250f8847128d2878ea

**Comment by idraulicadueci** [comment]
Per adesso ho riportato tutto alla versione 2.4.15, perché ho necessità di utilizzare il gestionale in produzione. Appena ho un po' di tempo, creo uno spazio su server dedicato a testare la nuova versione. Grazie per il tuo tempo prezioso, non voglio approfittarne oltre. Se ho novità, le posto, sperando di essere utile per altri utenti. :+1:

**Comment by Dasc3er** [comment]
Nessun problema, siamo sempre disponibili per ricercare bug e risolverli :smile: 
Mi dispiace che per il momento non siamo riusciti a individuare il problema di questo caso, ma vedremo con informazioni future e in base ad altre segnalazioni.

**Comment by idraulicadueci** [comment]
Ho creato uno spazio per test parallelo. In questo caso ho cambiato procedura:
ho fatto una installazione pulita di OSM 2.4.15
ho ripristinato la cartella files
ho ripristinato il database salvato con il backup della versione 2.4.15
ho fatto l'aggiornamento alla versione 2.4.17

Adesso sembra tutto a posto. Cercherò di capire cosa causasse il problema.

Grazie mille

**Comment by idraulicadueci** [comment]
> Ho creato uno spazio per test parallelo. In questo caso ho cambiato procedura:
> ho fatto una installazione pulita di OSM 2.4.15
> ho ripristinato la cartella files
> ho ripristinato il database salvato con il backup della versione 2.4.15
> ho fatto l'aggiornamento alla versione 2.4.17
> 
> Adesso sembra tutto a posto. Cercherò di capire cosa causasse il problema.
> 
> Grazie mille

Al fine di chiudere l'issue, ti comunico che facendo questa procedura, la nuova versione 2.4.17 funziona perfettamente. Quindi escludo bug della versione.

**Comment by Dasc3er** [comment]
Grazie! Può essersi trattato di un problema con l'applicazione di alcune modifiche, quindi per il momento chiudo la issue.
Se ci sono ulteriori problemi segnalali pure! 😄
