### ISSUE TITLE
MIGLIORIA: Introduzione Codice Interno nel modulo articoli

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#876]
Con l'introduzione del plugin "Fornitori" nel modulo articoli, si semplifica il rintracciamento dell'articolo in fase di registrazione dei documenti di acquisto. Resta però il problema della difficoltà nel rintracciare mediante codice l'articolo in fase di compilazione di documenti di vendita, perché è impossibile ricordare a memoria tutti i codici fornitore; anche la ricerca mediante descrizione non sempre è agevole.
Nella mia azienda per ovviare a questo problema ho introdotto una nomenclatura standard che segue una logica nella codifica, quindi è facile ricordare o risalire al codice in base alla tipologia di prodotto, indifferentemente dai diversi codici fornitore che assume il prodotto stesso. Quindi il codice interno può essere uguale per più codici fornitore dello stesso prodotto.
La logica di codifica infatti segue questa sequenza logica:

![IMG03](https://user-images.githubusercontent.com/40104356/91637614-06a0de80-ea0a-11ea-81e6-0d1b18fc6e8d.jpg)

In OSM questa logica può essere seguita introducendo il campo **Codice Interno**.
Quindi alla creazione di un articolo metto il **codice principale = codice produttore**, il **codice interno** della propria azienda e mediante il plugin "fornitori" inserisco i **codici fornitore**. 

In questo modo sono in grado di richiamare l'articolo in fase di compilazione di un documento di vendita utilizzando il codice interno.

Allego lo zip con i file che ho modificato per avere la funzionalità

[Introduzione CODICE INTERNO.zip](https://github.com/devcode-it/openstamanager/files/5145238/Introduzione.CODICE.INTERNO.zip)

**Comment by Dasc3er** [comment]
@idraulicadueci Il sistema dei codici è molto più semplice di quanto tu abbia indicato.
Ogni articolo ha un proprio codice, che corrisponde al codice interno dell'azienda che viene utilizzato per la vendita.
Per ogni fornitore è possibile definire un codice di acquisto personalizzato, che comunque viene indicato in automatico solo ed esclusivamente nelle fatture di acquisto. Nelle fatture di vendita resta sempre disponibile il codice originale.

Mi sembra quindi che l'unico miglioramento utile per l'identificazione dell'articolo sarebbe indicare graficamente sia codice di vendita che codice di acquisto per le fatture di acquisto al momento della selezione.

**Comment by idraulicadueci** [comment]
Sì è corretto quanto dici, con l'introduzione del plugin fornitori il modulo articoli ha fatto un grosso passo in avanti. Nel mio caso avevo la necessità di rintracciare tramite i miei codici interni il prodotto, indicandolo nei documenti di vendita con il codice produttore. Questo mi evita di inserire il codice nella descrizione dell'articolo (per es. Codice ABCD - Descrizione: Nome articolo cod. fornitore XYZ). Questo aiuta nel rintracciare le schede tecniche di determinati articoli da chiunque digitandolo come chiave di ricerca su internet o ricercandolo direttamente sul catalogo, cosa che non darebbe risultati se ricercato tramite il mio codice interno.

**Comment by idraulicadueci** [comment]
Potrebbe quindi essere utile su questa linea di ragionamento implementare, anziché il codice interno, il codice fornitore, magari facendolo aggiungere in automatico alla descrizione, se valorizzato in anagrafica articoli.

**Comment by Dasc3er** [comment]
Quello che non ho ben capito è la motivazione nel tenere separato il codice interno da te indicato con il codice di vendita, ovvero il codice produttore secondo la tua spiegazione.
Se l'obiettivo è aggiungere un codice secondario con cui identificare un articolo, la faccenda è risolvibile abbastanza facilmente con una semplice personalizzazione... Quale sarebbe il caso d'uso più generale?

**Comment by idraulicadueci** [comment]
Riprendendo la discussione, per meglio intenderci, il campo da me introdotto sarebbe stato alla stregua di un alias, un modo per rintracciare più facilmente un articolo. Se un articolo che ha un codice che mal si ricorda, chiamandolo con una nomenclatura più semplice, si può rintracciare più facilmente.

Per esempio, in magazzino ho articoli dello stesso fabbricante, della stessa categoria, con desinenze di stringa simili, e un codice assurdo ARN002345673456 (!!), la ricerca per descrizione mi restituisce 10 o anche 15 risultati. Un po' troppi per rendere agevole l'inserimento nei documenti. Articoli senza etichetta ne' confezione, neanche il Santo Codice a Barre ci può aiutare!! Un alias invece sarebbe l'ideale, perché sarebbe un codice che richiama l'articolo, ma che poi lo restituisce con il suo codice assurdo ARN002345673456. Poi è anche vero che il mondo è pieno di persone che ricordano a memoria l'elenco telefonico di Milano.... :smiley:
