### ISSUE TITLE
MIGLIORIA:  Problema con lo scadenzario

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#877]
## Comportamento richiesto

Cambiare la logica di gestione delle scadenze. La logica dovrebbe seguire il seguente flusso:

![img](https://user-images.githubusercontent.com/40104356/91657744-9bb3de00-eac3-11ea-811f-dacb7e790e80.png)

## Comportamento attuale

Attualmente se ho una fattura con pagamento suddiviso in più rate, se mando insoluta la prima rata, al momento che faccio la registrazione contabile, non registro la seconda rata, ma la prima.

## Possibile soluzione

Introdurre un modal in cui seleziono mediante radio button la rata di cui registro il pagamento, oppure introdurre un flag "INSOLUTO" accanto alla rata in scadenzario, in modo che alla registrazione del pagamento viene presa in considerazione la rata successiva non flaggata.
Inoltre ho notato che se registro il pagamento direttamente in scadenzario, valorizzando il campo "pagato", manualmente, non trovo poi l'operazione in prima nota, quindi anche in questo caso va introdotto un modal per l'apertura del modulo "prima nota", oppure rendere il campo non editabile.

![immagine](https://user-images.githubusercontent.com/40104356/91657832-a7ec6b00-eac4-11ea-99e5-e6c6115a88d8.png)

**Comment by Dasc3er** [comment]
Per quanto riguarda il problema dei pagamenti di una specifica rata, è certamente sensato introdurre una selezione di una specifica scadenza della fattura.

Per il secondo problema, per registrare il movimento in Prima Nota esiste già il pulsante "Registra contabile pagamento":
![image](https://user-images.githubusercontent.com/15911489/91693950-1b958300-eb6c-11ea-901a-3585bbca08ff.png)
Anche in questo caso può essere utile permettere la selezione di una specifica scadenza tra il gruppo. relativo al documento.

**Comment by idraulicadueci** [comment]
Al di là che ho sbagliato, (in quanto il numero che ho inserito doveva essere negativo), avevo usato questa procedura per ovviare al problema descritto ("..se mando insoluta la prima rata, al momento che faccio la registrazione contabile, non registro la seconda rata, ma la prima"..). In fattura la scadenza viene correttamente barrata, però con questo sistema non viene generata la prima nota. E' per questo motivo che avevo indicato il secondo problema.

**Comment by Pek5892** [comment]
Nella corrente versione è possibile registrare in prima nota il movimento contabile relativo all'insoluto tramite apposito pulsante dalla fattura di vendita, la scadenza viene così barrata e il movimento in prima nota viene correttamente registrato. In questo modo il pagamento successivo andrà registrato correttamente in corrispondenza alla rispettiva data.
