### ISSUE TITLE
BUG anagrafiche

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#878]
Al salvataggio di un'anagrafica si presenta questo errore: Si è verificato un'errore [uid: 2fe137f]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception Whoops\Exception\ErrorException: "Array and string offset access syntax with curly braces is deprecated" at /web/htdocs/www.*****.it/home/osm/vendor/davidepastore/codice-fiscale/src/CodiceFiscale/Validator.php line 283

[error.log](https://github.com/devcode-it/openstamanager/files/5152448/error.log)

Per informazioni il fatto si verifica quando vado a salvare un'anagrafica in cui viene valorizzata sia Partita IVA che Codice Fiscale.

OSM 2.4.17

**Comment by Dasc3er** [comment]
Il problema è noto, ed è causato da una dipendenza del progetto non perfettamente compatibile con PHP 7.4.
Per il momento è sufficiente fare il downgrade a PHP 7.3.

**Comment by idraulicadueci** [comment]
OK. Grazie. Scusa il doppione

**Comment by Dasc3er** [comment]
Nessun problema, non ricordo se la segnalazione è stata fatta qui oppure sul forum :smile:

**Comment by idraulicadueci** [comment]
> 
> 
> Nessun problema, non ricordo se la segnalazione è stata fatta qui oppure sul forum smile

Sì, è sul forum [https://forum.openstamanager.com/viewtopic.php?f=10&t=95337&sid=21931fe89931137134106964d22bed8d](url)

**Comment by Dasc3er** [comment]
A partire dalla versione 2.4.18 attualmente in sviluppo la dipendenza che causa il problema è stata aggiornata alla relativa release compatibile con PHP 7.4. Non dovrebbero pertanto ripresentarsi problemi relativi a questo errore.
