### ISSUE TITLE
Visualizzazione preventivo

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#879]
Problema riscontrato con la versione 2.4.17 su browser Chrome

Dopo aver creato un attività e selezionato il preventivo nell' apposito campo, al salvataggio lo stesso non viene visualizzato (nonostante il link "Visualizza scheda" riporta correttamente al preventivo).
Anche provando a riselezionarlo e salvare, dopo il salvataggio il campo viene nuovamente presentato vuoto.

**Comment by Dasc3er** [comment]
Grazie per la segnalazione!

**Comment by idraulicadueci** [comment]
Ho applicato la correzione, però adesso ho questo problema.

[error.log](https://github.com/devcode-it/openstamanager/files/5170421/error.log)

**Comment by Dasc3er** [comment]
@idraulicadueci Questo perchè evidentemente non hai applicato il solo commit indicato, ma anche altri differenti (in particolare, quello che introduce la revisione sulla geolocalizzazione in  Anagrafiche e Attività).
Ti consiglio a questo punto di mantenerti aggiornato con la versione master e aggiornare manualmente il database ad ogni modifica. In alternativa crea una classe Sede come trovi nella repository, ma questo può risolvere solo temporaneamente il problema e potrebbe causarne altri.

**Comment by idraulicadueci** [comment]
Grazie mille!!
