### ISSUE TITLE
FATTURE - non riporta unità di misura dei materiali dall'intervento

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#88]
Fatturando un intervento che ha dei materiali, riporta i materiali, le quantità ma non le unità di misura.

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione!
Dovrebbe essere stato risolto con il commit 0d14015953eeb6152940202afec31c425412c405, se puoi confermare...

**Comment by loviuz** [comment]
appena provato, vedo che è funzionante
