### ISSUE TITLE
Componenti non visualizzati su attività

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#880]
Problema riscontrato su ver. 2.4.17
Dopo aver installato un componente su un impianto, e lo stesso impianto inserito sulla scheda impianti di un attività, alla sezione "componenti soggetti all' intervento" non viene visualizzata la lista dei componenti precedentemente installati.

**Comment by Dasc3er** [comment]
Grazie per aver segnalato questo problema, ma sospetto sia già stato risolto nella versione in sviluppo.
Da verificare più nel dettaglio e indicare il commit relativo se disponibile.

**Comment by SaroTaz** [comment]
Come discusso già sul forum, applicando le modifiche del commit 9edf66e non si risolve il problema.

**Comment by Dasc3er** [comment]
Ultimo test effettuato sulla versione master, quindi con tutti i commit aggiunti dalla versione 2.4.17:
![image](https://user-images.githubusercontent.com/15911489/92359730-08466280-f0ec-11ea-9f96-9bd450561f4d.png)
![image](https://user-images.githubusercontent.com/15911489/92359766-12686100-f0ec-11ea-8010-1e58224a8f6a.png)

Pertanto il funzionamento mi risulta corretto al momento, anche se potenzialmente non è stato risolto dal commit specifico indicato.

**Comment by SaroTaz** [comment]
Ok. Il bug in effetti è un tantino più complesso di quanto avevo descritto.

Nella versione ufficiale 2.4.17 se inserisco l' impianto nella schermata di aggiunta attività come hai mostrato, trova sia impianto che componente; ma quando vado a verificare sulla scheda impianti nel mio caso viene riportato l'impianto ma non il componente; **lo stesso componente qualora lo vada a selezionare dal menù a discesa mi viene trovato, ma al momento del salvataggio viene cancellato nuovamente.**

![Cattura](https://user-images.githubusercontent.com/61335029/92380614-cc21fa80-f109-11ea-86d3-89b159370093.JPG)

Se invece nella schermata di aggiunta attività non inserisco nulla e desidero invece farlo successivamente dalla scheda impianti, a questo punto, riesco a selezionare l'impianto ma **nella scelta del componente restituisce direttamente "nessun risultato trovato".**


Altro comportamento anomalo capita quanto aggiungo due impianti diversi (sempre successivamente alla schermata di aggiunta attività) sulla stessa attività.

Il campo di selezione componente del primo impianto risulta un box non modificabile
![Cattura1](https://user-images.githubusercontent.com/61335029/92383087-ffff1f00-f10d-11ea-97f3-e43353f6921d.JPG)

**Comment by Dasc3er** [comment]
Grazie per i dettagli!
Posso confermare che negli ultimi test i comportamenti descritti non provocano il problema.

> Altro comportamento anomalo capita quanto aggiungo due impianti diversi (sempre successivamente alla schermata di aggiunta attività) sulla stessa attività

Questo in effetti è un altro bug che non ci era mai stati segnalato, ora risolto.
Grazie!

**Comment by SaroTaz** [comment]
Confermo che sulla versione in via di sviluppo tutto funziona regolarmente.
