### ISSUE TITLE
Miglioria: Rendere più veloce l'inserimento dei dati e degli articoli nei documenti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#881]
## Comportamento richiesto

Fare in modo che il contenuto di un campo venga selezionato quando ci si sposta con il tasto tab, in modo da poter sovrascrivere eventuale testo predefinito (per es. per i prezzi "0,0000")
Stesso comportamento quando si aggiunge un articolo, il campo di ricerca dovrebbe essere selezionato in automatico, in modo da poter digitare subito la stringa di ricerca.

## Comportamento attuale

Attualmente alla pressione del tasto TAB, il cursore si sposta nel campo successivo, però a destra del testo predefinito. Questo obbliga l'utente a dover selezionare manualmente il contenuto predefinito per poi valorizzare il campo. Questo non rende agevole l'inserimento dei dati.

Altro riferimento #382

**Comment by Dasc3er** [comment]
La funzionalità dovrebbe essere prevista esclusivamente per i campi numerici, giusto?
Al momento è in sperimentazione una nuova libreria JS per gli importi che dovrebbe risolvere il problema in automatico.

**Comment by idraulicadueci** [comment]
Ciao e grazie per la risposta.
Il comportamento dovrebbe seguire la modalità del richiamare un articolo e successivamente spostarsi sul campi quantità. Questi generalmente sono i parametri variabili nell'inserimento righe in un documento. Gli altri, pur essendo modificabili, dovrebbero già essere impostati nell' anagrafica dell'articolo.
