### ISSUE TITLE
Mancata visualizzazione campo "Span"

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#884]
## Comportamento richiesto

Dopo aver inserito in un intervento un articolo a cui è legato un componente personalizzato contenente un campo "span", lo stesso campo insieme a tutti gli altri alimentati su articolo dovrebbero essere visualizzabili sulla scheda componenti di Impianti.

## Comportamento attuale

Il solo campo span non viene visualizzato come si nota nello screen:

![Cattura](https://user-images.githubusercontent.com/61335029/92465355-c6421d00-f1ce-11ea-9ee6-e2358415c9c2.JPG)

## Passi per riprodurre il comportamento

1. Associare a un articolo il componente personalizzato di default
2. Creare una nuova attività e inserire in una nuova riga l'articolo e l'impianto voluto
3. Verificare sulla scheda componenti di Impianti

## Contesto

* Modulo: Impianti
* Versione del progetto: 2.4.18 (in sviluppo)
* Versione PHP: 7.2
* Tipo di server: Ubuntu Server

**Comment by SaroTaz** [comment]
Mi sono accorto solo ora che anche la data di installazione riportata è errata:
"INSTALLATO in data 30/11/-0001"

**Comment by Dasc3er** [comment]
@SaroTaz Grazie per la segnalazione!
Devo dire che questa issue mi ha fatto scoprire una funzionalità che non avevo osservato in precedenza, ovvero il fatto che **collegando un Articolo a un Componente** sia possibile **aggiungere il Componente ad un Impianto nel momento in cui si aggiunge l'Articolo in Attività**. 
La soluzione al problema è risultata piuttosto estesa, considerando che non era limitata esclusivamente ai campi di tipo SPAN ma anche al Nome del Componente aggiunto negli Articoli. Dovrebbe ora essere tutto risolto.

Devo anche notare che questa funzionalità è presente almeno dalla versione 2.2, e nessuno ci aveva mai segnalato problemi a riguardo!
Grazie! :smile: 

Il problema della data è leggermente differente, poichè causato dal fatto che in Attività non sono presenti Sessioni di lavoro. Per ora come fallback in questo caso viene presa la Data di richiesta dell'Attività.

**Comment by SaroTaz** [comment]
E' una funzione che ho scoperto anche io per caso e risulta preziosissima per vincolare interventi, magazzino e impianti con un risparmio di tempo sostanziale. Grazie ancora per il supporto.
