### ISSUE TITLE
Numerazione righe documenti

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#885]
Versione 2.4.18 (in sviluppo) aggiornata all' ultimo commit

Descrizione bug

Le righe dei documenti (provato sia su preventivi che su ordini cliente) non rispettano una numerazione sequenziale man mano che vengono aggiunte voci (v. screen):

![Cattura](https://user-images.githubusercontent.com/61335029/92801720-2646e800-f3b6-11ea-8cdf-fbd2ec71ac29.JPG)

In realtà per correttezza le righe descrittive non dovrebbero essere numerate in quanto si tratta di una descrizione.
Quelle che dovrebbero andare in ordine crescente dall' alto in basso dovrebbero essere articoli e righe manuali.

**Comment by Dasc3er** [comment]
Grazie per la segnalazione!
Era stata effettuata una modifica per correggere l'ordinamento utilizzando alcune impostazioni native di PHP, ma purtroppo la funzionalità utilizzava gli ID effettivi delle righe come numero visualizzato. Ora dovrebbe essere tutto corretto.

Per quanto riguarda la numerazione delle righe, il gestionale tratta le righe di tipo Descrizione come righe effettive che vengono riportate in stampa e nei documenti fiscali. Pertanto dovrebbe essere corretto includere queste righe nel conteggio effettivo.
In alternativa, se necessario, si possono utilizzare i campi generali del documento Descrizione, Note, Note interne e così via.

**Comment by SaroTaz** [comment]
Perfetto. Grazie per la celerità.
