### ISSUE TITLE
Modifica righe attività e componenti

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#886]
## Comportamento richiesto

Dato un articolo a cui è associato un componente personalizzato, dopo aver inserito lo stesso articolo in una riga di un intervento, quando modifico la riga dovrei vedere l' impianto a cui è stato associato l' articolo (e quindi il componente).

## Comportamento attuale

In fase di modifica l' impianto non viene visualizzato, e se si prova a inserirlo e salvare nuovamente la riga, viene aggiunto all' impianto lo stesso componente di nuovo.

## Passi per riprodurre il comportamento

1. Avendo un articolo con associato un componente, aggiungere l' articolo a una riga di un intervento definendo l'impianto su cui va installato.
2. Andare su modifica riga
3. Verificare che il campo "impianto su cui installare" è vuoto

## Contesto

* Modulo: Attività
* Versione del progetto: 2.4.18 (in sviluppo) ultimo commit
* Versione PHP: 7.2.24
* Tipo di server: Ubuntu 18.04.6

**Inoltre il componente che viene associato dall'articolo viene rimosso se viene eliminato l'intervento, ma resta invariato se viene eliminata la sola riga, creando dei potenziali duplicati nei componenti installati sull' impianto.**

**Comment by Dasc3er** [comment]
Ciao @SaroTaz , grazie anche per questa segnalazione!
Putroppo in questo caso la faccenda è più complessa rispetto al precedente, e il comportamento _potrebbe_ essere voluto. Infatti  nella tabella  **my_impianto_componenti** viene salvato esclusivamente l'attività di origine, e non viene fatto riferimento a nessuna riga: questo provoca il comportamento da te descritto.

@loviuz @lucasalva87 Cosa ne pensate?
Si potrebbe includere una nuova colonna per indicare la riga dell'attività e risalire in questo modo alle informazioni relative, oppure si potrebbe estendere il sistema con le classi Eloquent per permettere l'aggiunta di Componenti a un Impianto da qualunque tipo di Documento.

**Comment by SaroTaz** [comment]
> oppure si potrebbe estendere il sistema con le classi Eloquent per permettere l'aggiunta di Componenti a un Impianto da qualunque tipo di Documento.

Credo che i componenti e gli impianti debbano restare entità strettamente legate al solo comparto manutentivo e quindi alle attività.
 
Cosa succede se ad esempio l’articolo viene associato a un impianto in un preventivo e il preventivo viene trasformato ad esempio in ordine? Viene inserito il componente sull’impianto due volte?
