### ISSUE TITLE
Azioni di gruppo mancanti su ordini cliente

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#887]
Ver. 2.4.18 (in sviluppo) ultimo commit

Il pulsante azioni di gruppo manca su ordini cliente

![Immagine](https://user-images.githubusercontent.com/61335029/93028054-8d140d80-f611-11ea-808c-b390b2175c33.jpg)

**Comment by Dasc3er** [comment]
Questo non è un bug: al momento non sono state sviluppate azioni di gruppo per il modulo Ordini.
Avresti suggerimenti?

**Comment by SaroTaz** [comment]
Sarebbe utile poter trasformare in blocco tutti gli ordini di un dato cliente in fattura o fatture. 
Non so la fattibilità della cosa ma potrebbe essere interessante poter inserire nelle righe della fattura, tutti i riferimenti agli ordini di origine e le relative righe degli ordini.

Nelle realtà di appalti di manutenzione industriale, il cliente emette degli ordini mensili che vengono poi fatturati a fine mese. Onde evitare di emettere tot. fatture per tot. ordini, in genere si emette una sola fattura contenente nelle righe tutti i riferimenti agli ordini emessi nel mese.
