### ISSUE TITLE
Miglioria: Gestione progetti

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#888]
Attualmente la strada verso cui è orientato OSM, lascia sperare a un futuro in cui il gestionale non avrà nulla da invidiare a software ben più blasonati e sicuramente meno scalabili. 
Una mancanza che si fa sentire (e che oggi più che mai è ritenuta di primaria importanza nella valutazione previsionale di costi e guadagni per futuri appalti) è la gestione dei progetti (o commesse).

Ogni singolo documento viene classificato su commesse predeterminate, con cui il cost controller può effettuare un analisi di spese e ricavi, avere un bilancio di commessa, attraverso i quali decidere con maggiore precisione sui contratti futuri.

**Comment by Dasc3er** [comment]
@SaroTaz Per il momento non esiste nessuna funzionalità del genere nella versione gratuita del gestionale, e dubito verrà introdotta nel breve periodo.
Infatti nel caso di progetti più complessi il team ufficiale di OpenSTAManager propone delle personalizzazioni oppure dei pacchetti a pagamento che permettono di estendere le funzionalità del gestionale. Per ottenere un sistema del genere ti consiglierei pertanto di controllare il sito ufficiale e di contattare via mail gli sviluppatori.

Se al contrario sei interessato allo sviluppo personale della funzionalità, puoi procedere attraverso un fork del progetto oppure attraverso lo sviluppo di un insieme di moduli e plugin dedicati: la documentazione ufficiale descrive alcune delle componenti più importanti del gestionale, per cui ti consiglio una lettura della stessa.

**Comment by SaroTaz** [comment]
La mia voleva essere una semplice proposta che eventualmente potrebbe essere presa in considerazione in futuro (anche nel lungo periodo).
