### ISSUE TITLE
INTERVENTI - Tabella Costi Totali

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#89]
![image](https://user-images.githubusercontent.com/34273200/34433794-f5f2d0bc-ec81-11e7-871f-6858c8a1a656.png)
Sarebbe più utile suddividere la prima riga in due righe: Manodopera e Diritti Fisso di chiamata, visto che in fattura sono distinti ed è più facile controllare
In questa tabella non ha senso mettere IVA 22 perchè non è detto che sia con questa aliquota, o si inserisce la possibilità di scegliere già qui l'IVA oppure non visualizzare IVA.

**Comment by loviuz** [comment]
> Sarebbe più utile suddividere la prima riga in due righe: Manodopera e Diritti Fisso di chiamata, visto che in fattura sono distinti ed è più facile controllare

Vero!

> In questa tabella non ha senso mettere IVA 22 perchè non è detto che sia con questa aliquota, o si inserisce la possibilità di scegliere già qui l'IVA oppure non visualizzare IVA.

Qui prende l'iva dall'iva predefinita nelle impostazioni. Può essere utile per buona parte degli utenti. Chi ha casi di iva diversa in base al cliente, dovrebbe considerare sempre e solo l'imponibile. Se dovessimo essere precisi dovremmo mettere la scelta dell'iva nell'intervento, però non vorrei che diventasse troppo pesante compilare l'intervento, anche perché il tecnico potrebbe non conoscere l'iva esatta da applicare.
C'è anche un altro aspetto, e cioè che in stampa del rapportino sarebbe corretto che il cliente vedesse il totale completo, quindi con iva.
Da ragionarci su...
@fpsoftware, @lucasalva87, cosa dite?

**Comment by Dasc3er** [comment]
@loviuz Eventualmente per quale milestone impostiamo la rivisitazione della struttura di questa tabella?

**Comment by fpsoftware** [comment]
Suddividere la prima riga va bene, inoltre possiamo migliorare la gestione dell'iva negli interventi con nuove impostazioni su zz_settings , i tecnici trovano valori di default ed inseriscono solo orario, articoli, spese, come adesso

**Comment by lepool** [comment]
Io se posso dare un consiglio per quanto riguarda l'iva è di seguire un filo logico come precedenza, in maniera da seguire questo sistema in tutti i moduli. 

prima opzione Iva predefinita 
se ipostato per cliente, va selezionato per cliente
se impostato per intervento o preventivo o altro, va selezionato per altro
se l'iva è selezionato per un articolo (o riga generica, ecc.), nel caso che un articolo vige una particolare aliquota IVA, va selezionato
e precompilato il campo. Poi uno lo modifica manualmente.

**Comment by loviuz** [comment]
Credo che aggiungere l'iva 22% prendendola dall'iva predefinita sia sbagliato a sto punto, perché potrebbe andar bene per le ore, ma non per gli articoli che possono avere (in rari casi) iva diversa, oppure le spese generiche potrebbero essere alcune esenti iva. L'iva al 22% aggiunta alla fine così mi sembra stia diventando un po' inutile e generica.
Secondo me ci sono 2 soluzioni:

1. si toglie completamente, per ora
2. si aggiunge una colonna con il prezzo ivato di manodopera e km (creando un'impostazione nuova con l'iva della manodopera), il prezzo ivato degli articoli, prendendo l'iva di ogni articolo aggiunto e l'iva di altre spese, prendendola dall'iva di ogni articolo

Io, inizialmente, la toglierei per non creare confusione. Magari per chi ha iva al 22% su tutto gli va bene, però chi ha regimi fiscali particolari o articoli con iva diversa, fa solo confusione...

Che ne dite @fpsoftware @lucasalva87?

**Comment by loviuz** [comment]
https://github.com/devcode-it/openstamanager/commit/0a0c24663ef738e911628b89ce25286ea803598f

**Comment by loviuz** [comment]
Dato che è stata aggiunta l'iva su articoli e spese delle attività, si può calcolare l'iva predefinita su manodopera, km e diritto di chiamata, mentre per "TOTALE ARTICOLI" e "TOTALE SPESE" considerare l'iva selezionata. Il campo finale "IVA (IVA 22%)" andrebbe quindi cambiato in "IVA" solamente, perché possono esserci più aliquote.

Non serve, secondo me, specificare l'iva divisa per aliquote nella stampa rapportino, perché è una stampa tecnica, non fiscale
