### ISSUE TITLE
Modale e freez pagina

### ISSUE THREAD

**Issue by christianlauri** [devcode-it/openstamanager#890]
Aprendo il modale e poi chiudendolo scompare la barra di scroll a destra e quindi è come se si freezzasse :D.

Ho provato ad utilizzare anche codici esempio già fatti in rete ma succede la stessa cosa

                                                                                <td class=" text-right">0,00 €</td>
                                                                                <td class=" text-right">5.033,06 €</td>
                                                                                <td class=" text-center">
                                                                                    <span class="pointer fa fa-list"
                                                                                            title="Visualizza"
                                                                                            data-toggle="modal"
                                                                                            data-target="#linea1"></span>
                                                                                </td>

<div class="bootbox modal fade in" tabindex="-1" role="dialog" aria-hidden="true" id="linea3">
        <div class="modal-dialog" style="width: 70%;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal">×</button>
                    <h4 class="modal-title">Dettaglio Impegni</h4>
                </div>
                <div class="modal-body">
                    <div class="bootbox-body">

                        <meta http-equiv="X-UA-Compatible" content="IE=edge">
                        <meta name="viewport" content="width=device-width,initial-scale=1">
                        <meta name="_csrf_parameter" content="_csrf">
                        <meta name="_csrf_header" content="X-CSRF-TOKEN">
                        <meta name="_csrf" content="a1b55d72-8ee6-4f06-b177-0f72b8911b28">

                        <div>
                            <div id="6e6385fc-b950-4b30-be22-fb56950208ba">
                                <form id="elencoDettaglioImpegniEsigibilitaForm">

                                    <div id="ricercaDettaglioImpegniBox_info" class="info info-message" role="info"
                                        aria-live="assertive" style="display: none">
                                        <ul class="messagesUl" id="ricercaDettaglioImpegniBoxUl_info"></ul>
                                    </div>

                                    <div id="modalElencoDettaglioImpegniEsigibilitaDataTable_wrapper"
                                        class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="dataTables_length"
                                                    id="modalElencoDettaglioImpegniEsigibilitaDataTable_length">
                                                    <label>Visualizza
                                                        <select
                                                            name="modalElencoDettaglioImpegniEsigibilitaDataTable_length"
                                                            aria-controls="modalElencoDettaglioImpegniEsigibilitaDataTable"
                                                            class="form-control input-sm">
                                                            <option value="10">10</option>
                                                            <option value="25">25</option>
                                                            <option value="50">50</option>
                                                            <option value="100">100</option>
                                                        </select> elementi
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="col-sm-6"></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <table id="modalElencoDettaglioImpegniEsigibilitaDataTable" width="100%"
                                                    class="fe-array-datatable table table-striped table-condensed table-hover dataTable no-footer"
                                                    data-paging="true" data-lang="it_IT"
                                                    data-table-varname="modalElencoDettaglioImpegniEsigibilitaTable"
                                                    data-table-js-array="ricercaDettaglioImpegniAppViewModel.ricercaDettaglioImpegniEsigibilitaForm.listaImpegni"
                                                    data-table-bind-ko-array="true"
                                                    data-table-app-view-model-name="appViewModel" role="grid"
                                                    aria-describedby="modalElencoDettaglioImpegniEsigibilitaDataTable_info"
                                                    style="width: 100%;">
                                                    <thead>
                                                        <tr role="row">
                                                            <th data-renderer-function="impegnoRenderer"
                                                                data-hidable="false" data-visible="true"
                                                                data-orderable-column="false" class="sorting_disabled"
                                                                rowspan="1" colspan="1"
                                                                aria-label="Decreto - IPE - Clausola"
                                                                style="width: 153px;">
                                                                Decreto - IPE - Clausola
                                                            </th>
                                                            <th data-renderer-function="capitoloPGRenderer"
                                                                data-hidable="false" data-visible="true"
                                                                data-orderable-column="false" class="sorting_disabled"
                                                                rowspan="1" colspan="1" aria-label="Capitolo Pg"
                                                                style="width: 98px;">
                                                                Capitolo Pg
                                                            </th>
                                                            <th data-parameter-name="annualita" data-hidable="false"
                                                                data-visible="true" data-orderable-column="false"
                                                                class="sorting_disabled" rowspan="1" colspan="1"
                                                                aria-label="
                    Annualità" style="width: 54px;">
                                                                Annualità
                                                            </th>
                                                            <th data-parameter-name="importo"
                                                                data-renderer-function="importoRenderer"
                                                                data-column-class="text-right" data-hidable="false"
                                                                data-visible="true" data-orderable-column="false"
                                                                class="text-right sorting_disabled" rowspan="1"
                                                                colspan="1" aria-label="
                    Importo
                " style="width: 46px;">
                                                                Importo
                                                            </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr role="row" class="odd">
                                                            <td>
                                                                <span
                                                                    title="Esercizio - Amministrazione - Ufficio Livello 1 - Ufficio Livello 2 - Decreto - IPE - Clausola">2018-030-0010-0002-5690--1</span>
                                                            </td>
                                                            <td>
                                                                <span
                                                                    title="Esercizio PG - Amministrazione PG - Ragioneria PG - Capitolo - Piano Gestione (PG)">2018-030-730-3652-47</span>
                                                            </td>
                                                            <td>2018</td>
                                                            <td class=" text-right">7.228,76 €</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-sm-4">
                                                <div class="dataTables_info"
                                                    id="modalElencoDettaglioImpegniEsigibilitaDataTable_info"
                                                    role="status" aria-live="polite">Vista da 1 a 5 di 5 elementi</div>
                                            </div>
                                            <div class="col-sm-8">
                                                <div class="dataTables_paginate paging_simple_numbers"
                                                    id="modalElencoDettaglioImpegniEsigibilitaDataTable_paginate">
                                                    <ul class="pagination pagination-sm">
                                                        <li class="paginate_button previous disabled"
                                                            id="modalElencoDettaglioImpegniEsigibilitaDataTable_previous">
                                                            <a href="#"
                                                                aria-controls="modalElencoDettaglioImpegniEsigibilitaDataTable"
                                                                data-dt-idx="0" tabindex="0">Precedente</a>
                                                        </li>
                                                        <li class="paginate_button active"><a href="#"
                                                                aria-controls="modalElencoDettaglioImpegniEsigibilitaDataTable"
                                                                data-dt-idx="1" tabindex="0">1</a>
                                                        </li>
                                                        <li class="paginate_button next disabled"
                                                            id="modalElencoDettaglioImpegniEsigibilitaDataTable_next">
                                                            <a href="#"
                                                                aria-controls="modalElencoDettaglioImpegniEsigibilitaDataTable"
                                                                data-dt-idx="2" tabindex="0">Successivo</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn  btn-primary btn-sm" type="button" data-dismiss="modal">Chiudi</button>
                </div>
            </div>
        </div>
    </div>

**Comment by Dasc3er** [comment]
Ciao, puoi indicare versione del gestionale, modulo dove si verifica il problema, azioni che hai effettuato per causarlo e altre informazioni sul browser?

**Comment by christianlauri** [comment]
Browser succede su tutti...

cosa ho fatto per causarlo? chiuso il modale sia con la 'x' sia con 'chiudi' sia cliccando fuori dal modale

**Comment by Dasc3er** [comment]
Le risposte alle altre domande?

**Comment by christianlauri** [comment]
Gestionale? non lo so altrimenti te lo direi
Dove avviene? ovunque metta il modale

**Comment by christianlauri** [comment]
praticamente già quando appare il modale scompare la barra di scroll del sito, quando lo chiudo è come se venga eliminata, tantè che la tabella si "allarga"

**Comment by christianlauri** [comment]
![image](https://user-images.githubusercontent.com/62547286/93616348-eba40780-f9d4-11ea-93de-ae134cc44db6.png)



![image](https://user-images.githubusercontent.com/62547286/93616297-d929ce00-f9d4-11ea-98ae-bff7f1f095af.png)

**Comment by Dasc3er** [comment]
@christianlauri Sei sicuro che il programma che stai utilizzando è OpenSTAManager?
Dagli screenshot non mi sembra proprio.
Ti consiglio pertanto di controllare il sito www.openstamanager.con per verificare di stare utilizzando questo software, preferibilmente aggiornato all'ultima versione disponibile.
