### ISSUE TITLE
Campo descrizione su aggiunta articolo

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#891]
Ver. 2.4.18 ultimo commit

Quando in un documento si aggiunge un articolo, nella maschera di inserimento dopo aver selezionato l'articolo il campo descrizione resta vuoto anziché proporre la descrizione standard dell' articolo in questione

**Comment by Dasc3er** [comment]
Grazie per la segnalazione!
Abbiamo di recente corretto alcuni comportamenti JS, il che ha provocato il problema in questione.
