### ISSUE TITLE
Domanda: Autorizzazioni per portale cliente

### ISSUE THREAD

**Issue by SaroTaz** [devcode-it/openstamanager#893]
Ipotizziamo volessi dare accesso ai clienti e visualizzare i propri ordini, impianti ecc. 
Creando un nuovo utente, associandolo a un anagrafica cliente, impostando le autorizzazioni di sola lettura su ordini, attività o impianti, il cliente visualizzerà solo quanto associato alla sua anagrafica o avrà accesso anche agli ordini, attività e impianti degli altri clienti?

**Comment by SaroTaz** [comment]
Provato da me. La visualizzazione è inerente ai soli documenti del cliente.

**Comment by Dasc3er** [comment]
Ottima notizia, la gestione è solitamente effettuata tramite filtri secondari che dipendono dall'installazione.
I filtri potrebbero però non essere abilitati per tutti i moduli di interesse, quindi ti consiglio di utilizzare il modulo Viste.
