### ISSUE TITLE
Impostazione libro giornale

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#895]
Per il modulo prima nota sarebbe utile aggiungere 2 colonne. Una con il valore dell'imponibile della fattura / e collegata /e e l'altra con il valore dell'iva.  Che ne pensi @loviuz

**Comment by Dasc3er** [comment]
Riferimento: #151

**Comment by loviuz** [comment]
Secondo me non serve, perché la prima nota prevede solo movimenti di conti in dare o avere. Forse non ho ben capito la richiesta iniziale
