### ISSUE TITLE
Modulo PAGAMENTI non funziona correttamente

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#896]
## Comportamento attuale

In fase di modifica di un pagamento, il pulsante SALVA non funziona, quindi le modifiche non vengono salvate.
Inoltre non vengono presi valori percentuali a 4 cifre decimali; per esempio se ho un pagamento in 3 rate, inserisco 2 pagamenti del 33,3333% e uno del 33,3334%, però dopo il salvataggio ritrovo 3 pagamenti di 33,3300%.

## Possibile soluzione

Potrebbe essere più pratico poter semplicemente indicare il numero di rate e far proporre in automatico le percentuali di suddivisione, poi modificabili. 

È necessario inoltre inserire un flag "IVA prima rata", in quanto alcuni fornitori recuperano l'IVA con la prima di X rate.

## Passi per riprodurre il comportamento

1. Creare un nuovo pagamento e inserire tutti i dati e salvare.
2. Riaprire il nuovo pagamento inserito e modificarlo. Salvare.

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Pagamenti
* Versione del progetto: OSM 2.4.17.1 (32911c5a)

**Comment by Dasc3er** [comment]
Grazie per la segnalazione!
Al momento è stata effettuata una correzione sul salvataggio dei dati, pertanto è ancora da verificare il comportamento sulle percentuali di pagamento.
Interessante la possibilità di prevedere la prima rata come rata con l'iva del pagamento, da verificare più nel dettaglio per vedere se di interesse per il gestionale.

**Comment by Dasc3er** [comment]
Confermo inoltre che il comportamento del modulo è ora corretto, e prevede l'utilizzo di massimo 2 decimali per le percentuali (come inteso originalmente).
