### ISSUE TITLE
Aggiunta prima nota da modello

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#897]
Bug su versione 2.4.18 (in sviluppo)

![Prima nota OpenSTAManager](https://user-images.githubusercontent.com/30728163/95609952-d7957800-0a5f-11eb-81df-f190a10a7a60.png)

Se compilo una prima nota da modello non vengono create correttamente le righe e in fase di salvataggio i valori si troncano dopo la terza riga perdendo di fatto tutti i valori inseriti in dare e avere.

**Comment by Dasc3er** [comment]
@lucasalva87 Ho effettuato una correzione in relazione a questa issue, da verificare più nel dettaglio per garantire il ripristino della funzionalità.
Poichè inoltre i modelli non supportano il riferimento a più di una Fattura in Prima Nota, non sono utilizzabili dalle schermate che preimpostano più di una Scadenza.

**Comment by lucasalva87** [comment]
@Dasc3er Ti ringrazio molto! Faccio qualche test entro sera.
