### ISSUE TITLE
MIGLIORIA: cancellazione e duplicazione in bulk delle righe di un documento

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#898]
Sarebbe utile poter cancellare o duplicare più righe contemporaneamente in un documento.

**Comment by Dasc3er** [comment]
L'unico accorgimento che queste funzionalità devono prevedere consiste nell'utilizzo delle classi:
- per la rimozione delle righe, chiamare il metodo `delete `sulla riga
- per la duplicazione delle righe, prevedere l'estensione del metodo `copiaIn `per utilizzare il flag interno $is_evasione (in modo da evitare l'utilizzo dei riferimenti interni tra documenti). In alternativa, si può considerare il metodo `replicate()`, a patto di gestire separatamente le movimentazioni di magazzino per gli Articoli.

**Comment by Pek5892** [comment]
Attualmente disponibile: https://docs.openstamanager.com/v/2.4.34/openstamanager/interfaccia/moduli-e-plugin#modifica-record
