### ISSUE TITLE
FATTURE - Prezzi unitari ed importi non chiari e non corretti

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#90]
Nel caso di applicazione di sconti sulle righe il risultato non è esatto ed in stampa è completamente sbagliato
![image](https://user-images.githubusercontent.com/34273200/34440033-b038e77e-ecb2-11e7-8e35-445bfc800955.png)
![image](https://user-images.githubusercontent.com/34273200/34440050-cec941f2-ecb2-11e7-8a12-477da89af64c.png)

**Comment by Dasc3er** [comment]
@fgambarelli Credo di non aver compreso il problema...
In questo caso hai impostato per ogni riga lo sconto del 10%, che viene sottratto correttamente in entrambe le immagini inserite.

Esempio:
383,60 euro con sconto 10% = 383,60 - 38,36 = 345,24 euro
Nella stampa, il calcolo viene mostrato in modo simile con la dicitura "- sconto 38,36 euro".

**Comment by fgambarelli** [comment]
Scusa non ho spiegato bene.. 
In stampa non appare come a video il vero importo finale di ogni riga, della prima mi aspetterei di vedere i 345,24.

**Comment by Dasc3er** [comment]
Effettivamente la stampa per il momento è stata progettata in questo modo...

@fpsoftware @loviuz @lucasalva87 Cosa ne pensate?

**Comment by fgambarelli** [comment]
Per me così è più leggibile, ho modificato il body della fattura in modo che nella stampa per ogni riga si riesca anche a vedere quanto è l'importo effettivo dell'articolo venduto. La colonna importo corrisponde all'imponibile scontato.
![image](https://user-images.githubusercontent.com/34273200/34448137-17a76cb8-eceb-11e7-8efe-bf0a951d9a58.png)

**Comment by loviuz** [comment]
Dato che a video avevamo messo sull'ultima colonna il totale già scontato, meglio metterlo anche nella stampa in modo che tutto sia uniforme. Dettaglio di cui non mi ero accorto...

**Comment by Dasc3er** [comment]
Risolto nel seguente modo:
![screenshot-2018-1-4 fattura_pro-2 pdf - pdfgen php](https://user-images.githubusercontent.com/15911489/34572205-1601cbc6-f171-11e7-89bc-fa94112e3557.png)
