### ISSUE TITLE
Sidebar plugin a scomparsa

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#900]
## Comportamento richiesto
Possibilità di chiudere e aprire la sidebar dei plugin a piacimento

## Comportamento attuale
Al momento la sidebar è fissa e porta via molto spazio per l'editing delle righe

## Possibile soluzione
Inserire un floating button (ad esempio con l'icona del menu) in alto a destra in modo da chiudere la sidebar dei plugin quando non serve. In questo modo non viene occupato spazio che verrebbe utilizzato dalle righe dei documenti.

## Contesto
Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Tutti
* Versione del progetto: 2.4.18
* Versione PHP: 7.4
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
@maicol07 Grazie per il suggerimento, la sidebar dovrebbe però avere già questa opzione per gli schermi più piccoli.
Guardando rapidamente, la dimensione minima dello schermo deve essere di 1140px per mostrare la sidebar in modo fisso. L'idea è infatti di semplificare la navigazione dei plugin evitando l'insieme di tab all'inizio della pagina.

**Comment by maicol07** [comment]
Magari rendere la sidebar a scomparsa un po' come il menu principale che si può aprire e chiudere a piacimento?

**Comment by Dasc3er** [comment]
@maicol07 La funzionalità dovrebbe ora essere implementata: https://github.com/devcode-it/openstamanager/commit/f17324dd392d803cea697037948726d5d6dbe889

**Comment by maicol07** [comment]
Confermo l'implementazione
