### ISSUE TITLE
Errore invio XML - SistemaEmittente

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#902]
Il camo `sistemaemittente` dell'XML deve essere max 10 caratteri. Al momento inviare una FE con questo campo risulta nella fattura scartata

## Contesto

* Modulo: Fattura Elettronica
* Versione del progetto: 2.4.18
* Versione PHP: 7.4
* Tipo di server: OpenLiteSpeed

**Comment by Dasc3er** [comment]
Grazie per la segnalazione, soprattutto poichè sulla versione in sviluppo.
