### ISSUE TITLE
Problema connessione account email SiteGround

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#903]
Versione 2.4.17 (appena aggiornato), PHP 7.2

Nel modulo delle email il pulsante "Salva e controlla credenziali" mi da "Connessione SMTP fallita Impossibile connettersi all'account SMTP".
Inizialmente ho pensato potesse trattarsi di un problema causato dell'account email che non era sullo stesso server, così ho creato un account di test sullo stesso server dove c'è l'installazione del gestionale. Continuo a riscontrare lo stesso problema... L'account mail che dovrei utilizzare è su hosting di SiteGround...

Ho provato anche ad abilitare "Non verificare il certificato SSL" ma senza nessun risultato.

Qualche consiglio?

Vi ringrazio in anticipo

**Comment by Dasc3er** [comment]
Ciao Cristian, 
Puoi dirci più nel dettaglio come hai configurato l'account SMTP?
In particolare, hai seguito le istruzioni ufficiali del provider per nome utente, password (ovviamente da non condividere), URL del server e porta?

**Comment by cristianviale** [comment]
Ciao Thomas, grazie per la risposta. Certamente ho utilizzato i parametri forniti dall'hosting ed ho anche verificato il funzionamento inserendo gli stessi parametri su Thunderbird.

**Comment by Dasc3er** [comment]
Ottimo, grazie per la conferma.
@loviuz Avete mai configurato e avuto problemi con l'hosting di SiteGround?

**Comment by cristianviale** [comment]
Nel frattempo vi aggiungo altri dettagli...
Inizialmente il problema si è verificato con la versione 2.4.15 che ho poi aggiornato alla 2.4.17 nella speranza di risolvere il problema. L'aggiornamento l'ho fatto col metodo "manuale" ovvero andando a sovrascrivere i file dell'installazione con quelli della release 2.4.17.
Ho pensato ad un blocco causato dal mio hosting, ho quindi provato a mettere l'indirizzo IP del server mail nella whitelist senza ottenere il risultato sperato.
Infine, ho creato anche un account email sullo stesso server dove ho l'installazione (che non è SiteGround) ma anche così continua a non funzionare.
Quindi escluderei un problema dell'hosting e dell'account mail...
Se avete idee proviamo

Grazie di nuovo

**Comment by cristianviale** [comment]
Ragazzi ho finalmente risolto il mistero, il problema era il carattere "#" nella password... Ve lo dico così potete risolvere per le prossime release...
Grazie per il supporto

**Comment by Dasc3er** [comment]
Grazie per la soluzione!
Purtroppo non possiamo fare molto per il problema, poiché la password viene gestita dagli utenti del gestionale e non dal gestionale stesso.
Probabilmente durante la comunicazione con il sistema di email di SuteGround il carattere # non viene interpretato correttamente.

**Comment by cristianviale** [comment]
In che senso? La password non viene salvata nella tabella em_accounts per l'invio delle mail direttamente dal gestionale mediante PHPMailer?

**Comment by cristianviale** [comment]
Scusate, forse mi sono spiegato male.. Sorry
Il gestionale è installato su un hosting, mentre l'indirizzo mail era su SiteGround. Ma per fare degli altri test ho ricreato una mail ad hoc sull'hosting sul quale ho installato OSM e ho riscontrato lo stesso problema.
Quindi non è un problema di SiteGround, ma è proprio un problema del carattere "#" nella password... Ovunque sia la mail...

**Comment by Dasc3er** [comment]
Certamente, la password viene salvata ma anche se contenesse il carattere # viene salvata e poi utilizzata correttamente.
Il problema si verifica durante la comunicazione (improbabile, poiché utilizziamo una libreria apposita) oppure nel server SiteGround. Non abbiamo modo di risolvere il problema proprio per questo.

Possiamo eventualmente inserire un warning specifico per SiteGround, ma non sono sicuro che abbia un utilità pratica poiché ci possono essere altri caratteri che causano il problema, ma solo per questo server.

**Comment by cristianviale** [comment]
Mi scrivi "solo per questo server", ma come ti ho detto ho provato con due server diversi: quello di SiteGround e quello dove ho l'installazione di OSM.
