### ISSUE TITLE
Errore nel file Anagrafica.php

### ISSUE THREAD

**Issue by cristianviale** [devcode-it/openstamanager#904]
Ciao a tutti, è un vecchio errore che pensavo fosse già stato segnalato... Ve lo segnalo in modo che possiate risolverlo nella prossima release.

Nel file **Anagrafica.php** trovo:

```
public static function fromTipo($type)
    {
        $tipologia = Tipo::where('descrizione', 'Tecnico')->first();

        $anagrafiche = self::whereHas('tipi', function ($query) use ($tipologia) {
            $query->where('an_tipianagrafiche.idtipoanagrafica', '=', $tipologia->id);
        });

        return $anagrafiche;
    }
```

Credo che **'Tecnico'** dovrebbe essere modificarlo con **$type**.

**Comment by Dasc3er** [comment]
Ciao @cristianviale , 
come puoi vedere dal codice seguente, il problema è ancora presente:
https://github.com/devcode-it/openstamanager/blob/a574112f4ed6810151309e1fac930842c57cc0e8/modules/anagrafiche/src/Anagrafica.php#L84

Provvedo a correggere. Fortunatamente, sembra che la funzione fromTipo sia utilizzata solo per i Tecnici 😄 .

**Comment by Dasc3er** [comment]
Grazie per la segnalazione!
