### ISSUE TITLE
Miglioria fatture pro-forma (vendite)

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#906]
Sarebbe utile tramite azione di gruppo prevedere la possibilità di convertire una o più fatture pro-forma in fatture di vendita fiscali. 
Decidendo se eventualmente accorparle in un'unica fattura per quel cliente
![immagine](https://user-images.githubusercontent.com/30728163/98937440-b0aae580-24e6-11eb-89f2-35e6be514a1f.png)

**Comment by Pek5892** [comment]
Funzionalità introdotta nelle release successive:
![immagine](https://user-images.githubusercontent.com/102604205/183612430-2ed45a0c-1f72-46b4-97f8-01650707290c.png)
