### ISSUE TITLE
Problema con i plugin

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#907]
Ho effettuato l'aggiornamento alla versione 2.4.18. Se clicco su plugin di qualsiasi modulo, sulla destra non compare nessun plugin.

**Comment by Dasc3er** [comment]
Ciao, al momento sembra un problema comune...
Stiamo cercando di risolverlo, nel frattempo puoi semplicemente copiare i file include/top.php e editor.php da una installazione precedente ed sostituirli a quelli nuovi.

Prima di fare questo, potresti controllare però se i controlli di integrità sui file nel modulo Aggiornamenti presentano dei problemi?

**Comment by Dasc3er** [comment]
In alcuni casi il problema e anche causato da file custom per il top.php

**Comment by idraulicadueci** [comment]
Ho rinominato il file /incluse/custom/top.php in /include/custom/top.bak. Adesso funziona tutto, quindi il mio problema è proprio là.
Grazie mille!! :v:

**Comment by Dasc3er** [comment]
Perfetto! Grazie per la conferma.
