### ISSUE TITLE
Problema con lo scadenzario F24

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#909]
## Comportamento richiesto

Avere la possibilità di registrare il pagamento degli F24 in prima nota

## Comportamento attuale

Allo stato attuale, se inserisco una scadenza F24, e clicco su "Registra contabile", mi appare la pagina di inserimento in prima nota, ma senza il pulsante "AGGIUNGI"
Forse è dovuto al fatto che non è collegato a nessun documento (noto nella tabella co_scadenzario che iddocumento = 0?

![img](https://user-images.githubusercontent.com/40104356/99184343-5efe9700-2742-11eb-8fbb-22abac4d603f.png)

OSM 2.4.17.1

**Comment by loviuz** [comment]
Vedo che manca il conto nella prima riga, puoi provare a compilarlo?

**Comment by idraulicadueci** [comment]
Era lì il problema. :grin:
Scusa per il falso allarme, ma è la prima volta che inserisco scadenze diverse da quelle relative alle fatture. Grazie
