### ISSUE TITLE
FATTURE - Assenza di controlli sulla data

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#91]
Non deve essere possibile inserire una fattura, sia acquisti che vendita, con data precedente all'ultima emessa.

**Comment by Dasc3er** [comment]
@devcode-it/openstamanager Non si possono verificare casi in cui sia necessario inserire una fattura precedente alla data dell'ultima _Emessa_?
Non intendo per correttezza di gestione, quanto per reale utilizzo da parte dei clienti, considerando che allo stesso modo la numerazione di fattura può essere modificata a piacimento dal Modulo...

**Comment by fgambarelli** [comment]
Non si possono emettere fatture con numero successivo e data precedente all'ultima emessa.
Es. l'ultima fattura è la 102 del 31/01/2018, il sistema non deve permettere di inserire la 103 con data 30/01/2018. Il sistema ora lo permette ed è pericolosissimo!!

**Comment by lucasalva87** [comment]
Aggiungerei un controllo sul controller_before.php nelle fatture di vendita in modo da evidenziare eventuali incogruenze. Il programma calcola corettamente i numeri ma per modifiche manuali non vorremmo "blindare" troppo l'utente. Al limite il blocco delle modifiche di numero e data potremmo vederla come una nuova impostazione futura.

**Comment by loviuz** [comment]
Nel frattempo aggiungerei che, nella popup di aggiunta nuova fattura, il calendario di jqueryui non faccia scegliere una data inferiore a quella dell'ultima fattura emessa (escluse le bozze).

**Comment by Dasc3er** [comment]
Con il commit accb938 è stato aggiunto un controllo sulla duplicazione della numerazione delle fatture.
La gestione di eventuali sistemi più complessi è da approfondire.

**Comment by Dasc3er** [comment]
Con il commit https://github.com/devcode-it/openstamanager/commit/5be7d7566e5a73e41e9f24965d0eda665c03574c la funzionalità è stata completata, poichè ora viene visualizzato un warning all'accesso di fatture che non rispettano la numerazione. Purtroppo non è possibile gestire attraverso query SQL il controllo effettuato.
