### ISSUE TITLE
MIGLIORIA Creazione ordine cliente da preventivo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#910]
Possibilità di accorpare in un unico ordine cliente molteplici preventivi

Quando si effettua un ordine cliente, spesso si includono più preventivi.

La possibile soluzione potrebbe essere quella di aggiungere un pulsante "+PREVENTIVO" nella sezione righe del modulo Ordine Cliente.

Riferimento Issue #908

**Comment by Pek5892** [comment]
Tasto + Preventivo in Ordini attualmente presente in release (v2.6)
