### ISSUE TITLE
Problema con le immagini negli ordini fornitori

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#911]
Creo un ordine cliente e inserisco solo articoli, senza aggiungere righe di descrizione.
Nella stampa non compare alcuna immagine.
Se invece aggiungo una riga di descrizione, le immagini vengono regolarmente visualizzate.

Altro problema che riscontro è che se nell'anagrafica dell'articolo non c'è l'immagine, al suo posto nella stampa appare una X che non è esteticamente bella.

![img](https://user-images.githubusercontent.com/40104356/99681453-701b1100-2a7e-11eb-8c36-8e2fefbdd89b.png)

Sto utilizzando la versione 2.4.17.1, quindi non so se con l'ultima release il problema sia stato risolto.

**Comment by Dasc3er** [comment]
Grazie per la segnalazione!

**Comment by idraulicadueci** [comment]
Il problema si ripresenta nella versione 2.4.19

**Comment by Dasc3er** [comment]
Il problema è stato risolto nella 2.4.20.
