### ISSUE TITLE
Errore durante importazione FE con PHP 8

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#912]
## Comportamento attuale

Errore in fase di import con PHP 8

## Passi per riprodurre il comportamento

1. Importare una FE, seguendo tutti i normali passaggi

Il problema riguarda il seguente controllo nel file src/Uploads.php (riga 220):
```php
// Creazione file fisico
        if (
            !directory($directory) ||
            (is_uploaded_file($source['tmp_name']) && !move_uploaded_file($source['tmp_name'], $directory.'/'.$filename)) ||
            (is_string($source) && !copy($source, $directory.'/'.$filename))
        ) {
            return null;
        }
```

Eventuali log relativi (cartella **logs/**):
```
[2020-12-09 09:52:04] Logs.ERROR: Uncaught Exception TypeError: "Cannot access offset of type string on string" at /home/battistini-impianti.it/public_html/amministrazione/src/Uploads.php line 220 {"exception":"[object] (TypeError(code: 0): Cannot access offset of type string on string at /home/battistini-impianti.it/public_html/amministrazione/src/Uploads.php:220)"}
{"url":"/editor.php?id_module=15&id_plugin=19&id_record=19&data_registrazione=2020-11-25&","ip":"141.101.76.45","http_method":"POST","server":"amministrazione.battistini-impianti.it","referrer":"https://amministrazione.battistini-impianti.it/editor.php?id_module=15&id_plugin=19&id_record=19&data_registrazione=2020-11-25&","uid":"db446be"}
```

## Contesto

* Modulo: Fatture di acquisto
* Versione del progetto: 2.4.19
* Versione PHP: 8.0
* Tipo di server: OpenLiteSpeed

**Comment by Dasc3er** [comment]
Grazie per la segnalazione!
Hai modo di verificare se il commit indicato risolve il problema?

**Comment by maicol07** [comment]
Dopo faccio una prova

**Comment by maicol07** [comment]
Sembra funzionare tutto correttamente così

**Comment by Dasc3er** [comment]
Perfetto, se trovi altri malfunzionamenti siamo sempre disponibili per risolverli! 😄

**Comment by maicol07** [comment]
@Dasc3er purtroppo l'errore si è ripresentato. Ho indagato e penso di aver trovato il fix definitivo. In aggiunta al fix originale, bisogna fare un controllo su `$source['data']`.

Quindi nel file `Uploads.php`:

7e5e370[/src/Uploads.php#L129](https://github.com/devcode-it/openstamanager/blob/7e5e370176f819d0cf036b5d8186d5c4ae5b13ef/src/Uploads.php#L129)

diventa:

```php
if (is_array($source)) {
    $data['size'] = $source['size'];
}
```

**Comment by Dasc3er** [comment]
@maicol07 Grazie ancora!
Purtroppo abbiamo scoperto che con la versione 2.4.* non saremo comunque in grado di supportare completamente PHP 8: per ora abbiamo individuato la libreria CSV che utilizziamo come incompatibile. Quindi con PHP 8 potrebbero non funzionare importazione ed esportazione CSV, fino al rilascio della futura 2.5 (che rimuoverà il supporto a PHP 5.*).

Se trovi altri problemi, segnalali pure e vedremo di risolverli il più rapidamente possibile 😄

**Comment by maicol07** [comment]
Molto bene! Ho già notato che è in sviluppo la branch laravel con la conversione del progetto a Laravel 8
