### ISSUE TITLE
Dopo aggrionamento 2.4.19 mancanza pianificazione, consuntivo, note interne in contratti

### ISSUE THREAD

**Issue by stefanostc** [devcode-it/openstamanager#913]
## Comportamento richiesto

Fino alla versin precedente aprendo un contratto in alto a dx c'erano le seguenti opzioni:
-Pianificazione fatturazione
-Rinnovi
-Pianificazione attività
-Consuntivo
-Note interne
-Info

## Comportamento attuale

Dopo l'aggrionamento alla verison 2.4.19 tutte le voci sopra sono scomparse ed è visibile solamente una voce Plugin, che se premuta apre una barra laterale destra vuota.

**Comment by Dasc3er** [comment]
@stefanostc Nelle nuove versioni è disponibile una barra laterale a destra per i plugin,
Se non la vedi, è probabilmente presente **include/custom/top.php**, che devi rimuovere.

**Comment by stefanostc** [comment]
Eliminato il file  include/custom/top.php ora funziona tutto correttamente. Grazie
