### ISSUE TITLE
Bug: import anagrafiche

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#914]
Nella versione 2.4.20 (in sviluppo) in fase di import non viene visualizzato il campo "Codice":

![immagine](https://user-images.githubusercontent.com/30728163/102481307-d422fc00-4061-11eb-85de-639866d9f317.png)

**Comment by Dasc3er** [comment]
@lucasalva87 Non sono riuscito a riprodurre il problema.
In particolare, ho esportato le anagrafiche dal gestionale tramite la nuova funzione sperimentale di esportazione. Importando quindi il file prodotto, i campi vengono compilati correttamente in automatico.
![image](https://user-images.githubusercontent.com/15911489/102619219-61d31a00-413c-11eb-82d1-be0e0ec6a8a0.png)

**Comment by lucasalva87** [comment]
Grazie @Dasc3er faccio un po' di test e ti aggiorno

**Comment by lucasalva87** [comment]
Dietro suggerimento di @loviuz ho provato a ricompilare gli assets però non ha funzionato. 
Provi eventualmente a ricompilarli anche tu?

**Comment by Dasc3er** [comment]
Già provato dopo aver ricompilato gli assets, che comunque non dovrebbero aver influenzato il bug in questione. È possibile che nel file che stai utilizzando ci sia qualche carattere speciale o spazio in "Codice"?

**Comment by lucasalva87** [comment]
Il file che sto utilizzando (se vuoi provare) è quello di esempio generato dal pulsante 

![immagine](https://user-images.githubusercontent.com/30728163/102640387-acfc2580-415a-11eb-9f7f-92d99fc976e8.png)

**Comment by lucasalva87** [comment]
Segnalo che il problema (almeno per me) persiste anche con la versione 2.4.20 rilasciata il 31/12/2020.

**Comment by loviuz** [comment]
@lucasalva87 puoi riprovare? Sembra funzioni con la 2.4.23 in sviluppo

**Comment by lucasalva87** [comment]
Confermo che dalla 2.4.22, o più nello specifico con il commit 018b716d710a631d60d1c4f53f5a655e72df7033, il problema è stato risolto.
