### ISSUE TITLE
Ordinamento Preventivi per numero non ordina correttamente

### ISSUE THREAD

**Issue by stefanostc** [devcode-it/openstamanager#915]
## Comportamento richiesto

Cliccando sulla colonna Numero l'ordonamento dovrebbe essere 1,2,3, ..., 10,111

## Comportamento attuale

L'ordinamenot è alfabetico 1,10,11...., 2,20......

**Comment by Dasc3er** [comment]
Ciao @stefanostc ,
tecnicamente non si tratta di un errore poichè il codice potrebbe contenere anche altri contenuti alfanumerici non legati al semplice numero progressivo (esempio: Fatture).
Puoi in ogni caso modificare l'ordinamento dal modulo Viste, che devi abilitare da Strumenti -> Stato dei servizi. Andando quindi dentro a Strumenti -> Viste -> Preventivi, puoi copiare il campo  Numero e aggiungere una query personalizzata per l'ordinamento relativo. Questo richiede però che tu abbia un po' di esperienza con SQL.

**Comment by stefanostc** [comment]
Grazie,
allego come creare la colonna numerica su cui fare l'ordinamento
![immagine](https://user-images.githubusercontent.com/60810666/102967580-88a19f80-44f2-11eb-8faa-bc5910ce7b0c.png)

**Comment by Dasc3er** [comment]
Grazie per la condivisione!
