### ISSUE TITLE
Modifica colonne non produce nessun effetto

### ISSUE THREAD

**Issue by stefanostc** [devcode-it/openstamanager#916]
## Comportamento richiesto

Selezionando lr colonne, queste dovrebbero essere visibili o meno.

## Comportamento attuale

Clicco sulla check box della colonna interassata, questa cambia colore da rotto a verde, poi clicco su X la pagina ricarica ma non mantiene la scelta fatta

**Comment by Dasc3er** [comment]
Ciao @stefanostc ,
che versione del software stai utilizzando? Che versione di PHP?
Ci sono errori nei file di log (logs/error.log)?

**Comment by stefanostc** [comment]
PHP (7.2.24-0ubuntu0.18.04.7)
 Versione 2.4.19 (cd6e0129) 

Nessun log relativo di errore

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione!
In effetti  il problema si verifica nel caso in cui non sia abilitato il modulo Viste. Poichè giustamente il comportamento segnalato è errato, ora dovrebbe essere disponibile in ogni caso (a partire dalla futura versione 2.4.20).

**Comment by stefanostc** [comment]
Grazie, a conferma nel frattempo ho attivato il modulo Vista ed ha iniziato a funzionare.
