### ISSUE TITLE
Problemi con una FE

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#921]
Questa FE non viene caricata bene (vengono create righe anomale) e mostra totale = 0 (anche se in fase di import le righe venivano mostrate correttamente). Questo comportamento non si verifica con le altre fatture...

[IT00891340408_01WLL.xml.zip](https://github.com/devcode-it/openstamanager/files/5770546/IT00891340408_01WLL.xml.zip)

**Comment by Shero08** [comment]
Buonasera, io invece il problema di importazione lo riscontro con tutte le fatture. Crea decine di arrotondamenti ed a volte non carica nemmeno iva. Grazie

**Comment by maicol07** [comment]
@devcode-it

**Comment by Shero08** [comment]
Buonasera, con le correzioni adesso non si creano più righe aggiuntive che non esistono, ma quando bisogna inserire l'aliquota IVA mi dice sempre nessun risultato trovato. Grazie

**Comment by Dasc3er** [comment]
Ciao @Shero08 ,
È possibile che in questo caso non siano disponibili aliquote Iva nel gestionale con la stessa percentuale indicata nella fattura elettronica.

**Comment by Shero08** [comment]
Ho verificato, in pratica il problema era che la fattura era dello scorso anno e l'aliquota IVA era stata cancellata e quindi non me la faceva selezionare. Per me il problema è risolto. Grazie
