### ISSUE TITLE
Modifiche Fatture per sconto su corrispettivo (cessione del credito ecobonus)

### ISSUE THREAD

**Issue by ston85** [devcode-it/openstamanager#922]
Buongiorno, 
volevo proporre un miglioramento in ottica di rendere il documento Fattura più leggibile nei casi sempre più diffusi di cessione del credito mediante sconto su corrispettivo per la realizzazione di opere o impianti (superbonus 110, ecobonus etc...)

Attualmente lo sconto va a decurtare l'imponibile, ed è possibile utilizzarlo per questo scopo, 
si può indicare lo sconto su corrispetivo solo nel campo note, così facendo il calcolo dello scadenziario non risponde però alla realtà. 

Servirebbe un nuovo campo nel quale si può definire il valore del credito acquisito, per poter calcolare così il netto a pagare (nelle stame visivamente simile a quello per lo split payment)

I pagamenti delle fatture saranno poi evasi mediante:
- la cessione del credito sul cassetto fiscale e non di un vero e proprio pagamento per la quota del credito acquisito 
- normale pagamento per la quota pari al valore del netto a pagare  

* Versione del progetto attualmente utilizzato: 2.4.20

**Comment by loviuz** [comment]
Ciao @ston85, è stato introdotto questo campo nella versione 2.4.21 ma nella 2.4.22 ha qualche automatismo in più. E' documentato qui come utilizzare lo sconto in fattura con le indicazioni per la fattura elettronica:
https://docs.openstamanager.com/procedure-contabili/fattura-elettronica/decreto-rilancio-2020

E' quello che cercavi?

**Comment by ston85** [comment]
Ciao,
si proprio questo,
molto bravi!

Il giorno sab 15 mag 2021 alle ore 11:21 loviuz ***@***.***>
ha scritto:
