### ISSUE TITLE
Problema con la numerazione degli interventi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#924]
Ho inserito un nuovo intervento nel nuovo anno con richiesta dell'anno scorso. La numerazione che è stata data è relativa all'anno nuovo (0001/2021)
Successivamente ho creato un nuovo intervento sempre nell'anno nuovo con richiesta dell'anno in corso. La numerazione assegnata è sempre 0001/2021, quindi adesso mi ritrovo due interventi con lo stesso numero progressivo.

OSM 2.4.19

**Comment by loviuz** [comment]
la data richiesta dei 2 interventi qual è?

**Comment by idraulicadueci** [comment]
Una è del 30/12/2020, l'altra del 04/01/2021.

**Comment by lucasalva87** [comment]
Dovrebbere essere stato risolto con la fix dbc63b93b4bfe7a13a4966cabdab76c271dd2cb9
