### ISSUE TITLE
Problema sconti in fattura

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#925]
Versione 2.4.20

Se si prova ad inviare una fattura per la quale si è applicato uno sconto unitario viene restiuto il seguente scarto:
**2.2.2.6 <Imposta> non calcolata secondo le regole definite nelle specifiche tecniche** 
Es.

![immagine](https://user-images.githubusercontent.com/30728163/104011262-1990a000-51ae-11eb-99e7-9b71fb06eca4.png)

![immagine](https://user-images.githubusercontent.com/30728163/104012046-6e80e600-51af-11eb-8cc2-517cb547b16c.png)

Per replicare il problema creare un contratto contenente righe con sconto e provare a convertilo in fattura.

**Comment by Dasc3er** [comment]
@lucasalva87 Informazioni sull'iva applicata a quanto dovrebbero essere i totali?

**Comment by lucasalva87** [comment]
Sì scusami ho visto ora che dall'immagine non si vede. Iva applicata 22% i totali dovrebbe essere 244,00 e non 208,80

**Comment by Dasc3er** [comment]
@lucasalva87 Ho appena provato, facendo da Contratto a fattura come descritto. Il problema non si presenta e i conti sono corretti.
![image](https://user-images.githubusercontent.com/15911489/104025747-603dc480-51c5-11eb-9ae8-f8542fbffb50.png)

**Comment by lucasalva87** [comment]
Grazie @Dasc3er . Verifico. Forse ho trovato comunque un anomalia. Se si clicca sul pulsante arancione di modifica compare questa schermata. 

![immagine](https://user-images.githubusercontent.com/30728163/104027825-3afe8580-51c8-11eb-9e5d-a732b00fa6aa.png)

Ovvero propone uno sconto di 97,60 e non di 80,00 euro

**Comment by Dasc3er** [comment]
Non è che magari hai qualcosa attivo, tipo i prezzi ivati?

**Comment by lucasalva87** [comment]
No, da impostazioni i prezzi ivati sono disattivati. Ma è proprio li che sbaglia: in fase di import riporta lo sconto come se fosse ivato. Se poi correggo lo sconto unitario e lo riporto ad 80,00, lo mantiene.

**Comment by Dasc3er** [comment]
@lucasalva87 In effetti il problema era presente. Puoi verificare se ora è risolto?
Allo stesso modo, potresti verificare se gli sconti indipendenti sono riportati correttamente?

**Comment by loviuz** [comment]
io ho provato e sembra risolto

**Comment by loviuz** [comment]
io ho provato e funziona

**Comment by loviuz** [comment]
io ho provato e funziona

**Comment by lucasalva87** [comment]
Sì ora è ok, grazie 👍
