### ISSUE TITLE
Problema creazione sottocategorie articoli

### ISSUE THREAD

**Issue by Shero08** [devcode-it/openstamanager#926]
Buonasera, volevo segnalare questa problematica. Se sono nella creazione di un articolo e voglio creare una sottocategoria all'articolo me la crea come categoria principale ma non la fa nemmeno selezionare, la lega all'articolo e per eliminarla bisogna poi togliere il collegamento all'articolo. Non so se sono stato chiaro, nel caso serva mi cercherò di spiegarmi meglio.

**Comment by medianik** [comment]
Confermo il problema, inoltre non funziona il caricamento di un nuovo articolo tramite i moduli ordini, attività ecc..., praticamene inserendo il nuovo articolo tramite i vari moduli quando lo aggiungi per inserirlo nella casella di testo "articoli" lo stesso articolo dovrebbe comparire anche nella casella di testo sottostante "descrizione" ma ciò non succede.

**Comment by Dasc3er** [comment]
@MatteoPistorello Mi sembra di aver visto un commit relativo alle sottocategorie, il problema è risolto?

**Comment by medianik** [comment]
Si grazie tutto risolto come ho già scritto in ghitub.

Antonio
