### ISSUE TITLE
Problema style.css custom nelle stampe

### ISSUE THREAD

**Issue by kalipso52** [devcode-it/openstamanager#927]
## Comportamento richiesto

Il file templates/base/custom/style.css venga letto.

## Comportamento attuale

Dopo update dalla 2.4.15 alla 2.4.20 il file style.css della nella cartella custom delle stampe non viene letto. 

## Passi per riprodurre il comportamento

1. Creare cartella custom in templates/base/
2. Creare file style.css con una custom properties differente dal file principale
3. Verificare che la proprietà cambi nella stampa

## Contesto

* Modulo:
* Versione del progetto: 2.4.20
* Versione PHP: 7.4.13
* Tipo di server: Linux

**Comment by Dasc3er** [comment]
@kalipso52 Mi permetto di far notare che a livello di codice non ho trovato nessuna indicazione che tale sostituzione fosse permessa, in nessuna versione rilasciata fino ad ora.
Con il commit indicato dovrebbe ora essere disponibile il funzionamento corretto.

**Comment by kalipso52** [comment]
@Dasc3er In effetti anch'io non ho trovato alcun riferimento, non mi spiego come potesse funzionare prima. 
Per quanto riguarda la fix sembra non funzionare, continua ad utilizzare lo style.css presente in templates/base e ignora quello in templates/base/custom

**Comment by Dasc3er** [comment]
Segnalo che c'è stata una correzione minore sul commit che ho indicato, che dovrebbe risolvere un problema di percorso con gli stili.
È però strano che non si sia sviluppata nessuna modifica...

**Comment by kalipso52** [comment]
Non l'avevo vista, perfetto funziona.
Grazie!
