### ISSUE TITLE
Fornitore predefinito non settabile in articoli

### ISSUE THREAD

**Issue by fargianni** [devcode-it/openstamanager#928]
## Comportamento richiesto

Quando si crea o edita un articolo cliccando sul campo "Fornitore predefinito" dovrebbe comparire la lista delle anagrafiche fornitore tra cui scegliere per impostare il campo

## Comportamento attuale

La lista appare sempre vuota (ovviamente sono presenti anagrafiche fornitore) ed il campo non è quindi settabile
![immagine](https://user-images.githubusercontent.com/77353938/104472317-205b5080-55bc-11eb-9d90-d0f3e6652414.png)

Il bug appare sia in ambiente di produzione migrato da 2.4.15 a 2.4.20 sia su installazione pulita.

Inoltre negli articoli già presenti ante upgrade, e con il fornitore predefinito già impostato, se si entra in modifica sull'articolo e si salva (anche senza aver toccato nulla) il fornitore presente si perde

**PRIMA**
![immagine](https://user-images.githubusercontent.com/77353938/104472737-8ba52280-55bc-11eb-82f3-b20d56d5831f.png)

**DOPO**
![immagine](https://user-images.githubusercontent.com/77353938/104472803-9d86c580-55bc-11eb-8909-87cfc547805d.png)

## Contesto

* Modulo: Articoli
* Versione del progetto: 2.4.20
* Versione PHP: 7.3.19
* Tipo di server: xampp 7.3.19 (apache 2.4.43 php 7.3.19 MariaDB 10.4.13 Windows 10 pro

**Comment by ir0n87** [comment]
Sto provando ad aggiornare dalla .20 alla .21
Il processo automatico si blocca e se provo a lanciare l'sql manualmente appare questo:

Analisi statica:

Sono stati trovati 1 errori durante l'analisi.

    Token inatteso. (near "(" at position 209)

Query SQL: Documentazione

-- Fix fornitore predefinito articoli INSERT INTO `mg_prezzi_articoli`( `id_articolo`, `id_anagrafica`, `prezzo_unitario`, `prezzo_unitario_ivato`, `dir`, `sconto_percentuale` )( SELECT `mg_articoli`.`id`, `mg_articoli`.`id_fornitore`, `mg_articoli`.`prezzo_acquisto`, `mg_articoli`.`prezzo_acquisto` + `mg_articoli`.`prezzo_acquisto` * IFNULL( `co_iva`.`percentuale`, `iva_default`.`percentuale` ) / 100, 'uscita', 0 FROM `mg_articoli` LEFT JOIN `co_iva` ON `mg_articoli`.`idiva_vendita` = `co_iva`.`id` LEFT JOIN( SELECT `valore` AS `idiva` FROM `zz_settings` WHERE `nome` = 'Iva predefinita' ) AS `impostazioni` ON 1 = 1 LEFT JOIN `co_iva` AS `iva_default` ON `iva_default`.`id` = `impostazioni`.`idiva` WHERE `id_fornitore` NOT IN( SELECT `id_anagrafica` FROM `mg_prezzi_articoli` AS `prezzi_specifica` WHERE `id_articolo` = `mg_articoli`.`id` ) AND `id_fornitore` IS NOT NULL )

Messaggio di MySQL: Documentazione
#1452 - Cannot add or update a child row: a foreign key constraint fails (`gestionale`.`mg_prezzi_articoli`, CONSTRAINT `mg_prezzi_articoli_ibfk_2` FOREIGN KEY (`id_anagrafica`) REFERENCES `an_anagrafiche` (`idanagrafica`))

**Comment by loviuz** [comment]
Puoi provare a sostituire quella query con questa?
```

-- Fix fornitore predefinito articoli
INSERT INTO `mg_prezzi_articoli`(
    `id_articolo`,
    `id_anagrafica`,
    `prezzo_unitario`,
    `prezzo_unitario_ivato`,
    `dir`,
    `sconto_percentuale`
)(
    SELECT
        `mg_articoli`.`id`,
        `mg_articoli`.`id_fornitore`,
        `mg_articoli`.`prezzo_acquisto`,
        `mg_articoli`.`prezzo_acquisto` + `mg_articoli`.`prezzo_acquisto` * IFNULL(
            `co_iva`.`percentuale`,
            `iva_default`.`percentuale`
        ) / 100,
        'uscita',
        0
    FROM
        `mg_articoli`
    LEFT JOIN `co_iva` ON `mg_articoli`.`idiva_vendita` = `co_iva`.`id`
    LEFT JOIN(
        SELECT
            `valore` AS `idiva`
        FROM
            `zz_settings`
        WHERE
            `nome` = 'Iva predefinita'
    ) AS `impostazioni`
ON
    1 = 1
LEFT JOIN `co_iva` AS `iva_default`
ON
    `iva_default`.`id` = `impostazioni`.`idiva`
WHERE
    `id_fornitore` NOT IN(
    SELECT
        `id_anagrafica`
    FROM
        `mg_prezzi_articoli` AS `prezzi_specifica`
    WHERE
        `id_articolo` = `mg_articoli`.`id`
) AND `id_fornitore` IN (SELECT `idanagrafica` FROM `an_anagrafiche`)
); 
```

**Comment by fargianni** [comment]
Scusate come non detto per l'importazione. :)

Non avevo notato che è possibile importare i prezzi specifici in quanto ci sono gli appositi campi nel tracciato csv.

Che vergogna!!

Se tocca a me farlo (scusate ma sono un po niubbo di github) procederò domani a chiudere la segnalazione.

Grazie per la tempestiva risoluzione

**Comment by ir0n87** [comment]
> Puoi provare a sostituire quella query con questa?
> 
> ```
> 
> -- Fix fornitore predefinito articoli
> INSERT INTO `mg_prezzi_articoli`(
>     `id_articolo`,
>     `id_anagrafica`,
>     `prezzo_unitario`,
>     `prezzo_unitario_ivato`,
>     `dir`,
>     `sconto_percentuale`
> )(
>     SELECT
>         `mg_articoli`.`id`,
>         `mg_articoli`.`id_fornitore`,
>         `mg_articoli`.`prezzo_acquisto`,
>         `mg_articoli`.`prezzo_acquisto` + `mg_articoli`.`prezzo_acquisto` * IFNULL(
>             `co_iva`.`percentuale`,
>             `iva_default`.`percentuale`
>         ) / 100,
>         'uscita',
>         0
>     FROM
>         `mg_articoli`
>     LEFT JOIN `co_iva` ON `mg_articoli`.`idiva_vendita` = `co_iva`.`id`
>     LEFT JOIN(
>         SELECT
>             `valore` AS `idiva`
>         FROM
>             `zz_settings`
>         WHERE
>             `nome` = 'Iva predefinita'
>     ) AS `impostazioni`
> ON
>     1 = 1
> LEFT JOIN `co_iva` AS `iva_default`
> ON
>     `iva_default`.`id` = `impostazioni`.`idiva`
> WHERE
>     `id_fornitore` NOT IN(
>     SELECT
>         `id_anagrafica`
>     FROM
>         `mg_prezzi_articoli` AS `prezzi_specifica`
>     WHERE
>         `id_articolo` = `mg_articoli`.`id`
> ) AND `id_fornitore` IN (SELECT `idanagrafica` FROM `an_anagrafiche`)
> ); 
> ```

Così nessun errore! :)

**Comment by loviuz** [comment]
Ottimo! :-)
f49a9436f383f5207f6aafdcf435acd863f7e368

**Comment by idraulicadueci** [comment]
A me continua a non elencarmi i fornitori nell'elenco a discesa. I fornitori predefiniti nelle precedenti versioni, compaiono regolarmente, ma sui nuovi articoli non ho l'elenco.
Non c'è qualche bug nel file /modules/articoli/edit.php?

OSM 2.4.21

**Comment by fargianni** [comment]
In queste ultime release hanno cambiato la gestione del fornitore predefinito in conseguenza della nuova feature di avre più fornitori per ogni articolo.
Quindi per i nuovi articoli occorre creare anche un prezzo specifico (dal plugin prezzi specifici nel menù a sinistra una volta in edit dell'articolo) per il fornitore che si intende usare come predefinito e poi dalla pagina di gestione dell'articolo sarà possibile selezionarlo.
Purtroppo quando si ha un solo fornitore questa modalità di gestione è un po farraginosa.

**Comment by idraulicadueci** [comment]
Ok grazie @fargianni per la risposta. Non avevo capito come era la procedura nella 2.4.21.
