### ISSUE TITLE
PROBLEMA con i DDT in uscita

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#929]
Inserisco un nuovo DDT. Al momento che eseguo il salvataggio mi viene restituito un errore in cui non trova la colonna "peso_manuale"

Sono entrato nella tabella relativa di MySql e ho notato che il campo _null_ era impostato su Falso; ho impostato il valore su Vero e adesso il problema non si presenta.

Vedi file log allegato
[error.log](https://github.com/devcode-it/openstamanager/files/5815725/error.log)

OSM 2.4.21

**Comment by Dasc3er** [comment]
@idraulicadueci Sei sicuro di non avere utilizzato una versione parzialmente aggiornata del gestionale?
Le query sono correttamente presenti:
https://github.com/devcode-it/openstamanager/blob/c8d980fa452f2657402dd22c9261b3380d3e4d3a/update/2_4_21.sql#L43
```sql
-- Aggiunto flag peso e volume manuale in fatture e ddt
ALTER TABLE `dt_ddt` ADD `peso_manuale` TINYINT(1) NOT NULL AFTER `volume`;
ALTER TABLE `dt_ddt` ADD `volume_manuale` TINYINT(1) NOT NULL AFTER `peso_manuale`;
ALTER TABLE `co_documenti` ADD `peso_manuale` TINYINT(1) NOT NULL AFTER `volume`;
ALTER TABLE `co_documenti` ADD `volume_manuale` TINYINT(1) NOT NULL AFTER `peso_manuale`;
```

**Comment by idraulicadueci** [comment]
Non so, ho eseguito l'aggiornamento con la release ufficiale. Con la modifica che ho indicato il problema non si è ripresentato
