### ISSUE TITLE
fattura di vendita , non funziona duplica fattura

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#93]
Quando duplico una fattura mi raddoppia gli articoli nella copia. Le righe generiche invece a quanto ho constatato vengono copiate correttamente.
 
Versione OSM 2.3.1/master

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione!
Il problema era generato dal fatto che, per completare la movimentazione da magazzino, viene utilizzata la funzione _add_articolo_infattura_ che inserisce nuovamente la riga...

@lepool Potresti confermare la risoluzione con il commit 7ee53829eb4815201a9301587013b75987a3ad45?

**Comment by lepool** [comment]
Ottimo, sembra risolto. Anche le movimentazioni magazzino vengono aggiornate. :+1:
