### ISSUE TITLE
BUG viste DDT

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#930]
Nella vista dei DDT nelle colonne vengono riportati numeri anziché descrizioni. Ho notato, per esempio, che la query del campo "CAUSALE":

``dt_causalet`.`descrizione``

restituisce il valore 0,0000 anziché la stringa corrispondente (Reso, Vendita, ecc.)

OSM 2.4.21

**Comment by loviuz** [comment]
E' stato risolto nella 2.4.22, ma si può anticipare la fix abilitando il modulo "Viste" e togliendo la spunta su "Formattabile" su questi 2 campi, è solo un errore di impostazione delle colonne.
