### ISSUE TITLE
Problema su digitazione indirizzo email

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#932]
Quando sto per inviare un'email, dopo aver digitato l'indirizzo destinatario completo, se tento di modificarlo non riesco ad aggiungere il carattere "." (punto) nella parte prima della chiocciola:

![immagine](https://user-images.githubusercontent.com/1647128/104700292-39771500-5714-11eb-8e0e-825479ecded2.png)

Ad esempio qui, se vado dopo "mario" a mettere il punto per scrivere "mario.rossi@cliente.it" non viene considerato il punto. Credo dipenda da un plugin JS usato.

**Comment by Dasc3er** [comment]
Sospetto che il problema sia la maschera di inputmask impostata, ma ciò significa che il problema è presente da numerose versioni.

**Comment by Dasc3er** [comment]
@loviuz Controllando al momento nella versione in sviluppo, il problema non si presenta: una volta inserito un qualunque indirizzo email (scritto completamente o completato in automatico dai suggerimenti), è sempre modificabile e il punto viene scritto correttamente.

**Comment by loviuz** [comment]
Confermo che ora funziona correttamente.
