### ISSUE TITLE
BUG Contratti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#934]
## Comportamento attuale

Se provo a inserire un contratto con validità espressa in mesi o anni mi viene restituito un errore (vedi file log allegato)

[error.log](https://github.com/devcode-it/openstamanager/files/5853892/error.log)

Ho notato inoltre che nel modulo CONTRATTI che il campo "Validità contratto" nella stampa compare come "validità offerta"

OSM 2.4.21

**Comment by Dasc3er** [comment]
@MatteoPistorello Mi sembra di aver visto un commit relativo alla validità dei contratti, il problema è risolto?
