### ISSUE TITLE
Scadenze non calcolate correttamente

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#937]
## Comportamento attuale
Le scadenze vengono calcolate in modo errato: ogni fattura importata ha coeme scadenza 0,00 € ma con data corretto. Avendo importo nullo, non vengono riportate nello scadenziario

## Passi per riprodurre il comportamento
1. Importare una fattura elettronica

## Contesto

* Modulo: Fatture di acquisto
* Versione del progetto: 2.4.21
* Versione PHP: 7.4
* Tipo di server: OpenLiteSpeed

**Comment by Dasc3er** [comment]
@maicol07 Grazie per la segnalazione!
In questo caso il problema si verificava per fatture elettroniche senza il dato DatiPagamento (facoltativo, ma solitamente incluso).
Ora il problema dovrebbe essere risolto, se puoi confermare 😄

**Comment by lucasalva87** [comment]
Grazie @Dasc3er! Confermo da parte mia che il problema sembra risolto.
