### ISSUE TITLE
MIGLIORIA Collegamento a Prima nota

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#939]
## Comportamento richiesto

Creare un collegamento alla prima nota direttamente dalla fattura oppure dallo scadenzario

## Comportamento attuale

Quando una fattura è saldata totalmente, nel modulo continua a esserci il collegamento allo scadenzario, e questo direi che è corretto per seguire lo storico dello scadenzario, che nelle versioni precedenti veniva eliminato totalmente, insieme a eventuali allegati in esso inseriti (vedi issue #829). Serve però il collegamento alla relativa prima nota generata.
Attualmente, l'unico modo per risalire alla prima nota è arrivarci dal relativo modulo.

OSM 2.4.21

**Comment by Pek5892** [comment]
Introdotto con commit 2.4.22
