### ISSUE TITLE
Problema prezzi articoli

### ISSUE THREAD

**Issue by cast941** [devcode-it/openstamanager#94]
Buongiorno, 
se inserisco un articolo e metto ad esempio (sia su prezzo acquisto, sia su prezzo vendita)
0,XX viene sempre e comunque sostituito da 0. (dove XX un qualsiasi numero).

Potete aiutarmi ?

Versione 2.3 beta

**Comment by Dasc3er** [comment]
Ciao @cast941,
il problema in questione era già stato segnalato con la issue #50 e risolto nella versione in sviluppo...
Prossimamente dovrebbe essere rilasciata la relativa versione stabile, con la soluzione a diversi bug presenti nelle versioni beta.

**Comment by cast941** [comment]
Ok ti ringrazio per la risposta, ho guardato anche la issue #50 ma non capisco come risolvere il problema.
potresti darmi una dritta?

Grazie

**Comment by Dasc3er** [comment]
@cast941 Dovresti aggiornare il file **src/Intl/Formatter.php** con la [versione master corrente ](https://github.com/devcode-it/openstamanager/blob/master/src/Intl/Formatter.php)...
Per sicurezza, effettua prima una copia del file originale per ripristinarla se si verificano ulteriori problemi...

**Comment by cast941** [comment]
Grazie mille, sostituendolo si è risolto !
