### ISSUE TITLE
Quando si abilita lo split payment per una fattura andrebbero ricalcolate le scadenze

### ISSUE THREAD

**Issue by lucasalva87** [devcode-it/openstamanager#942]
Versione 2.4.22 (in sviluppo)

**Comment by Dasc3er** [comment]
@lucasalva87 Cosa intendi?
Per abilitare lo Split payment bisogna mettere la fattura in stato Bozza, che di default rimuove le scadenze. Successivamente il passaggio ad Emessa dovrebbe ricalcolare le scadenze correttamente.

**Comment by lucasalva87** [comment]
Fattura di acquisto emessa, scadenza calcolata 298,90 (245+IVA). La riporto in bozza e abilito lo split payment.  La ri-emetto. La scadenza calcolata rimane 298,90 mentre dovrebbe andare a 245,00 in quanto il fornitore , in questo caso, dovrebbe incassare la fattura al netto dell'IVA.

**Comment by cigo76** [comment]
> 
> 
> Fattura di acquisto emessa, scadenza calcolata 298,90 (245+IVA). La riporto in bozza e abilito lo split payment. La ri-emetto. La scadenza calcolata rimane 298,90 mentre dovrebbe andare a 245,00 in quanto il fornitore , in questo caso, dovrebbe incassare la fattura al netto dell'IVA la quale sarà versata direttamente dall’ente di Pubblica Amministrazione all’Erario. @loviuz corretto ?

Esatto!! ho riscontrato anche io l'errore!!

**Comment by loviuz** [comment]
@MatteoPistorello

**Comment by MatteoPistorello** [comment]
Il bug è stato risolto nella versione in sviluppo (2.4.23), questo è il commit: https://github.com/devcode-it/openstamanager/commit/ce038ad0b317db7d45e8c7c34f1bf1d6ff6a9b23
