### ISSUE TITLE
BUG Scadenzario su azione di gruppo

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#943]
## Comportamento attuale

Provo a registrare il pagamento di più scadenze, (con pagamenti rateizzati) utilizzando l'azione di gruppo "Registrazione contabile", nel modal di creazione della prima nota vengono inserite tutte le rate.

## Passi per riprodurre il comportamento

Creare due fatture con un pagamento 30-60-90 gg d.f.f.m
Aprire il modulo scadenzario e selezionare le due rate in scadenza a 30 gg d.f.f.m.
Azioni di gruppo ---> Registrazione contabile

Vengono inserite tutte le scadenze relative alla fattura (30-60-90 gg) oltre quella selezionata per il pagamento (30 gg)

OSM 2.4.21

**Comment by Dasc3er** [comment]
@idraulicadueci Il comportamento è attualmente considerato come corretto a causa delle struttura interna del gestionale.
Infatti, poiché le Scadenze sono legate in modo "leggero" ai movimenti in Prima nota, al momento di selezione di una scadenza di un documento vengono proposte in contemporanea tutte le scadenze ancora da pagare del documento. Alla registrazione della Prima Nota viene sempre pagata la prima scadenza disponibile del documento, e le successive se l'importo è sufficientemente elevato: il gestionale non supporta quindi il movimento contabile per una specifica scadenza selezionata liberamente.

**Comment by Pek5892** [comment]
Risolto nelle versioni successive
