### ISSUE TITLE
BUG su modulo "Tipi di attività"

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#944]
## Comportamento attuale

Se vado a inserire un nuovo tipo di attività, il capo "Tempo standard" restituisce l'errore _"Questo valore è troppo lungo. La lunghezza massima è di 5 caratteri"_ Nelle impostazione ho il numero di decimali settato a 4 e nel campo indicato viene sicuramente conteggiata anche la virgola.

## Passi per riprodurre il comportamento

Impostare il numero di decimali a 4
Aprire il modulo Tipi di attività
Aggiungere una nuovo tipo di attività
Cliccare Aggiungi

OSM 2.4.21

**Comment by idraulicadueci** [comment]
Ho provato a settare le cifre decimali su importi a 3 dalle impostazioni generali, e il problema non si presenta.

**Comment by Shero08** [comment]
Stesso problema anche a me. Inoltre se sto modificando un'attività e voglio modificare in "Ore di Lavoro" un tecnico, non mi completa la modifica perchè nel campo "tipo di attività" esce vuoto e non mi da nessun risultato.
