### ISSUE TITLE
Note interne orfane

### ISSUE THREAD

**Issue by loviuz** [devcode-it/openstamanager#945]
Quando si eliminano dei record (fatture, attività, ecc), se queste hanno delle note interne associate con una data di scadenza, rimangono a database e rimangono visualizzate nel widget "Notifiche interne", con il link per aprire il record padre che risulta non trovato perché eliminato.

- Conviene lasciare la nota e il link non cliccabile? Di contro c'è che la nota non sarà più recuperabile.
- Conviene invece fare in modo che la nota collegata al record cancellato venga anch'essa eliminata? Non si può fare con le foreign keys, ma magari si può aggiungere una operazione **delete** nel file `actions.php` principale in modo che come operazione aggiuntiva nel caso di eliminazione record elimini anche eventuali note collegate.

**Comment by Dasc3er** [comment]
@loviuz Sempre in relazione a questo argomento, si verifica lo stesso comportamento per Allegati, Checklist e Campi personalizzati.
Si potrebbe vedere di generalizzare con l'utilizzo delle classi una procedura automatica di cleanup alla rimozione degli elementi.
