### ISSUE TITLE
Stampa Piano dei conti - Imponibile senza sconto

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#946]
## Comportamento richiesto

Quando stampo il piano dei conti, deve essere indicato, secondo me, l'imponibile scontato.
## Comportamento attuale

Attualmente quando stampo il piano dei conti viene indicato l'imponibile della fattura senza lo sconto applicato

## Possibile soluzione

Non saprei in quanto è troppo complicato il codice per le mie conoscenze

## Passi per riprodurre il comportamento

Registrare una fattura di acquisto con sconto sull'imponibile e stampare il piano dei conti. 

* Modulo: 
* Versione del progetto: 2.4.21
* Versione PHP: PHP 7.0.33-0ubuntu0.16.04.16 (cli) ( NTS )
* Tipo di server: Immagine Docker

**Comment by Dasc3er** [comment]
@loviuz @lucasalva87 Cosa ne pensate? Il comportamento sarebbe da correggere?

**Comment by Pek5892** [comment]
E' stato risolto nelle versioni successive
