### ISSUE TITLE
Stato contratto

### ISSUE THREAD

**Issue by mdkdog** [devcode-it/openstamanager#947]
## Comportamento richiesto

Quando metto in stato "pagato" una fattura relativa ad un contratto anche il contratto va in stato "pagato"

## Comportamento attuale

Il contratto rimane in stato "Fatturato"

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Fatture / Contratti
* Versione del progetto: 2.4.21 (8b4bd266)
* Versione PHP: PHP 7.4.7
* Tipo di server: FreeBSD

**Comment by Dasc3er** [comment]
@mdkdog Il comportamento attuale è corretto: il Contratto è Fatturato, in qualunque stato sia la Fattura in questione.
Se desideri un comportamento diverso, considera una personalizzazione.
