### ISSUE TITLE
MIGLIORIA: Note interne modificabili con stato documento completato

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#948]
## Comportamento richiesto
Sarebbe opportuno poter modificare una nota interna di un documento anche quando questo assume lo stato completato

## Comportamento attuale

Per adesso, una volta che il documento assume lo stato completato (pagato, fatturato, ecc.), non è più possibile modificare le note interne.

OSM 2.4.21

**Comment by Dasc3er** [comment]
@idraulicadueci Controllando nella versione in sviluppo corrente (2.4.23) il problema non si verifica: è sempre possibile creare nuove Note interne e cancellare le esistenti. Potrebbe trattarsi di una correzione recente, ma non mi sembra visto che l'ultima correzione al riguardo risale a 17 mesi fa (https://github.com/devcode-it/openstamanager/blame/4c41d3ec12187731388b6a7caf5179f3e39109bc/plugins/notes.php#L98).

**Comment by loviuz** [comment]
Confermo.
