### ISSUE TITLE
MIGLIORIA: Ricerca articolo anche con codice fornitore

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#949]
## Comportamento richiesto

Possibilità di filtrare un articolo indicando il codice inserito nel plugin "Prezzi specifici"

## Comportamento attuale

Per ora è possibile ricercare un articolo soltanto indicando il codice interno. Questo crea difficoltà quando, per esempio, da un documento cartaceo voglio risalire all'articolo in anagrafica.

**Comment by Dasc3er** [comment]
@idraulicadueci Intendi che nella tabella principale del modulo Articolo sarebbe utile la ricerca per codice fornitore nel campo Codice?
