### ISSUE TITLE
Interventi numerazione

### ISSUE THREAD

**Issue by fpsoftware** [devcode-it/openstamanager#95]
Segnalazione da Facebook
su openstamanager 2.3 la numerazione degli interventi come può essere effettuata? ho provato a inserire 2018/### o ###/2018 ma quando vado ad aggiungere un secondo intervento mi da errore "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2018/001' for key 'codice'".

**Comment by fpsoftware** [comment]
Il problema potrebbe essere il carattere slash
Infatti mi risponde:

Per il momento risolvo impostando 2018### che sembra non dare errori.

**Comment by Dasc3er** [comment]
Sarebbe utile sapere con quale versione è stato riscontrato questo malfunzionamento, perchè con la versione master non riesco a replicare l'errore...

Tra l'altro, ho notato che se viene effettuato un cambiamento nel formato del codice dalle impostazioni e sono presenti degli interventi precedenti, il nuovo codice viene generato in modo errato...

**Comment by lepool** [comment]
Esatto @Dasc3er !
Avevo 2 interventi inseriti. Ad ogni inserimento di altri interventi , con l'impostazione 2018/### mi aggiungeva al numero nuovo (3) sempre "1" . Mi spiego:

intervento prova 1 -> 1
intervento prova 2 -> 2
intervento prova 3 -> 31
intervento prova 4 -> 311
intervento prova 5 -> 3111

**Comment by Dasc3er** [comment]
Il problema sembra essere generato dalla funzione **get_next_code** quando il codice di base su cui si effettua l'incremento non rispetta il formato definito nelle impostazioni...

**Comment by lepool** [comment]
Nel modulo interventi nel file add.php verrebbe calcolato il codice intervento corretto mentre il codice calcolato in actions.php non legge il codice corretto dal database.

**Comment by Dasc3er** [comment]
@lepool Grazie mille per l'indicazione!
Con il commit a65e73198a28e42c39c53982c15333e4e94a5bc3 ho implementato la stessa procedura nel file **actions.php**, e mi sembra sia stato risolto anche il problema per il caso in cui il codice precedente non utilizzava lo stesso formato.
Se potresti confermare il corretto funzionamento...

**Comment by lepool** [comment]
ora il problema è il seguente


![grafik](https://user-images.githubusercontent.com/32035706/34681883-8251dbd4-f49d-11e7-8d81-ddacfcc666bb.png)

**Comment by Dasc3er** [comment]
@lepool Sicuro di aver aggiornato correttamente?
Perché nella versione master la riga che segnala l'errore (_310_) è la _296_...

**Comment by lepool** [comment]
Era un problema con il merge della repo, sorry ,

**Comment by lepool** [comment]
Allora, secondo il i seguenti formati : 
 ### -> ok
2018### -> ok
2018/### -> errore
2018.### -> errore
2018a###-> ok

Sembra che in caso di alcuni caratteri parte sempre dalla prima numerazione e genera un codice già esistente. gen_next_code fallisce.

**Comment by fpsoftware** [comment]
confermo che il problema è l'ordinamento tramite "CAST(codice AS UNSIGNED)" che purtroppo interpreta il campo codice come numero, ma se viene messo un carattere non numerico l'ordinamento non funziona.
@Dasc3er  abbiamo già trattato questa problematica con lo sviluppo dei sezionali, sistemiamo noi questo problema dall'ufficio.
Grazie ad entrambi.

**Comment by loviuz** [comment]
@fpsoftware, sicuro che abbiamo già risolto?

**Comment by fpsoftware** [comment]
È lo stesso problema che ho avuto sulla numerazione delle fatture quando ho sviluppato i sezionali, basta controllare la maschera del numero e modificare la query in caso di lettere...

**Comment by loviuz** [comment]
ho appena provato con questo formato:
2018/###

ma il codice successivo lo crea correttamente... :-\
qualcun'altro può confermare? @lepool ?
ho l'ultimissimo commit.
se risolviamo questo, domani (venerdì) si fa la release :-D

**Comment by lepool** [comment]
Sta sera provo e vi faccio sapere.

**Comment by lepool** [comment]
Ho provato con le stringe 2018/####, numerato 2 interventi, 2018.####,  2018/##### , 2018/#####abc .

Non ho riscontrato errori. :+1:

**Comment by loviuz** [comment]
evviva! :-D
