### ISSUE TITLE
BUG: Indirizzo sede legale in fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#950]
## Comportamento attuale

Se inserisco una destinazione diversa in fattura, nell'indirizzo dell'intestatario viene riportato quello della destinazione diversa.
Mi aspetterei invece di avere nell'indirizzo dell'intestatario la sede legale e nella destinazione diversa l'indirizzo della sede di destinazione, come era nelle versioni precedenti.

OSM 2.4.21

**Comment by Pek5892** [comment]
Risolto con commit 2.4.24
