### ISSUE TITLE
DISCUSSIONE: Sconto nei preventivi

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#951]
## Comportamento richiesto

Quando stampo un preventivo in cui ho applicato uno sconto, a fondo pagina mi viene fuori (per esempio):
Imponibile € 3712,00
Sconto € 2654,08
Totale imponibile € 1057,92
Totale IVA € 371,20
Totale documento € 1429,12

Il calcolo è esatto, ma il problema sta nella comprensibilità del calcolo che nasce da uno sconto in fattura per ecobonus, e che parte da un importo imponibile di 3712 + iva 10% 371,20 = 4083,20 
Poi viene applicato lo sconto del 65% (sul totale IVA inclusa) , pari a € 2654,09 (esente IVA), con totale netto di € 1429,12

Si deve considerare che in molti casi gli sconti vengono calcolati sul totale IVA inclusa. 

## Possibile soluzione

Aggiungere l'importo da scontare IVA inclusa, nel seguente modo:

TOTALE imponibile: € 3712,00
Totale IVA: € 371,20
IMPORTO TOTALE: € 4083,20
Sconto applicato: € 2654,08
NETTO A PAGARE: € 1429,12 

OSM 2.4.21

**Comment by Dasc3er** [comment]
Dall'ultima versione rilasciata 2.4.22, esiste uno nuovo sconto denominato Sconto finale che presenta questo comportamento. Questo sconto è limitato alle Fatture e non sarà aggiunto in altri documenti: se hai bisogno di uno sconto del tipo indicato, utilizza le fatture.

In ogni caso, mi sembra che l'unico problema sia dovuto a una semplice logica di visualizzazione della tabella delle righe, che puoi sempre modificare come necessiti.

**Comment by idraulicadueci** [comment]
Ok ti ringrazio, proverò a fare la modifica.
