### ISSUE TITLE
Righe mischiate durante la modifica di un preventivo duplicato

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#952]
## Comportamento attuale
L'ordine delle righe viene mischiato durante la modifca di una riga di un preventivo duplicato. L'ordine delle righe del preventivo originale viene anch'esso mischiato.

## Passi per riprodurre il comportamento

1. Creare un preventivo con un pò di righe
2. Duplicare il preventivo
3. Modificare per un pò di tempo il preventivo (il problema si è verificato dopo 15 minuti circa)
 
## Log dal database (tabella `zz_operations`)
233 è il preventivo duplicato

| id_module | id_plugin | id_email | id_record | id_utente | op | options | created_at | updated_at | 
| ---: | ---: | ---: | ---: | ---: | --- | --- | --- | --- | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-19 14:43:17 | 2021-03-19 14:43:17 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-19 14:43:47 | 2021-03-19 14:43:47 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-19 14:43:53 | 2021-03-19 14:43:53 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-19 14:46:05 | 2021-03-19 14:46:05 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-19 14:46:36 | 2021-03-19 14:46:36 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-19 14:47:21 | 2021-03-19 14:47:21 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-19 14:47:28 | 2021-03-19 14:47:28 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-19 14:47:57 | 2021-03-19 14:47:57 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-19 14:48:06 | 2021-03-19 14:48:06 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-19 14:48:17 | 2021-03-19 14:48:17 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 18:45:14 | 2021-03-21 18:45:14 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 18:45:53 | 2021-03-21 18:45:53 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 18:46:46 | 2021-03-21 18:46:46 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-21 18:47:32 | 2021-03-21 18:47:32 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 18:47:54 | 2021-03-21 18:47:54 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 18:48:19 | 2021-03-21 18:48:19 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 18:48:49 | 2021-03-21 18:48:49 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 18:49:24 | 2021-03-21 18:49:24 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:07:37 | 2021-03-21 19:07:37 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:09:29 | 2021-03-21 19:09:29 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:10:07 | 2021-03-21 19:10:07 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:10:35 | 2021-03-21 19:10:35 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:12:37 | 2021-03-21 19:12:37 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:13:06 | 2021-03-21 19:13:06 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:13:18 | 2021-03-21 19:13:18 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:13:28 | 2021-03-21 19:13:28 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:14:12 | 2021-03-21 19:14:12 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:14:49 | 2021-03-21 19:14:49 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:15:07 | 2021-03-21 19:15:07 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:20:44 | 2021-03-21 19:20:44 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:20:50 | 2021-03-21 19:20:50 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:21:10 | 2021-03-21 19:21:10 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:21:54 | 2021-03-21 19:21:54 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:22:08 | 2021-03-21 19:22:08 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:22:25 | 2021-03-21 19:22:25 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:24:51 | 2021-03-21 19:24:51 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:25:04 | 2021-03-21 19:25:04 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:25:10 | 2021-03-21 19:25:10 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:25:15 | 2021-03-21 19:25:15 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:25:37 | 2021-03-21 19:25:37 | 
| 13 | \N | \N | 233 | 1 | delete_riga | \N | 2021-03-21 19:25:47 | 2021-03-21 19:25:47 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:26:16 | 2021-03-21 19:26:16 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:30:05 | 2021-03-21 19:30:05 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:30:13 | 2021-03-21 19:30:13 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:30:35 | 2021-03-21 19:30:35 | 
| 13 | \N | \N | 233 | 1 | delete_riga | \N | 2021-03-21 19:30:54 | 2021-03-21 19:30:54 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:31:10 | 2021-03-21 19:31:10 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:32:05 | 2021-03-21 19:32:05 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:32:16 | 2021-03-21 19:32:16 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:32:33 | 2021-03-21 19:32:33 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:36:25 | 2021-03-21 19:36:25 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:36:42 | 2021-03-21 19:36:42 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:36:49 | 2021-03-21 19:36:49 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:36:54 | 2021-03-21 19:36:54 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-21 19:37:03 | 2021-03-21 19:37:03 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:37:07 | 2021-03-21 19:37:07 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:37:14 | 2021-03-21 19:37:14 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-21 19:37:47 | 2021-03-21 19:37:47 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:37:50 | 2021-03-21 19:37:50 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:38:02 | 2021-03-21 19:38:02 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:38:15 | 2021-03-21 19:38:15 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-21 19:38:40 | 2021-03-21 19:38:40 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:38:59 | 2021-03-21 19:38:59 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:39:06 | 2021-03-21 19:39:06 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:39:20 | 2021-03-21 19:39:20 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:39:24 | 2021-03-21 19:39:24 | 
| 13 | \N | \N | 233 | 1 | delete_riga | \N | 2021-03-21 19:40:54 | 2021-03-21 19:40:54 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:41:21 | 2021-03-21 19:41:21 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:41:26 | 2021-03-21 19:41:26 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-21 19:42:28 | 2021-03-21 19:42:28 | 
| 13 | \N | \N | 233 | 1 | update_position | \N | 2021-03-21 19:42:44 | 2021-03-21 19:42:44 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:42:49 | 2021-03-21 19:42:49 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:48:13 | 2021-03-21 19:48:13 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:48:17 | 2021-03-21 19:48:17 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:48:31 | 2021-03-21 19:48:31 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:48:36 | 2021-03-21 19:48:36 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:48:47 | 2021-03-21 19:48:47 | 
| 13 | \N | \N | 233 | 1 | manage_riga | \N | 2021-03-21 19:48:49 | 2021-03-21 19:48:49 | 
| 13 | \N | \N | 233 | 1 | update | \N | 2021-03-21 19:49:04 | 2021-03-21 19:49:04 | 
| 13 | \N | \N | 233 | 1 | manage_descrizione | \N | 2021-03-21 19:49:06 | 2021-03-21 19:49:06 | 

## Contesto
* Modulo: Preventivi
* Versione del progetto: 2.4.22
* Versione PHP: 7.4
* Tipo di server: OpenLiteSpeed

**Comment by maicol07** [comment]
Novità su questo bug?

**Comment by maicol07** [comment]
@MatteoPistorello @Dasc3er novità?

**Comment by loviuz** [comment]
@MatteoPistorello

**Comment by Dasc3er** [comment]
@maicol07 Da ultime verifica sulla versione in sviluppo ho verificato che le righe di documenti distinti non sono collegate, quindi l'aggiornamento dell'ordine in un documento non influenza altre righe.
Potrebbe essere che @MatteoPistorello abbia risolto il problema senza segnalarlo nella issue, quindi al momento considererei questa parte come completa.
