### ISSUE TITLE
comportamento anomalo in modifica DDT in uscita con "tipo spedizione" personalizzata

### ISSUE THREAD

**Issue by fargianni** [devcode-it/openstamanager#953]
Il comportamento indicato si verifica se vengono create nuove modalità di spedizione oltre a quelle presenti e poi usate nelle DDT in uscita

## Comportamento attuale

Se si crea una DDT in uscita con "Tipo di spedizione" una personalizzata creata nelle relativa tabella e poi successivamente si va in modifica allora richiede obbligatoriamente il campo Vettore (ma nel programma gli unici tipi di spedizione che prevedono il vettore sono "espressa" e "vettore"). Il problema non si verifica utilizzanod la modalità predefinita "Ritiro in magazzino"

![immagine](https://user-images.githubusercontent.com/77353938/112818040-62584680-9083-11eb-9b7c-d3f08d565207.png)

## Comportamento richiesto

Il campo vettore non deve essere obbligatorio in modifica della DDT con "tipo di spedizione" uno personalizzato

## Passi per riprodurre il comportamento

1. Creare nella tabella "tipi di spedizione" un nuovo tipo per es. "Consegna a domicilio"
2. creare una DDT in uscita e salvarla in bozza (senza mettere vettore e comunque in questa fase il campo vettore è disabilitato)
3. entrare in modifica della DDT
4. Il campo vettore è diventato obbligatorio

## Possibile soluzione

Da un'analisi del file edit.php del modulo DDT credo che il bug sia nella riga 187 che è :

```php
{[ "type": "select", "label": "<?php echo tr('Vettore'); ?>", "name": "idvettore", "ajax-source": "vettori", "value": "$idvettore$", "disabled": <?php echo intval($record['idspedizione'] == 3); ?>, "required": <?php echo (!empty($record['idspedizione'])) ? intval($record['idspedizione'] != 3) : 0; ?>, "icon-after": "add|<?php echo Modules::get('Anagrafiche')['id']; ?>|tipoanagrafica=Vettore&readonly_tipo=1|btn_idvettore|<?php echo (($record['idspedizione'] != 3 and intval(!$record['flag_completato']))) ? '' : 'disabled'; ?>" ]}
```
e dovrebbe essere invece;
```php
{[ "type": "select", "label": "<?php echo tr('Vettore'); ?>", "name": "idvettore", "ajax-source": "vettori", "value": "$idvettore$", "disabled": <?php echo intval($record['idspedizione'] > 2); ?>, "required": <?php echo (!empty($record['idspedizione'])) ? intval($record['idspedizione'] <= 2) : 0; ?>, "icon-after": "add|<?php echo Modules::get('Anagrafiche')['id']; ?>|tipoanagrafica=Vettore&readonly_tipo=1|btn_idvettore|<?php echo (($record['idspedizione'] <=2 and intval(!$record['flag_completato']))) ? '' : 'disabled'; ?>" ]}
```
## Contesto

* Modulo: DDT
* Versione del progetto: 2.4.22
Versione PHP: 7.3.19
Tipo di server: xampp 7.3.19 (apache 2.4.43 php 7.3.19 MariaDB 10.4.13 Windows 10 pro

**Comment by Dasc3er** [comment]
Ciao, sembra che la correzione sia già stata effettuata nella versione in sviluppo.
Puoi trovare il codice qui: https://github.com/devcode-it/openstamanager/blob/4c41d3ec12187731388b6a7caf5179f3e39109bc/modules/ddt/edit.php#L191

Ecco il commit: https://github.com/devcode-it/openstamanager/commit/c7899c03216510a198286690efc3a2141db8e2ac

**Comment by fargianni** [comment]
Ottimo grazie.
Il commit introduce la gestione del flag "spedizione con vettore"  per la tabella tipo spedizione che rende ancora più flessibile la gestione dei tipi personalizzati.
