### ISSUE TITLE
Problema con opzioni stampa preventivo 

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#954]
## Comportamento attuale

Se effettuo la stampa "Preventivo senza totali" nel preventivo viene visualizzato comunque il totale.
Ho verificato nel modulo stampe, e nelle opzioni è inserita la configurazione JSON `hide_total:true`

OSM 2.4.21

**Comment by Dasc3er** [comment]
@idraulicadueci Sembra infatti che la configurazione sia errata. Ecco le informazioni corrette:
![image](https://user-images.githubusercontent.com/15911489/114354402-7bc2bd80-9b6e-11eb-8024-7a52b2b3aadf.png)

**Comment by idraulicadueci** [comment]
In realtà il problema ce l'ho con la stampa senza totale. Quella senza prezzi funziona.
