### ISSUE TITLE
Maggiorazione 1% stampe liquidazione iva

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#955]
Non ho capito dove inserire il parametro per indicare quando si stampa la liquidazione Iva di calcolare l'1% per liquidazioni trimestrali

* Versione del progetto: 2.4.22

**Comment by loviuz** [comment]
Al momento non è presente, le stampe di liquidazione iva sono ancora in beta.

**Comment by leo-spa** [comment]
grazie per l'interessamento, sarebbe molto utile per chi gestisce l'iva trimestrale poter accedere a questo automatismo invece di calcolare l'1% manuale sul totale iva da pagare ed aggiungere una scrittura a parte per far quadrare i conti quando si effettua la liquidazione.
