### ISSUE TITLE
Campo "Richiesta" non salvato durante apertura Attività

### ISSUE THREAD

**Issue by moodino** [devcode-it/openstamanager#956]
Buongiorno,
sembra che andando a creare una nuova attività, inserendo una descrizione nel campo "Richiesta", il campo non venga salvato. Bisogna scriverlo due volte.

* Modulo: Attività
* Versione del progetto: 2.4.22

**Comment by loviuz** [comment]
ciao @moodino, è stato risolto nella versione in sviluppo. puoi aggiornare il modulo interventi se vuoi anticipare la fix
