### ISSUE TITLE
Righe in fattura con ritorni a capo vengono emesse tutte su una riga in FE filtrando i CRLF e diventa poco leggibile

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#959]
## Comportamento richiesto

Sarebbe utile nel caso di descrizioni multilinea delle fatture, invece di filtrarli semplicemente, di convertire i ritorni a capo in simboli - per facilitare la lettura in formato XML con foglio di stile. Eventualmente tale operatività, essendo invasiva potrebbe essere impostata come opzione e lasciata disattivata per default.

Non conosco soluzioni ancora migliori che siano aderenti al formato dettato dalle specifiche della fattura elettronica, ma se c'è una soluzione migliore ben venga!

Cioè, l'idea è che desiderabilmente la riga articolo nella maschera:

```
Attività: [omissis]
Date:
12 13 aprile 2021
```

diventerebbe
```
<Descrizione>Attivit  : [omissis] - Date: - 12 13 aprile 2021</Descrizione>
```

(il filtro sulle accentate è cosa buona e giusta, anche se anche li avrei fatto un tentativo di premappaggio à->a prima di filtrarle e basta)

## Comportamento attuale

Le righe multiple in descrizione in fattura vengono appiattite in una concatenandole e rendendole difficilmente leggibili.

Ovvero, in relazione alla riga in precedenza, il risultato è:
```
<Descrizione>Attivit  : [omissis]  Date:  12 13 aprile 2021</Descrizione>
```

## Possibile soluzione

Sto indagando bene per proporre una soluzione efficace.

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: fattura elettronica
* Versione del progetto: 2.4.21
* Versione PHP: 7.4
* Tipo di server: Aruba (apache)

**Comment by Dasc3er** [comment]
Grazie per il suggerimento!
Non so se l'applicazione sia di interesse comune per più utenti, ma puoi certamente modificare e correggere il comportamento tramite la classe Validator.php e in particolare il seguente codice:
https://github.com/devcode-it/openstamanager/blob/08c3e46cadc10670af942e7cb07b59a4857cfcca/plugins/exportFE/src/Validator.php#L633

Se desideri, puoi anche effettuare una Pull Request qui su GitHub per chiedere l'inclusione della modifica nel gestionale.

**Comment by marcus905** [comment]
Provo a elaborare un po' e preparo una pull request. Grazie!
