### ISSUE TITLE
stampa intervento non mi funziona più

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#96]
Ecco il seguente errore:

![grafik](https://user-images.githubusercontent.com/32035706/34521307-61191e0a-f08d-11e7-903b-03a52d01c5ce.png)

dimenticavo : versione 2.3.1 [commit 7ee5382](https://github.com/devcode-it/openstamanager/commit/7ee53829eb4815201a9301587013b75987a3ad45)

**Comment by lepool** [comment]
Forse un errore mio. Verifico stasera.

**Comment by Dasc3er** [comment]
@lepool L'errore in questione è generato da uno degli ultimi commit.
Per risolverlo devi eseguire nuovamente il comando **yarn run develop-OSM**, perchè è necessario aggiornare i componenti esterni attraverso Composer.

**Comment by lepool** [comment]
Confermo, ora ho visto che nel commit erano inclusi moduli js. Chiedo scusa.
