### ISSUE TITLE
Impossibilità di utilizzo dello sconto/maggiorazione generale in fattura (2.1.1.8)

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#960]
## Comportamento richiesto

Risulta necessario avere un campo sconto generale attivabile/disattivabile che consenta di inserire ciò che ora è possibile fare solo negli attributi avanzati fattura, di modo da mantenere la validità formale della stessa.

## Comportamento attuale

Non è presente nella maschera fatture la possibilità di calcolare lo sconto generale in fattura. Aggiungendolo dalla maschera attributi avanzati, nell'XML l'importo totale documento non viene decurtato dell'ammontare dello sconto. Tale operazione è necessaria per quanto riguarda l'emissione di fatture con detrazione ECO-BONUS al 65% (e altre percentuali).

## Possibile soluzione

Sto tentando di fare tali modifiche nel gestionale in sviluppo, proverò a inoltrare un pull request ad esse relativo non appena riuscirò in tal modo. Se però avete già una soluzione che ben venga!

## Passi per riprodurre il comportamento

1. Creazione fattura
2. Tentativo di inserire uno sconto generale impossibile

## Contesto

* Modulo: fattura/fattura elettronica
* Versione del progetto: 2.4.21
* Versione PHP: 7.4
* Tipo di server: Aruba (apache)

**Comment by loviuz** [comment]
Ciao @marcus905 , ti anticipo che questo campo è stato introdotto nella versione 2.4.22, e nella 2.4.23 quasi pronta per il rilascio è stato aggiunto anche negli altri documenti per essere facilmente preventivato e trasportato nella fattura finale.

Prova ad aggiornare alla 2.4.22 e fammi sapere se così è ciò che intendevi

**Comment by marcus905** [comment]
Ah! Mi sono perso una versione allora!
Controllo ora, ecco perché non mi trovavo con la versione in sviluppo in questo ambito ahaha

Scrivo se è tutto ok a breve, grazie mille ancora!

**Comment by marcus905** [comment]
Ho verificato, ma un bug persiste.

Ora il file XML è generato correttamente, ma la stampa PDF risulta sbagliata perche IVA lo sconto finale apparentemente.

**Comment by marcus905** [comment]
> Ho verificato, ma un bug persiste.
> 
> Ora il file XML è generato correttamente, ma la stampa PDF risulta sbagliata perche IVA lo sconto finale apparentemente.
> 
> EDIT: mi spiego meglio
> 
> La fattura in XML e la fattura a schermo risultano corrette, ad una prima occhiata, ma la fattura generata in PDF riporta un totale a pagare errato, come se applicasse l'IVA sullo sconto e poi la sottraesse al totale, mentre tale cosa non risulta corretta.

Non riesco più a riprodurre il bug in oggetto, ora funziona tutto perfettamente -- probabilmente era una stranezza momentanea del sistema. Chiudo, grazie mille!
