### ISSUE TITLE
Problemi con update a versione 2.4.21

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#961]
## Comportamento richiesto

Eseguire update a versione 2.4.21 dalla versione 2.4.17

## Comportamento attuale

Attualmente mi compare il seguente errore

**Si è verificato un'errore [uid: e74bb16]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).

Uncaught Exception Error: "Call to undefined function string_starts_with()" at /var/www/html/osm/include/init/requirements.php line 113** 

## Contesto

* Versione del progetto: 2.4.17
* Versione PHP: PHP Version 7.3.27-1~deb10u1
* Tipo di server: Apache/2.4.38 (Debian)

**Comment by lepool** [comment]
Ho anche provato la versione 2.4.22 con lo stesso problema. La funzione viene inizializzata in lib/util.php che nel progetto non viene incluso. Ho aggiornato dal modulo aggiornamento.

**Comment by Dasc3er** [comment]
@lepool Il file che hai indicato viene incluso in automatico, l'unico motivo per cui ci possa essere un problema è se il file non viene sostituito in modo corretto a causa di permessi dei file male impostati.
Puoi verificare che il file sia stato sostituito correttamente?

**Comment by lepool** [comment]
I permessi mi sembrano corretti. Controllando da una shell vedo :

-rw-r--r--  1 www-data www-data  5205 May  6 06:05 common.php
-rw-r--r--  1 www-data www-data 12846 May  6 06:05 deprecated.php
-rw-r--r--  1 www-data www-data 11942 May  6 06:05 functions.php
-rw-r--r--  1 www-data www-data  6161 May  6 06:05 helpers.php
-rw-r--r--  1 www-data www-data 17394 May  6 06:05 util.php

Infatti se aggiorno la pagina l'update me lo esegue correttamente. Poi controllo attraverso il modulo aggiornamenti l'integrità dei file della versione e mi dice "Nessun file con problemi di integrità." 

Potrebbe essere che PHP usando una cache crei un problema?
