### ISSUE TITLE
BUG: Impossibile eliminare DDT stato bozza

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#962]
## Comportamento attuale
Il pulsante elimina è scomparso e non è possibile eliminare un DDT in stato bozza
  	
OSM 2.4.23

**Comment by Dasc3er** [comment]
@idraulicadueci Il pulsante di eliminazione è presente e funzionate.
Hai delle modifiche al codice?

**Comment by idraulicadueci** [comment]
Proverò a fare un'installazione pulita e vedere di risolvere i bug che sto riscontrando. grazie

**Comment by idraulicadueci** [comment]
@Dasc3er credo ch il problema sia causato dalla riga 527 in /modules/ddt/edit.php

`// Eliminazione ddt solo se ho accesso alla sede aziendale`
`if (in_array($record[$field_name], $user->sedi)) `

nei ddt infatti metto sempre la sede di destinazione che è diversa da quella legale e questo mi impedisce l'eliminazione (pulsante ELIMINA non visibile).
Rimettendo la sede legale come destinazione, il pulsante ELIMINA ricompare.
A mio avviso questo comportamento non è corretto. Forse sarebbe opportuno trovare un altro parametro che impedisca l'eliminazione, per esempio permetterla solo agli amministratori e a chi a creato il documento. E magari solo nello stato di bozza (adesso è eliminabile anche se evaso).
Che ne dici?

**Comment by Dasc3er** [comment]
@loviuz @MatteoPistorello  Vedo la modifica @https://github.com/devcode-it/openstamanager/commit/9d1d40e38529d7f46f7e6159b6c640ec0db7562c#diff-ac492786b036015990fd67f7111b29fd978dfbf9befd4635e45c23b5864f668c, quale era la motivazione dietro questa nuova limitazione?
