### ISSUE TITLE
Errori in salvataggio attività

### ISSUE THREAD

**Issue by reteinformatica** [devcode-it/openstamanager#963]
## Comportamento attuale
Quando salvo un'attività (rapporto d'intervento) ricevo due box rossi con scritto:

Si è verificato un'errore [uid: e84ac24]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Uncaught Exception Error: "Call to a member function isEmpty() on null" at /data/vhosts/reteinformatica.biz/domterz/staman/plugins/notes.php line 22

Si è verificato un'errore [uid: e84ac24]. Se il problema persiste siete pregati di chiedere assistenza tramite il forum apposito (https://forum.openstamanager.com/).
Call to a member function isEmpty() on null

Poi all'atto pratico l'attività viene salvata.

## Passi per riprodurre il comportamento

Creo o modifico un'attività, clicco salva.

* Modulo:
* Versione del progetto: 2.4.23 (R1de51267)
* Versione PHP: 8.05
* Tipo di server: Linux CloudOS

**Comment by Dasc3er** [comment]
Ciao @reteinformatica ,
il problema è probabilmente relativo a quello da te segnalato in #965.
Potrebbe essere che alcuni file non sono stati aggiornati correttamente nell'aggiornamento.
