### ISSUE TITLE
problema durante aggiornamento a versione 2.4.23

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#964]
Durante l'aggiornamento alla versione 2.4.23 mi è comparso il seguente errore nel logfile. 

[2021-05-22 15:14:45] Logs.EMERGENCY: Invalid check_digits for format IT(?<check_digits>[A-Z0-9]{2})(?<national_check_digits>[A-Z0-9]{1})(?<bank_code>[A-Z0-9]{5})(?<branch_code>[A-Z0-9]{5})(?<account_number>[A-Z0-9]{12}) []
{"url":"/osm.test/index.php?action=do_update&firstuse=false","ip":"xxx.xxx.xxx.xxx","http_method":"GET","server":"xxx.xxx.com","referrer":"https://xxx.xxx.com/osm.test/index.php?force","uid":"459c34f"}

* Modulo: aggiornamento
* Versione del progetto: 2.4.23
* Versione PHP: 7.3.27-1~deb10u1
* Tipo di server: apache2 24.38 -  mysql 8.0.25

**Comment by lepool** [comment]
Ho capito che ha a che fare con il formato di un Iban. Che formato viene richiesto dal gestionale della versione 2.4.23?

**Comment by loviuz** [comment]
Probabilmente hai a database un iban non corretto, ci siamo accorti infatti tardi che l'errore di un iban blocca l'aggiornamento. Puoi provare ad aggiornare il file update/2_4_23.php presente in questo momento nel repository? Aggiornando questo file viene gestito l'errore per cui dovresti riuscire a completare l'aggiornamento senza problemi.

**Comment by lucasalva87** [comment]
Confermo che il problema è già stato trattato e risolto sul nostro forum: https://forum.openstamanager.com/viewtopic.php?f=2&t=95541
