### ISSUE TITLE
Impossibile aggiungere righe nelle attività

### ISSUE THREAD

**Issue by reteinformatica** [devcode-it/openstamanager#965]
## Comportamento richiesto

Apertura finestra per aggiungere righe

## Comportamento attuale

Mi sono accorto solo ora che nelle attività non è possibile aggiungere nessuna opzione della sezione "Righe": cerca di aprirsi la finestra ma non compaiono e campi e gira a vuoto la scritta "Attendere"
https://forum.openstamanager.com/viewtopic.php?f=10&t=95540&p=104894#p104894

## Passi per riprodurre il comportamento

Clicco su una qualsiasi delle opzioni della sezione "Righe" nelle attività

## Contesto

Linux CloudOS

* Modulo:
* Versione del progetto:
* Versione PHP: sia 8.05 che 7.4.18
* Tipo di server: Linux CloudOS

**Comment by lucasalva87** [comment]
Purtroppo non riesco a riprodurre il problema. (come potete vedere dalla nostra demo pubblica non c'è traccia di queste anomalie: https://demo.osmcloud.it/2423/)
Potreste verificare che tutti i file della release siano stati caricati correttamente?
