### ISSUE TITLE
BUG: Problema con l'ordinamento delle righe in fattura

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#966]
## Comportamento richiesto

Mantenere l'ordine dopo riordinamento.

## Comportamento attuale

Creo una fattura da un preventivo. Nella fattura modifico l'ordine delle righe e salvo. Se elimino una riga, al momento del salvataggio mi viene riproposto l'ordine originale (nel mio caso quello che avevo nel preventivo)

## Passi per riprodurre il comportamento

Creare un  preventivo e renderlo fatturabile. Creare la fattura dal preventivo.
Modificare l'ordine delle righe e salvare.
Cancellare una riga.

OSM 2.4.23

**Comment by Dasc3er** [comment]
@idraulicadueci Seguendo la procedura indicata, nella versione in sviluppo non sono riuscito a replicare il problema.
Potrebbe essere stato risolto, anche se non ho visto particolari modifiche nel codice responsabile della gestione righe.

**Comment by idraulicadueci** [comment]
ok. attendo la nuova release, probabilmente è come dice tu.
