### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [devcode-it/openstamanager#967]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by Dasc3er** [comment]
Hi, 
We can certainly add the information for security problems as stated by GitHub standard 😄 
Meanwhile, you can send the details for security issues at info@openstamanager.com.

Thank you in advance!

**Comment by zidingz** [comment]
Thank you! We'll get that email to you shortly.

Here's a PR for the security.md to save you some valuable time! https://github.com/devcode-it/openstamanager/pull/968
