### ISSUE TITLE
BUG: Pagamento MP05 30g d.f.f.m.

### ISSUE THREAD

**Issue by stefanostc** [devcode-it/openstamanager#969]
## Comportamento richiesto

Selezionando il pagamento "Pagamento MP05 30g d.f.f.m." mi aspetto che la data di scadenza sia la fine del mese successivo a quello in cui emetto la fattura. Es: emetto fattura il 16/7 -> Termine pagametno 31/8

**Pagamento MP05 30g d.f.f.m. è impostato cosi:**
Percentuale 100%
Scadenza: data fattura fine mese
Distanza giorni 30

Versione: 2.4.23 (R1de51267)

## Comportamento attuale

Il termine di pagametno viene impostato nello stesso mese di emisisone della fattura (nell'esempio 31/7)

**Comment by Dasc3er** [comment]
Ciao @stefanostc ,
il problema non si verifica. Credo che tu abbia impostato erroneamente il pagamento che hai indicato, poichè non è tra a quelli predefiniti del gestionale.

Segue l'esempio di "Bonifico 30g d.f.f.m", per cui ho verificato il funzionamento corretto,
![image](https://user-images.githubusercontent.com/15911489/125908859-ad22c4d1-4a55-48d4-b0e1-4e0a268ff39f.png)

**Comment by stefanostc** [comment]
Ciao

questo è il metodo di pagamento

e da un po di tempo si presenta il problema. Secondo me il problema si è 
iniziato a manifestare dopo che una volta ho modificato le rate di 
questo pagamento.

Ma pur avendo ripristinato tutto continua a non funzionare. Posso 
controllare a db che non ci sia qualcosa di incoerente ?

Grazie

Stefano

Il 16/07/2021 09:25, Thomas Zilio ha scritto:

**Comment by Dasc3er** [comment]
Se desideri verificare manualmente nel database, i dati sono i seguenti:
![image](https://user-images.githubusercontent.com/15911489/125913087-29217639-0427-44d1-b8f3-862af8b4985a.png)

La schermata del modulo Pagamenti però riflette esattamente i contenuti del database, quindi dubito che il problema sia questo.
Al tempo stesso, testando in locale il problema non si verifica.

**Comment by stefanostc** [comment]
Ho provato ad eliminare la rata e ricrearla ma mi ha eliminato il metodo di pagamento presente completamente

Ho ricreato un nuovo con  la stessa denominazione e parametri come da tua foto.

Ora però in tutte le fatture emesse è scomparso il metodo di pagamento e risulta impossibile salvare o modificarle (es riportandole in stato bozza) perchè riporta che il metodo di pagametno è obbligatorio.
Ovviamente il nuovo metodo di pagametno ha un ID diverso dal precedente.
Posso modificare da db l'id del nuovo metodo di pagamento con il vecchio id precedente  (82)?
Ci sono relazioni da altre tabelle che usano l'id della riga ? (Non ho creato ancora offerte, fatture etc etc... con il nuovo.) El in che tabella sono salvate le impostazioni delle rate ?

Grazie

**Comment by marcus905** [comment]
In realta ho avuto anche io questo problema sui pagamenti differiti monorata, ma non l'ho segnalato pensando avessi fatto io qualche modifica errata.

**Comment by Dasc3er** [comment]
> Posso modificare da db l'id del nuovo metodo di pagamento con il vecchio id precedente (82)?
@stefanostc Visto che hai modificato direttamente dal database, puoi in questo solo caso modificare l'ID manualmente a 82.

@marcus905 @stefanostc Ci servirebbero maggiori informazioni sul problema, se si verifica nelle vostre installazioni. Che versioni di PHP, e MySQL state usando? E OpenSTAManager (2.4.23 per @stefanostc )?
Avete personalizzazioni o modifiche al codice originale?
In che situazioni specifiche si verifica il bug? Avete modo di fare screenshot per verificare le date erroneamente calcolate per i specifici pagamenti? Il problema si verifica con tutti i pagamenti simili o solo con alcuni?

**Comment by stefanostc** [comment]
Ciao,

- Ho modificato l'id a 82 e tutto si è riallineato, idem lo storico 
delle fatture/preventivi emessi.

- Versioni:

PHP 7.2.24-0ubuntu0.18.04.8
mysql  Ver 15.1 Distrib 10.1.48-MariaDB
No personalizzazioni al codice (eccetto un aggiunta sul footer dei 
preventivi...)

Il problema si presenta solo con questo *Bonifico 30g dffm* mentre 
*Bonifico 30g *df funziona correttamente

Stefano

Il 16/07/2021 11:50, Thomas Zilio ha scritto:

**Comment by marcus905** [comment]
> > Posso modificare da db l'id del nuovo metodo di pagamento con il vecchio id precedente (82)?
> 
> @stefanostc Visto che hai modificato direttamente dal database, puoi in questo solo caso modificare l'ID manualmente a 82.
> 
> @marcus905 @stefanostc Ci servirebbero maggiori informazioni sul problema, se si verifica nelle vostre installazioni. Che versioni di PHP, e MySQL state usando? E OpenSTAManager (2.4.23 per @stefanostc )?

Sto lavorando su hosting aruba, PHP 7.2, Mysql 5.7.32-35-log - Percona Server (GPL), Release 35, Revision 5688520, OSM 2.4.23

> Avete personalizzazioni o modifiche al codice originale?

No, tutto standard.

> In che situazioni specifiche si verifica il bug? Avete modo di fare screenshot per verificare le date erroneamente calcolate per i specifici pagamenti? Il problema si verifica con tutti i pagamenti simili o solo con alcuni?

La prossima fattura che emetto faccio degli screen. Ho provato a guardare il codice anche in Fatture/src e nei pagamenti ma sembra giusto ad occhio.

**Comment by stefanostc** [comment]
Dopo aver modificato la riga sul db (rimesso id 82) avendo ricreato la modalita di pagamento come da indicazioni ed aver aggiornato alla verisone 2.4.24 tutto funziona. Ho emesso fattura oggi a 30 g d.f.f.m  e correttamente la scadenza è il 30/09/2021

**Comment by loviuz** [comment]
Credo che questo bug sia della versione 2.4.23, riscontrato e risolto da @MatteoPistorello. @marcus905 puoi provare ad aggiornare alla 2.4.24 e confermare che è risolto?

**Comment by stefanostc** [comment]
aggiornato alla 2.4.24 tutto funziona
