### ISSUE TITLE
Aggiornamento non funzionante da "OSM V2.0 migrazione"

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#97]
Forse c'è un altro passaggio in mezzo? O non ci sono ancora procedure adatte? 
L'errore in error.log in seguito ad aggiornamento da 2.0 migrazione a versione 2.3.1/master

[2018-01-04 08:24:47] Logs.ERROR: Uncaught Exception PDOException: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list' - SELECT id AS id_utente, password, enabled FROM zz_users WHERE username = 'admin' LIMIT 1" at /var/www/assistenza/src/Database.php line 761
{"url":"/assistenza/?op=login","ip":"10.0.0.93","http_method":"POST","server":"10.0.0.130","referrer":"http://10.0.0.130/assistenza/","uid":"75ac806"} 

Al momento la tabella si chiama ancora zz_utenti .
Se la richiesta non è pertinente, chiudete pure la richiesta.

Lepool

**Comment by lepool** [comment]
Per il nuovo OSM 2.3 i database MYSQL possono chiamarsi p.e osm.migrazione ?

**Comment by lepool** [comment]
Sembra proprio che nella nuova versione di OSM non è accettato la sopra descritta nomenclatura.

**Comment by Dasc3er** [comment]
Ciao @lepool,
potresti indicare con precisione la procedura che hai utilizzato per eseguire l'aggiornamento?
Dai log che hai postato sembra che l'aggiornamento non sia stato eseguito a livello di database, e oltretutto non ci sono tabelle con nome **migration** all'interno del gestionale.

Le procedure dovrebbero essere già adeguate e funzionanti, con test di compatibilità eseguiti a partire dalla versione 2.3beta2...

Inoltre potresti utilizzare esclusivamente la versione master? Per la branch 2.3.1 non sono stati effettuati test né tentativi di installazione, perché per il momento è alle prime fasi di definizione...

**Comment by Dasc3er** [comment]
Mi correggo: effettivamente l'errore segnalato è causato dalla riga 95 del file **update/api.php**.
Potresti provare a correggerla nel seguente modo?
```
$query = 'SHOW COLUMNS FROM `'.$table.'` IN `'.$database->getDatabaseName()."` WHERE Field='|field|'";
```

**Comment by lepool** [comment]
Inoltre in 2_3.sql c'è la problematica in caso di presenza nella tabella zz_permissions di alcuni riferimenti al vecchio modulo marketing presente nel OSM V1 (almeno nella mia versione). Ma potrebbe essere anche stato una vecchia problematica di update da parte mia.  
L'errore  è  il seguente : 

error 1452 cannot add or update a child row

A causarlo e stato la riga 661 in 2_3.sql : 

-- Aggiunta di chiavi esterne in zz_permissions
ALTER TABLE `zz_permissions` ADD FOREIGN KEY (`idmodule`) REFERENCES `zz_modules`(`id`) ON DELETE CASCADE, ADD FOREIGN KEY (`idgruppo`) REFERENCES `zz_groups`(`id`) ON DELETE CASCADE;

**Comment by Dasc3er** [comment]
@loviuz Questa tabella era presente in ogni installazione della versione 1?
Se si, avrebbe senso inserire un DROP specifico nell'aggiornamento alla versione 2.3?

**Comment by lepool** [comment]
Se puo essere d'aiuto io ho fatto l'update dalla versione 1.1.8RC2 alla 2.0 e poi alla 2.3

**Comment by loviuz** [comment]
il modulo marketing mi sembrava fosse stato inserito nella 1.1.8, poi dismesso, quindi attualmente le tabelle mk_* si possono togliere

**Comment by Dasc3er** [comment]
Ed era presente anche una tabella **zz_permissions**?

**Comment by Dasc3er** [comment]
@loviuz Ed era presente anche una tabella **zz_permissions**?

**Comment by lepool** [comment]
Forse verificando in nel file 2_3.php con una procedure si riescono a prevenire eventuali riferimenti a moduli inesistenti e cancellarli in automatico. 

Io ho trovato i record nella seguente maniera : 

SELECT COUNT(*),idmodule
FROM zz_permissions AS a
LEFT OUTER JOIN zz_modules AS q ON a.idmodule = q.id
WHERE q.id IS NULL

Ho cancellati i record in questione et voila , l'update va avanti. 
Questa è un idea e non so se il problema si presenta anche ad altri utenti.

**Comment by Dasc3er** [comment]
@lepool Quindi erano presenti dei permessi non legati ad un modulo specifico...
@loviuz Questi permessi inutilizzati si possono rimuovere, considerando che sono originati dalla procedura di migrazione dalle prime versioni e non sono utilizzati?

**Comment by lepool** [comment]
Si,erano presenti ldei permessi ad un modulo non più esistente.

**Comment by Dasc3er** [comment]
@lepool Potresti provare l'aggiornamento dalla versione 1 aggiungendo la seguente query nella riga 661 del file **update/2_3.sql**?
```sql
DELETE FROM `zz_permissions` WHERE `idmodule` IS NULL;
```

Questo dovrebbe equivalere all'operazione da te eseguita per permettere l'aggiornamento, e non influenzerebbe in modo eccessivo la procedura...

**Comment by lepool** [comment]
Scusa @Dasc3er , ma i valori in zz_permissions non sono NULL ma hanno da me per esempio il valore 19.

L'unico modo per trovarli è fare la query indicata sopra da me, perche non è NULL il valore di idmodule in zz_permissions , ma non esiste la referenza del valore indicato in zz_permissions in zz_modules.

**Comment by Dasc3er** [comment]
@lepool Scusa, errore mio!
Ecco la query aggiornata:
```
DELETE FROM `zz_permissions` WHERE `idmodule` NOT IN (SELECT `id` FROM `zz_modules`);
```

**Comment by lepool** [comment]
Ho un altro problema in api.php nella cartella update : 

[2018-01-13 14:18:28] Logs.EMERGENCY: SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause - ALTER TABLE `an_anagrafiche` ADD `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

Strano che non me lo sia segnato come errore. Probabilmente avevo corretto il database a mano per poter vedere la funzionalità dell' OSM V2.3 o ci sono stati dei passaggi intermedi.

**Comment by lepool** [comment]
MA la api funziona correttamente solo con MYSQL versione 5.6.5?

**Comment by Dasc3er** [comment]
@lepool Sì, effettivamente questa particolarità non è ancora stata documentata completamente...
In pratica, per il funzionamento corretto dell'API sono stati introdotti i campi `created_at` e `updated_at` che vengono gestiti in automatico da MySQL; questo però ha portato alla necessità di richiedere una versione di MySQL => 5.6.5 per poter utilizzare l'API.

E' però strano che si sia verificato questo problema, poiché la query che provoca l'errore presente nei log viene seguita solo se MySQL è compatibile...
Potresti specificare la versione MySQL in utilizzo?

**Comment by lepool** [comment]
No, allora il problema è solo mio. Ho mysql 5.5.8 installato e ho temporaneamente modificato la stringa per la compatibilità. Ora chiaramente nel mio mysql non è supportato la funzione richiesta nell' api.php in update. provvedo e poi rirovo. Errore mio.

**Comment by lepool** [comment]
Ho apportato le modifiche nel [pull-request](https://github.com/devcode-it/openstamanager/pull/113) provato e funzionante.
