### ISSUE TITLE
Un tecnico non riesce ad aprire un attività a lui assegnata se non sono presenti sessioni per esso

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#970]
## Comportamento richiesto

Un tecnico assegnato dovrebbe essere abilitato ad accedere ad un interevnto a lui assegnato.

## Comportamento attuale

Il tecnico puo accedere all'attività solamente se ci sono presenti sessioni

## Possibile soluzione

Modifica della "clause" per i tecnici nel modulo attività in maniera che possa accedere alle attività assegnate . 
```sql
UPDATE `zz_group_module` SET `clause` = ' (in_interventi.id IN (SELECT idintervento FROM in_interventi_tecnici WHERE idintervento=in_interventi.id AND idtecnico=|id_anagrafica|) OR \r\n in_interventi.id IN (SELECT id_intervento FROM in_interventi_tecnici_assegnati WHERE id_intervento=in_interventi.id AND id_tecnico=|id_anagrafica|))\r\n' WHERE `zz_group_module`.`name` = 'Mostra interventi ai tecnici coinvolti';
```

## Passi per riprodurre il comportamento

1. Creo un attività senza sessioni per tecnici
2. assegno l'attività ad un tecnico
3. accedo come utente tecnico al quale è stato assegnato l'attività 

* Modulo: attività
* Versione del progetto: 2.4.23

**Comment by Dasc3er** [comment]
Grazie mille per la segnalazione e la soluzione indicata! 😄
