### ISSUE TITLE
BUG: Modifica dettagli listino fornitori

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#971]
## Comportamento attuale
Se vado a modificare un dettaglio nel plugin listino fornitori (modulo articoli) mi viene restituito un errore (vedi log)
[error.log](https://github.com/devcode-it/openstamanager/files/6899952/error.log)

## Passi per riprodurre il comportamento

Creare un articolo
Nel plugin listino fornitori inserire un record
Modificare il record e salvare

* Modulo: ARTICOLI plugin Listino fornitori
* Versione del progetto: OSM 2.4.24

**Comment by Dasc3er** [comment]
@idraulicadueci Il campo Descrizione è obbligatorio, pertanto l'errore indicato è corretto.
Sembra che per qualche motivo non hai impostato il contenuto del campo oppure non è stato salvato.

**Comment by idraulicadueci** [comment]
è probabile. Adesso il problema non si è ripresentato
