### ISSUE TITLE
Si è verificato un'errore [uid: 61a0ab2]. 

### ISSUE THREAD

**Issue by rmoggia** [devcode-it/openstamanager#972]
Da stamattina ricevo dopo il login questo messaggio di errore. Lo ricevo 35 volte. Il codice cambia ad ogni tentativo.
Ho provato a ripristinare copie precedenti ma niente. Persiste. Sullo stesso host ho anche altre installazioni di OSM stessa versione che funzionano. Ho controllato il db e sembra ok. Allego il log.
Grazie
[error.log](https://github.com/devcode-it/openstamanager/files/6900757/error.log)

* Modulo:
* Versione del progetto: 2.4.9
* Versione PHP: 7.4
* Tipo di server: hosting

**Comment by Dasc3er** [comment]
Ciao @rmoggia,
è strano che il problema si verifichi da un momento all'altro, senza modifiche ai file del gestionale.
Potresti provare ad aggiornare a una versione più recente, se non hai particolari personalizzazioni?
La 2.4.9 è al momento vecchia di circa 2 anni, quindi diversi bug relativi potrebbero essere stati risolti. In alternativa, potresti provare ad estrarre dall'archivio ZIP della 2.4.9 la cartella vendor/ per ripristinare eventuali file corrotti.

Potresti inoltre fare un test sul forum? Nella giornata di ieri è stato effettuato l'aggiornamento alla piattaforma Flarum, che dovrebbe essere più semplice da usare e avanzata. Per accedere, è necessario prima effettuare un recupero password: se ci sono problemi potresti segnalarlo?
