### ISSUE TITLE
Problema Gestione Seriali 2.4.23

### ISSUE THREAD

**Issue by Frostbyte91** [devcode-it/openstamanager#973]
Riscontro un problema con la gestione dei seriali, in particolar modo quando inserisco un articolo in un'attività.
Nella scelta del prodotto la quantità disponibile risulta corretta, ma quando vado ad inserire il seriale mi vengono mostrati sia quelli disponibili sia quelli già impegnati in altre attività.

La problematica si è verificata da quando ho aggiornato il programma dalla versione 2.4.19 alla versione 2.4.23.

**Comment by Dasc3er** [comment]
Il problema è presente dalla versione 2.4.23 ed è causato da questo commit: https://github.com/devcode-it/openstamanager/commit/472c88889c3a076cc51519187491636d72b391d7#diff-768a413b4821a6982175696721590740711b2b12b29c74182584c0ce8389f668,
E' al momento in corso una verifica della funzionalità, e abbiamo ricevuto una segnalazioni simile dal forum: https://forum.openstamanager.com/d/2038-inserimento-seriale-in-ddt

Grazie per le segnalazioni!

**Comment by MatteoPistorello** [comment]
Abbiamo risolto il problema descritto con il seguente commit: https://github.com/devcode-it/openstamanager/commit/3a33def351fc13237b1ccec5280042701acd2a51
