### ISSUE TITLE
Filtri su viste nascosti

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#975]
## Comportamento richiesto

Mantenere la visualizzazione del filtro applicato

## Comportamento attuale

Se applico un filtro e accedo al record filtrato, tornando alla vista principale continuo a vedere i dati filtrati, ma non il filtro; l'unico sistema per rivedere tutti i dati è cercare di ricordare su quale colonna ho inserito il filtro, cliccarci e dare invio.

## Passi per riprodurre il comportamento

Aprire per esempio il modulo anagrafiche.
inserire un filtro sulla colonna "ragione sociale"
Cliccare su uno dei dati filtrati
Cliccare su "torna all'elenco" o "indietro"

OSM 2.4.24

**Comment by Dasc3er** [comment]
Ciao, grazie per la segnalazione!
Il problema è relativo a un bug più generale del codice JS dell'ultima versione, già risolto nella versione in sviluppo.
Puoi trovare la soluzione ufficiale qui: https://forum.openstamanager.com/d/2017-osm-2424-28072021/5

**Comment by idraulicadueci** [comment]
Con la modifica apportata, adesso funziona correttamente. Grazie.
