### ISSUE TITLE
MIGLIORIA: sede diversa in fattura elettronica

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#977]
## Comportamento richiesto

Esistendo la possibilità di indicare in fattura (non elettronica) la sede di destinazione ("Destinazione diversa") (vedere issue #950), sarebbe utile poter ritrovare l'informazione in fattura elettronica come riga descrittiva

## Comportamento attuale

Nella stampata della fattura è possibile riportare una sede diversa da quella legale, ma questo dato non è visibile in fattura elettronica

## Possibile soluzione

Riportare il dato come riga descrittiva nel corpo della fattura elettronica (per es. "Destinazione fattura Via G. Verdi, 1 .....") oppure poter inserire nelle impostazioni una dicitura personalizzata a cui accodare sul documento elettronico i dati della sede di destinazione.

**Comment by loviuz** [comment]
@idraulicadueci puoi provare con la 2.4.24? Dovremmo aver risolto lasciando nella stampa PDF in "Spett.le" i dati dell'azienda principale e se specificata una sede diversa questa appare subito sotto nel riquadro "Sede diversa", come nei ddt.

**Comment by idraulicadueci** [comment]
@loviuz nella stampata cartacea già funziona, la miglioria che indicavo è relativa alla fattura elettronica
