### ISSUE TITLE
Listino fornitore

### ISSUE THREAD

**Issue by Frostbyte91** [devcode-it/openstamanager#978]
Ciao a tutti, riscontro problemi con il plugin dell'inserimento del fornitore negli articoli. 
Effettuo l'inserimento, e il prezzo ma dopo il salva non ho nessuna modifica, anzi se mi sposto al plugin "listino clienti" mi trovo lì la modifca.

Suggerimenti? 

Grazie e buon lavoro.

**Comment by Dasc3er** [comment]
Ciao @Frostbyte91 , grazie per la segnalazione!
In effetti si tratta di un bug nella creazione dei Listini Fornitori, che vengono sempre creati come Listini Cliente. 
Il bug è stato risolto con questo commit: https://github.com/devcode-it/openstamanager/commit/fe2117f26b62ffa0357d216035411b8c01e1b519

Se desideri, puoi modificare la colonna `dir `della tabella `mg_prezzi_articoli` con il valore `uscita` per la riga di interesse, oppure provare di nuovo dopo aver applicato le modifiche.

**Comment by Frostbyte91** [comment]
Ciao @Dasc3er, grazie per la risposta rapidissima! Ti terrò aggiornato! 

Grazie mille

**Comment by Frostbyte91** [comment]
Grazie risolto!
