### ISSUE TITLE
BUG: Pulsante +DDT in fatture di acquisto non funziona

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#979]
## Comportamento attuale

Creando una nuova fattura, il pulsante +DDT è attivo, ma non apre la scheda di selezione DDT evasi.

* Modulo: Fatture di acquisto
* Versione del progetto: OSM 2.4.24

**Comment by Dasc3er** [comment]
Grazie per la segnalazione! Il problema è stato segnalato e risolto qui: https://github.com/devcode-it/openstamanager/commit/d0f2746d01a41dfc85df11c2eac82cbc728552b0
