### ISSUE TITLE
FATTURE - Arrotondamenti IVA errati

### ISSUE THREAD

**Issue by fgambarelli** [devcode-it/openstamanager#98]
La somma dell'IVA non corrisponde esattamente, ci sono 0,02 cent di differenza..
![image](https://user-images.githubusercontent.com/34273200/34614498-f75c9888-f231-11e7-8c8d-bf60869f2be6.png)
Facendo le somme con excel, sia degli importi a video, sia delle righe dettaglio della tabella co_righe_documenti, il totale viene giusto.
![image](https://user-images.githubusercontent.com/34273200/34614805-f4b1ecb8-f232-11e7-9025-8cef5eb607ae.png)
Non di 46,69 ma di 46,72

**Comment by Dasc3er** [comment]
@fgambarelli Grazie per la segnalazione!
Effettivamente si trattava di un errore di approssimazione (per la precisione, non veniva effettuata correttamente).

**Comment by loviuz** [comment]
Prova a vedere con quest'ultimo commit, ho ricreato la stessa fattura. Ho risolto l'iva anche nel piano dei conti, dove non veniva arrotondato il calcolo correttamente
