### ISSUE TITLE
Aggiornamento 2.4.24 a 2.4.25

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#981]
Ciao a tutti,

ho caricato lo zip di aggiornamento poco fa dalla versione 2.4.24 e ora non arriva più a Login con questo errore a video su pagina bianca:

Fatal error: Uncaught Error: Class "ComposerAutoloaderInit8559ee9663fe71c2001294952170d041" not found in /var/www/html/vendor/autoload.php:7 Stack trace: #0 /var/www/html/core.php(42): require_once() #1 /var/www/html/index.php(21): include_once('/var/www/html/c...') #2 {main} thrown in /var/www/html/vendor/autoload.php on line 7

Vedo se riesco a capirci qualcosa

PHP 8.0.9 (cli)
Server version: Apache/2.4.38 (Debian)
MySQL 5.7.32

**Comment by cigo76** [comment]
> Ciao @leonardocalabretta ,
> puoi provare a cancellare completamente la cartella vendor/ ed estrarla manualmente dall'archivio della versione 2.4.25?

Problema risolto!!
Ma esce una scritta/errore: (Attenzione! Ci sono delle tabelle non previste nella versione standard del gestionale: my_impianto_componenti.)

**Comment by Dasc3er** [comment]
@cigo76 Tranquillo, il warning al momento è corretto perchè sono state effettuate alcune modifiche ai Componenti degli Impianti, che ora sono gestiti in una tabella diversa. La tabella vecchia (`my_impianto_componenti` appunto) è al momento stata mantenuta per risolvere eventuali problemi se si verificano durante il passaggio dei dati al nuovo formato.
