### ISSUE TITLE
Miglioria - Regimi fiscali per Cassa - Data Competenza

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#982]
## Comportamento richiesto

I regimi fiscali per cassa devono, secondo me, basarsi su data competenza sopratutto in fatture di vendita e acquisto

## Comportamento attuale

Il gestionale attualmente da per scontato che tutti i regimi fiscali lavorino basandosi sulla data di emissione mentre per i regimi "per cassa" bisogna basarsi su quello. Quindi anche tutte le stampe, report, ecc ecc, in base al regime fiscale dovrebbero prendere in esame la data emissione o la data competenza. Magari con un flag da qualche parte nell'anagrafica

**Comment by Dasc3er** [comment]
Segnalazione forum di riferimento: https://forum.openstamanager.com/d/2048-data-competenza
