### ISSUE TITLE
BUG - 2.4.24 - Fattura Accompagnatoria

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#983]
## Comportamento richiesto

Dovrei poter tornare a Bozze anche se non ho compilato i dati di "Dati Fattura accompagnatoria" mentre ora non me lo fa fare.

## Comportamento attuale

Ho creato una fattura accompagnatoria e l'ho messa in stato "Emesso". Mi sono però accorto di non aver compilato la sezione "Dati Fattura accompagnatoria" ma una volta in stato Emesso giustamente non posso farlo. Cerco di rimetterla in stato "Bozze" ma non posso perchè sotto "Vettore" mi compare "Questo valore è richiesto." e non posso tornare a Bozze.
Dovrebbe invece esser possibile farlo 

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Fatturazione Attiva
* Versione del progetto: 2.4.24
* Versione PHP: 8
* Tipo di server: 2.4

**Comment by Dasc3er** [comment]
@leonardocalabretta Come hai fatto a mettere in stato **Emessa** senza aver compilato il campo **Vettore**?

**Comment by leonardocalabretta** [comment]
Niente di particolare. Me l'ha fatto fare

**Comment by Dasc3er** [comment]
Se provo con una nuova Fattura accompagnatoria, devo obbligatoriamente inserire un Vettore, Per fare le modifiche con la fattura problematica, ti consiglio di accedere direttamente al database e modificare `idstato `della tabella `co_documenti `per il record di interesse.
A quanto sono riuscito a vedere, il passaggio non è possibile con un semplice salvataggio delle modifica alla fattura, quindi se riesci a replicare il malfunzionamento potresti indicarne i dettagli?
