### ISSUE TITLE
BUG: Modulo invio documenti non prende indirizzo e-mail

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#984]
## Comportamento attuale

Se invio un documento nella casella destinatario non ho l'elenco dei destinatari inseriti in anagrafica.
Ho correttamente inserito i referenti nelle varie sedi indicate

## Passi per riprodurre il comportamento

Aprire un documento (io ho provato con ordini fornitore)
Cliccare INVIA.
Il capo destinatari è vuoto e se lo apro, l'elenco a discesa è vuoto

OSM 2.4.25

**Comment by idraulicadueci** [comment]
Informazione aggiuntiva: prende solo l'indirizzo e-mail principale dell'anagrafica

**Comment by Dasc3er** [comment]
Ciao @idraulicadueci ,
ho appena effettuato un test come hai indicato. Con un Fornitore dove è segnato l'indirizzo email, la scheramta di invio email compila correttamente il destinatario predefinito. L'elenco a discesa viene quindi visualizzato alla digitazione di alcune lettere, e mostra gli indirizzi email di referenti che contengono le lettere indicate.
Puoi verificare di avere impostato correttamente l'anagrafica?

**Comment by idraulicadueci** [comment]
Ciao, grazie della risposta,
ho fatto le seguenti prove:

- Inserito indirizzo principale (scheda principale anagrafica) e indirizzo referente per quella sede. Mi dà soltanto indirizzo principale
- Tolto indirizzo principale e lasciato indirizzo referente per quella sede, non mi elenca nessun indirizzo
- Indicato referente nel modulo ordini, mi restituisce indirizzo referente

In poche parole, l'unico sistema per avere un indirizzo nel campo destinatario, è indicare il referente nel modulo ordini o indicare una mail principale.

Provo a fare un'installazione pulita e ti aggiorno.

**Comment by idraulicadueci** [comment]
Nell'installazione precedente avevo un file custom (variable.php) dove avevo inserito la riga

` 'ragione_sociale' => $r['ragione_sociale'],` che funzionava correttamente

La cosa strana è che se modifico il file variables.php originale o la copio nella cartella custom si presenta il problema, mentre se ripristino il file custom dell'installazione precedente (quello da me modificato) il problema scompare. Ovviamente la modifica fatta nel file originale non funziona.

Alla fine il problema si risolve cancellando la cartella custom e il file variables.php modificato e sovrascrivendo la cartella ordini con i file originali della versione 2.4.25.
Sarebbe utile sapere come fare la modifica delle variabili
