### ISSUE TITLE
BUG listino fornitore

### ISSUE THREAD

**Issue by idraulicadueci** [devcode-it/openstamanager#985]
## Comportamento attuale

Se provo a modificare il dettaglio in un listino fornitori, invece del campo editabile mi compare

`{[ "type": "textarea", "label": "Descrizione", "name": "descrizione", "required": 1, "value": "DESCRIZIONE" ]}
`
e quindi non è possibile effettuare la modifica.
L'unica soluzione è eliminare il dettaglio e ricrearlo.

OSM 2.4.25

**Comment by idraulicadueci** [comment]
Cosa strana è che lo fa con alcuni articoli e con altri no.

**Comment by Dasc3er** [comment]
@idraulicadueci La descrizione degli articoli contiene delle virgolette doppie (")?

**Comment by idraulicadueci** [comment]
Sì, è il simbolo delle misure in pollici. È lì il problema. Se poi vado a eliminare il dettaglio che dà l'anomalia, non viene eliminato completamente, ma resta il nome del fornitore con il pulsante per la definizione del prezzo.
Inserendo un nuovo dettaglio con lo stesso fornitore e una descrizione senza ", il problema scompare.
Se non esiste una soluzione, mi limito a inserire ' al posto di ".
L'importante era capire dove fosse la magagna.
Grazie per l'aiuto.

**Comment by idraulicadueci** [comment]
Ciao, ho fatto una prova con la modifica indicata nel commit [https://github.com/devcode-it/openstamanager/commit/10d6b8c9a7e00c5bb302ad1791f584df25397e08](https://github.com/devcode-it/openstamanager/commit/10d6b8c9a7e00c5bb302ad1791f584df25397e08)
Adesso il problema non si è presentato. Grazie.
