### ISSUE TITLE
Caricamento allegati non funziona

### ISSUE THREAD

**Issue by DevClimb** [devcode-it/openstamanager#986]
Dopo l'aggiornamento non funziona il caricamento degli allegati e la barra laterale dei plugin rimane sempre attiva andando a nascondere parte della schermata

**Comment by DevClimb** [comment]
Dopo l'aggiornamento non funziona il caricamento degli allegati e la barra laterale dei plugin rimane sempre attiva andando a nascondere parte della schermata

**Comment by Dasc3er** [comment]
@DevClimb Hai provato a cancellare la cache del browser?
Puoi inoltre controllare dal modulo Aggiornamenti che i file siano stati sostituiti correttamente tramite un Controllo di integrità?

**Comment by DevClimb** [comment]
Ho eliminato la cache del browser e del server, ho provato a reinstallare manualmente i file ma non si risolve. Se provo l'integrità dei file trovo i seguenti errori: CHANGELOG.md e .vscode/launch.json. Per il resto non mi segnala nessun errore. Grazie

**Comment by DevClimb** [comment]
Sembrerebbe un problema dovuto al file function.min.js

**Comment by loviuz** [comment]
Ciao @DevClimb, riscontri ancora il problema con le versioni più recenti?

**Comment by DevClimb** [comment]
Il problema è stato risolto.
Grazie
Nicola Zatta
DevClimb
e-commerce web design business analysis
Tel. +39 379 2543890
www.devclimb.com
email: ***@***.***
