### ISSUE TITLE
Mancanza Banca in stampa preventivi quando l'anagrafica cliente ha una banca specifica

### ISSUE THREAD

**Issue by marcus905** [devcode-it/openstamanager#988]
## Comportamento richiesto

Nel caso si specifichi una banca speciale in un anagrafica, la stessa come compare nelle fatture PDF dovrebbe comparire anche nei preventivi.

## Comportamento attuale

Nelle fatture la banca compare correttamente, mentre nei preventivi non compare.

![reg](https://user-images.githubusercontent.com/392762/134138783-5f990fb6-6880-4d2e-a044-5f32c5c618ce.png)

![prv](https://user-images.githubusercontent.com/392762/134138824-d29cc385-a4d0-4add-b684-5350e80130a3.png)

![ftt](https://user-images.githubusercontent.com/392762/134139236-c10e6bf1-cc4f-490c-a303-2c980d9feff0.png)

## Possibile soluzione

Probabilmente c'è un'errore nella query che carica il conto, diversa tra modulo preventivi e fatture. Non ho purtroppo avuto tempo di analizzarla con precisione ancora.

## Passi per riprodurre il comportamento

1. Assegna un conto predefinito per accrediti all'anagrafica
2. Produci un preventivo PDF
3. Nella stampa non è riportata la banca come da screen

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: preventivi
* Versione del progetto: 2.4.24
* Versione PHP: 7.2
* Tipo di server: Aruba, apache 2

**Comment by Dasc3er** [comment]
Ciao @marcus905 grazie per la segnalazione!
Ho effettuato un fix sulla stampa che risolve un problema nell'individuazione della stampa, ma non credo sia legato al problema in questione (https://github.com/devcode-it/openstamanager/commit/17d5fd8df3d1c78dc592c234d2bb9f1e6b7af4d5).
Nello specifico, la stampa visualizza la banca predefinita solo se è associata a un Conto (modulo **Banche**) che corrisponde al Conto del Pagamento (modulo **Pagamenti**) del Preventivo che stai stampando.

**Comment by marcus905** [comment]
Sistemando i conti predefiniti senza il tuo fix nel commit di sopra (mettendo entrambi i conti bancari come predefiniti su Banca C/C) nei due moduli Pagamenti e Banche purtroppo applica sempre il primo dei due conti, indipendentemente da quale dei due è sull'anagrafica o è predefinito.

Sto tentando di applicare il fix che hai committato sul server, pochi minuti e ti aggiorno sulla sua risolutività.

Grazie mille!

**Comment by marcus905** [comment]
(aggiungo che anche se le modifiche sono state salvate nel modulo Banche, il browser avvisa sempre che le modifiche verranno perse se si abbandona la pagina)

**Comment by marcus905** [comment]
Confermo, non cambia il preventivo dopo quel fix. Rimangono vuoti i campi nella stampa

**Comment by Dasc3er** [comment]
@marcus905 Puoi verificare con il commit https://github.com/devcode-it/openstamanager/commit/9ab649ff72efd0ec4e45c4f6f30f8e6c9c8b0c73?
Ho rivisto la logica di selezione della Banca, che ora dovrebbe prevedere correttamente tutti i casi necessari.

**Comment by Dasc3er** [comment]
Per i Preventivi la logica di individuazione della Banca è al momento la seguente.

Dato il Pagamento del Preventivo, viene ricercata la Banca dell'Azienda impostata come predefinita per l'anagrafica Cliente.
Se il conto del Pagamento e della Banca non corrispondono, viene cercata la prima banca in ordine di priorità tra quelle dell'Azienda con il Conto corrispondente al Pagamento.

Infine, se il Pagamento è Ri.Ba. viene mostrata la banca predefinita per il Cliente.

**Comment by marcus905** [comment]
Ciao, verificato. Sembra funzionare correttamente tutto ora. Per il momento ti ringrazio, se dovesse ricapitare aggiungo un commento.

**Comment by Dasc3er** [comment]
Nel caso si verificasse di nuovo il problema, per favore crea una nuova issue e indica questa come riferimento precedente.
