### ISSUE TITLE
BUG: Dopo aggiornamento 2.4.21 > 2.4.25 il valore "Netto a pagare" è stampato errato nella vista Fatture di vendita

### ISSUE THREAD

**Issue by ettoreperri** [devcode-it/openstamanager#989]
## Comportamento richiesto

Nella lista ci si aspetta che venga stampato il totale netto a pagare della fattura.

## Comportamento attuale

Nel caso in cui in fattura sono presenti voci con valore negativo(non indicate come sconto), queste nella vista non vengono detratte ma aggiunte al totale. Il problema si è verificato dopo l'aggiornamento da 2.4.21 a 2.4.25

## Possibile soluzione

Nell'esportazione del CSV la stampa avviene correttamente

## Passi per riprodurre il comportamento

Creando una fattura il cui totale è 992.50€ ed è presente tra le voci una con valore -2314 €

![Schermata da 2021-09-29 17-18-10](https://user-images.githubusercontent.com/36436650/135298686-8018b8c7-4162-44d3-b063-9daf414ede97.png)
 nella vista sarà mostrato come Netto a pagare il valore equivalente a 992.50+2314+2314 = 5620.50€
![Schermata da 2021-09-29 16-56-11](https://user-images.githubusercontent.com/36436650/135298515-c74a236f-068f-4aea-b36b-2f53f136dd37.png)

## Contesto

* Modulo: Vista Fatture di Vendita
* Versione del progetto: 2.4.26
* Versione PHP: 7.2
* Tipo di server: LAMP

**Comment by ettoreperri** [comment]
BUG ANCORA PRESENTE IN VERSION 2.4.27!

**Comment by loviuz** [comment]
con i commit di qualche giorno fa dovremmo aver risolto definitivamente. hai modo di provare a reimportare la fattura aggiornando la tua versione? in alternativa dovrebbe bastare aggiornare la cartella plugins/importFE/

**Comment by ettoreperri** [comment]
Non ho capito che intendi. Non ho mai importato alcuna fattura, il problema è nella vista di tutte le fatture di vendita...

**Comment by lepool** [comment]
Io avevo notato nella mia installazione il valore netto a pagare alterato nel riepilogo fattire di vendita avendo inserito per sbaglio lo sconto finale. La cosa strana è che tale sconto non veniva calcolato nella fattura, ma solo nella vista delle fatture del modulo.
