### ISSUE TITLE
bug dopo aggiornamento a vesione 2.4.26

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#990]
Dopo l'aggiornamento alla versione 2.4.26 appare una notifica che riporta: Hook "Informazioni su Services" in esecuzione.
 Configurazione per l'accesso Services non completata correttamente. Per abilitare i servizi, compilare l'impostazione "OSMCloud Services API Token". 
 - è un bug o devo effettuare delle modifiche manuali per un funzionamento ottimale del programma

* Versione PHP: 7.2.10

**Comment by lucasalva87** [comment]
Il funzionamento del gestionale non viene pregiudicato in alcun modo quindi non è un bug. Sembra semplicemente un mancato controllo sull'impostazione. Grazie per la segnalazione.

**Comment by Dasc3er** [comment]
@leo-spa La soluzione al problema dovrebbe essere indicata in questo commit: https://github.com/devcode-it/openstamanager/commit/107229de443efe466c302cc94a31434b24aad261

**Comment by leo-spa** [comment]
ho provato ad effettuare le modifiche riportate, ma non hanno dato esito positivo, permane la notifica
