### ISSUE TITLE
account di posts smtp, versione 2.4.26

### ISSUE THREAD

**Issue by leo-spa** [devcode-it/openstamanager#991]
non funziona nessun server di posta inserito, seguendo le istruzioni nella guida, ho provato anche quello di google ma il sistema dice: Connessione SMTP fallita
Impossibile connettersi all'account SMTP

smtp.gmail.com
porta 587
sicurezza tls

ho fatto un test anche con la sicurezza ssl ma il messaggio è uguale

    Versione PHP: 7.2.1

**Comment by loviuz** [comment]
Ciao @leo-spa, il problema è abbastanza anomalo perché qualsiasi server dovrebbe funzionare. Su quello di Google magari ci può essere qualche noia perché serve attivare OAuth o creare una password specifica per l'applicazione. Con quali SMTP hai provato? Credo sia comunque un problema non legato al gestionale.
