### ISSUE TITLE
Il modulo impianti - componenti alla versione 2.4.27 non funziona

### ISSUE THREAD

**Issue by lepool** [devcode-it/openstamanager#995]
Aggiungendo componenti mi compare la maschera aggiuta articolo e nella selezione compare solamente il primo articolo inserito nel database. 
Non ho ancora provato con una versione pulita. Il problema mi compare però su piu installazioni aggiornate.

**Comment by kenchu84** [comment]
Idem. ho fatto installazione pulita...

**Comment by lepool** [comment]
@loviuz c'è una descrizione o un diagramma di come dovrebbe funzionare il modulo per poter eventualmente contribuire?

**Comment by lepool** [comment]
con il commit  8806304 il problema degli articoli nel select sembra risolto.

**Comment by loviuz** [comment]
@lepool non abbiamo ancora ben documentato il funzionamento. Comunque di base permette di collegare degli articoli agli impianti rispetto a prima che erano dei file .ini.

**Comment by lepool** [comment]
Ma si pensava ad una maschera di immissione come quella precedente per quanto riguarda i dati di eventuali componenti, per esempio modelli e matricole dei componenti oppure altri dati che riguardano i componenti?

**Comment by loviuz** [comment]
Per ora no, nel senso che rimangono piú che altro di collegamenti ad articoli, senza campi dinamici, però se c'é qualche suggerimento di come migliorarli ben venga.
