### ISSUE TITLE
BUG: Problema configurazione mail quando presente &

### ISSUE THREAD

**Issue by kalipso52** [devcode-it/openstamanager#999]
## Comportamento richiesto
La passowrd dell'account email deve poter contenere il carattere &

## Comportamento attuale
Attualmente se la password contiene il catattere & l'autenticazione fallisce

## Passi per riprodurre il comportamento

1. Configurare account mail per aruba business
2. Porta 587
3. server smtp: mail.miodominio.it
4. disattivare controllo ssl 

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Mail
* Versione del progetto: 2.4.27 
* Versione PHP: 7.3.32
* Tipo di server: Linux su aruba business

**Comment by Pek5892** [comment]
Non viene accettato il carattere '&' neanche nel config se incluso nella password del database.

**Comment by cristianviale** [comment]
Ho lo stesso problema, non è mai stato risolto?

**Comment by cristianviale** [comment]
Ho dato un'occhiata: il problema è che il carattere "&" nel database viene salvato come "&amp;".

**Soluzione:**
Per evitare di modificare il modo in cui le password vengono salvate nel database, si può apportare una modifica in src → Notifications → EmailNotification.php, nel metodo __construct().

Bisogna sostituire la riga
$this->Password = $account['password'];
con
$this->Password = html_entity_decode($account['password']);

**Comment by Pek5892** [comment]
Ciao @cristianviale, grazie per il suggerimento ma abbiamo deciso di risolverlo in un'altro modo:
https://github.com/devcode-it/openstamanager/commit/31c5199be6b03baa7e25b8695944a0bb116af5e0
